### PR TITLE
gradle upgrade

### LINKED ISSUE #7382: custom task named 'wrapper' has been deprecated
in "Configure project "

Creating a custom task named 'wrapper' has been deprecated. This is scheduled to be removed in Gradle 5.0. You can configure the existing task using the 'wrapper { }' syntax or create
 your custom task under a different name.
        at build_w5tx7p2bosgsq4d6b4f13ifv.run(C:\StudioProjects\cgeo\build.gradle:186)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

### PR DESCRIPTION
**Pull request by bekuno**
- Upgrade gradle to 5.3
  -> updated jar (by wrapper)
  -> updated gradle scripts (by wrapper)
- build.gradle
  - wrapper task configuration for gradle 5.x
  - new license configuration for gradle log upload

fix #7382

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Please add this to gradle.properties:
`org.gradle.internal.launcher.welcomeMessageEnabled=false`
Otherwise gradle now prints release notes every first time on a machine (which might be everytime on a clean CI system), as visible in your PR console output. See https://github.com/gradle/gradle/issues/5213

That being said, I'm quite surprised the build is green, since gradle 4.x said that some of our methods would no longer work with 5.x. But they are still shown as deprecated and to be removed, instead of failing.

**Comment by bekuno** [comment]
> Please add this to gradle.properties:
> `org.gradle.internal.launcher.welcomeMessageEnabled=false`
> Otherwise gradle now prints release notes every first time on a machine (which might be everytime on a clean CI system), as visible in your PR console output. See [gradle/gradle#5213](https://github.com/gradle/gradle/issues/5213)

If I read the gradle#5213 right then this situation is already in the current gradle version.
Then you can add it already in your PR #7427 .

My PR was the first with gradle 5.3 (see download before), so I assumed so far that the download and the welcome message do not occur again with this configuration at the new start.

How can I initiate a new jenkins run (without code change)?

**Comment by bekuno** [comment]
The build has a strange checkstyle error:

23:11:12  Execution failed for task ':main:checkstyle'.
23:11:12  > Could not resolve all files for configuration ':main:checkstyle'.
23:11:12     > Could not find com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava.
23:11:12       Searched in the following locations:
23:11:12         - file:/opt/android-sdk-linux/extras/m2repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom
23:11:12         - file:/opt/android-sdk-linux/extras/m2repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
23:11:12         - file:/opt/android-sdk-linux/extras/google/m2repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom
23:11:12         - file:/opt/android-sdk-linux/extras/google/m2repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
23:11:12         - file:/opt/android-sdk-linux/extras/android/m2repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom
23:11:12         - file:/opt/android-sdk-linux/extras/android/m2repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
23:11:12         - https://repo.maven.apache.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom
23:11:12         - https://jcenter.bintray.com/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom
23:11:12         - https://jitpack.io/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom
23:11:12         - https://jitpack.io/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
23:11:12         - https://dl.bintray.com/alexeydanilov/maven/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom
23:11:12         - https://dl.bintray.com/alexeydanilov/maven/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
23:11:12         - https://dl.google.com/dl/android/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom
23:11:12         - https://dl.google.com/dl/android/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
23:11:12       Required by:
23:11:12           project :main > com.puppycrawl.tools:checkstyle:8.17 > com.google.guava:guava:27.0.1-jre

But the first link
https://repo.maven.apache.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom
finds the configuration.
Can someone have a look on that?

**Comment by Bananeweizen** [comment]
Okay. I did not check the version when that behaviour started, I only noticed it in the output of your PR (which I looked into because I could not believe it was green, although we had deprecated methods). And I can also add it to my change, even though I created that one _after_ I commented here.

**Comment by Bananeweizen** [comment]
Regarding checkstyle you could force gradle to use the old version of checkstyle that was contained in 4.x, since it now uses a newer version by default: https://docs.gradle.org/current/release-notes.html#default-checkstyle-version-upgraded-to-8.17. Or you could even try explicitly setting a version in between, and try to find the highest without that issue.

However, that is of course not a solution, but just an avoidance of the warning. I have no clue what the checkstyle guys did with their curious dependency.

**Comment by bekuno** [comment]
> That being said, I'm quite surprised the build is green, since gradle 4.x said that some of our methods would no longer work with 5.x. But they are still shown as deprecated and to be removed, instead of failing.

I think this was only the change for the wrapper task.
This is also fixed in this PR. (As in yours)

**Comment by bekuno** [comment]
No checkstyle library dependency error with gradle 5.2.1.

**Pull request merged**
