### PR TITLE
Disable ocus

### PR DESCRIPTION
**Pull request by rsudev**

### CODE REVIEW

**Comment by rsudev** [comment]
Let's see what happens with this one...

**Comment by Lineflyer** [comment]
Looks like daniel recently changed his username but else seems fine :)

**Comment by rsudev** [comment]
Hmmm - for this we likely also have to change the test data. I'll have a look tomorrow.

**Comment by Lineflyer** [comment]
@rsudev I hope I did it right and saved you some work.
I did not squash the commits while merging as this are two unrelated changes in this PR

**Pull request merged**
