### PR TITLE
Remove some code duplication between map and new map

### PR DESCRIPTION
**Pull request by samueltardieu**
This attempts to remove some (not all, far from it) duplications between the existing map code and the "new" map.

Note that `liveEnabled` is still present in `mapOptions` and `mapState`. This mirrors the existing situation.

### CODE REVIEW

**Comment by samueltardieu** [comment]
retest this please

**Comment by samueltardieu** [comment]
retest this please

**Comment by samueltardieu** [comment]
please retest this

**Comment by samueltardieu** [comment]
retest this please

**Comment by SammysHP** [comment]
IMHO the new map code should stay independent as much as possible. Then it is easier to rewrite the code for new ideas instead of being stuck to the old implementation.

**Comment by samueltardieu** [comment]
Some common (and reusable) ideas have been extracted. No dependency on the new map from the old maps or on the old maps on the new map have been added.

The idea is to extract what is common to be able to also use it in version 2 of Google Maps API.

**Comment by samueltardieu** [comment]
retest this please

**Comment by rsudev** [comment]
I was initially also a little suspicious, but this refactoring is a very worthwhile improvement for both and does not hinder the new advance independently.
There is only one thing. If I read the change correctly, the maps will now be indistinguishable in the navigation menu and navigation menu settings.

**Comment by samueltardieu** [comment]
@rsudev You're right the label were indistinguishable in the original version. I have changed this one hour ago and updated the PR.

**Pull request merged**
