### PR TITLE
try to fix BRouter failing CI build

### PR DESCRIPTION
**Pull request by eddiemuc**
try to fix BRouter failing CI build

### CODE REVIEW

**Comment by moving-bits** [comment]
Ah, thanks. 

Can we restrict it to certain types of checks? All 64 messages stem from four types of checks, see https://ci.cgeo.org/job/cgeo%20pull%20request/5222/checkstyleResult/, "types" tab:

| type | # |
| --- | --- |
| EqualsHashCodeCheck | 1 |
| FinalParametersCheck | 25 |
| InnerAssignmentCheck | 10 |
| ParameterAssignmentCheck | 28 |

**Comment by eddiemuc** [comment]
@moving-bits let's first get the build green again asap and adjust details later...

**Comment by eddiemuc** [comment]
Ok, this seems to make the build "green", I will merge

**Comment by eddiemuc** [comment]
Created #10274 for adjusting suppression settings. Let's see if build becomes green (I have problems testing this local because of #10269 )

**Comment by moving-bits** [comment]
@eddiemuc 
Thanks for fixing this so fast!

**Pull request merged**
