### PR TITLE
Fix #12577 - Downgrade commons-lang3 to 3.11

### LINKED ISSUE #12577: Android 5 - Crash when opening cache details (NoClassDefError)
### Describe your problem!

While checking out `release` on an Android 5 (API 21) emulator I have a reproducible crash when trying to open a certain (but not all) stored cache.

### How to reproduce?

- Open stored list
- Click on the cache to open its details

### Actual result after these steps?

Crash

```
022-01-21 10:37:14.930 3662-3662/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 3662
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/StringJoiner;
        at org.apache.commons.lang3.StringUtils.join(StringUtils.java:4747)
        at org.apache.commons.lang3.StringUtils.join(StringUtils.java:4702)
        at org.apache.commons.lang3.StringUtils.join(StringUtils.java:4855)
        at cgeo.geocaching.utils.KeyableCharSet.<init>(KeyableCharSet.java:30)
        at cgeo.geocaching.utils.KeyableCharSet.<clinit>(KeyableCharSet.java:15)
        at cgeo.geocaching.utils.KeyableCharSet.createFor(KeyableCharSet.java:34)
        at cgeo.geocaching.utils.formulas.DegreeFormula.<clinit>(DegreeFormula.java:26)
        at cgeo.geocaching.utils.formulas.DegreeFormula.compile(DegreeFormula.java:122)
        at cgeo.geocaching.models.CalculatedCoordinate.<clinit>(CalculatedCoordinate.java:27)
        at cgeo.geocaching.models.Waypoint.isCalculated(Waypoint.java:284)
        at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator.fillViewHolder(CacheDetailActivity.java:2099)
        at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$1.getView(CacheDetailActivity.java:2002)
        at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
        at android.widget.AbsListView.obtainView(AbsListView.java:2344)
        at android.widget.ListView.makeAndAddView(ListView.java:1864)
        at android.widget.ListView.fillDown(ListView.java:698)
        at android.widget.ListView.fillFromTop(ListView.java:759)
        at android.widget.ListView.layoutChildren(ListView.java:1673)
        at android.widget.AbsListView.onLayout(AbsListView.java:2148)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:678)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
    	at android.widget.LinearLayou
```

### Expected result after these steps?

Normal operation

### Reproducible

Yes

### c:geo Version

2022.01.21-RC

### System information

```text
API21 emulator
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Lineflyer**
## Description

Downgrade used version of commons-lang3 to 3.11 which was tested to make c:geo work again on API 21-23

## Related issues

Fixes #12577 
Reverts #10100

## Additional context

Please check if any `noinspection` or similar needs to be defined.

### CODE REVIEW

**Comment by eddiemuc** [comment]
Retest this please

**Comment by bekuno** [comment]
> Please check if any `noinspection` or similar needs to be defined.

Done.
Additionally, I added it to the dependabot ignore list.

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Pull request merged**
