### PR TITLE
add option to not ROT13 the hint

### PR DESCRIPTION
**Pull request by ztNFny**
image

### CODE REVIEW

**Comment by Narrat** [comment]
As the word clicked for me primarily is associated with a respective pointer device like a mouse, shouldn't it replaced with tapped (if that is the right form/word)? Which is more commonly used as a word for interacting with touch devices?

**Comment by Lineflyer** [comment]
Yep, we agreed on "tap" as wording some time ago.

Regarding the feature:
Believe it or not, but sometimes we even get support tickets, that the hint "is broken". :)
I am fine with this feature as long as the default is enabled.

**Comment by ztNFny** [comment]
Will change that tomorrow.

Should this also disable the "tap to en/decrypt" on hint or just change the default?

**Comment by Lineflyer** [comment]
I guess it should disable the tap on the hint function if active.

**Comment by ztNFny** [comment]
> 

Done

**Comment by Lineflyer** [comment]
Any objections, else will merge tomorrow.

**Pull request merged**
