### PR TITLE
Support links encoded in some GeoKrety QRCode

### PR DESCRIPTION
**Pull request by kumy**
Follow PR#5168

Code has been rebased.

@samueltardieu I've looked again at the call of `getGeocodeFromTrackingCode()`. The call is from `GeokretyConnector.searchTrackable()` which already deal with network calls. On the other side, `GeokretyConnector.searchTrackable()` is in turn called from inside `AppObservable.bindActivity()` in `TrackableActivity`. So I don't think this function is really problematic. May you please deeper look into this PR?

### CODE REVIEW

**Comment by rsudev** [comment]
ok to test

**Comment by rsudev** [comment]
@kumy The check result in this case indicate a build fail (you need to look into the build console log to see that). Could you cross-check that?

**Comment by kumy** [comment]
Ho, I'll check...

On January 16, 2016 6:37:19 PM GMT+01:00, rsudev <notifications@github.com> wrote:
>@kumy The check result in this case indicate a build fail (you need to
>look into the build console log to see that). Could you cross-check
>that?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/pull/5368#issuecomment-172234490

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
@rsudev I've missed to change an include while merging... Should be ok now. Thank you for your vigilance.
BTW the new job for checking the PR is really cool :)

**Pull request merged**
