### PR TITLE
sheet info: use bottom swipe info instead of fullscreen transition

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Cache / waypoint sheet:
Replaces the fullscreen swipe-up gesture and transition with a smaller info box below the rest of the content:

image

(visible on swipe-up only)

Info sheet stays visible while cache details load

### CODE REVIEW

**Comment by fm-sys** [comment]
What's the benefit of it? Tested the PR and - sorry to say - this feels completely buggy.

We may discuss showing the popup content while loading, but the popup definitely needs to be full height in extended state. 

It just feels totally unexpected if an activity suddenly pops up, although I haven't swiped it to that state.

Apps which have similar up-swipeable components (Google Maps, Musik Apps like Spotify), in all these cases the transition will go all the way to the top. And there are reasons for it, it just looks completely ugly otherwise.

Until now, no reasonable argument was shown why the current visually really clean implementation should be changed to the worse, and not a single nightly user has complained about it. (There was the request to show the hint text instead of cache details activity, but that's a completely different feature request which won't get solved by this PR in any way)

**Comment by moving-bits** [comment]
Hey, that's what PR are for: To have a look at a proposal and to discuss it. (Though probably a bit less emotional, I would prefer.) What one person feels is visually fine, others may think of "can be improved" or even "needs further improvement". We should discuss such remarks and proposals, but without judging them, IMHO. BTW: Google apps are not always the best examples for visually consistent and easy to use apps, some of their apps and websites are quite the contrary, to be honest.

But back to this topic: In the related issue #14881 a couple of things are named which lead me into investigating that. For me it was:
- long swipe way
- content of popup not visible during swiping, and especially during loading the activity (which may take something between a half and a couple of seconds, depending on current state of device)
- using a text below the info sheets content was already proposed in that issue as a possible alternative
- (one could even discuss not using the swipe-up at all, as its behavior is incomplete/inconsistent currently - but that's not what I'm aiming at)

There are more things which are not working currently with the swipe-up, that should be fixed (though they are out of the scope of this PR):
- if you have a long description text, you can scroll this text to its end, but you cannot scroll back, as this gesture will be regarded as swipe down (#14874)
- in some constellations (again: long text) swipe up cannot be used at all, it simply does not work

Don't get me wrong: I don't say that this PR is the ultimate solution (it surely isn't), but let us discuss what can & what should be improved in current implementation.

**Comment by Lineflyer** [comment]
- IMHO the long swipe way in the current implementation is OK for me. This helps to not accidentally open the details (which might be a time consuming action while its loaded) while e.g. cleaning the display in the rain or simply having thick fingers ;)
- What is IMHO missing in the current implementation is any hint, that there actually is a swipe up gesture available, thus my suggestion in #14881 to replace the "more details" button by something else. The simplest possibility would be to add "Up arrows" to the button text (but that's probably not nicely looking).

With respect to this PR, which I checked out on my emulator:
I have to agree to @fm-sys, that it now looks like something is "blocking the UI"/hanging while swiping.

**Comment by moving-bits** [comment]
> What is IMHO missing in the current implementation is any hint, that there actually is a swipe up gesture available, thus my suggestion in [[BottomSheet CachePopup] improve swipe-up-view #14881](https://github.com/cgeo/cgeo/issues/14881) to replace the "more details" button by something else. The simplest possibility would be to add "Up arrows" to the button text (but that's probably not nicely looking).

Would the regular "swipe up" indicator suffice for this? Like in map quick settings:

image

**Comment by fm-sys** [comment]
> Though probably a bit less emotional, I would prefer. 

Honestly I felt bad writing this and if definitely wasn't meant as offense. UI design is an emotional topic. In fact both versions are pretty much the same with or without this PR. However it _feels_ completely different. I tried to express my opinion and write more than just "don't like it" so it need to be emotional, maybe too emotional though.

**Comment by fm-sys** [comment]
> - long swipe way

I don't know if you are using the nightlys or dev builds on a real device (which I can recommend ;)), but I never had the problem that the swipe gesture was interpreted wrong. I can only speak for myself though. This is mostly due to the fact that not only swipe distance but also the velocity is taken into consideration for interpreting the swipe.

**Comment by moving-bits** [comment]
> > Though probably a bit less emotional, I would prefer.
> 
> Honestly I felt bad writing this and if definitely wasn't meant as offense. UI design is an emotional topic. In fact both versions are pretty much the same with or without this PR. However it _feels_ completely different. I tried to express my opinion and write more than just "don't like it" so it got emotional, maybe too emotional though.

All good for me, now, I've calmed down a bit myself meanwhile :-)
Let's close this PR and continue discussion about possible improvements in #14881.

**Comment by moving-bits** [comment]
> > * long swipe way
> 
> I don't know if you are using the nightlys or dev builds on a real device 

So far I've been on emulator only. The only testing device I can install my own builds on (on a regular basis) is a pretty old S5 neo running on Android 6, with limited device space left. While trying to activate the dev builds there I've stumbled across #15101.

Meanwhile I'm able to install c:geo on that device in parallel to the release version, but it's very laggy and crashes frequently (which I guess is due to the age of the system, not caused by c:geo itself, as it runs fine on a more sophisticated device). So it's somewhat hard to distinguish between a "real error" and something caused by running on a low-end device (from today's perspective).

**Pull request closed without merging**
