### PR TITLE
proximity notification messages as Android textual notifications

### PR DESCRIPTION
**Pull request by moving-bits**
So far proximity notifications (while approaching a cache, a waypoint, or a set coordinate) can be signalled by tones only. This PR adds a feature to use Android system notifications for signalling (configurable).
If targeted to a specific waypoint/cache/coords, directions ("12 o'clock" ...) are given additionally.

The use case for this is if you want
- a silent proximity notification
- and/or transfer the notification to a wearable.

Using settings - map you can chose between "tone only", "text only", "tone + text".

### CODE REVIEW

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/location/ProximityNotification.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4636360&bid=15535146)

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/location/ProximityNotification.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4636360&bid=15535146)

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/location/ProximityNotification.java  7
- main/src/cgeo/geocaching/CompassActivity.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4636360&bid=15535146)

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/CompassActivity.java  1
- main/src/cgeo/geocaching/location/ProximityNotification.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4636360&bid=15535146)

**Comment by moving-bits** [comment]
need to fix some notification issue first, therefore setting "WIP" label

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/location/ProximityNotification.java  3
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java  11
- main/src/cgeo/geocaching/CompassActivity.java  1
- main/src/cgeo/geocaching/location/WaypointDistanceInfo.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4636360&bid=15535146)

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/location/WaypointDistanceInfo.java  1
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java  11
- main/src/cgeo/geocaching/location/ProximityNotification.java  3
- main/src/cgeo/geocaching/CompassActivity.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4636360&bid=15535146)

**Comment by bekuno** [comment]
Please merge PR #7996 before this one. I think that rebasing of your PR should be easier.

**Comment by moving-bits** [comment]
Also #7979 should be merged before this one. There will be merge conflicts I will have to resolve, as #7979 simplyfies a few things also touched by this PR. - I'll try to merge over the weekend.

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/location/ProximityNotification.java  3
- main/src/cgeo/geocaching/CompassActivity.java  1
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java  4
- main/src/cgeo/geocaching/location/WaypointDistanceInfo.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4636360&bid=15535146)

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
> Also #7979 should be merged before this one. There will be merge conflicts I will have to resolve, as #7979 simplyfies a few things also touched by this PR. - I'll try to merge over the weekend.

rebased to today's master with resolving the conflicts => ok

**Comment by moving-bits** [comment]
updated to AndroidX, rebased & squashed

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/location/WaypointDistanceInfo.java  1
- main/src/cgeo/geocaching/location/ProximityNotification.java  3
- main/src/cgeo/geocaching/CompassActivity.java  1
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4636360&bid=15535146)

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/location/ProximityNotification.java  3
- main/src/cgeo/geocaching/location/WaypointDistanceInfo.java  1
- main/src/cgeo/geocaching/maps/mapsforge/v6/caches/CachesBundle.java  4
- main/src/cgeo/geocaching/CompassActivity.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4636360&bid=15535146)

**Pull request merged**
