### PR TITLE
Skip testFormatStoredAgo on non-English devices

### PR DESCRIPTION
**Pull request by UniQP**
Alternative solution for #8400 .

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by UniQP** [comment]
@bekuno Can you test whether this works?

**Comment by bekuno** [comment]
will do it.

**Comment by bekuno** [comment]
In this way we replace one failing test by another.

Now:
~~~
java.lang.IllegalStateException: Test requires English default locale
at org.assertj.core.util.Preconditions.checkState(Preconditions.java:138)
at cgeo.geocaching.utils.FormatterTest.testFormatStoredAgo(FormatterTest.java:101)
at java.lang.reflect.Method.invoke(Native Method)
at junit.framework.TestCase.runTest(TestCase.java:168)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
at junit.framework.TestResult.run(TestResult.java:118)
at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
at junit.framework.TestCase.run(TestCase.java:124)
at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at androidx.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:97)
at androidx.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:65)
at androidx.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:115)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1962)
~~~

before:
~~~
org.junit.ComparisonFailure: expected:<"[Stored in device]
"> but was:<"[Auf dem Gerät gespeichert]
">
at java.lang.reflect.Constructor.newInstance0(Native Method)
at cgeo.geocaching.utils.FormatterTest.testFormatStoredAgo(FormatterTest.java:103)
at java.lang.reflect.Method.invoke(Native Method)
at junit.framework.TestCase.runTest(TestCase.java:168)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
at junit.framework.TestResult.run(TestResult.java:118)
at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
at junit.framework.TestCase.run(TestCase.java:124)
at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at androidx.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:97)
at androidx.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:65)
at androidx.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:115)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1962)
~~~

**Comment by UniQP** [comment]
Changed the code to catch the `IllegalStateException` → That should do the trick.

**Comment by bekuno** [comment]
I don't understand why you want to make it so complicated.
If `hasEnglishDefaultLocale` is false - then we know that the test `Preconditions.checkState` will fail. So we can omit the regular tests and and this test case.
If we catch after the last `assertFormatStoredAgo` then we don't know if the `IllegalStateException`was thrown in `Preconditions.checkState` or in `assertFormatStoredAgo`.

**Comment by bekuno** [comment]
Now it is similar to #8400.

**Comment by UniQP** [comment]
Yes. The question is why Codacy likes this one but not #8400.

**Comment by bekuno** [comment]
I think that it had a problem with the commit, not with the code.
Please try my code in your PR to compare it.

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
The last codacy check tooks some time, but now it is successfull.
So we have in PR #8400 only a problem with codacy, not with the code.

**Comment by bekuno** [comment]
I replaced #8400 by #8563 . This PR works.

**Comment by UniQP** [comment]
Close as duplicate of #8563

**Pull request closed without merging**
