### PR TITLE
Removed idea files and folders, see #5581

### PR DESCRIPTION
**Pull request by pstorch**
As discussed in #5581 I removed the `.idea` folder and the `.iml` files and added them to the `.gitignore`.
Android Studion (and I guess IntelliJ) works without them. It might be necessary to import the project once again.
Ignoring these files and folders simplifies switching between branches, commiting relevant changes, merging and rebasing.

### CODE REVIEW

**Comment by samueltardieu** [comment]
Please do not merge right away. I think some files should be kept (the inspection profile for example, as well as the style rules). I'll try to check tomorrow.

**Comment by pstorch** [comment]
I compared the `.idea` directory from `master` and this PR after starting AS once.
These files seem to be specific for cgeo: 

- `inspectionProfiles/`
  - `Project_Default.xml`
  - `c_geo_standards.xml`
  - `profiles_settings.xml`
- `runConfigurations/`
  - `cgeo___tests.xml`
- `scopes/`
  - `cgeo_project_sources.xml`
  - `scope_settings.xml`
- `codeStyleSettings.xml`
- `findbugs-idea.xml`

If these files are essential, how are they synchronized between Eclipse and AS?

**Comment by samueltardieu** [comment]
They are not synchronized automatically. Is this even possible?

**Comment by pstorch** [comment]
I don't know an automatic way. That's why I'm asking. Is someone doing it manually?
Can we move some settings into the Gradle build (e.g. the findbugs config), so that we have a common basis?

**Comment by samueltardieu** [comment]
You can keep files starting with "cgeo" and drop others I would say.

**Comment by samueltardieu** [comment]
Retest this please

**Comment by pstorch** [comment]
That might be a compromise. But I would like to understand what they are used for. 
For example `runConfigurations/cgeo___tests.xml` changes everytime I start AS and when I look into it, I don't see something important which is worth sharing.

**Comment by pstorch** [comment]
I tried to keep these two cgeo specific files:

- `inspectionProfiles/c_geo_standards.xml`
- `scopes/cgeo_project_sources.xml`

and ignored anything else.
The result was that after importing the project into AS it deleted both files and restored all others.

At the moment I think we should try ignoring the complete `.idea` folder as initially planned and see how it works out. If anything feels awkward we can revert the change and restore these files anyway.

**Comment by pstorch** [comment]
Any other objections?

**Comment by Bananeweizen** [comment]
I just merged 5 other PRs, but I have too little insight into the AS file structure to give any valuable feedback here. Someone else?

**Comment by rsudev** [comment]
Right now I am testing a little what is volatile and what fixed in the configs of AS and idea, when you just work with them. Perhaps this gives some insight what to keep and what to ignore

**Comment by rsudev** [comment]
My current research supports the concept of this PR.
- idea (latest version) deletes all .iml files in the projects, creates new ones in .idea/modules and keeps fiddling with them on every run. If there is some stable configuration file where code styles and checks can be placed I would need to find out
- AS (latest version) still uses the .iml files in the projects, also fiddling with them on every run. There seems to be a codeStyle configuration in .idea, but how stable that is I don't know (and it is deleted by idea).

I guess at some point AS will again be aligned with the workspace layout of idea and than it might make more sense to carve out the (hopefully) stable part that contains codestyle settings and checks.

**Comment by rsudev** [comment]
@samueltardieu What version of idea are you using (mine is 2016.1.3 Build #IC-145.1617) and how do you manage the config changes?

**Comment by samueltardieu** [comment]
I don't. I have no objection to removing the IDEA specific files.

**Comment by rsudev** [comment]
Rebased and pushed directly. Thanks!

**Pull request closed without merging**
