### PR TITLE
workaround for google maps corrupted zoom data file bug

### PR DESCRIPTION
**Pull request by moving-bits**
workaround for issuetracker.google.com/issues/154855417
as described in https://issuetracker.google.com/issues/154855417#comment179

### CODE REVIEW

**Comment by moving-bits** [comment]
@bekuno 
Can you test this workaround on the device where you were able to reproduce the bug?

**Comment by bekuno** [comment]
@moving-bits 
This is my real caching device, I don't have a secure backup yet.
Not so good.

**Comment by moving-bits** [comment]
Google has updated their recommendations for a workaround, see https://issuetracker.google.com/issues/154855417#comment398. Have updated this PR accordingly.

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Pull request merged**
