### PR TITLE
navigation: add entry for google maps transit mode

### PR DESCRIPTION
**Pull request by lewurm**
This is more like a feature request, as I didn't manage to setup eclipse properly to build this thing. Can someone with a proper setup have a look?

I want to add another entry in the navigation menu that opens google maps finding a route with public transport. It should be rather straight forward I think.

Another question: How are translations managed? Do I need to add an entry for each language?

Thanks!

### CODE REVIEW

**Comment by samueltardieu** [comment]
The code looks and compiles fine (translations are added later by translaters using Crowdin). However, it doesn't switch to transit mode on Google Maps on my Nexus 5 (Android 5.1.1).

However, it looks like this is not specific to your change: every mode triggers the same applications (Google Maps & CityMapper) and seems to ignore the mode.

**Comment by samueltardieu** [comment]
It looks like transit mode is "r", not "t" which means toll-free car mode. I'll update it.

**Comment by samueltardieu** [comment]
Thanks for your contribution.

**Comment by lewurm** [comment]
awesome, thank you!

**Pull request merged**
