### PR TITLE
preserve last tb action per trackable (fix #13590)

### LINKED ISSUE #13590: Remember trackable actions per trackable
### Tell us your idea!

Currently the default action for trackables in your inventory is "No action". You can change in the settings that the default action should be "visited".

If you own some trackables that travel with you and some that don't, it's very tedious to select "no action" for stationary TBs and "visited" for travelling ones.

### What solution would you suggest?

Application should remember what action has been chosen for every TB in your inventory and set it as the default for the next logs. 

The new TBs you add to your inventory should have the default action set, i.e. "no action" or "visited", depending on the settings.

### Is there an alternative?

Selecting appropriate action on every log.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Remember last selected action per trackable

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by eddiemuc** [comment]
I might be wrong, but I feel a tendency to use DBExtension very much in last time. I thought this was meant to store small amounts of values not fitting nicely into our db table structure. Now I get the impression it is meant to "turn" our relational db approach into a NoSQL-for-the-poor (store everything in a key-value-fashion).

In this PR: isn't there a db table storing trackables where the last state could be stored in a new column? Instead of using a DBExtension?

**Comment by eddiemuc** [comment]
> Under what conditions does a trackable gets added to the cg_trackable table?

I honestly don't know. I assumed it would contain the owned trackables, because afaik we don't have "offline trackables" in c:geo.

If this table is filled with something else, then please ignore my previous comment.

**Comment by Lineflyer** [comment]
> If this table is filled with something else, then please ignore my previous comment.

I think from back in my head it contains the inventory of caches linked to the caches table....I might be wrong though as I never in depth took a look at our SQL-DB.

**Comment by moving-bits** [comment]
Ok, I've done a bit of research: 

I cross-checked for what @Lineflyer has suggested. Indeed, on saving a cache page, the tb in the inventory of the cache gets stored to `cg_trackables` table. But although this tb data is stored already, tapping on a tb leads to an error when internet connection is switched off. I'll create a new issue for that.

Then I cross-checked our use-case here, whether tb data for the current user's inventory gets stored on logging a cache. This is _not_ the case, so I guess we need some mechanism to store the relevant data.

I see two options here:
- a) We can use the `cg_trackables` table for those tb as well.
  - Pro: No additional data structure needed
  - Con: Table structure consumes more space than `cg_extension` row; possibly additional data requests needed to fill the columns
- b) Or we use the `cg_extension` approach of this PR
  - Pro: Self-contained data structure with only the data needed for this use-case; no additional table; less space-consuming

Personally I would go with approach b, but I'm open for the other approach as well. In either case, I found out that we should adjust the index structure anyway, as
- table `cg_extension` does not have a key on the `_type` column, and
- table `cg_trackables` does not have a key on the `tbcode` column (which we would need for our use-case).

Depending on how we decide to continue here, I'll open an issue for updating the index structure as well.

**Comment by eddiemuc** [comment]
Thanks for the detailed analysis!

 Since owned trackables are not stored in the db table yet, I would vote for b) personally. I assume the table is tied to a concrete cache (e.g. has a geocode field) which would make it unsuitable for storing owned trackables anyway

**Comment by Lineflyer** [comment]
Could that be a foundation for #420 (better described in #838) ?

**Comment by moving-bits** [comment]
> Could that be a foundation for #420 (better described in #838) ?

#838 as well as #4394 is about storing a user's tb inventory and/or a user's owned tb in our database and offer views for it. Indeed our current `cg_trackables` table might be a base for storing the relevant data (and `cg_extension` wouldn't be), but we would need to distinguish the different reasons why a trackable is stored there - cache's inventory, user's inventory, owned by a user -, and check the related queries. 

Getting the data, keeping it up to date, and adding the views for it is a somewhat larger task, so I'd say let's not wait for that.

**Pull request merged**
