### PR TITLE
Rename "OSM: Map" to "OpenStreetMap Standard" (fix #8181)

### LINKED ISSUE #8181: Rename OSM menu entry
From https://github.com/openstreetmap/operations/issues/371#issuecomment-598016057

> Could you change the "OSM: Map" to "OpenStreetMap Standard" or something that has the full name?

### PR DESCRIPTION
**Pull request by moving-bits**
per request of OSM operations team, see https://github.com/openstreetmap/operations/issues/371#issuecomment-598016057

### CODE REVIEW

**Comment by Lineflyer** [comment]
Do we need to name it standard, while there is no other OSM based map around?Von Samsung-Tablet gesendet
null

**Comment by moving-bits** [comment]
We could call it just "OpenStreetMap" as well. What do you think?

**Comment by jakedot** [comment]
I think the "Standard" was something the OSM guys wanted to have explicitly, so if possible we should honor it?

**Comment by moving-bits** [comment]
> I think the "Standard" was something the OSM guys wanted to have explicitly, so if possible we should honor it?

They requested `Could you change the "OSM: Map" to "OpenStreetMap Standard" or something that has the full name?`, so I guess an "OpenStreetMap" would be ok for them as well.

**Comment by jakedot** [comment]
The question is if that is the full name as defined by them, but I'd guess so. Maybe @pnorman can clarify?

**Comment by pnorman** [comment]
OSM should be expanded to OpenStreetMap. Standard isn't required.

**Pull request merged**
