### PR TITLE
Implemented Filtering by Country (fix #5257)

### LINKED ISSUE #5257: Filter by Location (country)
From support mail:

Hello guys. Please add filter by Location (country). Could be very usefull to sort stored caches to different lists. Thanks.

### PR DESCRIPTION
**Pull request by jakedot**
Unconstrained, over all Countries extracted from the Location field on caches.

Fixes #5257.

### CODE REVIEW

**Comment by bekuno** [comment]
ok to test

**Comment by jakedot** [comment]
@bekuno seems like the build isn't happening even though you greenlisted it...

**Comment by Lineflyer** [comment]
Ok to test

**Comment by bekuno** [comment]
> @bekuno seems like the build isn't happening even though you greenlisted it...

I activated only the CI test ("default").

Please correct the problems found by codacy .

**Comment by jakedot** [comment]
> Please correct the problems found by codacy .
already did...

now, Jenkins gives additional checkstyle warnings. Why is that? Are there divergent configs?

fixed them too...

**Comment by bekuno** [comment]
> now, Jenkins gives additional checkstyle warnings. Why is that? Are there divergent configs?

both SHOULD honor the same configuration within c:geo (checkstyle.xml in the procect root)
But I saw such errors also in the codacy messages for the first check ...

**Comment by bekuno** [comment]
An additional lint issue needs yur attention :-)

**Comment by moving-bits** [comment]
I see this PR is coming from your master branch. Normally we create a feature branch in our fork (e.g.: "issue_5257"), create the PR on that locally, push to our fork ("origin"), and merge from there to c:geo master when it's ready. Be aware: The source branch gets deleted automatically after merging (although I'm not sure whether this is true for master branch as well).

I'm not sure about the technical consequences if a PR is coming from the contributor's master branch. Maybe someone more git savvy can comment on this?

**Comment by jakedot** [comment]
I should still try to implement the hint of @moving-bits in #5257 (restricting shown countries to those contained in the current list, so please set the WIP label.

**Comment by jakedot** [comment]
> I see this PR is coming from your master branch. Normally we create a feature branch in our fork (e.g.: "issue_5257"), create the PR on that locally, push to our fork ("origin"), and merge from there to c:geo master when it's ready. 

Thanks for the hint, will fix that.

> Be aware: The source branch gets deleted automatically after merging (although I'm not sure whether this is true for master branch as well).

Over at whereyougo github always explicitly asks me if I want to delete the fork branch, but it might be different here.

> I'm not sure about the technical consequences if a PR is coming from the contributor's master branch. Maybe someone more git savvy can comment on this?

I'm guessing there is no difference as long as the forked master is up-to-date? No idea though.

**Comment by Lineflyer** [comment]
> >I'm not sure about the technical consequences if a PR is coming from the contributor's master branch. Maybe someone more git savvy can comment on this?
>
> I'm guessing there is no difference as long as the forked master is up-to-date? No idea though.

Git does not care about which branch you use in principle.
It is however AFAIK good practice to use dedicated branches for each topic you are working on. When you work on master it is fine as long as this is the only thing you are working on. Be aware that all changes you push to your master branch will automatically be appended to this PR.

Additionally if you now want to work on another topic, its rather difficult to create another feature branch based on the state of upstream master (as you modified it already on your master).

So my recommendation is to always checkout a new branch from the base branch you need (typically master) to work on. This way you have the change to keep your master on the state of upstream master and be able to create another feature branch from that easily.

**Comment by Lineflyer** [comment]
> > Be aware: The source branch gets deleted automatically after merging (although I'm not sure whether this is true for master branch as well).
>
> Over at whereyougo github always explicitly asks me if I want to delete the fork branch, but it might be different here.

I recently changed that setting on both repositories (due to the need to delete the head branch of the translation each time after merge).
I do not know however if this only applies to branches in our repo or also merged branches of remote repositories. Feedback is welcome if you see a changed behaviour now.

**Comment by Lineflyer** [comment]
>  (although I'm not sure whether this is true for master branch as well).

If `master` is his default branch I guess it will not be deleted by the system at any time.

**Comment by jakedot** [comment]
> Additionally if you now want to work on another topic, its rather difficult to create another feature branch based on the state of upstream master (as you modified it already on your master).

Difficult?

Can't I just do a "git checkout -b new_branch upstram/master" on my local machine?

**Comment by Lineflyer** [comment]
> Can't I just do a "git checkout -b new_branch upstram/master" on my local machine?

Sounds like it could work....I am still a bit of beginner with Git. :)

**Comment by jakedot** [comment]
> Sounds like it could work....I am still a bit of beginner with Git. :)

If it's somehow not possible I'm sure that I can just create a new branch locally and then call "git reset upstream/master" :-)

**Comment by Narrat** [comment]
And directly working on master (or whatever is chosen as the main branch) can cause divergence of upstream and downstream (or local clone). Therefor, yes, like you already explained Lineflyer, dedicated branches for every related work are the way to go :) 

> If it's somehow not possible I'm sure that I can just create a new branch locally and then call "git reset upstream/master" :-)

Yes, and the other way works too. And you could also just push your chosen local branch into a different branch of your github repo (example `git push origin name_of_local_branch:what_it_should_be_in_the_other_repo`). Although the local branch would still need to get reset to be in sync again with the upstream branch.

**Comment by jakedot** [comment]
Is there a way to change the fork branch for a PR? if not, I'll close this one and open another from my new issue_5257 branch.

**Comment by Narrat** [comment]
Dunno how far the support on github got extended. But you should see if it is possible if you go to header of this PR and hit edit. IIRC at least the target branch can be changed, but not sure if it was possible with the "from"-branch.

**Comment by bekuno** [comment]
Only the target branch, not the source.

**Comment by jakedot** [comment]
yeah, ok then. I did see changing the target branch was possible in an earlier PR, but it could have been that team members could also change the source branch... was worth asking, even if in hindsight it doesn't make sense that you would be able to control what I want to contribute... closing here, thanks

**Pull request closed without merging**
