### PR TITLE
fix #8978: GUI part of add fast log image

### LINKED ISSUE #8978: [Log: adding images] add resorting option and reintroduce image title prefix
**Is your feature request related to a problem?**
Adding of images to logs is currently a long image-per-image-procedure involving at least four clicks through 3 dialogs (in log dialog click "add", in image dialog click "stored", in image select intent choose image, in image dialog click "ok"). This is ok in case you want to edit other image properties like title and description anyway. For people simply wanting to add a couple of pics (maybe 2 or 3) however this is quite painful.

**Describe the solution you'd like**
Currently there is a single "add" button in the log. Idea is to place three (icon) buttons there instead: 
- "add from storage": opens image select intend, allows for selection of multiple images, those are added with default title, empty description and scaled down to a predefined size (maybe 640ox)
- "add from camera": opens camera intend, pic is placed in list with same logic as above
-  "add (advanced)": works exactly like today's button (opens c:Geo's own advanced image select dialog)

Additionally I would make tipping of image in a list open a context menu with options "edit" (opens c:geo image dialog) and "remove" (removes entry from image list

**Describe alternatives you've considered**
Alternative is to do nothing. Feature does not add new functionality.

**Additional context**
- Discussion in #8970 shows that existing dialog should stay
- fast select is inspired by other caching apps

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #8978: GUI part of add fast log image

### CODE REVIEW

**Comment by Lineflyer** [comment]
Can you provide a screenshot for this PR? Would be nice to see it before merging.

**Comment by fm-sys** [comment]
@Lineflyer see https://github.com/cgeo/cgeo/issues/8978#issuecomment-707863999

**Comment by eddiemuc** [comment]
Thanks to @fm-sys 

@Lineflyer should I copy screenshots to the PRs rather than into the linked issues? I always try to keep discussions on the issues, since they seem more fit for "long-term-documentation" to me while PRs are mostly short-living things. Is that a wrong assumption?

**Comment by Lineflyer** [comment]
> @Lineflyer should I copy screenshots to the PRs rather than into the linked issues? I always try to keep discussions on the issues, since they seem more fit for "long-term-documentation" to me while PRs are mostly short-living things. Is that a wrong assumption?

I agree that discussion should take place on the issue rather than on the PR. Maybe you could just link (like you did in your comment) to the screenshot.

**Pull request merged**
