### PR TITLE
SAF string improvements

### PR DESCRIPTION
**Pull request by Lineflyer**
Some proposals for string improvements/corrections:

- Add articles at places, where they have been omitted while its still a sentence (not only a toast, which should be kept short)
- Try to phrase some operations more understandable for users
- Remove the "See logfile for details" as no normal user would know hoe or where.

### CODE REVIEW

**Comment by eddiemuc** [comment]
Retest this please

**Review by eddiemuc — APPROVED** [review]
All fine of course. I just wonder why ci build fails

**Comment by eddiemuc** [comment]
Seems like there is an xml error in the file:

`home/jenkins/slave/workspace/cgeo pull request/main/res/values/strings.xml:2125:3: Resource and asset merger: The element type "string" must be terminated by the matching end-tag "</string>".
22:05:55      org.xml.sax.SAXParseException; lineNumber: 2125; columnNumber: 3; The element type "string" must be terminated by the matching end-tag "</string>".
22:05:55      	at `

**Comment by Lineflyer** [comment]
Upsi...will correct it.
Thanks CI

**Pull request merged**
