### PR TITLE
cgeo-contacts: upgrade according to c:geo

### PR DESCRIPTION
**Pull request by bekuno**
see #7193

- build.gradle
  - java 8
  - lib updates
- ContactsActivity.java
  - replace with try with ressources (Java 8)

The READ_CALL_LOG permission is now not more implicit necessary, because minSdkVersion is now 16.
(https://developer.android.com/reference/android/Manifest.permission.html#READ_CALL_LOG)

### CODE REVIEW

**Comment by bekuno** [comment]
@Lineflyer What is to do to get now the contacts-addon.apk?

**Comment by Lineflyer** [comment]
The addon is currently taken down from Google Play. Details in #7193

**Comment by Lineflyer** [comment]
The plugin wont work again with only these changes AFAIK
We need to handle the runtime read_contacts permission handling.

**Comment by Lineflyer** [comment]
@Bananeweizen Given the fact that you initially created this plugin AFAIK: Due to the requirements of Google Play we had to depublish it some months ago. We could republish it as it has no the matching targetSDK but it still needs the related permission handling. As the permissions were the reasons to initially publish it as a plugin, it makes even more sense to integrate it into the main app rather than pusblishing the plugin again, as we have runtime permission handling available now.
If you could help getting this function back into the main app, it would be great. At this moment only the existing installations are still out in the field, but new users or users not having installed it previously cannot use the feature.

**Comment by rsudev** [comment]
@Lineflyer: As long as we still target a minsdk that does not yet have runtime permission handling, the initial reason for this plugin still stands, so re-publishing with extension of a (simple) permission handling is IMO the way to go.

**Comment by Lineflyer** [comment]
@rsudev That is a valid argument. But on state-of-the-art android versions we are fine. At the end it depends also on the effort you want to spend to implement permission handling on the seperate plugin.

**Pull request merged**
