### PR TITLE
fix #15138: add a new formula function to select multiple single chars

### LINKED ISSUE #15138: calculation formula for substrings
### Tell us your idea!

I suggest an additional substring calculation:
sub1( \<string\> ;i)=substring( \<string\> ;i-1;1)

### What solution would you suggest?

In the vast majority of the substring the given index is not starting with 0 but with 1 and also only 1 character is needed.
Latest example:GCAHM12, current solution see alternative

### Is there an alternative?

Add a -1 in the sub formula
{c:geo-start}
@Finale (F) {CC|N $N1$N2° $N3$N4.$N5$N6$N7|E $E1$E2° $E3$E4.$E5$E6$E7}
$C='1234567890123456789012345678901234' | $N1=sub(C;13-1;1) | $N2=sub(C;20-1;1) | $N3=sub(C;15-1;1) | $N4=sub(C;24-1;1) | $N5=sub(C;33-1;1) | $N6=sub(C;16-1;1) | $N7=sub(C;9-1;1) | $E1=sub(C;21-1;1) | $E2=sub(C;4-1;1) | $E3=sub(C;28-1;1) | $E4=sub(C;14-1;1) | $E5=sub(C;10-1;1) | $E6=sub(C;26-1;1) | $E7=sub(C;32-1;1)
{c:geo-end}

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #15138: add a new formula function to select multiple single chars:

image

### CODE REVIEW

**Comment by moving-bits** [comment]
I'm undecided: It's a small and non-critical extension, but strictly speaking it's a new feature and should go to `master` 🤷‍♂️

**Comment by eddiemuc** [comment]
My vote is `release` (which is why I created the PR against this branch), but let's wait for other opinions.

**Comment by eddiemuc** [comment]
Currently we have one vote for merge (my own) and one undecided. If no one objects I will merge this PR sometime this evening.

**Comment by fm-sys** [comment]
+1 for undecided. Strictly spoken, it should go to `master`. 

But as we want to create a new beta anyway in the near future, it'll make no real difference whether it goes to master or release. We shouldn't do asseparate bug fix release just for it IMHO.

**Comment by moving-bits** [comment]
> We shouldn't do asseparate bug fix release just for it IMHO.

FYI: We have two yet unreleased fixes on `release` as well (wrt to trackables), see [changelog_bugfix.md](https://github.com/cgeo/cgeo/blob/release/main/src/main/res/raw/changelog_bugfix.md) (but seemingly not that urgent currently, concluding from support emails)

**Pull request merged**
