### PR TITLE
UnifiedMap: Reposition "follow my location" and compass rose

### LINKED ISSUE #15774: Move "follow me" button on map from toolbar to map
Idea from today's dev meeting:

Move the "follow me" icon from the toolbar to the map area, below or beside the compass rose.

Seems to be a more logical position, and gives more space in the toolbar for the "live mode" button (which seems to be forced to the overflow menu since the list chooser changes).

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Tries to fix #15774 and #15775:

- position compass rose below distance windows, right-aligned; position varies with more detailed distance infos
- "follow my location" button moved from toolbar to below compass rose
- long tap on compass rose opens rotation mode quick settings
- pulls up rotation indicator handling from map fragments to `UnifiedMapActivity`
- some code cleanup

Implemented for UnifiedMap (VTM + Mapsforge + GM), CGeoMap / NewMap are unchanged.

image.image

### CODE REVIEW

**Comment by ztNFny** [comment]
I'd suggest to not "clue" those buttons together but have them as 2, like map / route settings. Also maybe move them a bit up so vertical and horizontal distance are equal?

like
image

**Comment by moving-bits** [comment]
I will look into it. (That's just some margins defined in the layout file + using a different background (without divider) for compass rose button.)

**Comment by moving-bits** [comment]
Have adjusted a few settings:
- right margin of "rotation mode" / "follow my location" buttons is now identical to zoom buttons
- top margin and right margin of the two new buttons is now identical
- vertical distance between the two new buttons is now the same as horizontal distance between quick settings buttons

image

**Comment by ztNFny** [comment]
Nice!
Only the "position" icon looks a bit too large, compared to the others. But of you want I can also take a look at that one later.

**Comment by ztNFny** [comment]
At a quick glance that looks a lot better.

**Comment by moving-bits** [comment]
As this is done just by scaling down a 38dp image without or with nearly no padding, a correctly dimensioned xml drawable would be the way to go, IMHO. So if you find the time, an update would be very welcomed.

The files are `map_followmylocation_btn.xml` and `map_followmylocation_off_btn.xml` and the scaling down is done in `map_bearingindicator.xml` layout file:

```
<ImageView
    android:id="@+id/map_followmylocation_btn"
    android:tooltipText="@string/menu_centerposition"
    android:layout_width="24dp"
    android:layout_height="24dp"
    android:layout_centerInParent="true"
    android:contentDescription="@string/menu_centerposition"
    style="@style/map_quicksettingsbutton" />
```

**Comment by ztNFny** [comment]
I'll look at it, go ahead and merge. Something irks me about that compass as well, can't tell what exactly...

**Comment by moving-bits** [comment]
failing tests are unrelated (connection error to GC), so let's merge here for further fine-tuning of the icons

**Pull request merged**
