### PR TITLE
Upgrade RxJava to 3.0.3 (Fix #8251)

### LINKED ISSUE #8251: Update RxJava to version 3 until February 2021
c:geo currently uses RxJava 2.x, which is in maintenance only mode.

From the [RxJava site](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0):

_With the release of RxJava 3.0.0, the previous version line, 2.2.x, is in maintenance mode. This means only bugfixes will be accepted and applied; no new operators or documentation changes will be accepted or applied._

:information_source: _2.x will be supported until February 28, 2021, after which all development on that branch will stop._

So we should adapt our code and upgrade to RxJava 3 until then.

### PR DESCRIPTION
**Pull request by UniQP**

### CODE REVIEW

**Comment by moving-bits** [comment]
Build fails with `package io.reactivex does not exist`:

```
17:59:21  > Task :main:compileBasicDebugUnitTestJavaWithJavac
17:59:21  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxOkHttpUtilsTest.java:6: error: package io.reactivex does not exist
17:59:21  import io.reactivex.Single;
17:59:21                     ^
17:59:21  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxOkHttpUtilsTest.java:28: error: cannot find symbol
17:59:21      private static Single<Response> get(final String url) {
17:59:21                     ^
17:59:21    symbol:   class Single
17:59:21    location: class RxOkHttpUtilsTest
17:59:21  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxUtilsTest.java:7: error: package io.reactivex does not exist
17:59:21  import io.reactivex.Observable;
17:59:21                     ^
17:59:21  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxUtilsTest.java:8: error: package io.reactivex.disposables does not exist
17:59:21  import io.reactivex.disposables.Disposable;
17:59:21                                 ^
17:59:21  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxUtilsTest.java:9: error: package io.reactivex.subjects does not exist
17:59:21  import io.reactivex.subjects.PublishSubject;
17:59:21                              ^
17:59:21  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxUtilsTest.java:18: error: cannot find symbol
17:59:21          final PublishSubject<String> rawObservable = PublishSubject.create();
17:59:21                ^
17:59:21    symbol:   class PublishSubject
17:59:21    location: class RxUtilsTest
17:59:21  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxUtilsTest.java:18: error: cannot find symbol
17:59:21          final PublishSubject<String> rawObservable = PublishSubject.create();
17:59:21                                                       ^
17:59:21    symbol:   variable PublishSubject
17:59:21    location: class RxUtilsTest
17:59:21  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxUtilsTest.java:19: error: cannot find symbol
17:59:21          final Observable<String> observable = RxUtils.rememberLast(rawObservable, "initial");
17:59:21                ^
17:59:21    symbol:   class Observable
17:59:21    location: class RxUtilsTest
17:59:22  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxUtilsTest.java:31: error: cannot find symbol
17:59:22          final Disposable disposable = observable.subscribe();
17:59:22                ^
17:59:22    symbol:   class Disposable
17:59:22    location: class RxUtilsTest
17:59:22  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxUtilsTest.java:43: error: cannot find symbol
17:59:22              return Observable.just(s.length());
17:59:22                     ^
17:59:22    symbol:   variable Observable
17:59:22    location: class RxUtilsTest
17:59:22  /home/jenkins/slave/workspace/cgeo pull request/tests/src/cgeo/geocaching/utils/RxUtilsTest.java:60: error: cannot find symbol
17:59:22          Observable.never().doOnDispose(() -> unsubscribed.set(true)).lift(new RxUtils.DelayedUnsubscription<>(100, TimeUnit.MILLISECONDS)).subscribe().dispose();
17:59:22          ^
17:59:22    symbol:   variable Observable
17:59:22    location: class RxUtilsTest
```

Is there something missing in gradle config or does something needs to be installed on our CI?

**Comment by UniQP** [comment]
Looks like I missed some adaptations in the test code. I will take a look.

**Comment by bekuno** [comment]
> tests/src/cgeo/geocaching/utils/RxOkHttpUtilsTest.java:6

`import io.reactivex.Single;`

needs also the upgrade

**Comment by moving-bits** [comment]
BTW: What is the minimum API level requirement for RxJava3?

**Comment by UniQP** [comment]
MinSdk seems to be 9: https://github.com/ReactiveX/RxAndroid/blob/3.x/build.gradle#L24

**Comment by moving-bits** [comment]
> MinSdk seems to be 9: [ReactiveX/RxAndroid:build.gradle@`3.x`#L24](https://github.com/ReactiveX/RxAndroid/blob/3.x/build.gradle#L24) [](/ReactiveX/RxAndroid/blob/HEAD@{2020-05-02T17:13:29Z}/build.gradle#L24)

Thanks for looking this up, I hadn't found any info on their Github page.
Good to know it works with API level 9, so it's no restriction for us.

**Comment by Lineflyer** [comment]
According to this real old issue in their repo it could be higher meanwhile:

https://github.com/ReactiveX/RxAndroid/issues/68#issuecomment-64012951

**Comment by UniQP** [comment]
> According to this real old issue in their repo it could be higher meanwhile:
> 
> [ReactiveX/RxAndroid#68 (comment)](https://github.com/ReactiveX/RxAndroid/issues/68#issuecomment-64012951)

Yes, but they still set minSdk 9 in there current source code. Their sample project uses minSdk 15, which would also be fine for us (minSdk 16).

**Comment by moving-bits** [comment]
First of all, I have no idea of the internal workings of RxJave, so please forgive me if this is a dumb question ;-)

While scanning the changes I've stumbled upon that in the old code we sometimes used `import io.reactivex.disposables.Disposable` and sometimes `import io.reactivex.disposables.Disposables` (note the plural), now we only seem to use the singular form (`import io.reactivex.rxjava3.disposables.Disposable`) - is this on purpose? E. g. `playservices/LocationProvider`, `utils/RxAndroidUtils`, `utils/RxOkHttpUtils`.

**Comment by UniQP** [comment]
The `Disposables` class contained only static methods that were moved to the `Disposable` class in RxJava3.

**Comment by moving-bits** [comment]
> The `Disposables` class contained only static methods that were moved to the `Disposable` class in RxJava3.

Ah, I see. Thanks for clarifying.

**Comment by moving-bits** [comment]
@UniQP  Thanks for preparing the lib's update!

**Pull request merged**
