### PR TITLE
Use pull_request_target to allow secrets access

### PR DESCRIPTION
**Pull request by Lineflyer**
See: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

### CODE REVIEW

**Comment by Lineflyer** [comment]
@kumy 

I assume this is the right way to overcome the secret sharing problem for forks.

The reason its not working yet for this very PR is possibly this restriction (mentioned in the above link). Thus I assume it will work on the next PR after this change is merged to our repo:

> pull_request_target runs in the context of the target repository of the PR, rather than in the merge commit. This means the standard checkout action uses the target repository to prevent accidental usage of the user supplied code.

I think we can go this way without to much risk of disclosing our secrets as I also just configured our actions to only run if triggered by a organisation member. Any outside collaborator PR should need pre-approval by the team AFAIU the setting:

image

**Comment by Lineflyer** [comment]
> pull_request_target runs in the context of the target repository of the PR, rather than in the merge commit. This means the standard checkout action uses the target repository to prevent accidental usage of the user supplied code.

Rethinking this:
This probably means, that the code change contained in a PR coming from a fork repository will never be tested, but this is our usecase.
If this is the case, we could only do the following:
- Use pull_request_target to trigger a approval
- When approved the worklof should run in the source repository context (merge commit) if I understand the linked article correctly

**Comment by kumy** [comment]
@Lineflyer no, please don't do that :pray: 
I read somewhere (need to find my source) that `pull_request_target` action is the implementation before the security issue was discovered. So you'll be rolling back the security fix.

See https://github.com/cgeo/cgeo/issues/15608#issuecomment-2059773013 for another way of preventing failures.

> configured our actions to only run if triggered by a organisation member. Any outside collaborator PR should need pre-approval by the team

:+1: really nice

**Comment by Lineflyer** [comment]
@kumy  Oh, that happened at the same time. I will read through that first and ocmment over there.

**Pull request closed without merging**
