### PR TITLE
supersize distance view (fix #9282)

### LINKED ISSUE #9282: Super-size routing distance display (optional)
While being on a cache tour I frequently either set the next waypoint as routing target or open the popup for it. Both of it displays the distance to the selected waypoint.

When I'm using my bike, and the way gets a bit rougher, it's pretty hard to read the distance as the display gets shaken - so I probably need to stop, read the distance, and move on. "Proximity notification" or "talking compass" only help in some cases. (eg: You do not want to have your loudspeaker on in all cases and/or the surrounding may be too load for the text messages to be heard.)

So what I what like to see is a map overlay which displays the distance text ("120m") in super-size letters (like a quarter of the screen). This option should be switchable using the three dot menu in map mode, default to off.

### PR DESCRIPTION
**Pull request by moving-bits**
Optionally display current distance to navigation target in a super-sized font at the maps' head:

image

Supersize display can be switched either by using a menu item (Map Settings => Supersize distance) or by tapping on the distance shown in the upper right corner.

### CODE REVIEW

**Comment by fm-sys** [comment]
Why does the supersize distance view have rounded corners on the left but not on the right side?  IMHO rounding off none of them is the way to go...

**Comment by moving-bits** [comment]
Good catch - it's the styling I've reused from the small distance views.  I will change it.

**Comment by Lineflyer** [comment]
@moving-bits 
I don't get the content of the screenshot in full extend:
There is a small distance (routed) showing 820m. Your supersize is showing 492m. Why is it different? 
In case you can supersize different of that values (routed, straight) shouldn't we include the icon in front to make this clear to the user?

My opinion would be to ommit another setting. Clicking on it to supersize and revert should do the job, don't you think?
I am thinking this way, because our menus have to many items already.

**Comment by moving-bits** [comment]
We can show up to three distances currently, depending on your settings and data:
- distances for navigation target
  - straight distance (if configured or no routed distance available)
  - routed distance (if brouter available and straight distance within configured max distance)
- length of individual route

"Supersize" does show the first of the navigation target distances only (which is the straight distance, if no brouter is available, or if you have configured to show both straight and routet distance).

I can
- either add the symbol to the supersize window,
- keep all small windows (including their symbols, if any) additionally to the supersize window (that one without symbol)
- or close all small navigation target windows on opening the supersize window.

**Comment by moving-bits** [comment]
> My opinion would be to ommit another setting. Clicking on it to supersize and revert should do the job, don't you think? I am thinking this way, because our menus have to many items already.

I'm undecided with this one. On the one hand I see the risk of overcrowding menus, on the other hand c:geo already has too many hidden functions which are pretty hard to find for the user. Hmm 🤔

**Comment by Lineflyer** [comment]
> I'm undecided with this one. On the one hand I see the risk of overcrowding menus, on the other hand c:geo already has too many hidden functions which are pretty hard to find for the user. Hmm 🤔

You are right, but this is a pure visual on/off feature (a bit comparable to zoom the map or alike) and not a generic setting (which stays permanent). I would not include a setting option for a transient setting like this (and I also don't think we need it as permanent preference which would be the alternative).

**Comment by moving-bits** [comment]
Updated the PR / removed the menu entry

**Comment by Lineflyer** [comment]
@moving-bits 
Now that you removed the setting (Thanks!) my open question would be:
Does this anti-supersize if you click on it or how did you handle disabling?

**Comment by Lineflyer** [comment]
Include on `master` before beta?

**Comment by moving-bits** [comment]
> Does this anti-supersize if you click on it or how did you handle disabling?

Yes

> Include on `master` before beta?

Yes :-)

**Comment by geocachermgo** [comment]
Note: with google map or satelit the supersize setting by click on the number is not changed until I move the map. With OSM or offline map the change is done immediatly.

**Comment by moving-bits** [comment]
> Note: with google map or satelit the supersize setting by click on the number is not changed until I move the map. With OSM or offline map the change is done immediatly.

This is one of several inconsistencies between the two map types, since they have pretty different technical architectures internally. Hopefully most of this gets healed after merging GM and OSM into the (as-much-as-possible) same architecture as proposed by @rsudev.

**Pull request merged**
