### PR TITLE
update checkstyle

### PR DESCRIPTION
**Pull request by bekuno**
## Description

set checkstyle in AS to version 8.44 (which is also used on codacy)

## Additional context

maybe related to #11261

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
Set WIP for now.
The gradle checkstyle task must also be adopted. There where changes in gradle for checkstyle >= 8.42.

**Comment by Lineflyer** [comment]
Remark: While checking Codacy I have seen its using 8.44 already for their analysis of our PRs.

**Comment by bekuno** [comment]
> Remark: While checking Codacy I have seen its using 8.44 already for their analysis of our PRs.

See the PR description. ;-)

**Comment by Lineflyer** [comment]
> > Remark: While checking Codacy I have seen its using 8.44 already for their analysis of our PRs.
> 
> See the PR description. ;-)

Ups ;)

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
It looks like the CI checkstyle run did not work properly before.
Now the [INFO] messages for [UnnecessaryParentheses] are shown.
(see e.g. https://ci.cgeo.org/job/cgeo%20pull%20request/6659/console)

As these messages are categorized as priority low
image
I changed the CI PR configuration to only analyze the results for priority normal and high.

~~~
[CHECKSTYLE] Successfully parsed file /home/jenkins/slave/workspace/cgeo pull request/main/build/reports/checkstyle/checkstyle.xml with 267 unique warnings and 0 duplicates.
[CHECKSTYLE] Plug-in Result: Success - no threshold has been exceeded
~~~

This could be reverted after all violating files (currently 38) are annotated or changed.
As alternative we can also change the other CI configurations.

**Comment by bekuno** [comment]
lets now test live.

**Comment by eddiemuc** [comment]
I propose PR #11425 to reduce the number of false positives significantly

**Comment by eddiemuc** [comment]
Reduced to 206 by PR #11425. But that's not enough.

image

**Comment by bekuno** [comment]
But only on 15 files from 38 before.

**Pull request merged**
