### PR TITLE
fix #10393: introduce null-check on file list

### LINKED ISSUE #10393: NPE when starting (Test) app
The following NPE occured on a local test.

## Bug description 
~~~
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: cgeo.geocaching, PID: 2335
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at cgeo.geocaching.storage.LocalStorage$MigrateTask.doInBackgroundInternal(LocalStorage.java:443)
        at cgeo.geocaching.storage.LocalStorage$MigrateTask.doInBackgroundInternal(LocalStorage.java:401)
        at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.doInBackground(AbstractAsyncTaskWithProgress.java:134)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
~~~

## Reproduce 

Not sure what was the trigger.

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #10393: introduce null-check on file list

### CODE REVIEW

**Comment by fm-sys** [comment]
Wouldn't this be something for `release`?

**Comment by eddiemuc** [comment]
Hm don't know...
If I change base of PR to "release", then it seems to pull in all kinds of unrelated changes. So I would for now rahter prefer to keep it at master. If release is needed I fear I have to redo it.

**Comment by fm-sys** [comment]
@eddiemuc FYI, you can rebase a PR from master to release easily with following git commands (BTW, thanks to @UniQP! I think you had posted this command some time ago):

`git rebase --onto release master` and `git push --force-with-lease` afterwards

**Comment by eddiemuc** [comment]
@fm-sys thanks, works like a charm! I rebased to release

**Comment by eddiemuc** [comment]
Same here, Jenkins seems to build this PR continuously in a loop even after a green state was reached.
I will merge this now based on green Jenkins build 5454 (https://ci.cgeo.org/job/cgeo%20pull%20request/5454/)

**Pull request merged**
