### PR TITLE
fix #7078: give closeout status to Android < 4.1

### LINKED ISSUE #7078: No login to geocaching.com with Android 4.0.3
Since a few days it is not longer possible to login to geocaching.com.
Error message: "Anmeldung fehlgeschlagen: Verbindung zu Geocaching.com konnte nicht hergestellt werden (Server oder Verbindung inaktiv?)"
Does not work with the newest 2018.06.26 as well as the older 2018.02.05
Seems to be a problem with the Android 4.0.3 version (https-Login?) on the HTC one V; because in Android 8.0 it works well with the same account.
Unfortunatly one day before starting to holidays... Should buy a newer smartphone...

### PR DESCRIPTION
**Pull request by samueltardieu**

### CODE REVIEW

**Comment by samueltardieu** [comment]
Can be merged either to release or master (or first to master then to release after a trial period).

**Comment by Lineflyer** [comment]
As I do not own any device on Android 4.0 I cannot test, however it looks straight forward and the same code used to work for the older versions.

Feel free to merge to `release`.

**Comment by samueltardieu** [comment]
Merged to `release` then to `master`.

**Comment by Lineflyer** [comment]
Thanks @samueltardieu !

**Pull request merged**
