### PR TITLE
OSM offline map files downloader (fix #8610)

### LINKED ISSUE #8610: Ease onboarding with offline maps, part 2
This is part two to ease onboarding with offline maps for new users of c:geo, in addition (or as partial replacement) of #8180/#8183:

- add a link to the map selector: "Download offline maps"
- which opens a directory listing of the Mapsforge server (actually its mirror at fh-esslingen.de)
- You can browse through the directories up and down and select a file (map) to download.
- Map file gets downloaded in the background using Android's download manager.
- On completion the map file gets copied into c:geo map directory and activated as current map. (as in #8183).

This is how it looks like:

New menu entry "Download offline map" in map selection menu:
image
(the thin separator line is available on Android 10+ only)

Retrieved the initial listing of the v5 map directory:
image

Retrieving a sub directory, "Australia-Oceania" in this case:
image

For downloadable map files size and date of last change are shown:
image

When you select a map for downloading, you get a short notification that the download starts in the background. You can continue to work with c:geo until the download has finished:
image

When the download has finished the file gets copied to c:geo map dir automatically:
image

Finally you get a confirmation that the download has succeeded:
image
The newly downloaded map gets activated as current map automatically.

---

Current state of this PR is beta. Next steps are:
- creating and merging the "extension table" PR, which is a prerequisite
- a bit of minor roundup on this, then creating "map download" PR
- testing, testing, testing, ...

Any feedback is very welcome.

### PR DESCRIPTION
**Pull request by moving-bits**
For detailed description and screenshots see #8610

### CODE REVIEW

**Comment by moving-bits** [comment]
> copying the downloaded file makes less sense from what I understand. Please move the file to the correct map directory instead. Thats faster and saves disk space. Or isn't that possible due to the android permissions?

I'm not sure regarding permissions, but the main reason I'm not moving the file is that renaming/moving only works as long as source and target files are on the same mount points. To my understanding Anrdoid standard download folder is on internal storage, and many (most?) users will store c:geo data an sdcard (which would be a different mount point). What I can try is renaming first, see if it works, and do a copy only on failure to rename.

Regarding storage space: Downloaded files are managed by Android, and deleted automatically on running out of space (AFAIK).

**Comment by Lineflyer** [comment]
Shouldn't we make this available from map settings menu as well?

**Comment by moving-bits** [comment]
> Shouldn't we make this available from map settings menu as well?

Yes - this is the function I would like to put behind the "map icon" button we've searched a couple of days ago...

**Comment by Lineflyer** [comment]
> Yes - this is the function I would like to put behind the "map icon" button we've searched a couple of days ago...

Excellent...today I was already looking there

**Comment by moving-bits** [comment]
> > Yes - this is the function I would like to put behind the "map icon" button we've searched a couple of days ago...
> 
> Excellent...today I was already looking there

See #8724.

**Pull request merged**
