### PR TITLE
Support gpx v1 1 (fix #7147)

### LINKED ISSUE #7147: Support import of GPX 1.1
##### Detailed steps causing the problem:
- Import GPX file. See the attachment.
[GC7BFGC.zip](https://github.com/cgeo/cgeo/files/2430620/GC7BFGC.zip)

##### Actual behavior after performing these steps:
- Only basic information are imported. See the attachment.
screenshot_2018-09-29-14-08-27-360_cgeo geocaching

##### Expected behavior after performing these steps:
- Groundspeak and Gsak data should be imported as well

##### Version of c:geo used:
2018.09.17

Other applications have no problem with that GPX file. Am I missing something here?
Thank you.

### PR DESCRIPTION
**Pull request by murggel**
## Description

Support new elements for linkType / url for GPX V1.1
Support not correct gpx1.1 extension-position (be tolerant on reading, if extensions are under the node as in GPX V1.0)

## Related issues

fix #7147

### CODE REVIEW

**Comment by moving-bits** [comment]
@murggel 
In case you're wondering why we do not merge this PR / not sure if you have noticed already: Your PR has conflicting changes that need to be resolved before we can merge it.

**Comment by murggel** [comment]
> @murggel
> In case you're wondering why we do not merge this PR / not sure if you have noticed already: Your PR has conflicting changes that need to be resolved before we can merge it.

thanks for the hint, did not recognized the merge conflicts... is there any way to see that in the overview?

**Comment by moving-bits** [comment]
> thanks for the hint, did not recognized the merge conflicts... is there any way to see that in the overview?

Not that I know of. AFAIK you can only see them by opening the PR page and looking at the last block. If there's the "triangle with exclamation mark" logo, the there's a conflict.

**Comment by murggel** [comment]
Merge conflicts are resolved now.

**Comment by eddiemuc** [comment]
@murggel many thanks for the contribution!

**Pull request merged**
