### PR TITLE
Support other OSM based online map sources (fix #8148)

### LINKED ISSUE #8148: Support other OSM based online map sources
WhereYouGo supports more tile severs then only what we called "OSM:Mapnik":

- OSM:Mapnik
- OSM.de
- CyclOSM (could be a good replacement of the retired OpenCycleMap)
- Public Transport
- Esri world street
- Esri world Imagery (alternative to Google Satellite)

Tile source info can be found in cgeo/WhereYouGo code.

I have no idea whether these tile sources can really be freely used, but if this is the case we should support those (or a subset) also in c:geo.

### PR DESCRIPTION
**Pull request by moving-bits**
Extend our supported OSM based online maps by
- openstreetmap.de and
- cyclosm.org

Avaialble for NewMap only.
Also renamed "OpenStreetMap" to "OpenStreetMap.org" to distinguish from "OpenStreetMap.de".

Example screen shots:

OpenStreetMap.org (aka "OSM:Mapnik")
image

OpenStreetMap.de:
image

CyclOSM.org:
image

### CODE REVIEW

**Comment by moving-bits** [comment]
"Help wanted":

Current implementation seems to work fine so far, with one caveat which I haven't been able to tackle yet: After switching between two of the three OSM online services the map stays blank until you close and reopen the map. (This does not happen when switching from an online based map to an offline based map and vice versa.) So there seems to be one additional step needed.

**Comment by SammysHP** [comment]
Do you have a permission for us to use these maps?

cyclosm.org:

> A Tile Map Service is available at <code>https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png</code> under a <a href="https://operations.osmfoundation.org/policies/tiles/">fairuse tile policy</a>.

https://operations.osmfoundation.org/policies/tiles/:

> Heavy use (e.g. distributing an app that uses tiles from openstreetmap.org) is forbidden without prior permission from the Operations Working Group.

openstreetmap.de has something similar:

https://www.openstreetmap.de/germanstyle.html

> Das Einbinden der Kacheln in eigene Webseites können wir aufgrund der begrenzten Bandbreite leider nur für nichtkommerzielle Zwecke erlauben. Kleinere Webanwendungen, wie z.B. der Anfahrtsplan auf der Firmenwebseite dürfen die Kacheln selbstverständlich verwenden. Bitte beachten sie auch die Tile usage policy.

**Comment by moving-bits** [comment]
> Do you have a permission for us to use these maps?

Both new sources refer to the identical policy we already have for our current OSM online tile server, and attribution notes have been extended to list the two new sources.

**Comment by moving-bits** [comment]
retest this please

**Comment by SammysHP** [comment]
> Both new sources refer to the identical policy we already have for our current OSM online tile server

And nobody said that it is OK what we do. ;)

**Comment by moving-bits** [comment]
> And nobody said that it is OK what we do. ;)

The comment https://github.com/openstreetmap/operations/issues/371#issuecomment-598016057 can be read as a "temporarily ok, until we say otherwise".

This PR intends to reduce load on that server by distributing it over several different sources, hopefully resulting in low/acceptable load for all servers involved.

#8180 tries to help new users to configure offline map sources more easily to make more users of c:geo use offline maps.

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
