### PR TITLE
optimize space usage in search activity

### PR DESCRIPTION
**Pull request by ztNFny**
Restyling the search dialog by removing the 3-times duplicated information what to search by turning the button into an icon button

before:
image

after:
image

### CODE REVIEW

**Comment by fm-sys** [comment]
Like it! 

We could try how it looks if we align the button and textfield height as done in the variables tab as well... Not sure if this will look better though. 

Screenshot_20241116-091442

**Comment by ztNFny** [comment]
> We could try how it looks if we align the button and textfield height as done in the variables tab as well... Not sure if this will look better though.

tbh I'd rather prefer to reduce the height of those text fields, they are way oversized in my opinion... but that's a change probably too radical for c:geo

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
i've removed the restyling of section headers from this PR - I'm working on this in a broader context and it doesn't make sense to introduce parts of it here

**Comment by eddiemuc** [comment]
Can I merge this one?

**Comment by ztNFny** [comment]
> Can I merge this one?

yes please. additional changes will/might be in https://github.com/cgeo/cgeo/pull/16358

**Comment by ztNFny** [comment]
rebased

**Comment by bekuno** [comment]
retest this please

**Pull request merged**
