### PR TITLE
osm.paws.cz - new mapsforge maps source

### PR DESCRIPTION
**Pull request by osmpaws**
## Description
Add in-app download option for another (mapsforge) offline map source - osm.paws.cz

## Related issues
#13273 

## Additional context
Map and theme download is working, I have done some tests by myself with Android Studio. Whole new code is derived from existing. There is also source code for theme legend that is not done and is still almost original. However the option to show theme legend is not really in the menu for some reason. So this source code file can be removed or stay until I will finish it.

### CODE REVIEW

**Comment by Lineflyer** [comment]
ok to test

**Comment by moving-bits** [comment]
Thanks @osmpaws for your contribution, highly appreciated!

> However the option to show theme legend is not really in the menu for some reason.

This is a bit tricky with our current OSM maps implementation. Have a look at `maps/mapsforge/v6/legend/RenderThemeLegend.java:supportsLegend()` and `maps/mapsforge/v6/RenderThemeHelper.java:RenderThemeType`.

**Comment by osmpaws** [comment]
Legend for theme works, I am done for now.

**Comment by moving-bits** [comment]
Found time today to do a quick test: Seems to work very well, thanks @osmpaws for your contribution, very welcomed!

Only glitch I've found so far is automatic theme download, which does not work (results in a "404" error).

To test this:
- remove your paws theme from your themes folder (including companion file)
- download a map (but no theme) from paws server using the downloader
- theme download gets started automatically by c:geo, but fails with a 404 error

This is triggered by `getExtrafile()` method in `MapDownloaderPaws.java`.

**Comment by osmpaws** [comment]
Hi, thanks @moving-bits for testing, I just forgot to return to this issue. The URL is correct now.

**Comment by Lineflyer** [comment]
@osmpaws Can you try to rebase your PR to current head of `master`?

**Comment by Lineflyer** [comment]
> @osmpaws Can you try to rebase your PR to current head of `master`?

Nevermind...strange enough Github cannot do a rebase merge but only a squash merge. Never saw this situation on the UI.

**Comment by moving-bits** [comment]
> > @osmpaws Can you try to rebase your PR to current head of `master`?
> 
> Nevermind...strange enough Github cannot do a rebase merge but only a squash merge. Never saw this situation on the UI.

This happens when a multi-commit PR has commits, which are no longer compatible with the base branch, but a later commit is (eg: because of a merge). In this case, I guess, the PR has not been rebased along the way, but only been aligned using a merge commit. Thus a squash will work, single commits not. But no problem in this case, as it will be squashed anyway.

**Comment by moving-bits** [comment]
> Hi, thanks @moving-bits for testing, I just forgot to return to this issue. The URL is correct now.

Works like a charm now, thanks for fixing automatic theme download, and thanks for your contribution!

**Pull request merged**
