### PR TITLE
rel. to #14113 - Showcase: new architectural design for unified map

### PR DESCRIPTION
**Pull request by fm-sys**
@eddiemuc @moving-bits 

As discussed in #14113, here is the promised example.

I started decoupling different layers related to current user's position. I would be really interested to get some feedback what you think about this concept.

### CODE REVIEW

**Comment by eddiemuc** [comment]
Let's see if I understood the use case correctly:
* In the heart of your change there's the new UnifiedMapViewModel class whose aim it is to provide all (unified-)map-related data using the mutuallivedata-pattern
* As a first example you implemented provisioning of the Location/Heading data which is used in many places inside the map
* You also used this first example of mutual live data to provide new layer versions to paint using this info:
  * a new PositionLayer which paints positionMarker and accuracy circle
  * a new PositionHistoryLayer which paints the (optional) history trail available in c:geo
  
Correct?

My short feedback to your showcase: I like the pattern very much! I would be all in favor to use it for UnifiedMap.

Two things I noticed (both not relevant for the general decision to use this new pattern):
* In PositionLayer you created two instances of GeoItemLayer, each storing exactly one geoobject (one for positionmarker, one for accuracy circle). While I assume that this works, GeoItemLayer was not optimized for holding only one single element. Each GeoItemLayer will create own thread logic with own thread time scheduling to update map objects, and this introduces some overhead which would not be justified if such a layer would be created for single items only. It would be better to group several items into one GeoItemLayer (in this case: use same layer instead of creating a second one). GeoItemLayer instances can even be shared between "logical" layers as long as keys are not duplicated between them.
* PostionHistoryLayer contains business logic: the storing of trail history. Maybe we can find a way to put this logic also into the View Model

Great work! All in favor!

**Comment by fm-sys** [comment]
Thanks for the nice feedback :) 

> Let's see if I understood the use case correctly

Yes, exactly. You summarized it pretty well 👍 (sorry that I was too lazy to document it myself)

> In PositionLayer you created two instances of GeoItemLayer, each storing exactly one geoobject

If I understand it correctly, the z-order can currently be set on a per-layer basis only. (or did I missed something?) But yes, this can and should probably be changed...

> PostionHistoryLayer contains business logic

Good catch! Just didn't had an idea how to do it better... Will give it a try.

**Comment by moving-bits** [comment]
Can't say much about the Android frameworks involved here (don't know them yet in detail), but unifying code across different map types is what `UnifiedMap` is all about, and the nice new GeoItemLayer gives the measures to do that in this case. Also using methods provided by Android framework for maintaining state etc. instead of doing that on our own, using lots of "boilerplate code", seems to be very reasonable. So very much appreciated what you have started in your showcase!

Just we should test the results thoroughly, as we have introduced new Android mechanisms in other places in the past, and suddenly all kind of errors pop up - very likely not coming from the new code, but from "glueing" new architectural principles and pretty old legacy code in those places (eg. database IllegalStateException, SQLiteDatabaseLockedException in different places).

**Comment by fm-sys** [comment]
> Just we should test the results thoroughly, as we have introduced new Android mechanisms in other places in the past, and suddenly all kind of errors pop up - very likely not coming from the new code, but from "glueing" new architectural principles and pretty old legacy code in those places (eg. database IllegalStateException, SQLiteDatabaseLockedException in different places).

You are probably talking about problems like e.g. #13166. These things are not necessarily related to glueing new architectural principles and pretty old code in general, but are probably just accidental mistakes which of course will break the code. This can happen easily, however isn't related to new architecture components but can happen at any time when doing refactoring. 

What I want to say: 
I do not believe that my code is without errors (on the contrary), but all problems which might arise should be solvable without ugly hacks. 

But for sure, testing it thoroughly is important ;-)

**Comment by eddiemuc** [comment]
>> In PositionLayer you created two instances of GeoItemLayer, each storing exactly one geoobject

> If I understand it correctly, the z-order can currently be set on a per-layer basis only. (or did I missed something?) But yes, this can and should probably be changed...

Correct. I thought this was ok since this is how layers are used today in the "old" map implementation.
If this is a too-hard restriction, then setting a z-Level can be moved towards GeoItem/GeoPrimitive. Implementation for GoogleMaps is super-easy (Google Maps sets the z-level per item anyway), Mapsforge/VTM I would have to look into but should be doable.

**Comment by fm-sys** [comment]
> > PostionHistoryLayer contains business logic
> 
> Good catch! Just didn't had an idea how to do it better... Will give it a try.

Ok, I came up with a solution. I moved the `PositionHistory` object into the view model (wrapping it with `MutableLiveData` as well). If it's set to `null` the position history gets hidden, otherwise it will contain the current `PositionHistory` object. The layer itself now only contains drawing, everything else is handled at other places.

**Comment by fm-sys** [comment]
How do we want to proceed further? 

For sure, there is still very much to do... Refactor drawing of caches, track, route, distance view which are the things already implemented to unified map. And then all the rest, which is still missing.

However, from my side this PR should be ready. So I would suggest merging it, and collaborate further on `master` branch.

**Comment by moving-bits** [comment]
Let's get this into the nightlies for further collaboration. Thanks @fm-sys for diving into this!

**Comment by fm-sys** [comment]
Just for info (and to avoid unnecessary work):

I'm currently working on a refactored tracks layer based on geoitemlayer and this new design concept

**Comment by moving-bits** [comment]
> I'm currently working on a refactored tracks layer based on geoitemlayer and this new design concept

Great, thanks! I'll then wait with implementing a "isRoundtrip" flag for individual routes (as proposed in https://github.com/cgeo/cgeo/issues/14027#issuecomment-1501084361) until new track layer is in to avoid unnecessary implementation work.

**Comment by fm-sys** [comment]
> I'll then wait with implementing a "isRoundtrip" flag for individual routes (as proposed in https://github.com/cgeo/cgeo/issues/14027#issuecomment-1501084361) until new track layer is in to avoid unnecessary implementation work.

Up to now, I've only touched track handling, not yet the individual route. But even when refactoring the individual route as well, it will most likely not affect each other... So you can work on "linear route optimization" if you like :)

**Pull request merged**
