### PR TITLE
remove legacy filter access, see #11086 for next steps

### PR DESCRIPTION
**Pull request by eddiemuc**
remove legacy filter access, see #11086 for next steps

This PR will remove the possibility to access the legacy filter from c:geo cache list. It will NOT remove the associated filter code from c:geo. The later shall only be done after it was proven (e.g. via beta or release) that this functionality really can be removed.

For the removal of the filter legacy code, issue #11086 was created

### CODE REVIEW

**Comment by eddiemuc** [comment]
@Lineflyer this is the PR as requested at https://github.com/cgeo/cgeo/issues/10922#issuecomment-873474926

**Comment by eddiemuc** [comment]
I consider this PR as "closing" for #10952

**Comment by moving-bits** [comment]
failing test is unrelated, but one unused string resource (see CheckStyle)

**Comment by eddiemuc** [comment]
Is Codacy down?

**Comment by eddiemuc** [comment]
> failing test is unrelated, but one unused string resource (see CheckStyle)

fixed and force-pushed

**Comment by eddiemuc** [comment]
> failing test is unrelated, but one unused string resource (see CheckStyle)

I also changed the failing test code a bit. It will still fail/pass in same situations as before, but it will provide a little more info in case of fail (in this case: the actual external storage state)

**Comment by eddiemuc** [comment]
I took a quick look at codacy. For some reason, automatic analysis on all branches (including master and release) is disabled. Also, I can't enable it again - apparently one has to have "Admin" rights for the repository for this and I am not having this permission.

Can some "Admin" please enable analysis again?  Can be done here: https://app.codacy.com/gh/cgeo/cgeo/settings/branches

**Comment by moving-bits** [comment]
> Can some "Admin" please enable analysis again? Can be done here: [app.codacy.com/gh/cgeo/cgeo/settings/branches](https://app.codacy.com/gh/cgeo/cgeo/settings/branches)

From what I can see analysis for both `master` and `release` is enabled, at least the slider is in the "on" position (or at least in a different position as for all other branches):

image

But I've no admin rights either, so I cannot check any further.

@Lineflyer / @bekuno: Can you have a look at Codacy?

**Comment by eddiemuc** [comment]
> > Can some "Admin" please enable analysis again? Can be done here: [app.codacy.com/gh/cgeo/cgeo/settings/branches](https://app.codacy.com/gh/cgeo/cgeo/settings/branches)
> 
> From what I can see analysis for both `master` and `release` is enabled, at least the slider is in the "on" position (or at least in a different position as for all other branches):

You're right, did not see that (I somehow expected the switch to also have a different color if it is in the "on" position). 

I found out more:
* This page explains which permissions one is supposed to have in Codacy. Apparently this depends on the permissions one has in the github repo: https://docs.codacy.com/organizations/roles-and-permissions-for-synced-organizations/#change-analysis-configuration 
* Apparently there are 10 PR analysis currently running in parallel for quite some time now. Seem to be "hanging". Maybe there's a maximum capability set for analysis  to run in parallel: https://app.codacy.com/gh/cgeo/cgeo/pullRequests?step=0

I tried to abort some of the older analysis runs to see if this makes codacy run newer PR analysis. But I didn't find a way to do that

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
