### PR TITLE
For #7030 - Use vector material design icons

### LINKED ISSUE #7030: Redefining UI
Hey guys,
I've been using c:geo a few years ago a lot then I've stopped and today I've installed it again.
What a surprise for me was the same UI as before. In the evening I've got some contribution desire and I've sketch some ideas to improve UI of the app. The icons are Google material icons. I'm not a graphic designer but I work in automotive and my main focus is on wireframing and prototyping car UIs.

So if you like the concept feel free to contact me and I can make more screens or start work on html prototype that you can use as a guideline for the graphic designer and then for implementing UI into the app. 

sum

### PR DESCRIPTION
**Pull request by NotWoods**
Fixes #7030

** Description of change: **

This is a big PR that replaces most of the `ic_menu_*` icons with vector drawables pulled from https://materialdesignicons.com.

To work with API 16-20, the vector drawable compat library is used.

This helps unify the UI design a lot since the icons now converge into a single style rather than having designs from Gingerbread, Ice Cream Sandwich, and Lollipop. I plan to follow up with custom icons in the future.

** Screenshot (if applicable): **
Screen Shot 2019-09-15 at 10 50 38 PM
Screen Shot 2019-09-15 at 10 50 32 PM
Screen Shot 2019-09-15 at 10 50 27 PM

### CODE REVIEW

**Comment by Lineflyer** [comment]
add to whitelist

**Comment by moving-bits** [comment]
retest this please

**Comment by bekuno** [comment]
I love the proposed solution of switching to Vector Images as much as possible.
We are currently on the way to targetSdk/compileSdk/libraries to version 28. Let's do this switch first.
After that it would be easier to test and integrate your big work.

**Comment by bekuno** [comment]
@NotWoods 

~~~
Execution failed for task ':main:processBasicDebugAndroidTestResources'.

> Android resource linking failed
 /home/jenkins/slave/workspace/cgeo pull request/main/build/intermediates/merged_manifests/basicDebugAndroidTest/AndroidManifest.xml:22: AAPT: error: resource drawable/icon (aka cgeo.geocaching.test:drawable/icon) not found.
~~~

You removed the icon.png in
tests/res/drawable-hdpi/icon.png
tests/res/drawable-ldpi/icon.png
tests/res/drawable-mdpi/icon.png

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
@NotWoods please rebase your work to the current master

**Comment by Lineflyer** [comment]
retest this please

**Comment by moving-bits** [comment]
@Lineflyer 
Tests will break as long as your cache https://coord.info/GC3FJ5F is disabled :-)

**Comment by Lineflyer** [comment]
Ups... :) Will need another week to be enabled again. Right now the box is drying in my house :)

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
After the recent changes this build is back to green now. - This is a larger change, replacing many icons. Shall we merge this before our first targetSDK28 version or after? (Deadline set by play store for targetSDK28 is still more than two weeks to go.)

**Comment by bekuno** [comment]
I think we should wait after the first targetSdk 28 release.
Additionally, I saw on this PR again the icon problem in which I ran in PR https://github.com/cgeo/cgeo/pull/7335#issuecomment-468062895 on my latests tests.

**Comment by bekuno** [comment]
@Lineflyer 
Could you look at the suggestions for the new icon proposals?
There are many changes to the current icons. I'm not sure if they're all suitable replacements, or if we should take a look at other vector icons.

**Comment by moving-bits** [comment]
@NotWoods  

Thanks for your contribution. Moving from handmade bitmaps for every density to vector drawables (scalable & consistent look & feel) would be a very welcome step forward.

There are some crashes on older Android versions, though, which I would like you to recheck with Google Maps and Android 4.x, eg:

```
10-13 11:43:56.433 3412-3412/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 3412
    android.content.res.Resources$NotFoundException: File res/drawable/ic_menu_myposition.xml from drawable resource ID #0x7f070141. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
        at android.content.res.Resources.loadDrawable(Resources.java:2101)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at android.widget.CompoundButton.setButtonDrawable(CompoundButton.java:186)
        at cgeo.geocaching.maps.CGeoMap.onCreateOptionsMenu(CGeoMap.java:665)
        at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreateOptionsMenu(GoogleMapActivity.java:71)
        at android.app.Activity.onCreatePanelMenu(Activity.java:2538)
[...]
```
This one can be fixed (?) by changing line 665 in `maps/CGeoMap.java` from `myLocSwitch.setButtonDrawable(R.drawable.ic_menu_myposition);` to `myLocSwitch.setButtonDrawable(VectorDrawableCompat.create(getResources(), R.drawable.ic_menu_myposition, null));`

but there are followup errors like this one:

```
10-13 11:49:35.683 3633-3633/cgeo.geocaching E/VectorDrawableCompat: parser error
    org.xmlpull.v1.XmlPullParserException: Binary XML file line #2<vector> tag requires viewportWidth > 0
        at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:774)
        at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:711)
        at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:674)
        at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:656)
        at cgeo.geocaching.maps.CGeoMap.onCreateOptionsMenu(CGeoMap.java:666)
        at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreateOptionsMenu(GoogleMapActivity.java:71)
[...]
10-13 11:49:35.693 3633-3633/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 3633
    android.content.res.Resources$NotFoundException: File res/drawable/ic_action_layers.xml from drawable resource ID #0x7f070126. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
        at android.content.res.Resources.loadDrawable(Resources.java:2101)
        at android.content.res.Resources.getDrawable(Resources.java:700)
[...]
```

c:geo currently supports Android API levels starting with 16 / Android 4.1

Please have a look at those. While updating your PR please rebase to upstream/master and squash your commits. Thanks a lot!

**Comment by Lineflyer** [comment]
I would also vote for merging after we merged branches (meaning after the first targetsdk28 release).

**Comment by Lineflyer** [comment]
> @Lineflyer
Could you look at the suggestions for the new icon proposals?
There are many changes to the current icons. I'm not sure if they're all suitable replacements, or if we should take a look at other vector icons.

I think we could merge as is (later on as discussed above) and after testing in nightlies raise dedicated issues to discuss icons, which might not be suitable as replacement.

Setting "Do not merge" for the time being as discussed. As soon as we merged branches we can merge this PR.

**Comment by moving-bits** [comment]
@NotWoods

> Please have a look at those issues. While updating your PR please rebase to upstream/master and squash your commits. Thanks a lot!

We have merged the branches, preparing for our next release, so we're now ready to get your PR merged to the master branch, which is the next step in getting this feature out to the nightly versions.

Please have a look at the issues with older Android versions mentioned above and update your PR accordingly, rebasing to upstream/master and squashing your commits first. If you need help with any of those steps please feel free to ask.

**Comment by NotWoods** [comment]
I've updated that drawable call, although I'm not sure what tint to use to match with the rest of the action bar.

**Comment by moving-bits** [comment]
@NotWoods 
Thanks for updating. Still crashes for me (tested with Android Studio emulated Nexus 5X with API 17 and Google Maps). This is the full error message I receive directly after starting "Live Map", when map provider is set to Google Maps:

```
10-26 00:40:41.876 14295-14295/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    android.content.res.Resources$NotFoundException: File res/drawable/ic_menu_myposition.xml from drawable resource ID #0x7f070141. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
        at android.content.res.Resources.loadDrawable(Resources.java:1958)
        at android.content.res.Resources.getDrawable(Resources.java:660)
        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:465)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
        at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
        at cgeo.geocaching.maps.CGeoMap.onCreateOptionsMenu(CGeoMap.java:665)
        at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreateOptionsMenu(GoogleMapActivity.java:71)
        at android.app.Activity.onCreatePanelMenu(Activity.java:2490)
        at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:407)
        at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:769)
        at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:201)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
        at android.view.Choreographer.doFrame(Choreographer.java:531)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_menu_mylocation.xml from drawable resource ID #0x7f07013e
        at android.content.res.Resources.loadDrawable(Resources.java:1958)
        at android.content.res.Resources.getDrawable(Resources.java:660)
        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:173)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:885)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
        at android.content.res.Resources.loadDrawable(Resources.java:1955)
        at android.content.res.Resources.getDrawable(Resources.java:660) 
        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:465) 
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203) 
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191) 
        at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102) 
        at cgeo.geocaching.maps.CGeoMap.onCreateOptionsMenu(CGeoMap.java:665) 
        at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreateOptionsMenu(GoogleMapActivity.java:71) 
        at android.app.Activity.onCreatePanelMenu(Activity.java:2490) 
        at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:407) 
        at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:769) 
        at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:201) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:562) 
        at android.view.Choreographer.doFrame(Choreographer.java:531) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735) 
        at android.os.Handler.handleCallback(Handler.java:725) 
        at android.os.Handler.dispatchMessage(Handler.java:92) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
        at android.content.res.Resources.loadDrawable(Resources.java:1955)
        at android.content.res.Resources.getDrawable(Resources.java:660) 
        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:173) 
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:885) 
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822) 
        at android.content.res.Resources.loadDrawable(Resources.java:1955) 
        at android.content.res.Resources.getDrawable(Resources.java:660) 
        at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:465) 
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203) 
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191) 
        at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102) 
        at cgeo.geocaching.maps.CGeoMap.onCreateOptionsMenu(CGeoMap.java:665) 
        at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreateOptionsMenu(GoogleMapActivity.java:71) 
        at android.app.Activity.onCreatePanelMenu(Activity.java:2490) 
        at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:407) 
        at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:769) 
        at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:201) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:562) 
        at android.view.Choreographer.doFrame(Choreographer.java:531) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735) 
        at android.os.Handler.handleCallback(Handler.java:725) 
        at android.os.Handler.dispatchMessage(Handler.java:92) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
```

Going to a cache list works, and the new vector drawables are shown, but as soon as I open the map for the current cache, c:geo crashes with the same error.

**Comment by NotWoods** [comment]
I'm having trouble getting Google Maps as an option using the emulator (Nexus 5X, API 17 w/ Google Play services). Oddly Live Map works fine with the default provider.

The stack trace suggests that this line I added in `CgeoApplication.onCreate` is not getting called before the map menu is displayed.

```java
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
    }
```

Does the Google Map provider change how the Application class is called?

**Comment by moving-bits** [comment]
> I'm having trouble getting Google Maps as an option using the emulator (Nexus 5X, API 17 w/ Google Play services). Oddly Live Map works fine with the default provider.

Do you have an API key for Google Maps Android API v2? Without it you won't get Google Maps offered in c:geo.
I don't have the URL at hand - search for "Google Maps API key". The key itself is free, and you don't have to enter any credit card info, although the web form seems to force you to.
This key (actually a text string of about 60 characters) needs to be entered in a config file of c:geo (keys.xml IIRC) for c:geo to recognize it after the next build.
Then you can start debugging into GMv2 map implementation.

**Comment by moving-bits** [comment]
Additionally, see the following links regarding obtaining a GM API key:

- https://github.com/cgeo/cgeo (section on API keys, near bottom of page)
- https://developers.google.com/maps/documentation/android-sdk/get-api-key

**Comment by Lineflyer** [comment]
retest this please

**Comment by moving-bits** [comment]
@NotWoods  Did you get Google Maps working for you and have the time to fix the issue mentioned above?

@Lineflyer  Shall we merge this PR to master anyway, knowing that it includes at least one issue (crash) running under older Android versions, and start fixing it there?

**Comment by Lineflyer** [comment]
IMHO we should wait for the PR to be completely functional in itself.

**Comment by NotWoods** [comment]
I haven't had time yet to test the issue. I could potentially revert the affected icons for now to get the rest merged.

**Comment by Lineflyer** [comment]
> I haven't had time yet to test the issue. I could potentially revert the affected icons for now to get the rest merged.

@NotWoods 
Any news on this?

**Comment by NotWoods** [comment]
Updated to pass CI

**Comment by moving-bits** [comment]
Thanks for updating this PR. I did a very short smoke test using different Android versions. API 29 startup is fine, haven't tested any further yet, but using API 17 or 19 (= different versions of Android 4) c:geo immediately crashes on startup, you even don't get to see the main menu. LogCat is as follows:

```
04-09 14:06:56.243 7130-7130/? E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.MainActivity}: android.view.InflateException: Binary XML file line #152: Error inflating class ImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #152: Error inflating class ImageView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at cgeo.geocaching.activity.AbstractActivity.setContentView(AbstractActivity.java:161)
        at cgeo.geocaching.MainActivity.onCreate(MainActivity.java:265)
        at android.app.Activity.performCreate(Activity.java:5104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
        at android.app.ActivityThread.access$600(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_menu_info_details.xml from drawable resource ID #0x7f070147
        at android.content.res.Resources.loadDrawable(Resources.java:1958)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
        at android.widget.ImageView.<init>(ImageView.java:120)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:187)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:107)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) 
        at cgeo.geocaching.activity.AbstractActivity.setContentView(AbstractActivity.java:161) 
        at cgeo.geocaching.MainActivity.onCreate(MainActivity.java:265) 
        at android.app.Activity.performCreate(Activity.java:5104) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
        at android.app.ActivityThread.access$600(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
        at android.content.res.Resources.loadDrawable(Resources.java:1955)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:601) 
        at android.widget.ImageView.<init>(ImageView.java:120) 
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72) 
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68) 
        at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:187) 
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:107) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407) 
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) 
        at cgeo.geocaching.activity.AbstractActivity.setContentView(AbstractActivity.java:161) 
        at cgeo.geocaching.MainActivity.onCreate(MainActivity.java:265) 
        at android.app.Activity.performCreate(Activity.java:5104) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
        at android.app.ActivityThread.access$600(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by moving-bits** [comment]
@NotWoods 
We've just decided to drop support for Android version < 5.0 in our main release, so you can strip the legacy support layer in your PR, which should make things way easier. Also, if the PNG were needed only to support API level < 21, you may remove them as well.

**Comment by NotWoods** [comment]
Let's leave the legacy support in, because it fixes vector issues on Lollipop and Marshmallow. The PR should be good-to-go for 21+

**Comment by moving-bits** [comment]
Ok, then let's do it that way.

We're currently releasing, and there will be another minor release after that, containing the closeout notice for Android < 5.0 and some other minor improvements. As soon as that part is branched to release, we can continue here and merge this PR to master.

**Comment by moving-bits** [comment]
@NotWoods 
The "minor release after the April release" got a big bigger than expected, but now we are on the go with our "API 21+" version, and ready to merge your contribution. Can you rebase a last time to resolve the conflict in build.gradle? Thanks!

**Comment by fm-sys** [comment]
@NotWoods  Could you please rebase your PR, so that we can merge it and have enough time for testing

**Comment by Lineflyer** [comment]
retest this please

Job result seems inconclusive (No build running, but shown as pending)

**Comment by moving-bits** [comment]
Superseeded by #10818, let's close here, and restart with current master as base, if necessary.

**Pull request closed without merging**
