### PR TITLE
 fix to #6711 Copy WP coordinates in selectable format

### PR DESCRIPTION
**Pull request by Grobbo**
Added contextmenu for copying of waypoints coordinates on longclick just as in the main cache page.

### CODE REVIEW

**Comment by pstorch** [comment]
Test successfull, the solution works.

**Comment by pstorch** [comment]
test this please

**Comment by Grobbo** [comment]
Will fix the changes.

**Comment by pstorch** [comment]
ok to test

**Comment by pstorch** [comment]
@Grobbo what happened?

**Comment by Grobbo** [comment]
Sorry new to this..  made the changes and tried to squash the commits but made a mess of it will try to fix it then make another pull request.

**Pull request closed without merging**
