### PR TITLE
update gradle to 6.3

### PR DESCRIPTION
**Pull request by bekuno**

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
Failed twice with the same error:

```
22:16:51  * What went wrong:
22:16:51  Execution failed for task ':main:createBasicDebugAndroidTestCoverageReport'.
22:16:51  > java.io.IOException: No coverage data to process in directories [/home/jenkins/slave/workspace/cgeo pull request/main/build/outputs/code_coverage/basicDebugAndroidTest/connected]
22:16:51  
22:16:51  * Try:
22:16:51  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
22:16:51  
22:16:51  * Get more help at https://help.gradle.org
22:16:51  
22:16:51  BUILD FAILED in 7m 18s
```

**Comment by bekuno** [comment]
We can use the update to gradle 6.3.
There are many bugfixes.
Let's investigate the 6.4.x problem later.

**Comment by bekuno** [comment]
retest  this please

**Comment by bekuno** [comment]
retest this please

**Pull request merged**
