### PR TITLE
Revert "Bump core from 1.3.2 to 1.5.0"

### PR DESCRIPTION
**Pull request by bekuno**
Reverts cgeo/cgeo#10680

see https://ci.cgeo.org/job/cgeo%20pull%20request/5833/console
and Issue #10730

### CODE REVIEW

**Comment by bekuno** [comment]
Lets close, this was not the problematic PR.

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

note:
Strange problem:
~~~
> Task :main:testBasicDebugUnitTest

cgeo.geocaching.filter.SizeFilterTest > testFilteringPerformanceOnLargeListToLargeList FAILED
    org.junit.runners.model.TestTimedOutException at SizeFilterTest.java:94

426 tests completed, 1 failed
~~~

**Comment by eddiemuc** [comment]
> retest this please
> 
> note:
> Strange problem:
> ~~~
> > Task :main:testBasicDebugUnitTest
> 
> cgeo.geocaching.filter.SizeFilterTest > testFilteringPerformanceOnLargeListToLargeList FAILED
>     org.junit.runners.model.TestTimedOutException at SizeFilterTest.java:94
> 
> 426 tests completed, 1 failed
> ~~~

This happens from time to time. This is a performance test, it tests an operation which should not take more than a few hundred milliseconds. The test fails if this operation takes longer than 5 seconds. 

So in order for this to fail the CI must be **really** slow. But if we have to account for this then I am afraid we have to deactivate the test. 

That's dissatisfying though because I really think we should be able to write small performance tests as well.

**Pull request merged**
