### PR TITLE
#5349: fixed links in waypoints

### PR DESCRIPTION
**Pull request by rahu**

### CODE REVIEW

**Comment by Lineflyer** [comment]
Sounds reasonable and the changes sounds understandable even to me.
Merging therefore.

@rahu: Thanks for your contribution.

**Comment by Lineflyer** [comment]
@rahu: Please dp in furture use Fix #xxxx in your PR title to make sure the mentioned issue is autoclosed when merged.

**Comment by rahu** [comment]
Can  you please add this to the readme? How to create pr. ;)  thanks

**Comment by rsudev** [comment]
This is a general feature of github as such, not specific to c:geo...

**Pull request merged**
