### PR TITLE
test checkstyle on ci

### PR DESCRIPTION
**Pull request by pstorch**
Do not merge, it's just a test for checkstyle on CI.

### CODE REVIEW

**Comment by pstorch** [comment]
retest this please

**Comment by samueltardieu** [comment]
retest this please

**Comment by Bananeweizen** [comment]
I guess you cannot test the behaviour of codacy, before the configuration file is actually _merged_. I assume the web configuration there will only scan the default branch.

**Comment by pstorch** [comment]
@Bananeweizen maybe. To be sure I would have to push the config file into the master directly (just for a test).

**Comment by pstorch** [comment]
Any objection to testwise put a copy of the checkstyle.xml into the root directory on master?

**Comment by Lineflyer** [comment]
I dont mind what is going on on `master` at the moment, as I am busy with `release`

**Comment by pstorch** [comment]
retest this please

**Comment by pstorch** [comment]
No, it doesn't pick it up either :disappointed:

**Comment by pstorch** [comment]
I've send this as a question to the codacy team.

**Comment by kumy** [comment]
@pstorch I have also asked Codacy team on my side. They've just responded

> what is happening is that you are using suppressions that need internet connection, which due to security reasons we don't allow. 

Does this help?

**Comment by pstorch** [comment]
Got the same response. When checking the checkstyle.xml file, maybe it is this section:
```
<module name="SuppressionFilter">

  <property name="file" value="https://raw.githubusercontent.com/cgeo/cgeo/master/main/project/checkstyle/suppressions.xml"/>

</module>
```

Maybe we can use relativ paths instead of a URL. I'll try tonight.

**Comment by pstorch** [comment]
@UniQP let's try with rebased from master

**Comment by pstorch** [comment]
\o/

**Comment by pstorch** [comment]
Now the question, if we can live with a global checkstyle.xml file for the whole project. At the moment we have different for different modules.

**Comment by UniQP** [comment]
What happens if we revert the commit that moved the checkstyle.xml to the root directory?

**Comment by pstorch** [comment]
we can try

**Comment by pstorch** [comment]
retest this please

**Comment by pstorch** [comment]
Hmm, now Jenkins doesn't check the checkstyle and codacy doesn't show up here at all.

**Comment by pstorch** [comment]
retest this please

**Comment by pstorch** [comment]
Looks like codacy doesn't pick up the checkstyle.xml if it is not in the project root.

Looking at how the other modules use the checkstyle config:

nine-old-androids is already referencing a checkstyle.xml in the project root:
```
nine-old-androids/pom.xml
40: <configLocation>${project.basedir}/../checkstyle.xml</configLocation>
```

The main module is the only module which has it's own checkstyle.xml.
```
main/build.gradle
598: configFile file("${project.rootDir}/main/project/checkstyle/checkstyle.xml")

main/.checkstyle
4: <local-check-config name="cgeo checkstyle" location="project/checkstyle/checkstyle.xml" type="project" description="">
```

viewpagerindicator referencing the checkstyle.xml in the root, but from a maven pom, which we don't execute, right?
```
viewpagerindicator/pom.xml
44: <configLocation>../checkstyle.xml</configLocation>
```

cgeo-contacts plugin referencing a checkstyle.xml which doesn't exist.
```
cgeo-contacts/.checkstyle
4: <local-check-config name="cgeo checkstyle" location="/cgeo/project/checkstyle/checkstyle.xml" type="project" description="">
```

The tests module is also referencing a checkstyle.xml which doesn't exist.
```
tests/.checkstyle
4: <local-check-config name="cgeo checkstyle" location="/cgeo/project/checkstyle/checkstyle.xml" type="project" description="">
```

Maybe it is ok, to move the checkstyle.xml into the project root and reference it there from all module.

**Comment by UniQP** [comment]
Ok, then let's move the checkstyle.xml to the root directory.

Since, checkstyle works with codacy now, we don't need to check it in our own CI.

**Comment by pstorch** [comment]
retest this please

**Comment by pstorch** [comment]
Looks good to me. Codacy and gradle build work with checkstyle.xml in project root.
Have disabled the checkstyle warning report from Jenkins, because that is duplicate now.

**Comment by pstorch** [comment]
closing here

**Comment by Bananeweizen** [comment]
I'll revert all your changes on .checkstyle files. Those are Eclipse specific, and worked quite well before...

**Comment by pstorch** [comment]
@Bananeweizen oh, sorry for that. Is `/cgeo/project/checkstyle/` a path on your local system? It's not in the repo.

**Pull request closed without merging**
