### PR TITLE
configuration for AS3.3 with gradle plugin 3.3 and gradle 4.10.2 (fix #7237)

### LINKED ISSUE #7237: AS 3.3 Build errors
##### Detailed steps causing the problem:
- Install/Upgrade Android Studio to version 3.3

##### Actual behavior after performing these steps:
Build works not more. Maybe from this error:
"D:\git\cgeo\main\build\intermediates\incremental\mergeBasicDebugResources\merged.dir\values\values.xml:3609: AAPT: error: resource android:attr/preserveIconSpacing is private.
error: failed linking references.
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create(Aapt2Exception.kt:45)
...
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed"

##### Expected behavior after performing these steps:
Gradle sync/Build with warnings as before

##### Version of c:geo used:
current master branch

##### Is the problem reproducible for you?
Yes

##### System information:
-

##### Other comments and remarks:
I think this point in GradleSync is the reason:
"WARNING: The following project options are deprecated and have been removed: 
android.enableAapt2
This property has no effect, AAPT2 is now always used.
Affected Modules: cgeo-contacts, main, mapswithme-api"

Maybe also this point:
"WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: main"

### PR DESCRIPTION
**Pull request by bekuno**
Adjust gradle with AS 3.3.
Use the gradle plugin 3.3 and gradle 4.10.2.

### CODE REVIEW

**Comment by kumy** [comment]
Jenkins: ok to test

**Comment by Lineflyer** [comment]
Retest this please

**Comment by Lineflyer** [comment]
Add to whitelist

**Comment by UniQP** [comment]
@bekuno Can you rebase to current master and squash the two commits into one?

**Comment by bekuno** [comment]
rebased and ready to merge.

**Comment by UniQP** [comment]
Thanks

**Pull request merged**
