### PR TITLE
userName/displayName in different meaning in GC and OC

### LINKED ISSUE #7998: "Caches hidden" fails to load with customized "cache owner" name
**Describe the bug:**
When viewing cache details, selecting "Caches hidden" from the CO name menu, fails to load when CO have specified a custom username for the currently displayed cache.

While I'm not sure, it seem as though "Caches hidden" tries to load the caches of a user with the username displayed for av given a cache. The displayed **name** for a CO, isn't necessarily the same as the username associated with a cache. The CO name is a free form name, on a cache by cache basis. All caches are still associated with a specific account/user, this should be used to load the caches hidden.

**To Reproduce:**
1. Open cache details for a cache with customized CO name
2. Click cache owner and select "Caches hidden"

**Actual behavior/state after performing these steps:**
c:geo tries to load caches hidden by a user with the displayed name. 

**Expected behavior/state after performing these steps:**
Caches hidden by the proper CO should be loaded.

**Version of c:geo used:**
2019.11.28

**Is the problem reproducible:**
Yes

**Additional context:**
This bug was introduced some time back, maybe a couple of months.

### PR DESCRIPTION
**Pull request by bekuno**
Set to the old behavior - works for GC, works not for OC, unknown for other cache connectors
needs to create a better solution for all connectors

fixes #7998: "Caches hidden" fails to load with customized "cache owner" name
revert #7125: Owner actions not working
revert #7818: different usage of userName and displayName

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by bekuno** [comment]
false base branch - create new PR

**Pull request closed without merging**
