### PR TITLE
Save button:  Show a "Save" icon when coordinates are invalid.

### PR DESCRIPTION
**Pull request by S-Bartfast**
As part of #6716 it was necessary to determine earlier whether the results of the calculation were valid or not so I figured we might as well use this knowledge to modify the "Done" button at the top right of the dialogue.  This button now displays the original "tick" wen the results are valid and a 'save' icon when the results are not.

This work could well lead to a cleaner operation in regard to saving the waypoint data in general, as discussed in #6696.

### CODE REVIEW

**Comment by SammysHP** [comment]
This PR contains PR #6729, #6730 and #6731.

**Comment by kumy** [comment]
Jenkins test this please

**Comment by pstorch** [comment]
@S-Bartfast I try to sort it out locally

**Comment by pstorch** [comment]
@S-Bartfast I've merge (cherry-picked) the relevant commits locally. So I'm closing here. Thanks for your contribution.

**Pull request closed without merging**
