### PR TITLE
Unifiedmap / GeoItemLayer: enhance zlevel support

### PR DESCRIPTION
**Pull request by eddiemuc**
Unifiedmap / GeoItemLayer: enhance zlevel support

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR enhances zlevel support for geoitem layer: it is now possible to set a zlevel per geoprimitive.

Unfortunately VTM (and Mapsforge) don't support zlevel very good. This is why I introduced a new helper GroupedList which helps maintain a priorized list (ordered by zlevel) and use this as a wrapper for VTM/Mapsforge layers list

**Comment by eddiemuc** [comment]
@moving-bits : I changed some things in the logic how layers are created for VTM. Basically I tried to change from a list index approach towards a group / zlevel approach. It would be great if you could take a look especially at those changes (in MapsforgeVtmView, methods "addLayerToGroup" and "addLayer")

**Comment by moving-bits** [comment]
> @moving-bits : I changed some things in the logic how layers are created for VTM. Basically I tried to change from a list index approach towards a group / zlevel approach. It would be great if you could take a look especially at those changes (in MapsforgeVtmView, methods "addLayerToGroup" and "addLayer")

Layer handling for VTM was only introduced this way to create _some basic_ support for z-level sorting. You can completely rearrange it, remove functions or create new ones if required.

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
Codac analyze is green on codacy server. Don't know why this is not reflected in this PR

**Comment by moving-bits** [comment]
> Codac analyze is green on codacy server. Don't know why this is not reflected in this PR

I've updated on Codacy side (although it was already "green" over there), but again status did not get transferred to GitHub

**Pull request merged**
