### PR TITLE
rel to #11261: dummy pr to create codacy warning

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #11261: dummy pr to create codacy warning

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR has the sole purpose to create a codacy warning. DO NOT MERGE!

**Comment by bekuno** [comment]
While analyzing at codacy it was an error, now it is ok.

**Comment by Lineflyer** [comment]
> While analyzing at codacy it was an error, now it is ok.

See: https://github.com/cgeo/cgeo/issues/11261#issuecomment-891309467

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
the "retest ..." does not trigger a codacy retest. Please change the PR to have another codacy check.

**Comment by Lineflyer** [comment]
I pushed codacy by pushing to @eddiemuc branch.

**Comment by bekuno** [comment]
> 
> 
> I pushed codacy by pushing to @eddiemuc branch.

Looks good.
A new check and without error.

**Comment by eddiemuc** [comment]
> the "retest ..." does not trigger a codacy retest. Please change the PR to have another codacy check.

You can trigger a retest directly at the codacy result page (click "refresh" Symbol next to "analyzed"). No need to change/push PR for this.

**Comment by eddiemuc** [comment]
This PR is no longer needee

**Comment by Lineflyer** [comment]
Reopen to test again as I found Checkstyle disabled as mentioned by @bekuno .
Lets see if it really stays green when enabling and reanalyzing.

**Comment by Lineflyer** [comment]
Damn it. Seems the disable/enable thing went wrong and tricked me by not really enabling it again.
The problem seems still there.

**Comment by bekuno** [comment]
Then lets try if PR #11399 is helpful.

**Comment by bekuno** [comment]
retest this please

check now after PR #11399  is pushed to release

**Comment by bekuno** [comment]
@eddiemuc It looks like Codacy needs a rebase. Can you do this?

**Comment by moving-bits** [comment]
since we have removed the related Codacy rule with #11465 this PR is no longere needed, therefore closing here

**Pull request closed without merging**
