### PR TITLE
rel to #14264: correct problems in scanning geojson simplestyle properties and merging with defaults

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #14264: correct problems in scanning geojson simplestyle properties and merging with defaults.

Also sets the default fill color to a transparent version of the default stroke color.

Example:
image

Geojson for example:

```
{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"properties": {
				"stroke": "#4931bf",
				"stroke-width": 6,
				"stroke-opacity": 0.8,
				"fill": "#eeff00",
				"fill-opacity": 0.5
			},
			"geometry": {
				"coordinates": [
					[
						[
							-16.98173915416504,
							32.7671270233774
						],
						[
							-16.98173915416504,
							32.705140585702398
						],
						[
							-16.90879275322979,
							32.705140585702398
						],
						[
							-16.90879275322979,
							32.7671270233774
						],
						[
							-16.98173915416504,
							32.7671270233774
						]
					]
				],
				"type": "Polygon"
			},
			"id": 0
		},
		{
			"type": "Feature",
			"properties": {
				"marker-color": "#cd2323",
				"marker-size": "medium"
			},
			"geometry": {
				"coordinates": [
					-17.05542990613077,
					32.73457386569392
				],
				"type": "Point"
			},
			"id": 1
		},
		{
			"type": "Feature",
			"properties": {
				"stroke": "#16e339",
				"stroke-width": 2,
				"stroke-opacity": 1,
				"fill": "#490bf4",
				"fill-opacity": 0.5
			},
			"geometry": {
				"coordinates": [
					[
						[
							-16.92963458206816,
							32.789031102555387
						],
						[
							-16.92963458206816,
							32.73958281811515
						],
						[
							-16.858176883192557,
							32.73958281811515
						],
						[
							-16.858176883192557,
							32.789031102555387
						],
						[
							-16.92963458206816,
							32.789031102555387
						]
					]
				],
				"type": "Polygon"
			},
			"id": 2
		},
		{
			"type": "Feature",
			"properties": {},
			"geometry": {
				"coordinates": [
					[
						[
							-16.87915797058372,
							32.74978734452368
						],
						[
							-16.9208027045523,
							32.74978734452368
						],
						[
							-16.9208027045523,
							32.69056624816247
						],
						[
							-16.87915797058372,
							32.69056624816247
						],
						[
							-16.87915797058372,
							32.74978734452368
						]
					]
				],
				"type": "Polygon"
			},
			"id": 3
		}
	]
}
```

### CODE REVIEW

**Comment by eddiemuc** [comment]
In the example, the polygon in the lower right (the reddish one) is set through c:geo information (line width, stroke color, fill color as 12,5% transparent version of stroke color) because there are no simplestyle info for it in the geojson file.

For the other geojson objects there's style information in the geojson file so this is used instead

**Comment by ztNFny** [comment]
> In the example, the polygon in the lower right (the reddish one) is set through c:geo information (line width, stroke color, fill color as 12,5% transparent version of stroke color) because there are no simplestyle info for it in the geojson file.

I get no fill for this file that has no styling info?!
[spree_neisse.geojson.txt](https://github.com/cgeo/cgeo/files/11471611/spree_neisse.geojson.txt)

**Comment by eddiemuc** [comment]
> > In the example, the polygon in the lower right (the reddish one) is set through c:geo information (line width, stroke color, fill color as 12,5% transparent version of stroke color) because there are no simplestyle info for it in the geojson file.
> 
> I get no fill for this file that has no styling info?! [spree_neisse.geojson.txt](https://github.com/cgeo/cgeo/files/11471611/spree_neisse.geojson.txt) image

Works on my emulator:

image

Note that geojson is NOT supported on Google Maps, only on mapsforge! At least not by my implementation. Supporting GM would be a new feature request.

**Comment by eddiemuc** [comment]
I am sorry, I forgot to push last change

**Comment by moving-bits** [comment]
Thanks, works like a charm now.

**Comment by moving-bits** [comment]
retest this please

**Comment by eddiemuc** [comment]
> Thanks, works like a charm now.

Thanks for the hint

**Pull request merged**
