### PR TITLE
add OpenAndroMaps as source for MapDownloader

### PR DESCRIPTION
**Pull request by moving-bits**
Extend MapDownloader framework to support multiple sources and add OpenAndroMaps as source.

As this PR probably clashes with the SAF update, let's merge SAF first, and I'll do conflict resolution on this PR. Setting the "WIP" label for now.

- Refactored MapDownloader framework to support different sources with individual parse patterns
- Received file get checked whether they need to be unzipped (and if so, if a file ending with ".map" is included)
- Add source type selector + short info (below update button) to updater view
- Display source name in result lists
- Update checker supports different sources in the same view
- Remember source type through all download steps and in offline map companion file

image.image
image

### CODE REVIEW

**Comment by Lineflyer** [comment]
Nice addition as OpenAndroMaps are also my favorite maps.
Can't we download the elevate theme by the way if the user downloads such map? Because as you stated on the example screen, they won't look right without it.

**Comment by moving-bits** [comment]
Good idea. The new framework should allow this, as it is explicitly about multiple sources. I'll look into it (need to find source URL and patterns). Would also try to include it in the update mechanism then.

More to come regarding this, as I would like to integrate the `mf-theme` and `mf-map-v4` schemes for direct download from the openandromaps homepage. One could also look into the freizeitkarte maps etc.

But one step after another... :-)

**Comment by moving-bits** [comment]
@eddimuc 
I did a rebase & conflict resolution and a smoke test with the result. Actual map selection & downloading works smooth, and the map gets selected and displayed - great! Thanks for adapting this part of the map downloader to SAF.

One thing does not work, though: The upgrade detection. I guess it's the `OfflineMapUtils.availableOfflineMaps()` method not returning the map companion files for downloaded maps, but need yet to debug into it.

The update button in the map downloader will get displayed only when there are map companion files for maps downloaded through the downloader, and the files referenced from within the companion file still exists. I have tested downloading a new map after the SAF upgrade: The companion file got created, but the "check updates" button still did not get displayed - neither for the old map files nor for the new one.

I'll try to debug into it the next days.

Anyway: Selecting OpenAndroMaps as download source and downloading a map file from there, which is the original intention of this PR, does work, so I'll remove the WIP label here, and create a new issue for the "check updates" problem.

**Comment by rsudev** [comment]
Just a short question: Did you ask whether they are fine with this? AFAIK they also 'live' by the donations they get from website visitors. And as @Lineflyer mentioned, without the right theme they are pretty useless....

**Comment by moving-bits** [comment]
Good point. I'll try to reach out to the guys from OpenAndroMaps.

**Comment by moving-bits** [comment]
Setting "Do not merge" label for now until all responses from the OpenAndroMap team received. (Already got an ok for one specific map and for the elevate theme, waiting yet for response regarding the map files itself.)

**Comment by moving-bits** [comment]
We got permission for direct downloading of both the map and the themes!

For reference here are copies of & links to the articles from the openandromap forum:

---

https://www.openandromaps.org/oam-forums/topic/cgeo-unterstuetzt-elevate-4-und-aktuelle-kartenformate/#post-41588
Was die Welt-Übersichtskarten betrifft habe ich keine Einwände (falls die auch von Interesse sein sollten) – Link zur betreffenden OAM-Sub-Page wäre nett.
Für die OAM-Vektor-Karten und Themes können nur Christian bzw. Tobias sprechen.
Schönen Gruß
Michael

---

https://www.openandromaps.org/oam-forums/topic/cgeo-unterstuetzt-elevate-4-und-aktuelle-kartenformate/#post-41608
Hallo moving-bits,
danke für die Nachfrage! Hier findest du die Lizenz-Infos für Elevate:
https://www.openandromaps.org/wp-content/users/tobias/licenses.txt
Soweit ich das sehe seit ihr ja eh Open Source/Nicht-kommerziell, da würde die erste Lizenz greifen.
Für mich spricht da gar nichts dagegen, ihr könnt auch die Theme-Datei direkt einbinden oder über die mf-theme://-Links. Bei ersterem hilft ggf. ein Check auf https://www.openandromaps.org/wp-content/users/tobias/version.txt, ob eine aktuellere Version verfügbar ist.
Spendenlink wäre natürlich auch schön, z.B. hierher:
https://www.openandromaps.org/projektkosten
Viele Grüße,
Tobias

---

https://www.openandromaps.org/oam-forums/topic/cgeo-unterstuetzt-elevate-4-und-aktuelle-kartenformate/#post-41644
Hallo @moving-bits

Nachdem @tobias und @mbe57 aka Michael schon ihr Bene gegeben haben habt Ihr auch meine Zusage für den direkten Download.
Nehmt bitte die direkten links zu gwdg. Damit ist eine Fehlerquelle weg
Setzt bitte einen Spendenlink, ich habe eben wieder 350€ für eine neue Backupplatte investiert 😉

LG Christian

**Comment by moving-bits** [comment]
I'll update this PR to include the backlink to openandromaps and remove the "WIP" label after that.

**Comment by eddiemuc** [comment]
What about the requested Spendenlink?

**Comment by moving-bits** [comment]
Added backlink / link to donation page (if exists) + extra attribution in about:contributors

image

Next step will be optionally downloading required theme file.

**Comment by Lineflyer** [comment]
Where does this donation link target to?

Please don't incluse links to pages like Paypal or similar, but better link to one of their pages giving further instructions how to donate.

The reason is, that according to Google Play T&C we are not allowed to collect any donations from within the app.
We had such issue some years ago with our own PayPal link (and replaced it by a link to our homepage).

**Comment by moving-bits** [comment]
> Where does this donation link target to?

For Mapsforge map I can only link to their Github page, as there seems to be no homepage etc.
For OpenAndroMaps I link to their "Projektkosten" page (as requested by the owners): https://www.openandromaps.org/projektkosten
(see file strings_not_translatable.xml)

**Comment by mbe57** [comment]
Only in case you also want to offer the world maps: does c:geo support
sqlitedb and/or mbtiles raster maps?

Cheers

Michael

**Comment by moving-bits** [comment]
> Only in case you also want to offer the world maps: does c:geo support sqlitedb and/or mbtiles raster maps? Cheers Michael

Hi Michael,
haven't looked into the overview maps yet. c:geo is used for geocaching, so mainly using high zoom levels.
We are using the https://github.com/mapsforge/mapsforge library for rendering the maps, which supports either online OSM map provider or offline .map files, but not mbtiles format. There seem to be external map provider add-ons for this format, but I haven't looked into it yet.

**Comment by fm-sys** [comment]
> Added backlink / link to donation page (if exists) + extra attribution in about:contributors

Where is the link in the posted screenshot. If it's the heart button, that's IMHO not clear enough. Or isn't it contained at all? It would probably be fair to display the attribution directly in the downloader and not only at our contributors page...

**Comment by moving-bits** [comment]
> Where is the link in the posted screenshot. If it's the heart button, 

The heart button is sort of a "like it" button and links to the map provider's page. Additionally I've added an extra line with links in the about:contributors page. - But I can add the URL in the description visible in the downloader if requested.

**Comment by fm-sys** [comment]
> But I can add the URL in the description visible in the downloader if requested.

IMO this would be polite, as we are allowed to use their servers free of charge in return...

**Comment by moving-bits** [comment]
Added link to server in the description (in addition to the "like it" URL via button):

image

**Pull request merged**
