### PR TITLE
Fixes for GK.canHandleTrackable (rel. to #15965)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Fixes the first two issues in #15965 / failing tests
- GeokretyConnectorTest.testCanHandleTrackable
- TrackableTest.testTrackableUrl

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by moving-bits** [comment]
failing tests are unrelated, so let's merge to get two GK tests back to green

**Pull request merged**
