### PR TITLE
Fix #4969: Inconsistencies between lists

### LINKED ISSUE #4969: Inconsistencies between lists
Starting with 2015.05.22-NB1 I seem to have extreme inconsistencies on my lists of saved caches.

Example:
- I open a list named GdH with 15 caches
- I open one of them and close it again
- Returning to the list I do see that all caches shown belong to the history list but not my list
- The header still shows GdH as name but a count of 81 caches (which is the amount of caches in the history list)
- Leaving and reentering the lists solves it

Trying to explitcitly reproduce it was not succesfull, but it keeps happening in various ways.

### PR DESCRIPTION
**Pull request by kumy**
Save the current list type between activity changes.

### CODE REVIEW

**Comment by Lineflyer** [comment]
@kumy 
Is this still up to date?

For me as a tester it seems to be the right time to merge this is no one objects...as we now have most time to test it on master.

**Comment by kumy** [comment]
@Lineflyer it could be merged if someone agree with the change

**Comment by kumy** [comment]
arf still some weird behaviours.
do not merge yet

**Comment by kumy** [comment]
IIRC, last submitted version is working. Any opinion? :)

**Comment by ldmpub** [comment]
I give you my feedback: I'm sorry but I'm still experiencing, hopefully less often, strange behaviour reported here #4834.
Since the changes done, I'm not able to give a scenario to reproduce but I can say "filters are lost 1 time among 4 when opening cache details from a nearby filtered list".

Note: I have get rid of the Android dev option "delete activity".

**Comment by Lineflyer** [comment]
@ldmpub 
Are you using a self-complied version?
Otherwise you are of course still experiencing the bug mentioned, as this PR is not yet merged into the nightly builds. Or did I get you wrong?

**Comment by kumy** [comment]
I've rebased the PR and tested it again. It's ok for me. I'll merge.
If someone don't agree, feel free to revert.

**Comment by ldmpub** [comment]
Hi,

Sorry for the late answer (I am on vacation) and you're right: I use the Nightly Builds... and will test it this week-end ;-).

**Comment by ldmpub** [comment]
Hi,

I'm still experiencing some troubles, less than before but there is still a bug.

To reproduce:

Context: some "nearby caches" already stored locally / Free GC Member.

1. search Nearby Caches
2. apply filter "containing TB"
3. search more caches, open some cache and / or TB details
4. sometimes when going back to the filtered cach list: some caches displayed previously are not there anymore!

Best regards,

**Comment by ldmpub** [comment]
Hi,

I'm still experiencing these troubles: list of caches is not consistent before and after opening cache details.

I have a suggestion to solve this issue: can we add a "store the current list" button to manually store the list before opening details and then the opposite button "restore previous caches list"?

What do you think?

**Pull request merged**
