### PR TITLE
Fix #4891: Convert loading Generic Trackables to RX style

### LINKED ISSUE #4891: Convert loading Generic Trackables to RX style?
While "playing" and testing RX stuff for #4802, I got a feeling that Trackables Connectors may/should be converted to RX.

Is this a good idea? Am I still understanding the RX stuff wrong way?

As an exercise, I started to do that... Not yet finished...

### PR DESCRIPTION
**Pull request by kumy**

### CODE REVIEW

**Comment by Lineflyer** [comment]
Should this be included into a possible next release?

@samueltardieu 
As you probably know RX the best, can you review this PR?

**Comment by samueltardieu** [comment]
I won't be able to review this in the next days/weeks.

**Comment by kumy** [comment]
ho, didn't saw automatic merge is now failing... :(

**Comment by Lineflyer** [comment]
In this case we should close and you should solve the conflicts...or not?

**Comment by kumy** [comment]
Please let it open, I'll force push updated code this week.

**Comment by kumy** [comment]
PR updated

**Comment by kumy** [comment]
Rebased the code

**Comment by kumy** [comment]
As we agreed in cgeo/cgeo@456abe4 
I merge, @samueltardieu feel free to add new commits

**Pull request merged**
