### PR TITLE
support new syntax for OC registration (fix #7536)

### LINKED ISSUE #7536: Create account option not working for some OC platforms
##### Detailed steps causing the problem:
- In the menu for each geocaching service we have the option to authorize.
- In the following menu we have a button to create an account for this platform.
- for some opencaching provider then we got the error err_application_no ("c:geo can't find any suitable application.")
- Ok for opencaching.de, .us
- KO for opencaching.pl, .nl, .ro, .uk

##### Version of c:geo used:
current master on Samsung S6 / Android 7
2019.04.16 on Samsung Note 8 / Android 9

##### Is the problem reproducible for you?
Yes

### PR DESCRIPTION
**Pull request by bekuno**
fix #7536 (Create account option not working for some OC platforms)

additional compose URL with site url and registration url

### CODE REVIEW

**Comment by bekuno** [comment]
Mmm, this is a bug in OCPL, should be fixed in opencaching/opencaching-pl#2028

So this PR will not be necessary after the OCPL PR.
Or to take up this PR, if such a problem occurs again later?

**Comment by Lineflyer** [comment]
IMHO we can wait as this is probably not a function which is called that often. Let OC-sites fix it. What do you think?

**Comment by bekuno** [comment]
It is no big change at OC site.
So lets wait a little bit for the PR there.

**Comment by rsudev** [comment]
I would also suggest not to introduce code on our site to workaround temporary OKAPI glitches, esp. in such a seldom used area.

**Comment by Lineflyer** [comment]
OK, then lets follow the majority and close this without merging.
@bekuno I hope, this is Ok for you.

**Comment by bekuno** [comment]
is fixed now in OCPL, PR here is not neccessary anymore

**Pull request closed without merging**
