### PR TITLE
Allow Java 1.8 to be used in cgeo

### PR DESCRIPTION
**Pull request by samueltardieu**
This enables features such as lambda expressions.

### CODE REVIEW

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
@samueltardieu 
Did you see, that the PR build on our CI for this change is failing?
I can't interprete why, but probably you can.

**Comment by bekuno** [comment]
There are some libraries which are not ready for java 8.
(tested this also in PR #7351)

**Comment by samueltardieu** [comment]
Since I won't have time to follow up on that, I'll close the pull request.

**Comment by Bananeweizen** [comment]
/home/jenkins/slave/workspace/cgeo pull request/tests/src-android/cgeo/geocaching/location/GeopointAndroidTest.java:16: error: reference to assertThat is ambiguous
17:10:57          assertThat(bundle.getParcelable(key)).isEqualTo(gp);
17:10:57          ^
17:10:57    both method assertThat(AtomicInteger) in Java6Assertions and method assertThat(AtomicBoolean) in Java6Assertions match

Qualifying the assertThat() call by its class should fix the compile error. Afterwards however, we should check switching from assertj 2.9.x to 3.x, and not using Java6Assertions, but Assertions. With your change we would not need the old java 6 compatible version anymore.

**Comment by UniQP** [comment]
I fixed the compile error → CI is happy again.

**Comment by samueltardieu** [comment]
LGTM

**Comment by UniQP** [comment]
I changed the fix to explicitly provide the generic type parameter of the method instead of inserting a cast.

**Pull request merged**
