### PR TITLE
Improve selected position info

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Implements the ideas described in https://github.com/cgeo/cgeo/pull/15429#issuecomment-2002128498:
- Combines map long-tap menu entries for "Show coordinates" and "Elevation (map)" into a single "Selected position" entry
- Tapping on it opens a dialog with following options:
  - Display coordinates (format switchable)
  - Display elevation from map
  - Display distance to current position (straight line)

image

Closes #15429

### CODE REVIEW

**Comment by moving-bits** [comment]
failing tests are unrelated

**Comment by ztNFny** [comment]
Thanks for taking care of this, I just didn't have the time for this yet.
One thing I had in mind was adding icons to the dialog (maybe instead of the text, not sure, have to try it) - I can take care of that after this PR.

**Comment by ztNFny** [comment]
Text alignment is broken. It's right-aligned to the widest text, not the.dialog

**Comment by moving-bits** [comment]
This was intentional, as having text/values unaligned looked pretty ugly, and having them aligned to the dialog's borders made them being very far apart from each other, looking unrelated.

(But this could be changed, if preferred, or even won't happen at all if we switch to icons instead of text. The last two lines could then be put into a single line.)

**Comment by moving-bits** [comment]
@ztNFny 
Maybe something like this?

image

(is a hand-crafted bitmap for now)

maybe skip the little separator dot between elevation and distance?

**Comment by ztNFny** [comment]
> This was intentional, as having text/values unaligned looked pretty ugly, and having them aligned to the dialog's borders made them being very far apart from each other, looking unrelated.

ok, I'll try to come up with something

**Pull request merged**
