### PR TITLE
read child waypoint types from GPX <type>

### PR DESCRIPTION
**Pull request by following5**
This is dry-written code; I have no c:geo development environment (yet).

It allows to have the type of GPX child waypoints only in the `<type>` element, instead of redundantly in `<type>` and `<sym>`. Then Garmin and Groundspeak waypoint IDs can coexist in the same file.

(`<sym>` is an original Garmin GPX element, while Groundspeak added the `<type>`.)

Example:
```
    <wpt lat="51.11847" lon="17.06827">
        ...
        <sym>Trail Head</sym>
        <type>Waypoint|Trailhead</type>
...
    </wpt>
```

(Garmin "Trail Head" = Groundspeak "Trailhead")

Such GPX files are now produced by OKAPI at Opencaching.PL/NL/US/RO. Example:

https://opencaching.pl/okapi/services/caches/formatters/gpx?consumer_key=YourConsumerKey&cache_codes=OP601F&alt_wpts=true&ns_ground=true

(Insert your OC.PL consumer key, that you received via [OKAPI signup](https://opencaching.pl/okapi/signup.html)).

### CODE REVIEW

**Comment by Lineflyer** [comment]
Ok to test

**Comment by Lineflyer** [comment]
retest this please

**Comment by bekuno** [comment]
I have tested it.
You find my proposed amendment in my branch gpx-child-waypoint-type
https://github.com/bekuno/cgeo/commit/b3c8b19b6ecd809e8bbca02457a6cf43413bccd9

**Comment by bekuno** [comment]
Please change the test case - see https://github.com/bekuno/cgeo/commit/5cc94a32c650d103d6a5fbb3c9adb3a1229bf762

**Comment by bekuno** [comment]
This is only a small change.
I suggest to add this PR without waiting for PR #7213.
@rsudev @UniQP ?

**Comment by Lineflyer** [comment]
@following5 
As we have a little lack on reviewers at the moment and as I also do not have such detailed insights into the GPX format:
How do you consider the risk with "backwards compatibility", meaning will GPX files from geocaching.com still work?
Do you recommend any test cases (Is there an easier way to get a GPX which I can use for a before/after comparison with respect to the new functionality added by your PR)?

**Comment by Lineflyer** [comment]
Lets merge and test

**Pull request merged**
