### PR TITLE
Solving Issue 5854: avoid duplication of personal note 

### PR DESCRIPTION
**Pull request by eddiemuc**
Attempts to solve #5854 
This PR removes **completely** the existing "merge" logic for personal notes when local caches are refreshed from providers and replaces it with a much simpler logic: when a cache is refreshed from provider then:
* the local note is preserved as is
* if a note exists at provider side, it is split using the well-known "\n--\n" separator. For any of the provider site "subnotes" found that way: if it is not found in local note (using `String.contains() `) then it is appended to local note using "\n--\n"

This should IMHO remove the side-effect duplicate creations we experience nowadays while preserving changes on provider side as best as possible

Note that (like before) the upload of user notes from cgeo to provider overwrites the provider note without any mercy or check!

### CODE REVIEW

**Comment by Lineflyer** [comment]
ok to test

**Comment by Lineflyer** [comment]
retest this please

**Comment by moving-bits** [comment]
Ok, let's merge and test this one.

@eddiemuc 
Thank you for your contribution, highly appreciated!

**Comment by MagpieFourtyTwo** [comment]
@eddiemuc 
This fix (resp rework), BTW, is working amazingly GREAT!
It's a real relief to have this issue solved.
Therefore, it is an urgent need for me to say thank you as well! :)

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo thank you :-) I really like the way the cgeo Team works together and how constructive and respectful you tread each other. Great spirit!

**Pull request merged**
