### PR TITLE
Change the compile pattern after change on the GC.com page (Fix #7291)

### LINKED ISSUE #7291: Cache descriptions showing blank
##### Detailed steps causing the problem:
- open non saved cache.
- goto description.
- no description show. Hint will show

Cgeo 2018.10.13

##### Is the problem reproducible for you?
Yes

##### System information:
```--- System information ---
Device: Pixel XL (marlin, google)
Android version: 9
Android build: PQ2A.190205.003
c:geo version: 2018.10.13
Google Play services: enabled - 15.0.90 (100400-231259764)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (56.5 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (56.5 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (56.5 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (79.0 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
ttach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

### PR DESCRIPTION
**Pull request by bekuno**
Fixes: Cache descriptions showing blank #7291

Change the compile pa ttern after change on the GC.com page

### CODE REVIEW

**Comment by moving-bits** [comment]
@kumy Currently all new builds are breaking at different stages, even those which only have changed some layout xml (see the last four PR). Could you have a look at Jenkins, pls? Thx.

**Comment by rsudev** [comment]
This one failed,as the stored test data does no longer fit the new site layout. I am looking into it.

**Comment by kumy** [comment]
I'm not available today :( will check or  rollback in the evening.

My idea in the past was to build on each android version, but from memories only the emulator running on android 24 was working fine (it was some month ago). I hope upgrading to tooling around didn't break things. @rsudev, does master node works as expected? It has been updated too.

**Comment by kumy** [comment]
I've found a moment before leaving, I've rollbacked the docker images to v2.0.1, hope this help at some point.

**Comment by kumy** [comment]
Jenkins: please test this

**Comment by kumy** [comment]
Hum, wrong keyword…

Jenkins: retest this please

**Comment by kumy** [comment]
FTR, https://github.com/cgeo/cgeo/pull/7287#issuecomment-462495465 the job referenced here, is Green, but in fact has failed :( - _Banging my head on the table_ -

**Comment by kumy** [comment]
Jenkins: retest this please

**Comment by kumy** [comment]
I have to leave now, I've also issued a manual upgrade of build-tools in the containers: `sdkmanager "build-tools;28.0.3"`

Tests jobs:
* http://ci.cgeo.org/job/cgeo%20pull%20request/1623/console
* http://ci.cgeo.org/job/cgeo%20pull%20request/1622/console

**Comment by janykey** [comment]
Ja
kumy <notifications@github.com> schrieb am So., 17. Feb. 2019, 11:21:

**Comment by kumy** [comment]
"Ja"?

**Comment by kumy** [comment]
@rsudev just read your last comment carefully, did you mean rollback was not necessary and problems came all from new GC website design?

**Comment by Lineflyer** [comment]
> @rsudev just read your last comment carefully, did you mean rollback was not necessary and problems came all from new GC website design?

 I would also say so. We have some dumped cache pages in our tests to test the parsing. Of course these might need to be adapted as soon as parsing rules are changed.

**Comment by Lineflyer** [comment]
But AFAICS the tests also show another problem which need to be fixed for trackables. I will open a dedicated issue for that.

**Comment by rsudev** [comment]
Two tests fixed by trackable fix and test data adaption:
* cgeo.geocaching.CgeoApplicationTest.testSearchTrackable
* cgeo.geocaching.connector.gc.GCParserTest.testParseCacheFromTextWithMockedData

Three tests fail now:
1. cgeo.geocaching.connector.gc.GCConstantsTest.testCacheCount
1. cgeo.geocaching.connector.gc.GCParserTest.testGetUsername
1. cgeo.geocaching.connector.gc.TrackablesTest.testParseSpeedManagerCompressedTrackable

ad 1): Unclear, need to investigate

ad 2): Triggered by the change in test data, very unclear to me, it should work as before...

ad 3): Triggered by the trackable fix, need to adapt test data

**Comment by Lineflyer** [comment]
Merged for testing. 
Thanks so far @bekuno and @rsudev

**Comment by rsudev** [comment]
@kumy regarding the build problems - I am unsure but had the impression from scanning the build logs. Unfortunately did I still no manage to get my node up-and-running, so I cannot cross-check right now.

**Comment by kumy** [comment]
Any action needed from my side today?

**Pull request merged**
