### PR TITLE
Raise minSdkVersion to 14

### PR DESCRIPTION
**Pull request by samueltardieu**
This is not over and I don't have the time right now to test or tackle the remaining compilation issue. Do not hesitate to work on this branch in order to raise the min sdk version, I just don't want this preliminary work done some days ago to get lost.

### CODE REVIEW

**Comment by samueltardieu** [comment]
Related to #6174.

**Comment by pstorch** [comment]
See #6190

**Comment by pstorch** [comment]
I've redone my changes on top of this branch with a merge from master. I hope this was ok.

**Comment by samueltardieu** [comment]
It looks fine to me.

**Comment by samueltardieu** [comment]
retest this please

**Pull request merged**
