### PR TITLE
add Android 11 notice about storage spaces

### PR DESCRIPTION
**Pull request by moving-bits**
Android 11 enforces storage spaces for all apps targeted to API 29 (which by itself is an upcoming requirement by Play Store). c:geo does not yet support storage spaces, which will lead to some of its data not being accessible by c:geo if running on Android 11. See #8457 for details.

I propose to add a info notice to our changelog to inform users not to upgrade their system to Android 11 for now (or at least only if they can live with the consequences regarding c:geo):

image

### CODE REVIEW

**Comment by eddiemuc** [comment]
I fully support writing this note. I would however add more clearly from a users perspective which data is not accessible any more and which functionality will not work with Android 11.
(Actually I don't know this myself. Will the sqlite DB still be accessible?)

**Comment by moving-bits** [comment]
> I would however add more clearly from a users perspective which data is not accessible any more and which functionality will not work with Android 11.

Can't say yet in detail, as I haven't explored in-depth so far.

As far as I've seen so far, the so called "public external directory" won't be accessible anymore, at least not using the methods we use now - that would be the `cgeo` dir and its subdirs, which are publicly visible today.

> (Actually I don't know this myself. Will the sqlite DB still be accessible?)

The internal database should still be accessible, but you wouldn't be able to backup to / restore from the public directory (`cgeo/backup`).

Let's start with above note for now, and add along the way as we explore what will work and what does not.
(I'm sort of in a hurry regarding this, as public beta versions are available for Android 11 already, and publishing date for the final version is not too far away.)

**Comment by eddiemuc** [comment]
Sugestion: add following sentence:
Android 11 enforces a new way for storing data, which c:geo does not support yet. If you switch your system to Android 11, c:geo will not be able to access part of its data. This will most likely disable storing offline images (listings and logs) as well as backup/restoring c:geo's database. Other effects may occur. We recommend to not upgrade to Android 11 for the time being.

**Comment by moving-bits** [comment]
@eddiemuc Thanks for the extended text. I'm not sure about the offline images (they go to an internal storage, IIRC), but export to GPX will be harmed, also access to offline maps. I'll update the text accordingly, including the other suggestions from you.

**Comment by moving-bits** [comment]
Updated to:
image
(light theme in this case, unrelated to the change)

**Comment by Lineflyer** [comment]
LGTM.

Maybe we should also add a warning if we detect running on Android 11. For example at the same place where missing login is shown on the mainscreen and link to our FAQ (entry to be created)?

**Comment by moving-bits** [comment]
> Maybe we should also add a warning if we detect running on Android 11. For example at the same place where missing login is shown on the mainscreen and link to our FAQ (entry to be created)?

I'll add it. Which anchor name within the FAQ shall I use? (Even if there's no text behind it yet.)

**Comment by Lineflyer** [comment]
> I'll add it. Which anchor name within the FAQ shall I use? (Even if there's no text behind it yet.)

As you like, e.g. `#android11`
Please kindly open a followup on the website repo once done (or even feel free to add it to the FAQ yourself).

**Comment by moving-bits** [comment]
Added a mainscreen warning "You appear to be using Android 11, which c:geo does not support fully yet. Please read our FAQ to get more info on this." if running on Android >= 11. Links to https://www.cgeo.org/faq#android11.

**Comment by moving-bits** [comment]
> Please kindly open a followup on the website repo once done

is this the `cgeo.github.io` repo?

**Comment by Lineflyer** [comment]
> is this the cgeo.github.io repo?

Jepp

**Pull request merged**
