### PR TITLE
Implemented a proposal for an adaptive icon.

### PR DESCRIPTION
**Pull request by jonas-koeritz**
I implemented an adaptive icon for c:geo that will work from Android 8.0 onwards on all launchers that support them. The screenshots are all from my Pixel 4 XL running Android 10, switching between the different theme options for icon outline.
This doesn't look too bad, given I just had to modify some parts of the SVGs to get this to work. IMO the 3D effect of the "Map" part of the icon is weakened a little but Google doesn't encourage icons with a distinct outline anymore.
Devices < API Level 26 will still display the old PNG icons.

photo5258281246373555500
photo5260563372951317635
photo5260563372951317636
photo5260563372951317637

### CODE REVIEW

**Comment by bekuno** [comment]
see issue #7631

**Comment by bekuno** [comment]
Why did you use these special folder names?

**Comment by Lineflyer** [comment]
It looks nice IMHO. People will recognize it (even withour shadow ;) ).

**Comment by moving-bits** [comment]
Like it 👍

**Comment by moving-bits** [comment]
> Why did you use these special folder names?

By appending a version number to certain ressource folder names you can tell Android to include those ressources only from this version on. Also you can provide alternative implementations for different versions.

**Comment by SammysHP** [comment]
Sorry, not my taste. The detailed map doesn't work as a background with a cutout mask. It also feels like something is missing from that lonely container.

**Comment by jonas-koeritz** [comment]
Somebody with a more designer"ish" background should have a look at what we could come up with.

**Comment by Lineflyer** [comment]
> Sorry, not my taste. The detailed map doesn't work as a background with a cutout mask. It also feels like something is missing from that lonely container.

Shall we then better keep the non-optimized until we get a better proposal or use this as an interim version? Or would you be able to create a better design, IMHO you redesigned the logo already in the past.

**Comment by jonas-koeritz** [comment]
I haven't done any work on the logo before. Let's stick with the current one until we come to some consensus.

**Comment by davidlb** [comment]
What about a single color background or even just white as most of google apps icon?

**Comment by jonas-koeritz** [comment]
That white background is just the default fallback icon when adaptive icons
are not supported. c:geo already looks like that when running on my Pixel 4.

David Le Brun <notifications@github.com> schrieb am Fr., 17. Jan. 2020,
11:36:

**Comment by SammysHP** [comment]
I'd keep the old logo and just add a better background (color or texture).

**Comment by Lineflyer** [comment]
> I'd keep the old logo and just add a better background (color or texture).

Maybe a black/darkgrey color like our homepage background? But I am not at all a good design expert.

**Comment by Lineflyer** [comment]
@SammysHP 
Any proposal from your side?
It does not help to keep this pending. So we should either have a new design propoal, accept this one or close it...

**Comment by SammysHP** [comment]
Then let's close it. If someone has a better idea we can reopen it.

**Pull request closed without merging**
