### PR TITLE
rel to #10070: introduce user display name for map themes

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #10070: introduce user display name for map themes.

More details will follow in a comment shortly.

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR introduces "user-friendly" display of map themes in map theme selection list:
* XML Themes directly lying in map theme folder will be displayed by stripping away any subfolder and the .xml extension
* XML Thems from within ZIP files will be displayed same as above but with Zip file name + / prepended (both subfolder structures where the zip file lies and subfolder structures inside the Zip are stripped away).
* Result is ordered alphabetically.

To visualize this I created a very complex example map themes dir as follows:

image

This example contains:
* Xml themes in both the theme root dir as in a subfolder "subfolder"
* Zip theme packages in same folders
* A "special" zip package "mythemes.zip" in both root and subfolder. I created this special zip by downloading both Elevate theme from OpenAndroMaps and one Freizeitkarte Theme and putting them both into a single Zip file. E,g, inside this Zip file the following xml themes are located (including zip-internal subfolders):

```
mythemes\freizeitkarte-v5\freizeitkarte-v5.xml
mythemes\Elevate\Elevate.xml
mythemes\Elevate\Elements.xml
```

Given this setup, map theme selection dialog display is as follows:
image

To be able to debug situations like this, I let the "themeId" (which contains also all subpaths and extensions) be displayed as well **when in debug mode**. With above test setup this would look as follows:
image

image

**Comment by moving-bits** [comment]
@eddiemuc 
After merging #10079 there is now a conflicting file in this PR - can you resolve & update this PR? Thanks.

**Comment by eddiemuc** [comment]
@moving-bits done

BTW: same thing will happen again with either #10086 (if you merge this PR first) or this PR (if you merge #10086 first).

**Comment by moving-bits** [comment]
Thanks for updating. Which way would be less hassle for you - start with merging this PR, and then #10086, or the other way around?

**Comment by eddiemuc** [comment]
Good question. Maybe better to merge this one first

**Comment by eddiemuc** [comment]
Btw: if you want I can also merge myself. Not so sure yet in which cases this is ok or not.

**Comment by moving-bits** [comment]
> Good question. Maybe better to merge this one first

done

> Btw: if you want I can also merge myself. Not so sure yet in which cases this is ok or not.

We have no fixed rule regarding this. Personally I try to handle it like this: Trivial changes I merge myself, other changes I leave open for some time, if someone wants to take a look at it. And if I'm unsure with some more "critical" parts, I'll request a review.

**Comment by MagpieFourtyTwo** [comment]
Looks perfectly fine. Just one hint regarding your test scenario; If you use it to just test the display of theme names, everything is fine, but if you additionally want to check if the themes really work in the map (e. g. while testing the folder sync), the ``subfolder\Elements.xml`` will most probably not, as OpenAndroMap theme .xml files need an ``ele_res`` folder besides it, otherwise they will not find their .svg files.

**Comment by eddiemuc** [comment]
Yes this was just for testing the dialog :-) A little bit also for testing whether such situation is handled stable by c:geo (e.g. no unexpected crash).

**Comment by MagpieFourtyTwo** [comment]
Is the sort already implemented?  If so, it does not work. If not, no problem, just want to be sure. ;)

**Comment by eddiemuc** [comment]
@MagpieFourtyTwo 
It was implemented, then it fell out again due to a wrongly solved merge conflict (I do too many PRs in same file...). It should work now again.

**Pull request merged**
