### PR TITLE
Wherigo: adjust error handling, badges and wherigo bar

### PR DESCRIPTION
**Pull request by eddiemuc**
Wherigo: adjust error handling, badges and wherigo bar

### CODE REVIEW

**Comment by eddiemuc** [comment]
This is a cleanup of error handling routines, wherigo bar and some other places. Biggest introduction is a BadgeManager to handle assigning and removing of badges to Views.

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
great, the CI is down again

**Comment by eddiemuc** [comment]
Badge view when there is a yet unread wherigo error:
image

View in Home screen when there is a currently paused dialog which should be resumed:
image

**Comment by ztNFny** [comment]
could you change the badge to use the accent color instead of blue?

**Comment by ztNFny** [comment]
could you change the badge to use the accent color instead of blue?

**Comment by eddiemuc** [comment]
> could you change the badge to use the accent color instead of blue?

That could be done easily of course and I don't mind doing it. But: I found code for existing badges (the one on the home item to be precise) where there is a distinction made between "high priority" and "low priority" badge. The "high prio" badge is in ascent color, the "low prio" badge is in blue color. I assumed that the wherigo stuff is "low prio", hence the blue color. 

Again, no problem and no resistance from my side to change badge color. But what is the c:geo "rule" here about badge colors?

**Comment by eddiemuc** [comment]
Ah well, I put ascent color for now. We can discuss and change this later again when needed.
image

**Comment by ztNFny** [comment]
I assumed it's something yiu added, wasn't aware of c:geo having badges 😯

**Comment by eddiemuc** [comment]
> I assumed it's something yiu added, wasn't aware of c:geo having badges 😯

Oh no it has. But I believe only on the Home Button so far

**Comment by moving-bits** [comment]
> > I assumed it's something yiu added, wasn't aware of c:geo having badges 😯
> 
> Oh no it has. But I believe only on the Home Button so far

IIRC, it's a "high prio" badge for login errors, and a "low prio" badge for those update notifications.

So "high prio" on WIG bottom navigation button would suitable for WIG errors, and "low prio" for "WIG resume", IMHO.

**Pull request merged**
