### PR TITLE
fix #6259: do not save cookie store with Google

### LINKED ISSUE #6259: Login issue (Unknown error) Code=403
Recently I started asking users on support to do this procedure when they report "Login failed: Unknown error" and confirmed to have checked all other things mentioned in the FAQ:

- Go to c:geo Menu - Settings - Service - geocaching.com
- Disable the service completely (disabling the tick box)
- Reboot device
- Go to c:geo Menu - Settings - Service - geocaching.com
- Enable the service again

In all cases users reported back, that it was now working normal (Login OK).

Can someone imagine any root cause in the c:geo code causing this.
I personally suspect problems in upgrade cases or data restore after reinstallation (Google backup)...IMHO this is somehow enabled in c:geo to store this data in Google.

### PR DESCRIPTION
**Pull request by samueltardieu**
Keeping the cookie store separate from the preferences allows not to
backup it with the backup manager.

### CODE REVIEW

**Comment by pstorch** [comment]
Interesting. Didn't know about the concept of preferences backup via google. Had to look it up. 
But the solution sounds plausible.

**Comment by pstorch** [comment]
Should we also reset the cookies on `CredentialPreference.revokeAuthorization()`. 
The `AbstractLogin` class has a `resetLoginStatus()` method.

**Comment by Lineflyer** [comment]
As written in #6259 I suggest to put this to `master` only (and maybe also discuss the background and further steps).

**Comment by pstorch** [comment]
@Lineflyer the target branch of a PR can also be changed via the `edit` button on top of the page. Ok, this doesn't work in all cases, but most of the time it is not needed to close and open a new PR.

**Comment by Lineflyer** [comment]
Then lets @samueltardieu do the needful. :)

**Comment by samueltardieu** [comment]
> Should we also reset the cookies on `CredentialPreference.revokeAuthorization()`?

Good idea, I'll do that in case of revocation of gc.com authorization.

**Pull request merged**
