### PR TITLE
fix #13921 (the real fix): correct landscape compass layout to use new location-status

### LINKED ISSUE #13921: NPE in compass activity leading to OnErrorNotImplementedException
### Describe your problem!

Crash reported for new beta 2023.01.30-RC (and recent nightlies).

Android 9,10,11,13
6 users
26 events

### How to reproduce?

Unclear

### Actual result after these steps?

```
Exception io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException:
  at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept (Functions.java:718)
  at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept (Functions.java:715)
  at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError (LambdaObserver.java:77)
  at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext (LambdaObserver.java:67)
  at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal (ObservableObserveOn.java:202)
  at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run (ObservableObserveOn.java:256)
  at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run (HandlerScheduler.java:123)
  at android.os.Handler.handleCallback (Handler.java:900)
  at android.os.Handler.dispatchMessage (Handler.java:103)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8393)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)
Caused by java.lang.NullPointerException:
  at cgeo.geocaching.CompassActivity$2.accept (CompassActivity.java:304)
  at cgeo.geocaching.CompassActivity$2.accept (CompassActivity.java:301)
  at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext (LambdaObserver.java:63)
```

### Expected result after these steps?

Normal operation

### Reproducible

Unclear

### c:geo Version

2023.01.30-RC

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #13921 (the real fix): correct landscape compass layout to use new location-status

This is the real fix. Cause of the problem was that in compass landscape layout the new field location status was missing.

### CODE REVIEW

**Comment by eddiemuc** [comment]
Failing build is unrelated

**Comment by eddiemuc** [comment]
Retest this please

**Comment by moving-bits** [comment]
@mucek4 
It's the "Could not create ADB Bridge." again - can you restart the executors, please? Thanks.

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
