### PR TITLE
Concistency between Services settings

### PR DESCRIPTION
**Pull request by kumy**
I have reworked some services setttings. Introduced a new `CredentialsAutorizationActivity` based on other activities from the same kind (`TokenAutorizationActivity`, `OAuthAutorizationActivity`) which ask for a user/password.
Connectors for EC, GC, GCVote are upgraded to `CredentialsAutorizationActivity`. Now all connectors share the same UI.
Some issues are fixed, not necessary how it was proposed (I think about #5092 / #5093)
Due to the new UI, avatar is not longer displayed uppon connexion (see also #4986). I wanted to display it directly in the connector settings, but failed to store the image to show it "permanently". Do you think it's necessary? Can someone help here?

screenshot_2016-03-24-00-27-24
screenshot_2016-03-24-00-26-48
screenshot_2016-03-24-00-27-30
screenshot_2016-03-24-00-27-05
screenshot_2016-03-24-00-28-01

### CODE REVIEW

**Comment by samueltardieu** [comment]
> Due to the new UI, avatar is not longer displayed uppon connexion (see also #4986). I wanted to display it directly in the connector settings, but failed to store the image to show it "permanently". Do you think it's necessary?

You can use `HtmlImage.getDrawable` with using `HtmlImage.SHARED` pseudo-geocode as the geocode in the constructor. This way, the image will not be refreshed unless you set `userInitiatedRefresh` (for example, when the user checks its credentials).

**Comment by kumy** [comment]
@samueltardieu thanks for the tip.
screenshot_2016-03-25-01-02-36

**Comment by kumy** [comment]
Any objection to merge?

**Comment by rsudev** [comment]
I didn't check the code, but frontend-wise I like the unification.

**Comment by samueltardieu** [comment]
No objection at all, this is a great step in the good direction!

**Comment by kumy** [comment]
So let's merge :)

**Pull request merged**
