### PR TITLE
Update AssertJ Core to version 2.9.1

### PR DESCRIPTION
**Pull request by UniQP**
Test whether upgrading AssertJ Core fixes the build problems.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
which build problems exactly? assertj 2.9.x is java 6 compatible and should not influence android builds in any bad way.

**Comment by UniQP** [comment]
For instance http://ci.cgeo.org/job/cgeo%20pull%20request/1742/console (PR build from yesterday) states
```
18:35:32  05:35:35 V/InstrumentationResultParser: There were 2 failures:
18:35:32  05:35:35 V/InstrumentationResultParser: 1) org.assertj.core.internal.cglib.transform.AbstractProcessTask
18:35:32  05:35:35 V/InstrumentationResultParser: java.lang.ClassNotFoundException: org.assertj.core.internal.cglib.transform.AbstractProcessTask
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.Class.classForName(Native Method)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.Class.forName(Class.java:324)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
18:35:32  05:35:35 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.assertj.core.internal.cglib.transform.AbstractProcessTask" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/cgeo.geocaching.test-1/base.apk", zip file "/data/app/cgeo.geocaching-2/base.apk"],nativeLibraryDirectories=[/data/app/cgeo.geocaching.test-1/lib/x86_64, /data/app/cgeo.geocaching-2/lib/x86_64, /vendor/lib64, /system/lib64]]
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
18:35:32  05:35:35 V/InstrumentationResultParser: ... 9 more
18:35:32  05:35:35 V/InstrumentationResultParser: Suppressed: java.lang.NoClassDefFoundError: org.assertj.core.internal.cglib.transform.AbstractProcessTask
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.DexFile.defineClassNative(Native Method)
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.DexFile.defineClass(DexFile.java:226)
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.DexPathList.findClass(DexPathList.java:338)
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
18:35:32  05:35:35 V/InstrumentationResultParser: ... 11 more
18:35:32  05:35:35 V/InstrumentationResultParser: Suppressed: java.lang.ClassNotFoundException: org.assertj.core.internal.cglib.transform.AbstractProcessTask
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.Class.classForName(Native Method)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
18:35:32  05:35:35 V/InstrumentationResultParser: ... 10 more
18:35:32  05:35:35 V/InstrumentationResultParser: Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
18:35:32  05:35:35 V/InstrumentationResultParser: 2) org.assertj.core.internal.cglib.transform.AbstractTransformTask
18:35:32  05:35:35 V/InstrumentationResultParser: java.lang.ClassNotFoundException: org.assertj.core.internal.cglib.transform.AbstractTransformTask
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.Class.classForName(Native Method)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.Class.forName(Class.java:324)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.doLoadClass(TestLoader.java:92)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.internal.runner.TestLoader.loadIfTest(TestLoader.java:113)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.loadClassesFromClassPath(TestRequestBuilder.java:801)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:747)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
18:35:32  05:35:35 V/InstrumentationResultParser: at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
18:35:32  05:35:35 V/InstrumentationResultParser: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.assertj.core.internal.cglib.transform.AbstractTransformTask" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/cgeo.geocaching.test-1/base.apk", zip file "/data/app/cgeo.geocaching-2/base.apk"],nativeLibraryDirectories=[/data/app/cgeo.geocaching.test-1/lib/x86_64, /data/app/cgeo.geocaching-2/lib/x86_64, /vendor/lib64, /system/lib64]]
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
18:35:32  05:35:35 V/InstrumentationResultParser: ... 9 more
18:35:32  05:35:35 V/InstrumentationResultParser: Suppressed: java.lang.NoClassDefFoundError: org.assertj.core.internal.cglib.transform.AbstractTransformTask
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.DexFile.defineClassNative(Native Method)
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.DexFile.defineClass(DexFile.java:226)
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.DexPathList.findClass(DexPathList.java:338)
18:35:32  05:35:35 V/InstrumentationResultParser: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
18:35:32  05:35:35 V/InstrumentationResultParser: ... 11 more
18:35:32  05:35:35 V/InstrumentationResultParser: Suppressed: java.lang.ClassNotFoundException: org.assertj.core.internal.cglib.transform.AbstractTransformTask
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.Class.classForName(Native Method)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
18:35:32  05:35:35 V/InstrumentationResultParser: at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
18:35:32  05:35:35 V/InstrumentationResultParser: ... 10 more
18:35:32  05:35:35 V/InstrumentationResultParser: Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

The PR was to test whether this problem disappears when upgrading AssertJ Core. Of course, we can merge it nevertheless.

**Comment by Bananeweizen** [comment]
We may want to defer the upgrade of assertj until https://github.com/cgeo/cgeo/pull/7347 has been merged. Then we should be able to use the 3.x version instead.

**Comment by UniQP** [comment]
Upgrading to AssertJ Core 3.x is not possible until we fix #7354.

**Comment by Bananeweizen** [comment]
If I get it right, the PR build has the same 2 test failures before this PR and with this PR. So upgrading does not seem to make it worse. Right? If so, I'm in favor of merging.

**Pull request merged**
