### PR TITLE
upgrade dependencies

### PR DESCRIPTION
**Pull request by Bananeweizen**
Since the switch to gradle 5.x and Java 8 we can again upgrade more
dependencies.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
For whatever reason this seems to be a real failure on CI despite for the CI having some hickups last days.
Looks a bit like the character encoding was influenced causing the test to fail?!

**Comment by Bananeweizen** [comment]
okhttp behaves differently when upgraded. I reverted that, so tests should be green now

**Pull request merged**
