### PR TITLE
set android:exported="true" if this is required

### LINKED ISSUE #12354: AndroidManifest @ Android 12
### Tell us your idea!

Observed while testing for #12307 when set `targetSdkVersion 21`:

~~~
Error: android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
~~~

This situation we have in main/AndroidManifest.xml
 - 11 x activity
 - 1 x receiver
 

### What solution would you suggest?

_No response_

### Is there an alternative?

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bekuno**
fixes #12354

Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.

We already set `android:exported="true"` if this is necessary.
Add this value also for the remaining intents.

(edited)

### CODE REVIEW

**Comment by fm-sys** [comment]
> Therefore I assume that all others should be set to `false`.

Like seen in the manifest all these activities have intent filters, means they are intended to be launched from outside cgeo. Therefore exported needs to be `true`

**Review by fm-sys — CHANGES_REQUESTED** [review]
Change to `android:exported="true"` as it will otherwise break existing functionality...

**Review by fm-sys — APPROVED** [review]
LGTM! Thanks for working on it 👍

**Comment by moving-bits** [comment]
I can try to look into this the next days. IIRC default value is neither "always true" nor "always false", but context-specific. And we should only export those activities which need to be called by other apps.

**Comment by bekuno** [comment]
set DNM until it was verified.

**Review by moving-bits — APPROVED** [review]
According to the [docs](https://developer.android.com/guide/topics/manifest/activity-element) `false` is the default "when there are no intent filters" (`true` otherwise). All of the changed activities in this PR do have intents, so `true` would be their default currently, and thus the changes are fine. Thanks for diving into it!

**Pull request merged**
