### PR TITLE
fix #3007: Support Geokrety

### LINKED ISSUE #3007: Support GeoKrety
Hi,
I am just curious... Is possible to show GeoKrety trackables in Geocaching caches? I think it is not implemented yet because I didnt see Geokret which was in my last cache in cgeo in trackables... but it was shown on GC.com websites with GeoKrety plugin...¨

Thank you

### LINKED ISSUE #4315: Add an icon to trackable representing "brand"
If GeoKrety (as of geolutins, pathtags...) are supported by c:geo, it would be good if they could be easily differentiated in cache inventory.

Adding an icon representing "brand" may be an option.

What's your opinion?

### LINKED ISSUE #4326: GeoKrety, some details are missing
The current implementation for viewing a GeoKrety trackable use the API brought by GK team.

We use export2.php script to retrieve data.
Currently we can get:
* gkid
* tracking code (when authenticated request)
* distance traveled
* lat/long
* current waypoint
* owner_id
* state
* type
* featured image
* and name

missing details, like:
* current goal
* pictures gallery
* rate
* detailed logs
* visited countries
* count watching users
* count place visited
* reported missing info

and maybe more...

On the IRC we told "no more html parsing"...
It would be cool if the GK webmasters can provide more info or API to retrieve those informations.

I can send them an email, proposing to discuss about that here.

### PR DESCRIPTION
**Pull request by kumy**
fix #4315: Add an icon to trackable representing "brand"
fix #4326: GeoKrety, some details are missing

* Load Geokrety Async while loading a cache
* Store brand into database
* rework xml parsing a bit on geokretyparser
* Create settings->service->Geokrety
* Load GK only if setting is active
* Add setting option to use GeokretyMap cache
* Make Geokrety loggable
* reworked LogTrackableActivity
* differenciate LogType and LogTypeTrackable
* Implement TrackableLoggingManager(s)
* Show GK in LogCacheActivity
* Implement GeokretyInventoryLoader
* Geokrety can be dropped in any loggable cache
* Moved Loaders to specific file. prevent loadersId conflict
* Geokretymap provides for some geokrety details infos
* Use geocode for accessing Geokret from LogCacheActivity
* Add geocode to TrackableLog

As discussed on IRC, here is some work for supporting GK.
Tests should pass.
I still have to write more unit tests.

I know there will be much to say.
Thanks for reviewing...

### CODE REVIEW

**Comment by Lineflyer** [comment]
I know this PR is rather huge and possiblty hard to review.
But how can we continue with that? I would be a pitty if the work done by @kumy would just not be considered. 
Can it be split up in smaller packages...would this help?
Can it be merged and possible problems analyzed afterwards?
Any ideas?

**Comment by samueltardieu** [comment]
You need to find a developer which commits into taking care of it from beginning to end. As far as I am concerned, I am currently not in a position to do it.

**Comment by SammysHP** [comment]
This is 4 months behind our master and cannot be merged anymore.

**Comment by Lineflyer** [comment]
@SammysHP Yes, this is the reason why I am asking how to go on with such PRs. @kumy did a lot of work which is now outdated, so I want ot understand what we have to change in our process to allow such contributions to be merged more easy. It's sad, that it might possibly get dropped now..

**Comment by SammysHP** [comment]
- make smaller pull requests
- discuss the implementation before start coding
- help reviewing
- find a collaborator for the merge (who is willing to assist during the implementation, the merge and afterwards) already at the beginning

**Comment by kumy** [comment]
@Lineflyer yes but no time... sorry

**Comment by kumy** [comment]
Code rebased.
raw/geokrety_14X_xml.xml need to be recreated (files lost).

**Comment by SammysHP** [comment]
Thanks for rebasing! But it is still a really huge PR and I doubt that anyone will review it. :/

Maybe @Bananeweizen, @samueltardieu and @rsudev can have a short look at it and then we can merge it into master (after the next release from master) to test it in real life (and hope that it works).

**Comment by kumy** [comment]
`final` qualifiers added, hope I've caught all of them.
Thanks for review.

**Comment by samueltardieu** [comment]
I'll see if I can add all the missing `final` in our current source base, since we just branched from `master` to `release` and it is a good time to do that. Then you can rebase your changes and make not having `final` a fatal error.

**Comment by samueltardieu** [comment]
The missing `final` qualifiers have been added (b2ffc2581c6630e313c4e623d0a40c8846e1e975) to the cgeo codebase.

**Comment by Lineflyer** [comment]
> and then we can merge it into master (after the next release from master) to test it in real life (and hope that it works).

I would appreciate that and support it by testing the feature.

**Comment by kumy** [comment]
>make not having final a fatal error
Do you know how to set this as `fatal` in IntelliJ Idea ? I only found `Error` but it doesn't prevent building.

**Comment by samueltardieu** [comment]
I don't think you can make this a build error, only an inspection error. If you do your commits from the editor, it can run the inspection on the files you commit automatically as far as I know. If you don't (which is my case), you have to manually run the inspection, or to look that files you are about to commit aren't flagged with a red square in the top right corner.

**Comment by kumy** [comment]
Thanks, I'll continue to check the red square.

**Comment by kumy** [comment]
Code rebased.

**Comment by Lineflyer** [comment]
If @samueltardieu or others think the code is clean enough after roughly looking at it, I would like to request to proceed as suggested by @SammysHP (i.e. to merge and debug possible deficiencies).
Right now we splitted up for release, so it might be a good time.

**Comment by kumy** [comment]
Code rebased.

**Comment by samueltardieu** [comment]
When trying the merge to master and running the tests, I get

```
--------- beginning of crash
03-28 16:36:24.223 E/AndroidRuntime( 2340): FATAL EXCEPTION: main
03-28 16:36:24.223 E/AndroidRuntime( 2340): Process: cgeo.geocaching, PID: 2340
03-28 16:36:24.223 E/AndroidRuntime( 2340): java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
03-28 16:36:24.223 E/AndroidRuntime( 2340): 	at cgeo.geocaching.LogTrackableActivity.onLoadFinished(LogTrackableActivity.java:112)
03-28 16:36:24.223 E/AndroidRuntime( 2340): 	at cgeo.geocaching.LogTrackableActivity.onLoadFinished(LogTrackableActivity.java:57)
```

@kumy, do the tests all work for you?

**Comment by kumy** [comment]
Argh, I can't look right now. Sorry.

**Comment by kumy** [comment]
Fixed this Exception.

Here are the unit tests results http://pastebin.com/3crg0pNx
There are 6 errors. Are they really related to my code ?

**Comment by Lineflyer** [comment]
On the first look this looks really great.
Need to create a test-GK now to do more tests.

**Comment by Bananeweizen** [comment]
I've fixed several warnings and other issues in the merged code. Our repository contains Eclipse project settings and IDEA project settings to avoid this. If you have imported the complete repository, they should even be applied automatically, so I'm wondering how you managed to not use them.

**Comment by kumy** [comment]
@Bananeweizen I used IDEA, as mentioned 12 days ago, I've reopened every files I've updated and checked the code inspector square status. It was green (after adding final statements) excepted for 2 or 3 files, where issues doesn't seem to be related to the code I've added. As you've corrected them (Thanks), I have examples where the code is "incomplete". I'll focus on them and try to understand why I didn't seen those warnings.

Thanks to all of you for your time & patience!

I'll stay around for supporting the code, and I'm open to suggestions.

Note: This PR is my first Java code and (real) contribution to OpenSource project.

**Pull request merged**
