### PR TITLE
add more database information to log and sysinfo

### PR DESCRIPTION
**Pull request by eddiemuc**
add more database information to log and sysinfo

### CODE REVIEW

**Comment by eddiemuc** [comment]
This will change database part of sys info to this:

image

It will also add a log line in logcat like this on c:geo startup:

`2021-11-28 09:36:28.837 10198-10198/cgeo.geocaching I/cgeo: [main] [DB] DB initialized: Path: /data/user/0/cgeo.geocaching/databases/data, V:98, Size:3.7 MB on system internal storage, WAL-enabled: false, IntegrityOk: true, ReadOnly: false, Page Size: 4096, Max Size: 4.0 TB`

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
retest this please

**Comment by kumy** [comment]
retest this

**Pull request merged**
