### PR TITLE
tiny adjustments to findWaypoint

### PR DESCRIPTION
**Pull request by moving-bits**
see https://github.com/cgeo/cgeo/pull/9678#discussion_r552693205 ff

### CODE REVIEW

**Comment by murggel** [comment]
similar posted in (before I saw this PR) https://github.com/cgeo/cgeo/pull/9678#discussion_r552734502
Hm, I think there was a problem with waypoint-type OWN and WAYPOINT. Because they have same name and hence same waypoint-name created from that, a duplicate waypoint with same name could be created, so I checked the names. 
Checking the special waypoint types separately here?

**Comment by moving-bits** [comment]
> Hm, I think there was a problem with waypoint-type OWN and WAYPOINT.

Do you have some test data I can check this against?

**Comment by fm-sys** [comment]
> > Hm, I think there was a problem with waypoint-type OWN and WAYPOINT.
> 
> Do you have some test data I can check this against?

Shouldn't such special cases be also added as Unit Tests?

**Comment by murggel** [comment]
> 
> 
> > > Hm, I think there was a problem with waypoint-type OWN and WAYPOINT.
> > 
> > 
> > Do you have some test data I can check this against?
> 
> Shouldn't such special cases be also added as Unit Tests?

you are right, I will check later (no kids needs maintenance :-) ), if there is some ... hm, build is red - test is red - probably this is one of those :-)

**Comment by moving-bits** [comment]
Ah, now I see. Then let's stay with `getL10n()` comparison - the tests are green in that case.

**Comment by murggel** [comment]
> Ah, now I see. Then let's stay with `getL10n()` comparison - the tests are green in that case.

Ok, thanks for looking into it and sorry for the confusion.

**Pull request merged**
