### PR TITLE
Google maps v2

### PR DESCRIPTION
**Pull request by UniQP**
Update from Google Maps v1 to Google Maps v2.

### CODE REVIEW

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
AFAICS we have some new lint warnings from CI for this code:
https://ci.cgeo.org/job/cgeo%20pull%20request/2268/androidLintResult/new/

**Comment by UniQP** [comment]
@Lineflyer I fixed them.

**Comment by Lineflyer** [comment]
Great. Ci shows green. 
Now first target and compilesdk then merge this one?

**Comment by UniQP** [comment]
We need to merge this PR, before we can increase the compile SDK.

**Comment by Lineflyer** [comment]
Then lets rumble ;)

**Pull request merged**
