### PR TITLE
related to #9151: restore one-click-edit for own logs in loglist

### PR DESCRIPTION
**Pull request by eddiemuc**
related to #9151: restore one-click-edit for own logs in loglist

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

**Comment by fm-sys** [comment]
@eddiemuc did you see, that there is a merge conflict in `LogViewCreator` and a rebase is needed?

**Comment by eddiemuc** [comment]
> @eddiemuc did you see, that there is a merge conflict in `LogViewCreator` and a rebase is needed? 

Ups, no. Thanks for the hint.
Funny, why is this shown with green check in overview...

**Comment by bekuno** [comment]
> Funny, why is this shown with green check in overview...

Not funny, its normal.
The check is only done when you push content to the PR.
The conflict started later with another push to master.

**Comment by eddiemuc** [comment]
> > Funny, why is this shown with green check in overview...
> 
> Not funny, its normal.
> The check is only done when you push content to the PR.
> The conflict started later with another push to master.

It would be great if there was a way to get informed by GitHub when existing pull requests I own turn from "mergeable/nothing-to-do-by-me" to "not-mergeable/action-needed". Is there any way to configure this somehow?

**Comment by bekuno** [comment]
> > The check is only done when you push content to the PR.
> > The conflict started later with another push to master.
> 
> It would be great if there was a way to get informed by GitHub when existing pull requests I own turn from "mergeable/nothing-to-do-by-me" to "not-mergeable/action-needed". Is there any way to configure this somehow?

Maybe with a GraphQL (https://docs.github.com/en/free-pro-team@latest/graphql/guides) call.
There is the enum mergeablestate (https://docs.github.com/en/free-pro-team@latest/graphql/reference/enums#mergeablestate), which could somehow ask to all PR.
Don't know if it is really necessary to develop this.

**Pull request merged**
