### PR TITLE
fix #5739 add gpx filename in import progress dialog

### LINKED ISSUE #5739: GPX file name in Import progress dialog
This is a feature request.

##### Detailed steps causing the problem:
- import a GPX file
- there was too little or no feedback when user clicked on GPX file, before import started. User does not know for certain if he/she clicked on the correct file or not.
- the import progress dialog is shown. This dialog shows a predefined message only.
The user does not know which GPX file is currently importing.

##### Expected behavior after performing these steps:
- the import progress dialog to show the filename of the GPX file being currently imported.

##### Version of c:geo used:
2016-05-09

##### Is the problem reproducible for you?
Yes

### PR DESCRIPTION
**Pull request by pstorch**

### CODE REVIEW

**Comment by pstorch** [comment]
I think the failing tests are not related to this patch, but I'll have a look at it this evening.

**Comment by samueltardieu** [comment]
Retest this please.

**Comment by samueltardieu** [comment]
Retest this please.

**Comment by samueltardieu** [comment]
The tests should be (mostly) fixed, but now geocaching.com is crawling to death. Merging since we can't wait forever :)

**Pull request merged**
