### PR TITLE
Checkstyle AS + gradle integration for test folders

### LINKED ISSUE #8052: Checkstyle AS + gradle integration for test folders
Currently the gradle checkstyle integration is only for the c:geo code ("main").
We should configure checkstyle also for the test folders.

The PR #8045 should be without this part.

### PR DESCRIPTION
**Pull request by bekuno**
fix #8052

Has to be merged after PR #8045

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 30
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4764041&bid=15882741)

**Comment by moving-bits** [comment]
@Bekuno  Commit history looks pretty weird to me, having a couple of commits unrelated to this PR. Can you have a look at this?

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 30
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4764041&bid=15882741)

**Comment by bekuno** [comment]
The rebase problem is solved.
Now ready to merge.

**Pull request merged**
