### PR TITLE
Resolves #6835: Allow use of Brackets for the calculator while in 'Plain' format

### LINKED ISSUE #6835: Allow use of Brackets for the calculator while in 'Plain' format
As discussed in the original proposal for the calculator only single character 'labels' fit on the buttons requiring intermediary 'names' to be used:
image

However, in 'Plain' format we do not have such size restrictions, so allowing direct entering of bracketed expressions should be possable:
image

### PR DESCRIPTION
**Pull request by S-Bartfast**
Allow use of Brackets for the calculator while in 'Plain' format

### CODE REVIEW

**Comment by pstorch** [comment]
@S-Bartfast: as this is a new feature it should address `master` branch.
cc @Lineflyer

**Comment by pstorch** [comment]
I really would like to have this feature. Today I went for a small Multicache with just one final formula.
But this formula was complex enough, that I didn't want to set it up with the individual buttons. At home I checked out this PR and tried it with C&P of the formula in the Plain format. But the result is wrong:

image

It sould be: `N 54° 33.845 E 008° 37.679`
As you can see only the first brackets are evaluated and the rest of the expressions are ignored.

**Comment by S-Bartfast** [comment]
>As you can see only the first brackets are evaluated and the rest of the expressions are ignored.

Yup, this is a problem with the parser rather than an issue with the calculator as such.

Have you tried entering `N 54° 33.125+720` into the regular coordinate parser.  I'm pretty sure you'll get the same result.

It's not entirely clear to me why there are even brackets in that formulation at all.  Usually brackets are used to delineate discrete numbers but in this instance it appears the brackets are intended to assign mathematical priority –though mathematically the expression would be identical whether brackets were used or not.

In this instance though, given it appears you want to group everything after the decimal point into a single number you could simply enclose everything in another set of brackets.
As in:
`N 54° (A-1967).((Z*F)+720)`
`E 008° (K-1963).((330*G)+9)`

Or if it makes it eaiser to follow you could group the number in square brackets such that the round brackets look more 'mathematical'.
As in:
`N 54° [A-1967].[(Z*F)+720]`
`E 008° [K-1963].[(330*G)+(G*E)+9]`

The real issue here though is the fact that `N 54° 33.125+720` is not parsed as being an error.

**Comment by UniQP** [comment]
> The real issue here though is the fact that `N 54° 33.125+720` is not parsed as being an error.

The parse function currently tries to parse different formats and picks the longest match (`N 54° 33.125` in the example). I can add a check that it matches the whole string, if desired.

Might be related to #6802.

**Comment by S-Bartfast** [comment]
>I can add a check that it matches the whole string, if desired.

Yes, that will defiantly be needed.
I'll continue the discussion in #6802 itself.

**Comment by pstorch** [comment]
As mentioned in https://github.com/cgeo/cgeo/issues/6797#issuecomment-346464089 this should go to `release`. 
@S-Bartfast can you rebase onto `release`?
@UniQP #6850 is a prerequisite for this? Then please change to `release` as well.

**Comment by UniQP** [comment]
Done

**Comment by pstorch** [comment]
I've tried it again and merged in #6850 locally into this, but it doesn't solve it. So I guess something else needs to be done additionally.

BTW: adding extra brackets like `N 54° (A-1967).((Z*F)+720)` works, but without them should, too.

**Comment by S-Bartfast** [comment]
>BTW: adding extra brackets like N 54° (A-1967).((Z*F)+720) works, but without them should, too.

I don't think `"N 54° (A-1967).(Z*F)+720"` _should_ be a valid formulation.  The issue with this formulation is that the brackets are being used in a different way than they usually are.  Normally whatever is inside the brackets is replaced by the result of the expression contained inside them and these results are simply concatenated (joined together) to create the final representation.

In this example the brackets (I assume) are defining mathematical priority, which is not normally what brackets are use for in this context.

Sure, we would be able to run an evaluation over each of the groups (essentially automatically wrapping each group in brackets) but I don't think that would be advisable.  Basically I think the calculator should report errors rather than try to 'guess' at what was intended.  Like the example we had before with additional spaces after the decimal point, once we start interpreting what was _meant_ rather than what is actually there  we will quickly run into contradictions.

For instance, if:
`N 54° (A-1967).(Z*F)+720` is equivalent to `N 54° (A-1967).((Z*F)+720)`

Surely `N 54° A-1967.Z*F+720` is equivalent to `N 54° (A-1967).(Z*F)+720` as well (I mean those brackets in this case are meaningless).

And what about `1.5 + 10` is that `1.15`, or `11.5`?  Presumably it wold be `1.15` but it starts to get tricky
How about `1 1. 1.5*4` is that `1 1.6`?
Then what about `1 1.1.5*4` 
You see what I mean.

Best thing to do is to substitute brackets and provide errors.

**Comment by pstorch** [comment]
> > BTW: adding extra brackets like N 54° (A-1967).((Z*F)+720) works, but without them should, too.

> I don't think "N 54° (A-1967).(Z*F)+720" should be a valid formulation.

Hmm, I just copied it from the geocache description as regular users would do. And it is mathematically correct.

**Comment by pstorch** [comment]
> And what about `1.5 + 10` is that `1.15`, or `11.5`?  Presumably it wold be `1.15` but it starts to get tricky
> How about `1 1 . 1.5*4` is that `1 1.6`?
> Then what about `1 1.1.5*4` 

My brain hurts :face_with_head_bandage:

**Comment by S-Bartfast** [comment]
>My brain hurts 🤕

Yeah, that's my point.

What I'm saying is we need delimiters to know which parts of the string to "evaluate".  Normally this is done with brackets but in this case the brackets are not representing 'sections' to be replaced.  I don't doubt `"N 54° (A-1967).(Z*F)+720"` came directly from a cache's description, I'm saying that it's a format we wont be able to accommodate directly.

"Normal" descriptions are of the form `"S48 51.(C-A)(C+D)(C+A)"`, where `(C-A)`, `(C+D)` and `(C+A)` are evaluated and their results joined together.  In the example you have their there are no delimiters and there for no consistent way to know which parts of `"N 54° (A-1967).(Z*F)+720"` should be substituted.  As it is in this instance it appears everything after the decimal point is to be evaluated as a single expression but we can't always assume that.

The rule as it is now is simply:
>* If it's inside brackets it gets evaluated
>* If it's outside brackets it gets sent to the parser directly

If you have a suggestion for a better rule I'll be willing to hear it but I can't think of a better way myself, and it's not due to a lack of trying.

**Comment by Matze2** [comment]
I agree with @S-Bartfast here. The rule "surround every expression with parenthesis" is clear.
And most of the listings I checked follow this rule.

At the end it is all about transparency again:
"N 54° (A-1967).(Z*F)+720" would be evaluated to something like "N 54° 30.200+720" and this should be indicated as an invalid coordinate.

**Comment by Lineflyer** [comment]
>  I don't doubt "N 54° (A-1967).(Z*F)+720" came directly from a cache's description, I'm saying that it's a format we wont be able to accommodate directly.

Most cache listings will IMHO assume the decimal digits being (virtually) a dedicated number. So couldn't we (always) set our own brackets (I mean in terms of being able to calculate it) around the decimal part, where in this example it would be:
`N 54° (A-1967).(Z*F)+720` --> `N 54° (A-1967).((Z*F)+720)`

This would also give a clear rule for the brainhurting examples above, wouldn't it?

**Comment by Matze2** [comment]
With additional parenthesis around will

> GC768Y3, Stage 10
> N 48° 32.(G-K)(E+E)(C) E 11° 27.(K-C)(E+F+G+H)

still work?

**Comment by S-Bartfast** [comment]
>This would also give a clear rule for the brainhurting examples above, wouldn't it?

Possibly, 
Assuming you consider the first '.' or ',' as the decimal point this would make:
`1 1.1.5*4` -> `1 1.(1.5*4)` -> `1 1.20` - `1 1.020`
but that's quite a leap of faith.  I would think it would be safer to give an error and have the user clarify with brackets ;)

And another example:
`N 1° 2.3(A) * 2`, where `A = 4`
Grouping after the decimal would give: `N 1° 2.34 * 2` -> `N 1° 2.68`
But the cache owner could well have meant: `N 1° 2.3[A * 2]` -> `N 1° 2.38`

Their's just no way to be sure and rather than guess it would be safer to simply require a more explicit formulation.

**Comment by S-Bartfast** [comment]
>With additional parenthesis around will
>>GC768Y3, Stage 10
>>N 48° 32.(G-K)(E+E)(C) E 11° 27.(K-C)(E+F+G+H)
>
>still work?

Sure.

If a formulation was valid to begin with, additional parentheses will never make it _not_ work.
The issue is that inserting parentheses will potentially make invalid formulations appear valid.

**Comment by pstorch** [comment]
>  would think it would be safer to give an error and have the user clarify with brackets ;)

When I proposed this for the leading zero problem, it was rejected. Why can't we then "assume" here the most probable interpretation, too? 
Stopping at the first separator (`.` or `,`) and interpret the rest as a whole.

And with the brackets: evaluate each pair, replace with the result. After that look at the whole string and either calculate (if operators are present, like in `(Z*F)+720`) or concatenate (like in `(K-C)(E+F+G+H)`);

**Comment by S-Bartfast** [comment]
>>would think it would be safer to give an error and have the user clarify with brackets ;)
>
>When I proposed this for the leading zero problem, it was rejected.

I'm not sure why your proposal was rejected.  If anything that proposal would agree with my general philosophy for error detection/handling.  Possibly it was rejected as it differed from the behaviour of the Coordinate Input Dialog, something we were more concerned about before.

>Why can't we then "assume" here the most probable interpretation, too?

Partially it's because the most probable interpretation is not as clear (see `N 1° 2.3(A) * 2` for example) but mostly because in this example those brackets have a different meaning to the regular multi-cache brackets.

Normally, in a multi-cache formulation, brackets are used to designate "substitution elements", that is sections that are to be 'swapped' for evaluated values but that's not what they mean here.

Now, we could define our own rules as to what denotes a 'section' to be 'swapped' (and it seems you are advocating "everything after the first decimal point" as one such rule) but I see this as a road that is fraught with difficulties.  Sure, like @Matze2's "removing spaces after the decimal" suggestion in #6835 it seems such a rule would be simple to include but this really is just to tip of the iceberg.  If we were to define an "after the decimal" rule we really should try to implement something similar for before the decimal as well, which is much harder.

We will also need to consider what to do if evaluating an expression changes the number of decimals as well.  For instance consider the formulation: `N 12 A*3` where `A = 1.5`.  Should this be evaluated as `N 12 1.15` (grouping after the decimal) or `N 12 4.5` (multiplying "A" by 3).  And I could go on...

My point being, while we could potentially write our own "lexer" (as it is known) for coordinate strings this is a bigger task than most would at first think and I for one simply don't think it's worth it.

**Comment by pstorch** [comment]
>  I for one simply don't think it's worth it.

You just don't want headaches, right? :innocent:

I don't know how much effort is worth putting into it. It clearly depends on how much you want to put into it. We all do it voluntarily. 

What is the best we can do right now? Start a release with what we have (incl. this PR) and see what users think about it?

**Comment by Matze2** [comment]
Honestly, I don't understand why all these useful pull requests are still hanging in the queue. I don't understand these theoretical discussions if N 1 or N 1.0 is a valid coordinate. We are not university anymore.
I could name at least one cache which is not covered at all by the current implementation but i won't because I would like to try this PR and hopefully also #6842/#6848 in master at least and not create yet another useless discussion about the perfect coordinate scanning.
Me as a nightly user would like to try these features in practice and not discuss about theoretical coordinate patterns that I will never make use of.
Unfortunately, using cgeo-debug.apk is not an option for various reasons (Google Maps is one of them), otherwise I would have put together my own cgeo since some time and not using nightlies that do not fulfill their purpose anymore.

**Comment by S-Bartfast** [comment]
>>I for one simply don't think it's worth it.
>
>You just don't want headaches, right? 😇

Essentially yeah. It's not that I'm not willing as such, it's more that I would imagine writing such a parser would be a extensive task and I'm not convinced that it would make the product any better.  In fact I actually think it would make the product less good.

If we can define a set of rules that govern how 'groups' should be defined than sure, I'll be happy to implement it.  The problem is that it's actually quite difficult to clearly define exactly what should constitute a 'group'. At the moment the 'groups' are defined by "What's between the brackets", which on the whole is the 'normal' convention used in descriptions, and I think it's a good convention. As it is I did actually foresee the possibility that formulations such as this one may arise so implemented the ability to use 'nested' brackets, along with the use of square and curly brackets/braces.  While this isn't immediately obvious and certainly isn't helped by lack of feedback, it was an attempt to cover exactly this type of unexpected formulation.

>I don't know how much effort is worth putting into it. It clearly depends on how much you want to put into it. We all do it voluntarily.

Sure, but to be fair I have put literally 100's of hours into this project over the past few months.  In fact the only reason I've been able to devote as much time as I have is that I am currently out of work and largely devoting all the time I have to the project (which of course I do willingly) but to imply that the reason I prefer the use of brackets rather than creating a parser to define groups is due to laziness or an unwillingness to put in the effort is a bit disingenuous.  As I say, I would be willing to "put in the effort" if it were clear what the solution should be and that it were to improve the product, neither of which I believe is true at the moment.

**Comment by S-Bartfast** [comment]
>What is the best we can do right now? Start a release with what we have (incl. this PR) and see what users think about it?

I think the calculator is pretty functional at the moment and certainly worthy of being used in the main app.  While I would like to be able to improve the error feedback provided to the user, just to help guide them a little more through these type of unexpected situations, that could be a ways off as it really is dependant upon getting more details from the coordinate parser. 

Also, if someone skilled in the art of web design could write a user guide it would be good to include #6664 (Incorporate usage guide into WP calculator) with the release as well.  While the framework for displaying the page has already been done and I would of course be more than happy to contribute to the technical details I'm afraid I'm not really up to the task of writing the guide itself.  So if someone with the know-how could produce a guide, that would make a really good addition to the release.

**Comment by S-Bartfast** [comment]
>I could name at least one cache which is not covered at all...

Oow, which cache would that be :p

To answer your question though...
The reason we keep getting hung up on these issues is that we do not want to put anything into the field that creates a precedent that needs to be rolled back later.  While we could probably be a little looser with allowing experimental concepts into the nightly build the reason we are reluctant to be too free is because once out there it's much harder to bring back.  As I say, we could probably afford to be a  little freer than we currently are for the nightly, but that's the reason for getting hung up on such seemingly pedantic details.

**Comment by pstorch** [comment]
> Honestly, I don't understand why all these useful pull requests are still hanging in the queue.

Yes, that is a difficult situation right now. I don't like either. There are several things that come together. We want to make a release with the first version of the calculator, but don't want to put more changes in the release as necessary to avoid breaking it. Then it looks like most of us core developers don't have time at the moment to review and test the changes. I feel a bit lonely a at the moment with these tasks and I don't want to decide it all by myself. That's why I ask so much and try to discuss where I am uncertain. Unfortunately that also leads to these difficult  edge cases. 
On the other hand I try to keep it going and move forward as much as I can.

**Comment by pstorch** [comment]
>  I have put literally 100's of hours into this project over the past few months.

It might not look like that when reading my comments, but I really appreciate your contributions.

**Comment by Matze2** [comment]
@pstorch Yes I see that you try to keep things rolling (desperately :wink:).

I just wonder why this couldn't be merged to master at least. Currently master and release are regulated in the same way.

Perhaps all others like me are just too tired to read all these posts and just want to try that feature.
I do not see how the PRs 6836 and 6848 make things worse than it is now in master and release.

**Comment by S-Bartfast** [comment]
>It might not look like that when reading my comments, but I really appreciate your contributions.

Yeah, I have no doubt that you do.
And although it may not look like it, I do actually really appreciate your comments ;)

**Comment by pstorch** [comment]
> I just wonder why this couldn't be merged to master at least. Currently master and release are regulated in the same way.

Because we want to have it in the `release`. When we merge it to `master` first, we can't easily merge it to `release` afterwards without pulling in all other changes in `master` in the meantime. Then we would fiddle around with cherry-pick, which I want to avoid.

**Comment by pstorch** [comment]
Tried it again, now I get this:
image

It doesn't give a wrong result anymore as before. It now gives me the intermediate result and some clue what to do. If I add extra brackets it evaluates the rest, too. 

I still think it would be "nice" to do the rest of the calculation as I would interpret it, but I'm totally fine if we start with this version for the `release`. 

If you can sort out the commits (squash into one and rebase on current `release`) I think we can finally merge it.

**Comment by S-Bartfast** [comment]
>If you can sort out the commits (squash into one and rebase on current release) I think we can finally merge it.

I'm trying to.
I'm having a great deal of trouble removing the "clean-up" commit though.
Would it be okay to squash the 'clean-up' commit into this one?

**Comment by pstorch** [comment]
> Would it be okay to squash the 'clean-up' commit into this one?

Let's give it a try.

**Comment by S-Bartfast** [comment]
>>Would it be okay to squash the 'clean-up' commit into this one?
>
>Let's give it a try.

Works for me (:

**Comment by pstorch** [comment]
Still thinking about. Maybe it's better when I cherry-pick this commit to release, because it is needed for two PRs.

**Comment by S-Bartfast** [comment]
>Maybe it's better when I cherry-pick this commit to release, because it is needed for two PRs.

I don't follow?

So, I've merged the 'clean-up' code in to this commit, and have now rebased the #6842 (Highlighting) onto this release, mainly to take advantage of the 'clean-up'.

Are you talking about excluding the 'clean-up' code again?

**Comment by pstorch** [comment]
This is merge now via PR #6848

**Pull request closed without merging**
