### PR TITLE
introduce full changelog (rel. to #10701, part b)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
This PR introduces a differentiation between to-be-published changelog and "full" changelog by providing the infrastructure for it. (No changes to `changelog_master.md` yet, but cleaned `changelog_release.md` to show a possible differentiation between full and shortened changelog.)

The "full" changelog is divided into sections "next release" (`release`), "current development" (`master`) and published releases. As it starts with our latest release `2021.05.20`, it also contains a link to our release history for older releases.

This page (`raw/changelog_full.md`) can be linked to from our website as official release history.

### CODE REVIEW

**Comment by Lineflyer** [comment]
Cleaning of `changelog_release.md` on master is not necessarily needed on `master`. But I guess you did this only the show the working mode...

The method to merge changelogs when forwarding `release` to `master` should not change with your proposal, correct?

**Comment by moving-bits** [comment]
> Cleaning of `changelog_release.md` on master is not necessarily needed on `master`. But I guess you did this only the show the working mode...

I did that only as `changelog_release.md` contained things already released, which are listed in the `2020.05.20` section. So this was only due to `release` branch not yet using our markdown files.

> The method to merge changelogs when forwarding `release` to `master` should not change with your proposal, correct?

No, AFAICS. `changelog_release.md` will be filled on `release` branch only, and `changelog_master.md` on `master` only. When we merge PR, we have to decide whether the change goes to no changelog (internal technical fixes, not relevant for the end-user), to `changelog_full.md` only, or additionally to `changelog_master.md` or `changelog_release.md` (depending on the branch you are working on).

---

I'll try to describe the steps necessary (with regards to changelog handling) - should be pretty similar to today, but handling the "md" files instead of "xml", and taking care of version numbers and full changelog.

@Lineflyer  Please cross-check

To prepare a release the following steps would be needed:
- on `release`:
  - make sure `changelog_master.md` is empty
  - edit `version_release.txt` to contain the new version number (e. g.: `2021.05.22`)
  - edit `changelog_full.md`: move contents of `release` section down to the `old releases` section, leaving an empty `release` section
- merge `release` to `master`
- release as today
- on `release`:
  - clear `changelog_release.md`
  - reset `version_release.txt` to "next release" (or something similar)

On preparing a release branch the following steps would be needed:
- on `master`:
  - move content of `changelog_master.md` to `changelog_release.md`, leaving an empty `changelog_master.md`
  - edit `changelog_full.md`: move contents of `master` section up to `release` section, leaving an empty `master` section
- forward `master` to `release`

**Comment by Lineflyer** [comment]
Not sure if your above sequence is right. You start at another point than we usually do.
This description should still be valid (I replaced *.xml by *.md): https://github.com/cgeo/cgeo/wiki/Prepare-a-release

Just add there, that:
- We need to maintain the version_release.txt (version_master.txt is IMHO not needed as `master` is always only nightly as we only release from `release`)
- We need to add your proposals of what to add to the well known files and what to add in the "full" version.

**Comment by moving-bits** [comment]
Updated PR:
- provide `version_release.txt` for release version number (leave empty to use default title "Next release")
- use default title "Nightly build" for master (no `version_master.txt` needed)

**Review by Lineflyer — APPROVED** [review]
LGTM

**Pull request merged**
