### PR TITLE
differentiate size "not chosen" and "other" for GC.com

### LINKED ISSUE #13795: Filtering of cache size "not chosen" versus "other"
### Describe your problem!

Reported by a user on support mail:

The filter in the map shows caches with the size "not chosen" even if I only filter on "other".

Many challenges does not equal "not chosen" and "other", so that could cause problems if I would find one of the wrong kind.

### How to reproduce?

For example https://coord.info/GC25KQD, a "not chosen" that still shows up with filter with only "other".
That same cache shows up if I only filter on "not chosen" too.

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

2022.12.21

### System information

_No response_

### Additional Information

Support ticket 484323

### PR DESCRIPTION
**Pull request by ztNFny**
fixes #13795

not sure whether this should be merged. See https://github.com/cgeo/cgeo/issues/13795#issuecomment-1369584410

### CODE REVIEW

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
@moving-bits can we merge this?

**Comment by moving-bits** [comment]
Did a quick test to understand what this PR does. I guess this is meant for filtering?
If I select "not chosen" I would expect earth caches to be listed (from reading the comment in the source), but those will show up when selecting "other" (like events).

**Comment by ztNFny** [comment]
> If I select "not chosen" I would expect earth caches to be listed (from reading the comment in the source), but those will show up when selecting "other" (like events).

You'll get ECs published until 2012:

> "Not chosen" (size 1) can no longer be selected at GC - it was available for all caches and the only value for EC, virtual, Webcam until 2012. Since then those types are using "Other" (size 6).

**Comment by moving-bits** [comment]
ok, I see. I can understand the issue posted in the referenced issue, OTOH it might break the workflow for other users used to filter for "other" only, now no longer getting all EC etc.

Anyway, let's try this in the nightlies and see what may come up as user feedback.

**Pull request merged**
