### PR TITLE
fix #15514: repair named filter handling on filter quickchange

### LINKED ISSUE #15514: Name of Saved Filter gets lost on adding criteria via Map's bottom sheet
### Describe your problem!

In (Live) Map's header the Name of the currently active Saved Filter gets replaced by the criteria (resp. its count(s)),
as soon as you deselect a Filter relevant criterion via Quick Settings of the map.
Moreover no name will be displayed in the Filter dialog anymore.

### How to reproduce?

Create and apply an appropriate filter:

1. open (Live) Map
2. open Filter dialog page by clicking the filter icon
3. in advanced mode, create a simple filter like "Type=Tradi" and store it as e. g. "Tradis only" 
4. return to live map by applying the filter

Header now shows name of applied filter (as to be expected)

5. open Quick Settings bottom sheet by clicking the cog
6. disable "Found"
7. apply the change by click on the map

### Actual result after these steps?

8. neither header nor filter dialog will show the name of the (changed) stored filter anymore.
    Instead in Map there will be the criteria of the filter and in Filter dialog just an empty field.

### Expected result after these steps?

The name of the Saved Filter should be shown, with its "changed markers" (i. e. name in brackets, italic, plus the star).
Same applies for the Filter dialog (to be able to easily change the saved version).

### Reproducible

Yes

### c:geo Version

2024.03.24-NB-3da0a92

### System information

_No response_

### Additional Information

Currently there's no way to overwrite, i. e. change the definition of a Saved Filter after such a change, other than either typing the filter's name by heart or (if it's more than just a no-brainer) discard the actual changes, re-apply the saved version of the filter in question, copy its name from the save dialog to clipboard, re-apply manual changes, open save dialog and paste the name from clipboard ... little bit cumbersome.  ;)

BTW, WRT the example above: After enabling "Found" again and then opening the filter page, the criteria group "Status" is still there, although all states are enabled - wouldn't it be better to drop the criteria group, if it does not add anything to the filter? 

Moreover, I tried the above with offline map, too (from mapping a stored list) and got curious results: Sometimes it behaved like in Life Map, sometimes the name of the filter vanished completely, although the filter was still active.

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #15514: repair named filter handling on filter quickchange

### CODE REVIEW

**Comment by eddiemuc** [comment]
Retest this please

**Comment by moving-bits** [comment]
@eddiemuc @murggel 
On merging `release` to `master` I got a merge conflict in `GeocacheFilterActivity.getFilterFromView()`. I resolved it by stacking both of your new calls, leading to
```
return GeocacheFilter.create(
  FilterUtils.getPurifiedFilterName(GeocacheFilter.getFilterNameFromUserDisplayName(binding.filterStorageName.getText().toString())),
  binding.filterBasicAdvanced.isChecked(),
  this.includeInconclusiveFilterCheckbox.isChecked(),
  filter);
```

Kindly cross-check if this makes sense in this context.

**Comment by murggel** [comment]
@moving-bits , @eddiemuc 
`GeocacheFilter.getFilterNameFromUserDisplayName` should not be necessary, this function was replaced by `FilterUtils.getPurifiedFilterName`

I will try the version
```
return GeocacheFilter.create(
  FilterUtils.getPurifiedFilterName(binding.filterStorageName.getText().toString()),
  binding.filterBasicAdvanced.isChecked(),
  this.includeInconclusiveFilterCheckbox.isChecked(),
  filter);
```

**Comment by murggel** [comment]
@moving-bits @eddiemuc 
I tried this version and it looks correct / better to me, otherwise changing a changed filter leads to a name in braces 
```
return GeocacheFilter.create(
  FilterUtils.getPurifiedFilterName(binding.filterStorageName.getText().toString()),
  binding.filterBasicAdvanced.isChecked(),
  this.includeInconclusiveFilterCheckbox.isChecked(),
  filter);
```
Shall I create a PR for this based on master?

**Comment by murggel** [comment]
see PR https://github.com/cgeo/cgeo/pull/15521

**Comment by eddiemuc** [comment]
@murggel @moving-bits 
GeocacheFilter.getFilternameFromUserDisplayname() is probably now not used any more and can be deleted completely.

@murggel I saw this just now: are your new methods for filter name formatting the only reason thatFilterUtils is now used in GeocacheFilter? In that case I suggest moving them to class GeocacheFilter. Reason: FilterUtils has strong ties to GUI and Android objects (unfortunately not recognizable in its name) while GeocacheFilter is a pure model class (no ties to GUI)

**Comment by murggel** [comment]
> @murggel @moving-bits 
> GeocacheFilter.getFilternameFromUserDisplayname() is probably now not used any more and can be deleted completely.
> 

I will remove it 


> @murggel I saw this just now: are your new methods for filter name formatting the only reason thatFilterUtils is now used in GeocacheFilter? In that case I suggest moving them to class GeocacheFilter. Reason: FilterUtils has strong ties to GUI and Android objects (unfortunately not recognizable in its name) while GeocacheFilter is a pure model class (no ties to GUI)

Probably it was the only reason, didn't thought of the gui-dependencies.
I will check and move it

**Pull request merged**
