### PR TITLE
fix #12030: add pin to waypoints on osm

### LINKED ISSUE #12030: Waypoint icons on map missing their "pin" on Mapsforge
### Describe your problem!

Since latest nightly update the waypoints on the map are missing their "position pin".
The cache icons are OK.

image

### How to reproduce?

Look at the map with activated waypoints :)

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

2021.11.02-NB1

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #12030: add pin to waypoints on osm

### CODE REVIEW

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
Build has this git access problem which was mentioned earlier by @Lineflyer too. I will retry a few more times, but there's not much I can do right now...

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Pull request merged**
