### PR TITLE
fix #10224: introduce otm for slow theme usage

### LINKED ISSUE #10224: How to make theme users aware of improvement by zip/sync?
Up to now we included improvement infos (use zipped theme, sync theme) at two places:
- In Settings - Map - Info on Map Themes
- In our FAQ

Both are not places where John Average will look at.
As you can see in the beta survey (and as I can see on support mail) some users notice this map start delay.
Some of those might contact us, but most will probably just think "It got worse" and do nothing.

I am no explicit fan of those one time messages (especially as it would be the third one on map) but maybe it would be just another case, where it might be helpful?!
It would just need to get shown under special conditions:
- Offline map used
- User defined theme active
- Sync is off
- Theme is not zipped

It could contain the text of the second section as in "Info on Map Themes" and a link to https://faq.cgeo.org/#theme-slow

BTW:
The link behind "More" in "Info on Map Themes" should rather target to that link as well instead of the user guide.

But maybe someone has a better proposal than using an one time message?!

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #10224: introduce otm for slow theme usage

### CODE REVIEW

**Comment by eddiemuc** [comment]
Whenever a "slow map theme" is selected (non-zipped, non-sync) or map viewer is opened and such a theme is preselected, then following one-time-dialog appears:

image

The "More Information" button leads to the FAQ-page

**Review by fm-sys — APPROVED** [review]
LGTM 👍

**Comment by Lineflyer** [comment]
@fm-sys For future: Feel free to merge if you reviews and/or tested a PR and it looks good to you. :)

**Comment by fm-sys** [comment]
> @fm-sys For future: Feel free to merge if you reviews and/or tested a PR and it looks good to you. :) 

Ok, will do :-)

Just wanted to keep this PR open a little longer, cause I reviewed like 3 minutes after CI got green...

**Comment by Lineflyer** [comment]
Ok, thats reasonable as well. Did not pay attention to the timeline in this case. 
For sure 1-2 days time depending on urgency might be wise, to give others a chance to review as well.

But anyway @cgeo/team:
Feel encouraged also to review merged PRs...we can still revert or fix issues for those.

**Comment by eddiemuc** [comment]
Wrt merging PRs, after talking to @moving-bits some time ago I now follow the practice to merge self-insure non-critical small PRs myself after leaving 1-2 days review time - except of course something comes up during this time.

**Pull request merged**
