### PR TITLE
add attribution to material design icons (fix #10858)

### LINKED ISSUE #10858: Add license for materialdesignicons
Some of the svgs I used were taken from materialdesignicons.com, which is under the Apache 2.0 license.

We have to add it and mention, that some were modified. I am not sure, if we have to mention, which ones are modified or if a general hint is sufficient.

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Add attribution to material design icons in about:contributors' page

### CODE REVIEW

**Comment by fm-sys** [comment]
Please note that the icons are officially designed by material.io which is owned by Google. The website you mentioned is just a third-party website, kind of a wrapper for the icon collection. 

Correct attribution would be Material Design Icons (https://material.io/) Licensed under Apache-2.0 License.

**Comment by moving-bits** [comment]
ok, if they are all from material.io originally, then we already have attribution for it, see the line above it.
My thought was, that there are also community-built icons not covered by material.io, but haven't checked it explicitly.

**Comment by fm-sys** [comment]
Ok, then we should probably find a more suitable name then "Material Design Icons". Maybe "Community Material Icons" instead?

Cause the "material design" is the official Google project. So if we just use "material" it's clear that they do not directly belong to this design framework but are based on the same principles...

**Comment by moving-bits** [comment]
Let's first ask @murggel whether the icons are all material.io based - then we don't need an addition attribution, or where else they do come from, and under what license (seems to be Apache 2.0, but let's be on the safe side).

**Comment by murggel** [comment]
No, they are not all the official ones, some are from the "community"
I am just preparing an overview, which are original material.io, which are from community and which are modified...

**Comment by moving-bits** [comment]
ok, then we need to look whether any of the community icons has a different license than Apache 2.0
Do we need to add a per-icon attribution? (Like we do for The Noun Project)

**Comment by murggel** [comment]
I found following info respect to the license:
https://github.com/Templarian/MaterialDesign/blob/master/LICENSE
There it is mentioned, 
```
This icon collection is released as free, open source, and GPL friendly by the [Pictogrammers](http://pictogrammers.com/) icon group. You may use it for commercial projects, open source projects, or anything really.
Icons: Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
Some of the icons are redistributed under the Apache 2.0 license. All other icons are either redistributed under their respective licenses or are distributed under the Apache 2.0 license.
```

But I did not find, under which license e.g. the following icon is, which I used
grafik

So, if nothing is mentioned, does it mean, it is under the Apache 2.0 license?

**Comment by moving-bits** [comment]
Yeah, that's probably the same as I have found: https://dev.materialdesignicons.com/license

So I guess: if no other license is mentioned specifically, Apache 2.0 license can be applied.

**Comment by murggel** [comment]
> 
> 
> Yeah, that's probably the same as I have found: https://dev.materialdesignicons.com/license
> 
> So I guess: if no other license is mentioned specifically, Apache 2.0 license can be applied.

Ok, then I will go through all "communtiy"-icons and check, whether a special license is applied - I guess not, but who knows.

Thanks for cross-check!

**Pull request merged**
