### PR TITLE
rel to #15194: adjust stored list grouping according to feature requests

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #15194: adjust stored list grouping according to feature requests

### CODE REVIEW

**Comment by eddiemuc** [comment]
image

**Comment by eddiemuc** [comment]
image

**Comment by ztNFny** [comment]
Maybe indent it to align the icons (in non-checkbox mode)?

**Comment by ztNFny** [comment]
> Maybe indent it to align the icons (in non-checkbox mode)? 

private int groupedItemPaddingInDp = 36; would achieve that

**Comment by eddiemuc** [comment]
> > Maybe indent it to align the icons (in non-checkbox mode)?
> 
> private int groupedItemPaddingInDp = 36; would achieve that

Ok, changed

**Pull request merged**
