### PR TITLE
delete unused class FloatItemRangeSlider

### PR DESCRIPTION
**Pull request by eddiemuc**
delete unused class FloatItemRangeSlider. Just a small code cleanup.

### CODE REVIEW

**Comment by eddiemuc** [comment]
I get HTTP 404 when tryping to access our Jenkins. Is the CI down?

**Comment by Lineflyer** [comment]
> I get HTTP 404 when tryping to access our Jenkins. Is the CI down?

Sorry, my fault. I renamed the job to get rid of the empty spaces in the URL. Also trying to make sure, that its not those being the reason for some file not found errors (which was not the case).
The new job URL is: https://ci.cgeo.org/job/cgeo-CI-PR-build/282/

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Comment by eddiemuc** [comment]
retest this please

**Pull request merged**
