### PR TITLE
Work on #6150 - Add attribution for OSM

### PR DESCRIPTION
**Pull request by Lineflyer**
...at least into "About c:geo" for now

### CODE REVIEW

**Comment by Lineflyer** [comment]
@SammysHP 
I know, but at least this would be a first step until this is realized as requested in #6150.
Or do you think it does not make sense at all?

**Comment by Lineflyer** [comment]
Corrected typo

**Comment by Lineflyer** [comment]
Damn...I wanted to target release but failed to do so.

**Comment by Bananeweizen** [comment]
cherry picked to release

**Comment by Lineflyer** [comment]
Thanks!

**Pull request merged**
