### PR TITLE
add shadows to map overlay buttons

### PR DESCRIPTION
**Pull request by ztNFny**
As requested by @moving-bits a [long time ago](https://github.com/cgeo/cgeo/pull/13063#issuecomment-1146778743) this PR now adds a shadow effect to all map buttons (zoom, quick settings, location, compass).

Small but unavoidable side effect: The buttons get a bit darker. This is because the buttons have white background with a slight transparency and the shadow is drawn behind the whole button - so also behind the transparent part.
As the buttons are already #FFF there's no way to make them whiter to offset the shadow. Reducing the transparency would make them whiter - but also less transparent, which they already are only slightly.

Alternative: We remove the transparency completly. (Transparency levels between old and none don't work, even old has only little transparency, any tuning very quickly arrives at no transparency)

(this PR relies on/includes https://github.com/cgeo/cgeo/pull/16290)

| Before | After |
| :---:   | :---: |
| Screenshot_20241031_190942 | Screenshot_20241031_201203 |

| darker transparent buttons = After | Non-transparent buttons | 
| :---: | :---: |
| Screenshot_20241031_201203 | Screenshot_20241031_201311 |

### CODE REVIEW

**Comment by moving-bits** [comment]
like it, makes the buttons more readable. Thanks for diving into this!

**Comment by ztNFny** [comment]
> like it, makes the buttons more readable. Thanks for diving into this!

which version? Transparent vs non-transparent?

**Comment by moving-bits** [comment]
> > like it, makes the buttons more readable. Thanks for diving into this!
> 
> which version? Transparent vs non-transparent?

IMHO the non-transparent version is even more readable, as the buttons stand out a bit more

**Comment by ztNFny** [comment]
after using both versions for half a day each the transparent one feels more natural, cgeo-ish to me. Could be because I'm used to it being slightly transparent. So I vote in favor of transparent, but could live with both version. A 70-30 vote I guess.

**Comment by ztNFny** [comment]
there are some more issues with the non-transparent versions, like the scale on Google Maps being covered by the buttons. So I suggest we go with the transparent version.
If further tweaks are required in future we can still adjust.

**Comment by moving-bits** [comment]
Although I would prefer the non-transparent version, the version with transparency would be ok for me as well.

**Comment by eddiemuc** [comment]
Does this PR currently implement the "transparent" version (which from discussion seems to be the preference)? In this case I suggest to merge this PR.

**Comment by ztNFny** [comment]
> Does this PR currently implement the "transparent" version (which from discussion seems to be the preference)? In this case I suggest to merge this PR. 

Yes

**Pull request merged**
