### PR TITLE
Fixes #5195, Bad overlay sizing

### LINKED ISSUE #5195: Bad overlay sizing
From german geoclub.de as announced by @SammysHP on IRC.
Look at the overlay for "final available" near middle of the screen.

http://show.picr.de/23125480nr.jpg.html

On current nighlties as well as on release.

### PR DESCRIPTION
**Pull request by rsudev**
- remove superfluous code from CacheListAdapter
- create new insets and adapt inset handling to accomodate list and map

### CODE REVIEW

**Comment by rsudev** [comment]
Finally I was able to at least partly untangle the current mess in our map icon and overlay sizes to produce consistent visual results for map and list.
If no objections arise, finally the new version can be produced and put to release...

Some screenshots:
- ldpi
map_ldpi
list_ldpi
- mdpi
map_mdpi
list_mdpi
- hdpi
map_hdpi
list_hdpi
- xhdpi
map_xhdpi
list_xhdpi

**Comment by samueltardieu** [comment]
Be my guest!

**Comment by kumy** [comment]
In lists caches icon don t have the same size if there is no overlays

**Comment by samueltardieu** [comment]
That's right. However, I feel like it does not hint readability enough to block the release. Would that be fine to include a fix for this in the next bugfix release ?

**Comment by kumy** [comment]
Don t block the release for that. BTW, I have little time at the moment to work on c:geo.

**Pull request merged**
