### PR TITLE
WIP: Testing GKv2 website on cgeo

### PR DESCRIPTION
**Pull request by kumy**
This is just a lazy way for me to get a working cgeo build without complete dev environment
Please do not merge

### CODE REVIEW

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this please

**Comment by kumy** [comment]
test this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
:partying_face: first time I get a successful build!

**Comment by Lineflyer** [comment]
@kumy  See https://github.com/cgeo/cgeo/issues/12182 
I disabled cgeo-5 as this was constantly failing. cgeo-1 seems a bit better but has other sporadic problems.

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by kumy** [comment]
retest this

**Comment by Lineflyer** [comment]
@kumy 
The branch is still there and can remain. Can we however close this PR for now?

**Comment by kumy** [comment]
No problem for me :+1:
Thanks

**Pull request closed without merging**
