### PR TITLE
update many icons

### PR DESCRIPTION
**Pull request by ztNFny**
- use solid material icons everywhere (replace the few "outline" icons in use)
- fix several issues with icon visibility in dark/light theme by tinting them
- icons for (un)watch and (un)favorite 
- new icon for user menu
- trackable logo
- remove some old unused ones
and more ...

### CODE REVIEW

**Comment by ztNFny** [comment]
image
image
image

**Comment by Lineflyer** [comment]
Thanks @ztNFny 
Lets take a look at them in our nightlies. If there are different opinions on some icons we can later open dedicated issues. But for me, those look good.

BTW:
Shall we add credits for the Travelbug icon into "About c:geo"?

**Comment by fm-sys** [comment]
The new "history" icon looks a bit unexpected on a first glance. Probably we will get used to it, but what was the exact reason you changed that icon? 

Screenshot_20211107_151240_cgeo geocaching

**Comment by ztNFny** [comment]
> but what was the exact reason you changed that icon?

The old one was a "clock" icon which seemed wrong when there's an actual "history" icon that's used in many apps for history (e.g. chrome)
https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Ahistory%3A

**Pull request merged**
