### PR TITLE
fix #10070, #10082, #10080: synchronize map theme folder in background

### LINKED ISSUE #10070: [Nightly] Syc'ing themes folder to internal storage does not work
**Describe the bug:**
After upgrading to the latest nightly this morning I got the wizard for changing the ``_themes`` folder from Legacy to SAF.
Did so, everything seemed to run smooth, the wizard sync'ed the folder to internal storage (as he reported in the popup),
but after opening the OSM live map, I do not see any themes at all anymore. And there should be plenty of ...
(about 16 or so, cause currently I experiment with different sizes for texts and symbols and stuff).

**To Reproduce:**
1. let the wizard switch your themes folder to SAF notation
2. open live map (default theme is shown)
3. try to switch to a differnet theme ...

**Actual behavior/state after performing these steps:**
Apart from ``default`` there are no themes at all.

**Expected behavior/state after performing these steps:**
My themes should be there as usual.

**Version of c:geo used:**
2021.02.24-NB-8f387a6

**Is the problem reproducible:**
Yes

**System information:**
```
--- System information ---
c:geo version: 2021.02.24-NB-8f387a6

Device:
-------
- Device type: VOG-L29 (VOG-L29EEA, HUAWEI)
- Android version: 10
- Android build: VOG-L29 10.1.0.150(C431E19R2P5)
- Sailfish OS detected: false
- Google Play services: disabled - 21.02.14 (120400-352619232)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: own/found archived
- Hide waypoints: -
- Set language: en_DE (system default)
- System date format: dd/MM/y
- Debug mode active: no
- Live map mode: true
- Global filter: display all caches
- Last backup: 23 Feb, 22:49
- Routing mode: Car

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   extremcaching.com: Logged in (Login OK)
- Geocaching.com date format: dd MMM yy
- BRouter connection available: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (64,9 GB free) v1 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (64,9 GB free) v1 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (64,9 GB free) v1 external non-removable isDir(238 entries)
- Public Folders: #9
- BASE: /cgeo (User-defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::], default: /storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Available:true, Files: 56, subdirs:13, free space: 64,9 GB, files on device: 13278715)
- OFFLINE_MAPS: ‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‎‏‏‎‏‏‎‎‎‏‏‏‏‎‏‏‎‎‎‎‎‏‎‎‏‏‎‎‎‎‏‏‏‏‎‏‎‎‎‏‏‏‎‎‏‏‏‎‏‎‏‎‎‏‎‎‏‏‎‎‏‎SD card‎‏‎‎‏‎/Locus/mapsVector (User-defined)[‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‎‏‏‎‏‏‎‎‎‏‏‏‏‎‏‏‎‎‎‎‎‏‎‎‏‏‎‎‎‎‏‏‏‏‎‏‎‎‎‏‏‏‎‎‏‏‏‎‏‎‏‎‎‏‎‎‏‏‎‎‏‎SD card‎‏‎‎‏‎/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector::], default: /cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector/document/0123-4567%3ALocus%2FmapsVector, Available:true, Files: 1234, subdirs:9, free space: 156,2 GB, files on device: 0)
- OFFLINE_MAP_THEMES: ‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‎‏‏‎‏‏‎‎‎‏‏‏‏‎‏‏‎‎‎‎‎‏‎‎‏‏‎‎‎‎‏‏‏‏‎‏‎‎‎‏‏‏‎‎‏‏‏‎‏‎‏‎‎‏‎‎‏‏‎‎‏‎SD card‎‏‎‎‏‎/Locus/mapsVector/_themes (User-defined)[‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‎‏‏‎‏‏‎‎‎‏‏‏‏‎‏‏‎‎‎‎‎‏‎‎‏‏‎‎‎‎‏‏‏‏‎‏‎‎‎‏‏‏‎‎‏‏‏‎‏‎‏‎‎‏‎‎‏‏‎‎‏‎SD card‎‏‎‎‏‎/Locus/mapsVector/_themes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes::], default: /cgeo/themes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/themes]] (Uri: content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes/document/0123-4567%3ALocus%2FmapsVector%2F_themes, Available:true, Files: 1215, subdirs:8, free space: 156,2 GB, files on device: 0)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Available:true, Files: 1, subdirs:0, free space: 64,9 GB, files on device: 13278715)
- GPX: /Download (User-defined)[/Download[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADownload::], default: /cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload, Available:true, Files: 88, subdirs:10, free space: 64,9 GB, files on device: 13278715)
- BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Available:true, Files: 25, subdirs:8, free space: 64,9 GB, files on device: 13278715)
- FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Available:true, Files: 28, subdirs:0, free space: 64,9 GB, files on device: 13278715)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Available:true, Files: 0, subdirs:0, free space: 64,9 GB, files on device: 13278715)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest], default: (same)] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Available:true, Files: 0, subdirs:0, free space: 64,9 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #4
- content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector%2F_themes (24 Feb, 16:29):RW
- content://com.android.externalstorage.documents/tree/primary%3ADownload (7 Feb, 14:47):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (7 Feb, 14:44):RW
- content://com.android.externalstorage.documents/tree/0123-4567%3ALocus%2FmapsVector (7 Feb, 14:46):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:322,6 MB) on system internal storage
 -Settings: v5, Count:225
--- End of system information ---
```

**Additional context:**
Tried with different themes folders (like e. g. ``...\_themes``, ``...\_themes\Elevate`` and ``...\_themes\Elevate\Elevate4``), but to no avail.

### LINKED ISSUE #10080: Theme options not working for zipped themes
While testing the map theme migration on other devices I stumbled upon another (maybe unrelated?) problem:
- Google Pixel 3a, Android 11, 2021.02.27-NB
- Migration of all folders completed
- Offline map and themes working normal
- Selected OpenAndroMaps Elevate theme
- Open map 
- Select Menu - Theme Options

Result:
The theme options screen is empty:
Screenshot_20210227-114620

On my other Android 11 device (Samsung S20) its working normal.
Debug log shows nothing related. 
Seems not to depend on the theme. When selecting another theme (e.g. Lightning from OpenAndroMaps) the screen is also empty

```
--- System information ---
c:geo version: 2021.02.27-NB-912ec0c

Device:
-------
- Device type: Pixel 3a (sargo, google)
- Android version: 11
- Android build: RQ1A.210205.004
- Sailfish OS detected: false
- Google Play services: enabled - 21.02.14 (150400-352619232)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: -
- Hide waypoints: -
- Set language: en_US (system default)
- System date format: M/d/yy
- Debug mode active: yes
- Live map mode: true
- Global filter: display all caches
- Last backup: Feb 16, 8:31 PM
- Routing mode: Walk

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
- Geocaching.com date format: MM/dd/yyyy
- BRouter connection available: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (38.5 GB free) v1 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (38.5 GB free) v1 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (38.5 GB free) v1 external non-removable isDir(15 entries)
- Public Folders: #9
- BASE: /cgeo (User-defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::], default: /storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Available:true, Files: 244, subdirs:10, free space: 38.5 GB, files on device: 12777472)
- OFFLINE_MAPS: /offlinemap (User-defined)[/offlinemap[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Aofflinemap::], default: /cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Aofflinemap/document/primary%3Aofflinemap, Available:true, Files: 120, subdirs:2, free space: 38.5 GB, files on device: 12777472)
- OFFLINE_MAP_THEMES: /cgeo/themes (Default)[/cgeo/themes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/themes], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fthemes, Available:true, Files: 230, subdirs:1, free space: 38.5 GB, files on device: 12777472)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Available:true, Files: 7, subdirs:0, free space: 38.5 GB, files on device: 12777472)
- GPX: /cgeo/gpx (User-defined)[/cgeo/gpx[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx::], default: /cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx/document/primary%3Acgeo%2Fgpx, Available:true, Files: 3, subdirs:0, free space: 38.5 GB, files on device: 12777472)
- BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Available:true, Files: 4, subdirs:2, free space: 38.5 GB, files on device: 12777472)
- FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Available:true, Files: 0, subdirs:0, free space: 38.5 GB, files on device: 12777472)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Available:true, Files: 0, subdirs:0, free space: 38.5 GB, files on device: 12777472)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest], default: (same)] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Available:true, Files: 0, subdirs:0, free space: 38.5 GB, files on device: -1)
- Map render theme path: Elevate.zip:Elevate.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
- content://com.android.externalstorage.documents/tree/primary%3Aofflinemap (Feb 27, 11:30 AM):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (Feb 27, 11:29 AM):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx (Feb 27, 11:30 AM):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:536.0 KB) on system internal storage
 -Settings: v5, Count:105
--- End of system information ---
```

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #10070: synchronize map theme folder in background

Synchronization of Map Themes is now done in the background, but still uses the same trigger points as before (on c:geo startup, on map theme folder change and after map theme download).

Instead of original GUI, user is informed via toast about map theme sync:

image

image

This PR also includes LocalizationUtils for localization methods useful when not having an activity around (so one does not have to deal with CGeoApplication).

It also fixes #10080, because this was just a parameter to add.

### CODE REVIEW

**Comment by moving-bits** [comment]
Do we really need two toasts for it? IMHO a short notification on starting the sync process "Synchronizing map themes in background..." (or similar) would be enough.

**Comment by eddiemuc** [comment]
Hm, If I had to decide for just one toast I would rather take the "finished" toast and leave the "start" toast out. Would that be fine too?

**Comment by moving-bits** [comment]
Why does the user needs to be notified about this internal process at all? - As a warning? As a signal that something is accessible now? As a signal that something has changed?

I guess it depends on what impacts syncing has (e. g. performance, access to certain folders etc.). If the user needs to be warned about something, the message should be before syncing. If there is some info that something new is available, this could justify a message after syncing.

So a possible solution could be (to have minimal impact):
If there is no negative impact of syncing (no "warning" needed) then show a toast after successful sync, but only if something has changed (removed or added themes).

**Comment by eddiemuc** [comment]
Sounds plausible, will implement it like this

**Comment by eddiemuc** [comment]
Ok, done

**Comment by moving-bits** [comment]
Wow, this was fast! Thanks 👍

**Pull request merged**
