### PR TITLE
raise wp limit to 200 (fix #6810)

### LINKED ISSUE #6810: Allow higher limit of waypoints shown on map
##### Detailed steps causing the problem:
In the "Settings" menue, sub menue "Map", parameter "Show Waypoints": Actual limit is 50.
When using a large high resolution screen, e.g. on a 10 inch tablet, a higher limit would be needed. Suggestion: limit of 200, pre setting after installation should be 40.

##### Actual behavior after performing these steps:
Difficult to get a good overview about an area and a possible walking path if a number of final location have already been entered: If the zoom level fits for the area, the finals are no longer shown.

##### Expected behavior after performing these steps:
Just a better ovrview.

##### Version of c:geo used:
2017.10.23

##### Is the problem reproducible for you?
Yes, it's not a bug, it's a nice feature

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

### PR DESCRIPTION
**Pull request by moving-bits**
raised max value for waypoints to 200 / default unchanged

### CODE REVIEW

**Comment by Lineflyer** [comment]
ok to test

**Comment by Lineflyer** [comment]
@rsudev Do you recall, if there was any technical reason for the upper limit of 50 WPs?

**Comment by moving-bits** [comment]
did a rebase with merge conflict resolution

**Comment by moving-bits** [comment]
rebased to today's (Feb 23) master

**Pull request merged**
