### PR TITLE
fixes #6181 history not working reliably

### LINKED ISSUE #6181: History not working reliably
This is more or less a reminder to myself (and others who would like to test):

Some user reports for the current RC version (2016.11.28-RC) tell, that there are problems in the history:
- Offline logged caches not visible
- History cannot be emptied
- History is emptied but cache count in title bar still shows x caches on list

I cannot reproduce any of them right now, but as we had a change in this area I think there might be some leftover bug under special conditions.

I will try to gather more information from users and try to test some things myself.

### PR DESCRIPTION
**Pull request by pstorch**
- fix History count
- fix online Logs not visible in History
- fix "clearOfflineLogs" cleared also all visited

### CODE REVIEW

**Comment by pstorch** [comment]
@Lineflyer now it's for `release` branch

**Comment by pstorch** [comment]
Maybe this also fixes #6167

**Comment by pstorch** [comment]
I guess the failing tests are because of the Map changes.

**Comment by Lineflyer** [comment]
Yes, the failing tests are there since I merged the icon decoder changes. Adaption of tests is still a ToDo.
Feel free to merge if you want me to test.

**Comment by pstorch** [comment]
OK, merged.

**Pull request merged**
