### PR TITLE
Activate chinese traditional for the contacts plugin

### PR DESCRIPTION
**Pull request by bekuno**
part "enable the language" for #8878

the apk looks fine:
grafik

### CODE REVIEW

**Comment by bekuno** [comment]
@moving-bits 
Please test the apk with an AVD. Thanks.

**Comment by moving-bits** [comment]
@bekuno 
Sorry, I'm a bit lost with the contacts plugin - never have used it so far.

> Please test the apk with an AVD. Thanks.

How can I install a pre-built APK?

APK provided by this build is 10 MB - this looks like the regular c:geo APK to me.

I've installed the contacts plugin from Play Store now, and build c:geo after merging this PR locally. But I do not see any translated string. - This may be due to not having selected the right locale, see https://github.com/cgeo/cgeo/pull/8875#issuecomment-679320657 and me not knowing which locale to choose after selecting the last entry (for Chinese traditional) in Android system language dialog.

AS cannot build the contact plugin locally yet on my machine, stating "Default Activity not found" if I select "cgeo-contacts" as build target.

**Comment by bekuno** [comment]
@moving-bits 
I forgot that the PR CI job does not generate the contacts apk.
My AS build configuration cgeo-contacts works well. So I test normally there.
Please check your config: tab: General, Launch: Nothing
If this does not help then write me a mail.

In CI is a job for contacts:
https://ci.cgeo.org/view/All%20jobs/job/cgeo-contacts%20release/
After merging this PR I started them. So you can use the apk from there.
(https://ci.cgeo.org/view/All%20jobs/job/cgeo-contacts%20release/23/artifact/cgeo-contacts/build/outputs/apk/release/cgeo-contacts-release.apk)

c:geo is not translated into zh-rTW, only the contacts addin.

**Comment by moving-bits** [comment]
Thanks for providing the APK download link. APK seems to work, at least the error toast for a non-existing contact now is in Chinese, whereas with the release version it has been in English:

image

**Pull request merged**
