### PR TITLE
update cached viewport on reload (fix #9354)

### LINKED ISSUE #9354: Live Map Cache Refreshs may trigger HTTP 429 "Too many requests" for geocaching.com
When using Live Map (OSM, Offline or GoogleMap) while quickly moving in a low-zoom map (=when moving more than or close to 1/4 of the viewport per second), then frequently issued viewport cache searchs may trigger HTTP 429 ("Too many requests") for GC.com. This results both in a not updated map and may also lead to blockage by server over time.

Reproduce as follows:
* Open c:geo, select Live Map
* Choose a zoom level not too broad (such that it is possible to move 1/4 of the viewport per second)
* Use some tool to simulate driving along some route (e.g. using an Autobahn from Munich to Frankfurt using Emulator and replaying at 5x the speed. Maybe same can be acomplished with apps like Lockito?)
* Wait a while
* At some point you will no longer see refreshed Geocaching-caches). Check logcat for HTTP429 errors

Places to fix
* For OSM/Offline: cgeo.geocaching.maps.mapsforge.v6.caches.LiveCachesOverlay.LoadTimerAction
* For GoogleMaps: cgeo.geocaching.maps.CgeoMap.LoadTimerAction

A typical exception in the log when problem happens:
```
2020-11-06 14:56:43.009 30829-31052/cgeo.geocaching D/cgeo: [network--10] GCMap.searchPlayMapByViewport(N 48° 27,316' · E 011° 34,438',N 48° 29,056' · E 011° 35,955') {GCMap.searchPlayMapByViewport:125/GCMap.searchByViewport:105/GCConnector.searchByViewport:261/ConnectorFactory.lambda$searchByViewport$0:346/-$$Lambda$ConnectorFactory$xlYIDnOeDkjd0u5VT0oIRtPq6Zk.apply:4/SearchResult.lambda$null$0:327/-$$Lambda$SearchResult$S4Ub23vsnqWr5X8nr-1svPn50lg.call:4/MaybeFromCallable.subscribeActual:47/Maybe.subscribe:5317/MaybeSubscribeOn$SubscribeTask.run:54}
2020-11-06 14:56:43.013 30829-31626/cgeo.geocaching D/cgeo: [OkHttp] GET https://www.geocaching.com/api/proxy/web/search?box=48.484266%2C11.573968%2C48.455274%2C11.599252&take=500&asc=true&skip=0&sort=distance&origin=48.46977%2C11.58661&app=cgeo {Network$LoggingInterceptor.intercept:358/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.029 30829-30898/cgeo.geocaching D/cgeo: [OkHttp] GET https://geocaching.su/api/list.php?maxlat=48.484266&maxlng=11.599252&minlat=48.455274&minlng=11.573968&oauth_consumer_key=b32876bd62c0b0841005cf6e4e6f38e10583547c7&oauth_nonce=825fbd1c7db71f960df501658faaa2fa&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1604671003&oauth_token=03ffe9c2134584b3a82413e4863c8f1505f6d8b55&oauth_version=1.0&oauth_signature=qbxEHhbdNfgDYROfa1KUR0EWu5g%3D {Network$LoggingInterceptor.intercept:358/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.031 30829-31624/cgeo.geocaching D/cgeo: [OkHttp] GET https://www.opencaching.de/okapi/services/caches/shortcuts/search_and_retrieve?langpref=de%7Cen&oauth_consumer_key=q7HSGzELA2hjEvCVLh4W&oauth_nonce=7047c01782c2b963e52027d4082b5c23&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1604671003&oauth_token=6RQeTdgpY8QjsQmDyZSQ&oauth_version=1.0&retr_method=services%2Fcaches%2Fgeocaches&retr_params=%7B%22fields%22%3A%20%22code%7Cname%7Clocation%7Ctype%7Cstatus%7Cdifficulty%7Cterrain%7Csize%7Csize2%7Cdate_hidden%7Ctrackables_count%7Cis_found%22%7D&search_method=services%2Fcaches%2Fsearch%2Fbbox&search_params=%7B%22bbox%22%3A%2248.455274%7C11.573968%7C48.484266%7C11.599252%22%2C%22status%22%3A%22Available%7CTemporarily%20unavailable%22%2C%22ignored_status%22%3A%22notignored_only%22%7D&wrap=true&oauth_signature=yVl%2BHUsXtbDEaq10r8gbtN%2BInSM%3D {Network$LoggingInterceptor.intercept:358/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.105 30829-31624/cgeo.geocaching D/cgeo: [OkHttp] 200 (74 ms) GET https://www.opencaching.de/okapi/services/caches/shortcuts/search_and_retrieve?langpref=de%7Cen&oauth_consumer_key=q7HSGzELA2hjEvCVLh4W&oauth_nonce=7047c01782c2b963e52027d4082b5c23&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1604671003&oauth_token=6RQeTdgpY8QjsQmDyZSQ&oauth_version=1.0&retr_method=services%2Fcaches%2Fgeocaches&retr_params=%7B%22fields%22%3A%20%22code%7Cname%7Clocation%7Ctype%7Cstatus%7Cdifficulty%7Cterrain%7Csize%7Csize2%7Cdate_hidden%7Ctrackables_count%7Cis_found%22%7D&search_method=services%2Fcaches%2Fsearch%2Fbbox&search_params=%7B%22bbox%22%3A%2248.455274%7C11.573968%7C48.484266%7C11.599252%22%2C%22status%22%3A%22Available%7CTemporarily%20unavailable%22%2C%22ignored_status%22%3A%22notignored_only%22%7D&wrap=true&oauth_signature=yVl%2BHUsXtbDEaq10r8gbtN%2BInSM%3D (http/1.1) {Network$LoggingInterceptor.intercept:366/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.107 30829-30892/cgeo.geocaching D/cgeo: [network--4] OC returning 0 caches from search by viewport {OCApiLiveConnector.searchByViewport:65/ConnectorFactory.lambda$searchByViewport$0:346/-$$Lambda$ConnectorFactory$xlYIDnOeDkjd0u5VT0oIRtPq6Zk.apply:4/SearchResult.lambda$null$0:327/-$$Lambda$SearchResult$S4Ub23vsnqWr5X8nr-1svPn50lg.call:4/MaybeFromCallable.subscribeActual:47/Maybe.subscribe:5317/MaybeSubscribeOn$SubscribeTask.run:54/ScheduledDirectTask.call:41/ScheduledDirectTask.call:28}
2020-11-06 14:56:43.152 30829-30898/cgeo.geocaching D/cgeo: [OkHttp] 200 (122 ms) GET https://geocaching.su/api/list.php?maxlat=48.484266&maxlng=11.599252&minlat=48.455274&minlng=11.573968&oauth_consumer_key=b32876bd62c0b0841005cf6e4e6f38e10583547c7&oauth_nonce=825fbd1c7db71f960df501658faaa2fa&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1604671003&oauth_token=03ffe9c2134584b3a82413e4863c8f1505f6d8b55&oauth_version=1.0&oauth_signature=qbxEHhbdNfgDYROfa1KUR0EWu5g%3D (h2) {Network$LoggingInterceptor.intercept:366/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.608 30829-31626/cgeo.geocaching D/cgeo: [OkHttp] 429 [] (594 ms) GET https://www.geocaching.com/api/proxy/web/search?box=48.484266%2C11.573968%2C48.455274%2C11.599252&take=500&asc=true&skip=0&sort=distance&origin=48.46977%2C11.58661&app=cgeo (http/1.1) {Network$LoggingInterceptor.intercept:368/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.609 30829-31052/cgeo.geocaching W/cgeo: [network--10] parallelCombineActive: swallowing error from connector cgeo.geocaching.connector.gc.GCConnector@f55cfdd {SearchResult.lambda$null$0:329/-$$Lambda$SearchResult$S4Ub23vsnqWr5X8nr-1svPn50lg.call:4/MaybeFromCallable.subscribeActual:47/Maybe.subscribe:5317/MaybeSubscribeOn$SubscribeTask.run:54/ScheduledDirectTask.call:41/ScheduledDirectTask.call:28/FutureTask.run:266/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
    java.lang.RuntimeException: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=429, message=, url=https://www.geocaching.com/api/proxy/web/search?box=48.484266%2C11.573968%2C48.455274%2C11.599252&take=500&asc=true&skip=0&sort=distance&origin=48.46977%2C11.58661&app=cgeo}
        at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
        at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
        at cgeo.geocaching.connector.gc.GCWebAPI.searchMap(GCWebAPI.java:414)
        at cgeo.geocaching.connector.gc.GCMap.searchPlayMapByViewport(GCMap.java:133)
        at cgeo.geocaching.connector.gc.GCMap.searchByViewport(GCMap.java:105)
        at cgeo.geocaching.connector.gc.GCConnector.searchByViewport(GCConnector.java:261)
        at cgeo.geocaching.connector.ConnectorFactory.lambda$searchByViewport$0(ConnectorFactory.java:346)
        at cgeo.geocaching.connector.-$$Lambda$ConnectorFactory$xlYIDnOeDkjd0u5VT0oIRtPq6Zk.apply(Unknown Source:4)
        at cgeo.geocaching.SearchResult.lambda$null$0(SearchResult.java:327)
        at cgeo.geocaching.-$$Lambda$SearchResult$S4Ub23vsnqWr5X8nr-1svPn50lg.call(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
        at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5317)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:41)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=429, message=, url=https://www.geocaching.com/api/proxy/web/search?box=48.484266%2C11.573968%2C48.455274%2C11.599252&take=500&asc=true&skip=0&sort=distance&origin=48.46977%2C11.58661&app=cgeo}
        at cgeo.geocaching.network.Network.lambda$static$6(Network.java:621)
        at cgeo.geocaching.network.-$$Lambda$Network$S1n6XPPgWcknnAjXJlYG-giT7W4.apply(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)
        at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
        at cgeo.geocaching.utils.RxOkHttpUtils$1.onResponse(RxOkHttpUtils.java:48)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2020-11-06 14:56:43.610 30829-31082/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-3] Filtering out 0 caches: [] {LiveCachesOverlay.download:115/LiveCachesOverlay.access$100:28/LiveCachesOverlay$LoadTimerAction.run:85/Scheduler$PeriodicDirectTask.run:566/Scheduler$Worker$PeriodicTask.run:513/ScheduledRunnable.run:65/ScheduledRunnable.call:56/FutureTask.run:266/ScheduledThreadPoolExecutor$ScheduledFutureTask.run:301/ThreadPoolExecutor.runWorker:1167}
```

Note: this issue as created after discussion in #8682

### PR DESCRIPTION
**Pull request by moving-bits**

### CODE REVIEW

**Comment by moving-bits** [comment]
@Lineflyer 
If you find the time: Can you cross-check your scenario if this build leads to less requests to the server?
(It's built against release currenlty, but I can build against master as well, if your prefer.)

**Comment by Lineflyer** [comment]
Will do

**Comment by Lineflyer** [comment]
Looks promising:
Tested on OSM online map
North to south track, 500m/unit zoom

Loading/caching looks like this, which is was I expected:
```
12:06:11.152 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=false, results=147, viewport=(N 51° 15,527' · E 007° 00,454',N 51° 20,906' · E 007° 05,813')
12:06:45.482 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=147, viewport=(N 51° 15,527' · E 007° 00,454',N 51° 20,906' · E 007° 05,813')
12:07:21.336 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=147, viewport=(N 51° 15,527' · E 007° 00,454',N 51° 20,906' · E 007° 05,813')
12:07:57.411 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=147, viewport=(N 51° 15,527' · E 007° 00,454',N 51° 20,906' · E 007° 05,813')
12:08:35.367 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=false, results=145, viewport=(N 51° 13,741' · E 007° 00,643',N 51° 19,072' · E 007° 06,108')
12:09:09.416 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=145, viewport=(N 51° 13,741' · E 007° 00,643',N 51° 19,072' · E 007° 06,108')
12:09:45.322 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=145, viewport=(N 51° 13,741' · E 007° 00,643',N 51° 19,072' · E 007° 06,108')
12:10:21.353 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=145, viewport=(N 51° 13,741' · E 007° 00,643',N 51° 19,072' · E 007° 06,108')
12:11:00.227 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=false, results=157, viewport=(N 51° 11,900' · E 007° 00,842',N 51° 17,263' · E 007° 06,382')
12:11:35.417 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=157, viewport=(N 51° 11,900' · E 007° 00,842',N 51° 17,263' · E 007° 06,382')
12:12:12.430 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=157, viewport=(N 51° 11,900' · E 007° 00,842',N 51° 17,263' · E 007° 06,382')
12:12:48.337 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=157, viewport=(N 51° 11,900' · E 007° 00,842',N 51° 17,263' · E 007° 06,382')
12:13:26.542 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=false, results=219, viewport=(N 51° 10,077' · E 007° 01,087',N 51° 15,391' · E 007° 06,620')
12:14:00.327 Debug cgeo 14329  [RxNewThreadScheduler-6] searchByViewport: cached=true, results=219, viewport=(N 51° 10,077' · E 007° 01,087',N 51° 15,391' · E 007° 06,620')
```

Caches are visible and loading from server seems minimized to the needed level

Will retest this scenario with release version to verify the difference.

**Comment by Lineflyer** [comment]
Negative test with 2020.11.03 (GMaps used as OSM has another - already fixed - problem in this version):
```
12:28:19.717 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=45, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:28:38.195 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=49, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:28:56.242 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=49, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:29:14.385 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=49, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:29:32.557 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=47, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:29:51.100 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=42, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:30:09.553 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=39, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:30:28.805 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=33, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:30:46.495 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=30, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:31:05.505 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=32, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
12:31:23.069 Debug cgeo 8045  [pool-6-thread-1] searchByViewport: cached=false, results=30, viewport=(N 51° 20,085' · E 007° 02,383',N 51° 21,268' · E 007° 03,470')
```

@moving-bits 
The fix looks really promising.
IMHO `master` is sufficient as the "map empty" fix is also only on `master`.

**Comment by moving-bits** [comment]
@Lineflyer Thanks for cross-checking. I've retargeted the PR to master and will merge it after successful completion of tests.

**Pull request merged**
