### PR TITLE
Issues/slow start theme 10406

### PR DESCRIPTION
**Pull request by eddiemuc**
related to #10406: aborts xml map theme scan after 2 seconds

### CODE REVIEW

**Comment by Lineflyer** [comment]
Thanks @eddiemuc 

1. Any estimation how many files/dirs a typical device will return in those two seconds? It seems kind of a fast timeout?
2. Will themes not found in these two seconds be unavailable on the map or is there another scan when starting the map?

**Comment by eddiemuc** [comment]
My assumption was that you wanted a quick fix to get out in production before weekend. Since no beta test is available it has to be a small change. This is why I introduced the time limit.

I can increase it easily e.g. to 5 or 10 seconds. What is the time limit triggering an ANR?

A better solution would of course be to put the scan to the background as @moving-bits suggests. But this is a bit more complicated to achieve (e.g. what happens if user opens map viewer before scan is finished - which can easily happen if it takes >5 seconds) and I may not have the time during the week to do this. Would You rather prefer to wait for a "better" fix then?

**Comment by eddiemuc** [comment]
Time limit increased to 5 seconds

**Comment by Lineflyer** [comment]
@moving-bits Are you OK with merging this as a first workaround? So we could push an update rather soon and have time afterwards to find a more suitable solution.

**Comment by moving-bits** [comment]
> @moving-bits Are you OK with merging this as a first workaround? So we could push an update rather soon and have time afterwards to find a more suitable solution.

Sure. Haven't had the time to check the technical details of the PR, but the approach itself (limiting the time) sounds pretty reasonable as a workaround.

**Pull request merged**
