### PR TITLE
Possibility to vote on opencaching (OCPL) caches during visit logging

### LINKED ISSUE #3787: Support cache voting on OC.pl
From support mail:

OC.pl supports rating a cache via vote while logging it.
In c:geo I can not vote for a cache when logging it.

### PR DESCRIPTION
**Pull request by mzylowski**
## Description
Introduce support for rating caches during logging visits for opencaching services (only those that bases on OCPL - there is no support for ratings in OCDE code) - see `rating` field description in https://opencaching.pl/okapi/services/logs/submit.html 

## Related issues
Fixes #3787

## Additional context
My change implements `IVotingCapability` interface for `OCApiLiveConnector` class, but my biggest concern is about `postVote` implementation. There is no any particular endpoint in OKAPI that I can call to set rating. I mean I can - because I can edit entry that I already sent (https://www.opencaching.de/okapi/services/logs/edit.html) but I see no reason to do it. For OKAPI rating can be posted together with rest of the log entry, so I see no reason to perform another api call only to be compliant with this intereface. Also current header of `postVote(@NonNull Geocache cache, float rating)` does not encourage to do this next api call because I need there also additional argument for log id used only for opencaching. So instead of this I just added a new argument to `postLog` method.

### CODE REVIEW

**Comment by bekuno** [comment]
ok to test

**Comment by mzylowski** [comment]
I see codacy reports issues around numer of parameters in postLog method. I'm thinking how I should mitigate them.. Or maybe I should implement this postVote method by calling edit log okapi endpoint?
I'm looking for strong opinion of lead c:geo developers :)
Maybe @Lineflyer @eddiemuc as reviewer of my previos PR related to recommendations?

**Comment by eddiemuc** [comment]
> I see codacy reports issues around numer of parameters in postLog method. I'm thinking how I should mitigate them.. Or maybe I should implement this postVote method by calling edit log okapi endpoint?
> I'm looking for strong opinion of lead c:geo developers :)
> Maybe @Lineflyer @eddiemuc as reviewer of my previos PR related to recommendations? 

I would argue that in these specific cases it is safe to suppress these warnings using SuppressWarning annotation .

There are many instances in code where npath warning is suppressed, just search the codebase for example. For long parameter list I don't know the rule name, you probably have to Google it.

**Comment by bekuno** [comment]
> For long parameter list I don't know the rule name, you probably have to Google it.

This is a PMD rule: ExcessiveParameterList.
You should be able to follow the link in the PR codacy results page, where you have a link to https://app.codacy.com/gh/cgeo/cgeo/pullRequest?prid=11964670&bid=35969760.

I vote also to suppress the check here. The syntax would be the same as for NPathComplexity.

**Comment by bekuno** [comment]
The CI errors are based on the captcha problem.
Often you have to wait some time and then try a next time.

retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by mzylowski** [comment]
So my PR is all green from few days, can I get some review or merge? :)

@bekuno @eddiemuc @moving-bits

**Review by eddiemuc — APPROVED** [review]
LGTM, thans for the contribution

**Pull request merged**
