### PR TITLE
extend cache popup's hint view by personal note

### PR DESCRIPTION
**Pull request by moving-bits**
When pressing the cache popup's hint button: Do show the personal note as well (if given), not just the hint.

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by okainov** [comment]
Not tested yet but have you checked the case when personal note is big (I.e. like 1-2 full description screens)?

**Comment by moving-bits** [comment]
The view is scrollable.

**Comment by moving-bits** [comment]
Retest this please

**Comment by SammysHP** [comment]
I wonder if we still need the popup as more and more information is integrated in it…

**Comment by Lineflyer** [comment]
> I wonder if we still need the popup as more and more information is integrated in it…

Well yes, its still a quick possibility to get info while staying on the map (and of course its useful for unsaved caches to get basic information)

**Pull request merged**
