### PR TITLE
move several config items from system to offline data preference screen

### LINKED ISSUE #7712: Move offline data settings from "System" to "Offline Data" sub menu
For whatever reason we collected a lot of settings into the "System" menu, which do not really belong there.

IMHO the title "System" indicates, that these are settings only needed in special cases, however it contains also the setting for location of geocache data directory which is a normal setting for data handling.

I propose to move this setting to the sub menu Offline Data instead.

### PR DESCRIPTION
**Pull request by moving-bits**
Moved the following config items from system to offline data preference screen: (fix #7712)
- GPX Export Directory
- GPX Import Directory
- Database location
- Geocache data directory
- Maintenance: Delete orphaned files

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
I will merge this a bit later - not due to the severity of the functional change, but to allow one more release until users manual, etc. needs to be adapted.

**Comment by Lineflyer** [comment]
@moving-bits Feel free to merge yourself (after resolving conflicts) :)

**Pull request merged**
