### PR TITLE
rel to #2012: enhance gc.com log api to allow edit/delete for logs/images

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #2012: enhance gc.com log api to allow edit/delete for logs/images

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR includes a roundtrip log/logimage creation/editing/deletion test. Let's see whether this works on CI as well...

**Comment by eddiemuc** [comment]
As claimed before: this PR introduces methods to add, edit and delete cache logs, cache log images and trackable logs (only create/delete for now) against gc.com using the new log API.

It also introduces tests for this:
* one test which creates a test cache log, modifies it in several ways (including image upload) then deletes it afterwards
* one test which creates a trackable log and deletes it afterwards

This has some side-effects:
* Test takes rather long (about 30-40 seconds local)
* Since the test creates real logs against one of my own caches and trackables (and deletes them afterwards) I will receive emails from gc.com, including the user used for the test. Is this o with the team?

**Comment by eddiemuc** [comment]
Update:test creates only logs of type "Note" of course (no "Found"/"DNF" logs or something like it)

**Comment by fm-sys** [comment]
You may want to consider creating an unpublished cache (not yet submitted to review) from a fake GC account or use a cache which is already archived.

I don't have a problem with it, even the other way around: I think it's a good thing that the log API is finally unit tested. However, I'm not sure if GC is fine with that. It would be bad if @mucek4's personal GC account gets blocked cause of suspicious behavior.

**Comment by eddiemuc** [comment]
> You may want to consider creating an unpublished cache (not yet submitted to review) from a fake GC account or use a cache which is already archived.

I don't own any archived caches. This would also not solve the problem with trackables.

As for unpublishes caches: I discovered recently that it is no longer allowed to publish write notes for unpublishes caches. Also, no one except the "owner" could see and log to such a cache.

> I don't have a problem with it, even the other way around: I think it's a good thing that the log API is finally unit tested. However, I'm not sure if GC is fine with that. It would be bad if @mucek4's personal GC account gets blocked cause of suspicious behavior.

Good thought, haven't considered that. Wouldn't it be better in general to use a fake account for CI?

**Comment by fm-sys** [comment]
However, you may want to consider our `NotForIntegrationTests` annotation. Then the test will only get executed once a day (watchdog tests) but not for PR builds. This would avoid mail spamming and speeds up PR builds.

**Comment by eddiemuc** [comment]
> However, another thought: You may want to consider our `NotForIntegrationTests` annotation. Then the test will only get executed once a day (watchdog tests) but not for PR builds. This would avoid mail spamming and speeds up PR builds.
> 

Watchdog test seems to execute only the tests in `WatchdogTest.java`. There is one other test marked with `@NotForIntegrationTests` which is not executed by the watchdog.

We have another job `cgeo nightly` which seems not to execute tests at all. Not sure what is the meaning of this.

**Comment by eddiemuc** [comment]
> > Wouldn't it be better in general to use a fake account for CI?
> 
> Probably yes... Although it would cost us some extra money for an additional premium account.

40€ a year seems neglectable

**Comment by eddiemuc** [comment]
Update:  added `NotForIntegrationTests` annotation. 
This de facto stops CI from executing the tests and thus makes them useless.
However, it allows ne to merge the PR and continue with implementing log editing

**Comment by eddiemuc** [comment]
Retest this please

**Pull request merged**
