### PR TITLE
create ZZ0 UDC in new list + with additional info

### PR DESCRIPTION
**Pull request by moving-bits**
Fixes parts of #8082:
- add some explanation about what UDC ZZ0 is
- store ZZ0 in a new user defined list

image

### CODE REVIEW

**Comment by moving-bits** [comment]
Missing to #8082 is either removing history target migration or using localized strings during migration - depending on whether someone finds a way to access localized strings during migration.

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/connector/internal/InternalConnector.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4854263&bid=16103910)

**Comment by Lineflyer** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
