### PR TITLE
Store fonts and developer shirt design

### PR DESCRIPTION
**Pull request by Lineflyer**
## Description

Store the following data in our repository:
- Fonts I have found in an archive which are either very similar or - in fact- the font we use for our logo
- Some developer shirt design graphics (still using the old logo though)

## Related issues

PR #10468

### CODE REVIEW

**Comment by bekuno** [comment]
Do we need the main/project/design/shirts/t-shirt - Kopie.svg ?

Do we use the ubuntu font(s) somewhere?

**Comment by Lineflyer** [comment]
> Do we need the main/project/design/shirts/t-shirt - Kopie.svg ?

Looks to me like the old front icon for the shirt?!

> Do we use the ubuntu font(s) somewhere?

I received those back in the days from @SammysHP.
Not sure if we use them?

**Comment by bekuno** [comment]
> > Do we need the main/project/design/shirts/t-shirt - Kopie.svg ?
> 
> Looks to me like the old front icon for the shirt?!

The name should be without " - kopie".

**Comment by Lineflyer** [comment]
> The name should be without " - kopie".

Corrected.

**Comment by moving-bits** [comment]
Should we wait for https://github.com/cgeo/cgeo/pull/10468#issuecomment-827321675 before merging this PR?

BTW: Would it be ok at all (wrt the license) to merge those fonts into a public repository (in contrast to just using them in our graphics, if granted)?
Or should be better store them in some team-internal repo?

**Comment by Lineflyer** [comment]
> BTW: Would it be ok at all (wrt the license) to merge those fonts into a public repository (in contrast to just using them in our graphics, if granted)?

The license is about using not storing.
You are right however as the whole repo is declared under a certain license which then does not apply to all its contents. But isn't it the same for things we use under CC-BY... licenses in contrast to our Apache license?

**Comment by moving-bits** [comment]
Maybe I've read too many of those "20 pages printed in 3 point font size" license agreements with their hair-splitting phrases... ;-)

From what I can decipher from the readme, the license is not very specific and only distinguishes between personal use ("use freely") and commercial use ("you may be charged for it"). So we are probably on the safe side.

**Comment by moving-bits** [comment]
anything open here (e. g. about the Ubuntu fonts), or can we merge?

**Pull request merged**
