### PR TITLE
fix pattern for GC.com log counts

### LINKED ISSUE #12667: geoApplicationTest -> testSearchByGeocodeBasis -> AssertionError: logcount of GC2CJPF - Expecting actual not to be null
### Describe your problem!

New at CI - are there changes on the GC website ?
~~~
cgeo.geocaching.CgeoApplicationTest > testSearchByGeocodeBasis[android-30(AVD) - 11] [31mFAILED [0m
	java.lang.AssertionError: [logcount of GC2CJPF for type FOUND_IT]
	Expecting actual not to be null
~~~

### How to reproduce?

see eg. https://ci.cgeo.org/job/cgeo-CI_PR-build/1185/console

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

CI tests

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ztNFny**
pattern on geocaching.com for log count section has changed

fixes #12667

### CODE REVIEW

**Comment by ztNFny** [comment]
No idea what's going wrong here. The test is OK on my local env.
Is there some cached version of the gc.com site with the old layout on the buildserver that's used in testParseCacheFromTextWithMockedData() ?

**Comment by eddiemuc** [comment]
@ztNFny the test failing is NOT the same test which failed originally. From a quick glance at the code, the test failing now uses Mocked cache data which is stored in our repository as test data. Maybe this stored test data needs to be adapted to the new pattern as well?

**Comment by ztNFny** [comment]
> @ztNFny the test failing is NOT the same test which failed originally.

I know. But it's still working in my local env. So it seems the buildserver is using different data than my local env is. Question is, where does the buildserver get that data from - apparently not from git, else I'd have the same issues locally.

**Comment by eddiemuc** [comment]
@ztNFny checking the code, the data used for the mocked cache comes from a file "GC2JVEH.html" (stored in folder `tests/src/cgeo/geocaching/test/mock`). Your PR does not include any change of this file, so my assumption would be that it still contains the "old" logcount html which does not fit to the "new" pattern.

Maybe you forgot to push this local change to the PR?

**Comment by eddiemuc** [comment]
image

**Comment by ztNFny** [comment]
I've updated the html now. But strangely with and without that update the test is successful in my local env ...

**Comment by eddiemuc** [comment]
The update wsa successfull. But sadly now the test fails with the next cache GC3FJ5F.html... I fear all the mock html files needs updating.

Also it is strange that this does not fail locally. Maybe the test does not find the mock files in the path locally and skips in this case?

**Comment by ztNFny** [comment]
The testcase seems to be broken. Looking at it's output it's full of errors:

```
--------- beginning of main
02-04 18:48:37.914 +0000 10161 15430 15452 W cgeo    : [Instr: androidx.test.runner.AndroidJUnitRunner] GCParser.parseCache: Failed to parse cache log count
02-04 18:48:38.124 +0000 10161 15430 15472 W cgeo    : [network--8] GCParser.parseLogsAndClose: status is error
02-04 18:48:38.145 +0000 10161 15430 15452 W cgeo    : [Instr: androidx.test.runner.AndroidJUnitRunner] GCParser.parseCache: Failed to parse cache log count
02-04 18:48:38.343 +0000 10161 15430 15474 W cgeo    : [network--10] GCParser.parseLogsAndClose: status is error
02-04 18:48:38.485 +0000 10161 15430 15452 W cgeo    : [Instr: androidx.test.runner.AndroidJUnitRunner] GCParser.parseCache: Failed to parse cache log count
02-04 18:48:38.758 +0000 10161 15430 15470 W cgeo    : [network--7] GCParser.parseLogsAndClose: status is error
02-04 18:48:38.817 +0000 10161 15430 15452 W cgeo    : [Instr: androidx.test.runner.AndroidJUnitRunner] GCParser.parseCache: Failed to parse cache log count
02-04 18:48:38.996 +0000 10161 15430 15464 W cgeo    : [network--3] GCParser.parseLogsAndClose: status is error
02-04 18:48:39.037 +0000 10161 15430 15452 W cgeo    : [Instr: androidx.test.runner.AndroidJUnitRunner] GCParser.parseCache: Failed to parse cache log count
02-04 18:48:39.372 +0000 10161 15430 15463 W cgeo    : [network--2] GCParser.parseLogsAndClose: status is error
02-04 18:48:39.573 +0000 10161 15430 15452 I cgeo.geocachin: Explicit concurrent copying GC freed 12190(759KB) AllocSpace objects, 30(1312KB) LOS objects, 49% free, 6011KB/11MB, paused 19us total 44.264ms
02-04 18:48:39.618 +0000 10161 15430 15452 I cgeo.geocachin: Explicit concurrent copying GC freed 1141(67KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 6096KB/11MB, paused 6.105ms total 41.207ms
02-04 18:48:39.618 +0000 10161 15430 15452 I TestRunner: finished: testParseCacheFromTextWithMockedData(cgeo.geocaching.connector.gc.GCParserTest)


```

But the test still passes:
image

**Comment by ztNFny** [comment]
I've updated the other html files - manually as I couldn't find any script to do that - is that correct?

**Comment by moving-bits** [comment]
@Lineflyer 
Would we need to publish this fix as a separate bugfix release on top of current release 2021.12.24, or do we plan to publish current state of `release` within the next, let's say, 7 days, and wait with this fix for it?

**Comment by ztNFny** [comment]
> @Lineflyer Would we need to publish this fix as a separate bugfix release on top of current release 2021.12.24, or do we plan to publish current state of `release` within the next, let's say, 7 days, and wait with this fix for it?

We should include https://github.com/cgeo/cgeo/pull/12671 in that bugfix release as withoutnit fieldnoted upload will break pretty soon.

**Comment by Lineflyer** [comment]
IMHO the feature loss is not that significant....so it could wait until bottom nav is ready to go.

But I am not 100% sure about whether more has changed.
Two reports about log posting with image being problematic....but did not try to reproduce yet.

**Comment by moving-bits** [comment]
> IMHO the feature loss is not that significant....so it could wait until bottom nav is ready to go.

Ok, then let's merge this PR to `release`.

> But I am not 100% sure about whether more has changed. Two reports about log posting with image being problematic....but did not try to reproduce yet.

I've created #12673 for it. Cannot send logs in the emulator at all, haven't retested with a physical device yet.

**Pull request merged**
