### PR TITLE
alc optimizations (2)

### PR DESCRIPTION
**Pull request by baiti**
as discussed.

### CODE REVIEW

**Comment by baiti** [comment]
something is rotten in denmark here. I worked "by the book" (wiki, git for beginners). I have done this now multiple times on "master" and after some initial hurdles it worked. I have now done 3 PRs targeting release and they ALL went like this. Of course I could now `git rebase -i HEAD~21` and delete everything except my one and only commit I made and then do a force push. Most likely it would even work but that an't be the solution. Here is what I did, please let me know what I should have done instead:

```
git switch release
git pull --rebase upstream release 
git push origin release
git switch -c alc_optimizations
```
... here I edited exactly 4 files
```
git status
git diff
git commit -a -m "alc optimizations"
git push -u origin alc_optimizations
```

**Comment by eddiemuc** [comment]
@baiti can't tell you exactly what happens here, but the one commit of mine in you list was merged to master only and is not meant to be on release.

My guess is that somehow your local release branch is mixed up with master (means: it somehow contains commits which on c:geo remote are not in master).

I would advise to "throw away" your local remote branch and "recreate" it with same content as c:geos release branch. But I don't know which git commands will do that.

**Comment by eddiemuc** [comment]
If my guess is correct (would be good if a real gut expert would comment, much like baiti I am often surprised and overwhelmed what chaos git causes in my system...), I found following page explaining how to delete and recreate a branch from remote:

https://stackoverflow.com/questions/9210446/how-to-replace-local-branch-with-remote-branch-entirely-in-git/61490618

In your case:
* Save your work somehow, it will get lost with the next steps
* git branch -D alc_optimizations (deletes the branch in your local repo!)
* git branch -D release 
* git fetch upstream release
* git checkout -b release upstream/release (recreates local branch release with exact same content as on c:geo repo)
* git push --force-with-lease (pushes your local release branch to your remote release branch)

After that, my guess is that you can create new branches starting from release and work with it as you do on master.

No guarantees though!

**Comment by baiti** [comment]
> @baiti can't tell you exactly what happens here, but the one commit of mine in you list was merged to master only and is not meant to be on release.
> 
> My guess is that somehow your local release branch is mixed up with master (means: it somehow contains commits which on c:geo remote are not in master).

Yes, that is the most likely scenario as the same happened on the three other PRs I wanted to base on release.

**Comment by baiti** [comment]
> If my guess is correct (would be good if a real gut expert would comment, much like baiti I am often surprised and overwhelmed what chaos git causes in my system...), I found following page explaining how to delete and recreate a branch from remote:
> 
> https://stackoverflow.com/questions/9210446/how-to-replace-local-branch-with-remote-branch-entirely-in-git/61490618
> 
> In your case:
> 
> * Save your work somehow, it will get lost with the next steps
> * git branch -D alc_optimizations (deletes the branch in your local repo!)
> * git branch -D release
> * git fetch upstream release
> * git checkout -b release upstream/release (recreates local branch release with exact same content as on c:geo repo)
> * git push --force-with-lease (pushes your local release branch to your remote release branch)
> 
> After that, my guess is that you can create new branches starting from release and work with it as you do on master.
> 
> No guarantees though!

Will check with @Lineflyer if perhaps the PR based on master will do. If that is the case then after the merge I will conduct the steps you described as I then won't have to save any local work. BTW: What happens to `origin alc_optimizations` in this picture? Doesn't have that to be deleted too? If yes, the delete would also close this PR inevitably ... which might actually be ok too.

**Comment by baiti** [comment]
@eddiemuc ... I'd guess the following indicates that it is now all in sync:

`8d63ddf3d (HEAD -> release, upstream/release, origin/release)`

I will now do a new PR on release to verify that it is indeed all ok now. @Lineflyer can then decide whether he merges the one based on master or the one based on release.

**Comment by moving-bits** [comment]
I can't help with the git magic involved here, but let me describe my approach to working with cgeo, which works pretty well for me:

- I have a local repo, an online fork of the cgeo repo (`origin`) and the original cgeo repo (`upstream`).
- Two things are most important for my work:
  - I'm completely ignoring the state of my fork!
     `master` and `release` of my fork are out-of-sync with `upstream` by a few thousand commits. - So what! 
    I'm using my fork only for preparing a PR, and as this goes to a new branch in my fork, the states of `master` and `release` of my fork are irrelevant.
  - My local repo is synched against `upstream`, and when working on a new thing, I update this sync, and then do a `git checkout release` or `git checkout master`, depending on what branch my work needs to be based upon.

This approach has saved me from a lot of hassles throughout the last two years.

I've a small script which syncs my local copy with `upstream`, which I call every day when I'm starting to work on something new. This makes sure I'm working on a current state and spares me a lot of possible merge conflicts.

**Comment by baiti** [comment]
> I can't help with the git magic involved here, but let me describe my approach to working with cgeo, which works pretty well for me:
> 
> * I have a local repo, an online fork of the cgeo repo (`origin`) and the original cgeo repo (`upstream`).
> * Two things are most important for my work:
>   
>   * I'm completely ignoring the state of my fork!
>     `master` and `release` of my fork are out-of-sync with `upstream` by a few thousand commits. - So what!
>     I'm using my fork only for preparing a PR, and as this goes to a new branch in my fork, the states of `master` and `release` of my fork are irrelevant.
>   * My local repo is synched against `upstream`, and when working on a new thing, I update this sync, and then do a `git checkout release` or `git checkout master`, depending on what branch my work needs to be based upon.
> 
> This approach has saved me from a lot of hassles throughout the last two years.
> 
> I've a small script which syncs my local copy with `upstream`, which I call every day when I'm starting to work on something new. This makes sure I'm working on a current state and spares me a lot of possible merge conflicts.

Thanks much for explaining. It seems I was already on a similar track, ignoring "diversions" on the fork and just focusing on upstream and local and dealing with the branches.

I believe the screwup was somewhere on my local repo where `release` was contaminated with commits from `master`. Next time, at the point where I am about to create the PR, will look closer at the bottom of that webpage where it will tell me what would go into the PR. Had I looked at this yesterday and the days before, I would have seen that it wanted to throw 21 commits into the PR (and changing 200+ files) while I wanted only 1 to go in. I could have just not created that PR and looked what went wrong on my local repo. Each and every day I learn to understand that beast better.

**Comment by eddiemuc** [comment]
> What happens to origin alc_optimizations in this picture? Doesn't have that to be deleted too?

Good catch, I guess it makes sense to delete that one too. This can be done via GitHub Web GUI.

**Comment by eddiemuc** [comment]
@Lineflyer it seems you use the remote names `origin` and `upstream` exactly the other way around as is recommended in out git beginner guide?

**Comment by moving-bits** [comment]
I guess I'm addressed here. I use `origin` for my fork of the original c:geo repo (https://github.com/moving-bits/cgeo), and `upstream` is the original c:geo repo (https://github.com/cgeo/cgeo).
For my local copy I'm using `upstream` only to fetch the current state (so download only), and `origin` only for pushing a new PR to my fork (so upload only).

**Comment by Lineflyer** [comment]
> @Lineflyer it seems you use the remote names origin and upstream exactly the other way around as is recommended in out git beginner guide?

Me. what makes you think it like this?
`origin` is my fork and `upstream` is the cgeo original repo.

@baiti 
Without having read all what you wrote in detail, I stumbled upon the fact, that you used `git pull --rebase upstream release `. I never use the `--rebase` option for that, it would only be required if I already applied my changes on that branch and forgot to pull in beforehand. In your case it might mix-in some unwanted commits if your branch has diverged for any reason. 
Using a simple `git pull upstream release` should in normal cases only fast-forward and therefore be the exact "clone" of the upstream (unless you mixed it already up before).

As written @moving-bits and @eddiemuc you should start cleanly by removing and re-fetching the upstream branches.

**Comment by eddiemuc** [comment]
> > @Lineflyer it seems you use the remote names origin and upstream exactly the other way around as is recommended in out git beginner guide?
> 
> Me. what makes you think it like this?
> `origin` is my fork and `upstream` is the cgeo original repo.

You are right, I misread your comment before, sorry.

> Without having read all what you wrote in detail, I stumbled upon the fact, that you used `git pull --rebase upstream release `. I never use the `--rebase` option for that

While this is true, I made it a habit to **always** pull with the --rebase option (regardless of situation and branch) because there's almost never a case where I want to pull using merge option. Additionally I set pull command to use rebase as default in my git settings, this is kind of a "double check" for me.

**Comment by baiti** [comment]
> @baiti
> Without having read all what you wrote in detail, I stumbled upon the fact, that you used `git pull --rebase upstream release `. I never use the `--rebase` option for that, it would only be required if I already applied my changes on that branch and forgot to pull in beforehand. In your case it might mix-in some unwanted commits if your branch has diverged for any reason.
> Using a simple `git pull upstream release` should in normal cases only fast-forward and therefore be the exact "clone" of the upstream (unless you mixed it already up before).

In the git for beginners there is a command `git config --global pull.rebase true`, which I executed as suggested.

This turns each and every `git pull` into a `git pull --rebase` automatically. If that is a bad idea, I better delete that from my global config.

> 
> As written @moving-bits and @eddiemuc you should start cleanly by removing and re-fetching the upstream branches.

Yes, I have done it and it worked nicely applying @eddiemuc's recipe.

**Comment by Lineflyer** [comment]
> In the git for beginners there is a command git config --global pull.rebase true, which I executed as suggested.
> This turns each and every git pull into a git pull --rebase automatically. If that is a bad idea, I better delete that from my global config.

I am not sure, will play around with that next days.

**Comment by eddiemuc** [comment]
> > In the git for beginners there is a command git config --global pull.rebase true, which I executed as suggested.
> > This turns each and every git pull into a git pull --rebase automatically. If that is a bad idea, I better delete that from my global config.
> 
> I am not sure, will play around with that next days.

I use this config already since beginning of my c:geo involvement and it works fine.

**Pull request closed without merging**
