### PR TITLE
WherigoPlayer: add things list, add caching for media and audio, add first icons and styling

### PR DESCRIPTION
**Pull request by eddiemuc**
WherigoPlayer: add things list, add caching for media and audio, add first icons and styling

### CODE REVIEW

**Comment by ztNFny** [comment]
How about these for the icons? Can adjust them and add as xml if you want.

**Comment by ztNFny** [comment]
How about these for the icons? Can adjust them and add as xml if you want.

**Comment by eddiemuc** [comment]
Sure, I like them.

**Comment by eddiemuc** [comment]
@ztNFny I will merge this PR for now, but there will be many more. Would be glad to replace icons with your new ones then

**Comment by ztNFny** [comment]
> @ztNFny I will merge this PR for now, but there will be many more. Would be glad to replace icons with your new ones then

Please ping me when the UI is more or less stable. There are many buttons right now that could use a better icon, but i guess the UI won't stay as it is?

**Comment by eddiemuc** [comment]
> > @ztNFny I will merge this PR for now, but there will be many more. Would be glad to replace icons with your new ones then
> 
> Please ping me when the UI is more or less stable. There are many buttons right now that could use a better icon, but i guess the UI won't stay as it is?

That's correct. Will be a while until gui stable.

**Pull request merged**
