### PR TITLE
hint should be tooltipText on buttons

### PR DESCRIPTION
**Pull request by ztNFny**
https://github.com/cgeo/cgeo/pull/15915 added "hint" to Button / ImageView elements instead of the intended tooltipText which should only be used for TextView as placeholder text

### CODE REVIEW

**Comment by moving-bits** [comment]
Thanks for fixing this. Play Store linked to this page: https://support.google.com/accessibility/android/answer/7158690#zippy=%2Cview. I interpreted this as "use `contentDescription` for ImageViews, `hint` for everything else", but probably I misinterpreted that for our buttons.

**Comment by ztNFny** [comment]
Question is, do we use the tooltipText or remove it completely?

**Comment by fm-sys** [comment]
We already use tool tips at other places in cgeo. They are quite useful IMHO, not just for accessibility reasons.

Screenshot_20240802-232044

**Comment by moving-bits** [comment]
Having tooltips is definitely useful, they should be added where they are missing currently. I'm not sure, though, if they help with accessibility - to my understanding `contentDescription` needs to be added as well.

**Comment by ztNFny** [comment]
Retest this please

**Comment by fm-sys** [comment]
AFAIK tooltips are used by screen readers as well...

**Comment by bekuno** [comment]
Primary we should use `contentDescription` (https://developer.android.com/reference/android/view/View#attr_android:contentDescription). Additionally we can use `tooltipText` (https://developer.android.com/reference/android/view/View#attr_android:tooltipText) for a short tool tip (for API 26+).

**Comment by ztNFny** [comment]
let's merge this as it fixes the bug for button display. Other accessibility improvements may be added later independent of this PR

**Comment by fm-sys** [comment]
Honestly, how many blind people use c:geo at API versions <26? 

I believe adding tooltips is (more than) enough. Everything else would be over the top IMHO.

 But as pointed out by @ztNFny, we can discuss this later on...

**Comment by fm-sys** [comment]
@ztNFny could you re-target this PR to release please?

**Comment by ztNFny** [comment]
> @ztNFny could you re-target this PR to release please?

done

**Pull request merged**
