### PR TITLE
button enhancement

### PR DESCRIPTION
**Pull request by murggel**
## Description

In this PR I added some enhancements, which I found while switching from ImageButton to Button.
I can split it up, if some of the changes should not be implemented

* use accent color for toggle-group in map-settings
image
* adapt compass icon in waypoint list - it was too light 
* image

* don't switch icon for button to store / delete cache from list programmatically -> use 2 buttons and make only one visible
* change delete-icon in export-dialog to cross-sign (but should be replaced with the build-in-clear-function)
already done -> revert corresponding commits
 
* use map icon from material.io in settings
image

* fill settings-symbol on map

## Related issues

rel #10769

### CODE REVIEW

**Comment by Narrat** [comment]
I suppose the commit `ce161e7` (change icon in export-dialog...) from this PR could be dropped, as PR https://github.com/cgeo/cgeo/pull/10934 tries to change it to the build-in clear function?

**Comment by moving-bits** [comment]
> change delete-icon in export-dialog to cross-sign (but should be replaced with the build-in-clear-function)

done with #10934

**Comment by murggel** [comment]
There will be merge-conflicts with PR #10937 in CacheDetailActivity
Once one PR is merged I will resolve them

**Comment by moving-bits** [comment]
Thanks @murggel for tackling the icon button issues!

Failing test is unrelated to the changes in this PR, so let's merge.

**Pull request merged**
