### PR TITLE
GCVote checklogin is added #4794

### PR DESCRIPTION
**Pull request by madankumarbaskaran**
Highlighted comments are fixed. Please review the code and share your comments.

### CODE REVIEW

**Comment by samueltardieu** [comment]
This pull-request contains unresolved conflicts and files which should not have been modified. It cannot be merged as-is.

**Comment by madankumarbaskaran** [comment]
@samueltardieu I am sorry, I created the pull request from wrong branch. Please find the files I changed for GCVote check login fix.

https://github.com/madankumarbaskaran/cgeo/commit/f993e39c9511783665e64e8680123c862a042773

Can I raise PR for this change?. Please comment.

**Comment by samueltardieu** [comment]
Just update this PR.

**Comment by Lineflyer** [comment]
@madankumarbaskaran Can you update this PR or will you raise another PR?

**Comment by Lineflyer** [comment]
Closing this PR due to lack of feedback
@madankumarbaskaran If you would like to continue working on that please feel free to reopen/update this PR or raise another PR.

**Pull request closed without merging**
