### PR TITLE
fix #6886 GC wpt type parsing

### LINKED ISSUE #6886: Waypoint type not parsed correct
##### Detailed steps causing the problem:
- GC19EE6 should have a parking waypoint
- It was correctly stored some weeks ago on my device
- After updating it today the waypoint type changed to reference point 

Looking at other freshly loaded caches nearly all waypoints seem to be parsed as reference point.

##### Version of c:geo used:
2017.12.16-NB1 (incl. latest site change fixes)

##### Is the problem reproducible for you?
Yes

### PR DESCRIPTION
**Pull request by pstorch**

### CODE REVIEW

**Comment by SammysHP** [comment]
Aren't there any tests for this?

**Comment by pstorch** [comment]
@SammysHP I'll have a look

**Comment by pstorch** [comment]
Apparently not. I check if I can add some.

**Comment by Lineflyer** [comment]
If you confirmed it working, I suggest to release again tomorrow. Could be even we replace todays release, but not sure how we could handle the version code in this case.


Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Peter Storch <notifications@github.com> Datum: 16.12.17  17:12  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [cgeo/cgeo] fix #6886 GC wpt type parsing (#6887) 
Apparently not. I check if I can add some.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pstorch in #6887: Apparently not. I check if I can add some."}],"action":{"name":"View Pull Request","url":"https://github.com/cgeo/cgeo/pull/6887#issuecomment-352192841"}}}

**Comment by pstorch** [comment]
The unitests which test the cache parsing didn't check the waypoints. I've added some waypoint checks.

**Comment by pstorch** [comment]
@Lineflyer depending on whether we release today or tomorrow: how should the changelog look like? I've kept the date and the changes from today. Because there are still a good number of users on the old release.

**Comment by Lineflyer** [comment]
Last time when this happend in short cycles, I just changed the date/version name and kept the list of changes.So more or less we replace 12.16 by 12.17 


Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Peter Storch <notifications@github.com> Datum: 16.12.17  19:13  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Lars <gc@droescher.eu>, Mention <mention@noreply.github.com> Betreff: Re: [cgeo/cgeo] fix #6886 GC wpt type parsing (#6887) 
@Lineflyer depending on whether we release today or tomorrow: how should the changelog look like? I've kept the date and the changes from today. Because there are still a good number of users on the old release.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cgeo/cgeo","title":"cgeo/cgeo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cgeo/cgeo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pstorch in #6887: @Lineflyer depending on whether we release today or tomorrow: how should the changelog look like? I've kept the date and the changes from today. Because there are still a good number of users on the old release."}],"action":{"name":"View Pull Request","url":"https://github.com/cgeo/cgeo/pull/6887#issuecomment-352200714"}}}

**Comment by pstorch** [comment]
I've changed the changelog for tomorrows date. After CI gives green I'll merge it.

**Pull request merged**
