### PR TITLE
fix #8942: handle also same-item-event

### LINKED ISSUE #8942: Problem with tb actions while logging
Just copying from support mail, no time to check myself at this moment:

---

To check.
When you "report your visit", the TB are "Has visited" (personal settings). If I want to choose another reason including "do nothing" the list of choices is already on this check mark. If we take this choice again, nothing happens. You have to change the motive. Go back to this pattern for it to take effect.

---

```
--- System information ---
Device: SM-G950F (dreamltexx, samsung)
Android version: 9
Android build: PPR1.180610.011.G950FXXU9DTF1
c:geo version: 2020.09.02-RC
Google Play services: enabled - 20.30.19 (100408-326531024)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: fr_FR
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (9,1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (9,1 GB free) external non-removable
Geocache data: /storage/6432-3331/Android/data/cgeo.geocaching/files/GeocacheData (82,0 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (64,2 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Connecté) / PREMIUM
Geocaching.com date format: dd/MM/yyyy
Installed c:geo plugins: contacts
BRouter connection available: true
--- End of system information ---
```

### PR DESCRIPTION
**Pull request by eddiemuc**
Fix for #8942 : handle also same-item-event

### CODE REVIEW

**Comment by eddiemuc** [comment]
Is this automatically merged to master as well or do I have to do something additional for that?

**Comment by eddiemuc** [comment]
@moving-bits or someone else: I get feedback from codacy "Codacy/PR Quality Review — Codacy was unable to analyse your pull request.". 
This is the first time I request a merge to branch release. Did I do something wrong?

**Comment by moving-bits** [comment]
> @moving-bits or someone else: I get feedback from codacy "Codacy/PR Quality Review — Codacy was unable to analyse your pull request.".
> This is the first time I request a merge to branch release. Did I do something wrong?

Most certainly not - we do have problems with Codacy on release branch sometimes. You can try a retest, but maybe someone with access and knowledge needs to have a look at the CI config.

**Comment by eddiemuc** [comment]
Retest this please

**Comment by moving-bits** [comment]
@eddiemuc 
After merging this PR and #8949 to `release` branch I've merged `release` back to `master`, but received merge conflicts in `geocaching/ui/TextSpinner.java`. I've tried to resolve them, but please cross-check on `master` branch, if this is still behaving as expected with your changes coming from #8907. Thanks.

**Comment by eddiemuc** [comment]
@moving-bits looks very good! Thank you for stepping thtough merge-hell on my behalf.
A question out of curiosity: how do you merge release to master (on the level of "git commands")? I assume you do not rebase master on release but really use `git merge release` for this?

**Comment by moving-bits** [comment]
@eddiemuc 
Thanks for cross-checking, I'm relieved. Interestingly, git had skipped a couple of lines during merging, listed them on neither side. Only by opening the two original PR I discovered what there should be more code in the merge...

Regular way for merging `release` to `master` is using the following command sequence on a local copy _of the original repo_, not of your fork:

```
git checkout release
git pull
git checkout master
git pull
git merge release
git push
```

(With extra commands before the last when merge conflicts should arise.)

But there are other ways as well, without the need of a local copy of the original repo. git is a mighty tool, but to be feared as well sometimes :-)

**Comment by eddiemuc** [comment]
@moving-bits thanks for the insights!

>  Interestingly, git had skipped a couple of lines during merging, listed them on neither side. Only by opening the two original PR I discovered what there should be more code in the merge...

Did you try to use Android Studio conflict resolutions for this (or another tool with similar capabilities)?

**Comment by moving-bits** [comment]
Actually no - I'm so used to command line...
Maybe I should try to remember using AS conflict resolution next time. But merge conflicts are not that often, fortunately, so I tend to have forgotten this when the next conflict arises.

**Pull request merged**
