### PR TITLE
Remove Twitter support

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Removes Twittter support from c:geo (authorization, posting found logs, posting trackable logs)

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by bekuno** [comment]
There is also an entry in the README.md

**Comment by bekuno** [comment]
> retest this please

Please have a look at the checkstyle result. https://ci.cgeo.org/job/cgeo-CI_PR-build/5440/checkstyleResult/

**Comment by moving-bits** [comment]
> Please have a look at the checkstyle result

have fixed those

> There is also an entry in the README.md

This PR only removes support for posting to Twitter, it does not remove our Twitter contact data (which is in `README.md` as well as in-app).

**Pull request merged**
