### PR TITLE
issue_8871

### PR DESCRIPTION
**Pull request by baiti**
fixed spelling

### CODE REVIEW

**Comment by rsudev** [comment]
ok to test

**Comment by moving-bits** [comment]
@baiti 
Thanks for fixing this typo. Workflow is fine so far, just one tiny suggestion: If you additionally use `(fix #xxxx)` in your commit message, with `xxxx` being the issue this PR is for, GitHub would automatically close the related issue on merging this PR. So the commit message in this case could have read `fix typo (fix #8871)`.

**Comment by baiti** [comment]
> @baiti
> Thanks for fixing this typo. Workflow is fine so far, just one tiny suggestion: If you additionally use `(fix #xxxx)` in your commit message, with `xxxx` being the issue this PR is for, GitHub would automatically close the related issue on merging this PR. So the commit message in this case could have read `fix typo (fix #8871)`.

yes, I remember you mentioning it before. I hat put in "issue #8871" but it seems to trigger litereally on "fix #8871" will do next time.

**Comment by Narrat** [comment]
One of the keywords is necessary, yes
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
Without a keyword this PR is only linked to the said issue

**Pull request merged**
