### PR TITLE
fix #5498 only one loader should be active

### LINKED ISSUE #5498: "Nearby" list sometimes forgets number of caches loaded (truncates to 40 entries)
This is another one which is a little bit annoying if you want to explore "Nearby" caches with c:geo.
This issue exists since a long time.
###### Detailed steps causing the problem:
- Open "Nearby" list
- Load at least 60 caches in the list
- Select one entry to see the details
- Go back
###### Actual behaviour after performing these steps:

List shows only 40 caches and not the original list.
If you select an entry again to see the details and go back you might get back to the original number of entries.
###### Expected behaviour after performing these steps:

The already loaded list is always kept and not truncated to 40.
###### Version of c:geo used:

Latest NB.
###### Is the problem reproducible for you:

Yes, almost always.
###### Attach system information if available (see c:geo menu -> About c:geo -> System):

Device: D5503 (D5503, Sony)
Android version: 5.1.1
Android build: 14.6.A.1.236
Cgeo version: 2016.03.03-NB-46936b1
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE (cgeo forced to English)
Geocaching sites enabled:
geocaching.com: logged in (Login OK) / BASIC Installed cgeo plugins: none 
--- End of system information ---

### PR DESCRIPTION
**Pull request by Matze2**
See #5498 for steps how to reproduce and how to verify the fix.

### CODE REVIEW

**Comment by rsudev** [comment]
Please test

**Comment by pstorch** [comment]
test this please

**Comment by Matze2** [comment]
@pstorch
Thanks for testing and approving.

**Comment by pstorch** [comment]
Ok, let's merge it. @Matze2 thanks for your contribution.

**Comment by Matze2** [comment]
Thanks. Looking forward to use a nightly again with Google Map support.

**Pull request merged**
