### PR TITLE
reorder layers (fixes #15334)

### LINKED ISSUE #15334: Track layer displayed on top of cache layer with OSM map source
On OSM maps (both online / offline) the track layer is displayed on top of the cache icon while with Google Maps and the old map implementations it's drawn between map and cache icon layers.

OSM:
image
Google Maps
image

Version: Todays master

### PR DESCRIPTION
**Pull request by ztNFny**
reordered some UnifiedMap layers

This affects only OSM for some reason, not sure how Google Maps layers are layered??

### CODE REVIEW

**Review by moving-bits — APPROVED** [review]
LGTM, thanks for fixing

**Review by moving-bits — CHANGES_REQUESTED** [review]
but it needs to go to `release`, as we should include this fix in the next beta

**Comment by ztNFny** [comment]
> but it needs to go to `release`, as we should include this fix in the next beta

Done

**Comment by moving-bits** [comment]
retest this please

**Review by moving-bits — APPROVED** [review]

**Pull request merged**
