### PR TITLE
fix #15169: redesign MapMarkerUtils/InsetBuilder to mutate all created drawables

### LINKED ISSUE #15169: MapMarkerUtils: exception " Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state"
I found the following exception in a log file (which I analyzed for a different issue). It indicates some non-correct behaviour when dealing with Map Markers. I don't know the concrete effects of this to the user.

```
01-05 11:30:20.671 15881 15881 W LayerDrawable: Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.
01-05 11:30:20.671 15881 15881 W LayerDrawable: java.lang.RuntimeException
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1857)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1977)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:173)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1782)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at cgeo.geocaching.utils.MapMarkerUtils.createWaypointMarker(MapMarkerUtils.java:333)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at cgeo.geocaching.utils.MapMarkerUtils.getWaypointMarker(MapMarkerUtils.java:263)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator.fillViewHolder(CacheDetailActivity.java:2253)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$1.getView(CacheDetailActivity.java:2132)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.AbsListView.obtainView(AbsListView.java:2662)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.HwAbsListView.obtainView(HwAbsListView.java:1309)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.ListView.makeAndAddView(ListView.java:2174)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.ListView.fillDown(ListView.java:874)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.ListView.fillFromTop(ListView.java:943)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.ListView.layoutChildren(ListView.java:1926)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.AbsListView.onLayout(AbsListView.java:2448)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.HwAbsListView.onLayout(HwAbsListView.java:466)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:697)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1146)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3743)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3207)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.Choreographer.doFrame(Choreographer.java:911)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.os.Handler.handleCallback(Handler.java:900)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.os.Handler.dispatchMessage(Handler.java:103)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.os.Looper.loop(Looper.java:219)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-05 11:30:20.671 15881 15881 W LayerDrawable: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
01-05 11:30:20.672 15881 15881 W LayerDrawable: Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.
01-05 11:30:20.672 15881 15881 W LayerDrawable: java.lang.RuntimeException
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1857)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1977)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:173)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1782)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at cgeo.geocaching.utils.MapMarkerUtils.createWaypointMarker(MapMarkerUtils.java:333)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at cgeo.geocaching.utils.MapMarkerUtils.getWaypointMarker(MapMarkerUtils.java:263)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator.fillViewHolder(CacheDetailActivity.java:2253)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$1.getView(CacheDetailActivity.java:2132)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.AbsListView.obtainView(AbsListView.java:2662)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.HwAbsListView.obtainView(HwAbsListView.java:1309)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.ListView.makeAndAddView(ListView.java:2174)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.ListView.fillDown(ListView.java:874)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.ListView.fillFromTop(ListView.java:943)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.ListView.layoutChildren(ListView.java:1926)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.AbsListView.onLayout(AbsListView.java:2448)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.HwAbsListView.onLayout(HwAbsListView.java:466)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10407)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:697)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1146)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.View.layout(View.java:22496)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewGroup.layout(ViewGroup.java:6528)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3743)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3207)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.Choreographer.doFrame(Choreographer.java:911)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.os.Handler.handleCallback(Handler.java:900)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.os.Handler.dispatchMessage(Handler.java:103)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.os.Looper.loop(Looper.java:219)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-05 11:30:20.672 15881 15881 W LayerDrawable: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #15169: redesign MapMarkerUtils/InsetBuilder to mutate all created drawables

This PR refactors MapMarkerUtils (and the InsetBuilder-classes) to mutate ALL "base" drawables used in the markers on the point of their creation. This should be ok memory-wise because the created markers are always cached and reused anyway.

@moving-bits , @ztNFny since you are the experts in these classes, I would be glad if you could take a look at the code

### CODE REVIEW

**Comment by eddiemuc** [comment]
BTW: InsetBuilder and ImageParam seem to have some similarities in that they try to encapsulate a drawable and how it is drawn... I think about that and might look into merging these two concepts

**Comment by eddiemuc** [comment]
Failing build is unrelated. It is related to a translation error which I (hopefully) corrected on crowdin

**Comment by ztNFny** [comment]
Didn't really have time to review this yet, BUT together with the recent change of opaque waypoint drawables:
MapMarkerUtils should receive an even bigger refactoring to get rid of scaling throughout the code. Right now scaling is handled on the lowest possible level - when the individual drawable is inserted. It'd be a lot nicer to first build the whole drawable, then scale it as one.
This was done "back then" because applying the scaling to the LayerDrawable wasn't possible, but now if there's one flattened mutated drawable anyway then it can be done on that result drawable which will probably get rid of about 20% of the code of MapMarkerUtils.

**Comment by eddiemuc** [comment]
> MapMarkerUtils should receive an even bigger refactoring to get rid of scaling throughout the code. Right now scaling is handled on the lowest possible level - when the individual drawable is inserted. It'd be a lot nicer to first build the whole drawable, then scale it as one.

As part of my (small) refactoring I already extracted a helper function which gets the drawable and optionally mutates and scales it. Not sure if this is what you mean or if you have something even bigger in mind?

**Comment by ztNFny** [comment]
Something bigger ;-)

Every element that makes up the marker is scaled individually:
image

Alternative would be to draw the marker at fixed size, then at the end flatten it to 1 drawable instead of a layerdrawable and scale that.  didn't want to do that at the time due to the overhead, but it seems this is now done for most cases anyway (e.g. as an enabler for the transparent icons).

**Comment by ztNFny** [comment]
Looking at your changes I can't spot any calls of InsetsBuilder with mutate=false. Why then introduce this as a variable if it's always true?

**Comment by eddiemuc** [comment]
> Looking at your changes I can't spot any calls of InsetsBuilder with mutate=false. Why then introduce this as a variable if it's always true?

That's a valid question. Two reasons:
* InsetsBuilder seemed to be a general-purpose class which can also be used in other places than MapMarkerUtils. I wanted to leave those "other places" the option to choose mutate=false
* Maybe it is not necessary to mutate really ALL drawables. Leaving the flag gives the option to un-mutate single usages later

Very honestly I did not completely understand InsetBuilder/InsetsBuilder and whether it was created specifically for MapMarkerUtils or not. So maybe it would be ok to leave out the flag

Also maybe the whole PR doesn't make much sense if a bigger rfactoring of MapMarkerUtils should be done

**Comment by ztNFny** [comment]
> Also maybe the whole PR doesn't make much sense if a bigger rfactoring of MapMarkerUtils should be done

It being required and being done are 2 different things ;-)
The PR is fine imho, we can still do more later

**Comment by eddiemuc** [comment]
Ok, thanks a lot for the feedback

**Comment by eddiemuc** [comment]
Not quite sure what's wrong with the build. It reports a lint issue for a translation problem. But I fixed this problem already in crowding 2 days ago and rebased the build onto master this morning. Apparently I did something wrong

**Comment by eddiemuc** [comment]
Retest this please

**Comment by moving-bits** [comment]
From a quick glance LGTM, thanks for diving into this.

> Something bigger ;-)

I guess @ztNFny is referring to #14621.

**Pull request merged**
