### PR TITLE
fix #5760 wrong marker when canceling store

### LINKED ISSUE #5760: cancelling storing leads to wrong markers
##### Detailed steps causing the problem:
- Start downloading an online search result list
- Cancel at some point in between

##### Actual behavior after performing these steps:
The online search result list is refreshed and _all_ caches have the offline marker. But in fact, not all have been stored. When randomly clicking caches from the list now, some open immediately, and some will be downloaded first (the ones we cancelled).

### PR DESCRIPTION
**Pull request by pstorch**
moved the assignment of the (new) lists into the store method

### CODE REVIEW

**Comment by pstorch** [comment]
A geokrety Test fails. I don't think it is related to my changes. I can have a look tomorrow.

**Comment by kumy** [comment]
@pstorch GKM api seems down. I ll look at it. Thanks for pointing this.

**Comment by kumy** [comment]
CI: test please

**Comment by kumy** [comment]
test this please

**Comment by pstorch** [comment]
@kumy thanks

**Pull request merged**
