### PR TITLE
Add geochecker geotjek.dk

### PR DESCRIPTION
**Pull request by zagge-cgeo**
** Description of change: **
Add the geochecker geotjek.dk used in e.g. this cache
https://coord.info/GC2P6JZ

### CODE REVIEW

**Comment by Lineflyer** [comment]
ok to test

**Comment by Lineflyer** [comment]
@zagge-cgeo Can you please provide a geocode of a cache where this is used?

**Comment by Lineflyer** [comment]
@zagge-cgeo  Sorry, did not see it in your comment. Nevermind.

**Comment by Lineflyer** [comment]
@zagge-cgeo Still one question: This looks like the same website as geocheck.org. Do you know whether they have even more aliased, which we could/should add in the same step?

**Comment by zagge-cgeo** [comment]
> @zagge-cgeo Still one question: This looks like the same website as geocheck.org. Do you know whether they have even more aliased, which we could/should add in the same step?

@Lineflyer I do not know that but I currenlty check for checkers not yet supported by cgeo

**Comment by zagge-cgeo** [comment]
I have greped trough the caches I have in my database but found none other one that uses the same path as geochecker.com. Howerver I have added support for the checker of geocache-planer.de that is used quite often.

**Pull request merged**
