### PR TITLE
split "Map" settings into 2 new pages and move some stuff to Appearance

### LINKED ISSUE #14103: Split "map" settings into multiple pages
All our settings pages are (on my phone) 1-2 pages long which is ok to find a setting. And then there's map settings which is 6 pages, making it the 3*larger and hard to navigate.

I propose to split this up into multiple pages for better accessibility.

Proposal:
- Map Sources (sources, offline maps, offline themes, offline hillshading, multithreaded osm)
- Map content (waypoints, map conent)
- Map behaviour (map behavior, proximity notifications)
- Map colors (map lines)

### PR DESCRIPTION
**Pull request by ztNFny**
fixes #14103

split "Map" settings into:
- Map Sources (sources, offline maps, offline themes, offline hillshading, multithreaded osm)
- Map content & Behaviour (waypoints, map conent, map behavior, proximity notifications)

map line colors is moved to "appearance"

### CODE REVIEW

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
Rebased. Not sure what to do about the Codacity complexity warnings - it's less complex than it was before when it was 1 file ...

**Comment by moving-bits** [comment]
> Rebased. Not sure what to do about the Codacity complexity warnings - it's less complex than it was before when it was 1 file ...

AFAICS Codacy only complains about unused imports and wrong import order, see https://ci.cgeo.org/job/cgeo-CI_PR-build/4493/checkstyleResult/new/

**Comment by ztNFny** [comment]
> > Rebased. Not sure what to do about the Codacity complexity warnings - it's less complex than it was before when it was 1 file ...
> 
> AFAICS Codacy only complains about unused imports and wrong import order, see https://ci.cgeo.org/job/cgeo-CI_PR-build/4493/checkstyleResult/new/

Strange, those were not there before but instead complexity warnings... Fixed the imports, let's see

**Comment by moving-bits** [comment]
BTW: You can check things like import order locally in AS when using the Checkstyle tab

**Comment by ztNFny** [comment]
> BTW: You can check things like import order locally in AS when using the Checkstyle tab

Checkstyle doesn't complain about this import order while Codacy does:

import cgeo.geocaching.R;
import cgeo.geocaching.settings.SettingsActivity;
import cgeo.geocaching.utils.MapMarkerUtils;

**Comment by ztNFny** [comment]
Retest this please

**Comment by moving-bits** [comment]
> Checkstyle doesn't complain about this import order while Codacy does:
> 
> import cgeo.geocaching.R;
> import cgeo.geocaching.settings.SettingsActivity;
> import cgeo.geocaching.utils.MapMarkerUtils;

I guess this was not about the cgeo import entries, but about the `import android.os.Bundle;` entry before the cgeo block. Checkstyle should be able to detect this, if you select the "cgeo" profile.

Import order is documented here: https://github.com/cgeo/cgeo/wiki/Coding-Conventions#imports-order

**Comment by ztNFny** [comment]
Retest this please

**Comment by moving-bits** [comment]
"Could not create ADB bridge" error again...

retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by ztNFny** [comment]
Retest this please. "Could not create ADB Bridge" again

**Comment by ztNFny** [comment]
Retest this please

**Comment by eddiemuc** [comment]
> Import order is documented here: https://github.com/cgeo/cgeo/wiki/Coding-Conventions#imports-order

I never understood why c:geo needs a special import order not complaint to the java/android standards btw...

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
