### PR TITLE
fix #13008: fix transition problems for single image galleries

### LINKED ISSUE #13008: [Image gallery] strange animations under specific circumstances
### Describe your problem!

The image gallery does crash when going back from single-image-view of a spoiler image. 

### How to reproduce?

- click on "spoiler images"
- open a/the spoiler image in full screen
- go back
- CRASH! 

### Actual result after these steps?

```
05-13 11:31:35.524  3815  3815 E AndroidRuntime: FATAL EXCEPTION: main
05-13 11:31:35.524  3815  3815 E AndroidRuntime: Process: cgeo.geocaching, PID: 3815
05-13 11:31:35.524  3815  3815 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView.getImageViewForIndex(ImageGalleryView.java:412)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView.lambda$openImageViewer$7(ImageGalleryView.java:467)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView.lambda$openImageViewer$7$ImageGalleryView(Unknown Source:0)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ui.-$$Lambda$ImageGalleryView$LG32SzA9OCH4UYy9B_CYXE5lOr8.call(Unknown Source:4)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at cgeo.geocaching.ImageViewActivity$6.onMapSharedElements(ImageViewActivity.java:472)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.ActivityTransitionCoordinator.viewsReady(ActivityTransitionCoordinator.java:236)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.EnterTransitionCoordinator.viewsReady(EnterTransitionCoordinator.java:133)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.EnterTransitionCoordinator.triggerViewsReady(EnterTransitionCoordinator.java:161)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.EnterTransitionCoordinator.viewInstancesReady(EnterTransitionCoordinator.java:117)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.ActivityTransitionState.startEnter(ActivityTransitionState.java:233)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.ActivityTransitionState.enterReady(ActivityTransitionState.java:213)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8148)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.Activity.performRestart(Activity.java:8198)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:5355)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.servertransaction.WindowVisibilityItem.execute(WindowVisibilityItem.java:39)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
05-13 11:31:35.524  3815  3815 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
```

### Expected result after these steps?

No crash 

### Reproducible

Yes

### c:geo Version

2022.05.13

### System information

_No response_

### Additional Information

Unrelated to the crash, but there's another situation where there is a strange animation (see video):

https://user-images.githubusercontent.com/64581222/168257814-bbfa849a-3a4c-4970-9103-55a6434fce6e.mp4

https://user-images.githubusercontent.com/64581222/172001745-2ba227be-a6e9-4b2f-9b5c-7bdcceb10b10.mp4

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #13008: fix transition problems for single image galleries

### CODE REVIEW

**Comment by eddiemuc** [comment]
Todo: try to use onstart/onstop in image gallery activity, but use postphone in on create and start transition in onstart

**Comment by Lineflyer** [comment]
retest this please

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
Failing test is unrelated so let's merge

**Comment by fm-sys** [comment]
Great, thanks! Works like a charm...

**Pull request merged**
