### PR TITLE
update crowdin process

### PR DESCRIPTION
**Pull request by bekuno**
- clarify the README
- optimize/fix download script
  - fix bug for the "pr" parameter check
  - add check for new languages
- add gitignore entry for cgeo-calendar strings

### CODE REVIEW

**Comment by Lineflyer** [comment]
retest this please

**Comment by bekuno** [comment]
@rsudev Can you review this PR in the next days?

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
@moving-bits please merge this PR

**Pull request merged**
