### PR TITLE
Add 'go to' deprecation notice

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
As discussed in yesterday's dev meeting: Add a deprecation notice for "go to" functionality.

### CODE REVIEW

**Comment by fm-sys** [comment]
We won't delete the goto cache itself, right? So maybe it would be better to only show the notice when calling via the deprecated link...?

**Comment by moving-bits** [comment]
I had tried that first, showing the dialog in `QuickLaunchItem`. But when called via `AbstractNavigationBarActivity` it opens the dialog and immediately crashed, noting a "activity has leaked a WindowDecor" (or something like this), though the given activity is still valid (eg: `MainActivity`, still running).

**Comment by moving-bits** [comment]
Alternatively we could use a one-time message to not annoy those who use ZZ0 regularly (but with the risk that some people may not read the notice and just click it away - but we can't take care of every situation probably)

**Comment by moving-bits** [comment]
Rebased + changed message to a OneTimeMessage to be less-intrusive

**Comment by moving-bits** [comment]
failing test is unrelated, PR #15379 not yet aplied

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
