### PR TITLE
SAF-Helper: introduce FileByteReader

### PR DESCRIPTION
**Pull request by eddiemuc**
SAF-Helper: introduce FileByteReader
This will help implementing #10176

### CODE REVIEW

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
Retest this please

**Comment by moving-bits** [comment]
@eddiemuc 
Thanks for providing `FileByteReader` class. I've finally reached a stage with BRouter integration where I felt prepared to tackle SAF migration of routing tile data.

I've tackled the calling chain and reached the grounds of `PhysicalFile`. Instead of a `File` I provide the `InputStream` returned by `ContentStorage.get().openForRead(PersistableFolder.ROUTING_TILES.getFolder(), filenameBase + ".rd5")`.

But now I'm stuck in the class constructor of `PhysicalFile`: I guess `FileByteReader` is meant to replace `RandomAccessFile`?

If I try to replace the old `ra = new RandomAccessFile(f, "r")` with `ra = new FileByteReader(is)` it does not work, as a `InputStream` is not accepted as parameter, it has to be a `FileInputStream`, but there is no method in `ContentStorage` returning a `FileInputStream`.

Changing `FileByteReader` to accept `InputStream` instead of `FileInputStream` does not help either, as `InputStream` does not provide a `getChannel()` method which `FileByteReader` seems to rely on heavily.

(Have not dived any deeper in replacing `RandomAccessFile` with `FileByteReader` - many more changes needed there, as there are quite a few methods being called from `RandomAccessFile`, but not supplied by `FileByteReader` - but haven't checked yet, whether they will still be needed.)

Can you give me some hint on how to continue?
I've put the current intermediate state (not yet compiling!) into a branch `brouter_saf_tilefiles` in my repo: https://github.com/moving-bits/cgeo/tree/brouter_saf_tilefiles

**Comment by eddiemuc** [comment]
@moving-bits short answer is that the InputStream returned by scoped storage is in fact a FileInputStream IF it references a local file. So you can safely cast it. Same is done for map files btw (and I learned the trick from @pstorch)

But if you want I can tackle this issue further. I just forgot about it last couple of days.

**Comment by moving-bits** [comment]
Ah, I see, didn't know that. Thanks for the pointer! I'll try to continue working on this the next days, let's see how far I will come :-)

**Pull request merged**
