### PR TITLE
add splash logo (fix #8988)

### LINKED ISSUE #8988: Splash Screen while starting c:geo
Opening c:geo on low budget devices can take 1-2 seconds without any visual feedback, so we should integrate a splash screen which is displayed while android loads the first activity.
Currently, `windowDisablePreview` is (probably) set, that's why we don't see a just black or white empty screen while c:geo is starting up (like in some other apps). 
However, we can also display the c:geo logo on startup, like it is also done by whatsapp or the official gs geocaching app.

Approach is explained here:
https://developer.android.com/topic/performance/vitals/launch-time#themed
https://android.jlelse.eu/the-complete-android-splash-screen-guide-c7db82bce565

Sidenote: Of course, I don't want to prolong the start unnecessarily, but just "beautify" the waiting time that is already there...

### PR DESCRIPTION
**Pull request by moving-bits**
Alternative to #8993.

This PR implements its own `SplashActivity` which does nothing more than displaying the image and forwarding the intent to the original `MainActivity`.

### CODE REVIEW

**Comment by fm-sys** [comment]
Tested, but didn't work for me. See https://github.com/cgeo/cgeo/pull/8993#issuecomment-718035795

**Comment by moving-bits** [comment]
Adapted this PR a bit after having found slightly different examples - does work over here now :-)

I found no way for transparency or for setting the background according to our theme settings at this early stage of loading program, only predefined opaque colors, so I chose a middle-grey for background for now:
image

@fm-sys
Would be great if you could cross-check it, if you find the time.

**Comment by fm-sys** [comment]
I found time to test it - and I was impressed. What a smooth startup! Now it's even more fun to open c:geo just to see the startup animation ;-)

**Comment by Lineflyer** [comment]
Cool. I would rather use a (almost) black background (as black is the default theme in c:geo).

**Comment by fm-sys** [comment]
What about the background color used at our home activity when transparency is deactivated?

**Comment by moving-bits** [comment]
Updated it to the dark grey tone used on MainActivity when transparency is disabled:

image

**Comment by moving-bits** [comment]
and thanks for cross-checking / testing!

**Pull request merged**
