### PR TITLE
rel to #12384: first version for multi waypoint creation

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #12384: first version for multi waypoint creation

### CODE REVIEW

**Comment by eddiemuc** [comment]
A first and not yet very comfortable possibiility to create multiple waypoints out of a calculated coordinate.

* Select a calculated coordinate with long click and choose new entry "Generate Waypoints":
image

* In the upcoming dialog, enter a range expression for the variable you want to iterate over, e.g.:
image

* In the upcoming list, select the generated coordinates which actually should become waypoints, e.g.:

image

=> waypoints are generated as selected:

image

image

**Comment by eddiemuc** [comment]
When investing a little time you can create ratheer artistic waypoints constellations already:

image

image

image

image

**Comment by moving-bits** [comment]
Very cool feature, love to see that in c:geo!

A couple of questions / ideas:
- is a syntax like "A=1,3,6" possible as well?
- are the generated waypoints preselected (dialog) - otherwise an "all" button would be nice
- shall we use a separate waypoint type for those generated waypoints to be able to use a different icon (for easier recognition on the map)
- the latter would also allow a function to remove all generated waypoints from the waypoint list which could come handy

**Comment by eddiemuc** [comment]
I just relalized that the feature incomplete. It will not correctly work for indirect values. E.g. if there's a variable B=A+1 and I specif A=0-5 then B will not be updated accordingly. I probably should not merge this feature yet...

**Comment by eddiemuc** [comment]
> - is a syntax like "A=1,3,6" possible as well?

Works already. You can also exclude single values by pretending ^

> - are the generated waypoints preselected (dialog) - otherwise an "all" button would be nice

Yes that would be handy :-) In plan to add this generically for the SimpleDialog.selectMulti function. But it is not there yet.

> - shall we use a separate waypoint type for those generated waypoints to be able to use a different icon (for easier recognition on the map)

Good idea

> - the latter would also allow a function to remove all generated waypoints from the waypoint list which could come handy

Also good idea. To prevent generating too many waypoints I was also thinking about building a map preview function to view the waypoints before even saving them.

**Comment by eddiemuc** [comment]
This PR is superseeded by PR #12588, thus I will close/delete it

**Pull request closed without merging**
