### PR TITLE
ALC Loosing Found State (issue #14672)

### PR DESCRIPTION
**Pull request by baiti**
## Description

An attempt to address the issue of `searchByGeocode()` not giving us the true found state of a lab cache. The envisioned solution is to do a subsequent `search()`, which actually seems to be superfluous since we actually got the searched object, however, we got it without the found state. The `search()` function gives us the found state so we merge that into the object we wanted to fetch in the first place. This fix is a circumvention for a missing functionality in the api we're using.

## Related issues

issue #14672

## Additional context

I have not been able to verify whether this fix actually resolves the referenced issue. Reason is that I don't have a userid which I can use. It only works with a premium account, however, with my premium account I don't do lab caches ;)

P.S.: I have removed two methods which were flagged as being "not used". If those should remain in the code, I will hve to update the PR accordingly. Pls let me know.

### CODE REVIEW

**Comment by Lineflyer** [comment]
If I am reading the code right, this change is done not only for the found state of lab caches but checking the found state of all results. 
IMHO we should give this change more time to test in nithtlies, which would mean to only merge it once we branched of for the next beta. Only my few cents without deep code knowledge...

**Comment by baiti** [comment]
> If I am reading the code right, this change is done not only for the found state of lab caches but checking the found state of all results. IMHO we should give this change more time to test in nithtlies, which would mean to only merge it once we branched of for the next beta. Only my few cents without deep code knowledge...

It does a search based on a `Geopoint` within a radius of 1 meter. In most cases the search will return a Collection with just one object, the one we're interested in. Even if it returned multiple objects (within that 1 meter radius) I am comparing the `gecocode` aka `alc-id` for a match and only on a match I am extracting the found state.

Also, the `search()` function I am using is exclusively scoped at adventure lab caches, it does not target any other geocache objects managed by other connectors. The function can never return any other object that an adventure lab cache.

Of course I am ok with postponing a merge for as long as you think it is appropriate. I am even more ok with not throwing it into the upcoming beta.

**Review by moving-bits — APPROVED** [review]
LGTM from looking at the code (haven't tested actual execution - currently have no caches in reach for me that fit the criteria).

**Comment by moving-bits** [comment]
WRT merging this PR: As we are planning to start a new beta phase today, which is typically two weeks, I see two choices:
- we could merge it today and include it directly in upcoming beta - change is restricted to certain cache type and radius only, LGTM, and would be easy to remove from beta, if need should be.
- or we give it a couple of days in the nightlies first (hoping that some people text explicitly this area), and cherry-pick it into beta version, then preparing a second beta.

Currently I tend to option one.

**Comment by ztNFny** [comment]
I will try to test this tonight, can't promise anything tho

**Comment by moving-bits** [comment]
Let's try it in the nightlies

**Pull request merged**
