### PR TITLE
Move LoggingManager network calls to background thread

### PR DESCRIPTION
**Pull request by NotWoods**
## Description
The logging manager classes were making network calls on the main thread after some initial background work was done. This change moves that work to the background.

## Related issues
Issue discovered in https://github.com/cgeo/cgeo/pull/13126

### CODE REVIEW

**Comment by fm-sys** [comment]
retest this please 

_CI build is failing, but it's most probably unrelated to the PR. This comment will trigger a rebuild._

**Comment by bekuno** [comment]
> 
> CI build is failing, but it's most probably unrelated to the PR. This comment will trigger a rebuild.

@mucek4 Time for a reboot?

**Comment by mucek4** [comment]
Rebooted. 
Retest this please.

**Comment by moving-bits** [comment]
@NotWoods 
After having merged your PR about annotating methods for worker threads there's now a conflicting file in this PR. Can you update? Thanks.

**Comment by NotWoods** [comment]
retest this please

**Comment by moving-bits** [comment]
Compiling issues fixed, let's give it a try in the nightlies. Thanks @NotWoods for this contribution!

**Pull request merged**
