### PR TITLE
Make cache list info items configurable

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
- Make cache list info items configurable
- Add migration for quicklaunch items and showListsInCacheList

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
Whats this about?
Is there any related issue explaining this feature?

**Comment by moving-bits** [comment]
Sorry, forgot to link to: This is #13278

**Comment by ztNFny** [comment]
Why is this preference on "offline data"? It should be in appearance.
I had to look up this PR and check the code to even find the setting - and that's with knowing it was added

**Comment by moving-bits** [comment]
I've put it there because the old setting for displaying lists was there. Also the list load limit is there (should be moved as well, if we decide to put this setting in a different place).

**Comment by ztNFny** [comment]
All the old settings refer to offline lists only - at least according to their texts. If stuff like load limit also applies to searches its text needs to be changed

**Comment by Lineflyer** [comment]
I had the same feeling at first when looking for this new feature, but then the "loading limit for offline lists" should move with it.

**Comment by ztNFny** [comment]
So in Appearance a new sub-section "Cache Lists"?

**Comment by fm-sys** [comment]
Appearance can probably be renamed to "general". Appearance is a bit misleading as map appearance for example is _not_ there

**Comment by moving-bits** [comment]
I'll prepare this for the nightlies, so we can test it

**Comment by moving-bits** [comment]
What about the "ask which list to store caches in" entry?

**Comment by Lineflyer** [comment]
> Appearance can probably be renamed to "general". Appearance is a bit misleading as map appearance for example is _not_ there

"General" is a bit to generic ;) ......not knowing a better name though.

**Comment by ztNFny** [comment]
Can we rename "Jasmer" to "Place month" or something similar? Even knowing what the jasmer challenge is I didn't know what to expect from the item, had to add it and see it in action.

**Pull request merged**
