### PR TITLE
add try/catch for RejectedExecutionException (related to #8402)

### PR DESCRIPTION
**Pull request by moving-bits**
- Adds a try/catch block for the suspected code lines for `RejectedExecutionException `, logs the exception message
- tries to help with #8402

### CODE REVIEW

**Comment by Lineflyer** [comment]
Releaase or master?

**Comment by moving-bits** [comment]
ok, simply switching base branch in GitHub does not work in this case. I'll try to create a separate PR based on release later.

**Comment by UniQP** [comment]
@moving-bits You can do `git rebase --onto release master` to (locally) retarget the branch from `master` to `release`. Afterwards, you need a `git push --force-with-lease` to push the changes.

**Comment by moving-bits** [comment]
@UniQP 
Thanks for the hint. Pretty cool! 
Will add this to my personal git cheat sheet...

**Comment by Lineflyer** [comment]
Thanks @UniQP 
This will also go to my cheat sheet :)

**Comment by Lineflyer** [comment]
@moving-bits 
I have just seen, that this is in the map code. 
Wild guess: Many people report, that the map stops loading caches at some point while moving around. Only after manual trigger by moving/zooming the map its loaded before later the problem occurs again. Any correlation to this point in code?

**Pull request merged**
