### PR TITLE
don't clear openInAdvancedMode setting when deleting a filter

### PR DESCRIPTION
**Pull request by fm-sys**
Somewhere this issue was recently mentioned off-topic, but I don't find the place anymore...

### CODE REVIEW

**Comment by ztNFny** [comment]
I can't see that this makes any difference at all? Clearing the filter behaves the same with and without this.

I think you're refering to https://github.com/cgeo/cgeo/issues/11328

**Comment by fm-sys** [comment]
> I think you're refering to #11328

Yes, exactly. Thank you!



> I can't see that this makes any difference at all?  

Have you really tested it with the "quick clear" button? For me, it had worked in the emulator...

grafik
 

https://github.com/cgeo/cgeo/issues/11328#issuecomment-950599277:
> Also that Clear is just even worse than the "Delete" function inside the filter dialog, it removes all the filter options and also sets the filter to simple instead of advanced mode.

**Comment by fm-sys** [comment]
> had hoped it would fix the "removes all the filter options" part.

If you are referring to "use OR", "inconclusive" etc. it should be clarified first, if these settings are really expected to be persistent even after a complete clear... For "advanced" this is definitely the case (and already handled that way by the filters activity). But for the other settings...? 

Opinions?

**Comment by eddiemuc** [comment]
Codewise it looks fine. Won't merge though because there seema to be a still-open discussion about this.

**Review by eddiemuc — APPROVED** [review]

**Comment by ztNFny** [comment]
> If you are referring to "use OR", "inconclusive" etc. it should be clarified first

No. I'm refering to the actual filter settings.
The way I'm using the filters I always have Types and Status sections enabled, then (the 2 most frequently used scenarios) filter for "Found" or "Has offline log". To unset that filter I then have 2 options:
- press delete / clear -> next time I open the filter dialog I'll first have to add the section back -> many clicks
- go to the filter dialog, find the modified filter (e.g. "Found") and change it from "Yes" to "All" -> search for the filter, time consuming.

But I think this discussion should be in #11328, not in this PR which in itself is probably fine (but not solving #11328)

**Comment by fm-sys** [comment]
The still ongoing discussion is unrelated to the bug, which was mentioned in that issue as off-topic. So let's merge here...

**Pull request merged**
