### PR TITLE
fix #5415: PQ import dialog not intuitive

### LINKED ISSUE #5415: The improved dialog for PQ import is less intuitive
2016.01.21-NB

This is for sure a subjective impression, but for me the previous implementation with showing a dialog after clicking on a PQ name was ¨failsafe¨ and intuitive. WIth the new implementation users might miss to understand that clicking on the name and clicking on the icon triggers different things.
I don't know why Ihave this feeling, maybe because the icon does not really look clickable. I would honestly prefer the old implementation.
Opinions on that?

### PR DESCRIPTION
**Pull request by pstorch**
I'm not an expert in UI design, but I wanted to give it a try.
What do you think about this design change? Now they are 'real' buttons and the options should be more clear to the user.

### CODE REVIEW

**Comment by rsudev** [comment]
I am also no UI expert :)
What I like in this change is the clear interaction hint to the user. What I do not like so much is the ragged left the titles form. I think putting the buttons to the right will work better.

**Comment by pstorch** [comment]
Good idea, let's compare it with buttons to the right.

**Comment by pstorch** [comment]
Yes, buttons to the right looks better.

**Comment by SammysHP** [comment]
This does not follow any UI guideline, but c:geo does not follow any UI guideline at all, so it's not a problem at the moment. ;)

What happens when you tap on the title? The same as tapping on the magnifying glass?

**Comment by pstorch** [comment]
Nothing. The listeners are attachted to the buttons only.

**Pull request merged**
