### PR TITLE
introduce new wapoint type for generated waypoints (rel. to #12626)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Stores generated waypoints using a new waypoint type.
For screenshots see https://github.com/cgeo/cgeo/issues/12626#issuecomment-1030830136

Setting "WIP" for now, as some waypoint handling features should be added. For a proposal see https://github.com/cgeo/cgeo/issues/12626#issuecomment-1030825175

### CODE REVIEW

**Comment by ztNFny** [comment]
@moving-bits I accidentally committed my icon changes against your branch. if you mind them just revert, I have them in a branch of my own. Will test-drive them in my build for a few days and adjust them based on that first impression. If you have feedback to share please be welcome.

**Comment by moving-bits** [comment]
> @moving-bits I accidentally committed my icon changes against your branch. if you mind them just revert, I have them in a branch of my own. 

No problem. As it looks that I need to fix some CI findings anyway, and as you still have your files in your own branch, I would simply update my PR and force-push.

> Will test-drive them in my build for a few days and adjust them based on that first impression. If you have feedback to share please be welcome.

Thanks for working on it. I'll provide screenshots to make it easier for the team to follow the path being pursued:

image.image

Some quick thought on those icons:
- pro: crisp & clear in both standard and compact mode
- con: I would associate the icon more with "has a formula" than with "has been generated"

I guess the latter is more relevant for the standard-sized icons. Maybe something like "[1-3]" would fit for those (using square brackets and a range of numbers)?

**Comment by fm-sys** [comment]
> Maybe something like "[1-3]" would fit for those (using square brackets and a range of numbers)?

Maybe it would also be enough to just use square brackets instead of normal ones...? `[x]`

**Comment by ztNFny** [comment]
> Maybe something like "[1-3]" would fit for those (using square brackets and a range of numbers)?

Too much content for the small space available. Height would be too small to recognize anything

**Comment by moving-bits** [comment]
> > Maybe something like "[1-3]" would fit for those (using square brackets and a range of numbers)?
> 
> Maybe it would also be enough to just use square brackets instead of normal ones...? `[x]`

still think it's too close with the symbol for "has formula":

image

In this screenshot, only the last two waypoints do have a formula, whereas all waypoints above are generated (and have fixed coordinates, no formula). When using "[x]" as symbol for a waypoint this would look pretty confusing, IMHO, as the generated waypoints would have "[x]" as icon symbol, and the last two waypoints would have a "(x)" as symbol directly beneath the icon.

I would go for something more distinct.

**Comment by moving-bits** [comment]
> > Maybe something like "[1-3]" would fit for those (using square brackets and a range of numbers)?
> 
> Too much content for the small space available. Height would be too small to recognize anything

Ok, understandable. I had feared something like this.

Hm, any other idea to make it more distinct from the other "(x)" symbol?

**Comment by ztNFny** [comment]
But "has formula" and "generated" are closely related. You can only generate from a formula, so having that icon seems like an obvious choice to me.
Also the (x) icon indicates "variable", which is what the waypoint represents, the result of "testing" a variable.

The other idea I had was something like a joker in a card game but couldn't come up with a simple enough icon for that.

**Comment by ztNFny** [comment]
I had tested a star like this, liked the "(x)" better, but I can show you other options on sunday
image

**Comment by moving-bits** [comment]
Browsing material font, maybe some of those would fit?

image.image.image.image.image.image


Or maybe just a sequence of numbers, as here (but without the extra border):
image

Or maybe just the generic "waypoint" marker (two circles), but in a different color?
e. g.: 
image

**Comment by ztNFny** [comment]
> Browsing material font, maybe some of those would fit?

None of them say "joker", "guess" or "variable" to me. The icon should have some association with the formula it comes from so you can identify it as such.

> Or maybe just the generic "waypoint" marker (two circles), but in a different color?

Just changing the color is bad UX and ignoring vision-impaired users (and also normal ones with bad visibility conditions, e.g. direct sunlight).

**Comment by ztNFny** [comment]
The icon represents "the result of a formula with some variable(s) guessed". To me this offers the following keywords an icon could be selected from:
- result
- formula
- variable
- guess

**Comment by moving-bits** [comment]
- "result" could be associated with the "=" sign, so maybe `=` or `[=]` might work
- or we could use "?" as the universal placeholder symbol, e. g. `[?]`, `1?7`, `.?.`, `•?•` or just plain `?`

**Comment by fm-sys** [comment]
> [?]

I like this one most. At least it seem to be the most logical one... :)

**Comment by ztNFny** [comment]
> > [?]
> 
> I like this one most. At least it seem to be the most logical one... :)

Similar to mystery though?

**Comment by moving-bits** [comment]
> > > [?]
> > 
> > 
> > I like this one most. At least it seem to be the most logical one... :)
> 
> Similar to mystery though?

We would have a white background with colored symbol (inverted colors compared to mystery caches), and we have added brackets, so they should be distinguishable enough.

Alternatively we still have the first two proposals in https://github.com/cgeo/cgeo/issues/12626#issuecomment-1030677669

**Comment by moving-bits** [comment]
> The new type should not appear when creating a waypoint, just noticed this in yesterday's build.

Meaning: The new type should never appear in the waypoint type selector, and waypoints of type "generated" should have no type selector?

**Comment by moving-bits** [comment]
Hm, thinking about it, let me fine-tune this a bit:

The new type should never appear in the waypoint type selector, _if current waypoint type isn't "generated". Waypoints of type "generated" should have a waypoint type selector, to be able to convert such a waypoint to (e. g.) "Final"._

**Comment by moving-bits** [comment]
Added variable display of type `GENERATED`:

|editing waypoint of type GENERATED|editing waypoint of different type|adding a new waypoint|
|---|---|---|
|image|image|image|

**Pull request merged**
