### PR TITLE
check & add NonNull/Nullable annotation

### PR DESCRIPTION
**Pull request by bekuno**
While working on #10071, I saw many possible Null problems.
Therefore, I have started to annotate the code and fix such errors.
More changes will follow.

@moving-bits Please review the changes especially in Route.

### CODE REVIEW

**Comment by moving-bits** [comment]
@bekuno 
Something has gone wrong with this PR, have a look at the commit history

**Comment by bekuno** [comment]
> 
> 
> @bekuno
> Something has gone wrong with this PR, have a look at the commit history

@moving-bits 
Yes I know, I did a false click. :-(

For now it is no problem as there are no conflicts.
I will reorder the PR when all changes of the pipeline are in.

It would be fine if you could review the changes.
Every commit is a single change.
But I would not make so much small PR.

**Comment by moving-bits** [comment]
> > @bekuno
> > Something has gone wrong with this PR, have a look at the commit history
> 
> @moving-bits
> Yes I know, I did a false click. :-(

Ah, ok.

> It would be fine if you could review the changes.

Will do, but need some more time for it. Pretty busy time right now... Will try to have a look at it during the weekend.

**Comment by moving-bits** [comment]
> @moving-bits Please review the changes especially in Route.

@bekuno 
It's a bit hard to say from this convoluted commit history, as even p/n-navigation in GitHub stucks at some point, but as far as I can see, the changes to `Route`, `RouteSegment` and `ManualRoute` seem to be ok. Thanks for tackling those.

**Comment by fm-sys** [comment]
Somehow there are displayed many unrelated changes in the PR that were introduced with other commits like aac5dc7eb94f0576b380206a3007def995de42a5.  Probably because you had merged masters into your feature branch instead of rebasing your changes onto master... 

But anyway, it shouldn't be a problem IMHO, and is probably difficult to solve now

**Comment by bekuno** [comment]
> Probably because you had merged masters into your feature branch instead of rebasing your changes onto master...

Correct. This was my "false click".

I plan to create the PR as new one and cherry pick my commits.

**Comment by bekuno** [comment]
> as far as I can see, the changes to Route, RouteSegment and ManualRoute seem to be ok. Thanks for tackling those.

Fine. 
So I can go ahead to finish/recreate the PR.

**Pull request closed without merging**
