### PR TITLE
add visit state toggle button to map's waypoint popup (fix #2592)

### LINKED ISSUE #2592: Easy setting of visited state to wpt from popup
What about setting visited state directly from wpt popup ? Button or checkbox ?

I did one multi today ... and I felt it uncomfortable to mark wpts by clicking edit, checking that checkbox than saving and getting back to map.

### PR DESCRIPTION
**Pull request by moving-bits**
added a toggle button to the map's waypoint popup:

image

(label switches from "set visited" to "unset visited" according to current state)

### CODE REVIEW

**Comment by Lineflyer** [comment]
Is it possible to have the new button leftbound, so that the popup does not get such wide?
Or maybe the same checkbox like in the waypoint edit?

**Comment by moving-bits** [comment]
> Is it possible to have the new button leftbound, so that the popup does not get such wide?
> Or maybe the same checkbox like in the waypoint edit?

The two buttons are on a separate row, so if there's not enough space, the button should start below the "note" label or even left to it. ("note" does not belong to the buttons but to the waypoint infos the lines before.)

**Comment by moving-bits** [comment]
> > Is it possible to have the new button leftbound, so that the popup does not get such wide?
> > Or maybe the same checkbox like in the waypoint edit?
> 
> The two buttons are on a separate row, so if there's not enough space, the button should start below the "note" label or even left to it. ("note" does not belong to the buttons but to the waypoint infos the lines before.)

See this screenshot made on a low res (emulated) device:

image

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
Agreed to be merged and tested within approx. next two weeks.
Set label `Fieldtest` as reminder.

**Comment by okainov** [comment]
As per screenshot it feels like really visually huge and attractive button. However `set visited` IMO is not really very often required action. I do click `more details` much-much more often.

Also, it it possible to have checkbox-like visual element instead of button? 

I would suggest to put it below, maybe as separated row after all the info, however it will make it even longer, so not really sure how feasible is it...

Can we make "more details" button to fit the width of the dialog so it's wider?

We definitely need UX guy here and in general for the app :(

**Comment by Lineflyer** [comment]
First tests show its working as expected but now the bug (listed somewhere here) comes in, that the icon is not updated instantly when returning to map. 
This will confuse users for sure as their change is not visible on map (only after closing/opening the map).

**Comment by moving-bits** [comment]
> First tests show its working as expected but now the bug (listed somewhere here) comes in, that the icon is not updated instantly when returning to map.
> This will confuse users for sure as their change is not visible on map (only after closing/opening the map).

This is #7695 - let's continue there for that one. I'll try to look into it.

**Comment by moving-bits** [comment]
> Also, it it possible to have checkbox-like visual element instead of button?

I'll look into it, see, if it can be done with reasonable effort. If possible, I would try to implement it visually in a way similar to the waypoint list (so: checkbox + "visited" label).

> I would suggest to put it below, maybe as separated row after all the info, however it will make it even longer, so not really sure how feasible is it...

I would not like to have it that way, as it would be consuming even more space + adding visual clutter.

> Can we make "more details" button to fit the width of the dialog so it's wider?

We could, but then the "visited" toggle would have to go into a separate line - see before.

**Comment by moving-bits** [comment]
> > Also, it it possible to have checkbox-like visual element instead of button?
> 
> I'll look into it, see, if it can be done with reasonable effort. If possible, I would try to implement it visually in a way similar to the waypoint list (so: checkbox + "visited" label).

It could look like this: (no implementation yet, just a visual prototype)

image

Not too bad, visually.

But: It would be breaking our regular workflows. On the waypoint edit mask, from which the user is used to the checkbox approach shown in the screenshot above, no change is permanent until you have confirmed them using the confirmation button in the upper right (check mark). - Whereas in this PR, if modified to using the checkbox approach, simply checking or unchecking would start the action. Not good...

As I do not want to introduce an extra confirmation button, and also do not want to have setting / unsetting the visited state using the dot menu, I would like to stay with the button implemented so far (as long as no other, better solution comes up). Using a button to directly start an action is standard UI.

**Comment by Lineflyer** [comment]
> But: It would be breaking our regular workflows. On the waypoint edit mask, from which the user is used to the checkbox approach shown in the screenshot above, no change is permanent until you have confirmed them using the confirmation button in the upper right (check mark). - Whereas in this PR, if modified to using the checkbox approach, simply checking or unchecking would start the action. Not good...

Correct me if I am wrong:
But the current implementation of the toggled button does also save directly, doesnt it?

**Comment by Lineflyer** [comment]
And generally:
I like the checkbox more than the button personally.

**Comment by moving-bits** [comment]
> Correct me if I am wrong:
> But the current implementation of the toggled button does also save directly, doesnt it?

Yes, it does. But that's what you would expect from a button. (But not from a checkbox itself, at least not in "older" UI like we use in c:geo - WPF or Win10 UI is different.)

**Comment by moving-bits** [comment]
> And generally:
> I like the checkbox more than the button personally.

Visually: I agree. But...

A different approach could be to create a smaller button having a checkbox icon on it (checked or unchecked according to state). Then it would be smaller, but still be a button.

**Comment by Lineflyer** [comment]
> Yes, it does. But that's what you would expect from a button. (But not from a checkbox itself,...

Mmh..I have no idea of UI concepts but for me its logical. In doubt I would change, close the popup and open again to see its still changed.
My thinking would be: Everything on popup needs no confirmation...so this item might work the same way...independently fro the way its looking.

Other opinions out there?

**Comment by moving-bits** [comment]
Maybe this approach works: use a labelled checkbox (as shown in the screenshot above) and save directly after setting or unsetting the check, but give a visual feedback to the use that the setting has been saved already (using a short toast message). Any opinions?

**Pull request merged**
