### PR TITLE
fix #12718: dont cut off var tab buttons

### LINKED ISSUE #12718: [Variables] Buttons are cut off
### Describe your problem!

A picture tells more than thousand words :) 

Screenshot_20220212_101712_cgeo geocaching

### How to reproduce?

Use a small screen or large font size... 

### Actual result after these steps?

Buttons are cut off. 

### Expected result after these steps?

The buttons should be ordered dynamically. This can easily be done with a AndroidX `CoordinatorLayout`. 

### Reproducible

Yes

### c:geo Version

NB2022.02.12

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #12718: dont cut off var tab buttons

### CODE REVIEW

**Comment by eddiemuc** [comment]
> Why not put everything in one `ChipGroup` instead of two? Would save some screen space when thinking about larger devices (e.g. tablets) 

I wanted to separate the "add" actions from the "other" actions. If you don't think this is meaningful (?) then one chipgroup would be enough indeed. What do you think?

**Comment by fm-sys** [comment]
Hm... As all buttons are related to adding/deleting variables I guess this separation is IMHO not really necessary.

This is how it looks when I turn my mobile to landscape: I feel like the space could be used better ;-) 

Screenshot_20220212_151837_cgeo geocaching_copy_585x270

**Comment by eddiemuc** [comment]
OK, PR was changed to one ChipGroup only. Looks now like this in portrait:

image

And like this in landscape:

image

**Comment by fm-sys** [comment]
The margin looks quite large currently. If we reduce it a bit, all buttons will probably fit into one line. But this is device specific anyway...

**Comment by moving-bits** [comment]
Funny that it uses different horizontal spacing between the buttons (see first line vs. second line in portrait mode). Any way to influence this?

**Comment by eddiemuc** [comment]
> Funny that it uses different horizontal spacing between the buttons (see first line vs. second line in portrait mode). Any way to influence this?

Your're right, margin definition is different for the delete button than for all others. I will fix this

**Comment by eddiemuc** [comment]
> The margin looks quite large currently. If we reduce it a bit, all buttons will probably fit into one line. But this is device specific anyway...

margin is set to 6dp right now. Changing it to 3dp gives us this:

image

**Pull request merged**
