### PR TITLE
replace icon-creation by ribbonizer by dedicated images (version 2)

### LINKED ISSUE #8896: ribbonizer does not work with adaptive launcher icons (from Android 8.0)
After changing our icon to an adaptive icon it does not show the "debug" overlay created by the Ribbonizer.
This addon seems not to be further developed - latest release is from August 2017.

Therefore I suggest to switch to another plugin.
I found easylauncher-gradle-plugin - should work for now, but also not in active development (latest from October 2018).

An alternative would be to have own images for the build flavers as described in https://stackoverflow.com/questions/19528063/android-app-icon-for-debug-and-release-mode.

Any ideas?

### PR DESCRIPTION
**Pull request by bekuno**
## Description

This is the other solution for #8896 described in #10408.
Instead creation a resourse tree for the buildTypes in the first version we use now image resources with dedicated names.

We have two variants of the images. For old devises below API 26 = Android 8 we have images with ribbons as shown in https://github.com/cgeo/cgeo/pull/10408#issuecomment-822053784 , for newer we use the adaptive icon. Here the icon background color is changed according the buildType.

## Details
- remove ribbonizer code
- add static ribbonized icons with own names for buildTypes rc (beta), nightly and debug
- add colored backgrounds for adaptive icons for the buildTypes above
- define separate appIcons for the buildTypes above
- set the appIcons for the buildTypes above in the "About c:geo" Windows

## Related issues
fixes #8896
prereq for upgrade gradle plugin to version 7.0

### App Icons adaptive
debug:
cgeo_background_blue
nightly:
cgeo_background_black
beta:
cgeo_background_red

### About c:geo Activity Icons adaptive
debug:
cgeo_about_blue
nightly:
cgeo_about_black
beta:
cgeo_about_red

@Lineflyer Please have a look at older devices if the icons are fine there.

### CODE REVIEW

**Comment by Lineflyer** [comment]
Thanks @bekuno for reworking it.
Somehow I liked the ribbons on your first attempt more, than altering our background color scheme..its a bit to much IMHO. What so you think?

**Comment by fm-sys** [comment]
> its a bit to much IMHO. What do you think?

I believe that the reason for a different background color is not comprehensible enough for everyone (especially for average betatesters). I would more like changing the "cgeo" text to something like "cgeo beta" or something like that inside the icon. IMHO that wouldn't be so intrusive but still more understandable to users...

**Comment by bekuno** [comment]
For the new implementation I tried to optimize the adaptive icon foreground image part with adding the banner, but this is not fine (was created outside the visibile area on rounded icons).

> I believe that the reason for a different background color is not comprehensible enough for everyone (especially for average betatesters). I would more like changing the "cgeo" text to something like "cgeo beta" or something like that inside the icon. IMHO that wouldn't be so intrusive but still more understandable to users...

Not easy to place.
Maybe a horizontal banner instead the diagonal ribbon?
Will try to create one based on https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/ic_launcher_foreground.svg

**Comment by bekuno** [comment]
Just quickly drawn as a principle picture:
grafik

**Comment by Lineflyer** [comment]
I also could not do it any better.
@pstorch   As you designed the new adaptive icons AFAIR, any idea/suggestion for these flavor icons? You seem to have the needed tools and knowhow :)

@fm-sys  You did those nice PlayStore screenshots...any idea or good tool around to make a nice icon?

**Comment by pstorch** [comment]
I used inkscape to edit the SVGs. I'm not a graphic designer, but sometimes experimenting with such tools.

As always, it is a matter of taste. For another app I also altered the background color to differentiate between the flavors 😉. I would prefer the orange background for the release version. But an explizit text has also some advantages. Hard to say what is the best.

**Comment by moving-bits** [comment]
Thanks @bekuno for trying to tackle this. Personally I would prefer a (horizontal) text banner over a changed background color, but I could live with that as well.

If you try to apply text to the adaptive icons, please keep in mind that depending on your launcher's settings the icon may be square, squircle or circle (see https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive), so the text should be pretty short and placed not too much off-center.

**Comment by Lineflyer** [comment]
@pstorch Feel free to give it a try.

I would be in favor of a colored text instead of a pure color change. A changed color would not be explanatory enough, e.g. for beta users which then change between the colors depending on if we are running a beta-phase or not. The text is self explanatory.

**Comment by fm-sys** [comment]
If wanted, I can try to design some sketches as well. Simple, modern and understandable - let's see what I can do here :)

**Comment by bekuno** [comment]
Code is changed to use configured foreground icon.
My proposal:
debug_icon
debug_about
beta
nightly

**Comment by Lineflyer** [comment]
Looks also OK to me.
Lets wait if any other proposals from @pstorch or @fm-sys come in and then let the majority decide.

**Comment by pstorch** [comment]
No proposals from me at the moment, sorry.
But there are already good ones here.

**Comment by bekuno** [comment]
> 
> 
> IMHO these ellipses look kind of last decade (but that's only my personal taste).

Oh nooo ...

> I have also created some (hopefully a bit more modern) drafts. Note, that they are only quickly drawn. If we agree on a specific design, I will draw them again neatly :)
> 
> **My personal favorite...**

This is also my favorite from your proposal.

**Comment by bekuno** [comment]
I would love to see an adaptive icon ic_launcher_foreground*.xml. We have already suche one for the background.
@pstorch As you created the ic_launcher_background.xml - What is the way from svg to xml (if possible)?

**Comment by pstorch** [comment]
@bekuno 

> @pstorch As you created the ic_launcher_background.xml - What is the way from svg to xml (if possible)?

That's done in Android Studio when you create a new drawable for the launcher icon. There you select the svg and AS creates the xml and bitmap images.

**Comment by Lineflyer** [comment]
My preference would be the last option which @fm-sys provided (besides the fact, that the used font is somehow looking strange). We should really document somewhere (if not documented already) which font looks like our "c:geo". I used it for the shirts but forgot. Will look it up.

**Comment by Lineflyer** [comment]
This zip file contains a TT-font, which should be almost matching our design font: https://www.dropbox.com/s/5yov6jhrnqneuwk/cgeo-tshirts_fonts_etc.zip?dl=0

Will check copyrights (if any) and store it in the repo.

**Comment by fm-sys** [comment]
> We should really document somewhere (if not documented already) which font looks like our "c:geo". I used it for the shirts but forgot. Will look it up.

The font called "232MKSD" and I used it for the icon proposals. While "c:geo" only uses lowercase letters, the upper case letters look kind of strange in that font. But we can use lowercase letters for "debug", etc. as well...

**Comment by bekuno** [comment]
> 
> 
> @bekuno
> 
> > @pstorch As you created the ic_launcher_background.xml - What is the way from svg to xml (if possible)?
> 
> That's done in Android Studio when you create a new drawable for the launcher icon. There you select the svg and AS creates the xml and bitmap images.

Yes, the Vector Asset Studio *can* help. (File ->New -> Vector Asset)
I tried to convert the foregroud image with bad success:
grafik

**Comment by fm-sys** [comment]
> > That's done in Android Studio when you create a new drawable for the launcher icon. There you select the svg and AS creates the xml and bitmap images.
> 
> Yes, the Vector Asset Studio _can_ help. (File ->New -> Vector Asset)
> I tried to convert the foregroud image with bad success:

I used the "new image asset" for displaying the different draft icon variants. Looking at you're PR, it seems like you use some kind of Inkscape internal format. IIRC there are different export options in Inkscape (but I haven't used Inkscape for a while)

grafik

**Comment by bekuno** [comment]
> 
> 
> > We should really document somewhere (if not documented already) which font looks like our "c:geo". I used it for the shirts but forgot. Will look it up.
> 
> The font called "232MKSD" and I used it for the icon proposals. While "c:geo" only uses lowercase letters, the upper case letters look kind of strange in that font. But we can use lowercase letters for "debug", etc. as well...

It is `232MKSDRoundMedium`.

From https://fonts.webtoolhub.com/font-n24418-232mksd-roundmedium.aspx?lic=1 :
~~~
Licensing Information
Copyright :Copyright (C) 2009 Maniackers Design / Masayuki sato All Rights Reserved. / www.mksd.jp
More Info :No additional information provided. 
~~~

**Comment by bekuno** [comment]
> I used the "new image asset" for displaying the different draft icon variants. Looking at you're PR, it seems like you use some kind of Inkscape internal format. IIRC there are different export options in Inkscape (but I haven't used Inkscape for a while)

I also until yesterday. Had to update them first.
My short test above was with the original foreground image, not with my changed one.
You can save from Inkscape also to "Normal SVG", maybe easier to prepare for the Vector Studio import.

**Comment by pstorch** [comment]
Ah yes, sometimes it is necessary to fiddle around with different options in Inkscape, so AS can properly import it. You can save it in a simplified SVG format for example. Somtimes also the size of the "page" in inkscape mattered.

**Comment by fm-sys** [comment]
> It is `232MKSDRoundMedium`.

Yes exactly the variant I had used for my drafts. Either I had a too low pixmap resolution or the capital letters realy look strange. Probably the first one, but to be honest I would prefer lower case letters anyway :)

**Comment by bekuno** [comment]
> It is `232MKSDRoundMedium`.
> 
> From https://fonts.webtoolhub.com/font-n24418-232mksd-roundmedium.aspx?lic=1 :
> 
> ```
> Licensing Information
> Copyright :Copyright (C) 2009 Maniackers Design / Masayuki sato All Rights Reserved. / www.mksd.jp
> More Info :No additional information provided. 
> ```

Update.
Source is http://www.mksd.jp/232mksd.html

A readme can be downloaded at this site.
English part:
```
For Maniackers Design
Fonts Usages.
All rights of the fonts and graphics are reserved by Maniackers Design. Maniackers Design does not have any responsibilities for losses by using the fonts.
You may use both free and shareware fonts freely for noncommercial personal purposes, such as creating a logo for a personal web site, free web design materials, goods or banners.
Please contact Maniackers Design before using the fonts for commercial purposes, such as for commercial products, stores or companies logos, TV, books and magazines, or CDs.
You may be charged for it. Maniackers Design would appreciate if you send us a sample of your artwork for our reference especially in commercial use.
Though Maniackers Design is ready to answer your questions, please try browsing the internet first. You could find the answers yourself.
Maniackers Design might not be able to answer the questions about Windows PC because we rarely use them.
Thank you.
```

**Comment by Lineflyer** [comment]
> For Maniackers Design
> Fonts Usages.
> All rights of the fonts and graphics are reserved by Maniackers Design. Maniackers Design does not have any responsibilities for losses by using the fonts.
> You may use both free and shareware fonts freely for noncommercial personal purposes, such as creating a logo for a personal web site, free web design materials, goods or banners.
> Please contact Maniackers Design before using the fonts for commercial purposes, such as for commercial products, stores or companies logos, TV, books and magazines, or CDs.
> You may be charged for it. Maniackers Design would appreciate if you send us a sample of your artwork for our reference especially in commercial use.
> Though Maniackers Design is ready to answer your questions, please try browsing the internet first. You could find the answers yourself.
> Maniackers Design might not be able to answer the questions about Windows PC because we rarely use them.
> Thank you.

What does it mean for us...noncommercial I would say.

Will add that to my recent PR.

**Comment by eddiemuc** [comment]
@Lineflyer 
> What does it mean for us...noncommercial I would say.

I would also say we are non-commercial. But to be sure I suggest sending them out our logo with their font used (like they request, although especially for commercial), that way they know about the usage and can complain if the are it otherwise

**Comment by Lineflyer** [comment]
> I would also say we are non-commercial. But to be sure I suggest sending them out our logo with their font used (like they request, although especially for commercial), that way they know about the usage and can complain if the are it otherwis

Lets first make sure it is that font after all.
@SammysHP  @mucek4  @rsudev  You might know?

**Comment by bekuno** [comment]
I am not satisfied with the conversion from svg to xml. The biggest visual problem is that the "sunken" effect of the letters is lost. Also the corner shaddow is gone.
The Android Vector Asset Studio does not know this effect (as can be seen in the error above), the website svg2vector declares that it is better (https://svg2vector.com/vector-asset-studio-errors), but here too the effect is swallowed up.

So it looks without the sunken effekt.
grafik
This is the original one:
grafik

Has someone another idea?

**Comment by jcklpe** [comment]
@bekuno linked me this ticket. I'd be willing to make a new vector based icon for c:geo, but I'd only do it if I were given enough leash to create new design. I think the current design is dated could be improved upon. In general I think the entire thing could do with a rebrand.

**Comment by Lineflyer** [comment]
Well, the adaptive launcher icon we use for c:geo is relatively new and I personally think its quite OK. This issue is only about creating some specialized icons for some build flavors.

Still I would be keen to see your idea for an c:ge icon in general. I think it should be still well recognizable for users.
For the app design itself you are perfectly right, that it needs renovation.

**Comment by bekuno** [comment]
I have created Issue https://github.com/cgeo/cgeo/issues/10522.
There we should discuss the problem for the adaptive icon.

I will continue in this PR with raserized images.

@jcklpe Feel free to present your design ideas in #10522.

**Comment by jcklpe** [comment]
@Lineflyer

>Well, the adaptive launcher icon we use for c:geo is relatively new and I personally think its quite OK. This issue is only about creating some specialized icons for some build flavors and the problems coming along with that (no one having enough experience to modify it).
>Still I would be keen to see your idea for an c:ge icon in general. I think it should be still well recognizable for users.
For the app design itself you are perfectly right, that it needs renovation.

I've started tossing out some ideas in a moodboard exercise in the thread linked by @bekuno 

To some degree visual design is a matter of context and taste. The c:geo icon might be fine but I think it could be a lot more interesting and it would be worth exploring those possibilities. I'm not going to force anything on anyone but I'd like people to engage in the collaborative creative process I try to model in that moodboard exercise. Interested to hear from people what the c:geo brand means to them, what it should evoke. 

And I think thinking in terms of the brand might be a good first step towards the work of the general UX. Branding is [CX](https://en.wikipedia.org/wiki/Customer_experience) and CX is part of UX. It can help provide the foundations for a broader holistic rethinking of how users experience an app.

**Comment by bekuno** [comment]
That's now my implemented proposal:
grafik

**Comment by bekuno** [comment]
The PR is ready for the next review/to merge from my site.

@Lineflyer Do you want to have that in release?

**Comment by Lineflyer** [comment]
lets put it onto master to allow testing how the icon is replaced wheb changing the installed build type.

**Comment by Lineflyer** [comment]
Used this PR in my debug build and the overlays look good IMHO.
Lets merge and check in nightlies and prior to next release.

**Pull request merged**
