### PR TITLE
fix part of #10661: basic vs advanced filter mode

### PR DESCRIPTION
**Pull request by eddiemuc**
fix part of #10661: basic vs advanced filter mode

### CODE REVIEW

**Comment by eddiemuc** [comment]
Implements a "basic vs advanced" switch at top of filter configuration activity. 

Since "cache type" filter is currently far too long, the "basic" filter doesn't really look good. This will be fixed in a separate PR.

**Comment by fm-sys** [comment]
Made a quick test in the emulator, but I come up with a total empty screen at basic, and it keeps remain (nearly) empty if switching to advanced. 

grafik
grafik

But then, if an add a new filter D/T/Type pops up as well. 





grafik


I think D/T/Type should only be taken oven if it actually "filters" (only a specific range/type(s) are selected)

---

Don't know if it's related, but I get following stacktrace if I press "Go!" while screen is empty:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 24284
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.widget.CheckBox.isChecked()' on a null object reference
        at cgeo.geocaching.filters.gui.CheckboxFilterViewHolder.createFilterFromView(CheckboxFilterViewHolder.java:125)
        at cgeo.geocaching.filters.gui.FilterViewHolderCreator.createFrom(FilterViewHolderCreator.java:104)
        at cgeo.geocaching.filters.gui.GeocacheFilterActivity.getFilterFromView(GeocacheFilterActivity.java:296)
        at cgeo.geocaching.filters.gui.GeocacheFilterActivity.finishWithResult(GeocacheFilterActivity.java:282)
        at cgeo.geocaching.filters.gui.GeocacheFilterActivity.onOptionsItemSelected(GeocacheFilterActivity.java:207)
        at android.app.Activity.onMenuItemSelected(Activity.java:4137)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1176)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by eddiemuc** [comment]
Suggested view for basic filter:
image

What do you think?

**Comment by fm-sys** [comment]
> What do you think?

Looks good 👍

Will this type filter layout also be used for advanced mode?

**Comment by Lineflyer** [comment]
Looks like a perfect approach.
Lets IMHO use it and see whether we find any optimizations later on...but that looks already quite straight forward and easy to use.

**Comment by eddiemuc** [comment]
> Will this type filter layout also be used for advanced mode?

Yes it will.

Ok then I will start fixing up the code base behind it...

**Comment by fm-sys** [comment]
@Lineflyer fo you agree that this is a suitable replacement for the current "global filter" (means we can remove/replace it)?

**Comment by moving-bits** [comment]
> What do you think?

Looks really good, like it 👍 

Only one slight change proposed: I would put the checkbox for Select all/none directly beside the label:

image

Otherwise it looks (at least to me) like having a dangling checkbox belonging to nothing.


Or put it in the same line as the headline, something like this - saves one line:

image

Or make it a slider (like we have in the PQ activity)

Maybe only label it "Select all" instead of "Select all/none"?

**Comment by fm-sys** [comment]
> Or make it a slider (like we have in the PQ activity)

I would IMHO stay with a ckeck box. To be honest, I've never seen a slider in any UI which activates all ckeckboxes below. In this use case, always a checkbox is used. 

But I agree, that all/none should be moved directly beside the label.

**Comment by Lineflyer** [comment]
Yes, I think we should go for that also to replace the current global filter, meaning to keep the menu item but fill it with this basic/advanced filter.

**Comment by eddiemuc** [comment]
Thanks for the feedback. Two comments:
* Moving "select all" in the headline would clash with the "advanced" view where in this place there are the delete and the drag button. If this is really wanted then I would ask for a separate issue because this is a lot of work on its own. I would for now place it aligned to the "right column" (and change text to"Select all" of course)
* Replacing global filter with this is the plan, but there's a lot of work to be done behind the scenes before this can really be carried out. Keep in mind that new filtering is still marked as experimental for good reason, and global type filter is very widely spread in c:geo code. Much coding and testing ahead of us.

**Comment by fm-sys** [comment]
> I would for now place it aligned to the "right column"

Totally fine 👍

> Replacing global filter with this is the plan, but there's a lot of work to be done behind the scenes before this can really be carried out. Keep in mind that new filtering is still marked as experimental for good reason, and global type filter is very widely spread in c:geo code. 

Take your time. We're just already looking forward ;-) 
And thanks for your really great work!

**Comment by eddiemuc** [comment]
One more thing wrt cache types:
as you can currently see when you open the cache type filter on master, we have 23 (!) cache types currently used in c:geo (see https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/enumerations/CacheType.java). In order not to overflow the filter, we have to "group" them together somehow. Also, layout-wise it makes sense to have an even number (if types are presented in two columns).

gc.com is doing the same, and using their logic plus some of my own (esp for the non-gc.com-types) I now implemented the following "groups" and "grouping rules":

image

Grouping Rules:
* "Traditional" will also find GCHQ and PROJECT_APE (same logic as on gc.com)
* "EVENT" will also find MEGA, GIGA, COMMUN_CELEBRATION, GCHQ_CELEBRATION, GPS_EXHIBIT, BLOCK_PARTY (same logic as on gc.com **except** that gc.com also finds CITO in this setting!)
* **Unlike** gc.com I created an OWN search field for CITO to make the displayed number of cache types even
* "Virtual" will also find "LOCATIONLESS"
* "User-Defined" will also find "Unknown" and "All" (but I expect/hope that the latter is never actually assigned to a cache)

Please let me know if you want different "groups" or "group rules". Alas, this can also easily be changed/adapted at a later point in time.

**Comment by eddiemuc** [comment]
(Edited last comment wrt cache type "all")

**Comment by fm-sys** [comment]
"Userdef" should IMHO be "Userdefined" / "User-defined". That's only four/five characters more and the length which fits into the screen differs for every device anyway. How should "def" be translated into different languages? I guess in other languages it will be way longer anyway so I hope the displayed string just gets shorted by "..." if necessary...

**Pull request merged**
