### PR TITLE
Remove trailing spaces in strings

### PR DESCRIPTION
**Pull request by UniQP**

### CODE REVIEW

**Comment by UniQP** [comment]
Should I also remove the space in the translations or should this be handled via crowdin?

**Comment by SammysHP** [comment]
This might invalidate the matching translations. Maybe there is a better way. @rsudev?

**Comment by rsudev** [comment]
It will invalidate the translations, but those can be easily re-attached (and checked for spaces at the same time). I can do that right after the import to crowdin.

**Comment by rsudev** [comment]
Rebased and merged locally.

**Pull request closed without merging**
