### PR TITLE
#9791 setting case in calculator

### PR DESCRIPTION
**Pull request by S-Bartfast**
Implementing filters for calculator input fields.

### CODE REVIEW

**Comment by bekuno** [comment]
ok to test

**Comment by moving-bits** [comment]
@bekuno 
Currently we have no Codacy checks (not only on this build) - can you check why, please?

**Comment by bekuno** [comment]
@moving-bits 
codacy has currently a maintenance period, see https://status.codacy.com/
`In Progress - Database Maintenance  - Scheduled for Jan 16, 10:00 - Jan 16, 19:00 (CET)`

**Comment by moving-bits** [comment]
@bekuno 

> codacy has currently a maintenance period, see [status.codacy.com](https://status.codacy.com/)
> `In Progress - Database Maintenance - Scheduled for Jan 16, 10:00 - Jan 16, 19:00 (CET)`

good to know. Thanks for researching it.

**Review by fm-sys — APPROVED** [review]
Great! I tested your code and everything works as expected. And using an `InputFilter` is codewise even better (I didn't know that something like this exists) then an `onTextChangeListener`.

Only thing which is totally unrelated to your PR:  Should we deactivate suggestions for the input fields? Thst can be done via `android:inputType="textNoSuggestions|textVisiblePassword"` according to SO for the best compatibility

**Comment by S-Bartfast** [comment]
> using an `InputFilter` is codewise even better (I didn't know that something like this exists) then an `onTextChangeListener`.

Yeah, I wasn't aware of it either till I started trying to work it out.

Turned out there already was a TextChangeListener associated with the edit text (it was being used to validate and update the resultant coordinate field in real time). At first I tried using this listener but it had the problem that it would 'listen' for text to be entered, examine the entered text and modify it if necessary.

Although this worked it had the problem that the updating would actually set new text causing the listener to be invoked a second time. It was easy enough to ignore the second call but it was still a little messy. The filter mechanism however  works perfectly and seems to have been made for pretty much exactly this purpose: 👍

**Pull request merged**
