### PR TITLE
fix #11488: make preimum caches available for basic members plus distance heuristic

### LINKED ISSUE #11488: Nearby search with filter "Premium = yes" gives empty list (at least for base members)
### Describe your problem!

With the introduction of the new filter and/or the new nearby search it is not possible to see PMO caches in the nearby list at least for base members.

Even for base members the information that a PMO cache is nearby might be interesting when caching together with premium members and to be able to log from there.

### How to reproduce?

Log in as base member.
Go to Nearby list, open the filter and select "Yes" for Premium caches.
List is empty even if PMO caches are around.

### Actual result after these steps?

List is empty.

### Expected result after these steps?

List should contain nearby PMO caches if Premium filter is not set to "No".

### Reproducible

Yes

### c:geo Version

2021.08.17-NB-240646f

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #11488: make preimum caches available for basic members plus distance heuristic

### CODE REVIEW

**Comment by Lineflyer** [comment]
Question from my side (not having tested this PR yet):
Are you using again the approximate indication we used to have (so those caches will be shown with the `~` in front of the distance)?

**Comment by eddiemuc** [comment]
> Question from my side (not having tested this PR yet):
> Are you using again the approximate indication we used to have (so those caches will be shown with the `~` in front of the distance)?

Yes. Was this disabled/discouraged before? (Because it was still in the code, I just fill it with my heuristic now instead of the parsed info from web site search result)

**Comment by eddiemuc** [comment]
(unfortunately I am unable to provide screenshots currently)

**Comment by Lineflyer** [comment]
> If the setting above IS checked, then the zoom level and shown area is adjusted such that all waypoints and the cache itself are visible (the cache is most likely not centered in this case)

It should be used indeed. My question was only to try to prevent you invented something new rather than reusing this method. Sounds perfect.

**Comment by eddiemuc** [comment]
@Lineflyer your question made me unsure whether I can merge this PR function-wise. Can I merge or is a change needed?

**Comment by Lineflyer** [comment]
All good. Merging for further testing.

**Pull request merged**
