### PR TITLE
rel to #11227: add logging for startup times

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #11227: add logging for startup times

### CODE REVIEW

**Comment by fm-sys** [comment]
Maybe @moving-bits can test the CI debug APK, so we do not need to merge it at all... The logging looks a bit too "verbose" to be included in a release version, isn't it?

**Comment by eddiemuc** [comment]
Fine for me, let's put this on hold. I label the PR accordingly.
(But I really just inserted two lines, only the code intent has changed)

**Comment by fm-sys** [comment]
> (But I really just inserted two lines, only the code intent has changed)

Ah, ok. Just had another look, and it's codewise totally file for sure. 

But it would have been a quite hard job to merge 133 lines of intent changes and 577 lines of code changes correctly without breaking anything... 😅

**Comment by eddiemuc** [comment]
Resolved conflicts with master after bottom navigation is not integrated, and added a time measurement for database initialization as well.

**Pull request merged**
