### PR TITLE
quick-load geocode from clipboard text

### LINKED ISSUE #12169: quick-load geocode from clipboard text
### Tell us your idea!

I often get messages like "I'm at cache GCxxxxxx, do you have a hint?" upon which I look up my cache notes in cgeo. The required steps to do that are:
1. Copy message
2. Paste message somewhere so i can select only the GC code (depends on the messenger)
3. In cgeo.main screen click search
4. Long-click the search field -> paste
5. On keyboard click the search icon

It'd be nice to have a more convenient way to load a cache whichs code is in clipboard.

### What solution would you suggest?

Next to the search field/in main menu add a "load from clipboard" action that takes the current clipboard and, of it's more than just a geocode, extracts a geocode from it, then loads that cache. This would be similar to the existing "from clipboard" function in defining a waypoint.
image

### Is there an alternative?

_No response_

### Additional Information

Geocode recognition should look at the enabled connectors to see what a geocode could look like to avoid false recognitions. E.g. with only gc connector enabled OC123 shouldn't be recognized as geocode.

### PR DESCRIPTION
**Pull request by ztNFny**
## Description
Improves loading a geocode from clipboard by "recognizing" geocodes in text.
There's 3 parts to this commit:
1. fixes to the pattern(s) used for recognizing a GC-code in URLs
2. extension of the existing functionality in "Search" activity to auto-fill the geocode field with a geocode from clipboard. This now works not just for plain geocodes but also geocode-urls (e.g. https://coord.info/GC123) and geocodes contained in text ("Check out GC123"), see https://github.com/cgeo/cgeo/blob/3e311ec09ffc46158781fa5572733639495b1d3f/tests/src-android/cgeo/geocaching/connector/gc/GCConnectorTest.java#L115 for some more text examples
image
3. add a "paste" button to the quicksearch field in main activity. The button only shows up if clipboard contains a geocode (either pure, url or in text) and directly loads that geocode
image

## Related issues
fixes #12169

### CODE REVIEW

**Comment by ztNFny** [comment]
Codacy complains about NPath complexity, but that was already bad before, nothing that could be solved as part of this PR.

**Comment by moving-bits** [comment]
> Codacy complains about NPath complexity, but that was already bad before, nothing that could be solved as part of this PR.

Is there some meaningful way to reduce NPath complexity for those two methods?
If so, it would be nice if you could dive into it and improve the quality of our code base (as time permits). 
Otherwise I propose to add something like `@SuppressWarnings("PMD.NPathComplexity") // split up would not help readability` as we have done in other places (where it was applicable) in the past.

**Comment by ztNFny** [comment]
I've very slightly decreased complexity in `onCreate` (it's way less complex than Codacy thinks somehow) and split `instantSearch` in 2

**Comment by moving-bits** [comment]
Search tab crashes if you have a text in clipboard containing a TB code, e. g. "Any news on TB9GB8G?"

**Comment by ztNFny** [comment]
> Search tab crashes if you have a text in clipboard containing a TB code, e. g. "Any news on TB9GB8G?"

fixed. Code was still using String.isEmpty() instead of StringUtils.isEmpty()

**Review by moving-bits — APPROVED** [review]
LGTM. Thanks for diving into this and for fixing the findings.

**Pull request merged**
