### PR TITLE
Fix #5038 - Request large heap

### LINKED ISSUE #5038: Try to minimize OOM problems by requesting larger heapsize
As discussed on IRC:
I would like to test if requesting a larger heapSize in our manifest could help minimizing the OOM problems (caused by large bitmaps and mapsforge library) for the time being.
I am aware it is no solution but still maybe helpful until we get more memory optimizations (like e.g. a new mapsforge library).

Reference:
http://developer.android.com/reference/androi/R.styleable.html#AndroidManifestApplication_largeHeap

I suggest to change it on `master` and do some comparisons on some devices.

### PR DESCRIPTION
**Pull request by Lineflyer**
Experimental change to test if it has any advantage/disadvantage on memory intense scenarios in c:geo.

Could someone check if the syntax is OK or reply if anyone does see a problem with it?

I will test and provide feedback based on the nightlies so we can decide to keep or revert.

### CODE REVIEW

**Comment by rsudev** [comment]
From inspection this probably will not compile as thos attribute conflicts with our minSdk AFAIK

**Comment by Lineflyer** [comment]
Good question.
I have read that it will only work out on Honeycomb+... but I did not read a hard API limit though.
Can you try to compile?

**Comment by mucek4** [comment]
It is possible to compile different versions. Just more work for deployment.

**Comment by rsudev** [comment]
Contrary to my initial short research it seems not to fail the build, therefore I'll merge it for testing. Please cross-check specifically if it creates problems on 2.x devices (shouldn't have any effect there).

**Pull request merged**
