### PR TITLE
[14502] for linear labs use numbers as waypoint marker, for all WPs show type icon as overlay

### PR DESCRIPTION
**Pull request by ztNFny**
implements the remaining items from #14502 per https://github.com/cgeo/cgeo/issues/14502#issuecomment-1676448955:

- for linear ALCs use emoji-numbers instead of puzzle icon. As those only cover 0-9 stage numbers > 10 stage are handled by substracting 10 from the stage count -> stage 10 is displayed as 0
- for all waypoints show the associated cache type as marker in top-left (if no custom cache icon (emoji) is set for the cache)

image

### CODE REVIEW

**Comment by moving-bits** [comment]
Thanks for diving into this. Two follow-ups:
- Will the numbering of stages be beginning with 0 or with 1? While using 0 is quite common in IT, it isn't in real life, so I would prefer starting numbering waypoints with 1. (But maybe it's already the case, haven't checked the source.)
- There are emojis for 10+ as well, so in the (relatively infrequent) case of lab adventures with 10 stages, you could use those emojis. (Haven't seen labs with more than 10 stages yet, though.)

**Comment by ztNFny** [comment]
> * Will the numbering of stages be beginning with 0 or with 1?

1-based, only stage 10 is displayed as "wrong" 0. 

> * There are emojis for 10+ as well,

only in the "number with circle"-style though. Using "number" for 1-9, then "number with circle" for 10+ seems kinda ugly and confusing. And I think in general the "number" emojis are nicer, especially as the "number with circle" ones are really small:
image


As there are never (until now) more than 10 stages and 10 stages don't happen so frequently (only mega/giga and sponsored labs) showing 10 as 0 is the better solution here imho as it produces a nicer result for 95% of labs.

**Comment by moving-bits** [comment]
agreed. Also I haven't seen a ten-stage _linear_  ALC yet in real life.

**Comment by ztNFny** [comment]
> Also I haven't seen a ten-stage _linear_ ALC yet in real life.

https://labs.geocaching.com/goto/dd8d0a80-92f8-401a-ae8d-2b644d10b3dd

**Comment by moving-bits** [comment]
Interesting. All ten-stage ALC I've seen so far were non-linear. Linearity may even make sense in this case, whereas otherwise it's mostly just a plain PITA, IMHO :-)

**Comment by fm-sys** [comment]
Maybe just display ➕ for stages >= 10?

**Comment by ztNFny** [comment]
> Maybe just display ➕ for stages >= 10?

imho "last digit" is better than "+":

- if there actually are more than 10 stages then 11=1, 12=2, ... which still guides the user through the order as opposed to +,+,+,..
- for a 10 stage lab both "0" and "+" will need to use to think for a moment what it means. Then he'll probably check the waypoints list, see that the icon means stage 10 and accept that. So equal in functional regard. But 0 looks more like the other icons, so why introduce a break?

**Pull request merged**
