### PR TITLE
Add OneTimeDialog for map quick settings (fix #9593)

### LINKED ISSUE #9593: Users missing map settings
Several mails on support mail from beta users 2020.12.22-RC:

- All the map settings are gone in the beta version?
- Why do I need to change hiding own caches now from the settings each time. It was better in last version where it was possible from the map menu!
- I can no longer change the routing between walk, drive. The menu is no longer where it was before.

Maybe it would be good to add a dismiss-able message box (didn't we introduce such generic function recently) when entering the map to explain, that all map customization has been moved to the quick settings and where they can be found?

### PR DESCRIPTION
**Pull request by moving-bits**
image

### CODE REVIEW

**Comment by fm-sys** [comment]
We might think about only showing the popup to users, who upgraded to the new c:geo version, but not for newcomers. 

@moving-bits what do you think? BTW, such differentiation has not yet been designed for one time messages so a small architecture adaption will be necessary...

**Comment by fm-sys** [comment]
> We might think about only showing the popup to users, who upgraded to the new c:geo version, but not for newcomers.

I can/would like to create a PR for it (end of this week)

**Comment by Lineflyer** [comment]
> I can/would like to create a PR for it (end of this week)

Sure, appreciated.

**Comment by moving-bits** [comment]
For reference: @fm-sys 

Currently detection of "new user" works by checking `Settings.getLastChangelogChecksum() == 0` in `SplashActivity`, but this value is overwritten by `Settings.setLastChangelogChecksum(checksum)` in `MainActivity:checkChangedInstall` and thus no longer available in the map activities.

We need either find a different way to recognize a new installation (maybe some other settings not yet set) or forward this info to the map activities after a fresh install.

**Comment by fm-sys** [comment]
I was thinking of a more generalized solution. For example detecting a fresh install and initialize all OneTimeMessages depending on their default show state (always, freshInstall, upgrade, never) which could be added as a third enum parameter...

**Comment by moving-bits** [comment]
Sounds promising!

**Pull request merged**
