### PR TITLE
OAuthPreference: fix status for non-OC services

### PR DESCRIPTION
**Pull request by okainov**
Instead of using hardcoded OC-only keys, get them dynamically

Fixes: #7184

### CODE REVIEW

**Comment by Lineflyer** [comment]
ok to test

**Comment by okainov** [comment]
@rsudev @UniQP @SammysHP @Lineflyer  Just a friendly reminder, any updates?

**Comment by Lineflyer** [comment]
I have no idea about the OAuth mechanism in c:geo, but @rsudev can probably check the change.

**Comment by Lineflyer** [comment]
@rsudev Friendly reminder

**Comment by okainov** [comment]
Rebased

**Comment by rsudev** [comment]
I was not aware that this part of #7170 was also published as a separate PR, so please see my comments over there.

**Comment by okainov** [comment]
Merged together with the rest of SU changes

**Pull request closed without merging**
