### PR TITLE
fix loading of available logtypes for TBs

### LINKED ISSUE #15747: Still trackable logging issues
### Describe your problem!

Users report, that there are still issues with trackable logging.
On sending trackable logs c:geo reports an error, but the log is posted online.
I tried to test this (with my owned trackable only for now) and can somehow reproduce (but slightly different behavior)

### How to reproduce?

- Search for a trackable secret code to open its detail page
- Select to compose a log
- Send a log

### Actual result after these steps?

- Starting the loggging view c:geo gives an error toast "Cannot fetch the needed data...."
- Sending the log c:geo presents an error toast "LOG ERROR (user=...." and afterwards "c:geo could not post the log. Please check online..."

Checking online I have seen different things:
- Trying to log a "discover" resulted in a "note" to be logged
- In other subsequent tests no log at all was posted online

### Expected result after these steps?

Logging should work without errors

### Reproducible

Yes

### c:geo Version

2024.05.28-NB

### System information

```text
Ticket 932400
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ztNFny**
fixes #15747

### CODE REVIEW

**Comment by eddiemuc** [comment]
Thanks for the fix!

**Comment by bekuno** [comment]
Retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
