### PR TITLE
set target SDK to 28

### PR DESCRIPTION
**Pull request by moving-bits**
Play store requires all existing apps to target SDK 28 to be still upgradeable beginning November 19 so let's start testing

### CODE REVIEW

**Comment by Lineflyer** [comment]
Wasnt there the problem, that this will break gmapsv1?

In this case I would suggest another approach:
1. Set target to 28 on gmapsv2 branch and test it
2. Try to tackle the listed bugs of gmapsv2 
3. At some point merge the new gmapsv2 to master

What do you think?

**Comment by moving-bits** [comment]
> Wasnt there the problem, that this will break gmapsv1?

Can't say. It compiles with GMv1, and the visual result is the same for me:

image

That is to say, that the map tiles were not visible for me before as well - my key does not seem to be valid for Google. There are no error messages regarding GM in Logcat for me.

**Comment by Lineflyer** [comment]
Before merging this, let us wait for next branching from `master`to `release` as mentioned in #7665.
Meanwhile I might give the debug.apk a testrun.

**Comment by bekuno** [comment]
Here is the site descriping the "behavior changes: apps targeting API level 28+":
https://developer.android.com/about/versions/pie/android-9.0-changes-28

**Comment by Lineflyer** [comment]
I did not come very far with testing the debug.apk from CI as seemingly these APK do not contain any of our keys (No Google Maps, No authorization towards opencaching). I also tested other debug.apk from CI with the same result. So this is independent of the targetSDK and I am wondering whether this is normal on the CI?

**Comment by moving-bits** [comment]
> Wasnt there the problem, that this will break gmapsv1?

It breaks when you set the "Compile SDK" to 28 - it's not compilable anymore then (which I encountered while testing the "keep GPS going" issue using a foreground service).

**Comment by Lineflyer** [comment]
Shall we merge this to `master` now to check the (unexpected) consequences and as a first step towards GMaps V2?

**Comment by jonas-koeritz** [comment]
Mapsforge does break on targetSDK 28. Upstream Mapsforge 0.11.0 seems to work with only minor modifications. I could create a pull request for that.

**Comment by Lineflyer** [comment]
Oh, I did not expect a problem with target28 and mapsforge. Do you know the cause?

Generally we could use mf0.11 but recently we rolled back to 0.91 due to performance issues. You might want to browse our issues for details.
I assume we will run into this again once we upgrade to 0.11.
Still we could do this, but then we should debug and solve this performance problem.

**Comment by jonas-koeritz** [comment]
See https://github.com/mapsforge/mapsforge/commit/b7b07619a6389886734acd5bcb8ae9b14dfce8c2 for reference, I currently do not experience any performance problems when running on targetSdk 27 and Mapsforge 0.11.0

**Comment by Lineflyer** [comment]
See #7494 for the task of upgrading to mf0.11 (You might want to include "Fix #7494" in your corresponding PR).

Additionally #7523 describes the performance problem with mf0.11

**Comment by jonas-koeritz** [comment]
I would say that the "bumpy zoom" has been there on 0.9.1 too, when zooming in, everything looked just like the screenshot on #7523. I'm going to test c:geo with mapsforge 0.11.0 a bit, currently it seems about as fast as before.

**Comment by Lineflyer** [comment]
retest this please

**Comment by UniQP** [comment]
@moving-bits Can you also increase the `compileSdk`?

**Comment by moving-bits** [comment]
> @moving-bits Can you also increase the `compileSdk`?

Done.

Also added  `<uses-library android:name="org.apache.http.legacy" android:required="false" />` to `AndroidManifest.xml` to fix #7841.

Result is compilable and both Google Maps and OSM show up. (Although a first regression comes up: #7854)

**Comment by moving-bits** [comment]
@mucek4 
Could you once again accept licence agreement for SDK 28, please?

from error log of last build:
 > Failed to install the following Android SDK packages as some licences have not been accepted.
23:15:44       platforms;android-28 Android SDK Platform 28
23:15:44    To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
23:15:44    Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

**Comment by bekuno** [comment]
Before switching to compileSdk/targetSdk 28 we should at first update Upgrade the support libraries.

Cite from
https://google-developer-training.github.io/android-developer-fundamentals-course-concepts-v2/unit-1-get-started/lesson-3-testing,-debugging,-and-using-support-libraries/3-3-c-the-android-support-library/3-3-c-the-android-support-library.html#versions :
~~~
As a general rule, use the most recent version of the support library for the API your app is compiled and targeted for, or a newer version. For example, if your app targets API 26, use the version 26.x.x of the support library.
You can always use a newer support library than the one for your targeted API. For example, if your app targets API 22 you can use version 25 or higher of the support library. The reverse is not true—you cannot use an older support library with a newer API. As a general rule, you should try to use the most up-to-date API and support libraries in your app. 
~~~

Let's start with version 7.1.1 .

**Comment by mucek4** [comment]
I am updating executor 3 with to latest Docker image. When it gets back online (and if it works) I have to build 4 and 5 too.

**Comment by moving-bits** [comment]
@mucek4:

> I am updating executor 3 with to latest Docker image. When it gets back online (and if it works) I have to build 4 and 5 too.

Hi mucek4, I don't know if you'd found the time to update cgeo-3 already, but currently build still fails on that CI with the following message:

> File /home/jenkins/.android/repositories.cfg could not be loaded.
> Checking the license for package Android SDK Platform 28 in /opt/android-sdk-linux/licenses
> Warning: License for package Android SDK Platform 28 not accepted.

(see https://ci.cgeo.org/job/cgeo%20pull%20request/2300/console)

**Comment by mucek4** [comment]
I did. Executor 3 should be the latest. I'll check tomorrow.

**Comment by moving-bits** [comment]
@mucek4

Thanks

**Comment by bekuno** [comment]
folow up the discussion in PR #7861

I got these errors - in the test suite:
~~~
> Task :main:compileBasicDebugAndroidTestJavaWithJavac
C:\Users\admin\StudioProjects\cgeo\tests\src-android\cgeo\CGeoTestCase.java:9: error: package android.test does not exist
import android.test.ApplicationTestCase;
                   ^
C:\Users\admin\StudioProjects\cgeo\tests\src-android\cgeo\CGeoTestCase.java:13: error: cannot find symbol
public abstract class CGeoTestCase extends ApplicationTestCase<CgeoApplication> {
                                           ^
... and so on ....
~~~

**Comment by bekuno** [comment]
A currently failing function here (not automatic tested) 
see https://github.com/cgeo/cgeo/issues/7860#issuecomment-533871209

**Comment by Bananeweizen** [comment]
retest this please

**Comment by Bananeweizen** [comment]
I've accepted the SDK28 license directly in the Jenkins build script (as it was done for all earlier licenses already). That way you can already test, even though the new SDK will be installed repeatedly in the docker image.

**Comment by moving-bits** [comment]
Created an issue regarding the tests failing due to missing package `android.test`: #7866

**Comment by moving-bits** [comment]
This PR has grown too much into a mixup of compileSDK, targetSDK and other changes, IMHO, therefore creating a separate PR, which only switches targetSDK and adds the one lib ref to make it compilable for targetSDK28.

**Pull request closed without merging**
