### PR TITLE
add FileProvider for sharing gpx files and images list (fix #7302) (fix #7255)

### LINKED ISSUE #7255: Context menu on image tab stopped working
##### Detailed steps causing the problem:
- Open cache details
- Swipe to image tab
- Click on an image

##### Actual behavior after performing these steps:
Nothing happens

##### Expected behavior after performing these steps:
Picture related context menu should open

##### Version of c:geo used:
2019.01.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

### LINKED ISSUE #7302: GPX export file sharing broken
Similar to #7255 we do also seem to have a problem on GPX export (probably with activated "Share after export" function).

Crash report from beta channel for 2019.02.17-RC

```
android.os.FileUriExposedException: 
 
  at android.os.StrictMode.onFileUriExposed (StrictMode.java:1958)
 
  at android.net.Uri.checkFileUriExposed (Uri.java:2356)
 
  at android.content.ClipData.prepareToLeaveProcess (ClipData.java:944)
 
  at android.content.Intent.prepareToLeaveProcess (Intent.java:10480)
 
  at android.content.Intent.prepareToLeaveProcess (Intent.java:10486)
 
  at android.content.Intent.prepareToLeaveProcess (Intent.java:10465)
 
  at android.app.Instrumentation.execStartActivity (Instrumentation.java:1616)
 
  at android.app.Activity.startActivityForResult (Activity.java:4564)
 
  at android.app.Activity.startActivityForResult (Activity.java:4522)
 
  at android.support.v4.app.FragmentActivity.startActivityForResult (FragmentActivity.java:842)
 
  at android.app.Activity.startActivity (Activity.java:4883)
 
  at android.app.Activity.startActivity (Activity.java:4851)
 
  at cgeo.geocaching.utils.ShareUtils.share (ShareUtils.java:21)
 
  at cgeo.geocaching.export.GpxExport$ExportTask.onPostExecuteInternal (GpxExport.java:172)
 
  at cgeo.geocaching.export.GpxExport$ExportTask.onPostExecuteInternal (GpxExport.java:110)
 
  at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.onPostExecute (AbstractAsyncTaskWithProgress.java:71)
 
  at android.os.AsyncTask.finish (AsyncTask.java:695)
 
  at android.os.AsyncTask.-wrap1 (Unknown Source)
 
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:712)
 
  at android.os.Handler.dispatchMessage (Handler.java:105)
 
  at android.os.Looper.loop (Looper.java:164)
 
  at android.app.ActivityThread.main (ActivityThread.java:6938)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

### PR DESCRIPTION
**Pull request by moving-bits**
add FileProvider for sharing gpx files (fix #7302)
tested against API 19, 22, 26

### CODE REVIEW

**Comment by moving-bits** [comment]
added the second fix to this PR, as both share a common base

**Comment by Lineflyer** [comment]
All good, but IMHO the PR should target branch `release` now if we agree on having it in the next upcoming release (which I would prefer).

**Comment by Lineflyer** [comment]
@rsudev Can you review and merge if ok?

**Comment by rsudev** [comment]
One small thing only: Some overly long lines.
And please rebase on and retarget for release.

**Comment by Lineflyer** [comment]
@moving-bits You if you find to to rebase then we could merge and test. IMHO this is the last real big functional regression. We also have the missing spinner on map and other regressions, but this seems to be the only known functional regression to be solved to be back in game.

**Comment by Lineflyer** [comment]
@rsudev Can you merge this change from release to master as well, so we have in the NB?

**Comment by Lineflyer** [comment]
oh..it is already....However in the NB the image tab is still unchanged (not working) for me.

**Pull request merged**
