### PR TITLE
update GC log smileys

### LINKED ISSUE #12461: Three text smileys flawed
### Describe your problem!

c:geo inserts the following flawed text smileys in cache logs:

`[}:]` but should insert `[}:)]`
`[:o]` but should insert `[:o)]`
`[B]` but should insert `[B)]`

All other smileys are correct.

### How to reproduce?

Log a cache and use the c:geo embedded smileys to insert them.

### Actual result after these steps?

These broken text smileys are not transformed into images by geocaching.com.

### Expected result after these steps?

**All** available text smileys should be transformed into images by geocaching.com.

### Reproducible

Yes

### c:geo Version

2021.12.24

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bekuno**
- Fix false smileys
- use same wording as GCLH

fixes #12461

### CODE REVIEW

**Comment by Lineflyer** [comment]
Just a question alongside;
Are the textual descriptions (e.g. "evil") used somewhere on the GUI?

**Comment by bekuno** [comment]
> Just a question alongside; Are the textual descriptions (e.g. "evil") used somewhere on the GUI?

Not until now.
But a PR for using it is in the pipeline.

**Comment by Lineflyer** [comment]
> But a PR for using it is in the pipeline.

:) 
I would not replace the icons in the menu but show it additionally or something like this.

**Comment by bekuno** [comment]
> > But a PR for using it is in the pipeline.
> 
> :) I would not replace the icons in the menu but show it additionally or something like this.

see #12471

**Pull request merged**
