### PR TITLE
rel to #12783: redesign image tab, add edit features for own images

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #12783: redesign image tab, add edit features for own images

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR, if merged, will add ONLY in development/nightly builds a second "Image" tab. It is meant to experiment with a new "image tab" look with possibility to directly compare it to the old image tab:

Existing:

image

New (current state, to be changed, see discussion in #12783):

image

**Comment by eddiemuc** [comment]
Update:

image

I will merge this later today if no one objects. As already said: will only be visible on dev and nightly

**Comment by Lineflyer** [comment]
Cool, I really appreciate these shadow features as it makes it easy to see/test the difference.

**Comment by moving-bits** [comment]
> Update:
> 
> I will merge this later today if no one objects. As already said: will only be visible on dev and nightly

Looks really promising, thanks for working on it!

**Pull request merged**
