### PR TITLE
replace the last old profile link (fix #9150)

### LINKED ISSUE #9150: Retirement of old profile page on gc.com
As listed on [release notes](https://forums.geocaching.com/GC/index.php?/topic/358816-release-notes-website-upcoming-retirement-of-old-profile-page/) gc.com will retire the old profile page.

I am not sure whether we use that one for any purpose (getting find count or whatever else).

Please kindly doublecheck if there is any dependency to avoid upcoming problems.

Old page: https://www.geocaching.com/my/default.aspx
New page: https://www.geocaching.com/account/dashboard

### PR DESCRIPTION
**Pull request by fm-sys**
see https://github.com/cgeo/cgeo/issues/9150#issuecomment-779318569

IMHO it does not worth to release a new version just because of this small fix. Anyway, if we plan a bugfix-release it's targeted to release branch....

### CODE REVIEW

**Comment by fm-sys** [comment]
Is there any trackable which is permanently in the hands of a different user (not the owner), so I can write a unit test for it? As currently the regex is not covered by the unit tests...

**Comment by moving-bits** [comment]
> Is there any trackable which is permanently in the hands of a different user (not the owner), so I can write a unit test for it? As currently the regex is not covered by the unit tests...

You can use one of mine, if you like: TB9NTJQ

**Comment by fm-sys** [comment]
> You can use one of mine, if you like: TB9NTJQ

The problem is that the trackable needs to be permanently in the hands of one and the same user. No dropped logs, etc.
 
But as it's a really minor functionality, it's probably also OK if we find no trackable which is permanently matching these criterias. This is probably the reason why there were no unit test before...

**Comment by moving-bits** [comment]
So you need a TB which is activated by user X, then gets grabbed by user Y and stays there?

**Comment by fm-sys** [comment]
Jep. Or leave out the unit test 😉

**Comment by bekuno** [comment]
> 
> 
> So you need a TB which is activated by user X, then gets grabbed by user Y and stays there?

E.g. a activated TB as a gift at a mega/giga event for supporter.
(I logged such a TB a long time ago, but the owner deleted then log)

**Comment by Lineflyer** [comment]
Are we talking about "spotted by user"?
Isn't it sufficient that user y has once "discovered" the trackable of user x?

**Comment by moving-bits** [comment]
@fm-sys 
I created such a TB: TB8WRVW

**Comment by fm-sys** [comment]
> 
> 
> @fm-sys
> I created such a TB: TB8WRVW

Great, thank you! By chance, I have also discovered another trackable right now, which also meets the criteria. TB: TB4BPQK

It hasn't received any future logs since 2013, so it should be a rather good test case. @moving-bits So we can either think about a different special test case for you're trackable, or it may travel again ;-)

**Pull request merged**
