### PR TITLE
rel to #12910: refactor html rendering, add description styles

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #12910: refactor html rendering, add description styles

This PR started primarily to support #12910. This might no longer be possible due to non-available libraries (see in issue). However, this PR still contains many HTMl rendering refactorings as well as a new possiblity to select a description render style:
* "Default": as today (including especially backgrpound coloring of text colors with low contrast)
* "Monochrome": all text colors are set to "text color" (white for dark mode, black for light mode), all color backgrounds are removed
* "HTML Source": the HTMl source is displayed instead of rendered listing

### CODE REVIEW

**Comment by eddiemuc** [comment]
image
image

Default:
image

Monochrome:
image

HTML Source:
image

**Comment by moving-bits** [comment]
@eddiemuc 

Failing builds on `master` are caused by this line:

```
20:07:11  /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/main/java/cgeo/geocaching/unifiedmap/googlemaps/GoogleMapsThemeHelper.java:199: error: incompatible types: incompatible parameter types in lambda expression
20:07:11              .setGroupDisplayMapper(s -> TextParam.text("**" + s + "**").setMarkdown(true));
20:07:11                                     ^
```
(probably some merge error)

Do you want to dive into it, or shall I give it a try?

**Comment by eddiemuc** [comment]
It's a merge error and the fix is trivial. I will provide it, give me some minutes...

**Comment by moving-bits** [comment]
retest this please

**Comment by eddiemuc** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by eddiemuc** [comment]
retest this please

**Pull request merged**
