### PR TITLE
rel to #12379: introduce calculated waypoint migration preview

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #12379: introduce calculated waypoint migration preview

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR, if merged, will introduce a "Calculated Waypoint Migration Preview" feature. It allows us to see how old calculated waypoints would be migrated to the new global cache variables without actually performing the migration. This allows for testing and discussion of the migration.

Feature is of course restricted to non-productive setups (development and nightly )

If one opens a waypoint list where there is at least one calculated waypoint (old method), a new button "Preview Waypoint Migration" appears:

image

Clicking it opens a simple Messagebox with information:
* Which waypoints would be due for migration
* Which global vars exist in the cache BEFORE migration
* How the coordinates of the migrated caches would be changed, and
* Which new global vars would be added by the migration

image

(Depending on how many calculated waypoints are in the cache, the text field can get quite long)

This PR is not primarily about the actually implemented algorithm for migration but should allow testing and discussion on this algorithm. As of now, following is implemented:
* All local variables in calculated coordinates, if there's already a var with same name and different formula on the cache, are appended with an index value to create a new unique var. E.g. `A` becomes `A2` (or if `A2` is also already in use then `A3` and so on)
* The var is replaced in formulas using this var using the syntax `($varname)` (this syntax will be recognized e.g. by the guided mode of the new variable calculator as a formula field due to the parenthesis).

**Comment by Lineflyer** [comment]
Will read through and answer next days and meanwhile think about what would be expected migration from my perspective.

**Comment by eddiemuc** [comment]
> Will read through and answer next days and meanwhile think about what would be expected migration from my perspective.

Let's move the overall discussion to #12379

**Comment by eddiemuc** [comment]
Putting to wip, please don't merge

**Comment by eddiemuc** [comment]
Process was changed: 

now whenever user opens a waypoint for editing containing legacy calculation coordinate data, a dialog like the following opens:
image

The user can choose to migrate the data as suggested, dismiss the old calculation data or postphone migration (cancel).

**Comment by eddiemuc** [comment]
In the example above, there was already a variable a defined in the cache, but no variables A, F or G

**Pull request merged**
