### PR TITLE
update libraries

### PR DESCRIPTION
**Pull request by bekuno**
Update used libraries compatible to the current supportLibraryVersion and compileSdkVersion
and minor syntax optimization.

List of updated libraries:
com.github.ben-manes:gradle-versions-plugin: 0.21.0 -> 0.24.0
com.gradle:build-scan-plugin: 2.3 -> 2.4.1
org.apache.commons:commons-collections4: 4.3 -> 4.4
org.apache.commons:commons-compress: 1.18 -> 1.19
com.fasterxml.jackson.core:jackson-databind: 2.9.9 -> 2.9.9.3
com.caverock:androidsvg: 1.3 -> 1.4
com.drewnoakes:metadata-extractor: 2.11.0 -> 2.12.0
com.squareup.okhttp3:okhttp: 3.12.2 -> 3.12.3
io.reactivex.rxjava2:rxjava: 2.2.8 -> 2.2.12
com.android.support.test:runner : 0.5 -> 1.0.1

### CODE REVIEW

**Comment by moving-bits** [comment]
> Update used libraries compatible to the current supportLibraryVersion and compileSdkVersion
> and minor syntax optimization.

Is this in preparation of our planned targetSDK change or based on current compile & target versions?
IMHO we should focus our efforts on getting the targetSDK 28 version up and running, and optimize our environment according to that version.

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
Yippie - the build errors are gone.

Not more:
~~~
There were 2 failures:
1) org.assertj.core.internal.cglib.transform.AbstractProcessTask 
2) org.assertj.core.internal.cglib.transform.AbstractTransformTask
~~~

Now:
~~~
OK (495 tests)
~~~

see #7319

**Comment by bekuno** [comment]
> > Update used libraries compatible to the current supportLibraryVersion and compileSdkVersion
> > and minor syntax optimization.
> 
> Is this in preparation of our planned targetSDK change or based on current compile & target versions?

This is for the current master.
I'm waiting for the migration of gmv2 branch to master.

> IMHO we should focus our efforts on getting the targetSDK 28 version up and running, and optimize our environment according to that version.

Sure.
Most of these changes are already reached their latest versions.
For more we have to change to compileSdkVersion, which we can do in a branch without gmv1.

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
I think we should at first update these libraries before raise the compileSdk 
and supportLibraryVersion as follow up to compileSdk.

**Comment by Lineflyer** [comment]
So shall we merge this now or is there any dependency to the issue you opened regarding the viewpagerindicator?

**Comment by bekuno** [comment]
The viepagerindicator problem will be later after raising the compileSdk version higher then current.
Please merge.

**Pull request merged**
