### PR TITLE
add offline stored counter to dashboard (fix #11936)

### LINKED ISSUE #11936: Total amount of stored caches missing
### Describe your problem!

In the old main activity the lists icon used to show the total amount of stored caches. This was IMHO very helpful to see whether there is some leftover to clean up or also just to see the utilization.

For beginner users it could be helpful to see the figure once they stored caches for the first time or also just to verify that the caches they wanted to store have been stored.

If its technically possible with the bottom navigation I vote for not losing this feature.

### How to reproduce?

see above

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

2021.10.19-NB

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by moving-bits**
(Less intrusive alternative to #11957)

## Description
Add a "offline stored counter" to the dashboard, added below all connector infos:

image

### CODE REVIEW

**Comment by bekuno** [comment]
We had tickets with performance problems regarding lists.
Therefore if would be good to have the counter (if possible separated for each connector) in the system information.
This is a must have, if we have no user visible counter.

**Comment by ztNFny** [comment]
> This is a must have, if we have no user visible counter.

There is a counter already though? The "all caches" list.

**Comment by bekuno** [comment]
> 
> 
> > This is a must have, if we have no user visible counter.
> 
> There is a counter already though? The "all caches" list.

Not at the first place.
Screenshot_20211030-140305_cgeo
But from the list menu there is it:
Screenshot_20211030-140328_cgeo

Should be unified, imho.

**Comment by ztNFny** [comment]
> Should be unified, imho.

I think that's because you can't save a cache to "History" or "All caches", those are virtual lists. They should probably not even show up in the pick a list menu then.

**Comment by Lineflyer** [comment]
I think we should still have some kind of count somewhere.
From support mail I know many experienced users (who probably don't need it) but also a lot of "non teccy" users who even struggle to understand the concept of multiple lists. 
Therefore informing the user, that something changed after they did some save/delete action or just to make them aware they have something stored by just showing the totals is IMHO still a good idea and wI would not like to loose this feature with the bottom navigation.

With respect to the implementation I still struggle. I still somehow think, that using the bottom nav capability to show such counter should be used. This fits into the concept, that we e.g. show a red alert dot on the "Home" if there is attention required (e.g. login failed). 
So my vote finally goes to the other PR instead of this one.

**Comment by Lineflyer** [comment]
retest this please

**Comment by moving-bits** [comment]
According to the recent discussion in #11936 a different solution is preferred (show number in list selector), so let's close here.

**Comment by SammysHP** [comment]
@ztNFny

> > Should be unified, imho.
> 
> I think that's because you can't save a cache to "History" or "All caches", those are virtual lists. They should probably not even show up in the pick a list menu then.

That dialog is also used as a list quick selection (long press on lists in bottom navigation).

**Pull request closed without merging**
