### PR TITLE
Wherigo: add one-time-message

### PR DESCRIPTION
**Pull request by eddiemuc**
Wherigo: add one-time-message

### CODE REVIEW

**Comment by moving-bits** [comment]
Can those messages contain HTML links or Markup?
Then we could add a link that links directly to the specific setting (using `cgeo-setting://prefkey` syntax, IIRC)

**Comment by eddiemuc** [comment]
> Can those messages contain HTML links or Markup? Then we could add a link that links directly to the specific setting (using `cgeo-setting://prefkey` syntax, IIRC)

As far as I can see OneTimemessage allows adding one link to description. I quickly looked into this but couldn't see an easy way to link to the Appearance page or any of the two relevant settings (custom menu entry or quick link item). @moving-bits maybe something to add at a later point in time?

**Comment by moving-bits** [comment]
c:geo allows to deep-link settings: For quick launch buttons this is `<a href="cgeo-setting://quicklaunchitems_sorted">...</a>`, and for custom menu button, it's `<a href="cgeo-setting://custombnitem">...</a>`. Haven't tested yet, though, whether it works with "advanced settings" disabled.

**Comment by eddiemuc** [comment]
> c:geo allows to deep-link settings: For quick launch buttons this is `<a href="cgeo-setting://quicklaunchitems_sorted">...</a>`, and for custom menu button, it's `<a href="cgeo-setting://custombnitem">...</a>`. Haven't tested yet, though, whether it works with "advanced settings" disabled.

I tried it. It links you to the "Appearance" settings page all right and scrolled to the right place (Quick Launch Items). When advanvced settings are disabled it still opens "Appearance" settings for you, but naturally you can't see the setting...

If those settings become so important in context of Wherigo, maybe we should make them "non-advanced" ones?

**Pull request merged**
