### PR TITLE
Use try with resources

### PR DESCRIPTION
**Pull request by UniQP**

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Now I'm confused. try-with resource is only available from level 19, but we have minimum 16, right? Shouldn't this PR build have failed?

**Comment by UniQP** [comment]
You're right. Maybe the CI doesn't check SDK 16.

Should I revert the commit?

**Comment by Bananeweizen** [comment]
Yes, I suggest to revert. I'm still not sure how to configure Android Studio for this. In Eclipse I got the error message about API level the moment I pulled the change.

**Comment by UniQP** [comment]
I reverted the commit on master.

**Pull request merged**
