### PR TITLE
rel to #10176: migrate brouter tile access to SAF

### PR DESCRIPTION
**Pull request by eddiemuc**
This will migrate access to brouter tile files (rd5 files previously located in segment4) to SAF

@moving-bits would appreciate your feedback

### CODE REVIEW

**Review by moving-bits — APPROVED** [review]
Hi @eddiemuc,
thanks for tackling this! I've installed it locally and played around with it a bit - seems to work as intended, as long as I use the standard "segments4" subfolder beneath ROUTING_BASE. If I use a different folder I need to comment out the check for `segmentDir` in `NodesCache`, lines 70-72.
IMHO we should merge your PR, and I'll be happy to do above's fix and some other cleanup I'd already prepared on my branch, and create a separate PR for that.
Again, thanks for taking the time to prepare the necessary SAF infrastructure and creating this PR to move the last missing bit of BRouter to SAF, highly appreciated!

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
Thanks @moving-bits , I will merge asap. Seems that ci didn't build this PR for some reason

**Comment by eddiemuc** [comment]
I don't know what is happening here. It seems Jenkins builds this PR (and others) in a loop without coming to an end.

Based on green build 5455 (https://ci.cgeo.org/job/cgeo%20pull%20request/5455/) I will now merge this

**Pull request merged**
