### PR TITLE
SimpleDialog multiselect: add selectall option

### PR DESCRIPTION
**Pull request by eddiemuc**
This PR adds a "selectall" option to multiselect dialogs opened using SimpleDialog. For example:

image

### CODE REVIEW

**Comment by Eldenroot** [comment]
I think it should be separated somehow... maybe a line after the "select all"?

**Comment by fm-sys** [comment]
Not necessary IMHO. The purposed solution looks perfectly fine at least to me...

**Comment by Lineflyer** [comment]
I also think the "select all" entry could look a little different (e.g. indented, cursive,..) to differentiate from the rest.

**Comment by eddiemuc** [comment]
I propose to put the entry between `<>`. E.g. `<Select All (21)>`. This would be the same design like the "new list" entry is separated from existing list entries in the "save caches" dialogs.

Additionally we can make font type italic if this is wanted.

Putting a line under the entry would be very complicated technically (due to restrictions in AlertDialog which is used underneath) so I would not do this.

**Comment by moving-bits** [comment]
Putting it into brackets sounds like a good idea, I would stay away from italic or other font attributes, though, to keep dialogs consistent.

**Comment by eddiemuc** [comment]
Found a bug in impementation, do not merge. It is surprisingly complicated to create a working "select all checkboxes" programatically in an AlertDialog. It is actually programmed kind of stupidly

**Comment by eddiemuc** [comment]
For comparison: this is what it looks like with <> and italic:

image

**Comment by eddiemuc** [comment]
...and this is what it looks like with just <> but no italic:

image

I will commit the version without italic for now but leave this PR open in case there's more discussion

**Comment by eddiemuc** [comment]
Bug is fixed too

**Review by Lineflyer — APPROVED** [review]
IMHO without italic and using <> is inline with other places, like for selecting lists to store a cache in, where we use `<New list>` as a selection item.

**Comment by eddiemuc** [comment]
@Lineflyer is it ok to merge this one to master? (due to upcoming next release)

**Comment by Lineflyer** [comment]
Yep, `master` please.

**Pull request merged**
