### PR TITLE
Update gradle plugin to 3.6.2 for AS 3.6.2

### PR DESCRIPTION
**Pull request by bekuno**

### CODE REVIEW

**Comment by bekuno** [comment]
@Lineflyer What is the normal/easy way to bring this change from release to master?

**Comment by Lineflyer** [comment]
Perform a git merge release on master. I can also do this tonight.

**Comment by Lineflyer** [comment]
Already done. 
Its a normal merge operation, should IMHO be described somewhere in our Wiki.

Assuming your default remote is the cgeo repo itself:
`git checkout release`
`git pull` <- to get the latest changes
`git checkout master`
`git pull`  <- to get the latest changes
`git merge release`

That should be it, if everyone followed to rules not to produce conflicting changes.

**Comment by bekuno** [comment]
Ok.
So there is nothing possible on the website.
(what I searched and not found :-) )

**Comment by Narrat** [comment]
Just for your information :)
If your `git --version` reports `2.23.0` or greater, then there are two new commands which are split out of `checkout`: `switch` for switching branches and `restore` for handling files. Which may reduce the confusion, which can arise with using `checkout`.
So `git checkout release` would be `git switch release.`

And maybe, if you didn't know: `pull` is short for `fetch` + `merge`. So the described workflow could also be done as:
```sh
git fetch origin
git checkout release
git merge origin/release
git checkout master
git merge origin/master
git merge release
git push
```
or
```sh
git fetch origin
git checkout master
git merge origin/master
git merge origin/release
git push
```
(if `origin` is the name of the main c:geo repo)
which of course doesn't update the local `release` branch. Just an example for a different approach. Or how more freely can be worked with branches if `pull` is not everytime involved.
But as I wrote: Just an FYI and in no way change your way if you're comfortable how it works currently :)

**Comment by Lineflyer** [comment]
@Narrat Thanks for the insights...I am also still learning git. :)

**Pull request merged**
