### PR TITLE
fix #14642: rework trackable log type logic completely

### LINKED ISSUE #14642: Default TB log type to "visited" on directly logging a TB
Reported on support:

When using search => TB => log TB, default logging action seems to be random for yet unknown TB. For some it seems to be "grab", for others "discover". Request is to set the default to "visited" when logging a TB from the TB-specific page (resp. last action, when TB is already known).

Ticket numbers: 345502, 838122, 791319, 655197

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #14642: rework trackable log type logic completely, fixing the problem with it

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
@eddiemuc 
Merging this to `release` conflicts with changes in 2ac2fa6594283b48abcbfb03a9ec9091962bfcf3, thus `release` cannot be merged into `master` automatically, and in this case of refacturing I do not want to mess around with those changes. Can you have a look at it?

I can either give you the git command sequence to do the merge in the original repo, or you could post here what changes to keep, then I'll continue the merge.

Two conflicts are reported in `LogTrackableActivity`:

---

```
private void init() {
<<<<<<< HEAD
    if (CollectionUtils.isEmpty(possibleLogTypesTrackable)) {
        possibleLogTypesTrackable = Trackable.getPossibleLogTypes();
    }
    logType.setTextView(binding.type).setDisplayMapperPure(LogTypeTrackable::getLabel);
    logType.setValues(possibleLogTypesTrackable);
    logType.setChangeListener(lt -> setType(lt, true));

    setType(typeSelected, false);
=======
    updateForNewType();
>>>>>>> release
...
```

---

```
private void postLog() {
<<<<<<< HEAD
    final TrackableLogEntry logEntry = TrackableLogEntry.of(trackable)
        .setAction(typeSelected)
        .setDate(date.getDate())
        .setLog(binding.log.getText().toString());

    logActivityHelper.createLogTrackable(geocache, logEntry, connector);

    Settings.setTrackableAction(typeSelected.id);
=======
    final LogTrackableTaskInterface taskInterface = new LogTrackableTaskInterface();
    taskInterface.loggingManager = loggingManager;
    taskInterface.geocache = geocache;
    taskInterface.trackable = trackable;
    taskInterface.typeSelected = logType.get();
    taskInterface.binding = binding;
    taskInterface.date = date;
    new LogTrackableTask(this, res.getString(R.string.log_saving), taskInterface, this::onPostExecuteInternal).execute(binding.log.getText().toString());
    Settings.setTrackableAction(logType.get().id);
>>>>>>> release
    Settings.setLastTrackableLog(binding.log.getText().toString());
}
```

**Comment by eddiemuc** [comment]
In first conflict keep the lower part (release).
In second conflict keep the upper part (HEAD)

If you feel uncomfortable doing this you can also send me the commands.

**Comment by moving-bits** [comment]
Thanks, have adapted accordingly.

Additionally, I have changed
- `typeSelected` in `postLog()` to `logType.get()`, 
- and `LogTypeTrackable::getLabel` to `tt -> TextParam.text(tt.getLabel())` in `onCreate()`.

`master` is updated now.

BTW: Command sequence would be:
- clone c:geo source repo (not your fork)
- `git checkout release`
- `git pull`
- `git checkout master`
- `git pull`
- `git merge release`
- (fix any conflicts and `git add` resolved files)
- `git commit -m "Merge branch 'release' (with conflict resolution)"`
- `git push`

**Comment by eddiemuc** [comment]
Thanks a lot!

**Pull request merged**
