### PR TITLE
fix #12073: sync adapter and layout, remove removal of nonfiltering filters when loading saved configs

### LINKED ISSUE #12073: Loading filters is wonky
### Describe your problem!

Loading a stored filter (in advanced mode) is unreliable, "randomly" only some elements of the filter are loaded.

The below video shows repeatedly loading 2 filters which were both created with the filter criteria "Cache Type" and "Status" visible. Filter settings are:
- "Found": in Status Found=Yes
- "Offline log": In Status Has Offline Log=Yes

Loading the filters none to all filter elements are loaded in a seemingly random pattern.

https://user-images.githubusercontent.com/1258173/140818406-ea04e17a-3cbb-42f5-b463-24e0e4067f27.mp4

 

### How to reproduce?

Create 2 filters with different settings
Load them

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

2021.11.07-NB

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #12073: sync adapter and layout, remove removal of nonfiltering filters when loading saved configs

### CODE REVIEW

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
CI seems to be bumpy again, I will try a few more times...

**Comment by eddiemuc** [comment]
retest this please

**Comment by bekuno** [comment]
@mucek4 
Please have a look at our CI.
None of the build are successfully; the green build are false positives.

**Comment by bekuno** [comment]
retest this please

**Pull request merged**
