### PR TITLE
UnifiedMap: Add map attribution (fix #14803)

### LINKED ISSUE #14803: [unified map] Add OSM map attribution
Map attribution should be added for VTM

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Adds map attribution for mapsforge online & offline maps (including combined map)

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by bekuno** [comment]
Please have a look at the CI results - there are new checkstyle and lint issues.

**Comment by fm-sys** [comment]
All checkstyle and lint issues are _not_ caused by this PR. It's caused by the fact that more lint/checkstyle issues exist on master compared with release.

**Comment by moving-bits** [comment]
> All checkstyle and lint issues are _not_ caused by this PR. It's caused by the fact that more lint/checkstyle issues exist on master compared with release.

which means that if you compile the same PR on `release` first, and then again against `master`, you'll get an increased lint/Checkstyle counter for the second build.

**Comment by moving-bits** [comment]
But in this case it's been an actual error of this PR (wrong order of import statement) - shouldn't this trigger the build to fail?
(Anyway, I'll update the PR to fix this.)

**Comment by bekuno** [comment]
> But in this case it's been an actual error of this PR (wrong order of import statement) - shouldn't this trigger the build to fail? (Anyway, I'll update the PR to fix this.)

The checkstyle error is in severity `info`, therefore no failing build.

See the log (https://ci.cgeo.org/job/cgeo-CI_PR-build/6492/console):
~~~
14:39:39  > Task :main:checkstyle
14:40:11  [ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/main/java/cgeo/geocaching/unifiedmap/tileproviders/AbstractTileProvider.java:5:1: Wrong order for 'cgeo.geocaching.unifiedmap.AbstractMapFragment' import. [ImportOrder]
14:40:12  Checkstyle rule violations were found. See the report at: file:///home/jenkins/slave/workspace/cgeo-CI_PR-build/main/build/reports/checkstyle/checkstyle.html
14:40:12  Checkstyle files with violations: 1
14:40:12  Checkstyle violations by severity: [info:1]
~~~

Should we change this?

**Pull request merged**
