### PR TITLE
fix conflict resolving for FilterNaming

### PR DESCRIPTION
**Pull request by murggel**
## Description
enhance conflict resolving for fixing filter-name

see comment https://github.com/cgeo/cgeo/pull/15515#issuecomment-2021573663

### CODE REVIEW

**Comment by eddiemuc** [comment]
LGTM, thanks for your help!

**Comment by murggel** [comment]
@eddiemuc 
Will move the functions from FilterUtils back to GeoCachefilter

Or should I create a separate PR for that?

**Comment by eddiemuc** [comment]
> @eddiemuc 
> I will move the functions from FilterUtils back to GeoCachefilter in this PR as well, or should I create a separate PR for that?

Whatever you prefer :-)
Thanks a lot!

**Comment by moving-bits** [comment]
Thanks @murggel + @eddiemuc for diving into it!

**Pull request merged**
