### PR TITLE
New GCLogAPI: enable logging of trackables

### PR DESCRIPTION
**Pull request by eddiemuc**
New GCLogAPI: enable logging of trackables

Follow-up on PR #14647: enable logging of trackables

### CODE REVIEW

**Comment by eddiemuc** [comment]
CI test error would fall into the area modified by this PR; but tests run locally. Thus I retry

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
Note: solution may be subject to bug when logging trackable actions other than "note" (requiring a trackingcode). See https://github.com/orgs/cgeo/discussions/77#discussioncomment-7094725

**Comment by moving-bits** [comment]
> Note: solution may be subject to bug when logging trackable actions other than "note" (requiring a trackingcode). See [github.com/orgs/cgeo/discussions/77#discussioncomment-7094725](https://github.com/orgs/cgeo/discussions/77#discussioncomment-7094725)

This seems to have been a temporary quirk, so let's test the extension for trackables in the nightlies as well.

**Pull request merged**
