### PR TITLE
make extended settings more prominent

### PR DESCRIPTION
**Pull request by fm-sys**
rel to #14603

### CODE REVIEW

**Comment by Lineflyer** [comment]
I am really impressed by the speed you provided this PR. :)
Please take a look into the discussion in #14606 before we implement this improvement though.

**Comment by fm-sys** [comment]
Well, I had coded this as visual demo anyway, and it felt wasteful to just throw it away. If we come up with an even better solution, I'm fine with it as well :)

**Review by moving-bits — APPROVED** [review]
Nice and clean solution, without the side-effects of using the action bar here. Thanks for diving into this.

**Comment by moving-bits** [comment]
Only thing that comes to my mind: Do we really need a "Settings" subheading (category) - the whole page is about settings. It looks a bit lost, IMHO.

**Comment by fm-sys** [comment]
> Do we really need a "Settings" subheading (category)

I added it to have a clean separation between the "filter" and the real preferences, and to make the filter toogle even more prominent. IMHO it looks way worse if it's just part of it. But that's just my personal taste...

**Comment by moving-bits** [comment]
How about this?

image

**Comment by fm-sys** [comment]
I don't have a strong opinion about this. Anyone else?

**Comment by eddiemuc** [comment]
> I don't have a strong opinion about this. Anyone else? 

Me neither

**Pull request merged**
