### PR TITLE
Variables tab icons

### PR DESCRIPTION
**Pull request by ztNFny**
changed the icons in variables tab in a way that imho they can work without texts. It's 2 commits, 1. to change the icons, 2. to remove the texts, so in case you oppose to removing the texts the first could still be used standalone.

related to https://github.com/cgeo/cgeo/issues/16341

image

### CODE REVIEW

**Comment by eddiemuc** [comment]
> ... in case you oppose to removing the texts...

In case the "you" relates to me (?): In like your approach a lot!

There's just this one button adding the "next free variable" (the "simple plus" button in your PR) where I would prefer if the variable to be added would be somehow made visible to the user. But that's maybe a detail.

I would merge this PR, I keep it open for a while to let others share their thoughts though.

**Comment by ztNFny** [comment]
> In case the "you" relates to me (?): In like your approach a lot!

yeah, i had actually typed that text in the issue and then realized it should go into a comment :-D

> There's just this one button adding the "next free variable" (the "simple plus" button in your PR) where I would prefer if the variable to be added would be somehow made visible to the user. But that's maybe a detail.

on that button I wanted to keep the text initially, then I realized there's no matching button style existing right now and decided it's not worth the effort to create it ;-) But of course you may disagree with that and re-add the text - feel free!

**Comment by ztNFny** [comment]
@eddiemuc if you want to re-add the text, should I drop this part of the change?
image

**Comment by eddiemuc** [comment]
> @eddiemuc if you want to re-add the text, should I drop this part of the change?

That would be great, thanks!

**Review by eddiemuc — APPROVED** [review]
LGTM, thanks for diving into this

**Pull request merged**
