### PR TITLE
update "Useful Apps"

### LINKED ISSUE #11530: QR Scanner App
We have linked a QR scanner app in c:geo. However, the app seems to be discontinued and is categorized as malware by some user reviews... 

Is anyone using the app or can/should we remove the link? 

Screenshot_20210825_005857_copy_432x460
Screenshot_20210825_005916_copy_432x305
Screenshot_20210825_005751_copy_539x2559

### LINKED ISSUE #12168: add "GCWizard" to Utility programs
### Tell us your idea!

https://gcwizard.net/ is a quite useful app for any kind of code table and the like, successor to GCC

I can take care of it if feedback is positive.

### LINKED ISSUE #12171: remove BRoute from Useful apps
BRouter is now integrated into c:geo for routing, the need to install it as a separate app has vanished. Thus it should be removed from the list of "Useful apps".

### PR DESCRIPTION
**Pull request by ztNFny**
Add GC Wizard, fixes #12168
Remove EOL Zxing Barcode Scanner, fixes #11530
Remove BRouter, it's integrated into c:geo, fixes #12171

### CODE REVIEW

**Comment by moving-bits** [comment]
Can you remove the "scan geocode" link on the home screen as well?

**Comment by ztNFny** [comment]
> Can you remove the "scan geocode" link on the home screen as well?

done

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

I disabled cgeo-5 to see how its going on cgeo-1

**Pull request merged**
