### PR TITLE
Create a "Getting Started" page to display on first installation

### PR DESCRIPTION
**Pull request by bekuno**
fix#4263 (1st impression in application is bad)

As before discussed in #7461 now separated the idea for an initial welcome screen.

I have created a "Getting Started" page that is displayed to the user the first time c:geo start after installation.
It is located in the "about c:geo" section, so the user can read it also later.
The initial text is split in 3 section - general, permission and platform information.
This could be extended if necessary, e.g. in German language to https://www.cachewiki.de/wiki/Hauptseite.

To make the cache platforms recognizable to other services, the corresponding section of the services page has been split.

The page is presented before the permissions questions (on map access).

Screenshot_20190423-233248

### CODE REVIEW

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
I would suggest to focus on "getting the app working" but not on the geocaching basics.
Therefore how about changing the sequence to:
1. c:geo device permissions
2. First steps in c:geo with link to service settings
3. Geocaching basics

I have some small improvement proposals for the text as well. I might probably push them to your branch/to this PR later today/tomorrow.

Anyway the approach is IMHO very good, not so much text but links to further information.

**Comment by Lineflyer** [comment]
I can not push the change to your local branch, probably as it is marked private.

Here is my proposal (base for discussion):
https://github.com/Lineflyer/cgeo/commit/42f06a11131a5b0c05fd2ed798ee210c65bd8620

**Comment by bekuno** [comment]
I'm not sure with the permission info. We use by definition:
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.NFC" />
but only for location and storage we need the explicit user agreement.
The camera is a hardware-feature.
    <uses-feature
        android:name="android.hardware.location.gps"
        android:name="android.hardware.camera"
        android:name="android.hardware.screen.portrait"
        android:name="android.hardware.nfc"
        android:name="android.hardware.touchscreen"

So I think we should reduce the info to these two points.

I suppose that when "Geocaching Basics" is after the Button to jump to the platform configuration then nobody will read this text. But I will present your sequence as next. How about to write the "Basics" sentence on top without a headline?

Screenshot_20190425-002113

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
Sure geoaching basics wont maybe readed if it is at last on this page. But from experience I think the platform autorization and permissions are more often asked on our support channels. Maybe because c:geo is not very often a beginners app.

If a potential user has no idea of geocaching, then our basics wont help so much anyway. I think this page is however OK for the time being and can be superseeded by something better and more complete in future.

**Pull request merged**
