### PR TITLE
update lint-baseline.xml

### PR DESCRIPTION
**Pull request by eddiemuc**
update lint-baseline.xml

### CODE REVIEW

**Comment by Lineflyer** [comment]
Whats wrong with the tests. I have already seen these `java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/StringJoiner` since yesterday evening short after some dependency updates have been merged.

**Comment by bekuno** [comment]
> 
> 
> Whats wrong with the tests. I have already seen these `java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/StringJoiner` since yesterday evening short after some dependency updates have been merged.

Im unsure if this is a CI or code problem.

~~~
12:40:05  cgeo.geocaching.CgeoApplicationTest > testSearchByGeocodeNotLoggedIn[android-23(AVD) - 6.0] [31mFAILED [0m
12:40:05  	java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/StringJoiner;
12:40:05  	at org.apache.commons.lang3.StringUtils.newStringJoiner(StringUtils.java:5522)
~~~

I yesterday updated the `org.apache.commons.lang3` from version 3.11 to 3.12.0.
There is no change for `.tringUtils.newStringJoiner`. 
It calls `java/util/StringJoiner`, which is part of the android java.

So it seems codewise unchanged.

@eddiemuc 
If you have time, please test if this PR will be fine if lang3 is downgraded back to version 3.11. Thanks.

**Comment by eddiemuc** [comment]
@Lineflyer, ,@bekuno, @mucek4 as already stated at https://github.com/cgeo/cgeo/pull/10100#issuecomment-799374804 I believe this is a problem with Jenkins slaves other than cgeo-1 not using JDK8 for executing the tests (because tests only fail when exedcuted on slaves other than cgeo-1 and the error indicates that a class used in JDK8 is not found).

I will now merge this PR which reverts the upgrade to commons-lang3 3.12.0 to 3.11 which seems to fix the problem

**Comment by Lineflyer** [comment]
cgeo-1 is AFAIR the dockerized slave created by @mucek4 and seems to be more up to date, than the others. I will open an issue to apply the same on the other slaves.

**Comment by bekuno** [comment]
> @Lineflyer, ,@bekuno, @mucek4 as already stated at [#10100 (comment)](https://github.com/cgeo/cgeo/pull/10100#issuecomment-799374804) I believe this is a problem with Jenkins slaves other than cgeo-1 not using JDK8 for executing the tests (because tests only fail when exedcuted on slaves other than cgeo-1 and the error indicates that a class used in JDK8 is not found).

@eddiemuc Good catch. I was not aware of the jre7/8 problem for this class and that the old slaves not using jre8.

**Pull request merged**
