### PR TITLE
make accuracy circle line configurable

### PR DESCRIPTION
**Pull request by moving-bits**
For consistency (and for being wished for by @MagpieFourtyTwo, IIRC) add color config for accuracy circles as well.

### CODE REVIEW

**Comment by MagpieFourtyTwo** [comment]
Great! Thy!

Nevertheless, seems as if it's not working properly yet, as changing the parameters for ``Accuracy circle fill color`` does not change anything at all (over here), while ``Accuracy circle line color`` primarily changes the circle fill color and opaqueness.

**Comment by MagpieFourtyTwo** [comment]
Moreover: The same values for the settings of ``Accuracy circle line`` and ``Circle fill color`` (which in fact both do change the circle fill color) lead to different results. Is this expected?

**Comment by moving-bits** [comment]
Hm, then it has never worked before - I simply replaced the hard-coded color constants with the values from preferences. Looks like I need to test this on a physical device, as in my emulated device I'll never get any accuracy circles... I'll try to look into it throughout the next days.

**Comment by MagpieFourtyTwo** [comment]
Thx! But, no stress, as it's already usable right now, one just has to know.  ;)
And, yes, now that it can be made more visible, the proximity circle starts to make sense again.

**Comment by MagpieFourtyTwo** [comment]
BTW: In Lockito you can set accuracy. And when setting up a route in Lockito, you will even get a proximity circle.

**Comment by moving-bits** [comment]
Aaarg - copy & paste type while working on retrieving the colors in `MapLineUtils` - have prepared a fix for it...

**Comment by MagpieFourtyTwo** [comment]
Thx!

**Pull request merged**
