### PR TITLE
Fix typos in comments

### PR DESCRIPTION
**Pull request by UniQP**
A small rebase exercise for @Bananeweizen ;-)

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Thanks a lot. I like the straight line in my local history view. :+1:

**Comment by UniQP** [comment]
Hm, looks like that email address of the commit changed :-(

**Comment by Bananeweizen** [comment]
I think when doing any operation in the web UI, github will use the name and mail of the user as given in the profile for creating new commits, not as given in the original commit. I see a similar thing in that the merges which I create for pull requests (of others) go by "Michael Keppler", while my own commits all go by "Bananeweizen".

**Comment by SammysHP** [comment]
In case of a rebase this is wrong and should be reported to GitHub. (Commits might come from different people, not necessarily from the one who opened the pull request.)

**Comment by UniQP** [comment]
For a linear history you can still fetch the branch of the PR and rebase/push by hand.

**Pull request merged**
