### PR TITLE
update contributors page

### PR DESCRIPTION
**Pull request by moving-bits**
Our contributors page has become out of sync lately. I updated the page, adding all contributors from 2018/19 according to github's contributors page, using their respective github user names.

### CODE REVIEW

**Comment by bekuno** [comment]
I'm not sure if we really should create a list for active contributors.

By the way, at least kumy & SammysHP should be in the actice contributor list.
Also other user where involved in this time, eg. following5.

@Lineflyer et al,
A more generally question: some users are not listed with there github names, e.g. rsudev. Was this planned?

I think that we could also thank to issue-creator and other supporter.

And at least. This is no longer a contributors page. ("strings_not_translatable")
How about to make the page with (translatable) headline?

**Comment by SammysHP** [comment]
See also #2386.

**Comment by moving-bits** [comment]
> See also #2386.

Nice stats on https://www.openhub.net, thanks for the link.
But I'm not too happy about linking to it, as it would create an additional dependency to a separate server (and one which currently has an expired security certificate which creates big colorful warning messages blocking access at first in the browsers I use...).

So maybe we should look for a different solution, preferably one that is included in c:geo, even better an automated one. (On the other hand: as new contributors do not emerge too frequently it might be enough to update this list once per year manually.)

**Comment by moving-bits** [comment]
> I'm not sure if we really should create a list for active contributors.

The current list is pretty much outdated, and if I understood the comments right, it's so since years. So I started to add at least the contributors from the last year and this year and put together a list of "2018/19 contributors" (without deleting the names of the other contributors).

> By the way, at least kumy & SammysHP should be in the actice contributor list.

I started by looking at the github commits from 18 and 19 in the c:geo repo, but for sure other contributors can be added as well.

> Also other user where involved in this time, eg. following5.

is included already

> I think that we could also thank to issue-creator and other supporter.

will add

> And at least. This is no longer a contributors page. ("strings_not_translatable")
> How about to make the page with (translatable) headline?

You mean the headline only, or subheadings as well? The tab label is already translated.

**Comment by bekuno** [comment]
> > And at least. This is no longer a contributors page. ("strings_not_translatable")
> > How about to make the page with (translatable) headline?
> 
> You mean the headline only, or subheadings as well? The tab label is already translated.

Also subheadings, if possible.

**Comment by Lineflyer** [comment]
> @Lineflyer et al,
> A more generally question: some users are not listed with there github names, e.g. rsudev. Was this planned?

In the passt users added theirselves sometimes, or added such kind of links/names after they have been added. So for the existing it is fine, but we might also remove that if we e.g. decide to apply a commong source / automation of this.

**Comment by moving-bits** [comment]
> > > And at least. This is no longer a contributors page. ("strings_not_translatable")
> > > How about to make the page with (translatable) headline?
> > 
> > You mean the headline only, or subheadings as well? The tab label is already translated.
> 
> Also subheadings, if possible.

Done - subheadings, roles and parts of the text are translatable now.
Layout for the parts is the same as on the first "about c:geo" page (version / help).

**Comment by Lineflyer** [comment]
I appreciate, that the contributors list gets updated. While not having a fixed process for it, its IMHO quite OK to decide case by case to add/modify the list for now.

I will therefore merge this and doublecheck afterward based on my knowledge of the project history and maybe modify something.  Also all others: If you miss someone feel free to submit your change.

**Pull request merged**
