### PR TITLE
rel to #14547: auto-group-function for waypoints to cache on map using markers

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #14547: draft for auto-group-markers

### CODE REVIEW

**Comment by ztNFny** [comment]
Mixing this with list markers is a bad idea imho.

**Comment by eddiemuc** [comment]
> Mixing this with list markers is a bad idea imho.

It will only intermix if you have two or more list markers for one cache (because the cache is in two or more lists with marker). Then it get's strange anyway because it is undefined which list markers are the two "selected one's" for display, and which one is left or right. 

I personally use at max one list marker per cache only. In this case there's no mixup

**Comment by ztNFny** [comment]
Well, i use more... 
It'll be quite confusing to have icons with different meaning in the same place.
Also this feature should be optional if it's added at all.

**Comment by eddiemuc** [comment]
> this feature should be optional if it's added at all.

Full agreement. This PR is definitely not merge-ready

**Comment by eddiemuc** [comment]
For what it's worth: this PR would now be ready for merge.

It introduces a new setting:
image

Setting is disabled by default.

If enabled then automarkers are generated on waypoints and cache they belong to on map view (only):
image
image

Marker is chosen via hashcode from an emoji set consisting of all fully opaque circles and square/rectangle symbols:
image
image
image

However, this topic seems to be somewhat contraversal, so I'll leave it at that for now

**Comment by ztNFny** [comment]
See https://github.com/cgeo/cgeo/issues/14547#issuecomment-1694612295 for why i think this PR is a no-go in terms of UX

**Comment by eddiemuc** [comment]
Team consent seems to move in direction of "cache star lines", so I am closing this PR

**Pull request closed without merging**
