### PR TITLE
reset color value to original value on cancel (fix #8681)

### LINKED ISSUE #8681: Change to line color accepted although cancelled
User report for 2020.07.26-RC:
- Go to Settings - Map
- Open color picker for one of the lines
- Click on a new color (which is then indicated in a circle instead of square)
- Press "Cancel"

Result:
The menu still shows the old color, however after leaving and entering the Map settings the cancelled selection is active

Expected:
Don't change the color if the user cancels the dialog.

### PR DESCRIPTION
**Pull request by moving-bits**

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
FYI: Added branches `release` and `cgeo-legacy` to be analyzed by Codacy.

**Comment by Lineflyer** [comment]
retest this please

**Comment by moving-bits** [comment]
> FYI: Added branches `release` and `cgeo-legacy` to be analyzed by Codacy.

Thanks. I was already becoming desperate why CI doesn't like my PR anymore :-)

**Comment by Lineflyer** [comment]
Thanks @moving-bits 

Please feel free to merge release changes back into master on short term after merging a PR to `release`.
So we ensure to keep master always inline with release to avoid conflicts later on, when merging branches.
All changes on `release` need to be contained on `master` to ensure the ability to fast-forward `release` to `master` later on.

I mean, after you merged/commited something to `release`:
```
git checkout master
git merge release
```

Already done for this PR content.

**Pull request merged**
