### PR TITLE
Fix Icon size in lists different with/without overlay (fix #5193)

### LINKED ISSUE #5193: Icon size in lists different with/without overlay
In releas version 2015.09.15 there is a remaining bug in the frontend design:
Icons with overlays are larger as icons without overlays.

### PR DESCRIPTION
**Pull request by moving-bits**
Fixes the two causes for ragged display in cache list:
- fix different icon sizes (by calculating inset padding at runtime to respect the actual scaling)
- always reserve space for offline marker in cache list (show transparent marker if needed)

This fix is also a prerequisite for PR #7577.

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
Looking at your screenshot in #5193 I do now see, that the overlays are actually shown outside of the cache icon itself and no longer overlapping it. Is this intentional?
I am fine with that in general, I only fear, that the total icon size will increase in lists and map?

**Comment by moving-bits** [comment]
PR adapted to the changes in PR #7775

**Comment by Lineflyer** [comment]
Lets test this out as next step.

**Pull request merged**
