### PR TITLE
rel to #16430: move addObserver from onstart to onresume to match removeObserver in onPause

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #16430: move addObserver from onstart to onresume to match removeObserver in onPause

### CODE REVIEW

**Comment by eddiemuc** [comment]
I believe that the exception in https://github.com/cgeo/cgeo/issues/16430#issuecomment-2533969389 is caused by the mapsforgeFragment's state moving from PAUSED back to RESUME and then again to PAUSE. In the last change, the observer would be removed already (by previous call to PAUSE) and not been added again in the meantime (because it was done n onStarted instead of onResume()), leading to observed exception.

I cannot reproduce the error case though, so this is a bit guessing.

@moving-bits can you please double-check the change?

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
failng build is unrelated

**Comment by murggel** [comment]
I can reproduce a crash on the map after resume as well, but I am not sure,  if it is the same error-message.
But I can test with your PR tomorrow .

**Comment by murggel** [comment]
> I can reproduce a crash on the map after resume as well, but I am not sure,  if it is the same error-message.
> But I can test with your PR tomorrow .

With this PR, the map was often frozen after switching back to cgeo map state.

So unfortunately not really an improvement.

**Comment by eddiemuc** [comment]
> > I can reproduce a crash on the map after resume as well, but I am not sure,  if it is the same error-message.
> > But I can test with your PR tomorrow .
> 
> With this PR, the map was often frozen after switching back to cgeo map state.
> 
> So unfortunately not really an improvement.
> 

Then it might be something more tricky to solve

**Comment by eddiemuc** [comment]
> And just catching the exception as a quick and dirty fix?

Sure we can try that. Don't know what happens then though

**Comment by eddiemuc** [comment]
I can reproduce the problem reliably so far on my physical phone with following steps:
- open live map
- make sure that mode is unified map with mapsforge adapter
- make sure that an offline map is selected 
- change the app (in my case In am opening Whatsapp on my phone)
- switch back to c:geo

--> cgeo app freezes, I have to restart 

Unified map vtm seems to work fine in same scenario. I would suggest this as a workaround for users on support for now.

**Comment by bekuno** [comment]
retest this please

**Pull request merged**
