### PR TITLE
NewMap: Add long-tap context menu for caches/waypoints (rel. to #13176)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Adds a "long tap" context menu for caches/waypoints on map, providing (up to) the following items:
- append to route
- prepend to route
- remove from route
- remove from route end
- remove from route start

This allows to add a cache/waypoint multiple times to a route, specifically as both start and end point to create a round-trip.
Long tap on a cache/waypoint will now always trigger this context menu, no longer auto-toggle route item (as discussed in related issue among others.)

Implemented for `NewMap` only currently, to gather some feedback.

|Screenshot 1|Screenshot 2|
|---|---|
|image|image|

Screenshot 1: Cache is not yet part of the route, so allow to append or prepend to route.
Screenshot 2: Cache is part of the route (at the end), so allow prepend or remove.

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by fm-sys** [comment]
Nice, although it requires one more click. Imagine adding 50 caches of a power trail to individual route. 50 vs 100 clicks can make a huge difference. 

Maybe we can show the popup only if the cache is already part of the route? 

|_Selection options_|
|-|
Remove from {start/pos x/end} (show multiple times for each time it is part of the route) 
Add to start
Add to end

**Comment by moving-bits** [comment]
> Maybe we can show the popup only if the cache is already part of the route?

I'm a bit undecided about this one. For sake of consistency one could argue that it should be always a long-tap (also for non cache/waypoint-items of an individual route). This would also prevent users from creating an individual route unknowingly (we have this on support regularly).

OTOH it sounds reasonable and intuitive enough to give it a try.

@cgeo/team: More opinions?

> Imagine adding 50 caches of a power trail to individual route

For this I could image a cache list function: "Add all (selected) caches to individual route" and then do a route optimization.

**Comment by fm-sys** [comment]
I guess it wouldn't make much difference in terms of complexity and would at least be consistent. Although I agree it's probably a rare case...

**Comment by moving-bits** [comment]
Added item removal from specific position in route:

|(1)|(2)|(3)|
|---|---|---|
|image|image|image|

Created a star-shaped route, always returning to the center, and finally removed the center from start of route to better explain different scenarios:
1. Tapping on center point, it lists "Prepend to route" and the several positions this point is part of the route.
2. This "extension" is at position 2 of the route and can be appended or prepended to it (or removed from that position).
3. The starting point can be either removed (from start) or appended to the route.

Order of possible menu items is:
- Append to route (as default action)
- Prepend to route
- Remove from start
- Remove from position xxx
- Remove from end

**Comment by moving-bits** [comment]
@fm-sys @eddiemuc 
I could need some help here: I'm trying to implement the new long tap functions for individual routes for UnifiedMap. The function itself is working, but the route line is not updated on the map. How can I trigger the `IndividualRouteLayer` to update its contents?

(If this is an explicit method to call, I would need to wrap it in a method implementing the interface `IndividualRoute.UpdateIndividualRoute`, and pass this as parameter to the call of `MapUtils.createCacheWaypointLongClickPopupMenu()` in `UnifiedMapActivity.handleTap()`.)

**Comment by fm-sys** [comment]
> Order of possible menu items is:
> 
>     Append to route (as default action)
>     Prepend to route
>     Remove from start
>     Remove from position xxx
>     Remove from end
>

One could argue whether "remove" should be listed above add elements, so it is nearer to reach after long click. 

> @fm-sys @eddiemuc
> I could need some help here: I'm trying to implement the new long tap functions for individual routes for UnifiedMap. The function itself is working, but the route line is not updated on the map. How can I trigger the `IndividualRouteLayer` to update its contents?

No need to call the layer directly, but you need to inform the view model about the changed data. This can be done e.g. via `UnifiedMapViewModel.getIndividualRoute().notifyDataChanged()`. The ViewModel can be accessed from everywhere via `new ViewModelProvider(activity).get(UnifiedMapViewModel.class);`, or some classes hold the view model instance as private field.

**Comment by moving-bits** [comment]
Thanks @fm-sys for the pointer, it's working now.
Have swapped "add" and "remove" positions as well.

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
