### PR TITLE
test for #6721

### PR DESCRIPTION
**Pull request by pstorch**
I want to see which import step message is missing for GPXImporterTest.testImportOcGpx().

### CODE REVIEW

**Comment by pstorch** [comment]
@kumy are both test devices active?

**Comment by kumy** [comment]
No, only one until our last test.

On September 25, 2017 6:47:13 AM GMT+02:00, Peter Storch <notifications@github.com> wrote:
>@kumy are both test devices active? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/pull/6739#issuecomment-331776143

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pstorch** [comment]
@kumy can you enable the second? I want to see this test fail.

**Comment by kumy** [comment]
I ll do this evening.

On September 25, 2017 12:01:32 PM GMT+02:00, Peter Storch <notifications@github.com> wrote:
>@kumy can you enable the second? I want to see this test fail.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/pull/6739#issuecomment-331835297

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
@pstorch done.

Jenkins please test this

**Comment by pstorch** [comment]
retest this please

**Comment by pstorch** [comment]
no error :thinking: 
I'll try the other PR again

**Comment by pstorch** [comment]
let's try it against master branch.

**Comment by pstorch** [comment]
retest this please

**Comment by pstorch** [comment]
retest this please

**Comment by pstorch** [comment]
I'll close here, it didn't gave me any insights.

**Pull request closed without merging**
