### PR TITLE
Feature/7817 add location to log template menu

### PR DESCRIPTION
**Pull request by nmrsmn**
## Description
Added the [LOCATION] placeholder to add to signatures, log templates and log entries.

## Related issues
#7817

### CODE REVIEW

**Comment by Lineflyer** [comment]
ok to test

**Comment by nmrsmn** [comment]
> Usually c:geo holds a GPS lock only if needed (e.g. on map). Did you test how this behaves when the location is stale? E.g. open map to get location, then open the log dialog, move 100m -> what do you get?
> Or start c:geo, select cache from list view without going to map, how accurate is the location?

I’ve killed the app, started it back up, went to my stored caches and tried to log one of the stored caches. The location was correct and spot on for me. I’ve also tested it using the nearby function. 

I haven’t tested opening a log dialog and then move, but what do you expect to happen? Do you expect the log message to update when you move? If so did you consider people that are logging as they move to the next one? If they type slow or they edit their message, which takes some time, the location might change and isn’t the right location anymore.

**Comment by ztNFny** [comment]
> I haven’t tested opening a log dialog and then move, but what do you expect to happen?

I'd expect it uses the coordinate that's "current" when pressing the button. And "current" in this case is probably "last known" - so it might be stale

>  Do you expect the log message to update when you move?

Of course once inserted nothing must change.

**Comment by ztNFny** [comment]
btw, maybe it also makes sense to show such a dialog to be able to select a coordinate format? Currently it always returns it as DMM (using GeopointFormatter.Format.LAT_LON_DECMINUTE)

**Comment by nmrsmn** [comment]
@ztNFny I'm not sure how to handle the formatting dialog in case you added the `[LOCATION]` placeholder to your signature for instance (or even when you've added it to a log template in settings), since those placeholders are being replaced upon starting a new log visit. 

A dialog is technically possible when selecting the location placeholder from within the `LogCacheActivity`, but at this moment all the `LogTemplate` implementations need to return a `String` used replacement that is being applied upon clicking that item, so at this moment a dialog isn't possible. I'm confident we can work something out, but is this still in the scope of this "beginner" issue then? Isn't this a good "first" step on which we can expand upon? 

Also, the `LogCacheActivity` isn't aware of any location updates like the `AbstractDialogFragment` is. I'll add that to make the location updates work and prevent the user from adding stale location.

**Comment by ztNFny** [comment]
>  I'm confident we can work something out, but is this still in the scope of this "beginner" issue then?

I'm actually quite confused this was marked as a "good first issue". Imho it's quite a complex thing due to coordinate formats, figuring out what's the right location and possible delays.

> Also, the LogCacheActivity isn't aware of any location updates like the AbstractDialogFragment is.

I wonder what the battery impact of that is. But then again not too much time is spent on the log dialog probably ...

>  I'm not sure how to handle the formatting dialog in case you added the [LOCATION] placeholder to your signature for instance

Is that really the usecase though? Only use I see for including location in logs if the final location is off and you want to provide that info to others. It should probably *explicitly NOT* be available for inclusion in templates/signature - otherwise people will be posting the final locations of multis/mysterys.

**Comment by nmrsmn** [comment]
> I wonder what the battery impact of that is. But then again not too much time is spent on the log dialog probably ...

I was wondering the same but I agree on your comment on not spending that much time on the log dialog, so I figured this was an OK solution..

> Is that really the usecase though? Only use I see for including location in logs if the final location is off and you want to provide that info to others. It should probably _explicitly NOT_ be available for inclusion in templates/signature - otherwise people will be posting the final locations of multis/mysterys.

Now I'm getting confused. My first thought is that it wouldn't be that hard to make the `[LOCATION]` replacement available only for when you're on the `LogCacheActivity` (maybe even restrict it to when there is no final location available like for multis/mysteres). But as of now I'm really unsure what I should implement, since all the stuff spoken about in the issue itself.. So maybe someone can shed some light on that matter, like @Lineflyer or @eddiemuc?

**Comment by Lineflyer** [comment]
> I'm actually quite confused this was marked as a "good first issue". Imho it's quite a complex thing due to coordinate formats, figuring out what's the right location and possible delays.

Assuming that this template is only actively inserted while currently composing the log its IMHO sufficient to take what is delivered as current coordinate and insert is as DD MM.SSS as common geocaching format.

**Comment by ztNFny** [comment]
> My first thought is that it wouldn't be that hard to make the `[LOCATION]` replacement available only for when you're on the `LogCacheActivity`

That can be achieved by adding it to LogTemplateProvider.getTemplatesWithSignature() instead of getTemplatesWithoutSignature()

**Comment by nmrsmn** [comment]
Well in that case, if I understood correctly, I implemented the feature now as intended.

**Comment by ztNFny** [comment]
How about also inserting the accuracy? Like "N 00 00.00 E 000 00.000 (±10 m)"
See https://github.com/cgeo/cgeo/pull/12934 for getting it

**Comment by moving-bits** [comment]
Let's test this in the nightlies. Thanks @nmrsmn for your contribution, very welcomed!

**Pull request merged**
