### PR TITLE
rel to #15194: use stores list dialog for dropdowns

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #15194: use stores list dialog for dropdowns

### CODE REVIEW

**Comment by eddiemuc** [comment]
@moving-bits : this PR is not finished (has a lot of commented out code). But I was really surprised how much code I apparently could remove from UnifiedMapActivity by using a generic new class CacheListActionBarChooser to handle both Cache-Lists and Unified Map list dropdowns. I might have overlooked something, can you double-check?

I tried Live map, Offline map and viewing single caches

**Comment by eddiemuc** [comment]
image
image
image
image
image
image
(Note: in last screenshot, please consider that PR #15413 hs not yet been merged. With this PR the dialog will look much nicer)

**Comment by moving-bits** [comment]
I'm a bit time constrained currently, will try to look into this later this week. But most likely you are right with your observations :-)

**Comment by moving-bits** [comment]
Tried to test a bit today, but did not come far - map crashes immediately for me in my emulator, independant from the way of entry (plain map / map cache list / long tap on "map" + select list).

Probably because spinner tries to update while VTM is still loading, so its viewport being undefined yet:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.oscim.core.BoundingBox org.oscim.map.Map.getBoundingBox(int)' on a null object reference
at cgeo.geocaching.unifiedmap.mapsforgevtm.MapsforgeVtmFragment.getBoundingBox(MapsforgeVtmFragment.java:324)
at cgeo.geocaching.unifiedmap.AbstractMapFragment.getViewport(AbstractMapFragment.java:108)
at cgeo.geocaching.unifiedmap.UnifiedMapActivity.refreshListChooser(UnifiedMapActivity.java:580)
at cgeo.geocaching.unifiedmap.UnifiedMapActivity.setupActionBarSpinner(UnifiedMapActivity.java:599)
at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onCreate(UnifiedMapActivity.java:298)
at android.app.Activity.performCreate(Activity.java:8000)
at android.app.Activity.performCreate(Activity.java:7984)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:223) 
at android.app.ActivityThread.main(ActivityThread.java:7656) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by moving-bits** [comment]
Question: Do we still need the dropdown indicator in map/cache list spinner? Costs precious space, especially in map view, and it's no longer an actual dropdown anymore.

**Comment by eddiemuc** [comment]
> Question: Do we still need the dropdown indicator in map/cache list spinner? Costs precious space, especially in map view, and it's no longer an actual dropdown anymore.

I believe we need some sort of visual indication that the action bar is tappable and there's an action behind it. There was a drop-down indicator before to mark that, this has not changed (well the icon might be a little bigger, we can change that of course)

If we remove the icon, how will users know they can tap to select a new list?

**Comment by eddiemuc** [comment]
The exception will be fixed by me of course, as time permits

**Comment by eddiemuc** [comment]
Retest this please

**Comment by ztNFny** [comment]
This commit cause a crash on opening Unified map :-( Reverting this commit stops the crash. Investigating now

                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.unifiedmap.UnifiedMapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.oscim.core.BoundingBox org.oscim.map.Map.getBoundingBox(int)' on a null object reference
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.oscim.core.BoundingBox org.oscim.map.Map.getBoundingBox(int)' on a null object reference
                                                                                                    	at cgeo.geocaching.unifiedmap.mapsforgevtm.MapsforgeVtmFragment.getBoundingBox(MapsforgeVtmFragment.java:332)
                                                                                                    	at cgeo.geocaching.unifiedmap.AbstractMapFragment.getViewport(AbstractMapFragment.java:108)
                                                                                                    	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.refreshListChooser(UnifiedMapActivity.java:582)
                                                                                                    	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.setupActionBarSpinner(UnifiedMapActivity.java:604)
                                                                                                    	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onCreate(UnifiedMapActivity.java:298)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8305)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8284)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)

**Comment by ztNFny** [comment]
mapFragment.getViewport()
-> java.lang.NullPointerException: Attempt to invoke virtual method 'org.oscim.core.BoundingBox org.oscim.map.Map.getBoundingBox(int)' on a null object reference

**Comment by ztNFny** [comment]
Happens with all non-Google maps.

I threw a quick try-catch around the block for now, will propose that as a temporary fix unless @eddiemuc has a chance to take a proper look at this issue

**Comment by eddiemuc** [comment]
Thanks @ztNFny , I created PR #15430 to fix this. For whatever reason I can't reproduce these NPEs in my emulator, but from the stack traces the cause is pretty clear.

**Pull request merged**
