### PR TITLE
fix #14681: parse and fill geocachereferencecode for gc trackable retrieve logging

### LINKED ISSUE #14681: TB logging not possible for non-migrated user
### Describe your problem!

Using nightly 2023.10.03-NB2 (with new log API) I cannot grab a trackable.

### How to reproduce?

- Search for a trackable using its secret code
- The trackable page is shown (in my case another user has this TB in his inventory)
- Open TB log page, select "Woanders mitgenommen"
- Write log text
- Send the log

### Actual result after these steps?

c:geo claims it could not upload a log picture (although there is no log picture in this scenario)
image

### Expected result after these steps?

TB grabbing should work normal

### Reproducible

Yes

### c:geo Version

2023.10.03-NB2-9acf5e6

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #14681: parse and fill geocachereferencecode for gc trackable retrieve logging

### CODE REVIEW

**Comment by Lineflyer** [comment]
Thanks @eddiemuc for working this out.
You should target `release` with this PR as we are currently in a beta phase.

**Comment by eddiemuc** [comment]
> Thanks @eddiemuc for working this out. You should target `release` with this PR as we are currently in a beta phase.

I switched target to release. This also pulls in two other commits into my PR but seems to work otherwise. Need advise how to proceed if this is not ok

**Comment by Lineflyer** [comment]
looks strange. No idea, whether this might make problem on merging upstream afterwards.

I would suggest to provide a new PR, theoretically it should work like:
- Checkout release branch and make sure its up to date (pull)
- Create a new branch for this issue starting from release branch
- Cherry pick your commit onto this branch
- Push branch, create PR

**Comment by eddiemuc** [comment]
Closing this PR in favor of #14750

**Comment by fm-sys** [comment]
> I would suggest to provide a new PR, theoretically it should work like:
> 

For the future, there is a way easier way (copied from my git cheat sheet):

### Retarget a branch from master to release
`git rebase --onto upstream/release upstream/master`
(If the changes were already pushed, you need to force push afterwards)

**Pull request closed without merging**
