### PR TITLE
related to #8632: create indices to optimize cache-log-select

### PR DESCRIPTION
**Pull request by eddiemuc**
related to #8632: create indices to optimize cache-log-select
creates db version 86

### CODE REVIEW

**Comment by MagpieFourtyTwo** [comment]
Any chance to get this merged into master / nightly?

I'm *really* looking forward to this ... and would *really* like to know if we (resp. @eddiemuc) found the reason for this performance issue for real.

**Comment by eddiemuc** [comment]
> Any chance to get this merged into master / nightly?
> 
> I'm _really_ looking forward to this ... and would _really_ like to know if we (resp. @eddiemuc) found the reason for this performance issue for real.

Same here, but it seems that @moving-bits is currenty not available (maybe on well-deserved vacation), and I do not know anyone else with the permission to merge pull requests. @Lineflyer do you have any information on this?

**Comment by MagpieFourtyTwo** [comment]
Ok, so it's in fact just a "man power problem"?
Can live with it - esp as I guess they will come back perfectly recreated ...  ;)

**Comment by Lineflyer** [comment]
@eddiemuc I am also on vacation right now and did only punctually follow/answer any topics.
Need to catch up next week if find some time.

All core members (team of c:geo org on Github) can merge/push to the repo, of there is something urgent to do.

**Comment by moving-bits** [comment]
> Same here, but it seems that @moving-bits is currenty not available (maybe on well-deserved vacation)

Sorry, no vacation (would be nice, with the weather we currently have), but being pretty busy currently. Should become better again starting this weekend...

**Comment by MagpieFourtyTwo** [comment]
Even more thanks for committing anyway! 👍 
And next vacation will come.  ;)

**Comment by eddiemuc** [comment]
@moving-bits same from me, thanks for merging and I hope next vacation comes soon :-)

**Comment by moving-bits** [comment]
@MagpieFourtyTwo @eddiemuc Thanks, guys! 👍

**Comment by MagpieFourtyTwo** [comment]
Pure self-interest. ;)

**Pull request merged**
