### PR TITLE
merge waypoints on refresh from Okapi (fix #14100)

### LINKED ISSUE #14100: User defined waypoint lost if user defined coords are set on website
### Describe your problem!

Reported on support mail and reproducible for me:

This affects the OC connector only AFAICS.

User defined waypoints in c:geo are deleted, once you refresh the cache when there is a coordinate stored in the personal note.

### How to reproduce?

- Open OC10914 in c:geo
- There is no additional waypoint in c:geo
- Create a user defined waypoint in c:geo
- Go to the opencaching website and store a coordinate in the personal note section:
image

- Refresh the cache in c:geo

### Actual result after these steps?

The stored coordinate from the personal note is shown in the usual way, but the previously stored user defined waypoint is gone.

### Expected result after these steps?

Retrieving coordinates from user note should not alter or remove any other waypoints of the cache.

### Reproducible

Yes

### c:geo Version

2023.03.14-NB and current release

### System information

_No response_

### Additional Information

Support ticket 779643

### PR DESCRIPTION
**Pull request by murggel**
## Description

fixes deletion of user defined waypoints on update cache from OC with defined user-coordinates on website.
Waypoints are now getting merged instead of overwritten.

## Related issues

fix #14100

## Additional context

to discuss, if the coordinates from the user-coordinates on website should be overtaken in c:geo as modified cache-coordinates

### CODE REVIEW

**Comment by murggel** [comment]
can add some testcase, if OC-test-user is set up (see also PR #13726, comment https://github.com/cgeo/cgeo/pull/13726#issuecomment-1337481783)

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
One failing test (https://ci.cgeo.org/job/cgeo-CI_PR-build/4488/testReport/junit/cgeo.geocaching.models/GeocacheTest/testMergeLocalUserModifiedCoordsNotServerSideModified/), could be releated to the PR

**Comment by murggel** [comment]
I will have a look at it

**Comment by murggel** [comment]
retest this please

**Comment by moving-bits** [comment]
I'll ask @mucek4 to restart the executors to mitigate the "Could not create ADB bridge" error...

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
