### PR TITLE
fix #6973 log "Report Problem" a.k.a NM, NA

### LINKED ISSUE #6973: (Re)implement "Report a problem"
Since the new logging function has been implemented (#6519) we have a regression;
The log types "Needs maintenance" and "Needs archived" is no longer available due to the inline function on the new logging page for these kinds of reports.

What we need is a dropdown menu in the logging activity with the following options:
Heading: Report a problem
Selections: Logbook is full / Container is damaged / Cache should be archived / Other

We should furthermore inform the user in a appropriate way, that he needs to describe the problem in his log, once he selected an option.
Here is the Groundspeak wording for that:
"Add details to your log to help the cache owner and other geocachers understand the problem."

### PR DESCRIPTION
**Pull request by pstorch**
Implements the "Report Problem" for the new GC logging page and also for OC (#5539).

It partly solves #4899 for those cases where a cacher wants to save e.g. a found and a needs maintenance offline or a DNF and a needs archived.

It also solves #6812 because I had to change the logic to save the log when the report problem changed.

### CODE REVIEW

**Comment by pstorch** [comment]
I think the reported issue by Codacy regarding the `Use equals() to compare object references.` in the `ReportProblemType.isVisible()` is a false positive. You can compare two Enums with `==`. @Bananeweizen what do you think?

**Comment by Lineflyer** [comment]
@Bananeweizen @Kumy If you have some spare time, it would be nice if you could review this PR (and the relevance of the Codacy issue).

**Comment by Lineflyer** [comment]
@pstorch 
Seems the guys where you requested a review are not available at the moment.
How shall we proceed, I would of course like to test the change in our nightlies, but cannot judge the codacy issue.
Given codacy is right, would it be possible to use `equals()` here or else just put a comment in, that this needs to be investigated/modified later?!

**Comment by pstorch** [comment]
@Lineflyer I checked with other Enums in the codebase and as far as I can see we use `==` to compare them. I've added a Unittest to check that it is working.
I'll merge it now. If someone has a different opinion, please raise your hand.

**Pull request merged**
