### PR TITLE
fix #16415: Wherigo: add support for multiple cartridges referenced in one geocache

### LINKED ISSUE #16415: Wherigo: Better handling of multiple cartridges in listing
### Describe your problem!

Some old geocaching listings have the cartridges link with http instead of https.
c:geo only detects https links.

### How to reproduce?

Open GC7CAGJ 

http://www.wherigo.com/cartridge/details.aspx?CGUID=673530dd-1a0c-4bab-8939-46ba6a8093b8

### Actual result after these steps?

If the cartridge link is with http, then:
There's only the option to open with WhereYouGo 
There's no option to download and plasy with c:geo

### Expected result after these steps?

To be able to download and then play the cartridge with c:geo

### Reproducible

Yes

### c:geo Version

2024.12.06-NB-89f5c8b

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #16415: Wherigo: add support for multiple cartridges referenced in one geocache

### CODE REVIEW

**Comment by eddiemuc** [comment]
image

**Comment by ztNFny** [comment]
Considering that the usual situation to encounter that dialog would be without the cartridges downloaded I find the dialog to have quite limited use. Should I download 1 or 2 here? What's the difference? To figure that out I have to read the listing - and then find in there the links to the catrdiges
image

**Comment by eddiemuc** [comment]
> Considering that the usual situation to encounter that dialog would be without the cartridges downloaded...

I don't think this is the only situation where the dialog is used. I assume it is common for users to re-enter Wherigos previously downloaded through this menu.

Besides: unfortunately there's simply not much info to show when cartridge is not yet downloaded....

> I'd suggest to at least add a "refer to listing" text to this dialog

That's a good idea, I will add this

**Comment by eddiemuc** [comment]
image

**Comment by eddiemuc** [comment]
image

**Comment by eddiemuc** [comment]
I accidentally merged this PR/commit to master. It is now also merged to release where it belongs.

Git-Question: should I now revert this PR/commit on master? I assume that's not necessary (or may even create hazard) since on next merge of release to master git will recognize the commit. Right?

**Comment by moving-bits** [comment]
It produced a small conflict in conjunction with #16425, but that was easily resolved. `release` is merged to `master` now, no further action required from your side.

**Pull request merged**
