### PR TITLE
map auto rotation for Google Maps v2

### LINKED ISSUE #7507: Rotate map according to device orientation - Rotating map
With GMapsV2 we should have the capability to let the map rotate according to device orientation (map in walking/driving direction).

This is probably one of the most wanted feature reading our support channels.

Not sure if Google itself provides some library to do that (manual rotation is already working) or we need to implement the sensor stuff ourselves?

### PR DESCRIPTION
**Pull request by moving-bits**
Fixes #7507

When bearing between last rotation point and current location reaches +/- 15° map rotates accordingly. Auto rotation is enabled per default, and can be disabled using settings - map - map rotation - disable automatic map rotation.

### CODE REVIEW

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4677080&bid=15648571)

**Comment by Lineflyer** [comment]
Wow..nice...
Is it possible to toggle the rotation from within the map (e.g. icon on map)?
IMHO this would be a feature users would like to toggle very frequently depending on situation. 

I need to have a look how other apps implemented such feature.

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4677080&bid=15648571)

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4677080&bid=15648571)

**Comment by moving-bits** [comment]
rebased PR and added a menu option to toggle auto rotation

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/google/v2/GooglePositionAndHistory.java  2
- main/src/cgeo/geocaching/maps/CGeoMap.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4677080&bid=15648571)

**Pull request merged**
