### PR TITLE
Unnecessary check

### PR DESCRIPTION
**Pull request by S-Bartfast**
Removed an unnecessary check that was preventing the calculator from opening when a caches location is unknown.

### CODE REVIEW

**Comment by Lineflyer** [comment]
OK to test

**Comment by Lineflyer** [comment]
Was this check introduced by yourself, or was it in place before?
If it was there before, I wonder why we did it like that.

**Comment by S-Bartfast** [comment]
I wrote it before I really understood what it was.

When I first added the 'CalculateListener' I just copied it from the 'CacheListener' above it and while the 'cacheCoords' is valid for the 'CacheListener' it makes no sense to apply it to the 'CalculateListener'.  In fact it was preventing the calculator from opening for cache GC28M8N (as mentioned in #6699) as for some reason this cache has no cacheCoords.

**Comment by Lineflyer** [comment]
> as for some reason this cache has no cacheCoords.

It should have. I assume you are not logged in and/or have no login information stored for geoaching.com?!

However I think it might be in as you are able to select "Cache Coordinates" while entering coords for a new waypoint. Having these not defined might result in unexpected behaviour.

**Comment by S-Bartfast** [comment]
> ...as you are able to select "Cache Coordinates" while entering coords for a new waypoint.

I can't actually:
image

It is true that I am not logged in but I haven't been logged in on most of my emulated devices.  The other caches do seem to have 'cacheCoords' defined though so I'm not sure why this one doesn't.

No idea what's going on but in any event I can't see why 'cacheCoords' would need to be assigned for the calculator to be made available, so I got rid of the check, and it seems to work fine for me ;)

**Comment by Lineflyer** [comment]
Lets test then.

**Pull request merged**
