### PR TITLE
fix NPE in CachePopupFragment when cache no longer available (fix #8321)

### LINKED ISSUE #8321: NPE in CachePopupFragment.onResume
Another one from Google Play:

seems to happen when activity returns to the cache popup, and the cache is not available any longer

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4014)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4046)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1948)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)

Caused by: java.lang.NullPointerException: 
  at cgeo.geocaching.CachePopupFragment.init (CachePopupFragment.java:113)
  at cgeo.geocaching.AbstractDialogFragment.onResume (AbstractDialogFragment.java:156)
...
```

### PR DESCRIPTION
**Pull request by moving-bits**

### CODE REVIEW

**Comment by Lineflyer** [comment]
Restest this please

**Comment by Lineflyer** [comment]
After activating my cache again (which caused the two failed tests before) I assume those test results from CI now reveal the real status of this PR?

**Comment by moving-bits** [comment]
> After activating my cache again (which caused the two failed tests before) I assume those test results from CI now reveal the real status of this PR?

Not sure - it might be another artifact of the RxJave upgrade:

```
java.lang.RuntimeException: java.io.IOException: request was not successful
at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
at cgeo.geocaching.connector.gc.GCMap.searchByGeocodes(GCMap.java:49)
at cgeo.geocaching.connector.gc.GCBaseTest.testSearchFromMap(GCBaseTest.java:23)
at java.lang.reflect.Method.invoke(Native Method)
at junit.framework.TestCase.runTest(TestCase.java:168)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
```

@UniQP, can you have a look at it?

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
