### PR TITLE
enable search in preference screen (rel. to #12335)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
(updated description)

- enables search with preferences, using a suggestion provider
- at least three characters are required to trigger the search suggestion provider
- automatically scrolls to the selected preference
- highlights the title of that preference
- pressing enter in searchbar selects and opens the first found entry

(for screenshots see below: https://github.com/cgeo/cgeo/pull/12441#issuecomment-1003582062)

~Setting WIP label for now, as I'm not sure about the colors. I was looking for a color which highlights a text in both dark and light mode, and which is neither red nor green nor our accent color. A sort of turquoise is the best I've come up so far, but I'm open for other solutions.~
~Alternatively to a color, the found preference could be highlighted by a short animation or so - just don't know how to apply it.~

## Additional context
~I did not manage to search across all preferences, as the preference manager does load them on demand only, and asynchronally, so I would have to load each preference manually, wait for them to be displayed, and then perform the search I'm currently performing for the currently active preference. Any ideas?~

### CODE REVIEW

**Comment by moving-bits** [comment]
Ok, extending it to a global preference search was a bit tricky, but has been implemented now:

image.image

It's always doing a search across all main preference screens now, opening the screen for the first hit, and marking the preference's title.
(Extending it do display several hits is on my wish list, but will not be implemented in the first version.)

**Comment by fm-sys** [comment]
Would to be possible to highlight the background instead of the text (and only highlight these characters which are an actual match)?

Like it is known from browsers:

grafik

**Comment by moving-bits** [comment]
> Would to be possible to highlight the background instead of the text (and only highlight these characters which are an actual match)?

TMALSS: sadly, does not seem possible, or at least I have not found out yet, how to.

Details: I'm searching both title and summary of each preference for matching strings. I was able to color-mark titles (at least most of them), but have not been successful for most of the summaries, for unknown reason so far. Thus I decided to mark the title of a preference found only, disregarding whether the match is in title or in summary.
What I could do, though, is extending the search to display suggestions, and list both title and summary there, having the findings color-marked in a way you have described. This is the part "extending it do display several hits is on my wish list" mentioned above.

**Comment by ztNFny** [comment]
I checked some other apps that offer search in settings and none of them change the text color, in fact most don't highlight the text at all.

My suggestion would be to highlight the matching text (not the whole line, only the match) in our accent color.

**Comment by ztNFny** [comment]
If only 1 result is shown there definitly needs to be a "search next" button, just finding the first item will not help in a lot of cases.

I like the way Locus does it, it lists all the preferences, no matter which section they are from:
image

**Comment by moving-bits** [comment]
sneak preview: I've switched to SearchSuggestionProvider meanwhile, giving something like this:

image.image

Currently struggling with back key from search result - which closes `SettingsActivity` completely instead of returning to main settings screen.

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
only some checkstyle problems:
~~~
> Task :main:checkstyle
[ant:checkstyle] [WARN] /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/cgeo/geocaching/search/GeocacheSuggestionsAdapter.java:13:8: Unused import - android.view.ViewGroup. [UnusedImports]
[ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/cgeo/geocaching/settings/Settings.java:63:1: Wrong order for 'java.io.File' import. [ImportOrder]
[ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/cgeo/geocaching/settings/fragments/PreferenceMapFragment.java:13:1: Extra separation in import group before 'cgeo.geocaching.utils.SettingsUtils.initPublicFolders' [ImportOrder]
Checkstyle rule violations were found. See the report at: file:///home/jenkins/slave/workspace/cgeo-CI_PR-build/main/build/reports/checkstyle/checkstyle.html
Checkstyle files with violations: 3
Checkstyle violations by severity: [warning:1, info:2]
~~~

**Comment by moving-bits** [comment]
ready for review / merge

**Comment by moving-bits** [comment]
rebased and solved merge conflict

**Pull request merged**
