### PR TITLE
Condensed position info with icons

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
as discussed in #15571:

image

- removed right-alignment of elevation and distance info
- replaced text by our assigned icons for elevation / straight distance

### CODE REVIEW

**Comment by moving-bits** [comment]
failing tests are unrelated

**Comment by ztNFny** [comment]
You have to give me some time! 🤪
Could pick up https://github.com/cgeo/cgeo/issues/15566 and add a "vertical distance" to the dialog as well. Suitable icon would be https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aheight%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024

Layout suggestion:
Coordinates
Distance - Vertical distance
Elevation

Could you add tooltips to those textviews please?

**Comment by moving-bits** [comment]
vertical distance would be "map elevation at selected position" - "map elevation at current position" (allowing negative numbers)?

Will add the icon (thanks for looking it up) and tooltips.

**Comment by ztNFny** [comment]
Maybe also a compass icon in front of the coordinates? That'd provide a place for the tooltip as well, 
Not sure we already have one, if not:
https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aexplore%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024

**Pull request merged**
