### PR TITLE
try to fix the parsing of owner id after website change

### LINKED ISSUE #10421: Cache type and owner parsing not OK (Website change)
## Bug description 

Users report problems, that cache type and partly other information is missing after loading cache details.
There was also a website change today, so it might be caused by that:
https://forums.geocaching.com/GC/index.php?/topic/361563-release-notes-website-links-now-point-to-new-search-results-april-20-2021/

### Steps to reproduce the problem

- Open cache details of an unsaved  cache

### Actual result after these steps 

- Cache type is shown as "??" 

### Expected result after these steps 

Cache type parsing working

## c:geo version 

2021.04.15

## Reproducible 

Yes

## System information 

not relevant

## Additional context 

Other problems might apply, e.g. owner has some problem
Taken from a users log:
```
4-20 20:00:10.998  6897  9615 W cgeo    : [Thread-17] owner not parsed correctly for GC97Z19
04-20 20:00:10.999  6897  9615 W cgeo    : [Thread-17] type not parsed correctly for GC97Z19
04-20 20:00:16.265  6897  4136 W DpmTcmClient: read failed bytes countRead: -1
04-20 20:00:17.523  6897  9615 W cgeo    : [Thread-17] owner not parsed correctly for GC97WH4
04-20 20:00:17.523  6897  9615 W cgeo    : [Thread-17] type not parsed correctly for GC97WH4
04-20 20:00:22.620  6897  9615 W cgeo    : [Thread-17] owner not parsed correctly for GC96ZMP
04-20 20:00:22.620  6897  9615 W cgeo    : [Thread-17] type not parsed correctly for GC96ZMP
```

### PR DESCRIPTION
**Pull request by fm-sys**
fixes #10421

### CODE REVIEW

**Comment by Lineflyer** [comment]
@fm-sys The failing tests look like there is now a difference in the case the shown cache owner name differs from the user name, who owns the cache.
As you might know, the owner can define the shown user name while creating a cache so it might differ from the real user name. Could this be a problem for your PR?
You can use GC7C6K8 for testing. Owner is Lineflyer, shown owner is "Lineflyer & Velberlinle"

Test result on CI shows:
```
org.junit.ComparisonFailure: [Cache GC2JVEH: owner user id] expected:<"indianerjones[]"> but was:<"indianerjones[, der merlyn,reflektordetektor]">
```

**Comment by Lineflyer** [comment]
Or the mocked data needs update but AFAIR @moving-bits already updated the mocked data.

**Comment by moving-bits** [comment]
> but AFAIR @moving-bits already updated the mocked data.

I did so only regarding the date format, and manually so, no complete refresh.

**Comment by fm-sys** [comment]
In fact the reason for the failing test is, that the mocked test data is outdated and therefore the new regex will fail and the user display name is probably used as fallback in this case? I will need to update the test data, the regex itself seems to behave just fine...

BTW, I can only try modify the test data manually, as I (currently) don't have a GC premium membership. The alternative would be to merge this PR as is and someone else needs to update the test data afterwards...

**Comment by moving-bits** [comment]
I can look into it today or tomorrow, depending on available time.

**Pull request merged**
