### PR TITLE
clear visiteddate on clear offline log

### PR DESCRIPTION
**Pull request by eddiemuc**
clear visiteddate on clear offline log

### CODE REVIEW

**Comment by Lineflyer** [comment]
Is there any related issue or can you describe what problem this will solve?

**Comment by eddiemuc** [comment]
As of now, if you create an offline log, save it but then clear it afterwards, the viditeddate will keep set at the date and time of the log entry. This will let the associated cache show up in history list and sorted According to the (already deleted) offline log entry date.

But I have to think this whole topic through again anyway, will set this PR to "draft/wip"

**Comment by Lineflyer** [comment]
Same as me...just thinking if there is any reason for keeping the visitedate and also crawled older issues. But I did not find any reason for that. So I assume this is really a bug.

However, how will it behave in this use case:
- User performs offline log for some caches
- User exports field notes and logs online on the website
- User refreshes caches in c:geo to reflect found state
- User now deletes superfluous offline logs

Will the caches vanish from the history in that case? That would be unexpected. We should not delete a visiteddate if its logged online as found/DNF.

**Comment by eddiemuc** [comment]
@Lineflyer exactly my thoughts.

My current though is that the root problem is the "double usage" of the viditeddate field. It is used to store two different things at the same time:
* The last visited date as available from the website/service. This date has only day-granularity (at least for GC.com)
* The offline log entry date of an existing offline log (if any is there). This is a real timestamp (millisecond-granularity)

In many cases the two things are the same, but in.the case you described they are different. Which then leads to the described problems. Other corner cases are possible

To solve this cleany I fear we have to introduce a second column in the cache table, fill it correctly and change the History-Filter as well as the "date logged" sorting Algo accordingly. A bigger change...

A more hacky solution would be to check on cache refresh whether a viditeddate is already on cache for same date but with timestamp granularity and not update it in those cases. Might be possible, but might get tricky in cache merge logic

**Comment by eddiemuc** [comment]
Copied comments to #7919 for later reference. Will close this PR for now

**Pull request closed without merging**
