### PR TITLE
Add an AppShortcut to directly launch the Live-Map

### PR DESCRIPTION
**Pull request by jonas-koeritz**
Let the user go straight to the Live-Map from their app drawer or home screen.

photo5256059635884993642

### CODE REVIEW

**Comment by Lineflyer** [comment]
Nice.

IMHO we already have such function as a widget, thus why not use all widget functions also here?

**Comment by jonas-koeritz** [comment]
Can somebody point me to where the widget code lives? Had a quick look but didn't find it :P

**Comment by moving-bits** [comment]
@jonas-koeritz 

> Can somebody point me to where the widget code lives? Had a quick look but didn't find it :P

`main/src/cgeo/geocaching/CreateShortcutActivity.java`

**Comment by jonas-koeritz** [comment]
Recommended maximum number of AppShortcuts is 4 so i left out "Go to", wich also has some preconditions that would add complexity to this implementation.

**Pull request merged**
