### PR TITLE
Use downloadable fonts instead of bundled fonts to retrieve missing e…

### LINKED ISSUE #12856: FYI: APK size increased significantly
Some days ago I noticed, that the cgeo APK recently got significantly bigger.

Screenshot_20220313_215014_com android documentsui

It's not necessarily a problem, but 10 MB -> 20 MB (+100%) looks like a quite huge step to me. It would at least be interesting, what caused this rapid growth.

### PR DESCRIPTION
**Pull request by bekuno**
…moji

fixes #12856

This should work, as all samples I found in the web are work in this way.
But the creation of the FontRequest (EmojiDownloadService Line 37) fails with 
`Method threw 'java.lang.NullPointerException' exception. Cannot evaluate androidx.core.provider.FontRequest.toString()`

Does anyone have a solution?

### CODE REVIEW

**Comment by bekuno** [comment]
Maybe someone is able to test this on a API 21 (Android 5.0/Lollipop) device?

**Comment by Lineflyer** [comment]
> Maybe someone is able to test this on a API 21 (Android 5.0/Lollipop) device?

I could test on an API 21 emulator if this helps. I might have a API 21 real device somewhere, but this would be more easy to test it in nightlies.

**Comment by bekuno** [comment]
> > Maybe someone is able to test this on a API 21 (Android 5.0/Lollipop) device?
> 
> I could test on an API 21 emulator if this helps. I might have a API 21 real device somewhere, but this would be more easy to test it in nightlies.

We tested yesterday with @ztNFny and emulator. He could reproduce the problem.
The first API with all emoji is API 24.
So it would helpful to test on a real device lower API 24.

As this is probaly a rare used function and only a small percentage of user devices are involved, we could maybe stay without a emoji - the missing emoji is shown in https://github.com/cgeo/cgeo/issues/12471#issuecomment-1007813268

**Comment by Lineflyer** [comment]
Without having it tested:

I think we should just accept the limitation to show no emojis / not all emojis on API <24.

What we should reach is, that the APK size is reduced again...IMHO much more important than full feature coverage on pretty old devices.

**Comment by ztNFny** [comment]
It seems there's not really progress on this. Can we remove the bundled font please to get the size back down? Those old devices will just have to miss out on this feature.

**Comment by fm-sys** [comment]
The question is whether we need it at all...? Especially as we had the discussion to increase the min API version recently (#12581)

**Comment by bekuno** [comment]
We would need at least one other emoji for Blay Eye and Shy, as they are still missing until API 27.

**Comment by ztNFny** [comment]
> We would need at least one other emoji for Blay Eye and Shy, as they are still missing until API 27.

imho we can ignore API <27 (just show the generic placeholder icon for those smileys). That's just 13% of devices and the loss in functionality is almost non-existent.

**Comment by bekuno** [comment]
> > We would need at least one other emoji for Blay Eye and Shy, as they are still missing until API 27.
 
> imho we can ignore API <27 (just show the generic placeholder icon for those smileys). That's just 13% of devices and the loss in functionality is almost non-existe

Inclusive API 27 :-).
But these are only 2% more ...

**Comment by ztNFny** [comment]
> Inclusive API 27 :-).
> But these are only 2% more ...

15% of devices, a feature that few people will use, breaking in a way that's nearly irrelevant (there's still the character and the text version) - I say we shouldn't take care about at all if it takes more than 15 minutes but instead just ignore those without any workarounds or if (API.LEVEL >...)

**Comment by Lineflyer** [comment]
Replaced by https://github.com/cgeo/cgeo/pull/12935

**Pull request closed without merging**
