### PR TITLE
downgrade jackson library

### LINKED ISSUE #8135: Nightly not starting on Android 4.3
I do have an Android 4.3 device here, on which an old nightly was working (did not record the version though). I just updated it to the newest nightly and now it fails to start ("Unfortunately c:geo has stopped").

Will try to find debug logs. Can anyone try with an emulator?

### PR DESCRIPTION
**Pull request by bekuno**
fix #8135

### CODE REVIEW

**Comment by moving-bits** [comment]
@bekuno
Thanks for fixing this

**Comment by moving-bits** [comment]
Shouldn't we target this downgrade to release branch to have it in our next release?

**Comment by Lineflyer** [comment]
The upgrade was only done on master.
Release is still on a even lower version.

**Comment by moving-bits** [comment]
Ah, I see - that's fine, then. Thanks for pointing that out.

**Pull request merged**
