### PR TITLE
remove 'new list' from main screen 'stored' long press menu (rel. to #5407)

### PR DESCRIPTION
**Pull request by moving-bits**

### CODE REVIEW

**Comment by Lineflyer** [comment]
Would this lead to "New list" being the first entry in the pulldown?
I think this will break many users workflow when switching back from some custom list to the default list IMHO.
Maybe better put it at the end here?

**Comment by moving-bits** [comment]
Yes, will be the first entry. Will have to look up if this can be set otherwise.

The related issue was about making the mainscreen's "long press on stored" and the cachelist's spinner consistent (which would for me include "in the same order"). So put "create new" at the end for both?

Or maybe: Leave out "create new" in both lists? - I would find it sort of confusing to find this action item in the cachelist spinner anyway, and I - personally - have no need to have it on the mainscreen's long press, but don't know how other users use this regularly or not.

**Comment by fm-sys** [comment]
> Or maybe: Leave out "create new" in both lists? - I would find it sort of confusing to find this action item in the cachelist spinner anyway, and I - personally - have no need to have it on the mainscreen's long press, but don't know how other users use this regularly or not.

Totally agree. A new list only needs to be created whenever you want to move/save caches. And in both cases, the function for creating a new list is available...

**Comment by Lineflyer** [comment]
Also agree.

**Comment by rsudev** [comment]
While having a 'create new' item in a selection is IMO not so uncommon I would also prefer/agree to leave it out in the above mentioned contexts.

**Comment by moving-bits** [comment]
Adapted this PR accordingly to remove "new list" from stored's long press menu instead of adding it to the cache list's list selector.

**Pull request merged**
