### PR TITLE
upgrade to annotations 24.2.0 and butterknife 8.4.0

### PR DESCRIPTION
**Pull request by Bananeweizen**

### CODE REVIEW

**Comment by Bananeweizen** [comment]
retest this please

updated build script to accept license automatically

**Comment by Bananeweizen** [comment]
@kumy @samueltardieu if I get it right, you must recreate your agents from the dockerfile first, since this depends on a recent version of the annotations lib?

**Comment by kumy** [comment]
That's the clean solution, but we may also log into the container and update manually. There is also a Jenkins task for for emergency cases. Don't forget the main executor wich is handled by @mucek4.
May you provide the "key name" for installing via the sdk command line? It's necessary for updating the executor-docker repo.

On August 29, 2016 7:18:05 PM GMT+02:00, Michael Keppler <notifications@github.com> wrote:
>@kumy @samueltardieu if I get it right, you must recreate your agents
>from the dockerfile first, since this depends on a recent version of
>the annotations lib?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/pull/5924#issuecomment-243190008

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
After some tests on kumy-3 executor, I've updated remaining executors via [jenkins](http://ci.cgeo.org/view/Executors/job/Upgrade SDK). It should help. But we need @mucek4 to update the master server, before merge, else no more NB will be build.

**Comment by mucek4** [comment]
Master updated.

**Comment by kumy** [comment]
Recreating an instance and rebuilding an image are different tasks. Our executors stay alive and are only rebuilt if necessary as we need to download the whole sdk again which is (for me) very long.

On August 31, 2016 9:07:15 PM GMT+02:00, Michael Keppler <notifications@github.com> wrote:
>@kumy I was not aware that a new package needs to be installed. Since I
>only saw names in your config file, but no versions, I assumed that on
>re-creating the docker instance it would fetch _all_ versions of the
>specific package. And we have the annotations in there already, just
>not the most recent version.
>
>Did I get that wrong?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/pull/5924#issuecomment-243868002

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by samueltardieu** [comment]
retest this please

**Comment by samueltardieu** [comment]
retest this please

**Comment by samueltardieu** [comment]
retest this please

**Pull request merged**
