### PR TITLE
prevent ProGuard from cutting out enum class members

### LINKED ISSUE #7762: Prevent ProGuard from cutting out enum class members
Sometimes after upgrading my dev laptop to a new version of Android Studio I get strange results. This time I'm constantly receiving the following fatal error directly after installing the APK and launching the main activity:

```
2019-08-01 12:53:14.244 10119-10151/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: network--1
    Process: cgeo.geocaching, PID: 10119
    java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:272)
        at java.lang.Enum$1.create(Enum.java:262)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2423)
        at java.lang.Class.getEnumConstants(Class.java:2409)
        at com.fasterxml.jackson.databind.cfg.MapperConfig.collectFeatureDefaults(MapperConfig.java:99)
        at com.fasterxml.jackson.databind.cfg.MapperConfigBase.<clinit>(MapperConfigBase.java:32)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:565)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480)
        at cgeo.geocaching.network.Network.<clinit>(Network.java:71)
        at cgeo.geocaching.network.Network.requestJSON(Network.java:496)
        at cgeo.geocaching.network.StatusUpdater.lambda$static$0(StatusUpdater.java:95)
        at cgeo.geocaching.network.-$$Lambda$StatusUpdater$Dl9oq5EHQ1l7w5i7L9s1Ft_3XTo.run(Unknown Source:0)
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532)
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoSuchMethodException: values []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at java.lang.Enum$1.create(Enum.java:268)
        at java.lang.Enum$1.create(Enum.java:262) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2423) 
        at java.lang.Class.getEnumConstants(Class.java:2409) 
        at com.fasterxml.jackson.databind.cfg.MapperConfig.collectFeatureDefaults(MapperConfig.java:99) 
        at com.fasterxml.jackson.databind.cfg.MapperConfigBase.<clinit>(MapperConfigBase.java:32) 
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:565) 
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480) 
        at cgeo.geocaching.network.Network.<clinit>(Network.java:71) 
        at cgeo.geocaching.network.Network.requestJSON(Network.java:496) 
        at cgeo.geocaching.network.StatusUpdater.lambda$static$0(StatusUpdater.java:95) 
        at cgeo.geocaching.network.-$$Lambda$StatusUpdater$Dl9oq5EHQ1l7w5i7L9s1Ft_3XTo.run(Unknown Source:0) 
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532) 
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479) 
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288) 
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

I've already tried clean build, different SDK versions, clearing build caches, even a fresh install of AS - nothing works. 

After some research I found info that this is related to some ProGuard config, which may cut out some enums during shrinking process, which leads to the error shown above. To solve this you have to add the following to your ProGuard config:

```
# For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
```

I'll create a PR for this.

### PR DESCRIPTION
**Pull request by moving-bits**
Fixes #7762

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
@moving-bits will doublecheck and merge as needed.

**Comment by moving-bits** [comment]
Currently & with the switch to gradle 3.4.2 it works on the first machine without this PR - need to cross check on the second machine, though. Therefore setting WIP / DNM label for now.

**Comment by Lineflyer** [comment]
@moving-bits Pleas decide if still needed.

**Comment by moving-bits** [comment]
> @moving-bits Pleas decide if still needed.

Generally works for me currently, will recheck after the next point release of AS (3.6), thus leaving it at WIP state for now.

**Comment by moving-bits** [comment]
In the past, this has been a problem after each major upgrade of AS. But as it did not happen again with the update to AS 3.6, I'll close this PR for now.

**Pull request closed without merging**
