### PR TITLE
issue-6546: changes the cache list menu structure

### PR DESCRIPTION
**Pull request by pstorch**
- new menu structure of the cache list menu
- hides empty caches sub menu if there are no caches in the list

### CODE REVIEW

**Comment by Lineflyer** [comment]
Looks good now. Thanks @pstorch for helping out here.
AFAIR we discussed whether wwe should set the menus disabled now instead of invisible, which I would also prefer in order to minimize the "magically" vanishing menus. Its more clear for the user to disable instead of hide.

But we can anyway do this in a follow up PR.

**Comment by FUSSEL4** [comment]
for detailed description see [#6567](https://github.com/cgeo/cgeo/pull/6567).

If this PR is merged I'll close the original one.

**Comment by FUSSEL4** [comment]
@pstorch Thank you for helping out.

**Comment by pstorch** [comment]
@FUSSEL4 thanks for your contribution

**Pull request merged**
