### PR TITLE
greenify PR build

### PR DESCRIPTION
**Pull request by eddiemuc**
greenify PR build

### CODE REVIEW

**Comment by eddiemuc** [comment]
Attempts to fix https://github.com/cgeo/cgeo/issues/16132 so we can finally refer to green CI builds again

**Comment by eddiemuc** [comment]
...and apparently a few "unused imports" are in master as well...

**Comment by eddiemuc** [comment]
Build is green. Merging immediately. Please check for green CI builds for your PRs again from now on

**Comment by moving-bits** [comment]
thanks for housekeeping. I'm looking forward to get green builds again :+1:

**Pull request merged**
