### PR TITLE
add 'selext next 20 caches' to cache list (rel. to #12077)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
As discussed in #12077: Add an option to select the next 20 caches in the cache list.
Selecting this menu entry will check the first 20 unchecked caches, honoring the current sort order. Selecting this menu entry multiple times will select 40, 60, 80 etc. caches (20 more on each call).

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by eddiemuc** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
