### PR TITLE
Improve new backup handling

### PR DESCRIPTION
**Pull request by fm-sys**
## Changes - see https://github.com/cgeo/cgeo/issues/9104#issue-712512860:
- [x] always backup database and settings (to keep the UI clear and simple)
- [x] don't move the entire folder but just the backup files
- [x] always store the backup in `backup/yyyy-mm-dd hh-mm` (independent of advanced settings)
- [x] multiple backups at one day
- [x] move existing backup into new folder structure
- [x] Advanced settings: I would make the explanation text always visible & integrate it into the "create backup" section
- [x] choose dialog for restore backup from backup history (use c:geo's `SimpleDirChooser` component)
- [x] warning that backup is only local

---
- info message, that the old backup has been moved into the new folder structure

I'm unsure about this point: Should we really inform the user that his existing backup was moved into the new folder structure, or is it rater confusing? Probably most users will not care in which subdir the backup was exactly moved...  (with this PR, it only writes an info to log file instead)

### CODE REVIEW

**Comment by fm-sys** [comment]
Screenshot to make UI discussions easier...
Screenshot_20201011_132623_cgeo geocaching


I personally would have kept the "Maximum stored backups" in a third category at the bottom, but the majority decides...

**Comment by fm-sys** [comment]
As no further feedback occurred, we should merge it for testing it in our nightlies...

**Comment by moving-bits** [comment]
Thanks @fm-sys for the various improvements, like them!

One small suggestion: I find it confusing that "Maximum stored backups" has its own subheading and "include account data" does not have, which makes the latter sort of vanish optically. So I would either swap the two, so that "include account data" is part of the general "Create backup" section, or introduce a separate subheading for it.

Oh, and I would start each option with a capital letter. ("Include account data" in this case)

**Comment by fm-sys** [comment]
@moving-bits done!

Screenshot_20201019_180436_cgeo geocaching

**Comment by moving-bits** [comment]
@fm-sys 
Thumbs up & thanks!

**Pull request merged**
