### PR TITLE
issue_11001 improved

### PR DESCRIPTION
**Pull request by baiti**
attached pls find an update that treats the consumer-key in a more intelligent way. The string constant in the earlier PR had no real meaning after all. This PR provides a way to actually make use of the key.

### CODE REVIEW

**Comment by baiti** [comment]
@Lineflyer .... seems like none of you gets notified of new PRs if they aren't linked to a specific issue? Since #11001 is closed, I didn't know what to do. Should I open a new issue such that I could reference it via a tag in the PR?

What do you think with respect to the change being envisioned by this PR? Who wants to review?

**Comment by Lineflyer** [comment]
I was notified...but are on vacation at this moment...more or less only reading some mails and opening new issue while out caching at the moment. Back in 1,5 weeks.

**Comment by baiti** [comment]
> I was notified...but are on vacation at this moment...more or less only reading some mails and opening new issue while out caching at the moment. Back in 1,5 weeks.

ahhh ok. Enjoy!

**Review by moving-bits — APPROVED** [review]

**Comment by moving-bits** [comment]
failing test is unrelated, so let's merge

**Pull request merged**
