### PR TITLE
Useless comment fix

### PR DESCRIPTION
**Pull request by samueltardieu**
This change is [Reviewable](https://reviewable.io/reviews/cgeo/cgeo/5635)

### CODE REVIEW

**Comment by samueltardieu** [comment]
*[main/src/cgeo/geocaching/CgeoApplication.java, line 70 \[r1\]](https://reviewable.io:443/reviews/cgeo/cgeo/5635#-KEXK_pMPjq3C0ZIxZMN:-KEXK_pMPjq3C0ZIxZMO:-1503935795) ([raw file](https://github.com/cgeo/cgeo/blob/54e5ee6290437620e34bb39649f481e656ad49e9/main/src/cgeo/geocaching/CgeoApplication.java#L70)):*
This is a great enhancement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cgeo/cgeo/5635)*

**Comment by kumy** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[main/src/cgeo/geocaching/CgeoApplication.java, line 70 \[r1\]](https://reviewable.io:443/reviews/cgeo/cgeo/5635#-KEXKhsL74ejAh8xzS7E:-KEXKhsL74ejAh8xzS7F:819725511) ([raw file](https://github.com/cgeo/cgeo/blob/54e5ee6290437620e34bb39649f481e656ad49e9/main/src/cgeo/geocaching/CgeoApplication.java#L70)):*
Just a test message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cgeo/cgeo/5635)*

**Comment by kumy** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cgeo/cgeo/5635#-:-KEXLcB3LB8dmjnaNOn7:1417088721)*

**Comment by kumy** [comment]
CI: ok to test

**Pull request merged**
