### PR TITLE
Fix #5759, New map: "Store Offline" not shown

### LINKED ISSUE #5759: New map: "Store Offline" not shown
##### Detailed steps causing the problem:
- Enable new map
- Open live map
- wait till all visible caches are loaded
- Open menu

##### Actual behavior after performing these steps:
- No "Store Offline" menu entry is shown

##### Expected behavior after performing these steps:
- Menu "Store Offline" is shown

##### Version of c:geo used:
Reported via `2016.05.29-NB-fb50e95

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

##### Other comments and remarks:
Reported by a user via c:geo Fanpage on Facebook. I can reproduce it.

### PR DESCRIPTION
**Pull request by rsudev**
- implemented check for loading activity
- implemented handover of visible caches to storing process

Please give it a short cross-check, if possible.

### CODE REVIEW

**Comment by rsudev** [comment]
I'll check the codacy issue tomorrow

**Comment by samueltardieu** [comment]
Is that supposed to give you a "Store as list" menu? It doesn't on my phone.

**Comment by rsudev** [comment]
You should have a 'Store offline' menu entry (once the loading was completed), which, when selected, would either directly store or ask for a list selection, depending on your settings.

**Comment by samueltardieu** [comment]
I don't.

photo_2016-08-09_14-39-34

**Comment by Bananeweizen** [comment]
Just a side note: Also in the old map this is only available after loading finished.

**Comment by samueltardieu** [comment]
Loading had finished. No menu entry  though.

**Comment by rsudev** [comment]
There is another condition that has to be met to show this item (also on the old map) - there need to be unstored caches on the map. Was that the case for you or had all caches already been stored?

**Comment by samueltardieu** [comment]
Nope. None were stored in a list. However, since think this condition should be removed now that caches can be in multiple lists.

**Comment by rsudev** [comment]
Revisiting your screenshot I caught the reason for the menu not appearing - the caches that are cached in the database, are (falsely) not counted as 'not stored'.
If your suggestion to remove that check reaches consensus, this would be easily solvable...

**Comment by pstorch** [comment]
+1 for always show `Store as list`

**Comment by Bananeweizen** [comment]
Fine with the suggestion of always showing. It was previously disabled to avoid the same confusion like after GPX import with the old lists: Caches from moving from one list to another.

**Comment by rsudev** [comment]
Will resubmit, likely rather against master

**Pull request closed without merging**
