### PR TITLE
Allow the user to display a combination of all available offline map files

### PR DESCRIPTION
**Pull request by jonas-koeritz**
Added a new map source that displays a combination of all map files available in the map file directory. This allows users to download less map data if they just need several states or a few countries combined.

The screenshot shows my LiveMap with a map from Denmark and Germany showing simultaneously.

`OfflineMultiMapSource.getFileName()` is a bit rough but there don't seem to be any downsides to just returning the first map files name.

photo5256059635884993639

### CODE REVIEW

**Comment by jonas-koeritz** [comment]
This also would need translations for the menu item.

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/mapsforge/v6/layers/MultiRendererLayer.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4816814&bid=16018087)

**Comment by Lineflyer** [comment]
Does this combined setting then include all map files found in the folder?
Any limitation on amount of map files or in terms of performance?
What happens with overlapping areas (as usually e.g. adjacent countries have some miles map into the neighbor country)?

**Comment by jonas-koeritz** [comment]
The screenshot is a place where normally both maps would have an overlap. The tile rendering is working fine there. There doesn't seem to be noticable a performance hit, Mapsforge does a lookup which mapfiles can serve the tile in question and draws all ways and POIs. There is also an option to draw on first hit or deduplicate. Deduplication might hurt the performance though (I haven't tried).

**Pull request merged**
