### PR TITLE
Extend scaling options

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Extend map scaling options (experimental)

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by ztNFny** [comment]
Interesting. D/T markers are broken though 
image

**Comment by ztNFny** [comment]
> Interesting. D/T markers are broken though image

missing ", scalingFactorCacheIcons" in line 736:
insetsBuilder.withInset(new InsetBuilder(R.drawable.marker_rating_fg, scalingFactorCacheIcons));

What do you have in mind for the settings UI? A slider 50-200?

**Comment by ztNFny** [comment]
Oops, those icons are not just used on map but everywhere:
image
image

**Comment by moving-bits** [comment]
> Interesting. D/T markers are broken though
> missing ", scalingFactorCacheIcons" in line 736: insetsBuilder.withInset(new InsetBuilder(R.drawable.marker_rating_fg, scalingFactorCacheIcons));

thanks, I'll look into this

> What do you have in mind for the settings UI? A slider 50-200?

For now I started with a "hidden feature" to do some testing, but when we are going public with this, it'll be a slider probably, and 50-200 would be a valid range.

> Oops, those icons are not just used on map but everywhere:

Yeah. Initially the use-case I was thinking of was to support visually impaired people - font sizes are scaling, cache/waypoint icons are not. But your post made me rethink this. I see at least two different use-cases, and they need to be handled differently:
- enlarge icons to help visually impaired people => scaling of icons should happen everywhere in the app
- shrink icons to "see more of the map", but still have the details of the regular icons => scaling should happen on the map only

This could be solved by a switch whether to apply the scaling "everywhere" or "on map only.

I'll try to dive into this over the next days.

**Comment by ztNFny** [comment]
Visually impaired will need more than larger icons. I think that's already solved by the global Android density settings. And our map is pretty unusable for visually impaired anyway, nothing that larger icons could fix. 
So I think it's down to the second usecase.

**Review by ztNFny — COMMENTED** [review]
may I suggest to call "forMap" parameter "scaled" or "withScaling" or something along the lines?

You're not scaling dot icons, is that by intention?

**Comment by moving-bits** [comment]
> may I suggest to call "forMap" parameter "scaled" or "withScaling" or something along the lines?

changed it to `applyScaling`

> You're not scaling dot icons, is that by intention?

yes (so far) - the dot icons are already pretty small, scaling them further down could make them unreadable, IMHO. But let's see how it works out in daily use

**Pull request merged**
