### PR TITLE
Sort country filter list, remove unused db fetch implementations

### PR DESCRIPTION
**Pull request by jakedot**
Alternative to #8278

Cleaned up alternative implementations.

### CODE REVIEW

**Comment by bekuno** [comment]
ok to test

**Comment by jakedot** [comment]
codacy did already work but it seems @Lineflyer has to do the oking for build?

**Comment by moving-bits** [comment]
Crashes on startup when run in Android 4.x emulator:

```
05-01 16:08:47.415 2966-2966/? E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
        at cgeo.geocaching.CgeoApplication.onCreate(CgeoApplication.java:60)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
        at android.app.ActivityThread.access$1300(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoClassDefFoundError: cgeo.geocaching.storage.-$$Lambda$Y1zJdY_6ykQ3CqKNUai9tiYQJNA
        at cgeo.geocaching.storage.DataStore.<clinit>(DataStore.java:3431)
        at cgeo.geocaching.CgeoApplication.onCreate(CgeoApplication.java:60) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
```

Following the crash report the IDE marks some parts as being API level 24+ only:
image

Please update your PR to work with either API 16+ (if we want to merge it to the next release, which will become legacy version soon), or at least to API 21+ if we want to merge this to the version after the next release (which will not be part of legacy any more).

**Comment by jakedot** [comment]
All right, sorry, I didn't have those SDKs configured and was working on 28/29 - why wouldn't the IDE consistently warn me about using incompatible features?

**Comment by moving-bits** [comment]
I can only see those two red curly lines beneath `Comparator.comparing` and `thenComparing` in the IDE - don't know if there's some more prominent visual indicator available, or even something to stop compilation, if breaking changes are used without a version-checking if/then/else around it.

**Comment by bekuno** [comment]
ok to test

**Comment by jakedot** [comment]
@bekuno the trigger seems to still be broken

**Comment by moving-bits** [comment]
> @bekuno the trigger seems to still be broken

@Lineflyer  Can you look into this? Thx.

**Comment by bekuno** [comment]
> 
> 
> > @bekuno the trigger seems to still be broken
> 
> @Lineflyer Can you look into this? Thx.

I'm configure/testing it

**Comment by bekuno** [comment]
ok to test

**Comment by bekuno** [comment]
> 
> 
> ok to test

@Lineflyer @moving-bits 
Seems now to work after adding my user to the PR admins. I added also @moving-bits.
@moving-bits please test it on the next PR of jakedot.

**Comment by moving-bits** [comment]
@bekuno Thanks for updating the config!

**Comment by jakedot** [comment]
I don't think the failing build has anything to do with my changes. I'm still a bit confused about it all... 😐

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
@jakedot Thanks for tackling the issues, seems to run now on Android 4.x as well.

**Pull request merged**
