### PR TITLE
DT indicator in CachePopup

### PR DESCRIPTION
**Pull request by ztNFny**
A quick stab at adding the circle marker to popup to fix https://github.com/cgeo/cgeo/issues/15505
image

### CODE REVIEW

**Comment by eddiemuc** [comment]
I like it.
Maybe a tiny bit larger?

**Comment by ztNFny** [comment]
> I like it.
> Maybe a tiny bit larger?

Not easily done. The scaling is hardcoded in MapMarkerUtils.

I can do it afterwards if this PR is well received, otherwise too much work to invest.

**Comment by SammysHP** [comment]
Also `D` and `T` are kind of redundant with the labels. Not sure what lead to the removal of the stars, but I think the numbers plus a graphical representation like the stars or a bar graph would be better.

Of course this PR is still an improvement!

**Comment by moving-bits** [comment]
while I see the resemblance with the markers on the map, I think the visual identifier is too small here, so not that much gain over the pure textual representation. IMHO the proposal of @bekuno given in https://github.com/cgeo/cgeo/issues/15505#issuecomment-2016784459 would be easier to grap quickly.

**Comment by ztNFny** [comment]
as none of the alternatives proposed gained any track I went ahead and adjusted the size of the D/T marker in the popup to match that of the log icons.
PR is ready to merge then.

image

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
Retest this please

**Pull request merged**
