### PR TITLE
update mocked cache files used in MockedCache (fix #10439)

### LINKED ISSUE #10439: Update mocked data for GC2JVEH
Due to website changes we should update the mocked data (best for all mocked pages)

### PR DESCRIPTION
**Pull request by moving-bits**
Update the five cache pages used in `MockedCache`

### CODE REVIEW

**Comment by Lineflyer** [comment]
on my way to fix the lint issue...I have overseen it while merging translations.

**Comment by Lineflyer** [comment]
retest this please

Should be green now hopefully

**Comment by Lineflyer** [comment]
@moving-bits 
THe blocking lint error is fixed, but it seems the new mocked data needs adaption in other test caes which are user specific in that mocks.

**Comment by moving-bits** [comment]
Yeah, it's pretty frustrating currently... It's a good thing that they cleanup their HTML a bit, but it breaks so many things...

I guess for this PR to work I will wait for #10443, do a rebase, and see what's left.

**Comment by Lineflyer** [comment]
> I guess for this PR to work I will wait for #10443, do a rebase, and see what's left.

Yep, lets do it "agile". Only some steps away from success.

**Comment by moving-bits** [comment]
Ok, remaining failing tests are related to cache owner, which is #10454, so I guess this one here is ready for merge.

**Pull request merged**
