### PR TITLE
Rel to #13761: Refactor/reorganize cgeo code structure 

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #13761:  Refactor/reorganize cgeo code structure

**DO NOT SQUASH THE COMMITS IN THIS PR ON MERGE!!!!! USE "REBASE AND MERGE"!!!**

### CODE REVIEW

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
I am puzzled. Although I changed the Jenkinsfile to new paths...

image

...those paths doesn't seem to be used in Jenkins:

image

If the Jenkinsfile is not used, why are we maintaining any at all? Shouldn't we then rather delete it from repo?

I can't resolve this on my side, no access to Jenkins. I will wait a few hours for reaction, and if none is given I will revert the name change of "main" to "app" (I can then do this in a later PR). @Lineflyer , @bekuno, @mucek4 ?

**Comment by bekuno** [comment]
> I can't resolve this on my side, no access to Jenkins. I will wait a few hours for reaction, and if none is given I will revert the name change of "main" to "app" (I can then do this in a later PR). @Lineflyer , @bekuno, @mucek4 ?

Now you should have login rights to CI.

The jenkins script is not in use, and was not as long as I know. Don´t know why. Maybe it was not finished.
At CI are some dedicated scripts and direct scripts configured, and there are filters for results.

For now I would therefore say, that it is better to stay with the old name and do the renaming in a single step later.

**Comment by eddiemuc** [comment]
> For now I would therefore say, that it is better to stay with the old name and do the renaming in a single step later.

Agree. I will then switch "back" to the other PR :-)

**Comment by moving-bits** [comment]
Thanks @eddiemuc for diving into this issue. I'm in no way capable of doing an actual review here, as my experience with Android programming is coming from c:geo only. Nevertheless I did a quick test of this PR in my environment:
- Program compiles fine
- no problems detected during a short run of the program
- the following files remain in the source tree and need to be (re)moved manually:
  - main/cgeo.geocaching_preferences.xml
  - main/res/values/keys.xml
  - main/build

  Those files are not part of git, but we should leave a notice for the devs somewhere.
- the problem described in https://github.com/cgeo/cgeo/discussions/13606 is _not_ resolved
- "Project source files" view in AS is broken:
  image
  ("main" contains the left over files, should probably be removed; "app" is missing)
  "Project files" view does work, though, for both app's sources and tests, so it's maybe just a need to work a bit differently.
- tests do run, but 9 tests fail (although logged in as PM)

Another question springs into mind: If we implement this PR on `master`, will it co-exist with the different structure in `release`?

BTW: I did a short test locally, squashing the two commits into one (`git reset HEAD~1`, `git commit -a --amend` etc.), and retrieving history in AS (with right click on selected source, git, show history for selection) still did work.

**Comment by eddiemuc** [comment]
@moving-bits thanks for your feedback, I will answer in PR #13768 and abandon this PR. Reason: CI seems to have larger problems with its scripts when renaming "main" to "app". Thus I leave folder at "main" and continue with the other PR.

**Pull request closed without merging**
