### PR TITLE
Switch to Gradle 7.x

### PR DESCRIPTION
**Pull request by bekuno**
The update of AS to 2020.3.x is possible without update of gradle/AGP.
This PR should merged after the core team updated AS.

Also WhereYouGo works with AS 2020.3.x with the current gradle/AGP configuration.

With AS 2020.3.x we can use gradle 7 and AGP 7.
Details:
- update gradle 6.8.3 to 7.3.3
- Follow up:
  - addd new lint rule checkDependencies true
  - check - checkstyle relation must be ordered

### CODE REVIEW

**Comment by moving-bits** [comment]
Somehow build complains about some Checkstyle findings:

```
 [ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/cgeo/geocaching/settings/TemplateTextPreference.java:5:1: Extra separation in import group before 'cgeo.geocaching.R' [ImportOrder]
22:17:26  [ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/cgeo/geocaching/settings/TemplateTextPreference.java:5:1: Wrong order for 'cgeo.geocaching.R' import. [ImportOrder]
22:17:27  Checkstyle rule violations were found. See the report at: file:///home/jenkins/slave/workspace/cgeo-CI_PR-build/main/build/reports/checkstyle/checkstyle.html
22:17:27  Checkstyle files with violations: 1
22:17:27  Checkstyle violations by severity: [info:2]
```

Maybe a rebase to current `master` is required?

**Comment by moving-bits** [comment]
I've fixed the Checkstyle issue in `TemplateTextPreference`, so a rebase should do the trick now.

**Comment by bekuno** [comment]
> Somehow build complains about some Checkstyle findings:
> 
> ```
>  [ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/src/cgeo/geocaching/settings> ```
> 

They are only info messages, so this should not prevent the PR to merge.

I tested last days if it is valid in checkstyle to have a space line before the static imports, but this isn't.

**Comment by bekuno** [comment]
The build fails with
~~~
22:18:03  > Task :main:lintAnalyzeBasicDebug FAILED
22:18:03  Could not deserialize /home/jenkins/slave/workspace/cgeo-CI_PR-build/main/build/intermediates/incremental/lintAnalyzeBasicDebug to a lint model: java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException
...
FAILURE: Build failed with an exception.
22:18:10  
22:18:10  * What went wrong:
22:18:10  Execution failed for task ':main:lintAnalyzeBasicDebug'.
22:18:10  > A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
22:18:10     > Internal error: Unexpected lint invalid arguments
~~~

I searched for the reason (also in the web) and tested different possible solutions, but up to now I was not able to find one.
The class `org/xmlpull/v1/XmlPullParserException` is part of the Android API (see https://developer.android.com/reference/org/xmlpull/v1/XmlPullParserException), there are no changes.

The problem appears in the AGP - it is running with AGP 4.2.2.

Has someone an idea?

**Comment by Lineflyer** [comment]
When building on my machine with current `master`(including this PR) it still claims:

image

Why, and why does it state 4.2.2 as current version?

**Comment by bekuno** [comment]
This is for the AGP (Android Gradle Plugin), not for Gradle.
Sadly does c:geo does not compile for AGP 7.x.
See https://github.com/cgeo/cgeo/pull/12307#issuecomment-991926539

**Comment by Lineflyer** [comment]
Should we open this as dedicated issue then (or is there already one)?
Thanks @bekuno for taking care of those updates.

**Pull request merged**
