### PR TITLE
Remove calendar plugin leftovers

### PR DESCRIPTION
**Pull request by Lineflyer**

### CODE REVIEW

**Comment by moving-bits** [comment]
GitHub says "1 file changed" and lists "cgeo-calendar/build.gradle" for it, but with "no changes"?

**Comment by bekuno** [comment]
You should remove the folder cgeo-calendar completely.

Please also edit the .gitignore file.

**Comment by Lineflyer** [comment]
> You should remove the folder cgeo-calendar completely.

I did this already in my first commit AFAICS. See also my branch, where the PR is based upon. There is no cgeo-calendar directory anymore.

> Please also edit the .gitignore file.

Done.

**Comment by bekuno** [comment]
The remote branch looked ok to commit.
After commit the folder is gone.

**Pull request merged**
