### PR TITLE
offer "open log in browser" also for trackables

### PR DESCRIPTION
**Pull request by fm-sys**
grafik

~The only flaw in my implementation is, that the title doesn't look very nice with this very long log id. But we can either leave it like this (hey, it's only about trackables ;-) ), remove the log id also for caches completely from the title or need to introduce some magic (-> e. g. only show id's shorter than 10 characters)~

### CODE REVIEW

**Comment by eddiemuc** [comment]
Iirc the log id in title was not so much wanted anyway, so I would suggest to remove it (maybe display log date instead?)

**Comment by fm-sys** [comment]
> 
> 
> Iirc the log id in title was not so much wanted anyway, so I would suggest to remove it (maybe display log date instead?)

Done! I've decided to just remove the log id without adding the date instead. The reason is, that the date is already displayed outside the popup, so it would be an unnecessary and space-costing duplicate without any benefit...

**Comment by fm-sys** [comment]
retest this please

**Comment by fm-sys** [comment]
retest this please

**Comment by fm-sys** [comment]
Don't know yet why the tests are failing. I will look into it, but no more today. Setting "do not merge" for now...

**Comment by fm-sys** [comment]
OK, ready from my side. Should we include it to the SAF beta? It's IMHO in no way a critical change, but I'm also fine with waiting...

**Comment by eddiemuc** [comment]
I would vote to include it. I don't see how it is related to SAF (so no disturbance to be feared) and it is a nice new feature

**Comment by Lineflyer** [comment]
Nice addon, why not.

**Pull request merged**
