### PR TITLE
Enhance map long click functionality (fix #12361, fix #13104)

### LINKED ISSUE #12361: Pick up coordinates from map
### Tell us your idea!

Request from user at support:

It's cumbersome having to create a waypoint or user-defined cache on map just to get coordinates for a specific point.

### What solution would you suggest?

Display a movable cross on the map (on demand) and display the cross's coordinates. Moving the cross by dragging it around updates the coordinates.

### Is there an alternative?

_No response_

### Additional Information

ticket number 685604

### LINKED ISSUE #13104: Allow adding map points to individual route directly
### Tell us your idea!

Often, to plan a route, you need to add intermediate points on the map.

Currently, as a workaround, I just create custom caches in the places I want, and then plan the route from custom cache to custom cache.

However creating custom caches involves lots of unnecessary taps.

### What solution would you suggest?

I never ever use custom caches for anything else than the above described use.

So as an alternative to custom caches, when long pressing the map, it would be cool, if could just drop small map markers, like sticking a "needle" into a map. Creating another needle should just require a long tap and not open any new window. Just the needle appears.

And once you have dropped all needles, you can then plan a route from needle to needle.

### Is there an alternative?

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by fm-sys**
This implementation brings several improvements:
- Create a UDC, even when a cache target is currently set
- Place WPs / UDCs more precisely
- Add a location to the individual route without having to create a WP / UDC first (#13104)
- Copy map coordinates (#12361)
- Make long-tab on map less disturbing (#12821)
- Fix inconsistency between GMap/Mapsfore when setting a cache as target while being at the live map

grafik

Currently only implemented for Mapsforge Map, therefore setting WIP...

### CODE REVIEW

**Comment by moving-bits** [comment]
Really like the idea, thanks!

WRT to #12361 it would be nice to display the coordinates as well, so that you can give them to another geocacher, enter them in you car's navigation system etc.

Additionally, can you implement it for `UnifiedMap` as well? Would be great if we directly add new features to `UnifiedMap` as well to not loose functionality on some future switch and to avoid having to re-check all PR whether they include some stuff relevant for `UnifiedMap`.

**Comment by fm-sys** [comment]
Here we go...

|||
-|-
grafik|grafik

**Comment by moving-bits** [comment]
> > Additionally, can you implement it for UnifiedMap as well?
> 
> Does `UnifiedMap` already have a tap-handler interface at all? Otherwise it could be difficult to implement 😅

Not yet. It would be great if you could extend it as needed. Feel free to ask if you need any info on how things are related for `UnifiedMap`.

Until recently `UnifiedMap` did not much more than displaying a blank map, maybe tracks and routes. With recent changes it can be called from a cache detail page and displays a single cache, but no interaction yet. And no stored list of caches either.

> EDIT: For sure, I'm willing to port this feature to `UnifiedMap` - however, I think it is too early for this step. It would IMHO make much more sense to implement general geocache loading into the UnifiedMap first, before starting with such advanced stuff. I can open an issue as a reminder and assign it to myself.

Understandable, and ok for me as well. WRT to cache loading: I guess we should start discussing on how to handle different map types. I'd like to handle things a bit more explicitly as it is currently, therefore introduced `UnifiedMapType` with (potentially) more distinct types than today's map state. We need to collect a list of map types we want to support, and what our expectations are wrt to the map in relation to the different map types, e. g.
- setting zoom level
- setting position
- using filter
- setting title
- displaying or hiding waypoints for the caches
- ...

One more thing we should discuss is how to handle cache lists: Currently we take a list of caches that are part of a list, and call the map with a list of geocodes. The map then does not know any longer which list this is coming from. One thing being missed because of this is to be able to switch cache lists directly in map view. I see two possible alternatives for this:
- instead of passing a list of geocodes to the map, pass the info (map type) "cache list" and the list's id to the map, and let the map handle cache loading etc. - possible drawback: which filter should get applied to the map - map filter or last list filter?
- or pass a bunch of geocodes as today, but allow changing the list anyway, reloading the bunch of geocodes in this case.

I guess I'll open a discussion thread for those topics...

**Comment by fm-sys** [comment]
> We could additionally display the coordinates in a second format: DDD° MM' SS.SSS", as this is a very common format for car navigation systems.

Maybe use our click-to-switch-coordinate-format behavior? DDD.DDDD° is BTW often used as well...

> And we could add a button to "start navigation" which would open our navigation tool selector

I would put it into the context menu, not the coordinate dialog. Right?

**Comment by moving-bits** [comment]
sounds reasonable to me (both)

Would it be possible to integrate the coordinate display into the first popup as well (to avoid the extra tap), or would it look to crammed? E. g.:

N 52° 00.000
E 013° 00.000
\-----------------
Add waypoint
Create user-defined cache
Add point to route
Start navigation

**Comment by fm-sys** [comment]
The context menu can only be styled with _very_ limited possibilities. One thing which would be possible is to set the coords as header text which would look quite good IMHO. 

A context menu with title would look like this:

Screenshot_20220608_135804_cgeo geocaching_copy_195x200


However, we cannot implement the coordinate format switching as the title doesn't has an OnClickListener. Do we really need to support multiple coordinate formats at all? The "my coordinates" textview in the MainActivity does only support one single format as well, and no one has ever asked...

**Comment by moving-bits** [comment]
I was thinking of putting a single or multi-line entry for the coordinates into the menu, tappable for format switching, and adding a menu divider (which we have in our home screen's menu), if possible.

Using a header for this may lead to truncation (remember the cache name in cache popup on map?) as well as not being able (at least, not without some ugly hacks) to add an `OnClickListener` to it.

My use-case for having the DDD° MM' SS.SSS" format is getting coords to enter in car navigation (or to give them to somebody else for her/him to enter in their car navigation), but there may be other use-cases as well.

**Comment by fm-sys** [comment]
> I was thinking of putting a single or multi-line entry for the coordinates into the menu

Never have seen that multi-line menu entries are possible... We could just add two menu entries. But this wouldn't look nice. 

> tappable for format switching

The menu will automatically close when clicking on it and I'm not aware of a possibility to suppress this behavior.

So if you really need multiple formats we will probably have to stay with the dialog.

**Comment by fm-sys** [comment]
I just found out what android provides two totally different implementations for exactly the same UI component.

- Context Menu
- Popup Menu

Currently I'm using a Context Menu in this PR. However it seems, that the Popup menu can be utilized more flexible that a context menu which is bound to an specific activity. I will do some experiments...

Links for myself:
https://stackoverflow.com/questions/29726039/how-to-prevent-popup-menu-from-closing-on-checkbox-click/
https://stackoverflow.com/questions/13444594/how-can-i-change-the-position-of-where-my-popup-menu-pops-up

**Comment by ztNFny** [comment]
I've added another menu item: "Add point to route (as first target)" to add a point at index 0 to the route.
Are you open to me pushing this to your branch? Otherwise I'll wait until you're done here.

I'll also take a look at an icon that fits better with our map icons.

**Comment by fm-sys** [comment]
> Are you open to me pushing this to your branch? 

@ztNFny  Would be ok for me. 

Although I generally like to keep PR's as small as possible, it's IMHO fine in this case. Especially as I already added multiple new menu items anyway...

**Comment by ztNFny** [comment]
@fm-sys pushed. If there's any problems with it please discard.

**Comment by fm-sys** [comment]
Maybe we can use a shorter string? Problem is that menu entries can only be single line and will be truncated if necessary. 

 

E.g. `Add point to route start` or `Add point to beginning of route` instead of `Add point to route (as first target)`

Out of interest @ztNFny: 
Do you plan to add this functionality for caches/WPs as well (not only for empty locations)? This should however go into a separate PR and needs to be aligned with #13122.

**Comment by ztNFny** [comment]
> Do you plan to add this functionality for caches/WPs as well (not only for empty locations)? 

Yes. But not sure about the UI part yet. It was easy enough to add here so I started with this. I don't want to make adding caches to routes harder, so need to investigate some possibilities here. Maybe have it in cache pop-up menu ...

**Comment by fm-sys** [comment]
Yes, indeed difficult. Maybe a long click on "set as target"? However, this would be hard to find...

**Comment by fm-sys** [comment]
Rebased.

BTW, I added a "navigate" menu entry as well:

grafik

**Pull request merged**
