### PR TITLE
set darker background for dark mode (fix #10752)

### LINKED ISSUE #10752: Material theming: background color way too light
IMHO the new / current background color is way too light. While I agree that a pure black is too dark, the color should be a dark gray instead of light gray (as it was before at some places).

| Gmail | c:geo | pure black |
|-|-|-|
| grafik | grafik | grafik |

I would suggest using the "GMail" color theme (-> swap/adapt action bar and background color inside c:geo)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Set the background color #FF202020 as suggested in https://github.com/cgeo/cgeo/issues/10752#issuecomment-848974727

Result would be like this:
image.image.image

And in conjunction with #10764 it would look like this:
image.image

### CODE REVIEW

**Comment by Lineflyer** [comment]
Thats looks already much more nice IMHO also in combination with the accent outlined buttons.

**Review by Lineflyer — APPROVED** [review]

**Comment by fm-sys** [comment]
The Signal messenger uses `#121212` and in another app I saw `#141414`. I think `#FF202020` is still a bit to light compared to other apps which use dark mode. Would it be possible to compare these tree colors?

**Comment by fm-sys** [comment]
OK, just a quick draw via MS Paint:
`#202020` vs. `#141414` vs. `#121212`
grafik

These are no original emulator pictures, so not be confused why the action bar icons look that ugly...

I am of course aware that these are only very slight nuances, about which no one ever thinks again later on. Nevertheless, I would prefer the middle one ;-)

**Comment by Lineflyer** [comment]
Yup, #141414 looks good and its the middle one. Let's use that for the beginning I would say.
BTW: A lighter action bar looks good together with this IMHO...but that just another topic.

**Comment by eddiemuc** [comment]
#141414 looks fine. #121212 would also be ok for me.

**Comment by fm-sys** [comment]
`#303030` would IMHO be corresponding action bar color for `#141414`

Actionbar color can be adopted via: (there might be different ways though)

```
<style name="cgeo" parent="...">
      <item name="actionBarStyle">@style/ActionBarStyle</item>
      ...
</style>


<style name="ActionBarStyle" parent="Widget.MaterialComponents.Light.ActionBar.Solid">
    <item name="background">@color/mycolor</item>
</style>

```

Or change the primary color, but this will AFAIK affect other components as well...

**Comment by moving-bits** [comment]
Will this parent

> <style name="ActionBarStyle" parent="Widget.MaterialComponents.Light.ActionBar.Solid">

work for both light and dark theme?

(I'm asking because it has a `.Light.` in its name, and I don't know how those themes work wrt to day/night mode. And we do want to stay with a single theme for both dark and light mode...)

**Comment by fm-sys** [comment]
Not sure... But there are some other ActionBar themes which we can use as base... (don't know the exact difference between them)

grafik

**Comment by moving-bits** [comment]
Set background color to #141414, ActionBar background color to #303030 and ActionBar title text color accordingly, using the same colors in light and dark theme. Works for regular themed activities, map, popup and settings:

|dark theme|light theme|
|---|---|
|image|image|
|image|image|
|image|image|
|image|image|

Seems ok to me except the cache popup, as suddenly the transparent background got lost, although I've changed nothing in that are. I'll dive into that, but wanted to share the screenshots with you anyway.

**Comment by fm-sys** [comment]
Wow, looks really nice IMHO 🤩👍

**Comment by moving-bits** [comment]
Ok, found a way to get transparency back for the map's popup:

image

PR is now ready to merge from my side, if CI is happy.

**Comment by fm-sys** [comment]
Just for light theme, we might need a lighter action bar background as soon as we use SVG which are pure black for light mode and pure white for dark mode. But this is kind of unrelated and can be changed easily in the future...

**Comment by moving-bits** [comment]
Haven't tried, but should be doable by moving the `colorBackgroundActionBar` to `colors_light.xml` / `colors_dark.xml` and adjusting colors as needed, at least that's the idea behind it. For now I'm using the same colors for both themes.

**Comment by fm-sys** [comment]
Yes, all fine. Please merge as soon as CI is green. I feel like I can't survive another day with current background 😅

**Pull request merged**
