### PR TITLE
rel to #13761: refactor main source directory structure

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #13761: refactor main source directory structure

**DO NOT SQUASH THE COMMITS IN THIS PR ON MERGE!!!!! USE "REBASE AND MERGE"!!!**

### CODE REVIEW

**Comment by eddiemuc** [comment]
PR is doing a (big) part of the move suggested in #13761 as a first step:
* "main/src" to "main/src/main/java"
* "main/res" to "main/src/main/res", "main/res.maplegends" to "main/src/main/res.maplegends"
* "tests/src" to "main/src/test/java"
* "tests/src-android" to "main/src/androidTest/java"
* "tests/res" to "main/src/androidTest/res"
* files in "tests" (AndroidManifest.xml") to "main/androidTest" 
* necessary adjustments in "main/build.gradle"
* Adds a first example of a new-styled instrumented test using Junit4 style code

Care was taken NOT to change anything (not a single byte!) in the files being moved. By leacing content untouched, this allows git and git tools to recognize these files are being MOVED and thus conserve their git history in viewers. This leads to several problems e.g. failing tests. Those must be fixed in a SEPARATE commit to preserve file git history. See https://vjeko.com/2020/11/24/understanding-renaming-moving-files-with-git/

**Comment by eddiemuc** [comment]
**DO NOT SQUASH THE COMMITS IN THIS PR ON MERGE!!!!! USE "REBASE AND MERGE"!!!**

**Comment by eddiemuc** [comment]
My project structure now looks like this:
image

I am still cleaning up a bit, but already I find the new structure a big step forward:
* FINALLY I can see and modify instrumented tests locally
* FINALLY I can start single instrumented tests instead of running only the whole stack at once
* An unexpected bonus: local checkstyle on whole module now takes seconds instead of minutes (as before)

Not everything is done right now (for example module "main" should be renamed to "app", there is still separate "thirdparty" source module and androidTest needs to access test sources due to hidden html resource files), this needs to be cleaned up too.

I would like to check this in. However, this is a big structural change and thus affects all devs -> so I really need feedback before I do.

**Comment by bekuno** [comment]
> * An unexpected bonus: local checkstyle on whole module now takes seconds instead of minutes (as before)

Its not a bonus, it is a malus.

You have to relocate the source folders in the checkstyle task configuration in `build.gradle` Line 696ff:
~~~
    source 'src'
    source '../tests/src'
    source '../tests/src-android'
~~~

**Comment by bekuno** [comment]
> Not everything is done right now (for example module "main" should be renamed to "app", there is still separate "thirdparty" source module and androidTest needs to access test sources due to hidden html resource files), this needs to be cleaned up too.

I´m glad that you started this work. Many thanks.

Renaming the `main` name to `app` or `cgeo-app` is a good idea.

The `thirdparty` tree should for now stay as is, imho.

Additionally, we should be aware, that the tests for `cgeo-contacts` are part of the test folders.
Are they run fine?

The README.md need adjustment at least for the c:geo icon and the section `API keys installation`.

After merge, our Wiki should be adopted, if necessary.

**Comment by eddiemuc** [comment]
> > * An unexpected bonus: local checkstyle on whole module now takes seconds instead of minutes (as before)
> 
> Its not a bonus, it is a malus.
> 
> You have to relocate the source folders in the checkstyle task configuration in `build.gradle` Line 696ff:
> ~~~
>     source 'src'
>     source '../tests/src'
>     source '../tests/src-android'
> ~~~

Damn you're right...

**Comment by eddiemuc** [comment]
Good points you make. In will work on them

> Renaming the `main` name to `app` or `cgeo-app` is a good idea.

Agree, but in a second step/PR

> The `thirdparty` tree should for now stay as is, imho.

Really? There's just one code file in it, and it was modified at least to a cgeo package...

> Additionally, we should be aware, that the tests for `cgeo-contacts` are part of the test folders.
> Are they run fine?

I did not check this specifically, but all tests run without error. Will check again and keep an eye on this.

> The old `tests` structure is obsolete, imho.
> The script `/tests/scripts/update-trackables` can be moved to `/main/src/androidTest/` .

Is it needed at all? What is it used for?

> The README.md needs adjustment at least for the c:geo icon and the section `API keys installation`.

Agree

> As the source folder is moved, the `crowdin.yml` need adjustment (`/main/res/...)`.

Agree

> After merge, our Wiki should be adopted, if necessary.

Agree

**Comment by eddiemuc** [comment]
Updates:
* I am afraid there seems not to be a single test for cgeo-contacts. All tests in fomer tests/src and tests/src-android seem to be related to cgeo main app (however, on a different note: why not integrate the cgeo-contacts plugin into main app? I believe permission management is much more flexible these days)
* I will try to include renaming of "main" into "app" as well. This needs to be carefully planned (all moves in one commit, all changes in another -> so git keeps history), so I will start over a new PR. I will mark this PR as "do not merge" in the meantime

**Comment by eddiemuc** [comment]
@moving-bits 
> * the following files remain in the source tree and need to be (re)moved manually:  
>   * main/cgeo.geocaching_preferences.xml
>   * main/res/values/keys.xml
>   * main/build

Good point. To be on the save side I added a line into .gitignore so no leftover keys.xml is accidentally committed.
   
> * the problem described in [Several classes not found by Android Studio 2021.2+ #13606](https://github.com/cgeo/cgeo/discussions/13606) is _not_ resolved

Thats sad, I really hoped that AS is just choking on our strange project structure (it does on my machine).

> * "Project source files" view in AS is broken:
>   image
>   ("main" contains the left over files, should probably be removed; "app" is missing)
>   "Project files" view does work, though, for both app's sources and tests, so it's maybe just a need to work a bit differently.
> * tests do run, but 9 tests fail (although logged in as PM)

"app" is no longer existing (remains "main"), now it looks fine to me:

image

> 
> Another question springs into mind: If we implement this PR on `master`, will it co-exist with the different structure in `release`?

I am sure it will create hiccups when merging from one to another. If this is merged and master stabilized I would suggest to merge master to release and do a new beta quickly.

> BTW: I did a short test locally, squashing the two commits into one (`git reset HEAD~1`, `git commit -a --amend` etc.), and retrieving history in AS (with right click on selected source, git, show history for selection) still did work.

I followed the advise on https://vjeko.com/2020/11/24/understanding-renaming-moving-files-with-git/. The way I understand this article is that as long as files are only moved (not changed) within one commit then git can easily recognize moves. However, if file is moved AND changed, then it gets harder and more heuristic for git (may or may not fail). I don't want to risk using history based on such heuristics.

**Comment by eddiemuc** [comment]
Waiting for more feedback before merging

**Comment by bekuno** [comment]
> I am sure it will create hiccups when merging from one to another. If this is merged and master stabilized I would suggest to merge master to release and do a new beta quickly.

Do we have something in release only to be worth a new release?

Is there something on master which will be problematic for a new beta/release?

**Comment by eddiemuc** [comment]
> > I am sure it will create hiccups when merging from one to another. If this is merged and master stabilized I would suggest to merge master to release and do a new beta quickly.
> 
> Do we have something in release only to be worth a new release?

Couple of small fixes, nothing too serious IMHO: #13763, #13748, #13742, #13434, #13619

> Is there something on master which will be problematic for a new beta/release?

The obvious new thing on master is the new image gallery, but this is ready for beta release imho. Apart from that, we released only a short time ago (25.11.) with some time to find serious prod bugs (which did not occur). Also, not much feature development currently happening. When would be a better time for a bigger refactoring?

**Comment by fm-sys** [comment]
>> Do we have something in release only to be worth a new release?
>
> Couple of small fixes, nothing too serious IMHO: #13763, #13748, #13742, #13434, #13619

Still worth a quick bugfix, which should be quite uncritical. Afterwards we could directly start with the beta... What do you think?

**Comment by moving-bits** [comment]
I can prepare a bugfix release tonight. I suggest to wait a few days after releasing it to see if anything serious comes up, then prepare a new beta (maybe on Dec 25th?).

Only thing we could into before releasing a bugfix version - if someone has an idea how to tackle it - is the change for bookmark lists (already got a ticket in support for it).

**Comment by eddiemuc** [comment]
Naturally, everything merged to master will create merge conflicts on this PR (because all source files are moved). This has already started unfortunately. When would be a good time to merge?

**Comment by eddiemuc** [comment]
This PR is no longer mergeable, and resolving conflicts across all files is meaningless. Needs to be create anew.
I leave it open for me as reference (copying things to change). I try to ease burden of later "big change" by doing (and checking in) smaller preparation changes step by step

**Comment by moving-bits** [comment]
> This PR is no longer mergeable, and resolving conflicts across all files is meaningless. Needs to be create anew. I leave it open for me as reference (copying things to change). I try to ease burden of later "big change" by doing (and checking in) smaller preparation changes step by step

Sorry, that's been me syncing CrowdIn in preparation of yesterday's release.

If we plan to release a beta on Dec 25th, we should merge a new PR at least one day before, to have it in the nightlies for a day or so. And between creating this PR and merging it, no other PR (including CrowdIn) should be merged, on neither branch. If you plan to break it down into smaller PR (if meaningful), please give us a sign when to stop and when to resume merging other PR.

**Comment by eddiemuc** [comment]
> Sorry, that's been me syncing CrowdIn in preparation of yesterday's release.

No problem

> If we plan to release a beta on Dec 25th, we should merge a new PR at least one day before, to have it in the nightlies for a day or so. And between creating this PR and merging it, no other PR (including CrowdIn) should be merged, on neither branch. If you plan to break it down into smaller PR (if meaningful), please give us a sign when to stop and when to resume merging other PR.

I created two smaller PRs today which are "harmless" in relation to the "big move". I will merge them right now and prepare a "big move" PR. I will prepare it in a way that I can easily recreate it in case we can't merge it (because other things might have to be merged first).

**Comment by eddiemuc** [comment]
No longer valid...

**Pull request closed without merging**
