### PR TITLE
 fix #9332: remove all restrictions for initial map zoom

### LINKED ISSUE #9332: [Nightly] Low map zoom is always reset to specific zoom level
**Describe the bug:**
A short while ago we had the problem that zoom levels >100 m (i. e. 200 m, 500 m, 1 km ...) were reset to 100 m in subsequent map calls, which has been corrected with #9293. But while this is working perfectly fine, it's now (or perhaps even then?) the other way round: zoom levels <100 m (i. e. 50 m, 20 m, 10 m ...) are reset to 100 m in subsequent OSM map calls ...

In GM it's nearly the same, only difference: in GM and GSat the magic limit is even 200 m.

**To Reproduce:**
1. open any map view (no matter if Live map or cache map)
2. zoom until the scale shows "50 m"
3. leave map
4. re-enter map

**Actual behavior/state after performing these steps:**
If OSM was selected, zoom scale will be reset to 100 m, with GM/GSat it will even be reset to 200 m

**Expected behavior/state after performing these steps:**
Zoom should be constant over subsequent calls. 

**Version of c:geo used:**
2020.11.01-NB-cd04617

**Is the problem reproducible:**
Yes

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #9332: remove all restrictions for initial map zoom, comment code for future coders taggling this area

### CODE REVIEW

**Review by fm-sys — CHANGES_REQUESTED** [review]
If we decide to remove the max zoom level completely, it doesn't make any sense to get the maximum of 0 and the previous zoom level. Or did I missed something? But the current code looks a bit over complicated...

**Comment by eddiemuc** [comment]
> If we decide to remove the max zoom level completely, it doesn't make any sense to get the maximum of 0 and the previous zoom level. Or did I missed something? But the current code looks a bit over complicated... 

Ok I can simplify this, hopefully tomorrow

**Comment by eddiemuc** [comment]
> > If we decide to remove the max zoom level completely, it doesn't make any sense to get the maximum of 0 and the previous zoom level. Or did I missed something? But the current code looks a bit over complicated...
> 
> Ok I can simplify this, hopefully tomorrow

Done

**Review by fm-sys — APPROVED** [review]
👍

**Pull request merged**
