### PR TITLE
adapt cache type detection to website change (rel. to #10421)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Adapts our code to the website change of cache detail page regarding the cache type. It's now referenced using the waypoint type instead of the type guid.

## Related issues
related to #10421, but not completely fixing it, as there is also a change regarding the cache owner.

### CODE REVIEW

**Comment by Lineflyer** [comment]
Failing test seem to be caused by the remaining owner problem?!

**Comment by moving-bits** [comment]
> Failing test seem to be caused by the remaining owner problem?!

The first two, yes. But the third is failing as cache pages without login do not provide the "nearby caches of this type" link which I used for type detection. I've updated the PR to use the cache symbol svg identifier which seems to use the waypoint id as well, and is also present when you're not logged in. Let's see if this works for the tests...

**Comment by moving-bits** [comment]
There was another problem with the mocked data, as somehow the date format got interpreted differently, so that mocked data and actual data could not be made comparable any longer. I've adapted the date strings in the mocked data, and so the third test is also working again.

Now only the owner-related tests still fail (as to be expected).

**Comment by Lineflyer** [comment]
Merging to test the fix.
Thanks @moving-bits

**Pull request merged**
