### PR TITLE
Switch to AndroidX (fix #7748)

### LINKED ISSUE #7748: Move to AndroidX
I think c:geo should move from the Android Support libraries to AndroidX as soon as possible, maybe we should even create a GitHub project for that.
The Support Libs won't be there forever and AndroidX offers cleaner interfaces for development.

Switching to AndroidX is also a required prerequesite for using the Room persistence library, which would be a good fit for a complete rewrite of the DataStore backend which, according to checkstyle, currently contains some of the most complicated and error prone code in c:geo.

### PR DESCRIPTION
**Pull request by bekuno**
fixes #7748 (Move to AndroidX )

- in addition to the automatic changes (and manually polish)
  - edit checkstyle rule: ImportOrder; add androidx group after android
  - it was necessary to update butterknife, use newest (10.2.0)
  - replace ButterKnife.findById by findViewById (findById was removed in ButterKnife)
  - remove unused: main\thirdparty\android\support\v4\app\FragmentListActivity.java

### CODE REVIEW

**Comment by pstorch** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=4644521&bid=15556067)

**Comment by bekuno** [comment]
Did you checked especially for failure in the migration from ButterKnife.findById to findViewById?
I had some mistakes, maybe I had missed one.

On AndriodX are all libraries version independent.
See https://developer.android.com/jetpack/androidx/versions
So no variable is needed.

**Comment by moving-bits** [comment]
> Did you checked especially for failure in the migration from ButterKnife.findById to findViewById?
> I had some mistakes, maybe I had missed one.

Do you want to replace all `ButterKnife.findById` by `findViewById`? Then there are at least 28 more files to go... ;-)
(28 files having the string `ButterKnife.findById` at least once, a couple more if you look for `findById` only.)

> On AndriodX are all libraries version independent.

Are you sure? The webpage you linked to ([developer.android.com/jetpack/androidx/versions](https://developer.android.com/jetpack/androidx/versions)) lists several version numbers, eg `1.1.0` for appcompat and annotation (which we both use), but `1.0.0` or `2.1.0` for others.

**Comment by bekuno** [comment]
Because the method ButterKnife.findById is not more implemented we had to change ButterKnife.findById(class, id) to class.findViewById(id)

The migration to AndroidX classes was done by AndroidStudio. 
Maybe not targeting the latest version of the libraries. I will check it tomorrow.

**Comment by moving-bits** [comment]
@bekuno  Is this ready for merge already, or are you working on something?

**Pull request merged**
