### PR TITLE
Upgrade build tools and android support annotations

### PR DESCRIPTION
**Pull request by UniQP**
This change is [Reviewable](https://reviewable.io/reviews/cgeo/cgeo/5597)

### CODE REVIEW

**Comment by rsudev** [comment]
I is (luckily) only the support annotatins, which are upgraded here (should be safe). Upgrading the support library would require some more work...

**Comment by UniQP** [comment]
I adapted the commit message accordingly.

**Comment by Bananeweizen** [comment]
According to the pull request build, the necessary version of build tools is not yet installed.
```
00:13.920  * What went wrong:
00:13.925  A problem occurred configuring project ':cgeo-calendar'.
00:13.928  > failed to find Build Tools revision 23.0.3
```
http://ci.cgeo.org/job/cgeo%20pull%20request/196/console

@samueltardieu or @kumy, will you always have to upgrade the SDK parts manually or can we make it "install everything new automatically"?

**Comment by kumy** [comment]
@Bananeweizen I've setup a Jenkins Job to upgrade Android SDK.
But this upgrade isn't permanent. Local images have to be rebuilt by executors maintainer.

**Comment by kumy** [comment]
Please, do not merge until https://github.com/cgeo/cgeo-executor/issues/6 has been effectively closed

**Comment by samueltardieu** [comment]
Retest this please

**Comment by samueltardieu** [comment]
Retest this please.

**Comment by kumy** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cgeo/cgeo/5597)*

**Comment by kumy** [comment]
https://github.com/cgeo/cgeo-executor/issues/6 has been closed. This may now be merged.

**Comment by kumy** [comment]
Let's merge. And force a test build on @mucek4 CI.

**Comment by kumy** [comment]
Test build is http://ci.cgeo.org/job/cgeo%20nightly/123/console

**Pull request merged**
