### PR TITLE
extend map settings to hide archived caches and/or certain waypoints

### LINKED ISSUE #5118: Option for hiding specific waypoint types
Quite often users ask to add more customization to the live map by being able to hide some types of waypoints:

Original Coordinates:
Most of the time the listing coords of mystery caches are "meaningless". It is good to have them as a waypoint (also for the function to restore them) but they might clutter the map

Parking waypoints:
While those are meaningful if you use a car and watch a single cache map, they might overcrowd the map in a dense city area on live map if you have saved several caches.

Visited waypoints:
If a waypoint of a cache is marked as "Visited" I probably have no need to see them on the map anymore.

I do also see a benefit in doing this, so I suggest the following:
In Setting - Map we do have a section called "Map Content" where also the waypoint limit is set.
Some checkboxes could be added at this point in the menu:
- Hide "Original Coordinates"
- Hide "Parking Waypoints"
- Hide waypoints marked as "Visited"

This setting should then be used on all live maps (but not on other maps e.g. when mapping waypoints of a single cache).

Follow up of #1530 (will be closed),

### LINKED ISSUE #7848: Add "Hide archived" option to map settings
**Is your feature request related to a problem?**
I like to keep all of my own caches in cgeo, even the ones that have been archived.
However, these are all shown on the map making it unusable.

**Describe the solution you'd like**
Under map-settings, there could be a "Hide archived" option (There is a "Hide disabled" option but I still want to see live caches that are disabled).

**Describe alternatives you've considered**
There could be a flag added to each list to say "Don't show caches in this list on the map".

### PR DESCRIPTION
**Pull request by moving-bits**
Add a separate menu entry "hide" in maps' dot menu for the new options to
- hide archived caches
- hide original waypoints
- hide parking waypoints
- hide visited waypoints

and move the existing options to
- hide own/found caches
- hide disabled caches

to the same menu.

fixes #7848
fixes #5118

For updated screenshots see below.

Change: The impact from "exclude disabled" gets split: Until now it checked for both disabled and archived, now it only checks for disabled, and check for archived is separated. For migration purposes, the default value for "exclude archived" is set to the value of "exclude disabled".

### CODE REVIEW

**Comment by moving-bits** [comment]
One thing I'm uncertain about is whether we want to have all six "hide" options in the map settings menu, which gets quite long by that, or whether we want to move those six options to a new menu, maybe called "map hide settings" or something like that. What do you think?

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/MapUtils.java  3
- main/src/cgeo/geocaching/maps/CGeoMap.java  8
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4885541&bid=16184856)

**Comment by Lineflyer** [comment]
Nice.
My personal preference would be a sub menu "Hide" (german: Ausblenden) for all those items, as I also like it tidy.

Another question I stumble upon sometimes on support:
Any technical possibility to seperate owned and found in two items.AFAIR there was some technical limitation why we could not do this in the past.May be it changed due to the new live map implementation.

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java  8
- main/src/cgeo/geocaching/maps/CGeoMap.java  8
- main/src/cgeo/geocaching/maps/MapUtils.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4885541&bid=16184856)

**Comment by Lineflyer** [comment]
Another point:
We should think about the desired strategy of where to show the options:
The hide owned/found is contained in map settings on map as well as settings/Cache-Details in the settings menu.

Here my personal preference would also be to have the new items also doubled as my proposed strategy is: Settings menu keeps all settings. Other parts of the app may offer shortcuts to some related settings.

**Comment by moving-bits** [comment]
> We should think about the desired strategy of where to show the options:
> The hide owned/found is contained in map settings on map as well as settings/Cache-Details in the settings menu.
> 
> Here my personal preference would also be to have the new items also doubled as my proposed strategy is: Settings menu keeps all settings. Other parts of the app may offer shortcuts to some related settings.

Understandable

> Thinkins about it again: As the new options only make sense in the live map context we might need to think again about that...

IMHO the current settings path is misleading, as the "hide own/found" and "hide disabled" options are on the cache details settings page, but act on the map content. Wouldn't it be more fitting to put them into the map => content section? (Including the new options)

**Comment by moving-bits** [comment]
> My personal preference would be a sub menu "Hide" (german: Ausblenden) for all those items, as I also like it tidy.

done

> Another question I stumble upon sometimes on support:
> Any technical possibility to seperate owned and found in two items.AFAIR there was some technical limitation why we could not do this in the past.May be it changed due to the new live map implementation.

That's a different task, which we need to investigate. (Isn't there a separate issue for that already?) I haven't looked thoroughly yet, but there are some code passages already with two different parameters for "hide found" and "hide owned", so at least on some places gc.com seems to be able to differentiate between the two. Don't know about all places, though, and also for the other connectors.

**Comment by Lineflyer** [comment]
> 
> IMHO the current settings path is misleading, as the "hide own/found" and "hide disabled" options are on the cache details settings page, but act on the map content. Wouldn't it be more fitting to put them into the map => content section? (Including the new options)

No, because they act on all parts of the app (e.g. searches).

**Comment by Lineflyer** [comment]
> hat's a different task, which we need to investigate. (Isn't there a separate issue for that already?) I haven't looked thoroughly yet, but there are some code passages already with two different parameters for "hide found" and "hide owned", so at least on some places gc.com seems to be able to differentiate between the two. Don't know about all places, though, and also for the other connectors.

Yes, there should be an issue for that AFAIR. So lets keep that separated.

**Comment by Lineflyer** [comment]
> done

LGTM

**Comment by moving-bits** [comment]
> > IMHO the current settings path is misleading, as the "hide own/found" and "hide disabled" options are on the cache details settings page, but act on the map content. Wouldn't it be more fitting to put them into the map => content section? (Including the new options)
> 
> No, because they act on all parts of the app (e.g. searches).

oh, yes, you're right. Those two are more widespread (and the new "hide archived" as well).
The waypoint related work different, though - they only filter for the map.
So, should we put them on two different pages, then?

**Comment by jakedot** [comment]
@Lineflyer: > My personal preference would be a sub menu "Hide" (german:
Ausblenden) for all those items, as I also like it tidy.

Maybe call it "Visibility / Sichtbarkeit"?

I agree that a new submenu would be nice!
Thanks for implementing this, I wanted it for some time now!

**Comment by Lineflyer** [comment]
> oh, yes, you're right. Those two are more widespread (and the new "hide archived" as well).
> The waypoint related work different, though - they only filter for the map.
> So, should we put them on two different pages, then?

The overall in "cache details" setting, the map related in "Map"...makes sense, or not?

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java  8
- main/src/cgeo/geocaching/maps/MapUtils.java  3
- main/src/cgeo/geocaching/maps/CGeoMap.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4885541&bid=16184856)

**Comment by moving-bits** [comment]
> We should think about the desired strategy of where to show the options:
> [...]
> Here my personal preference would also be to have the new items also doubled as my proposed strategy is: Settings menu keeps all settings. Other parts of the app may offer shortcuts to some related settings.

done: "exclude archived" in "cache details", the other three in "map" => "map content"

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java  8
- main/src/cgeo/geocaching/maps/CGeoMap.java  8
- main/src/cgeo/geocaching/maps/MapUtils.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4885541&bid=16184856)

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/maps/mapsforge/v6/NewMap.java  8
- main/src/cgeo/geocaching/maps/MapUtils.java  2
- main/src/cgeo/geocaching/maps/CGeoMap.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4885541&bid=16184856)

**Comment by andrixnet** [comment]
How about separate selection for: 
Hide found
Hide own

**Comment by Lineflyer** [comment]
Thats often wanted by users but AFAIR we had an issue for that and it was closed as not technically possible as those two are combined on the search pages on server used by cgeo.

**Comment by moving-bits** [comment]
We should recheck whether the technical limitation still exists - gc.com has changed their API quite a lot throughout the last years.

But for that, a separate issue should be opened instead of adding requests to already merged or closed issues, as the new things might easily get lost.

**Comment by eddiemuc** [comment]
Quick check on GC.com reveiled that they have separate filters for
* Caches found / not found
* Caches owned / not owned
* Caches enabled / disabled

Can't tell you how long those are already in place though

**Comment by andrixnet** [comment]
Regardless of the GC.com API ... 
I can't fathom how one caching provider site API can affect display rules for all other sites, including offline stored caches. 
This is a display filtering, not a live fetching filtering. And must be, since it has to affect the display of offline caches.
Thank you.

**Comment by andrixnet** [comment]
I mean this display filtering has to work with "LIVE=disabled" as well ...

**Pull request merged**
