### PR TITLE
#6781 Fixed: Blank section crash

### PR DESCRIPTION
**Pull request by S-Bartfast**
#6781 Fixed: Blank section crash

### CODE REVIEW

**Comment by pstorch** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
I don't understand why Codacy has issues with this PR...and I don't even see issues in their review report.

**Comment by pstorch** [comment]
Interesting. Codacy reports 2 new issues, but the issues tab on the report is empty. But if you open the changed file in the codacy report you see 9 issues and 2 new. When I interpret it correctly it's about the missing space after the comma in lines 585 and 586.

**Comment by pstorch** [comment]
I've sent them a message about this report. Let's see.

**Comment by S-Bartfast** [comment]
Huh, just realised there was indeed a couple of missing spaces in there.  At first I thought it was being silly about the comma in the string argument `","` so just ignored it but now i see it was actually complaining about the comma before the empty string `,""` which I have now fixed.

**Comment by S-Bartfast** [comment]
At first I thought it was being silly about the comma in the string argument `","` so just ignored it but now i see it was actually complaining about the comma before the empty string `,""` which I have now fixed.

**Comment by S-Bartfast** [comment]
Opps, didn't mean to do that. How do I cancel the close?

**Comment by S-Bartfast** [comment]
Okay, got it.

I did click just the "Comment" button first but it took a while to react and I thought nothing happened so I then tried the other one ("Close and comment").  I now see how easy it is for people to accidentally close issues without meaning to 😊

**Comment by Bananeweizen** [comment]
I cannot judge the correctness of the change. However, I'm wondering why we are having the validation code in this class at all. Wouldn't it be more useful to instead invoke one of the parsers inside the GeopointParser class instead? Those have been finetuned a lot and also deal with corner cases. Especially if we already know which format is currently active in this dialog, we could easily invoke the matching parser (MinDecParser etc.) instead of going through the Geopoint constructor based on 6 to 8 String arguments.

**Comment by S-Bartfast** [comment]
>I'm wondering why we are having the validation code in this class at all.

Well, it's there because to begin with I really didn't have a good handle on how things worked so I essentially just copied it directly out of the "Add Waypoint" dialog.  At the time I new it wasn't a 'good' move but didn't want to rearrange anything external to my class.  Even just doing preliminary testing made me aware the parser has many short comings and figured a proper over hall would no doubt be necessary at some stage.  I guess that time is about to come...

>Wouldn't it be more useful to instead invoke one of the parsers inside the GeopointParser class instead?

Almost certainly.  I've tried to follow exactly what goes on inside that parser a few times but each time I've just got so completely lost that I've just thrown my hands up in despair.  I'll create a separate ticket to address parsing more generally.

**Comment by S-Bartfast** [comment]
Okay, I just implemented a better solution which exclusively uses the 'Plain' format parser.

This solution is a lot neater and actually works quite well however, as discussed in #6716, it has the unfortunate side effect of zero padding groups after the decimal point with trailing (rather than leading) zeros:
image

**Comment by S-Bartfast** [comment]
Okay, a fix for #6716 has been submitted, now we'll just have to work out whether it was a "bug or a feature" ;)

**Comment by pstorch** [comment]
@S-Bartfast thanks

**Pull request merged**
