### PR TITLE
Update functional graphic

### PR DESCRIPTION
**Pull request by fm-sys**
#8786 part 1

cgeo_functional_graphic

### CODE REVIEW

**Comment by fm-sys** [comment]
What do you think about it?

**Comment by Lineflyer** [comment]
I would leave out the orange parts.

How about placing our new logo someehere on the left, and leaving text and background unchanged. Of course the new screenshot is needed as in your proposals, as the older was outdated from its content and UI.

**Comment by fm-sys** [comment]
It would look like this...

cgeo_functional_graphic

**Comment by Lineflyer** [comment]
IMHO much better in the second version.
I am however far away from being a designer, but I would place the logo on same height left of the c:geo text.

But let others also provide some feedback first :)

**Comment by fm-sys** [comment]
2020-08-13 14_01_45-PowerPoint-Bildschirmpräsentation  -  c;geo playstore bilder pptx (Benutzerdefiniert)

I'm not sure this looks better...

**Comment by Lineflyer** [comment]
@SammysHP Do you know which font we originally used or with font looks rather similar?
I dont' remember, but I can try to look into the shirt designer.

**Comment by Lineflyer** [comment]
Addon:
Found a resource link for our shirts which also contains two fonts.
@fm-sys Will forward via mail.

**Comment by SammysHP** [comment]
Do you mean the font in the logo? The original font is unknown. Not sure which font I used in my recreation, but I think we can also use a different font.

**Comment by fm-sys** [comment]
| c:geo's font (looks like it's the same as on the logo) | first draft font |
|-|-|
2020-08-13 15_44_59-PowerPoint-Bildschirmpräsentation  -  c;geo playstore bilder pptx (Benutzerdefiniert) | 2020-08-13 14_01_45-PowerPoint-Bildschirmpräsentation  -  c;geo playstore bilder pptx (Benutzerdefiniert)

**Comment by Lineflyer** [comment]
IMHO the left font is the one to use.

**Comment by fm-sys** [comment]
There is one last thing we need to discuss - the font size: 
I would choose the lage font, because the functional graphic is displayed quite small in playstore

| lage font | font size as my pictures before |
|-|-|
Folie7 | Folie6

**Comment by Lineflyer** [comment]
The small font looks a bit lost on the background. I think the larger font is appropriate.

**Comment by Lineflyer** [comment]
BTW: The background is a different one to the old one. The old one has a bite more contrast, thus it would be IMHO better. But I am not sure if we have this graphic somehwere.

**Comment by Lineflyer** [comment]
Another BTW:
We once produced a graphic for a facebook group (not associated with us)....when you are on it and find some time:
grafik

**Comment by fm-sys** [comment]
> The old one has a bite more contrast, thus it would be IMHO better.

I'm afraid I couldn't go along with that. I think it is important to have a certain recognition value and since we have already used this graphic on our website and in c:geo itself, I think it is the only right thing to use the graphic here as well...

**Comment by Lineflyer** [comment]
> I'm afraid I couldn't go along with that. 

Fair enough. Lets stay with your proposal, then everything is aligned.

**Comment by moving-bits** [comment]
Hi @fm-sys, I really like what you're doing here on the graphics side - gives c:geo a more modern touch on its web presences. As for the font: I can look up the font we had used for the t-shirt and send you the font name.

**Comment by fm-sys** [comment]
It already *is* the font from the t-shirts... @Lineflyer had sent them to me...

**Comment by moving-bits** [comment]
@fm-sys 
Is this PR ready to merge from your side?

**Comment by fm-sys** [comment]
Yes, ready to go...

**Comment by moving-bits** [comment]
> Yes, ready to go...

Ok, then let's merge it... Thanks for your contribution!

**Pull request merged**
