### PR TITLE
use owner displayName (according to cache details) to query owner actions

### LINKED ISSUE #7125: Owner actions not working
##### Detailed steps causing the problem:
- Open OC cache (e.g. OC1120A)
- Click on owner name to invoke context menu

##### Actual behavior after performing these steps:
The context title shows an ID rather than the user name
All associated actions (e.g. show hides) return no results

##### Expected behavior after performing these steps:
I guess this should rather use the owner name instead of the user ID to work as intended

##### Version of c:geo used:
2018.08.22-NB

##### Is the problem reproducible for you?
Yes

### PR DESCRIPTION
**Pull request by bekuno**
fix #7125 Owner actions not working

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
@mucek4 The latest PR builds does not finish mit ok (1 ends with a timeout error).
Can you check if Jenkins is running fine?

**Comment by Lineflyer** [comment]
Is it intentional that you push to gmapv2 branch?

**Comment by Lineflyer** [comment]
BTW: You should be able to access the CI yourself.
IMHO you should also be able to login and access more details.

**Comment by bekuno** [comment]
> Is it intentional that you push to gmapv2 branch?

Yes. The idea was that we in this way do not need to push to master and gmapsv2 branch, because master is on the way to release.
If you want the I change the base branch to master.

**Comment by Lineflyer** [comment]
Might be that CI is not yet fit for gmapsv2 branch state.
I think we should still use master as master until we merge gmapsv2 into it.

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
@Lineflyer Now both PR are happy with base master.

**Pull request merged**
