### PR TITLE
synchronize viewport calculation in GMv2 (fix #8401)

### LINKED ISSUE #8401: ConcurrentModificationException in Viewport.containingGCliveCaches
From Google Play flagged as new with beta version 2020.05.31-RC
Android 9+10, currently only 2 reports

```
java.util.ConcurrentModificationException: 
 
  at java.util.LinkedHashMap$LinkedHashIterator.nextNode (LinkedHashMap.java:757)
 
  at java.util.LinkedHashMap$LinkedKeyIterator.next (LinkedHashMap.java:780)
 
  at cgeo.geocaching.location.Viewport.containingGCliveCaches (Viewport.java:211)
 
  at cgeo.geocaching.maps.CGeoMap.doDownloadRun (CGeoMap.java:1442)
 
  at cgeo.geocaching.maps.CGeoMap.access$2700 (CGeoMap.java:112)
 
  at cgeo.geocaching.maps.CGeoMap$DownloadRunnable.runWithMap (CGeoMap.java:1414)
 
  at cgeo.geocaching.maps.CGeoMap$DoRunnable.run (CGeoMap.java:1542)
 
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
 
  at java.lang.Thread.run (Thread.java:919)
```

### PR DESCRIPTION
**Pull request by moving-bits**

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
Failing test is unrelated to this PR. Related message is the most notified error in current beta, therefore let's merge to see if this fix works.

**Comment by Lineflyer** [comment]
I merged this change up to master as well and currentlz producing a new nightly. As I am on vacation a new RC needs to wait until next weekend, unless someone else steps in.

I will however use the nightlies here to see whether there are any side effects of this change.

**Pull request merged**
