### PR TITLE
Bump androidx.browser:browser from 1.4.0 to 1.5.0

### PR DESCRIPTION
**Pull request by bekuno**
see https://github.com/cgeo/cgeo/pull/13969

For ReleaseNotes see https://developer.android.com/jetpack/androidx/releases/browser#version_15_2

Important changes since 1.4.0

 - Added CustomTabsIntent.Builder#setInitialActivityHeightPx, which allows developers to specify the initial launch height of a Custom Tab, and optionally the resize behavior (fixed or resizable).
 - Added CustomTabsIntent.Builder#setToolbarCornerRadiusDp which allows developers to specify the toolbar's top corner radius. 
 - Added CustomTabsIntent.Builder#setCloseButtonPosition which allows developers to set the position of the close button on the toolbar. 
 - Added an onActivityResized callback method to interface CustomTabsCallback to let developers know when a Custom Tab is resized. 
 - Make parts of CustomTabsCallback APIs asynchronous. 
 - Populates the current app's language in Accept-Language by default to align to Android’s per-app language experience.
 - Added @RequiresPermission to APIs that require granting the POST_NOTIFICATIONS permission on SDK 33 and above.

### CODE REVIEW

**Comment by bekuno** [comment]
The ftp-stud.hs-esslingen.de is currently not reachable, therefor the `testMapsforge` fails.

**Comment by moving-bits** [comment]
> The ftp-stud.hs-esslingen.de is currently not reachable, therefor the `testMapsforge` fails.

seems to be on and off currently, local run for that test failed once, then worked again for me

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
