### PR TITLE
Remove old mapsforge (fix #7836)

### LINKED ISSUE #7836: Remove old mapsforge v3
Looking at the remaining [open issues dealing with the new mapsforge implementation](https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Map+OSM%22) it might be time to decide upon retirement of the old mapsforge implementation rather soon.
Although there is no urgent need at this moment, it is also a matter of testing and maintaining. Not sure e.g. how the old mapforge library will work when raising or compile and target SDK. 

IMHO all real critical regressions are fixed by now. What do you think?

### PR DESCRIPTION
**Pull request by moving-bits**

### CODE REVIEW

**Comment by moving-bits** [comment]
This is a first working solution:
- settings, preference keys and strings for mf0.3 removed
- lots of mf0.3 related code removed
- mf0.3 library removed

Untangling GMv2 code from old CGeoMap can be done in a separate PR, if needed.

**Comment by Lineflyer** [comment]
Setting "Do not merge" as (as far as I understood the idea) we want to merge branches first giving users a notice period.

**Comment by moving-bits** [comment]
rebased to current master to stay up-to-date

**Comment by moving-bits** [comment]
Now that branches are prepared for a new beta this PR can be merged into master.

**Comment by Lineflyer** [comment]
As there was no objection over the last 3 weeks, lets merge it. 
Thanks @moving-bits

**Pull request merged**
