### PR TITLE
Fix #6395, Additional waypoints don't show up when live disabled

### LINKED ISSUE #6395: Additional waypoints don't show up when live disabled
##### Detailed steps causing the problem:
- have a list with caches
- make sure live is disabled 
- open new map for this list
- zoom in to a cache with additional waypoints (e.g. parking coordinates) 

##### Actual behavior after performing these steps:

- no additional waypoints show up

##### Expected behavior after performing these steps:

- additional waypoints show up

##### Version of c:geo used:
 Nightly developer version 

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: ONEPLUS A3003 (OnePlus3, OnePlus)
Android version: 7.0
Android build: ONEPLUS A3003_16_170208
Cgeo version: 2017.03.09-562efa7 developer build
Google Play services: enabled - 10.2.98 (448-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd.MM.yyyy
Installed cgeo plugins: contacts
--- End of system information ---

```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

### PR DESCRIPTION
**Pull request by rsudev**

### CODE REVIEW

**Comment by rsudev** [comment]
It is not yet fully working as expected. I plan to revisit this topic in the next days, so comment if you feel like it, but do not merge yet

**Comment by Lineflyer** [comment]
I really appreciate you are working on the map topics...really cool.
Did you see my comment on this crash problem...its really very annoying

**Comment by Bananeweizen** [comment]
Just added the tag according to your own request, not to express an opinion of mine. :)

**Comment by rsudev** [comment]
@Lineflyer: I have seen it. As my own impression reqgrding this crash was that it happens very infrequent I did not look deeper, but can now do so. Do you meanwhile have a clear-cut reproduction scenario?
@Bananeweizen Thanks!

**Comment by Lineflyer** [comment]
@rsudev Will add a step-by-step into the other issue.

**Comment by rsudev** [comment]
I was again too fast...

**Comment by rsudev** [comment]
If someone has time for a second look, I would appreciate that. Otherwise I will test on my device a little more and merge the next days for expanded testing (unless I again come across a major omission on my side)

**Comment by Lineflyer** [comment]
From my side feel free to merge, so I will test the nightlies.
Question:
Does this fix also involve or change the behaviour as documented in #5900 ?

**Comment by rsudev** [comment]
I think I'll merge and create a follow up to track some improvement ideas.
Regarding #5900, no this is not addressed with this change (and requires some more changes in the background/infrastructure to get solved in a performant fashion.

**Pull request merged**
