### PR TITLE
refactor quick settings popup to BottomSheetDialog (fix #10663)

### LINKED ISSUE #10663: Make Map settings pop-up a BottomSheetDialogFragment based on Material Design Guidelines
Signal has the new possibility to select the image size, which makes use of a so-called "bottom sheet". They are very intuitive and easy to use, as they appear at the bottom of the screen and are therefore easy to reach...

Screenshot_20210517_151911

Something like this I would really like to see for our quick settings pop-up too. (But it could be, that BottomSheets are only available as soon as we use material design theme)

Some links:
- The related commit in the Signal repo: [signalapp/Signal-Android@dd934e0](https://github.com/signalapp/Signal-Android/commit/dd934e0095197b30d760a4a12441381606f0d39f#diff-deda9be468ee329c8ea37e626318c07af1f148c546537c06f5b090cf5c19f3f5)
- https://medium.com/@kosta.palash/using-bottomsheetdialogfragment-with-material-design-guideline-f9814c39b9fc
- A very extensive description: https://material.io/components/sheets-bottom

### PR DESCRIPTION
**Pull request by fm-sys**
See #10663 for more information...

| half screen | full screen |
|-|-|
| grafik|grafik|

This is codewise quick and thirty yet, but IMHO the result looks very intuitive and modern...

Setting WIP for now, as I plan to add some ~helper classes~ generalized methods for it, so that it can be easily reused (e.g. for #8793 - might be interesting for @MagpieFourtyTwo ;-))

### CODE REVIEW

**Comment by Lineflyer** [comment]
Nice in general...just I am struggeling with the total black background (also in the new filter) instead of some lightend black (or dark grey). But thats a more general topic when it comes to refactoring our styles/themes.

**Comment by fm-sys** [comment]
> just I am struggeling with the total black background (also in the new filter) instead of some lightend black (or dark grey).

I don't like this background as well, but I wanted to keep things unified. It's the same background as used for lists, cache details, ........ nearly everywhere. 


BTW, what do you think: Could this also be used for a more modern cache details popup at our live map or even for advanced filtering? Just thinking...

**Comment by Lineflyer** [comment]
> BTW, what do you think: Could this also be used for a more modern cache details popup at our live map or even for advanced filtering? Just thinking...

Yes, it could be an option for a map popup replacement...see #3932

**Comment by Lineflyer** [comment]
> or even for  advanced filtering?

Such functions however IMHO deserve a dedicated fullscreen.

**Comment by fm-sys** [comment]
> > or even for  advanced filtering?
> 
> Such functions however IMHO deserve a dedicated fullscreen.

It is also possible to launch the BottomSheetDialog directly as full screen. 
However, they feel much more integrated. E.g. you can close them via a swipe down gesture, which is a large benefit especially on larger screen sizes. 

But this discussion is totally off topic, let's continue it somewhere else as soon as we have some testing experience with BottomSheetDialogs for Quicksettings and PN...

**Comment by moving-bits** [comment]
Thanks @fm-sys for exploring new UI/UX features, very welcomed. I've gave it a quick tour in the emulator, and some questions come to my mind:
- What is the advantage of having a BottomSheetDialog? From what I understand it may be easier to close on larger displays as you can use swipe down instead of having to use the arrow in the title bar. (But you could still use the back button.) OTOH you'll have more "work" for opening the dialog, as you still have to press the button, and then do another swipe to fully open the dialog (which some users may not recognize, and therefore missing some of the options).
- In the past we had some discussion (and even a minimal prototype) for displaying cache info as a fragment at the bottom of the window, supporting swipe up to expand on more info. Would that clash with this dialog?
- Since now the full width is used, the checkboxes and their "labels" are pretty far apart. We may need to rearrange them to show more clearly which belongs to what.
- Unrelated to the ButtomSheetDialog: I would put the new filter button into the dialog's actionbar, currently it's using pretty much space.
- BTW: Dialog title does not work well with light theme. IIRC we already have opened an issue for that.

image

**Comment by eddiemuc** [comment]
> Unrelated to the ButtomSheetDialog: I would put the new filter button into the dialog's actionbar, currently it's using pretty much space.

For this specific part, please see #10659

**Comment by fm-sys** [comment]
> * What is the advantage of having a BottomSheetDialog? From what I understand it may be easier to close on larger displays as you can use swipe down instead of having to use the arrow in the title bar. (But you could still use the back button.) 

Remember the many support mails "I can't close the quick settings pop-up". We meanwhile have the back button in the pop-up, but this is more a rather ugly workaround. And to be honest, I sometimes struggle with closing the popup as well. 

Good UX is often just a unconscious feeling. "it works" vs. "It's fun to use the intuitive ui" 


>OTOH you'll have more "work" for opening the dialog, as you still have to press the button, and then do another swipe to fully open the dialog (which some users may not recognize, and therefore missing some of the options).

Our current popup is that large, that you have to scroll on most devices anyway. But users would never expect, that they can scroll in a alert dialog, while they are already firm with the BottomSheetDialog (e.g. From Google maps) 

Furthermore, I explicitly implemented a "you can swipe up"-indicator / action button on the left (unfortunately only visible in dark theme currently), which is the way how it is recommended by material.io (and they have done much very good research) 

> 
> * In the past we had some discussion (and even a minimal prototype) for displaying cache info as a fragment at the bottom of the window, supporting swipe up to expand on more info. Would that clash with this dialog?

That wouldn't be a problem, as long as we don't want to show them both at the same time. ;-) 
> 
> * Since now the full width is used, the checkboxes and their "labels" are pretty far apart. We may need to rearrange them to show more clearly which belongs to what.

Could be. Maybe we can enlarge the outer margins 
> 
> * Unrelated to the ButtomSheetDialog: I would put the new filter button into the dialog's actionbar, currently it's using pretty much space.
> 

This is IIRC strongly dissuaded by material. But the map activity has much room as well...
> * BTW: Dialog title does not work well with light theme. IIRC we already have opened an issue for that.

I will fix this...

**Comment by MagpieFourtyTwo** [comment]
> Our current popup is that large, that you have to scroll on most devices anyway.

Hmm ... "most devices" I usually see have screens with 6 inches and more ... thus leaving plenty of room ...

**Comment by fm-sys** [comment]
> 
> 
> > Our current popup is that large, that you have to scroll on most devices anyway.
> 
> Hmm ... "most devices" I usually see have screens with 6 inches and more ... thus leaving plenty of room ...

That's true, but for these devices the "more work (click + swipe) for opening the dialog" argument probably isn't true as well ;-)

**Comment by fm-sys** [comment]
grafik

I'm now using the action bar color which we have at other places as well...

**Comment by fm-sys** [comment]
> OTOH you'll have more "work" for opening the dialog, as you still have to press the button, and then do another swipe to fully open the dialog (which some users may not recognize, and therefore missing some of the options).

It's possible to launch directly in fullscreen mode as well, so we can change the behavior later on if required (after some testing in the nightlys)

**Comment by MagpieFourtyTwo** [comment]
Looks really nice, in general, like it - apart from the longer ways, the fingers have to go now, these increased significantly:
In order to e. g. change the routing strategy, it was just three taps with really short distances between them before.
But now, in order to close the "popup", you either have to go to the upper end of the screen or make a swipe down,
which must be long enough (and it must be *really* long), and has perhaps even to be repeated, if it was to short ...

Question: Would it be possible to decrease the minimum swipe distance needed to trigger the "close event" ...?

**Comment by Lineflyer** [comment]
You can also just click outside like with the old dialog.

**Comment by MagpieFourtyTwo** [comment]
Yes, I know - but there is just one "outside section" left (the one I meant with "the upper end of the screen"), instead of four.
And sp. the "bottom section", which was clearly preferred by the thumb, is gone.

**Comment by fm-sys** [comment]
> Yes, I know - but there is just one "outside section" left (the one I meant with "the upper end of the screen"), instead of four.
> And esp. the "bottom section", which was clearly preferred by the thumb, is gone.

The problem was that on some devices (e.g. my device) all these four sides were nearly totally obscured by the dialog, so closing via an outside click was nearly impossible. 

But I have struggled with closing the bottom dialog as well (feels a bit like if the dialog wantsq  to stay and always comes back up) 

> Would it be possible to decrease the minimum swipe distance needed to trigger the "close event" ...?

Even though I don't know about it yet, I firmly believe that nothing is impossible... :)

**Pull request merged**
