### PR TITLE
cross-convert cache markers to solve tinting issue

### LINKED ISSUE #11616: [vectorIcons] Wrong icon style in "Set cache icon"
Advanced > Set cache icon, the dialog shows the cache type icon in the upper right to set it to default. That currently shows a white icon on white background.

Should show colored background + white icon (same as #11592)

Current:
image

To be:
image
colored background + icon, no white marker

### LINKED ISSUE #11715: [vectorIcons] Wrong cache icon background color in "Create user-defined cache" dialog
Cache icon background should be yellow instead of orange

image

This is caused by (MaterialButton) dialogButton.setIconTint(null); in InternalConnector.java:interactiveCreateCache()

Fix should be the same as #11616

### PR DESCRIPTION
**Pull request by fm-sys**
fix #11715
fix #11616

grafik
grafik

### CODE REVIEW

**Comment by moving-bits** [comment]
Ah, double-conversion does the trick 👍 - I'd stopped after a single conversion yesterday, but did not find a method accepting a `Bitmap`... \*blush\*

Anyway. One thing I've stumbled upon, not sure if it's intentionally: 

If you create a new UDC, the icon has the hexagonal form (which is fine, as UDC connector has a hexagonal shape), but if you start selecting a user-defined icon for this new cache, it will have a round form in the EmojiUtils dialog.

Same happens if you are coming from a cache list. If you select a user-defined symbol, the cache marker is always round, independent from connector type.

If you want to change this, you could change the `EmojiUtils.selectEmojiPopup`'s parameter from `@Nullable CacheType` to `@Nullable Geocache`, so that you have the associated connector available.

**Comment by fm-sys** [comment]
> If you create a new UDC, the icon has the hexagonal form (which is fine, as UDC connector has a hexagonal shape), but if you start selecting a user-defined icon for this new cache, it will have a round form in the EmojiUtils dialog.

Yes, this is due to the fact that I currently only use the CacheType Marker - not the real geocache marker. I totally agree that the real cache marker would be more fitting, however, is there a way to get the cache marker without overlays (@ztNFny)?

**Comment by moving-bits** [comment]
> Yes, this is due to the fact that I currently only use the CacheType Marker - not the real geocache marker. I totally agree that the real cache marker would be more fitting, however, is there a way to get the cache marker without overlays (@ztNFny)?

In my tries yesterday I created a new temporary geocache in `EmojiUtils` using something like:
```
final Geocache tempCache = new Geocache();
tempCache.setType = cache.getType();
tempCache.setGeocode = cache.getGeocode();
```

with `cache` being the changed parameter of `EmojiUtils.selectEmojiPopup`.
Then you'll get a similar cache marker, but without overlays.

**Comment by ztNFny** [comment]
What exactly do you need? The base shape (white ... with outline) and the background shape both are defined by the connector. Background tint and foreground are defined by cache type.

I've implemented a helper function for the filter dialog to retrieve the background (circle) + tint + icon.

**Comment by ztNFny** [comment]
Clarificatiom: The difference between that helper function and the normal map marker is the white base shape. I don't think we need that in dialogs like "set icon" or filters.

**Comment by fm-sys** [comment]
> white base shape. I don't think we need that in dialogs like "set icon" or filters.

Well, it would be helpful to have it, as especially the blue mystery background is otherwise nearly invisible in dark mode...

**Comment by ztNFny** [comment]
Right, i forgot about dark mode. In light mode it looks great without the background.
Should it also be with base marker in filter dialog?

**Comment by fm-sys** [comment]
> Should it also be with base marker in filter dialog?

I think for the filters dialog it's fine as it is.

IMHO that's quite consistent:
White base shape -> always connector speciffic
without base shape -> general cachetype marker

**Comment by ztNFny** [comment]
Ok, so what about the implementation then? I'd suggest a (new) helper function which takes connector and type as arguments and provides the marker. Can do that tomorrow, sinilar to cachetype marker

**Comment by fm-sys** [comment]
> Ok, so what about the implementation then? I'd suggest a (new) helper function which takes connector and type as arguments and provides the marker. Can do that tomorrow, sinilar to cachetype marker

Don't know whether it's worth a separate icon creation algorithm including caching etc. Maybe it's also enough to add @moving-bits suggested temporary geocache method to MapMarkerUtils:

> In my tries yesterday I created a new temporary geocache in `EmojiUtils` using something like:
> 
> ```
> final Geocache tempCache = new Geocache();
> tempCache.setType = cache.getType();
> tempCache.setGeocode = cache.getGeocode();
> ```

**Comment by ztNFny** [comment]
@fm-sys I extended the existing method, could you just cherry pick https://github.com/ztNFny/cgeo/commit/b829ce31c4b3d464ee618e1d3dea36c408db36d6 ?

**Comment by fm-sys** [comment]
It will now display the connector specific sharp (normal cache marker but without overlays)

grafik

**Pull request merged**
