### PR TITLE
for straight_border drawable distinguish between API 21 and earlier (fix #7473)

### LINKED ISSUE #7473: UnsupportedOperationException on Android 4.3 (Google Pre Launch Report)
On publishing a new (beta) release Google Play automatically runs robo tests on some device.
This pre launch report now came back with a crash report for an Android 4.3 device with the following stacktrace for beta version 2019.04.08-RC:

```
FATAL EXCEPTION: ControllerMessenger
android.content.res.Resources$NotFoundException: File res/drawable/border_straight.xml from drawable resource ID #0x7f0700da. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
	at android.content.res.Resources.loadDrawable(Resources.java:2974)
	at android.content.res.Resources.getDrawable(Resources.java:1558)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3573)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3616)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:357)
	at com.android.internal.app.AlertController.installContent(AlertController.java:259)
	at android.app.AlertDialog.onCreate(AlertDialog.java:337)
	at android.app.ProgressDialog.onCreate(ProgressDialog.java:198)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:362)
	at android.app.Dialog.show(Dialog.java:266)
	at cgeo.geocaching.activity.Progress.show(Progress.java:46)
	at cgeo.geocaching.CacheListActivity.importWeb(CacheListActivity.java:1431)
	at cgeo.geocaching.CacheListActivity.onOptionsItemSelected(CacheListActivity.java:894)
	at android.app.Activity.onMenuItemSelected(Activity.java:2640)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:406)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:103)
	at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:667)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
	at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:85)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
	at android.widget.AdapterView.performItemClick(AdapterView.java:301)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1510)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3339)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:138)
	at androidx.test.espresso.action.Tap$1.a(Tap.java:6)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
	at android.content.res.TypedArray.getColor(TypedArray.java:327)
	at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:967)
```

### PR DESCRIPTION
**Pull request by moving-bits**
use fixed color for API < 21 and parametrized color after that

### CODE REVIEW

**Comment by moving-bits** [comment]
rebased on current release branch and set target to release branch

**Comment by rsudev** [comment]
Please let me cross-check before merging this. It seems the rebase on release didn't work as intended.
In this case a cherry-pick from the head commit to release is likely the better approach to move the change over.

**Comment by moving-bits** [comment]
> Please let me cross-check before merging this. It seems the rebase on release didn't work as intended.
> In this case a cherry-pick from the head commit to release is likely the better approach to move the change over.

Alternatively I can create a new PR for this one, as it's only a handful of lines.

**Comment by moving-bits** [comment]
need to redo this PR from scratch technically

**Comment by moving-bits** [comment]
closed in favor of #7488

**Pull request closed without merging**
