### PR TITLE
change color for disabled settings to grey (fix #10845)

### LINKED ISSUE #10845: Theming: Inactive settings not being greyed out
## Bug description 
Inactive settings currently have the same coloring as active settings (at least regarding the text), thus they are not visually distinguishable.

### Steps to reproduce the problem
- open settings
- go to "Routing / Navigation"
- disable "use internal routing"

### Actual result after these steps 
The subsequent entries ("Folder with BRouter routing data" etc.) stay the same visually.

### Expected result after these steps 
The subsequent entries ("Folder with BRouter routing data" etc.) should be greyed out.

## c:geo version 
current master as of today (2021-06-04)

## Reproducible 
yes

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
adds color selectors for settings activity to be able to distinguish between enabled and disabled settings

image.image

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by fm-sys** [comment]
I guess this issue might be fixed with the the settings refactoring work of @schoolGuy implicitly.

@schoolGuy do you want this PR to be merged or should we wait with it?

**Comment by SchoolGuy** [comment]
@fm-sys As I am busy with a resisting UI in the WhereYouGo settings, this can be merged. I will still do the cgeo Settings, it sadly just takes a littlebit more time then I anticipated...

**Pull request merged**
