### PR TITLE
Fix #4316 - Add existing playstore description for main app

### LINKED ISSUE #4316: Add PlayStore description to Crowdin
Splitted from #3602 

Currently the translations for the PlayStore description of c:geo and the plugins are done manually (See #2339 for current approach).

Recently Google introduced an API which should allow to automate description syncronisation and therefore might enable us to include these strings on crowdin:
https://developers.google.com/android-publisher/

### PR DESCRIPTION
**Pull request by Lineflyer**
Adding all existing playstore desciptions for the c:geo main app:
- Add (manual) export from Google Play
- Add translations from Wiki page not yet contained on Google Play (Russian, Catalan)
- Use structure below proposed `/main/project/`
- Add existing screenshots for Google Play (only some localized) --> not for translation, just for having a storage
- Add icons/images used on Google Play --> placeholders as I did not find the original graphics yet

To Do:
- As the import was manually, there might be typos in folder and file names. Contents should be fine however
- Need to verify that dir names match the crowdin syntax

This PR only adds the files but not yet any transfer to/from Crowdin.
That would be the last step after everything is complete.

Probably I will also prepare the same for cgeo-contacts. This could be used as a trial before activating translation for the main app description.

### CODE REVIEW

**Comment by Lineflyer** [comment]
NO TEST

**Comment by bekuno** [comment]
> 
> 
> NO TEST

grafik

**Comment by Lineflyer** [comment]
@bekuno 
I was looking for a documentation of the PR builder to see, whether I can opt out a PR from testing as it is meaningless for this PR.
I found something for another PR builder plugin and simply hoped this keyword would also work here....seems not.

**Comment by bekuno** [comment]
skip ci

**Comment by bekuno** [comment]
> 
> 
> skip ci

from jenkins:
grafik

**Comment by Lineflyer** [comment]
excellent ;)

**Comment by Lineflyer** [comment]
I aborted and cleaned the queue. Lets test.

**Comment by moving-bits** [comment]
oops, this killed my bugfix PR build as well...

**Comment by Lineflyer** [comment]
> oops, this killed my bugfix PR build as well...

Sorry, feel free to rerun now.. Did not notice your PR.

Skip CI: Seems it does not work as I thought here

**Comment by bekuno** [comment]
Please try the phrase in the commit text.
It needs the brackets.

**Comment by moving-bits** [comment]
> > oops, this killed my bugfix PR build as well...
> Sorry, feel free to rerun now.. Did not notice your PR.

No problem. Just have been confused why the build broke so early ;-)

**Comment by Lineflyer** [comment]
> Please try the phrase in the commit text.
> It needs the brackets.

Mmh..not so really familiar with RegEx. I guess it needs lower case like `[skip ci]`?

**Comment by bekuno** [comment]
yes.

**Comment by Lineflyer** [comment]
Indeed, there is an issue somewhere out here to update them.
This is however the import of the existing screenshots.

**Comment by Lineflyer** [comment]
> Please do not delete these files (eg. by moving to another folder), use a copy.

Will change.

**Pull request merged**
