### PR TITLE
crowdin: New translations

### LINKED ISSUE #8080: Portuguese  language not working (beta)
We have several users of beta version 2020.01.16-RC which claim, that c:geo is no longer using portuguese language but english.
Did not verify yet.

### PR DESCRIPTION
**Pull request by bekuno**
also fix  #8080

The translations at crowdin from the release tree does not contain the latest strings.
I don't know how to fix this.
 
When this PR, created from the master branch, is based to release, then it shows some extra commits. Therefore it is based to master.

### CODE REVIEW

**Comment by moving-bits** [comment]
@Bekuno  I don't know if we can bring it into release branch this way without moving everything else from master to release as well (which me might want or not) - @Lineflyer?

OTOH: Do you have a chance to checkout master locally, create a new branch from this, and then import the strings? (All langs except the original English strings)

**Comment by Lineflyer** [comment]
How about a workaround to just push the pt string file to your repo and create a PR towards release with it?

**Comment by bekuno** [comment]
> How about a workaround to just push the pt string file to your repo and create a PR towards release with it?

Ok, tomorrow.

**Comment by bekuno** [comment]
superseded by  #8084

**Pull request closed without merging**
