### PR TITLE
fix #13979: check memory before opening very large track files

### LINKED ISSUE #13979: Crash in GeoJSonUtils on opening the map
User on support reports the map is always crashing for her. Error log points to GeoJsonUtils, see below:

```
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.OutOfMemoryError: Failed to allocate a 268959752 byte allocation with 16777216 free bytes and 228MB until OOM
at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:68)
at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 268959752 byte allocation with 16777216 free bytes and 228MB until OOM
at java.util.Arrays.copyOf(Arrays.java:3352)
at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:550)
at java.lang.StringBuilder.append(StringBuilder.java:205)
at com.cocoahero.android.geojson.util.StreamUtils.toString(StreamUtils.java:38)
at com.cocoahero.android.geojson.util.StreamUtils.toString(StreamUtils.java:18)
at com.cocoahero.android.geojson.GeoJSON.parse(GeoJSON.java:135)
at cgeo.geocaching.utils.GeoJsonUtils.parseGeoJson(GeoJsonUtils.java:57)
at cgeo.geocaching.files.GPXTrackOrRouteImporter.parseAsGeoJson(GPXTrackOrRouteImporter.java:120)
at cgeo.geocaching.files.GPXTrackOrRouteImporter.doInBackground(GPXTrackOrRouteImporter.java:89)
at cgeo.geocaching.files.GPXTrackOrRouteImporter.lambda$doImport$1(GPXTrackOrRouteImporter.java:39)
at cgeo.geocaching.files.GPXTrackOrRouteImporter.$r8$lambda$g0pSx27yHp6Zq7CsAgfCAE4gnXU(GPXTrackOrRouteImporter.java)
at cgeo.geocaching.files.GPXTrackOrRouteImporter$$ExternalSyntheticLambda0.run(R8$$SyntheticClass)
at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:91)
at cgeo.geocaching.utils.AndroidRxUtils.$r8$lambda$bqzWo9nlvU86BvboB-9jhDWp5vc(AndroidRxUtils.java)
at cgeo.geocaching.utils.AndroidRxUtils$$ExternalSyntheticLambda0.run(R8$$SyntheticClass)
at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
... 6 more
```
Release 2023.02.12
ticket 724300

Edit: I asked the user whether she has some tracks activated on map and whether she can send us the files so that we can debug into it.

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #13979: check memory before opening very large track files

### CODE REVIEW

**Comment by fm-sys** [comment]
I fear this will not work as expected. Although the error is caught inside _that_ specific thread, we cannot know if other threads will throw the OOME instead, which would make the problem just even harder to debug. Note that there's an Error and no Exception  which is thrown.

**Comment by eddiemuc** [comment]
> I fear this will not work as expected. Although the error is caught inside _that_ specific thread, we cannot know if other threads will throw the OOME instead, which would make the problem just even harder to debug. Note that there's an Error and no Exception which is thrown.

That's a fair assessment, I reworked the PR completely (it now checks the file size against available memory before starting to parse)

**Comment by eddiemuc** [comment]
failing tests seem unrelated

**Comment by bekuno** [comment]
> failing tests seem unrelated

The codacy error needs a tweak:
~~~
main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteImporter.java#L63
The method 'doInBackground(Context, Uri)' has an NPath complexity of 257, current threshold is 200
~~~

**Comment by eddiemuc** [comment]
> > failing tests seem unrelated
> 
> The codacy error needs a tweak:
> 
> ```
> main/src/main/java/cgeo/geocaching/files/GPXTrackOrRouteImporter.java#L63
> The method 'doInBackground(Context, Uri)' has an NPath complexity of 257, current threshold is 200
> ```

Will do by annotating the method as an exception to the rule for two reasons:
* frixing this would require a major code restructuring which seems unsuited in release branch
* My change did not raise the complexity of this methodt. It was of this complexity before already and this was obviously accepted at time of coding/checkin

We should seriously discuss whether the 200 threshold should be raised. It does not even nearly reflect the complexitiy of all the main classes of c:geo, and it is unrealistic to think that we will ever have time and passion to achieve this in the whole codebase.

**Pull request merged**
