### PR TITLE
Some fixes for TB parsing

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
TB parsing fixes (mitigating the recent website changes)

- added aria attribute in trackable icon / type parsing (optional, since not used in all places)
- new HTML structure for log entities

### CODE REVIEW

**Comment by moving-bits** [comment]
All TB-related tests are back to green, thus removing "WIP" label / draft state from this PR

**Review by bekuno — CHANGES_REQUESTED** [review]
Can you add the htm-sources for the test caches (TB2J1VZ, TB4BPQK) please?

**Comment by moving-bits** [comment]
> Can you add the htm-sources for the test caches (TB2J1VZ, TB4BPQK) please?

why? Those TB are loaded online on each run, and results are compared against that. Nothing changed in that part of the tests.

This is different to the TB touched by this PR, those are compared against an offline copy.

**Comment by bekuno** [comment]
> > Can you add the htm-sources for the test caches (TB2J1VZ, TB4BPQK) please?
> 
> why? Those TB are loaded online on each run, and results are compared against that. Nothing changed in that part of the tests.
> 
> This is different to the TB touched by this PR, those are compared against an offline copy.

The offline copy of this two caches would be interesting to compare them in a situation like today, so we can see what has changed.

**Comment by moving-bits** [comment]
> The offline copy of this two caches would be interesting to compare them in a situation like today, so we can see what has changed.

ok, have added them as part of #15573

**Pull request merged**
