### PR TITLE
Issue 9202

### PR DESCRIPTION
**Pull request by baiti**
My initial stab at Adventure Lab integration. Can we make this a draft-PR?

- Settings / Preferences
- New Connector, uses labs API in passive mode by faking a successful login

Problems not yet resolved:
- there is a memory leak which I haven't been able to track down, it periodically logs:
`
I/cgeo.geocachin: Explicit concurrent copying GC freed 1119(195KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4720KB/9441KB, paused 272us total 34.229ms
`
- On main activity screen it doesn't show that I am logged into Labs.

My next steps once the basics are in:

- issue the first API request to get some data
- write a JSON parser to create a Geocache object
- see what needs to be done to get the pin rendered on the map
- actually need a new icon for that pin. Here I could use some help with the tooling. At this time I am just reusing the EC icon
-  way down on the list: upon click of an LC icon, launch the Labs App on it.

### CODE REVIEW

**Comment by Lineflyer** [comment]
add to whitelist

**Comment by Lineflyer** [comment]
Just FYI @baiti 

I added you to the whitelist of our CI. This means, that each PR you open (or change) will be tested by our CI.
While working on your PR you should check the results of the checks (both CI and Codacy) and adapt accordingly. 
Remark: Some code style checks overlap between CI and Codacy.

In case of questions regarding those checks (or other code related questions) do not hesitate to ask for help.

**Comment by baiti** [comment]
> Just FYI @baiti
> 
> I added you to the whitelist of our CI. This means, that each PR you open (or change) will be tested by our CI.
> While working on your PR you should check the results of the checks (both CI and Codacy) and adapt accordingly.
> Remark: Some code style checks overlap between CI and Codacy.
> 
> In case of questions regarding those checks (or other code related questions) do not hesitate to ask for help.

Yes, some of those, e.g. unused imports, I have already fixed. Some I don't fully undersant yet, e.g. the order in which the imports apparently must be made.

In general: Everything pushed, compiled clean on the develipment system so the bots are mich more "picky"  as it seems ;)

**Comment by Lineflyer** [comment]
> In general: Everything pushed, compiled clean on the develipment system so the bots are mich more "picky" as it seems ;)

Yeah....It compiles is not always the only needed code quality criteria ;). But IMHO making it compile and work is the first step, then clean up later.

**Comment by baiti** [comment]
> > In general: Everything pushed, compiled clean on the develipment system so the bots are mich more "picky" as it seems ;)
> 
> Yeah....It compiles is not always the only relevant code quality criteria ;). But IMHO making it compile and work is the first step, then clean up later.

I am actually quite sure that I copied some of those issues over from the EC connector I used as a base.

**Comment by baiti** [comment]
> > Just FYI @baiti
> > I added you to the whitelist of our CI. This means, that each PR you open (or change) will be tested by our CI.
> > While working on your PR you should check the results of the checks (both CI and Codacy) and adapt accordingly.
> > Remark: Some code style checks overlap between CI and Codacy.
> > In case of questions regarding those checks (or other code related questions) do not hesitate to ask for help.
> 
> Yes, some of those, e.g. unused imports, I have already fixed. Some I don't fully understand yet, e.g. the order in which the imports apparently must be made, can you help there?
> 
> In general: Everything pushed, compiled clean on the develipment system so the bots are mich more "picky" as it seems ;)



> > In general: Everything pushed, compiled clean on the develipment system so the bots are mich more "picky" as it seems ;)
> 
> Yeah....It compiles is not always the only relevant code quality criteria ;). But IMHO making it compile and work is the first step, then clean up later.

These three types of errors actually drive me crazy. I have spent an hour reordering stuff trial and error and never got it clean.
Do you guys have those rules documented somewhere?

`'io.reactivex.rxjava3.core.Single' should be separated from previous imports.`
`Extra separation in import group before 'okhttp3.Response'`
`Wrong order for 'java.io.IOException' import.`

**Comment by fm-sys** [comment]
> there is a memory leak which I haven't been able to track down, it periodically logs:
>       `I/cgeo.geocachin: Explicit concurrent copying GC freed 1119(195KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4720KB/9441KB, paused 272us total 34.229ms`

AFAIK these messages were there before. I have also noticed them, but have no idea if/how to fix...

**Comment by bekuno** [comment]
Codacy should use our config file (checkstyle.xml).
We have defined
`            <property name="groups" value="cgeo,android,androidx,java,javax,*" />` ,
so all other (`*`) should be in one own group.

Please try
~~~
import com.fasterxml.jackson.databind.JsonNode;
import io.reactivex.rxjava3.core.Single;
import io.reactivex.rxjava3.functions.Function;
import okhttp3.Response;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
~~~

**Comment by bekuno** [comment]
You can use the checkstyle plugin in Android Studio.

**Comment by eddiemuc** [comment]
@baiti wrt Code checks: I feel your pain :-)

Definitely you should install the checkstyle plugin as @bekuno mentioned and run it locally before checking in. this will detect all the minor things which otherwise drive you crazy when correcting them from Codacy server output (e.g. all the spacing rules, final keyword rule, import order)

Wrt import order: I agree that c:geo has a very strange import order structure, I always struggle with it and it is somewhat different from settings I am user to from other projects (e.g. no separation of static vs nonstatic, java before com/org, very strict about allowed lines). But I assumed there's good reason for these specific choices for c:geo so I obey (I even usually format imports for c:geo manually :-))

Wrt problems in code that was already there: yes, the Codacy rules get more strict over time, but Codacy only validates code which was touched by a PR. So it regularly happens when you touch already existing code that you get warnings for code parts you never modified. Sometimes this seems a bit "unfair" but overall I think this is the only way we can improve codebase over time as a team.

**Comment by baiti** [comment]
Thanks much for your input on Codacy / Style. Will go for the plugin, that saves time. Now I have a more relevant question.

I am creating a Geocache object and since those ALCs are referenced by a UUID rather than what we call a geocode, I put the value int Geocache's property called "guid":

`cache.setGuid(response.get("id").asText());`

Now my problem is, I cannot get that guid back when my:

`public SearchResult searchByGeocode(@Nullable final String geocode, @Nullable final String guid, final DisposableHandler handler)`

is invoked. There is a guid parameter but it is always null. In the constructor it is first set to an empty string, but me calling setGuid() should actually put someting in but I never get it back. 

In `CacheDetailActivity's` `onCreate()` it is initialized to an empty string and depending on 

`guid = extras.getString(Intents.EXTRA_GUID);`

it gets some value but I am not coming in via some share intent.

How can I get the guid back from the Geocache object?

**Comment by fm-sys** [comment]
> How can I get the guid back from the Geocache object?

Isn't there no method like `grocache.getGuid()`?

Anyway, as geocodes are used at many places in c:geo as basic identifier, it would probably be better to convert the GUID to an unique base64 "geocode" like `LCxxxxx`. IIRC there even is a method for this conversion. You can take a look/use the `GCUtils` for it...

**Comment by baiti** [comment]
> > How can I get the guid back from the Geocache object?
> 
> Isn't there no method like `geocache.getGuid()`?
> 
> Anyway, as geocodes are used at many places in c:geo as basic identifier, it would probably be better to convert the GUID to an unique base64 "geocode" like `LCxxxxx`. IIRC there even is a method for this conversion. You can take a look/use the `GCUtils` for it...

I actually get a geocode like thing, which I already prefix with "LC" and the result renders on various views pretty much like the GC, OC, EC, .... codes and our eyes are familiar with these. With that code, after stripping the LC again, I can launch into the ALC app nicely, however, I can't use that code in the API to get cache details. In order to get cache details, I need the UUID.

Of course I could directly throw the UUID in the place of the geocode and I believe that would actually work. What makes me hesitate is that it looks very ugly on all the places where we typicalle see a GC  code.

**Comment by baiti** [comment]
> You can use the checkstyle plugin in Android Studio.

I have been unable to install the plugin. I tried to follow the steps in:

https://github.com/twotoasters/AndroidStyleGuidelines  Is that the plugin in question?

I was not even able to find "Preferences" in Android Studio

**Comment by baiti** [comment]
> > > How can I get the guid back from the Geocache object?
> > 
> > 
> > Isn't there no method like `geocache.getGuid()`?
> > Anyway, as geocodes are used at many places in c:geo as basic identifier, it would probably be better to convert the GUID to an unique base64 "geocode" like `LCxxxxx`. IIRC there even is a method for this conversion. You can take a look/use the `GCUtils` for it...
> 
> I actually get a geocode like thing, which I already prefix with "LC" and the result renders on various views pretty much like the GC, OC, EC, .... codes and our eyes are familiar with these. With that code, after stripping the LC again, I can launch into the ALC app nicely, however, I can't use that code in the API to get cache details. In order to get cache details, I need the UUID.
> 
> Of course I could directly throw the UUID in the place of the geocode and I believe that would actually work. What makes me hesitate is that it looks very ugly on all the places where we typicalle see a GC code.

So in essence I need both. The "LCcode" ... for launching the ALC App.
The UUID ... for fetching details via the API.

**Comment by bekuno** [comment]
> I was not even able to find "Preferences" in Android Studio

This should help:
https://www.geeksforgeeks.org/how-to-install-and-uninstall-plugins-in-android-studio/
Normally it is fine to use the marketplace as install source (see the image in this guide)

**Comment by baiti** [comment]
I have now marked it "Ready for Review". I am sure it is not ready for a merge but there is sufficient functionality in it such that it would make sense if some of you ran the build actually on an emulator and provide feedback and suggestions.

Here is what's in:

- Settings / Preferences (the login is fake at this time, depending on how we proceed with GC HQ)
- "Caches nearby"
- "Live Map". All the API provides is a search by center / radius so I converted the bbox to center and assumed a fixed radius
- Launch into ALC App via "Open Browser"

What my next steps would be:
- Make CacheDetailsActivity work. Here I need that UUID thing otherwise I can't call the API to get the details.

**Comment by baiti** [comment]
> > I was not even able to find "Preferences" in Android Studio
> 
> This should help:
> https://www.geeksforgeeks.org/how-to-install-and-uninstall-plugins-in-android-studio/
> Normally it is fine to use the marketplace as install source (see the image in this guide)

Yes it did ;) Thanks. It speeds up the cyle as it avoids CI runs on github

**Comment by baiti** [comment]
as it seems, some of the git magic screwed up the PR. None of the changes listed for:

main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java

are actually from me. I have no idea which rebase push pull magic made it part of this PR

**Comment by eddiemuc** [comment]
Jup you got my most recent commit to master (done by me, merged by @fm-sys ) into your PR. My guess would be that at this point you merged the master onto your PR instead of doing a rebase (because the later would have put my commit BEFORE all your commits and git would have noted that this one is already on master and not include it into your PR).

**Comment by eddiemuc** [comment]
The rule to follow to prevent this is "always rebase your feature branch against master, never merge it". 

How this is done is explained as best as I am able to here: https://github.com/cgeo/cgeo/wiki/Working-on-c%3Ageo-for-git-beginners

Esp section "Rebasing a branch and handling merge conflicts"

As on how to get out of current situation I would suggest an interactive rebase to remove the alien commit from your feature branch. Since you seem to have 40 commits on your branch, you would have to issue `git rebase -i HEAD^40`. Then a text editor should open with 40 lines (one for each commit), there delete the alien commit Land and save/close editor (btw by putting s or f in front of lines you may also squash multiple commits into one using same method). See also section "squashing commits" in above mentioned wiki page

Note: interactive rebase is pretty advanced git stuff, it is always good to make a backup before using it if you're not exactly know what you're doing.

**Comment by eddiemuc** [comment]
Just saw on wiki page that there might be better options for interactive rebase than using HEAD^40 (e.g. keep-base). Maybe better use the command described there (in the advanced parts git often exceeds my humble knowledge...)

**Comment by baiti** [comment]
> The rule to follow to prevent this is "always rebase your feature branch against master, never merge it".
> 
> How this is done is explained as best as I am able to here: https://github.com/cgeo/cgeo/wiki/Working-on-c%3Ageo-for-git-beginners
> 
> Esp section "Rebasing a branch and handling merge conflicts"
> 
> As on how to get out of current situation I would suggest an interactive rebase to remove the alien commit from your feature branch. Since you seem to have 40 commits on your branch, you would have to issue `git rebase -i HEAD^40`. Then a text editor should open with 40 lines (one for each commit), there delete the alien commit Land and save/close editor (btw by putting s or f in front of lines you may also squash multiple commits into one using same method). See also section "squashing commits" in above mentioned wiki page
> 
> Note: interactive rebase is pretty advanced git stuff, it is always good to make a backup before using it if you're not exactly know what you're doing.

Since I made some more commits, I tried:

`baiti@dog:~/cgeo$ git rebase -i HEAD^43`
`fatal: invalid upstream 'HEAD^43'`

**Comment by eddiemuc** [comment]
@baiti: my bad, sorry, you have to use ~ instead of ^:
`git rebase -i HEAD~43`

Or you could try the command version from the wiki page (I think this version is supposed to automatically find the point where your branch merged from master and give you the commits until then, but I never used it myself):
`git rebase -i --keep-base --fork-point master`

A word wrt squashing my own feature branch: if Iwork on a PR only a short time this is indeed not necessary
But when I work a longer time on a PR I regulary do this. Reason is that I also regularly do a master rebase in order to keep in sync with recent development from other people and not to drift too much apart from that. But whenever you rebase to master, the rebase is done by git on a commit-by-commit-base, and for each step you have to resolve conflicts if there are any. So by keeping my own branches history short (by squashing regularly) I save myself a lot of pain in case of such conflicts during master rebase. 
(Also I don't like all these "ci fix" / "make codacy happy" / ... commits to remain too long in my history but that's just a personal thing :-))

**Comment by baiti** [comment]
I tried the resolving it as per your suggestion but it seems I am getting deeper and deeper into the mess. My concern is now that I might loose all my changes and would need to do it all again. So I think I better don't touch anything from here and ask for help.

I shoudl have known better. It is NEVER a good idea to blindly follow some recipe. You need to understand what each of these lines in a recipe really do. Had I known adead of time what the "git rebase -i --keep-base --fork-point master" leads to, I'd never issues that command line.

baiti@dog:~/cgeo$ git status
On branch issue_9202
Your branch is up to date with 'origin/issue_9202'.

nothing to commit, working tree clean
baiti@dog:~/cgeo$ git rebase -i --keep-base --fork-point master

---> here I ended up in the edtor. I left alle the "pick prefixed" lines as they were and only the last two lines, I replaced "pick" with "d". My expectation was that this would remove those commits and leave everything as it was but that apparently is not what happend. Here is what happened instead:

Auto-merging main/src/cgeo/geocaching/settings/SettingsActivity.java
Auto-merging main/src/cgeo/geocaching/settings/Settings.java
CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/settings/LCAuthorizationActivity.java
Auto-merging main/src/cgeo/geocaching/settings/LCAuthorizationActivity.java
Auto-merging main/src/cgeo/geocaching/settings/CredentialsPreference.java
CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/connector/lc/package-info.java
Auto-merging main/src/cgeo/geocaching/connector/lc/package-info.java
CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/connector/lc/LCLogin.java
Auto-merging main/src/cgeo/geocaching/connector/lc/LCLogin.java
CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/connector/lc/LCConnector.java
Auto-merging main/src/cgeo/geocaching/connector/lc/LCConnector.java
CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/connector/lc/LCApi.java
Auto-merging main/src/cgeo/geocaching/connector/lc/LCApi.java
Auto-merging main/res/values/strings.xml
CONFLICT (content): Merge conflict in main/res/values/strings.xml
CONFLICT (add/add): Merge conflict in main/res/values/lcicons.xml
Auto-merging main/res/values/lcicons.xml
Auto-merging .gitignore
CONFLICT (content): Merge conflict in .gitignore
error: could not apply 4fcc0e1f3... initial changes
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 4fcc0e1f3... initial changes
baiti@dog:~/cgeo$ git status
interactive rebase in progress; onto a5a3de5bd
Last commands done (20 commands done):
   pick b5e7aeba7 Codacy .. again
   pick 4fcc0e1f3 initial changes
  (see more in file .git/rebase-merge/done)
Next commands to do (21 remaining commands):
   pick 4548d6d49 2nd iteration
   pick 0ef6fc06e 3rd iteration
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'issue_9202' on 'a5a3de5bd'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   main/src/cgeo/geocaching/connector/lc/LCLoggingManager.java
	modified:   main/src/cgeo/geocaching/settings/CredentialsPreference.java
	modified:   main/src/cgeo/geocaching/settings/Settings.java
	modified:   main/src/cgeo/geocaching/settings/SettingsActivity.java

Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add <file>..." to mark resolution)
	both modified:   .gitignore
	both added:      main/res/values/lcicons.xml
	both modified:   main/res/values/strings.xml
	both added:      main/src/cgeo/geocaching/connector/lc/LCApi.java
	both added:      main/src/cgeo/geocaching/connector/lc/LCConnector.java
	both added:      main/src/cgeo/geocaching/connector/lc/LCLogin.java
	both added:      main/src/cgeo/geocaching/connector/lc/package-info.java
	both added:      main/src/cgeo/geocaching/settings/LCAuthorizationActivity.java


First thing I will now create a tarball of all I have here locally, will have a specific focus on those 19 files I changed.

**Comment by baiti** [comment]
> I tried the resolving it as per your suggestion but it seems I am getting deeper and deeper into the mess. My concern is now that I might loose all my changes and would need to do it all again. So I think I better don't touch anything from here and ask for help.
> 
> I shoudl have known better. It is NEVER a good idea to blindly follow some recipe. You need to understand what each of these lines in a recipe really do. Had I known adead of time what the "git rebase -i --keep-base --fork-point master" leads to, I'd never issues that command line.
> 
> baiti@dog:~/cgeo$ git status
> On branch issue_9202
> Your branch is up to date with 'origin/issue_9202'.
> 
> nothing to commit, working tree clean
> baiti@dog:~/cgeo$ git rebase -i --keep-base --fork-point master
> 
> ---> here I ended up in the edtor. I left alle the "pick prefixed" lines as they were and only the last two lines, I replaced "pick" with "d". My expectation was that this would remove those commits and leave everything as it was but that apparently is not what happend. Here is what happened instead:
> 
> Auto-merging main/src/cgeo/geocaching/settings/SettingsActivity.java
> Auto-merging main/src/cgeo/geocaching/settings/Settings.java
> CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/settings/LCAuthorizationActivity.java
> Auto-merging main/src/cgeo/geocaching/settings/LCAuthorizationActivity.java
> Auto-merging main/src/cgeo/geocaching/settings/CredentialsPreference.java
> CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/connector/lc/package-info.java
> Auto-merging main/src/cgeo/geocaching/connector/lc/package-info.java
> CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/connector/lc/LCLogin.java
> Auto-merging main/src/cgeo/geocaching/connector/lc/LCLogin.java
> CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/connector/lc/LCConnector.java
> Auto-merging main/src/cgeo/geocaching/connector/lc/LCConnector.java
> CONFLICT (add/add): Merge conflict in main/src/cgeo/geocaching/connector/lc/LCApi.java
> Auto-merging main/src/cgeo/geocaching/connector/lc/LCApi.java
> Auto-merging main/res/values/strings.xml
> CONFLICT (content): Merge conflict in main/res/values/strings.xml
> CONFLICT (add/add): Merge conflict in main/res/values/lcicons.xml
> Auto-merging main/res/values/lcicons.xml
> Auto-merging .gitignore
> CONFLICT (content): Merge conflict in .gitignore
> error: could not apply [4fcc0e1](https://github.com/cgeo/cgeo/commit/4fcc0e1f3e4c0e3d3130b6d9e8d061b97894be7e)... initial changes
> Resolve all conflicts manually, mark them as resolved with
> "git add/rm <conflicted_files>", then run "git rebase --continue".
> You can instead skip this commit: run "git rebase --skip".
> To abort and get back to the state before "git rebase", run "git rebase --abort".
> Could not apply [4fcc0e1](https://github.com/cgeo/cgeo/commit/4fcc0e1f3e4c0e3d3130b6d9e8d061b97894be7e)... initial changes
> baiti@dog:~/cgeo$ git status
> interactive rebase in progress; onto [a5a3de5](https://github.com/cgeo/cgeo/commit/a5a3de5bdec39983d2e175c2b12fd347ba46eeb9)
> Last commands done (20 commands done):
> pick [b5e7aeb](https://github.com/cgeo/cgeo/commit/b5e7aeba7eb5d75bccded730b4a2aea7db32b310) Codacy .. again
> pick [4fcc0e1](https://github.com/cgeo/cgeo/commit/4fcc0e1f3e4c0e3d3130b6d9e8d061b97894be7e) initial changes
> (see more in file .git/rebase-merge/done)
> Next commands to do (21 remaining commands):
> pick [4548d6d](https://github.com/cgeo/cgeo/commit/4548d6d49a9a9295be5206319fc532c0f03c3853) 2nd iteration
> pick [0ef6fc0](https://github.com/cgeo/cgeo/commit/0ef6fc06e541544203de8e6644c32ee9e52d0d17) 3rd iteration
> (use "git rebase --edit-todo" to view and edit)
> You are currently rebasing branch 'issue_9202' on 'a5a3de5bd'.
> (fix conflicts and then run "git rebase --continue")
> (use "git rebase --skip" to skip this patch)
> (use "git rebase --abort" to check out the original branch)
> 
> Changes to be committed:
> (use "git restore --staged ..." to unstage)
> new file: main/src/cgeo/geocaching/connector/lc/LCLoggingManager.java
> modified: main/src/cgeo/geocaching/settings/CredentialsPreference.java
> modified: main/src/cgeo/geocaching/settings/Settings.java
> modified: main/src/cgeo/geocaching/settings/SettingsActivity.java
> 
> Unmerged paths:
> (use "git restore --staged ..." to unstage)
> (use "git add ..." to mark resolution)
> both modified: .gitignore
> both added: main/res/values/lcicons.xml
> both modified: main/res/values/strings.xml
> both added: main/src/cgeo/geocaching/connector/lc/LCApi.java
> both added: main/src/cgeo/geocaching/connector/lc/LCConnector.java
> both added: main/src/cgeo/geocaching/connector/lc/LCLogin.java
> both added: main/src/cgeo/geocaching/connector/lc/package-info.java
> both added: main/src/cgeo/geocaching/settings/LCAuthorizationActivity.java
> 
> First thing I will now create a tarball of all I have here locally, will have a specific focus on those 19 files I changed.

I have now done a 'git abort rebase' and now everything seems to be as it was before. At least I haven't lost anything, hopefully.

**Comment by eddiemuc** [comment]
To delete a commit you have to delete the line (not put a d in front)

Maybe try again with HEAD~43 format. 

But yes, it is a good idea to do a full backup first :-)

**Comment by baiti** [comment]
> To delete a commit you have to delete the line (not put a d in front)
> 
> Maybe try again with HEAD~43 format.
> 
> But yes, it is a good idea to do a full backup first :-)

I tried agan. the `git rebase -i HEAD~43`  gets me into the editor with 62 "pick" lines. The top 21 lines are not mine. The remaining 41 are mine. If I delete the top 21 lines and save the file, it starts to do something, reports conflcts and "automerges" lots of stuff but in the end the mess is exactly as I described earlier. None of this conflicts and automerge stuff should be necessary. There is exactly ONE file too many in the PR. Here is what I get:

interactive rebase in progress; onto de959e5c0
Last commands done (20 commands done):
   pick b5e7aeba7 Codacy .. again
   pick 4fcc0e1f3 initial changes
  (see more in file .git/rebase-merge/done)
Next commands to do (21 remaining commands):
   pick 4548d6d49 2nd iteration
   pick 0ef6fc06e 3rd iteration
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing branch 'issue_9202' on 'de959e5c0'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   main/src/cgeo/geocaching/connector/lc/LCLoggingManager.java
	modified:   main/src/cgeo/geocaching/settings/CredentialsPreference.java
	modified:   main/src/cgeo/geocaching/settings/Settings.java
	modified:   main/src/cgeo/geocaching/settings/SettingsActivity.java

Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add <file>..." to mark resolution)
	both modified:   .gitignore
	both added:      main/res/values/lcicons.xml
	both modified:   main/res/values/strings.xml
	both added:      main/src/cgeo/geocaching/connector/lc/LCApi.java
	both added:      main/src/cgeo/geocaching/connector/lc/LCConnector.java
	both added:      main/src/cgeo/geocaching/connector/lc/LCLogin.java
	both added:      main/src/cgeo/geocaching/connector/lc/package-info.java
	both added:      main/src/cgeo/geocaching/settings/LCAuthorizationActivity.java

Nowehere do I see how I could essentially just get rid of:
`main/src/cgeo/geocaching/maps/mapsforge/v6/RenderThemeHelper.java`

As this seems to be the only file that doesn't belong onto the PR. I have, again aborted the rebase and git status is clean again but the errnously pushed file is obviously still there.  Can't we just delete that from the set of changed files and call it done?

**Comment by baiti** [comment]
I have now deleted the file in question on the WebUI and it seems all clean now except that I am not sure wheter the PR, when it eventually gets merged, will process the "delete" and really deletes the file from master ... which would obviously be a mistake

**Comment by baiti** [comment]
To get out of this mess. how about the following:
- I stash away the 18 files I changed or created
- I delete the PR (or have an admin delete it completely)
- I delete my my branch

Then
- rebase my local environment
- create a new branch
-  stuff my changes into the branch
- do a single: git commit -a -m "..." ; git push
- Then I create a new PR with just one commit in it
- Then would be a good time for some of you experts to review and eventually merge the PR

I would actually want to make some more progress on developent. We could in theory even release the functionality as it is now. We would have to block the "Cache Detail" buttons vor ALCs, however, I'd find it much better if I could also actually show more details instead of just launching the ALC app.

There is only one small problem to solve: When the CacheDetailsAchtivity is launched, I do not just need a "geocode", I need the UUID that I stored into the Geocache object when I created it in Live Map or "Nearby".

I just don't know how that UUID is passed back to me when CacheDetailActivity is created.

**Comment by baiti** [comment]
after many attempts to resolve conflicts and rebase and merge it is finally in a state beyond all repair and I would like to eliminate that PR, the branch, my clone, my fork ... and completely start over from scratch even if that takes a full day

**Comment by eddiemuc** [comment]
@baiti sorry for this. I don't know if it's any consolation, but when I started with c:geo last summer I had the same problem and had to redo PRs several times until I got the hang on git. It is immensely powerful,. but yet far too complex for the majority of developers who "just want to code"...

I got rid of these problems by following a very rigid  process on my own:
* Never ever commit anything on master (also not locally). Only operations I do there is pull-rebase from cgeo/cgeo (`git pull --rebase upstream master`) and sync this to my personal fork on github (`git push origin`)
* Always, even for the most tiny change (e.g. a one-liner), create a new feature branch locally
* Always have only one commit on each of my feature branch (means: every time immediately after I put a second commit on top I do `git rebase -i HEAD~2` and put an "f"=fixup on the second, new commit -> will squash the two into one), with very few exceptions
* Regulary rebase feature branch with master (means: at beginning/end of each day I update local master as above, then do `git rebase master` on my feature branch and resolve conflicts)


Oh yes, and in case of bigger changes, I always do a local copy of my git repo (simple dir copy with File Explorer) just to be on the safe side. And this already rescued me a couple of times.

**Comment by baiti** [comment]
> @baiti sorry for this. I don't know if it's any consolation, but when I started with c:geo last summer I had the same problem and had to redo PRs several times until I got the hang on git. It is immensely powerful,. but yet far too complex for the majority of developers who "just want to code"...
> 
> I got rid of these problems by following a very rigid process on my own:
> 
> * Never ever commit anything on master (also not locally). Only operations I do there is pull-rebase from cgeo/cgeo (`git pull --rebase upstream master`) and sync this to my personal fork on github (`git push origin`)
> * Always, even for the most tiny change (e.g. a one-liner), create a new feature branch locally
> * Always have only one commit on each of my feature branch (means: every time immediately after I put a second commit on top I do `git rebase -i HEAD~2` and put an "f"=fixup on the second, new commit -> will squash the two into one), with very few exceptions
> * Regulary rebase feature branch with master (means: at beginning/end of each day I update local master as above, then do `git rebase master` on my feature branch and resolve conflicts)
> 
> Oh yes, and in case of bigger changes, I always do a local copy of my git repo (simple dir copy with File Explorer) just to be on the safe side. And this already rescued me a couple of times.

Thanks much @eddiemuc for your help. It is very clear to me that blindly executing command lines from the Wiki is a bad idea. It is ok to create little helper scripts with those commands in it, however, one has to have an understanding, how this stuff works and I clearly do not have that understanding.  There is nothing wrong with git, nothing wrong with cgeo's setup and processes, the only thing wrong is that I have never found a meaningful tutorial that brought me into a position of even remotely understanding how it works. The wiki is not a tutorial. The worst is, some  of these commands create irreversible changes. And without knowing what's going on underneath you wind up in a deeper an deeper mess. The only good thing is that I am learning the Android Studio's conflict resolution and merge tools. In the end I had 84 commits in the PR and 28 files touched although I had only touched 18 files intentionally.

I have now wiped my local development system completely. Deleted the fork on githun and will now start over from the point where I creae a new fork, a new clone, a new branch. Then I will manually get my changes in, build code, make checkstyle happy, run stuff on the emulator, commit to my local repo, push to my repo. I will NOT create a new PR until everything is golden from my own judgement and then and only then I do  a new PR and once that is opened I will not make any changes to it until it has been reviewed and merged. Then I can look at what the wiki says on refreshing the local environment.

**Comment by UniQP** [comment]
> The worst is, some of these commands create irreversible changes.
You can always go back to an older commit by `git reset --hard <sha1 of the old commit>`. And you can see all commits that you previously worked on by `git reflog`.

To get some idea how to work with git, I can recommend https://learngitbranching.js.org/ .

**Comment by moving-bits** [comment]
Just a small addition to @eddiemuc's comment:

To stay with "one commit only" in your local branch you can do second and subsequent commits with the `--amend` parameter, which adds the current changes in staging to the last commit. If you have already pushed your PR to GitHub, you will update this using `git push --force`.

So a recipe could be:

- start working on a new feature
  - `git checkout master`
  - `git checkout -b newbranch` (`newbranch` will be based on `master` by using this sequence)
  - (do some stuff)
  - `git commit -a -m "info"`

- do more work on the same feature
  - (do some stuff)
  - `git commit -a --amend` (appends local changes to your last commit; you can edit your commit message)

- first `push` to GitHub
  - `git push -u origin newbranch`

- subsequent pushes to GitHub (if you used something like `--amend` parameter or `git rebase` on your local branch)
  - `git push --force`

**Comment by fm-sys** [comment]
>  Always have only one commit on each of my feature branch (means: every time immediately after I put a second commit on top I do `git rebase -i HEAD~2` and put an "f"=fixup on the second, new commit -> will squash the two into one), with very few exceptions

@eddiemuc Just a small note how I'm doing this (which is IMHO even easier):
```
git commit --amend --no-edit              // keep commit message
git commit --amend -m "Commit Message"    // new commit message 
```

Oh, I just saw that @moving-bits was writing pretty much the same. 😅

But there is one more possible optimization. 
You can create aliases, for example `git config --global alias.amend 'commit --amend --no-edit'`
Then you can always update the commit with the small command `git amend`

**Comment by baiti** [comment]
Thanks **very** much for your help, I truely appreciate it. I feel quite embarassed for exposing my inabilities in this public channel. Perhaps everybody or at least some of us just have to go through all this.

At this time I have created a branch on my newly cloned fork and everything builds now clean again and runs on the emulator and checkstyle is happy and commits have been made and pushed ... but ... NO new PR yet. Creating a new PR will be the last step and then, I won't touch it until it is reviewed and merged.

In the meantime I will follow @UniQP 's link and learn some git ;)

**Pull request closed without merging**
