### PR TITLE
change group setting for download map menu entry

### PR DESCRIPTION
**Pull request by moving-bits**
@fm-sys 
Can you test this APK in your environment?

I've implemented a different group marker for the "download map" menu item - maybe that works in your setting.
Also I've added some `Log.i()` calls to output some debug info about the menu items while adding the map sources.

### CODE REVIEW

**Comment by fm-sys** [comment]
Unfortunately no success, Map Downloader Entry is still not displayed...

[logcat_2020-08-31_15-52.txt](https://github.com/cgeo/cgeo/files/5150729/logcat_2020-08-31_15-52.txt)

**Comment by moving-bits** [comment]
@fm-sys 
Thanks for testing this scenario.

Ok, as a fallback let's try something different: "Download offline map" now is a hard-coded item, and the different map sources get added dynamically. This leads to something like this:

image

Can you do another test (when the build is finished)?
I've removed the debug info, so no logcat needed this time.
Thanks.

**Comment by fm-sys** [comment]
This time the Google Maps item is hidden... (Again only for google maps/satellite)

Screenshot_20200831_200312_com huawei himovie overseas

**Comment by moving-bits** [comment]
This. is. strange. 

:-(

Thanks for testing. As I still cannot reproduce the problem: Do you have any system specifics for me to look for?
I've tested against emulator with both API 30 (Android 10) and 21 (Android 5), but both work.

**Comment by fm-sys** [comment]
I've tested the apk on my Huawei mate 20 lite running with android 10... So mabe EMUI specific. @MagpieFourtyTwo on which device did the bug occur? (model and android version) 

@moving-bits two ideas (haven't tried):
- isn't it possible to also hardcode the downloader as last element (with string and everything)?
- what about adding all the elements to one group (then we probably wouldn't have this separator line but it would be a try)

**Comment by moving-bits** [comment]
> * isn't it possible to also hardcode the downloader as last element (with string and everything)?

I had tried this before, but dismissed it, because the map sources got added at the end anyway. Haven't checked though, whether that variation helps with #8893.

> what about adding all the elements to one group (then we probably wouldn't have this separator line but it would be a try)

Will try that next. This will be without separator then, because separators are separating different groups only.

**Comment by moving-bits** [comment]
@fm-sys 
Can you test this variant? (Failing check is just a Checkstyle message, irrelevant for testing)
This time all menu entries are created dynamically, and all are in the same menu group.

**Comment by fm-sys** [comment]
Works fantastic!!!!! 

Just mabe add some `< ... >` like is is done for "new list" in the list selector. What do you think? Than the map downloader would be more visible and distinguished...

**Comment by moving-bits** [comment]
What a relief to finally have found a cross-device working solution... Thanks for testing!
Good idea with the `< ... >`, will add that.

**Pull request merged**
