### PR TITLE
fix #15543: adapt to gc.com login page change

### LINKED ISSUE #15543: Login error - "Failed to find request verification token"
At this moment some users on social media and support report this login problem.
Its also reproducible to me with current nightly build.

As the website in browser seems to work just fine, I assume it could be a website change....could still be a temporary isseu on their side though..

Lets monitor...or maybe someone can reproduce and debug right now?

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #15543: adapt to gc.com login page change

### CODE REVIEW

**Comment by eddiemuc** [comment]
Looks like trackable log parsing is also broken

**Comment by Lineflyer** [comment]
Shall we merge, so I can merge upstream and produce a new nightly to help with further function testing?

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
I have several tests failing with this PR. Those failing test point to other problems caused by gc.com website changes. I won't be able to look deeper into those. Also they somehow seem to change from build run to build run - probably the website is still under change.

It might make sense to apply this PR despite the failing tests to at least fix the login issue.

**Comment by Lineflyer** [comment]
I will wait until the latest test run is complete and merge PR and branches once I don't see any login related fails.

**Pull request merged**
