### PR TITLE
Fix #6682: Failed to detect loggin status

### LINKED ISSUE #6682: Error displayed when do a cache log
##### Detailed steps causing the problem:
- Open a geocache
- Log as "found it"
- When you are submitting it display an error saying "login failed"
- Reload geocache information, you see that the log was submitted successfully

It begin to appear, after new Geocaching.com layout.

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

### PR DESCRIPTION
**Pull request by kumy**
GS has changed some style.
Adapt the regex to correspond to the new format.

### CODE REVIEW

**Comment by kumy** [comment]
@Lineflyer do you have time to test the build from the CI?

**Comment by kumy** [comment]
There seems to have more changes than expected...

For example, on the `settings/homelocation` page, some html parts are now(?) embedded in `script` tags! Which break `document.select("input.search-coordinates").attr("value")`

```
<script type="text/x-handlebars-template" id="tplSearchCoords">
    <div class="search-coordinates-wrapper">
        <input class="search-coordinates" id="Query" name="Query" placeholder="Location&#32;(city&#32;or&#32;postal&#32;code)" type="text" value="xxx" />
        <span class="btn-wrapper">
            <button id="search" class="btn btn-primary">Search</button>
        </span>
    </div>
</script> 
```

**Comment by Lineflyer** [comment]
Do I interprete your comment and the CI result correct, that you need to recheck for other changes before it makes sense to test?

**Comment by kumy** [comment]
Last (failed) build should at least fix the logging problem with cache and TB. However unit tests reveal more hidden problems.

**Comment by kumy** [comment]
Other problems:
* One cache used for Unit testing is now archived (should not be a big problem)
* Home location failed to be detected, due to html changes...

**Comment by kumy** [comment]
All tests should now be ok.
@Lineflyer ready to test?

**Comment by kumy** [comment]
I think we could ignore the build failed.
CI has two build chains. The one marked as expirimental always fail since some time, whereas the [other one](http://ci.cgeo.org/job/cgeo%20continuous%20integration/1684/) ended with success.

**Comment by Lineflyer** [comment]
IMHO your change looks straight forward enough to merge first and directly test with a RC version.
I will do that in some minutes and provide feedback.

Can you say something about "backwards compatability", i.e. If they roll back to the old elements, will your change still cope with that?

**Comment by Lineflyer** [comment]
Question to the Git experts:
When merging via Github webpage, shall I use "rebase and merge" or "squash and merge"?

**Comment by kumy** [comment]
> Can you say something about "backwards compatibility"

* first commit 846bf53 should not be a problem in case of a rollback on their side (login detection)
* second commit 78fd083 ***will be** problematic* (home coordinates detection)

**Comment by kumy** [comment]
@Lineflyer for this current PR, don't use "squash" method please as I've intentionally separated commits for each error. So "rebase and merge" is the way to go. :)

**Pull request merged**
