### PR TITLE
optionally assign icon marker to lists

### PR DESCRIPTION
**Pull request by moving-bits**
Third part related to #7761: optionally assign icon marker to lists and display those markers on map and in cache lists

assign marker to list or remove it from list:

grafik

markers are shown in cache list...

grafik

... and on the map:

grafik

### CODE REVIEW

**Comment by moving-bits** [comment]
Hm, looking at the screenshots I notice something strange: Adding an overlay / inset to a drawable seems to change the drawable's size. How come? Might have the same cause as #5193.

**Comment by moving-bits** [comment]
> Hm, looking at the screenshots I notice something strange: Adding an overlay / inset to a drawable seems to change the drawable's size. How come? Might have the same cause as #5193.

I added a fix for this with PR #7779, which needs to get merged before this one. Need to adjust a few things (to resolve merge conflicts) after merging #7779 and before merging this one, therefore setting the "WIP" label here for now.

**Comment by Lineflyer** [comment]
From where do you assign these markers?
Is it only possible from the cache list view or is there also a menu/visualization in cache details?

**Comment by moving-bits** [comment]
> From where do you assign these markers?
> Is it only possible from the cache list view or is there also a menu/visualization in cache details?

Those markers are related to a list, not to an individual cache, so assigning them is done from cache list view: manage lists => set list marker.

**Comment by Lineflyer** [comment]
> Those markers are related to a list, not to an individual cache, so assigning them is done from cache list view: manage lists => set list marker.

Oh, this is indeed a neat method for the tags and pretty straight forward and understandable.

**Comment by Lineflyer** [comment]
Merged and I will test and provide feedback.
Any depending PRs should be adapted accordingly as @moving-bits described in #7761

**Comment by okainov** [comment]
@moving-bits thanks!

BTW have you seen https://github.com/cgeo/cgeo/issues/3523 and https://github.com/cgeo/cgeo/issues/5798? Seems very related :)

**Pull request merged**
