### PR TITLE
provide #9039 and #9068 for legacy version (fix #9075)

### LINKED ISSUE #9075: Apply login failure case detection to legacy version
Recently there have been changes:
- Correction for detecting wrong credentials
- New error cause if captcha is needed on gc.com while logging in

These changes should also be applied to `legacy` in order to release a new legacy version with correct login failure detection

### PR DESCRIPTION
**Pull request by moving-bits**
- detect captcha on login
- fix detection of wrong username/password on login

### CODE REVIEW

**Comment by Lineflyer** [comment]
retest this please

**Comment by moving-bits** [comment]
fix for tb change provided with #9079, can rebase and retest this PR after merging the other one to cgeo-legacy

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
No need to rebase IMHO as the PR always bases on the branch to be merged to. Theoretically the test should pass now after #9079 was merged.

**Pull request merged**
