### PR TITLE
fix #5784: wrong date when logging trackable early in the day

### LINKED ISSUE #5784: Wrong date when logging trackables very early?
I logged a trackable this morning at 6:10 German time. When I refreshed the trackable afterwards, it was shown logged yesterday. I had not changed the date selector, so I'm somewhat sure it was not set to yesterday. Might this be a problem with the time offset of -7 hours that we use somewhere?

I can't verify this behaviour at the moment, since I have no private tracking code available. Will re-test one of the next days with my own trackables.

### PR DESCRIPTION
**Pull request by samueltardieu**
The code for handling today as a special day and for handling the former
geoaching.com fields is removed.

### CODE REVIEW

**Comment by samueltardieu** [comment]
Please test early in the morning before merging.

**Comment by Bananeweizen** [comment]
might take some days until I really have time in the morning (and manage to remember this issue with a foggy brain) :)

**Comment by rsudev** [comment]
I try to cross check tomorrow

**Comment by rsudev** [comment]
I was able to verify this morning that it works with this change

**Comment by samueltardieu** [comment]
Great. Let's hope I haven't broken all other cases in the process :-) I'll merge.

**Pull request closed without merging**
