### PR TITLE
DocumentContentAccessor: add debug logging

### PR DESCRIPTION
**Pull request by eddiemuc**
DocumentContentAccessor: add debug-level logging.

Related to SAF discussion, trying to help with debugging those cases

### CODE REVIEW

**Comment by eddiemuc** [comment]
Related to #13865

**Comment by eddiemuc** [comment]
failing tests in CI are unrelated

**Comment by moving-bits** [comment]
Failing tests are unrelated, but...

retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by eddiemuc** [comment]
Failing tests are still unrelated :-) So let's merge here to get some analysis options

**Pull request merged**
