### PR TITLE
update contacts to api29

### PR DESCRIPTION
**Pull request by bekuno**
set compileSdkVersion and targetSdkVersion to 29 according to c:geo

### CODE REVIEW

**Comment by Lineflyer** [comment]
Shall we release a new plugin version before we merge this?

**Comment by bekuno** [comment]
> 
> 
> Shall we release a new plugin version before we merge this?

We can wait with this PR.

**Comment by Lineflyer** [comment]
@bekuno 
Almost forgot about this one.
I just built and released contacts plugin version 2020.10.13 (new versioning similar to main app). That was still targeting API 28.
Now we can merge this (unless it makes no sense as we rather want to integrate the function back into the main app).

**Comment by bekuno** [comment]
> Now we can merge this (unless it makes no sense as we rather want to integrate the function back into the main app).

Lets merge.
It is not urgent to integrate it in the main app. 
But I hope that I will find time to do it sometime this year.

**Comment by rsudev** [comment]
As long as we support Android versions that don't have user-selectable App permissions, we should not integrate it again in order to not require contact permissions generally.

**Pull request merged**
