### PR TITLE
Fix NPE on waypoint-projection (fix #16041)

### LINKED ISSUE #15756: Waypoint projection does not instantiate variables
### Describe your problem!

Using variables in waypoint projection (see #12600) does not create variables.

### How to reproduce?

1. Create a new waypoint
2. Set starting coordinates
3. Select "projection"
4. Enter variables in heading/distance
5. Save waypoint

### Actual result after these steps?

No variables were created in the variables page.

### Expected result after these steps?

Variables should be created in the variables page like it's done for the regular waypoint calculator. Additionally it would be nice to have the same quick access to variables as in the waypoint calculator.

### Reproducible

Yes

### c:geo Version

2024.05.11-NB-c926353

### System information

_No response_

### Additional Information

_No response_

### LINKED ISSUE #16041: [Nightly] Crash on waypoint projection
### Describe your problem!

When trying to add a projection to a waypoint, c:geo crashes as soon as you try to enter the very first numeric value

### How to reproduce?

1. create a new waypoint
2. set wp's coordinates to e. g. cache coordinates
3. add projection => Bearing (you can also chose Offset, makes no difference)
5. try to enter a number into either distance or bearing field ...

### Actual result after these steps?

6. c:geo immediately crashes

### Expected result after these steps?

Guess what.  ;)

### Reproducible

Yes

### c:geo Version

2024.09.07-NB-d93f2b2

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by murggel**
## Description

Fix NPE on waypoint-projection

Function `ensureFormula `does only ensure a valid formula but formula == null is still possible after that
checking for formula != null
If formula is null, the variables are created from the formulaString (has to compile for that)

## Related issues

fix #16041
fix #15756

### CODE REVIEW

**Review by eddiemuc — APPROVED** [review]
Lgtm

**Comment by murggel** [comment]
While testing I detected, that creating of the projection variables for #15756 does not work properly after the review-changes.
This PR will fix both effects - same code-line ;-)

**Comment by murggel** [comment]
@eddiemuc - ready for re-review

**Comment by eddiemuc** [comment]
Thanks for this fix!

**Pull request merged**
