### PR TITLE
"remove list" optimizations

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
- restore "remove list" dialog (reverts #11182)
- add option "do not ask me again" on a per-list basis
- add option to reset this flag for a list

|new dialog option|option to reset flag|option is disabled if flag not set|
|---|---|---|
|image|image|image|

### CODE REVIEW

**Comment by fm-sys** [comment]
Can we change the checkbox string to "don't ask again for this list" to make clear this is a per-list setting?

**Comment by moving-bits** [comment]
> Can we change the checkbox string to "don't ask again for this list" to make clear this is a per-list setting?

Sure. I had reused an existing string, but I agree a more specific string will be more precise.

**Comment by bekuno** [comment]
If I set "do not ask again" and hit "yes" - how it will work later?
If I create a list with the same name (case insensitive?) - is then this setting in use for this list?

**Comment by moving-bits** [comment]
> If I set "do not ask again" and hit "yes" - how it will work later?
> If I create a list with the same name (case insensitive?) - is then this setting in use for this list?

Setting is stored list-specific in the `cg_lists` table. If you remove a list (and not undo this), every info attached to the list is removed as well (name, list marker, "do not ask" setting etc.). 
If you create a new list (or recreate a list using the same name), the "do not ask me" setting defaults to `false` (or "0", to be more precise)

**Comment by bekuno** [comment]
Ok. What about clarifying the string to "When 'No', do not ask me again for this list"?

**Comment by fm-sys** [comment]
> Ok. What about clarifying the string to "When 'No', do not ask me again for this list"?

I think this would just make things harder to understand. We could rather just grey out the "yes" button if the checkbox is checked (like we already do it for one-time messages so this would only be consistent)

**Comment by moving-bits** [comment]
I've added checkbox handling as described above:

image

**Pull request merged**
