### PR TITLE
rel to #12783: add an own detail image viewer

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #12783: add an own detail image viewer

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by ztNFny** [comment]
just pulled this into my branch for some testing, only 1 big change to make it somewhat usable:

imageview_activity.xml:
-> android:scaleType="centerInside"

**Comment by ztNFny** [comment]
just pulled this into my branch for some testing, pushed some small changes to make it somewhat usable in day-to-day usage

**Comment by eddiemuc** [comment]
Hi @ztNFny actually I plan to rework or even abandon this PR since it is based on PhotoView library, and I wanted to rework the whole thing based on Loupe (see discussion in #12783)

**Comment by ztNFny** [comment]
oops, I thought this was already the new one

**Comment by moving-bits** [comment]
@eddiemuc 
FYI: Somehow your CheckStyle config file slipped into this PR

**Comment by eddiemuc** [comment]
> @eddiemuc FYI: Somehow your CheckStyle config file slipped into this PR

Whoops, thanks for the hint. I will revert this

**Comment by eddiemuc** [comment]
PR is now ready for review/merge

**Comment by eddiemuc** [comment]
Some images to get an impression. GUI is subject to discussion, I want to have this in master so the team + nightly users have a chance to give their feedback. Feature is not yet visible in beta/production.

image

Own image:

image

Zoomed:

image

Transition from one image to next (swipe right/left):

image

Listing Image with comment:

image

Log Image:

image

Images with metadata:

image

image

**Comment by eddiemuc** [comment]
Update: added "full image view" on single tap on image.

**Pull request merged**
