### PR TITLE
rel to #13551: fix nullpointerexception in ImageUtils.forEachImageUrlInHtml

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #13551: fix nullpointerexception in ImageUtils.forEachImageUrlInHtml

### CODE REVIEW

**Comment by Lineflyer** [comment]
@eddiemuc Shall we put this also onto branch `release` as it was reported for the market version?

**Comment by eddiemuc** [comment]
> @eddiemuc Shall we put this also onto branch `release` as it was reported for the market version?

The reported NPE could not have happened in release since I did not put the original change there. If the problem is in release, it must have another origin

**Comment by Lineflyer** [comment]
At least @murggel reported the problem for the market version and now says its gone (for now)...still might be unassociated.

**Comment by murggel** [comment]
> At least @murggel reported the problem for the market version and now says its gone (for now)...still might be unassociated.

I use the nightly Version- probably noted lnly the date but notvthe nightly-postfix to version...

**Pull request merged**
