### PR TITLE
include trailheads in waypoint numbering

### PR DESCRIPTION
**Pull request by moving-bits**
see https://github.com/cgeo/cgeo/issues/9041#issuecomment-756118022
- include trailheads in numbering for new waypoint names
- fix "*" to "+" in regular expression

### CODE REVIEW

**Comment by moving-bits** [comment]
@Lineflyer 
One of the failing tests mentions "GC3FJ5F" which is one of your caches. Anything changed with that cache recently?

Or do those tests fail randomly, as we had both green and red build today, with seemingly unrelated tests failing.

**Comment by Lineflyer** [comment]
gc.com is down or nearly unreachable in the last few hours. Start page and surroundings seem OK, but database (=cache) is slooooow.

**Comment by fm-sys** [comment]
retest this please

**Comment by moving-bits** [comment]
now it has worked, thanks @fm-sys + @Lineflyer

**Pull request merged**
