### PR TITLE
Enhancements to map quick settings popup (rel. to #8138)

### PR DESCRIPTION
**Pull request by moving-bits**
A step towards #8138:
- add circles, direction line, compact icon, routing to quick settings
- highlight selected buttons with colorAccent
- remove old menu entries from map overflow menu

image

(more to come)

### CODE REVIEW

**Comment by MagpieFourtyTwo** [comment]
> highlight selected buttons with colorAccent

Looks good!  :)

**Comment by MagpieFourtyTwo** [comment]
Maybe the color of the routing strategy symbols can be a bit lighter, same color as the texts of "Use compact icons"?

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
- fixed errors preventing the build
- switch all settings to positive "show ..." instead of mix of "hide" and "show"
- recalculating a route only gets triggered on routing mode change

image

**Comment by MagpieFourtyTwo** [comment]
> retest this please

The contrast of esp. the routing buttons is still too low. For better visibility of esp. the selected symbol, the symbol itself should be plain white, like the texts of the compact symbols buttons. 

While the same applies to all text in the popup, being kind of grey, which is not consistent with all the other menus.

**Comment by moving-bits** [comment]
@MagpieFourtyTwo 
Ah, you're right, have to work on the text contrast yet - this task got lost in the many comments of #8138. (Easier to have a separate issue for that... Not needed in this case, though, I'm already working on it.)

As for the buttons: I took the color from one of the other buttons. I would not use plain white in this case - too bright, and also not visible in light mode. (Most of our buttons are one-colored only, for both dark and light theme.) I'll try to make it a bit lighter, taking the shade from a different button.

**Comment by MagpieFourtyTwo** [comment]
Fine! Thx!

**Comment by MagpieFourtyTwo** [comment]
Just checked the new symbol and text color - looks good.

Perhaps it would even look better, if the dark contour line of the symbols would be darker / more visible, to increase recognizability of the currently selected symbol (border between white symbol and orange background looks a bit blurry, and the contours are a bit hard to see with the luminous background) ... but this may even be just a matter of taste ...

Nevertheless: Working with the Quick settings popup is a true joy!  :)

**Comment by moving-bits** [comment]
I played a bit with the image settings. How about those:

imageimage

**Comment by Lineflyer** [comment]
> I played a bit with the image settings. How about those:

Without having compared with current status it looks good IMHO.
BTW: Did you notice, that the accent color is not applied to the checkboxes when used in Google Maps?

**Comment by fm-sys** [comment]
> BTW: Did you notice, that the accent color is not applied to the checkboxes when used in Google Maps?

It's part of a larger theming problem tracked in #7587

**Comment by MagpieFourtyTwo** [comment]
Already wondered why they are blue in the screenshots. No, did not notice yet. But to be honest, I do not really like GM and use it for very high zoom levels only, cause it gives a better, i. e. not that cluttered overview (admittedly, zoom level definitions are still way better than in OSM), and GSat just sometimes, to get a better impression of the terrain, so this curiosity would have been a secret to me for a really long time ... ;)

As for the symbols: They still look a bit blurry, but they can be recognized way better, IMO. So I would be happy with them.

Thx for investigating!

**Comment by moving-bits** [comment]
> > BTW: Did you notice, that the accent color is not applied to the checkboxes when used in Google Maps?
> 
> It's part of a larger theming problem tracked in #7587

I found a solution for applying `colorAccent` to our Google Maps, see #9515.

**Comment by MagpieFourtyTwo** [comment]
Just wanted to note that the Quick Settings popup is a real joy to work with, esp. for changing the Routing Strategy.
Although I still catch myself occasionally, still heading towards the Hamburg menu to change it ... ;)
What I find remarkable: The number of clicks has remained the same, it still needs three clicks to re-route,
nevertheless it feels so much faster, easier and way more natural. Cool.
I guess it's because of a) shorter distances (esp. for the thumb), b) there's no need to reposition the phone anymore (esp with >6") or use the other hand, and finally you c) don't have to concentrate and read text to do so. It has become a real no-brainer.

BTW: Another wish, voiced a while ago, just crossed my mind: What would you think about different Routing Strategies for "normal" and individual routes? IIRC the idea has been dropped the other day, cause it was supposed to be too hard to understand and control for the average user ... but with the Quick settings menu it's as easy as one, two, three: Just another row of Routing Strategy symbols with a different header like ``Routing for Individual Routes`` and that's it ... at least seen from the operator's view ... ;)

If you agree, I would open an FR for it ...

**Comment by moving-bits** [comment]
Thanks for your feedback! Happy to see if that's an UX improvement.

Regarding the separate routing strategy for individual routes: That's #8323 - not forgotten, not closed, only not yet implemented... :-)

**Comment by MagpieFourtyTwo** [comment]
Ah, you're right - thanks for the reminder!  ;)

**Pull request merged**
