### PR TITLE
Revert "temporarily disable GC watchcount test which fails due to website changes"

### PR DESCRIPTION
**Pull request by UniQP**
This reverts commit bfc871b60037bc95910fb2c2c402fab563a5f094.

### CODE REVIEW

**Comment by Lineflyer** [comment]
Didn't you include this reversion also in your PR #10983. IMHO its better suited there as otherwise CI checks on `release` will keep failing..

**Comment by Lineflyer** [comment]
Addon: Or was the test only deactivated on `master` initially...sorry did not find time to check that.

**Comment by UniQP** [comment]
The test was only disabled on `master`. That's why I opened this PR after retargeting #10983 to `release`.

**Comment by Lineflyer** [comment]
Perfect. Merged both.

**Pull request merged**
