### PR TITLE
Test basic VTM (similar to MapFragment example)

### PR DESCRIPTION
**Pull request by moving-bits**
Do not merge / PR just for reference, see issue #15100

Mimics VTM's example "MapFragment"
(Requires "Berlin (OAM).map" file to be present in configured map folder.)

### CODE REVIEW

**Comment by ztNFny** [comment]
With this one I get strange non-black artifacts:
image

latest Germany OAM

**Comment by moving-bits** [comment]
thanks for cross-checking. I had this kind of artifacts as well when using the VTM.DEFAULT theme - may or may not be related to the cross-hatch issue (which is part of #15100 and got solved meanwhile by the change in #15310).

But no black labels for street names etc., no blinking when using this version?

**Comment by ztNFny** [comment]
> But no black labels for street names etc., no blinking when using this version?

No, but I fear that doesn't mean much as with "normal" builds I get black when enabling live which isn't possible here.

**Comment by moving-bits** [comment]
Ok, I've updated this PR to include the "transparent line" fixes for VTM and checks for germany (oam).map as well as Elements.zip theme for easier testing. I don't get black boxes anymore with @murggel's test case (https://github.com/cgeo/cgeo/issues/15100#issuecomment-1939449817)

**Comment by moving-bits** [comment]
with getting positive result from #15411 so far, we can close this WIP

**Pull request closed without merging**
