### PR TITLE
remove unused eclipse parts

### LINKED ISSUE #8980: remove old eclipse parts
In the last years no changed code parts for eclise. Now this is all outdated.
Therefore I vote to delete this.

I think e.g. about
- code-copy for play-services-base, -basement, -location
- .derived
- .settings
- .classpath
- .project
- .externalToolBuilders
- project.properties
- launch
- .factorypath
- manifest.mf

What do you mean?

### PR DESCRIPTION
**Pull request by bekuno**
fixes #8980

Delete the old play-* backups and eclipse / eclipse plugins configuration files and folders.

@rsudev , @SammysHP , @UniQP 
You have already worked on the c:geo code before AS.
Do you need something for the future or have I missed something?

### CODE REVIEW

**Comment by bekuno** [comment]
@rsudev Please have a look at the changes

**Comment by bekuno** [comment]
@rsudev Please have a look at this PR.

**Comment by bekuno** [comment]
@rsudev @UniQP Please review the changes.

**Review by UniQP — CHANGES_REQUESTED** [review]
I never used Eclipse for c:geo but I found some files/directories that can also be removed:
```
./cgeo-contacts/.checkstyle
./main/.checkstyle
./tests/.checkstyle
./main/project/attributes_okapi/AttrGen/.classpath
./main/project/attributes_okapi/AttrGen/.project
./main/project/attributes_okapi/AttrGen/.settings
./viewpagerindicator/.classpath
./viewpagerindicator/.project
./viewpagerindicator/.settings
```

There are also some eclipse-specific non-null asserts in the code but we can also remove them in a separate PR.

**Comment by bekuno** [comment]
> 
> 
> I never used Eclipse for c:geo but I found some files/directories that can also be removed:
> 
> ```
> ./cgeo-contacts/.checkstyle
> ./main/.checkstyle
> ./tests/.checkstyle
> ./main/project/attributes_okapi/AttrGen/.classpath
> ./main/project/attributes_okapi/AttrGen/.project
> ./main/project/attributes_okapi/AttrGen/.settings
> ./viewpagerindicator/.classpath
> ./viewpagerindicator/.project
> ./viewpagerindicator/.settings
> ```
> 
> There are also some eclipse-specific non-null asserts in the code but we can also remove them in a separate PR.

Thanks for have a look at this PR.
I removed the .checkstyle files.
The AttrGen/* are already removed after anoter PR (rebased this PR)
The viewpagerindicator is untouched. It is an external source only as reference.

**Comment by bekuno** [comment]
> There are also some eclipse-specific non-null asserts in the code but we can also remove them in a separate PR.

Yes, a separate PR would be better.

**Comment by bekuno** [comment]
rerady to merge from my side.

**Comment by UniQP** [comment]
Sorry, missed `tests/.settings` before.

**Comment by bekuno** [comment]
> 
> 
> Sorry, missed `tests/.settings` before.

I also.
Thanks.

**Review by UniQP — APPROVED** [review]

**Comment by moving-bits** [comment]
@bekuno 
"WIP" flag is still set, but above you say "ready to merge". Anything that needs to be done here, or can we merge it?

**Comment by bekuno** [comment]
There are no negative comments to it.
You can merge it to master if it make sense.

**Comment by moving-bits** [comment]
Ok, thanks for the reply. Then let's merge...

**Pull request merged**
