### PR TITLE
Use textVisiblePassword instead of textCapCharacters

### PR DESCRIPTION
**Pull request by lazydays79**
This fixes issue #7148

### CODE REVIEW

**Comment by SammysHP** [comment]
ok to test

**Comment by lazydays79** [comment]
I tried to check why cgeo.geocaching.address.GeocoderTest.testAndroidGeocoder fails (org.junit.ComparisonFailure: [country code for Android .geocoder] expected:<"FR"> but was:<null>), but locally it runs without any failure...

**Comment by rsudev** [comment]
@lazydays79 Sorry for not jumping in earlier: the geocoder might fail, as it uses a service which has a request limit (we currently don't know any which is free and open source compatible).

**Comment by lazydays79** [comment]
Ah, ok. I just was afraid that my PR could be rejected due to a failing build. 😅

**Comment by rsudev** [comment]
I looked thorugh the change (easy enough :) ) and have only one question: Did you check whether the lower case input also works with other caching sites (like oc.de/pl/...) as well?
Looking at the Android dev docs associated with this, it looked like it might even be possible to combine these flags (to perhaps achieve capitalized input alongside numbers available). Did you consider this or have I misinterpret the docs? Might not be overly necessary if the lower case input works for all cache sites, but could still be helpful if users don't know that lower case works.

**Comment by rsudev** [comment]
So, in the meanwhile checked both of my questions. Searching with lower-case works even for OC caches and adding textCapCharacters does not have an effect together with textVisiblePassword.
BTW, textVisiblePassword didn't have the desired effect (keyboard with letters and numbers) on my SDK 22 emulator instance...
Nevertheless a nice addition IMO, the remaining question is, whether this is not better suited on master (our general collection branch for new features and non-urgent bug-fixes).

**Comment by lazydays79** [comment]
Hi!

No, I didn't check it with oc sites.

But combining the flags is a good idea worth trying. I will test that today
or tomorrow.

If it doesn't work, we could upcase the strings in the Text Fields before
sending the requests. Wdyt?

Regards,
Michael

rsudev <notifications@github.com> schrieb am Mo., 1. Okt. 2018, 09:08:

**Comment by lazydays79** [comment]
Oh, didn't see your 2nd reply. 😂

Did you use the standard android keyboard in your emulator?

rsudev <notifications@github.com> schrieb am Mo., 1. Okt. 2018, 20:58:

**Comment by rsudev** [comment]
I guess so (at least I didn't actively change anything in that area). It might be because in that keyboard the numbers are available (and depicted as such) on long press on the upper row of characters.
I personally would suggest (if you don't mind) to re-target the PR against master, then I'll merge it right away.

**Comment by UniQP** [comment]
Maybe a changelog entry would also be nice.

**Comment by lazydays79** [comment]
Sure, master sounds good. 👍

Thanks!


rsudev <notifications@github.com> schrieb am Mo., 1. Okt. 2018, 21:31:

**Comment by lazydays79** [comment]
> I personally would suggest (if you don't mind) to re-target the PR against master, ...

Done

**Comment by lazydays79** [comment]
> Maybe a changelog entry would also be nice.

Done

**Comment by rsudev** [comment]
I know it's kind of tiring, but in order to have an understandable history - could you squash your changes into one commit please?

**Comment by lazydays79** [comment]
I can't get lose at least the merge commit, but all the others have been squashed. If this is not satisfying, I suggest to cherry-pick 7aff8e5de155af144a76663158365d02df1fb794

**Comment by rsudev** [comment]
As the new sqashed commit contained the complete change and was based on latest master, I just pushed it.
So all is done, thanks for your contribution!

**Pull request closed without merging**
