### PR TITLE
backup / restore program settings (shared prefs)

### PR DESCRIPTION
**Pull request by moving-bits**
backup / restore program settings (shared prefs)

- shared prefs are saved as XML file in downloads dir
- with or without account related data
- backup / restore as separate settings page
- backup / restore as menu entry in main screen

This is to ease the process of uninstalling and reinstalling c:geo, e. g. when switching between nightly and release version.

The new backup settings screen:
image
If we are going to add a backup function for cache images etc. (see #7692) it could be added here as well.

### CODE REVIEW

**Comment by SammysHP** [comment]
I think we should mention more explicit that the *full* backup contains unencrypted passwords.

**Comment by moving-bits** [comment]
> I think we should mention more explicit that the _full_ backup contains unencrypted passwords.

There is a dialog box specifically for this, which opens only when you chose the full backup.

**Comment by Lineflyer** [comment]
Thanks for your PR @moving-bits 
Looking at the plan phrased in #7665 I suggest to merge only after next branching from `master` to `release` which is hopefully not so far away from now.

**Comment by moving-bits** [comment]
This would be ok for me. - On the other hand: Merging this PR to master shouldn't be too risky - core backup database functionality is untouched (except moving it to a separate settings/preferences screen), and the new backup/restore program settings is following standards (and even if this would not work it would be no regression).

**Pull request merged**
