### PR TITLE
#6594 use mapsforge beta as default

### PR DESCRIPTION
**Pull request by pstorch**
Moved the BetaMap preference into the MapsPreferences section and reverted its logic. 
Now a user can choose to use the Old Mapsforge API as fallback if something is wrong. The new map is default now.

Google Maps is now selectable in the MapsMenu regardless of the chosen Mapsforge API.

### CODE REVIEW

**Comment by rsudev** [comment]
The general approach is spot-on. There are two small issues that I observed when looking briefly.
The zoom levels do not match up between google and mapsforge (switching from google to mapsforge zooms in considerably. this is likely my fault, as the zoom-level definition/calculation/adaption likely is wrong).
Switching back from google to mapsforge creates an empty map for me (no caches loaded), probably due to the missing MapOptions in the intent when coming from there, I can take a deeper look into it later today.

**Comment by pstorch** [comment]
@rsudev thanks for your help. The part with the maps in c:geo is still new to me.

**Comment by Lineflyer** [comment]
> Switching back from google to mapsforge creates an empty map for me (no caches loaded)

IMHO we have a dedicated issue for that.

**Comment by pstorch** [comment]
> > Switching back from google to mapsforge creates an empty map for me (no caches loaded)
>
> IMHO we have a dedicated issue for that.

Found it: #6149

**Comment by pstorch** [comment]
I tried to look into the zoom and missing caches issue reported by @rsudev.

Not much success. I see that the old mapsforge view has an offset of 1 to the google zoomlevel (which we store in the preferences) and the new map uses an offset of 3. If I change it to 1 I see other issues.

Regarding the missing caches when switching back from the google maps: I could only partly reproduce. In non-live-mode it was not an issue. In live mode it heavily depended on how I zoomed and scrolled around on the map. Sometimes the caches vanished and when zoomed or scrolled, they suddenly reappeared. 

The only thing I fixed was a possible nullpointer which I saw in the log while testing.

In the meantime mapsforge is already at release 0.9.1, we are still using 0.8.0. Should we upgrade?

**Comment by rsudev** [comment]
I had also looked into the zoomlevel issue and I have the feeling, that mapsforge and google maps define and use this differently. MAybon google maps in relation to the display and mapsforge in relation to the tiles. The reload issue is likely independent from the map switch as such and of secondary importance IMO.
Hopefully I can give the zoom issue another spin tomorrow...

**Comment by rsudev** [comment]
And yes, we should look into upgrading IMO.

**Comment by pstorch** [comment]
I've included the upgrade to Mapsforge 0.9.1 as a separate commit and I think I found the error that the zoomlevel increased on every change between google maps and mapsforge.
I think the maps from offline lists work quite ok. The main problem for me is the livemap. On the new mapsforge map the markers suddenly disappear. Then you have to zoom or scroll around to get them loaded again. Don't know yet what is causing it.

**Comment by Matze2** [comment]
Just to get some movement back on this PR.
As soon as this one is merged to master I would give it a try.

**Comment by rsudev** [comment]
I already started several attempts to tackle the zoom problem in its various aspects, but did not yet reach anything which worked consistently across screen resolutions and map types.
But I would be fine with giving this a spin on master, that makes it also easier to address the upcoming issues one at a time and broaden the testing as well.

**Comment by Lineflyer** [comment]
+1

**Pull request merged**
