### PR TITLE
Fix #5887: Use mobile version of translation website

### LINKED ISSUE #5887: Better url for Google Translatebgiving mobile version
I propose to use the mobile version of Google translate in c:geo.

##### Detailed steps causing the problem:
- Step 1
Open log of a cache
- Step 2
Long press a log in a forreign language.
- Step 3
Select to translate into your native tongue
- Step 4
Observe that you are taken to the desktop version of Google translate. 
- Step 5
Append /m/translate to the URI path, prior to the GET varisbles, to go directly to the mobile version of Google translate. 

Example URI
https://translate.google.com/m/translate?vi=c#auto/en/Der%20heutigen%20Tag%20begann%20wieder%20mit%20Sonne.%20Dies%20freute%20uns%20nat%C3%BCrlich%20besonders%2C%20da%20ein%20sonniger%20Cachetag%20wesentlich%20mehr%20Spa%C3%9F%20macht.%20Gem%C3%BCtlich%20starteten%20wir%20nach%20dem%20Fr%C3%BChst%C3%BCck%20und%20konnten%20auch%20heute%20wieder%20recht%20erfolgreich%20sein.%20Im%20Team%20mit%20Q3%20auf%20Tour%20gewesen.%20TFTC%20Gr%C3%BC%C3%9Fe%20aus%20Deutschland%20Orientexpress
##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```

### PR DESCRIPTION
**Pull request by UniQP**

### CODE REVIEW

**Comment by kumy** [comment]
We may also enable ssl by default. Than will prevent one redirect.

**Comment by samueltardieu** [comment]
@UniQP: Have you checked that the application still intercepts the request if installed?

**Comment by samueltardieu** [comment]
Also, please base this change against `release` rather than `master` so that it can go into the next release.

**Comment by UniQP** [comment]
@samueltardieu I did not checked whether the apps intercepts, because the patch just changes the URL, which is unrelated.

Will close this issue and will open a new PR against release.

**Pull request closed without merging**
