### PR TITLE
Annotation calls that should run on background thead

### PR DESCRIPTION
**Pull request by NotWoods**
## Description

Trying to catch blocking network calls on the main thread by adding `@WorkerThread` annotations to network code. This helps with readability and adds additional checks in Android Studio.

### CODE REVIEW

**Comment by fm-sys** [comment]
Ideally, we should fix the network on main thread issue instead of not adding the annotation to the relevant methods (https://github.com/cgeo/cgeo/pull/13126/commits/0cb7107d6df3b8afc975985ac92041bd00772308). Not sure if this is possible without larger refactoring though...

**Comment by NotWoods** [comment]
I'd prefer to leave that to a different PR since it requires a bigger refactoring

**Comment by fm-sys** [comment]
> I'd prefer to leave that to a different PR since it requires a bigger refactoring

Fine for me. However, we should open a follow-up issue to keep track which methods are affected by "network on main-thread"

**Comment by moving-bits** [comment]
> > I'd prefer to leave that to a different PR since it requires a bigger refactoring
> 
> Fine for me. However, we should open a follow-up issue to keep track which methods are affected by "network on main-thread"

I've created #13153 for this

**Pull request merged**
