### PR TITLE
fix #5541: don't reload after adding to list

### LINKED ISSUE #5541: don't reload after adding to list
###### Detailed steps causing the problem:
- Open cache details activity, scroll down
- Add to list

###### Actual behaviour after performing these steps:
Details activity refreshes, we jump to the top of the screen

###### Expected behaviour after performing these steps:
No reload/refresh of the activity, but just refreshing the view containing the list names

### PR DESCRIPTION
**Pull request by pstorch**
Geocache.searchByGeocode() didn't recognize already cached Geocache correctly.

### CODE REVIEW

**Comment by samueltardieu** [comment]
You have to fix the tests as well (and ideally run them before submitting) :)

**Comment by pstorch** [comment]
You are right, I really have to remember to run the tests before pushing.
I saw the failing CI build, but I couldn't determine what went wrong.
So I just executed locally ```./gradlew testBasicDebugUnitTest``` to find out what happend, but got a *BUILD SUCCESSFUL*, what is wrong?

**Comment by samueltardieu** [comment]
@pstorch The CI runs `./gradlew --no-daemon --stacktrace testDebug -Pandroid.testInstrumentationRunnerArguments.notAnnotation=cgeo.geocaching.test.NotForIntegrationTests`

**Comment by pstorch** [comment]
@samueltardieu thanks. I tested it again yesterday and this time `./gradlew testDebug` showed me the compile error in the test. Don't know what happened last time. 
But I'm still confused about AndroidStudio not showing me all compile errors after save. It seems it only compiles the current open tab. Have to get used to initiating an overall build manually.

**Pull request merged**
