### PR TITLE
Improve image gallery in context of trackable 

### LINKED ISSUE #13030: Image gallery not working for trackables
### Describe your problem!

Single image view cannot open for trackables... 

### How to reproduce?

https://user-images.githubusercontent.com/64581222/169488398-fa585d14-ba39-4d27-b3e1-38c83d1ee7b5.mp4

### Actual result after these steps?

```
05-20 10:09:18.167 11877 11877 E AndroidRuntime: FATAL EXCEPTION: main
05-20 10:09:18.167 11877 11877 E AndroidRuntime: Process: cgeo.geocaching, PID: 11877
05-20 10:09:18.167 11877 11877 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setTransitionName(java.lang.String)' on a null object reference
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at cgeo.geocaching.ImageViewActivity.openImageView(ImageViewActivity.java:481)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView.openImageViewer(ImageGalleryView.java:466)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView.access$400(ImageGalleryView.java:57)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView$ImageListAdapter.lambda$onBindViewHolder$2(ImageGalleryView.java:228)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageGalleryView$ImageListAdapter.lambda$onBindViewHolder$2$ImageGalleryView$ImageListAdapter(Unknown Source:0)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at cgeo.geocaching.ui.-$$Lambda$ImageGalleryView$ImageListAdapter$Yife03cz0JabAMBc4AV2XAcmUQw.onClick(Unknown Source:4)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at android.view.View.performClick(View.java:7192)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7166)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at android.view.View.access$3500(View.java:824)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27592)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:888)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-20 10:09:18.167 11877 11877 E AndroidRuntime: 	at 
```

### Expected result after these steps?

- cgeo should not crash
- optional: the image on the details page should open inside cgeo instead of the browser 

### Reproducible

Yes

### c:geo Version

2022.05.20-NB

### PR DESCRIPTION
**Pull request by fm-sys**
Fix #13030

- Fix NPE in trackable image gallery
- Use ImageViewActivity for enlarging trackable avatar

### CODE REVIEW

**Comment by eddiemuc** [comment]
Code lgtm. But please put the NPE fix on release

**Comment by fm-sys** [comment]
Can both commits be targeted to release, or should I split the PR up?

**Comment by eddiemuc** [comment]
> Can both commits be targeted to release, or should I split the PR up?

If you want to include both, then please add the feature toggle such that the new image view is only opened if the toggle is "on".

**Comment by eddiemuc** [comment]
> > Can both commits be targeted to release, or should I split the PR up?
> 
> If you want to include both, then please add the feature toggle such that the new image view is only opened if the toggle is "on".

Use `Settings.enableFeatureNewImageGallery()`

**Comment by fm-sys** [comment]
Done

**Pull request merged**
