### PR TITLE
Indicate waypoint has calculated coordinates in waypoint list (rel #9899, #6833)

### PR DESCRIPTION
**Pull request by murggel**
## Description

Show text "Calculate coordinates" in the waypoint list for the coordinates of a waypoint, if it has calculated coordinates.
CalcState is only saved, if it has equations / variables. 
grafik

In the CoordinatesInputDialog the button "Calculate" has italic font, if already a formula is given (I can change this to bold / colored, ... ).
grafik

## Related issues

#6833 , #9899 

## Additional context

Because there is no way to delete the calcState of the waypoint, I added the logic, that a calcState is only set, if it has equations.
Probably it should be extended to "delete the calcState, if the coordinates get cleared by user". But I an not sure about this, so this could be an extra PR.

I am working on showing a icon in addition (like the "tick" for "visited" waypoints), but I am not yet satisfied with the look and feel of that icon, I am not sure, if it is visible enough on small screens (see https://github.com/cgeo/cgeo/issues/9899#issuecomment-782926595)

### CODE REVIEW

**Comment by Narrat** [comment]
I may miss something, but if the waypoint has calculated coordinates shouldn't the displayed text also be `Calculated coordinates`? `Calculate coordinates` sounds more like something that should be done. Or does tapping on the text bring up the calculator?

**Comment by murggel** [comment]
> I may miss something, but if the waypoint has calculated coordinates shouldn't the displayed text also be `Calculated coordinates`? `Calculate coordinates` sounds more like something that should be done.

My thoughts as well, for the first implementation I just used the same text as on the button in the dialog, but sure, it can be changed...

> Or does tapping on the text bring up the calculator?

Good idea, will check that, if I can implement that...

**Comment by moving-bits** [comment]
Thanks @murggel for diving into this issue. It's good to have a visual indicator for having a formula-supported waypoint.

> Show text "Calculate coordinates" in the waypoint list for the coordinates of a waypoint, if it has calculated coordinates.

This does not work for me if the coordinates are calculated and all variables are defined (so the calculated coordinates are fully determined). IMHO it should display the hint also in this situation.

> In the CoordinatesInputDialog the button "Calculate" has italic font, if already a formula is given (I can change this to bold / colored, ... ).

I like it the way it is - it gives you a good visual hint without being too obstrusive, so I would stay with italic font. You could even use "Calculated coordinates" here as well, would still fit and be consistent with the hint in the waypoint list.

**Review by moving-bits — APPROVED** [review]
Thanks @murggel for tackling this issue, and thanks for the last adaptions. LGTM

**Pull request merged**
