### PR TITLE
Add new types, sizes and waypoints to SU

### PR DESCRIPTION
**Pull request by okainov**
I did the coding almost "blindly" without real testing but with help of tests it seems fine.

It would be cool if I can get build APK so I can test it by myself.

Parser test fails for me on "store" stage because there is no DB. I can either delete it or mock the db if you have any clue how.

**Content**

We introduced several new things on .SU:
- Two new cache types for "mystery" caches
- Size indicator
- Waypoints
So I tried to add it to c:geo.

### CODE REVIEW

**Comment by rsudev** [comment]
test this please

**Comment by rsudev** [comment]
retest this please

**Comment by rsudev** [comment]
I'd assume the failed test is not due to this change, but due to some instability on the geocoder side.
Is the debug apk produced by the PR-builder sufficient for your testing needs?

**Comment by okainov** [comment]
Amazing! It really works! Fine from my side!

**Comment by okainov** [comment]
test this please

**Comment by Lineflyer** [comment]
test this please

Only works for core team members

**Comment by okainov** [comment]
Can it be merged or is there anything I can improve?

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
The CI wont pass, but this is due to an unrelated AndroidGeocoder problem as already stated by @rsudev .
I cannot judge the code itself, but do not see any problem in enhancing the geocaching.su functionality as described. @rsudev or other assigned reviewers, please kindly check if this can be merged.

**Comment by okainov** [comment]
@Lineflyer when can I expect this to appear in Release branch? Should it be separated PR? 2+months passed with 2 c:geo releases already, but it still seems to be not in the official version....

**Comment by rsudev** [comment]
The past releases were all only bug-fix ones directly from the release branch, therefore this change is not out yet. Perhaps is currently a good point in time to collect the latest master changes into a smaller feature release, before the targetSdk change is due.
@Lineflyer what do you think?

**Pull request merged**
