### PR TITLE
fix #10621: enable Proxy WebAPI v2 and gc.com attribute search

### LINKED ISSUE #10621: Gc.com search for attributes not implementable: WebApi proxy v2: cgeo explicitely not authorized?
I found something fishy today when I tried to integrate V2 of gc.coms Web proxy Api.

The following things were all done while logged in as a premium member.

The following Uri is an example for a search of traditional caches (ct=2) with the V2 Proxy WebApi:
https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo 

When I issue it exactly like this I get an "unauthorized" message:
`{"statusCode":401,"statusMessage":"Unauthorized","errorMessage":"","uri":"http://websearch.groundspeak.biz/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo"}`

When I issue the SAME request with V1, it works:
https://www.geocaching.com/api/proxy/web/search?ct=2&take=500&skip=0&sort=distance&asc=true&app=cgeo 

And now the mean part: when I issue the same request (for V2) with an `app`-parameter-value **other** than `cgeo` or without the `app` parameter, it works too! E.g.:
https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true&app=tumdedum
https://www.geocaching.com/api/proxy/web/search/v2?ct=2&take=500&skip=0&sort=distance&asc=true

Are they really explicitely blocking c:geo from using the V2 Proxy WebApi???

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #10621: enable Proxy WebAPI v2 and gc.com attribute search

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR, if merged, will enable usage of gc.com Proxy WebAPI v2 instead of the currently used v1 (=non-versioned).

As a positive side effect it will now allow c:geo to do online searches for attributes on gc.com

**Comment by Lineflyer** [comment]
Just thinking:
Does it make sense to merge `master` into `release` before merging this PR to `master`.

As both the market release and the nightlies are IMHO both performing good, we could cut an `release` including the variables (with beta phase) and have more time to test v2 API on `master` (and also we do not yet have an official reply, that it will keep working..still waiting for it).

**Comment by eddiemuc** [comment]
If V2 is not working, we can switch back to V1 just by deleting three chars in code (the part `/v2` of the url)

**Comment by Lineflyer** [comment]
> If V2 is not working, we can switch back to V1 just by deleting three chars in code (the part `/v2` of the url)

Saw that. But i thought a bit of stability and function check would be nice.
Who knows if it behaves the same as v1 in all details after all.

**Comment by Lineflyer** [comment]
We received confirmation by Groundspeak, that the problem is fixed.

**Pull request merged**
