### PR TITLE
Merge branch release

### PR DESCRIPTION
**Pull request by Lineflyer**

### CODE REVIEW

**Comment by samueltardieu** [comment]
Please do not merge `release` into `master` through a pull request, as we do not want to do any commit manipulation in this case (we need to see the right history). We have disabled the merge commit method in GitHub.

Closing to ensure this is not merged.

**Comment by SammysHP** [comment]
Actually this was suggested by @Bananeweizen.

**Comment by samueltardieu** [comment]
This is an horrible idea nevertheless :-)

**Comment by Lineflyer** [comment]
Good to know! Thanks @samueltardieu

**Pull request closed without merging**
