### PR TITLE
fix #5490: fix selection for LinkMovement enabled TextView

### LINKED ISSUE #5490: Scrolling broken after selection
Select some text of the description. Close selection mode. Try to scroll the view up and down. It jumps around.

### PR DESCRIPTION
**Pull request by rahu**
same fix, now based on release branch. Also removed the no longer needed workaround.

### CODE REVIEW

**Comment by rahu** [comment]
I modified the code and added @kumy 's findings.

**Comment by Bananeweizen** [comment]
I believe that removing the old fix in IndexOutOfBoundsAvoidingTextView isn't right, since it covers another unrelated issue: https://code.google.com/p/android/issues/detail?id=35466

**Comment by rahu** [comment]
I don't see the overloaded `onSelectionChanged` workaround in this issue?

Am 6. März 2016 08:23:34 MEZ, schrieb Michael Keppler <notifications@github.com>:
>I believe that removing the old fix in IndexOutOfBoundsAvoidingTextView
>isn't right, since it covers another unrelated issue:
>https://code.google.com/p/android/issues/detail?id=35466
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/pull/5506#issuecomment-192820079

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Bananeweizen** [comment]
Me neither. I'm just saying that the class itself has that issue in its Javadoc comment as the reason why it was introduced. I cannot really judge, if that issue will or will not occur if that method is removed. Since your PR targets the release branch, I suggest a kind of in-the-middle solution: On the release branch I would leave the onSelectionChanged method in there (and only apply your remaining change) and on the master branch we could remove it, allowing for some more testing. Does that sound reasonable?

However, I have no strong opinion here. If you or other developers are confident that the method can be deleted, then I'll accept that.

**Comment by kumy** [comment]
@Bananeweizen solution seems reasonable for me.

**Comment by rahu** [comment]
for me too, I updated the PR.

**Pull request merged**
