### PR TITLE
Update compileSdk to match targetSdk

### PR DESCRIPTION
**Pull request by UniQP**

### CODE REVIEW

**Comment by mucek4** [comment]
I have accepted all licenses on Master node, but all executors probably need new Docker image. I have manually connected to executor 4 and 5 and accepted licenses. Will test if works. But executors have no permanent storage. Until they are up it will work.

**Comment by mucek4** [comment]
retest this please

**Comment by mucek4** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
error on
~~~
1) testSearchFromMap(cgeo.geocaching.connector.gc.GCBaseTest)
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7f6639ddb100: I/O error during system call, Connection reset by peer
at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
~~~
Please try upgrading RxJava to
    implementation "io.reactivex.rxjava2:rxjava:2.2.12"

**Comment by UniQP** [comment]
> Please try upgrading RxJava to
> implementation "io.reactivex.rxjava2:rxjava:2.2.12"

We already use this version.

**Comment by bekuno** [comment]
> 
> 
> > Please try upgrading RxJava to
> > implementation "io.reactivex.rxjava2:rxjava:2.2.12"
> 
> We already use this version.
Oh yes, my master was not uptodate.

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
There are fixes for OkHttp:
    implementation 'com.squareup.okhttp3:okhttp:3.12.5'

see
  https://square.github.io/okhttp/changelog_3x/#version-3125

Maybe this helps?

**Comment by bekuno** [comment]
retest this please

**Comment by moving-bits** [comment]
ok, let's try this out

**Pull request merged**
