### PR TITLE
rel to #10952: add things to status filter, add stored since filter

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #10952: add things to status filter, add stored since filter

Status filter can now filter for "has trackables", "has own vote" and "has offline log":

image

New filter "stored since" allows for filtering of storage date/timestamp:

image

### CODE REVIEW

**Comment by moving-bits** [comment]
clean look & very useful, thanks!

**Comment by moving-bits** [comment]
One additional question: Does "favored" mean "I have given a favorite point to this cache"? The we should probably extend the text to something like "own favorite" to distinguish it from "has favorite points" (from whoever)

**Comment by eddiemuc** [comment]
> One additional question: Does "favored" mean "I have given a favorite point to this cache"? The we should probably extend the text to something like "own favorite" to distinguish it from "has favorite points" (from whoever)

Done

**Comment by moving-bits** [comment]
> Done

Thanks

**Comment by murggel** [comment]
I like those emojis in the status filter.
So shouldn't the first three (found, own, stored) also use a colored emoji?
For "found" and "own" the emoji from map...

**Comment by eddiemuc** [comment]
> I like those emojis in the status filter.
> So shouldn't the first three (found, own, stored) also use a colored emoji?
> For "found" and "own" the emoji from map...

Technically this is really easy to achieve of course. 

Right now those are the same icons which are used in the map quick settings. If it is ok to have different setting here then it should not be a problem.

**Pull request merged**
