### PR TITLE
Remove Thunderforest API key and provide user setting

### PR DESCRIPTION
**Pull request by pstorch**
Thunderforest API key for OSM Cyclemap is not provided by c:geo anymore, but supports it via a user setting.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Will this automatically switch an existing user with Thunderforest active to another map? I've seen that a check is done in the settings activity to avoid empty keys with your change, but I'm thinking of a user who just upgrades and never opens settings. Or does the current code in the mapsforge provider already fall back to the default source then?

**Comment by pstorch** [comment]
To be honest, I have not tested this case. I have tested the SettingsActivity forth and back. It drove me crazy 😂. Till it updated the list of MapSources correctly. There I tested that if the Cyclemap is chosen and you remove the api key, the list above is reduced and the default is selected. 
I have to test the migration case explicitly. I think it will fall back to the default, but I'm not sure.

**Comment by pstorch** [comment]
Ok, tested migration successfully. If the Cyclemap was the chosen map source before, c:geo falls back to the default (Mapnik) after this change.

**Comment by Lineflyer** [comment]
Let me set "Do not merge" in order to first discuss the further proceeding in #6610

**Comment by pstorch** [comment]
I'll close here, due to better ideas came up in https://github.com/cgeo/cgeo/issues/6610#issuecomment-315747226

**Pull request closed without merging**
