### PR TITLE
add "Plain (single line)" format to coordinates input dialog

### PR DESCRIPTION
**Pull request by moving-bits**
Depending on the data I have I frequently wished to have a single line input field in the coordinates input dialog. (eg: https://coord.info/GC8FG9B has coordinates in plain format in the listing)

So here we are:

image

image

For now it's the input dialog only, not yet the coordinates calculator (format is deactivated there). Need to figure out how to reliably detect the longitude hemisphere letter in the different formats first...

### CODE REVIEW

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4747680&bid=15841088)

**Comment by Lineflyer** [comment]
Why would you like to have a single line?I could not imagine a use case for this.If coords are in the clipboard I can use our paste feature instead. If I dont have something in the clipboard I dont care the lines to enter.Von meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: moving-bits <notifications@github.com> Datum: 30.12.19  19:47  (GMT+01:00) An: cgeo/cgeo <cgeo@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [cgeo/cgeo] add "Plain (single line)" format to coordinates input
  dialog (#8039) Depending on the data I have I frequently wished to have a single line input field in the coordinates input dialog. So here we are:


For now it's the input dialog only, not yet the coordinates calculator (format is deactivated there). Need to figure out how to reliably detect the longitude hemisphere letter in the different formats first...



You can view, comment on, or merge this pull request online at:
  https://github.com/cgeo/cgeo/pull/8039

Commit Summary

  add plain_singleline format to coordinate input dialog
  add workaround for Coordinates Calculator not supporting single line plain format yet


File Changes

  
    M
    main/res/values/strings.xml
    (2)
  
  
    M
    main/res/values/strings_not_translatable.xml
    (2)
  
  
    M
    main/src/cgeo/geocaching/settings/Settings.java
    (1)
  
  
    M
    main/src/cgeo/geocaching/ui/dialog/CoordinatesCalculateDialog.java
    (32)
  
  
    M
    main/src/cgeo/geocaching/ui/dialog/CoordinatesInputDialog.java
    (14)
  


Patch Links:

  https://github.com/cgeo/cgeo/pull/8039.patch
  https://github.com/cgeo/cgeo/pull/8039.diff


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cgeo/cgeo/pull/8039?email_source=notifications\u0026email_token=AAHH3JJSJZPF5L7K2I5OEBLQ3I65TA5CNFSM4KBPFIN2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IDMNELA",
"url": "https://github.com/cgeo/cgeo/pull/8039?email_source=notifications\u0026email_token=AAHH3JJSJZPF5L7K2I5OEBLQ3I65TA5CNFSM4KBPFIN2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IDMNELA",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by moving-bits** [comment]
> Why would you like to have a single line? I could not imagine a use case for this.If coords are in the clipboard I can use our paste feature instead. If I dont have something in the clipboard I dont care the lines to enter.

An example use case is the cache mentioned above (coord.info/GC8FG9B): The coords are hidden in the listing, barely covered by white font, and c:geo displays them directly. So I highlight the coords, create a new waypoint and paste the coords.

Currently I do
- either have to copy in two steps, switching back and forth between listing and waypoint editor,
- or have to paste it twice, each time having to manually delete the part not necessary for the current input field.
Both is cumbersome, especially on a small handheld device.

With this PR I can simply copy & paste in one step.

**Comment by moving-bits** [comment]
retest this please

**Comment by Lineflyer** [comment]
> An example use case is the cache mentioned above (coord.info/GC8FG9B): The coords are hidden in the listing, barely covered by white font, and c:geo displays them directly. So I highlight the coords, create a new waypoint and paste the coords.

For me with this cache it is:
- Select whole coords in listing text
- Copy into clipboard
- Create new waypoint in c:geo
- Select "Paste from Clipboard"

Done. :)

**Comment by Narrat** [comment]
Not sure how the implementation of this PR adjusts to more lazily written coords, but I remember cases where coords copied to the clipboard where not recognized when creating a new waypoint (aka no button "Paste from clipboard")

**Comment by Lineflyer** [comment]
> Not sure how the implementation of this PR adjusts to more lazily written coords, but I remember cases where coords copied to the clipboard where not recognized when creating a new waypoint (aka no button "Paste from clipboard")

If you have such a case please kindly report it.
IMHO it is more wise to improve the intelligence of the paste feature instead of adding new features like this one. 

I am however against a new coord input format, just to have it in one line without any other benefit.

**Comment by Narrat** [comment]
> If you have such a case please kindly report it.

Will do if I remember a specific cache. Or test some of the cases I seem to recall.
> IMHO it is more wise to improve the intelligence of the paste feature instead of adding new features like this one.
> 
> I am however against a new coord input format, just to have it in one line without any other benefit.

Oh, sure. Perfectly fine if the existing one can be extended to cover all cases.

**Comment by moving-bits** [comment]
@Lineflyer 

> Select "Paste from Clipboard"

_\*blush\*_
Never seen this button before... But: It works! (At least for the use case that was the original reason to implement this.) This solves the original use case for me, so I'll close this PR.

@Narrat
If there's a separate problem with clipboard contents not being recognized, please open a separate issue for it, describing how to reproduce the problem (if possible).

**Comment by Lineflyer** [comment]
@moving-bits 
BTW: This is a good example of why it might be wise to open an issue first before going for the coding- as recently discussed on the mailing list. Maybe this sometimes saves time or directs a coding approach in the right direction before starting.

**Pull request closed without merging**
