### PR TITLE
Fix #6606: Use weighted arithmetic mean to sort GCVote ratings

### LINKED ISSUE #6606: Improve sort by rating
Follow-up of #6601:

A cache with one 5-star rating will be ranked higher than a cache with 20 4.5-star ratings. While this commit solves a specific problem, it is not the solution for a correct rating. We get average rating and number of votes, this should be enough to sort caches in a better way.

http://www.evanmiller.org/how-not-to-sort-by-average-rating.html
https://stackoverflow.com/questions/1411199/what-is-a-better-way-to-sort-by-a-5-star-rating

### PR DESCRIPTION
**Pull request by UniQP**
Intended as a basis for discussion.

Not tested yet.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
2.5 is not the average (and that was already wrong before). It should be 3, since that is the average between 1 and 5, which are the limits of the rating (and even the website uses "average" as textual value for 3).

In fact, I would even more like it to have a random sample of 10000 caches and their votes to calculate on actual in the field average rating, but I'm to lazy. :)

**Comment by UniQP** [comment]
It was 3.3995 for GC50*** (6782 caches with votes) → I changed it to 3.4.

**Comment by Bananeweizen** [comment]
:+1: I'm fine with merging.

**Comment by UniQP** [comment]
I finally got my emulator working again to test the PR. Seems to work as intended: 4.3 (16 votes) > 5.0 (2 votes) > 4.1 (9 votes).

**Comment by pstorch** [comment]
I don't really use GCVote and I haven't thought much about 5-star-rating-sorting, but I just verified this PR.

With this change the sorting of my homezone PQ was as follows:

1. 5.0 with 4 votes

1. 4.0 with 9 votes

1. 4.8 with 2 votes

1. 4.2 with 3 votes

1. 5.0 with 1 vote

1. 4.0 with 3 votes

1. 3.8 with 5 votes

1. 4.5 with 1 vote

1. 4.0 with 2 votes

1. 3.8 with 3 votes


Looks reasonable to me.

**Pull request merged**
