### PR TITLE
refactor http request response interface

### PR DESCRIPTION
**Pull request by eddiemuc**
refactor http request response interface

### CODE REVIEW

**Comment by eddiemuc** [comment]
This is an attempt to refactor the cgeo-internal interface to issue Http requests

**Comment by eddiemuc** [comment]
To be able to write unit tests for this, I added lib `com.squareup.okhttp3:mockwebserver` to test dependencies, hope this is ok

**Comment by fm-sys** [comment]
As long as it doesn't blow up the APK size (-> added as `testImplementation`) it's totally fine IMHO...

**Comment by eddiemuc** [comment]
Replaced the log image upload routine with new `HttpRequest` / `HttpResponse` class in this PR to show how it works and prove its stability in one area first

**Pull request merged**
