### PR TITLE
rel to #13793: support display of geojson for mapsforge

### LINKED ISSUE #13793: Support Display of GeoJson data
Sometimes I have caches where it would be helpful to draw geometric forms on the map (lines, polygons, circles). An example for such a cache is the Heinzel Challenge around Munich (https://coord.info/GC2YYGC)

My proposal for this is to support the import and display of geojson files. 
* GeoJson is described here: https://geojson.org/
* An online GeoJson editor can be found e.g. here: https://geojson.io 
* I would also include support for basic formatting e.g. color, line width

I am not sure, but probably mapsforge and/or VTM already support GeoJson anyway?

GUI-wise I propose something like the integration of individual route files, although there should be the possibility to import multiple GeoJson files and turn their display on and off.

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #13793: support display of geojson for mapsforge

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR as of now already enables geojson support: it simply displays all geojson files (identified by suffix `json`) which are stored in gpx folder. Only on mapsforge for now, not Google. Implementation was easy.

Integrating this into track file Dialog seems to be the hard part.

**Comment by moving-bits** [comment]
Importing routes / tracks is done in `files/GPXTrackOrRouteImportet.java`, calling several different parsers. You could do the distinction depending on file suffix here and call a parser of your choice.

If GeoJSON objects are polygons only, you could even store it as a track/route (with multiple segments, if needed). But I guess there are other object types as well, e. g. circles etc.
But maybe the route object could be extended to not only contain arrays of points, but other objects as well. Maybe even base it on segments (objects) of GeoJSON objects?

**Comment by eddiemuc** [comment]
> But maybe the route object could be extended to not only contain arrays of points, but other objects as well. 

Yes, I am trying to think about a good abstraction for this.

@moving-bits one question: I noticed that the custom mapsforge layer which renders the routes uses a cache inside where already calculated `Path` objects are reused. So e.g. Mercator transformations have to be calculated less often I assume. Instead a mapsforge `Polyline` layer could be used directly, but this one doesn't do an caching. Is this caching crucial e.g. due performance reasons?

**Comment by moving-bits** [comment]
Performance may be one reason, but IIRC there was a problem with `Polyline` that it connects all segments to form a single line.
We allow to load track files containing several segments, and we want to display them as unconnected items. Manual calculation allowed me to differentiate between `moveTo()` and `lineTo()`, see `AbstractRouteLayer.translateRouteToPath()`).

(Similar applies to `UnifiedMap`: I had to use a `VectorLayer` for displaying tracks instead of a `PathLayer` for the very same reason. BTW: No extra caching applied here - but VTM is vector based anyway, not bitmap based.)

**Comment by eddiemuc** [comment]
> > there was a problem with Polyline that it connects all segments to form a single line
> > I had to use a VectorLayer for displaying tracks instead of a PathLayer for the very same reason
> 
> 1 line overlay is expected to render 1 line.
> Can use many line overlays (Polyline, PathLayer) to render multiple lines (i.e. trkseg).
> 
> Or we could extend the current Mapsforge + VTM line layers.
> Pull requests are always welcome! :slightly_smiling_face: 

Mapsforge already has the `GroupLayer` for this. (I assume there is something similar in VTM?). I think this is enough to handle this use case.

**Comment by devemux86** [comment]
> Mapsforge already has the GroupLayer for this. (I assume there is something similar in VTM?).

There is also in VTM, however I have never needed it.
(it is just a List)

It is easier to maintain lists of layers inside the app,
as each app has specific needs.

**Comment by moving-bits** [comment]
From implementing track display in VTM I remember the following problem with the "one layer per segment" approach:
- I do not know the number of segments beforehand, it's a variable number of elements (and thus, layers, with this approach).
- The order of layers implicitly determines the z-order for display.
- `layers.set()` accepts an index number at which to set a layer, but the layer indices must not have "wholes" in it (so I cannot create a "large enough" gap to fill later with the layers required for my variable elements) - also a "large enough gap" approach is pretty risky, you never know which user data will be entered...

This means, that either the layers with the variable elements have to be at the top of the stack (making it most-prominent visually), or I have to remove and rebuild the layer stack on inserting an element potentially requiring multiple layers.

For those reasons I decided to put all tracks with all segments onto the same layer (which is pre-created layer on map startup at the index position for the required z-order), and make sure that I use a layer type which allows me to display unconnected polylines.

**Comment by eddiemuc** [comment]
> This means, that either the layers with the variable elements have to be at the top of the stack (making it most-prominent visually)...

I don't understand. Isn't every segment of the route a "variable" element? And why is the z-order important in which they are displayed?

**Comment by devemux86** [comment]
For an alternative way, see https://github.com/mapsforge/vtm/pull/101 and https://github.com/mapsforge/mapsforge/issues/1116.

- Layers.addGroup(group)
- Layers.addLayer(Layer, group)

**Comment by moving-bits** [comment]
> > This means, that either the layers with the variable elements have to be at the top of the stack (making it most-prominent visually)...
> 
> I don't understand. Isn't every segment of the route a "variable" element? 

We have a variable number of tracks, and while most tracks contain only a single path, eeach track can contain a variable number of unconnected segments.
(A similar problem arises with c:geo's history line, which is only one line, but can contain unconnected segments as well.)

> And why is the z-order important in which they are displayed?

Top-most elements may hide elements on layers with lower z-index, so we decided to put caches top-most, waypoints somewhere below etc.

**Comment by eddiemuc** [comment]
> > And why is the z-order important in which they are displayed?

> Top-most elements may hide elements on layers with lower z-index, so we decided to put caches top-most, waypoints somewhere below etc.

This should be solvable by putting elements with different z-priority in different Group Layers. Those would be permanent with a fixed z-order  but inside a group layer (where everything has same z-prio) one would be able to add/delete stuff w/o worrying about z-order. At least that's my understanding as of now. Am I missing something?

**Comment by moving-bits** [comment]
> > > And why is the z-order important in which they are displayed?
> 
> > Top-most elements may hide elements on layers with lower z-index, so we decided to put caches top-most, waypoints somewhere below etc.
> 
> This should be solvable by putting elements with different z-priority in different Group Layers.

Ah, didn't know that. Thanks for the pointer, will dive into it...

**Comment by eddiemuc** [comment]
> Ah, didn't know that. Thanks for the pointer, will dive into it...

Would.it be ok for you to wait on this? This would for sure clash with my ongoing geojson implementation. I can take a look at the z-order-thing too while I am at it.

(My idea is to treat both geojson and routes/tracks in the same "geo object" layer)

**Comment by moving-bits** [comment]
> > Ah, didn't know that. Thanks for the pointer, will dive into it...
> 
> Would.it be ok for you to wait on this?

Sure, no problem. 

Z-order is fine currently, but I'm looking into https://github.com/mapsforge/vtm/discussions/998, and maybe using `GroupLayer` in combination with `PathLayer` instead of `VectorLayer` may help to solve that issue.

**Comment by devemux86** [comment]
My suggestion would be to check the more powerful layer groups: https://github.com/cgeo/cgeo/pull/13806#issuecomment-1371298335

---

`GroupLayer` is just a `List`, can do a better implementation with your own layer lists.

**Comment by moving-bits** [comment]
> My suggestion would be to check the more powerful layer groups: [#13806 (comment)](https://github.com/cgeo/cgeo/pull/13806#issuecomment-1371298335)
> 
> `GroupLayer` is just a `List`, can do a better implementation with your own layer lists.

Did a very short test for tracks using layer groups, and was no longer able to reproduce the issue described in https://github.com/mapsforge/vtm/discussions/998.

Will now wait for this PR being finalized before restructuring `UnifiedMap` to use layer groups for VTM.

**Comment by eddiemuc** [comment]
> Will now wait for this PR being finalized before restructuring UnifiedMap to use layer groups for VTM.

If you're just modifying Unified map then go ahead (don't wait for this PR).

**Comment by devemux86** [comment]
> layer groups for VTM

Note: the layer groups are also available in Mapsforge.

**Comment by moving-bits** [comment]
> > Will now wait for this PR being finalized before restructuring UnifiedMap to use layer groups for VTM.
> 
> If you're just modifying Unified map then go ahead (don't wait for this PR).

done with #13833

**Comment by eddiemuc** [comment]
This PR, if merged, will enable display of GeoJSON objects for Mapsforge maps only! (Google and UnifiedMap are not yet supported). Under the hood it already abstracts out geoobject-list and route/track into the base interface called IGeoDataProvider

**Pull request merged**
