### PR TITLE
Use try-with-resources statements.

### PR DESCRIPTION
**Pull request by UniQP**
The feature is supported since Java SE 7.

### CODE REVIEW

**Comment by samueltardieu** [comment]
I think the older versions we support only have Java 6. It needs checking.

**Comment by Bananeweizen** [comment]
http://developer.android.com/tools/sdk/eclipse-adt.html

> Added support for Java 7 language features like multi-catch, try-with-resources, and the diamond operator. These features require version 19 or higher of the Build Tools. Try-with-resources requires minSdkVersion 19; the rest of the new language features require minSdkVersion 8 or higher.

Shouldn't be a problem therefore.

**Comment by samueltardieu** [comment]
Well, given that we build cgeo with `minSdkVersion 9`, that certainly would be a problem.

**Comment by UniQP** [comment]
The code base already uses the diamond operator as one of Java 7 features:
git grep "<>()" | wc -l
201

**Comment by samueltardieu** [comment]
The diamond operator is a compiler feature. It does not generate any new opcode and thus runs on JVM 6. Same goes with multi exceptions catch. However, try with resources require a new opcode in the JVM AFAIK, as do lambdas in Java 8 for example.

**Comment by SammysHP** [comment]
> Try-with-resources requires **minSdkVersion 19**; the rest of the new language features require minSdkVersion 8

**Comment by Bananeweizen** [comment]
Okay, I misread my own quoted text, since I totally focused on the build tools version. :/

@UniQP Android was created by implementing the Java 6 API from scratch. Therefore you can write Java 6 code, and the compiler will get this working. However, you cannot use any specific language feature or API method of newer Java versions, unless the Android tooling guys explicitly support that. While you are using the Java language, you are not programming against a Java runtime.

**Pull request closed without merging**
