### PR TITLE
Google Maps themes support

### PR DESCRIPTION
**Pull request by ztNFny**
implement theme support for Google maps with json themes
#12456 

- [x] general implemenation
- [x] final decision about themes to include
- [x] System mode theme switch (day/night)

image
image
image
image

### CODE REVIEW

**Comment by ztNFny** [comment]
feedback on the implementation in GoogleMapView.java would be welcome.
I don't really like the static stuff, but as I have to call it from https://github.com/cgeo/cgeo/pull/12705/files#diff-a25a47bd36a33f4384c48602f15a543f9e344ab38781eb71485c8102a4330c60R828 I didn't find any good way without it.
Suggestions welcome! @eddiemuc @fm-sys

**Comment by eddiemuc** [comment]
> feedback on the implementation in GoogleMapView.java would be welcome. I don't really like the static stuff, but as I have to call it from https://github.com/cgeo/cgeo/pull/12705/files#diff-a25a47bd36a33f4384c48602f15a543f9e344ab38781eb71485c8102a4330c60R828 I didn't find any good way without it. Suggestions welcome! @eddiemuc @fm-sys

Hi @ztNFny the link does not really work for me (at least it does not lead me to a specific line), but I assume you mean that you need to call the selectMapTheme method of class GoogleMapView from CgeoMap -> correct?

In that case, you can do the following to prevent the usage of static var:
* create the method "selectMapTheme" also in class `MapViewImpl`, make is abstract or leave it empty there. Make that method non-static of course. `GoogleMapView` extends class `MapViewImpl`, so it will implement this method then (if you make it non-static again).
* `CGeoMap` extends class `AbstractMap` which has access to the used `MapViewImpl` instance (stored in member `mapView`. So in `CGeoMap` you can then call the method using `this.mapView.selectMapTheme()`.

If you think that this class structure is unnecessarily complex I would definitely agree. I think this has historic reasons. One of these days we might want to clean this up.

**Comment by ztNFny** [comment]
> In that case, you can do the following to prevent the usage of static var:

Thanks, that's exactly the advise I was looking for!

**Comment by ztNFny** [comment]
non-static method and dynamic theme switching based on device theme added :-)

This should be ready to go code-wise. The themes to include I'd like to discuss during our next team meeting, leaving it in WIP until then.

@Lineflyer one item for sundays agenda :-)

**Pull request merged**
