### PR TITLE
alc optimizations (3rd edition)

### PR DESCRIPTION
**Pull request by baiti**
now based on a completely recreated release branch from master and synced to origin.

@Lineflyer ... you can now decide which one to merge. The other one can be closed then.

### CODE REVIEW

**Comment by Lineflyer** [comment]
No problem to have it in `release`.

**Comment by baiti** [comment]
As a next iteration, I am scanning the code for how to disable the "Images" Screen on CacheDetailActivity (for ALCs).  What would be an elegant way to turn that view off without writing too much if ... then ... else logic checking for cacheType or something similar. Any pointers where to look and for what to look would be appreciated.

**Comment by Lineflyer** [comment]
Why turning it off?

**Comment by baiti** [comment]
> Why turning it off?

Becasue all it shows is the image that can already be seen on the "Description" Page. It is completely redundant.

**Comment by Lineflyer** [comment]
No, its not 100% redundant:
1. You can use this page to open the image in an external app if you e.g. want a closer look on it
2. It could (potentially) also be used for stage images if this might come as well

**Comment by baiti** [comment]
> No, its not 100% redundant:
> 
> 1. You can use this page to open the image in an external app if you e.g. want a closer look on it
> 2. It could (potentially) also be used for stage images if this might come as well

Ah ok I wasn't aware of this. So we leave everything just the way it is. Thx for pointing it out.

**Pull request merged**
