### PR TITLE
fix #5975 remember last list selection

### LINKED ISSUE #5975: Remember last list selection
Sometimes I store caches one by one from the live map. Every time I have to select the same list(s) again and again.

Previously we had the "ask for list" option, now I suggest to add an option to remember the last list selection for storing a cache.

This is somehow related to the requested long-press in #5839 as it removes the additional work for selecting a list.

### PR DESCRIPTION
**Pull request by pstorch**
Remembering the selected lists for the multi list selection dialog. I've decided to remember the selection in the Settings, similar to last used list.

### CODE REVIEW

**Comment by pstorch** [comment]
retest this please

**Comment by samueltardieu** [comment]
I cannot test it right now so I'll ask: does it cover the case where a list belonging to the saved selected lists has been deleted? This can also happen if a preferences file is restored during a reinstallation.

**Comment by pstorch** [comment]
@samueltardieu oh, good point. I'll check.

**Comment by pstorch** [comment]
@samueltardieu now deleted lists are handled

**Pull request merged**
