### PR TITLE
add textual info for routingmode in map quick settings popup

### PR DESCRIPTION
**Pull request by moving-bits**
image

### CODE REVIEW

**Comment by fm-sys** [comment]
Is it really necessary? IMHO it's a bit confusing that the info uses the same style ad the headings...

**Comment by moving-bits** [comment]
> Is it really necessary? IMHO it's a bit confusing that the info uses the same style ad the headings...

IMHO it's useful for those that do not understand the meaning of the buttons (especially "off" and "straight"), and by placing it in the "heading" it does not take up any additional space.

Maybe use "Routing (Straight)" or "Routing (Current: Straight)" instead of "Routing: Straight"?

**Comment by fm-sys** [comment]
> Maybe use "Routing (Straight)" or "Routing (Current: Straight)" instead of "Routing: Straight"?

Jep, that would probably be better. Also we should IMHO (independent of this PR) try to find a better icon for "OFF"

baseline_near_me_disabled_black_18dpbaseline_link_off_black_18dpbaseline_explore_off_black_18dp

What about one of those? All three are material design icons...

**Comment by moving-bits** [comment]
Adapted the headline accordingly in this PR and prepared #9971 for the new button.

**Comment by bekuno** [comment]
A bit off topic - the spacing before the headlines is different. Before `use compact icons` we have nearly a line hight space, bot nothing before `Routing` and `Individual route`.
I would suggest to have a small space before every headline.

**Pull request merged**
