### PR TITLE
fix dark icons on dark toolbar (fix #11006)

### LINKED ISSUE #11006: Personal note dialog action items not visible in light theme
## Bug description 
The icons for "confirm" or "abort" in the new "edit personal note full-screen dialog" are not visible (or nearly so) in light theme:

image

### Reproduce 
- set c:geo to light theme
- open a cache listing
- choose "edit personal note" from menu

### Actual result after these steps 
Action buttons are displayed in black on dark grey

### Expected result after these steps 
Action buttons should be displayed in white on dark grey

## c:geo version 
current master

## Reproducible 
yes

### PR DESCRIPTION
**Pull request by murggel**
## Description

use new toolbar-style for androidx-toolbar to set color correctly

## Related issues

fix #11006

### CODE REVIEW

**Review by fm-sys — APPROVED** [review]
A quick test in the emulator was fine. Thanks @murggel for finding this solution 👍

**Comment by murggel** [comment]
Hm,  I did not check the other occurrences of the compass.
Will check that after the soccer-match 🤣⚽️

**Comment by fm-sys** [comment]
Oh, yes. You are right. With this PR, the touch feedback effect is missing again in the cache details page...

**Comment by murggel** [comment]
Probably some mix of both will work

**Comment by fm-sys** [comment]
But this regression is at least way less important than invisible icons ;-)

**Comment by fm-sys** [comment]
With PR #11040 I removed the last usage of the `action_bar` style, so I combined the two styles `action_bar` and `tool_bar`. I will merge #11040 as soon as checks are green, so don't forget to update your fork to avoid merge conflicts ;-)

**Pull request merged**
