### PR TITLE
Update some libraries, fix some deprecations

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Update AndroidX Browser 1.2.0 -> 1.3.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/browser))
- Update AndroidX ExifInterface 1.3.1 -> 1.3.2 ([changelog](https://developer.android.com/jetpack/androidx/releases/exifinterface)) 
- Update GeographicLib-Java 1.50 -> 1.51 (no changelog, but you can use https://winmerge.org/ and compare the sources.jar files)
- Port upstream README changes from mapsme/api-android
- Fix some deprecations
- Use LayoutInflater.from instead of getSystemService where possible

### CODE REVIEW

**Comment by TacoTheDank** [comment]
Repushed to fix codacy issue.

**Comment by rsudev** [comment]
Ok to test

**Comment by moving-bits** [comment]
@TacoTheDank 
Thanks for your contribution, very welcomed!
I'm not that deep into the compatibility layers, therefore the question: Are those changes compatible with the range of API levels we support, being API 21 (Android 5.0) up to the current Android version?

**Comment by bekuno** [comment]
@TacoTheDank
Also thanks to the contribution from my side.
It is our ambition that every PR brings exactly one solution to one issue. So it would be fine if you divide your PR into the 3 different topics. You should use an separate branch for every topic, see https://github.com/cgeo/cgeo/wiki/Working-on-c%3Ageo-for-git-beginners#working-on-an-issue

Some notes:
- the release notes for GeographicLib are at https://sourceforge.net/p/geographiclib/news/
- if you want you can also update androidannotations, see https://github.com/androidannotations/androidannotations/releases/tag/androidannotations-4.8.0
- if you want you can also update gradle-versions-plugin, see https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.36.0

**Comment by TacoTheDank** [comment]
@moving-bits 
> I'm not that deep into the compatibility layers, therefore the question: Are those changes compatible with the range of API levels we support, being API 21 (Android 5.0) up to the current Android version?

Yes, it should be all good 👍

**Comment by TacoTheDank** [comment]
@bekuno Ah, ok, thank you. I'll update this request to reflect that (though I can't change the branch from which this PR is being made now).

**Comment by bekuno** [comment]
LGTM
@TacoTheDank Thaks for your contribution

**Pull request merged**
