### PR TITLE
fix #14304: add basic SVG support

### LINKED ISSUE #14304: Certitude icon not shown in listing text
### Describe your problem!

A user reported, that on his owned cache, where he uses certitude as cache checker and the corresponding inline picture is not shown in c:geo.

### How to reproduce?

- Open GC80ECK
- Check after text "spoiler:" 

### Actual result after these steps?

The hyperlink is shown but the image after it, is missing (empty).

In your normal browser the image is shown:

image

### Expected result after these steps?

Image should be shown in c:geo

### Reproducible

Yes

### c:geo Version

2023.05.15

### System information

_No response_

### Additional Information

Source is:
```
<p align="CENTER" style="margin-bottom:0.5cm;"><font color="#000080"><a href="https://www.certitudes.org/certitude?wp=GC80ECK"><font color="#000080"><img src="https://imgproxy.geocaching.com/b1e761a0a93d9fb3fca80b8bc5e10d890320db3d?url=https%3A%2F%2Fwww.certitudes.org%2Flogo%3Fwp%3DGC80ECK" align="BOTTOM" width="129" height="129" border="1"></font></a></font>
 </p>
```

The missing file type ending of the linkes image looks suspicious. User fault?

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #14304: add basic SVG support to c:geo. Should fix issue with non-displayed certitude-logos

### CODE REVIEW

**Comment by eddiemuc** [comment]
Failing test seems unrelated

**Comment by moving-bits** [comment]
> Failing test seems unrelated

will be fixed with #14309

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
Now CI tests work again. But Codacy doesn't seem to work. It fails to analyze the PR. Don't know whats wrong.

**Comment by ztNFny** [comment]
retest this please

**Pull request merged**
