### PR TITLE
fix #12767: cherrypick from master: refactor http request response interface (was #12699)

### LINKED ISSUE #12767: Still/Again picture upload issue
### Describe your problem!

I am out on a business trip at the moment.
However while quickly scanning support mail, there are a few users reporting that with 2022.02.13 and 2022.02.16 they have problems uploading log images.

Symptoms seems to be similar to what we already fixed:
- c:geo reports error but upload is good (only title missing)
- Uploading more than one photo fails completely

Can someone doublecheck?

### How to reproduce?

see above..sorry, written from mobile device

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Unclear

### c:geo Version

2022.02.16

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #12767: cherrypick from master: refactor http request response interface (was #12699)

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR tries to merge a cherry-picked commit (261c6b841cab614ba175978365c6d5f231cd3434) from master to release in order to maybe-fix #12767

**Comment by Lineflyer** [comment]
I am unsure about this one as its a rather huge change. As written in the corresponding issue I would like to wait if
- More users have this problem
- Any of them has a reproducible scenario for us

**Comment by eddiemuc** [comment]
> I am unsure about this one as its a rather huge change. As written in the corresponding issue I would like to wait if
> 
> * More users have this problem
> * Any of them has a reproducible scenario for us

Absolutely. Let's just wait. I don't suppose much will change in this code area in the near future anyway.

**Comment by Lineflyer** [comment]
There have been 4-5 such reports up to now.
I advised all users to relogin and try again.

One user provided feedback that its working now, others did not reply yet.
Lets wait a bit.

**Comment by eddiemuc** [comment]
This PR is no longer meaningful/needed

**Pull request closed without merging**
