### PR TITLE
Use more precise regular expressions for GC/TB codes.

### PR DESCRIPTION
**Pull request by UniQP**
The codes do not contain the letters I, L, O, S, and U.

### CODE REVIEW

**Comment by kumy** [comment]
I'm curious, where did you get this information?

**Comment by SammysHP** [comment]
Maybe it is better to have the definition of the expression only one time.

**Comment by SammysHP** [comment]
@kumy 
https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/connector/gc/GCConstants.java#L210

**Comment by samueltardieu** [comment]
So the failing test must be fixed as well, I guess that was a dummy geocode.

**Pull request merged**
