### PR TITLE
add reference + source for route invert order icon (rel. to #11389)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
see https://github.com/cgeo/cgeo/pull/11389#issuecomment-906777137
- adds reference to source file in svg for route invert order icon
- adds unmodified source file for this

### CODE REVIEW

**Comment by moving-bits** [comment]
@murggel 
Following the discussion about SVG for the docs: Shall I remove the "SVG" (XML) from this PR then, keeping only the added comment?

**Comment by murggel** [comment]
> @murggel 
> Following the discussion about SVG for the docs: Shall I remove the "SVG" (XML) from this PR then, keeping only the added comment?

If it shall be referenced in the manual,  you can keep it and I will add it to the DokuWiki, otherwise you can remove it...

**Comment by moving-bits** [comment]
Hm, thinking about it, we seem to try to accomplish two things at the same time:
a) keep original / source file for a drawable
b) save a SVG/PNG version for documentation

This PR adds a comment in the Android drawable (`drawable/ic_menu_swap_vert.xml`) pointing to the source, which should be sufficient for b). And as this PR does not add a SVG but the original XML only, a) can be served better with the drawable actually used in c:geo (in combination with your script).

So if I'm not mistaken, adding the original drawable in XML format does not make sense here.

**Comment by murggel** [comment]
> Hm, thinking about it, we seem to try to accomplish two things at the same time:
> a) keep original / source file for a drawable
> b) save a SVG/PNG version for documentation
> 
> This PR adds a comment in the Android drawable (`drawable/ic_menu_swap_vert.xml`) pointing to the source, which should be sufficient for b). And as this PR does not add a SVG but the original XML only, a) can be served better with the drawable actually used in c:geo (in combination with your script).
> 
> So if I'm not mistaken, adding the original drawable in XML format does not make sense here.

Ok, this is right, I thought you add the svg. You can remove the xml from raw images. We can get the svg then from web if necessary.

**Comment by moving-bits** [comment]
ok, removed the drawable in `rawimages` from this PR, keeping only the added comment

**Review by murggel — APPROVED** [review]
Thanks

**Pull request merged**
