### PR TITLE
make short date format configurable

### PR DESCRIPTION
**Pull request by ztNFny**
added a new "Localization" section in Settings where I grouped the new option with the old unit and language:
image

available configurable date formats:
image

in use:
image

fixes https://github.com/cgeo/cgeo/issues/16285
fixes https://github.com/cgeo/cgeo/issues/16249

### CODE REVIEW

**Comment by ztNFny** [comment]
Settings item is in wrong position, will fix later, WIP for now

**Comment by fm-sys** [comment]
> Also display texts should show examples

Maybe use the current day as example format? (this wouldn't really work at days like 02.02. though)

**Comment by ztNFny** [comment]
> > Also display texts should show examples
> 
> Maybe use the current day as example format? (this wouldn't really work at days like 02.02. though) 

That'd require the display texts to be generated which is probably overkill. 
I'd just go do m for something like 17.2.2024 to make it quite clear in any date format

**Comment by ztNFny** [comment]
retest this please

**Comment by moving-bits** [comment]
I like the approach to make the date format configurable + grouping of localization preferences. Not sure, though, if we have covered all relevant data formats.

Alternative approaches could be:
- automatically retrieve a list of available date formats and create the list dynamically - covers all available date formats, but can have lots of duplicates (if not filtered further)
- make the formatting arguments available directly - most flexible, but probably too technical for most users

But let's give it a try in the nightlies and see if more date formatting wishes come up.

**Comment by ztNFny** [comment]
> * make the formatting arguments available directly - most flexible, but probably too technical for most users

this technically is already available - you can go into the settings editor and enter your custom format

**Pull request merged**
