### PR TITLE
Fix #6682, #6702: Parse username using Jsoup

### LINKED ISSUE #6682: Error displayed when do a cache log
##### Detailed steps causing the problem:
- Open a geocache
- Log as "found it"
- When you are submitting it display an error saying "login failed"
- Reload geocache information, you see that the log was submitted successfully

It begin to appear, after new Geocaching.com layout.

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

### PR DESCRIPTION
**Pull request by kumy**
GS has changed the top bar code, let's adapt our page parsing.
Moved to using Jsoup instead of old style regexp pattern.

We still have to adapt our unit tests (MockedCache.java) and certainly update mocked caches in /cgeo/geocaching/test/mock/

### CODE REVIEW

**Comment by kumy** [comment]
Hum old style top bar select all span childs. Let's fix that

**Comment by Lineflyer** [comment]
This fixes both issues?

**Comment by kumy** [comment]
@Lineflyer yes :)

**Comment by Lineflyer** [comment]
Merge whenever you think you are ready. I will then build and test a RC version.
But you should merge to `release` not  `master`.

**Pull request merged**
