### PR TITLE
add "Edit Personal Note" button to CachePopup

### PR DESCRIPTION
**Pull request by ztNFny**
add a "Edit personal note" button to CachePopup for quick access to editing the note.
As all the "storing the note and handling updates" stuff is in CacheDetailActivity, not in EditNoteDialog, an intermediate CacheDetailActivity is started and finished.

image

### CODE REVIEW

**Comment by Lineflyer** [comment]
Only some remarks:
- Isn't that the spot, where the "hint" button appears if a cache hint is present? Is this handled in some way?
- AFAIR the "hint" button is also shown if a PN is present and on button-press it is then shown on the popup. Shouldn't this "edit note" button then be shown next to that personal note?

**Comment by ztNFny** [comment]
> * Isn't that the spot, where the "hint" button appears if a cache hint is present? Is this handled in some way?

There are several buttons that might be shown next to details: WIG, Lab, Hint - and now this one

> * AFAIR the "hint" button is also shown if a PN is present and on button-press it is then shown on the popup. Shouldn't this "edit note" button then be shown next to that personal note?

I have some problems with that: 
- Already todays display of note in hint is kinda unintuitive, it'd be even more strange to have to tap "show HINT" first to then be able to tap "edit NOTE"
- Hint/Note layout would end up quite strange
- 2 taps instead of 1, the second of which would have to find its target first - not very user friendly for an operation probably used frequently.

**Comment by ztNFny** [comment]
> When is this button supposed to show up?

Only condition is connector.canAddPersonalNote(cache), which for GC translates to a Premium account. Maybe your c:geo didn't properly sign in and thus premium features are not enabled?

**Comment by moving-bits** [comment]
> > When is this button supposed to show up?
> 
> Only condition is connector.canAddPersonalNote(cache), which for GC translates to a Premium account. Maybe your c:geo didn't properly sign in and thus premium features are not enabled?

ah, good point - I was probably using the wrong emulator. Thanks

**Comment by fm-sys** [comment]
Basic members can add personal cache notes inside cgeo as well. Should we really hide the button for them?

**Comment by ztNFny** [comment]
> Stumbled upon a small glitch in dark mode: (wrong icon tinting)

Good catch, fixed

> Basic members can add personal cache notes inside cgeo as well. Should we really hide the button for them?

I got that from some existing edit note function, didn't think too much about it. But you're right, that restriction doesn't make much sense - removed.

**Pull request merged**
