### PR TITLE
New IconDecoder #6175

### PR DESCRIPTION
**Pull request by mucek4**
Temporary fix. Detection is less detailed, I'll provide better detection in few days.

### CODE REVIEW

**Comment by Lineflyer** [comment]
retest this

**Comment by Lineflyer** [comment]
@samueltardieu Might you have time to take a look on this?

**Comment by samueltardieu** [comment]
I'll try to look at it this morning.

**Comment by samueltardieu** [comment]
@Lineflyer What do you want me to do? I cannot reasonably test this or update the tests if this will change. Do you want me to merge it to `release` unconditionally (it compiles)?

@mucek4 Could you share the sources (or commands) you used to produce this file? Maybe somebody can help working on this.

**Comment by mucek4** [comment]
if it compiles (Probably tests will fail) just merge to release and let Lineflyer test. I can push a code somewhere but it's terrible (written only for my eyes).

**Comment by samueltardieu** [comment]
Well, in this case just press the "Rebase and merge" button :-)

**Comment by Lineflyer** [comment]
If I understand correctly this change at least is able to compile (but will break some tests).
So merging would be a first step enabling me to test. 

Preferably someone ( @samueltardieu ?) can merge release to master afterwards? So I can test with the nightlies first before creating a new RC.

I will "rebase and merge".. Feel free to revert if this is not the right way to go forward.

**Pull request merged**
