### PR TITLE
Re-enable all unified map features

### PR DESCRIPTION
**Pull request by fm-sys**
Re-enable all unified map features which were working before starting with the new design pattern idea.

rel to https://github.com/cgeo/cgeo/issues/14113#issuecomment-1586344977

- Re-enable Tap handling
- Re-enable actionbar hiding (adapt to layout still missing)
- Refactor  / Re-enable LoadInBackgroundHandler / MapsforgeGeoitemLayer
- Refactor / Re-enable distance view / set as target
- Refactor AbstractPositionLayer to use geoitemlayer (only direction line is still missing)

### CODE REVIEW

**Comment by fm-sys** [comment]
retest this please

**Comment by fm-sys** [comment]
retest this please

**Comment by fm-sys** [comment]
@moving-bits @eddiemuc 

This PR restores all unified map features which were working before I started with the refactoring... In other words, this PR completes all ongoing changes related to GeoItemLayer, fragment-based map providers and observer-based UI refreshing for now.

If you find code parts where you think things could be done even better, feel free and go ahead! We should use the opportunity to write code which is easy to understand and maintain...

Unified map is looking for your help, quite some features are still waiting ;-)

**Comment by moving-bits** [comment]
Thanks @fm-sys for your hard work on improving UnifiedMap's architecture, very welcomed!

I propose to merge this PR to test it on `master` and open dedicated issues if anything arises.

As so much has been ongoing with regards to UnifiedMap's internal architecture, I'll close some of the older bug reports for UnifiedMap, as they are very likely obsolete. Let's do a fresh restart with regard to bug reports for UnifiedMap (except there's something obviously still broken).

**Pull request merged**
