### PR TITLE
rel to #13138: replace imagegalleryview self-made views with recyclerview

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #13138: replace imagegalleryview self-made views with recyclerview

### CODE REVIEW

**Comment by eddiemuc** [comment]
PR should now be ready for merge. This is however a fundamental change for the image gallery, it is now based on a single recyclerview (instead of many self-made views)

**Comment by fm-sys** [comment]
Looking forward to test it in the nightlys... :)

**Comment by moving-bits** [comment]
Thanks for your work, I'm really looking forward to get the new image gallery into release.

I played a bit with it in the emulator. I started with GC89AXV:
- Opening the gallery was pretty fast, but all images displayed instantly (having been downloaded already since those are listing images).
- Tapping on any image lead to a crash, though:

```
E/ActivityTaskManager: Second failure launching cgeo.geocaching/.ImageViewActivity, giving up
    android.os.TransactionTooLargeException: data parcel size 998708 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:540)
        at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2504)
        at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
        at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
        at com.android.server.wm.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:863)
        at com.android.server.wm.RootWindowContainer.startActivityForAttachedApplicationIfNeeded(RootWindowContainer.java:1965)
        at com.android.server.wm.RootWindowContainer.lambda$5fbF65VSmaJkPHxEhceOGTat7JE(Unknown Source:0)
        at com.android.server.wm.-$$Lambda$RootWindowContainer$5fbF65VSmaJkPHxEhceOGTat7JE.apply(Unknown Source:8)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:315)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
        at com.android.internal.util.function.pooled.OmniFunction.apply(OmniFunction.java:78)
        at com.android.server.wm.ActivityRecord.forAllActivities(ActivityRecord.java:3620)
        at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1331)
        at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1324)
        at com.android.server.wm.RootWindowContainer.attachApplication(RootWindowContainer.java:1944)
        at com.android.server.wm.ActivityTaskManagerService$LocalService.attachApplication(ActivityTaskManagerService.java:6890)
        at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:5378)
        at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:5458)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2320)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2883)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
```
(Not sure if we can do something about that.)

As GC89AXV is an extreme example, I continued with two earthcaches, GC7Y7FB (41 images) and GC7VQEN (71 images).
- Listing images were already downloaded, log images got loaded "on the fly" while scrolling down, displaying a placeholder image while downloading.
- Tapping on an image and scrolling left/right works like a charm.

Really nice work, a huge improvement over the old official gallery (which is why I'm using the in-between-version since months, now). Thanks for all the effort you've put in here!

I have only two small proposals for now:
- A bit confusing: Each image displays a small "v" / "^" in the lower right corner. If there is a title + log info, the content changes accordingly when tapping on the symbol, but if there is no title, nothing changes. Maybe this could be improved.
- When you are in image view, scrolling to an image not loaded yet, only an empty window is being shown (in contrast to list view, where a placeholder image is being shown). Maybe you can show the placeholder image here as well while the download runs.

**Comment by eddiemuc** [comment]
Ah I think my expectation management was not very good... Unfortunately this PR is not the end of the work (but it should be the major part of it), and it only fixes the performance problems in the gallery, not yet in the image details view. Note that I left the "experimental" label for now.

> - Tapping on any image lead to a crash, though:

Correct. As you probably guessed this is due to all image information to be displayed for the whole list is put into the intend data. If there are too many images, then intend data gets too large. This is fixable and will be fixed in a later step. I am not done :-)

> - A bit confusing: Each image displays a small "v" / "^" in the lower right corner. If there is a title + log info, the content changes accordingly when tapping on the symbol, but if there is no title, nothing changes. Maybe this could be improved.

Sure that's an easy one to do :-)

> - When you are in image view, scrolling to an image not loaded yet, only an empty window is being shown (in contrast to list view, where a placeholder image is being shown). Maybe you can show the placeholder image here as well while the download runs.

Noticed this too, and will change it

**Comment by eddiemuc** [comment]
For clarification: my plan is to fix the Imageview things in a new PR once this one is merged. Since they already exist in the system today, this PR will not "downgrade" it. And the PR is already too large for my taste. 

Hope that's fine?

**Comment by fm-sys** [comment]
> my plan is to fix the Imageview things in a new PR once this one is merged. Since they already exist in the system today, this PR will not "downgrade" c:geo. And the PR is already too large for my taste.
>
>Hope that's fine?

Sure, following the Git principle "commit small, commit often"... ;-)  

I haven't merged this PR yet, cause I was not sure if you are still working on it currently. Please merge if you are ready.

**Comment by moving-bits** [comment]
> For clarification: my plan is to fix the Imageview things in a new PR once this one is merged. Since they already exist in the system today, this PR will not "downgrade" c:geo. And the PR is already too large for my taste.
> 
> Hope that's fine?

Sure, go ahead when you are ready to merge. The new gallery is already very useful, even without those tiny things mentioned above.

**Pull request merged**
