### PR TITLE
add some basic tests for internal connector

### PR DESCRIPTION
**Pull request by moving-bits**

### CODE REVIEW

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/src-android/cgeo/geocaching/connector/internal/InternalConnectorTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4929841&bid=16306986)

**Comment by moving-bits** [comment]
Failing test claims that it cannot find a certain resource:
`android.content.res.Resources$NotFoundException: String resource ID #0x7f10040b`

The resource mentioned is the title for ZZ0 caches, defined in `res/values/strings.xml` - why does the test not find this resource, and how can I fix this?

**Comment by bekuno** [comment]
For thest we use the test source set:
~~~
       test {
            setRoot("../tests")
            manifest.srcFile '../tests/AndroidManifest.xml'
            java.srcDir '../tests/src'
            resources.srcDirs = ['../tests/src']
            res.srcDirs = ['../tests/res']
        }
~~~
Therefore the res folder from the test is active.

I checked the test implementations for string resolution. There is used 
~~~
CgeoApplication.getInstance().getString()
~~~

So I changed in InternalConnector.java from context.getString() to CgeoApplication.getInstance().getString() and the test errors are gone.

After that - this works:
~~~
    public static void testCreateZZ0() {
        InternalConnector.getInstance().assertHistoryCacheExists(CgeoApplication.getInstance());
~~~

**Comment by Lineflyer** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/src-android/cgeo/geocaching/connector/internal/InternalConnectorTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/cgeo/cgeo/pullRequest?prid=4929841&bid=16306986)

**Comment by moving-bits** [comment]
@bekuno Thanks for fixing this and for the explanation. Works like a charm now 👍 (for the Internal Connector tests). The three newly failing tests seem to be related to gc.com website being very volatile today.

**Comment by moving-bits** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Pull request merged**
