### PR TITLE
Fix #6839: add D/T rating to log signature

### LINKED ISSUE #6839: add D/T rating to log signature
**Feature Request**

As a geocacher I want to include the D/T rating of the current Cache in my log signature as template variable. Like this I am aware of D/T rating changes between the date I found the cache  (created an offline log) and the date I log the cache. This might be important when logging several caches for a challenge cache (having stored offline logs and the rating changed afterwards).

I want to be aware of D/T rating changes between the date I found the cache (created a offline log) and the date I log the cache. This might be important when logging several caches for a challenge cache (having stored offline logs and the rating changed afterwards).

**Acceptance Criteria**

1. when I click on "settings/logging/signature/insert template" I can choose "Difficulty" from the drop down.
2. when I click on "settings/logging/signature/insert template" I can choose "Terrain" from the drop down.
3. having selected "Difficulty" "[DIFFICULTY]" has been added to my signature.
4. having selected "Terrain" "[TERRAIN]" has been added to my signature.
 5. selecting "Log visit" on a Cache inserts my signature having e.g. "[DIFFICULTY]/[TERRAIN] replaced with the according rating (e.g. "D3/T4") for a D3/T4 cache.

### PR DESCRIPTION
**Pull request by janykey**
oh man! feeling like a noob ... thought I could reenter these lines lying on the sofa with my mobile ... Sorry!

I forgot to convert the float to a String ... 

Thanks,
Jan

### CODE REVIEW

**Comment by SammysHP** [comment]
OK to test.

**Comment by pstorch** [comment]
I tested it and it works as expected. If you squash the commits into one, we can merge it.

**Comment by pstorch** [comment]
And as @SammysHP mentioned, please change the commit message to `Fix #6839 add D/T rating to log signature`.

**Comment by janykey** [comment]
Thanos :-) happy to hear that.

Is there a way on github or do I have to do in in android studio?
I'm asking because I'm currently AFK and only have my mobile with me.

Jan

**Comment by pstorch** [comment]
> Is there a way on github or do I have to do in in android studio?

I think you have to use the command line or android studio. I've not done squashing via AS myself. I prefer the git cli for this task.

**Comment by janykey** [comment]
OK, I think it worked. $git rebase -i HEAD~3 ...

Now it's ready?

**Comment by pstorch** [comment]
@janykey perfect, thanks for you contribution

**Pull request merged**
