### PR TITLE
Fix #7510 -Crash when switching between map views.

### LINKED ISSUE #7510: Crash on map source change
##### Detailed steps causing the problem:
- Use cgeo-nightly-GM
- Open live map
- Click icon to change map source
- Change e.g. from Google: Maps to Google: Satellite

##### Actual behavior after performing these steps:
Sometimes c:geo crashes. On next access of the map the source changed as desired though
It might be related to the map being centered to current position or not...not sure.

##### Expected behavior after performing these steps:
Normal switch of map source

##### Version of c:geo used:
2019.04.15-NBGM1

##### Is the problem reproducible for you?
No, only sometimes but quite reproducible

##### System information:
Android 6.0.1 Cyanogenmod
Samsung S3 LTE

##### Other comments and remarks:
I was not yet able to capture a stacktrace but have seen some kind of AuthorizationProblem logs in the ADB logcat. Not sure whether this is related. Was shown as "E/Auth" as sender.

### PR DESCRIPTION
**Pull request by jonas-koeritz**
I don't know if an issue has been created for this but I experienced crashes when switching between map view types.

### CODE REVIEW

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
Should fix #7510

**Comment by jonas-koeritz** [comment]
Achievement unlocked: fixing an issue without knowing about it.

**Comment by Lineflyer** [comment]
:) 
If you are still interested to fix other known GMapsV3 issues:
https://github.com/cgeo/cgeo/issues?q=is%3Aopen+is%3Aissue+label%3A%22New+Map+Google%22

**Comment by Lineflyer** [comment]
The failed test seems to be related to the branch itself but not your change. I will merge and check when I find time to use the GMAPsv2 nightlies.

**Pull request merged**
