### PR TITLE
attributes sorting in cache details and attribute filter (fix #12189)

### LINKED ISSUE #12189: Sort attributes in cache details and attribute filters
### Tell us your idea!

Reminder to myself

### What solution would you suggest?

Sort attributes in cache details and attribute filters in the same way as it's done for attribute overview implemented with #12140 

### Is there an alternative?

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Sort attributes in cache details page and in attribute filter according to the attribute categories:

|cache details: icons|cache details: texts|attribute filter|
|---|---|---|
|image|image|image|

(also fixes one category assignment)

### CODE REVIEW

**Comment by bekuno** [comment]
For `cache details: texts` - is it possibe to use different size or font style for category and attribute?

**Comment by moving-bits** [comment]
> For `cache details: texts` - is it possibe to use different size or font style for category and attribute?

I've added underlining to the headings, see here:
image

(I had also tried bold, but this was a bit bulky, and did not clearly enough separate from the nex tline.)

> in text-view would it be possible to display "[icon] text"? helps learning the icons (though it's probably a separate feature request)

Would be a separate FR, as this would probably create the need for it's own list adapter etc.
But what one could try would be to add long press action / hints to the attribute icons, as it's done in the filter.

**Comment by ztNFny** [comment]
> But what one could try would be to add long press action / hints to the attribute icons, as it's done in the filter.

I think that's not suited here, a short-click to show the text version is easier than holding to get the tooltip for only 1 attribute (and I think most users don't even know about holding for a tooltip)

**Comment by moving-bits** [comment]
Too late :-)

But I think it does not harm either. I've added the tooltip to the `AttributesGridAdapter`, thus it is used for both cache details and attributes overview.

image.image

**Comment by Lineflyer** [comment]
> But what one could try would be to add long press action / hints to the attribute icons, as it's done in the filter.

In this context please also try to check the screen reader compatibility.
While briefly looking into #12085 I have noted, that the attribute icons are currently not backed by some textual description, thus the screen reader is not able to read those.

**Comment by moving-bits** [comment]
> In this context please also try to check the screen reader compatibility. While briefly looking into #12085 I have noted, that the attribute icons are currently not backed by some textual description, thus the screen reader is not able to read those.

added

**Pull request merged**
