### PR TITLE
use dedicated commit for the mapsforge library

### PR DESCRIPTION
**Pull request by bekuno**
As needed by #9919:

To use a special commit instead a release it is possible using jitpack.org.
First you have to integrate jitpack as maven source.
On jitpack you must select your commit.
Go to https://jitpack.io/#mapsforge/mapsforge, select commit, an "Get it" from th commit list.

### CODE REVIEW

**Comment by moving-bits** [comment]
@bekuno 
Thanks for preparing this configuration. Not sure, but don't we need the (currently) latest commit cdccd83a18, as according to the change log this is the commit that includes the ZIP render theme.

**Comment by bekuno** [comment]
This is the commit after the needed one with the new release notes.

**Comment by moving-bits** [comment]
@bekuno 
Need your help with this one:
I'm trying to access the `ZipRenderTheme` class, which is part of the mapsforge version included by this PR, but AS does not detect it. And if I select any other mapsforge class, AS will point me into the `mapsforge-map-0.15.0.jar`, although `build.gradle` clearly points to the specific commit. What do I have to do to be able to access the new classes introduced by that PR?

**Comment by bekuno** [comment]
I tested the access of one of the mapsforge classes. It looks in AS like 
grafik
Then you should be able to access the needed class ....

**Comment by moving-bits** [comment]
Thanks for cross-checking. I did it exactly this way, but AS neither did list any of the new classes like `ZipRenderTheme`, and only showed `mapsforge-map-0.15.0.jar` in the top left corner, although I have been on master branch. - But today our "special commit jar" is shown. Spooky :-) (Or maybe some caching problem.)

**Pull request merged**
