### PR TITLE
fix #3819 (and #5202): make description text selectable

### LINKED ISSUE #3819: Ability to copy only a part of the description
I often want to copy only a part of the description to use in other apps.
It might be a coord, a word that I want to google, a cipher in a mystery cache that I want to decipher etc.
But when I long press the description there are only an option to copy all of the description.

I would love if there was a possibility to select and copy a part of the description or part of the hint.

Suggestion:
Add a "Select text" option in the longpress menu
Use standard text selection to select a part of the text.
Like in the mockup below.

Select text

### PR DESCRIPTION
**Pull request by rahu**
with these changes it's possible to copy, share and translate only parts of description. I removed the separation of short and long description to be able to select both in a single selection.

Testing the new feature I run into https://code.google.com/p/android/issues/detail?id=137509 and https://code.google.com/p/android/issues/detail?id=23381. The workarounds are working fine.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Can one of the admins verify this patch?

**Comment by rsudev** [comment]
I can probably take a look at it today evening

**Comment by rsudev** [comment]
ok to test

**Comment by rsudev** [comment]
ok to test

**Pull request merged**
