### PR TITLE
fix #15972: log images, allow opening non-local data

### LINKED ISSUE #15972: Log images in remote locations cannot be used any more
c:geo version: 2024.08.09-RC
Support [Ticket #715663](https://cgeosupport.droescher.eu/scp/tickets.php?id=8387)

In log image picker, images from remote locations cannot be opened any more.

I believe this is caused by one of my changes: https://github.com/cgeo/cgeo/pull/15949

I believe that the statement `intent.addCategory(Intent.CATEGORY_OPENABLE)`; has to be removed in method `ImageActivityHelper.getMultipleItemsFromStorage()`

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #15972: log images, allow opening non-local data

### CODE REVIEW

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
I strongly suspect the build to be red due to CI problems

**Comment by bekuno** [comment]
Yes, correct.

@mucek4 
Please restart the whole CI. Thanks.

**Comment by bekuno** [comment]
Retest this please

**Comment by eddiemuc** [comment]
retest this please

**Comment by moving-bits** [comment]
failing tests seem to be unrelated, let's test this PR in the nightlies

**Pull request merged**
