### PR TITLE
fix icon style (fix #11732)

### LINKED ISSUE #11732: [vectorIcons] Wrong icon style in Cache/Waypoint selector
### Describe your problem!

Screenshot_20210926-120730

### How to reproduce?

- Open GC75KBQ
- Select Navigate - Navigate (Drive)

### Actual result after these steps?

Wrong icon style in Cache/Waypoint selector

### Expected result after these steps?

Show normal cache marker (like in cache lists)

### Reproducible

Yes

### c:geo Version

2021.09.08

### System information

_No response_

### Additional Information

_Extracted out of https://github.com/cgeo/cgeo/issues/11730_

### PR DESCRIPTION
**Pull request by fm-sys**
before|now
-|-
grafik|grafik

### CODE REVIEW

**Comment by fm-sys** [comment]
retest this please

**Comment by moving-bits** [comment]
Looks good generally, but would it be possible to have the waypoint icons without the little "pin" at the bottom?

**Comment by fm-sys** [comment]
> Looks good generally, but would it be possible to have the waypoint icons without the little "pin" at the bottom?

I'm unsure about this one, but however it has IMHO nothing to do with this PR. It's the same in `NewMap` in our current nightly:

So if we want to change this, it should IMHO go into an dedicated issue. 

Screenshot_20211003_092610_cgeo geocaching_copy_324x702

**Comment by fm-sys** [comment]
BTW, the pin does IMHO even make sense. While the cache doesn't need the be at the listed coords, waypoints are always fixed (as long as they have coordinates). So this pin marker helps to quickly recognize whether it's a cache or waypoint...

**Comment by moving-bits** [comment]
IMHO the pin makes sense on the map only, for pointing to a specific location on the map. I would leave it out in all other places. But I agree that this would fit for a separate issue.

**Pull request merged**
