### PR TITLE
gk: always use CET timezone

### LINKED ISSUE #9496: Geokrety logging doesn't work when logging from timezone ahead of CET
**To Reproduce:**
1. Open some cache (I'm in SU caches)
2. Save the log with 'write note type"
3. Use Geokrety to set all as visited
5. Send the log

Cgeo will show "logging GK", but this will be really really quick and no log will be added to GK.

I first though it doesn't work just for "write note" logs, but today it didn't for for "found" logs as well...

**Version of c:geo used:**
You will find the c:geo version in c:geo Menu -> About c:geo

**Is the problem reproducible:**
Yes / often

**Screenshots:**
You may attach screenshots if applicable and helpful to explain your problem

**System information:**
```
Attach system information here if available (see c:geo Menu -> About c:geo -> Swipe right to System)
Keep the apostrophe at beginning and end to have it properly formatted
```

**Additional context:**
e.g. Reference to other issues, projects, sources, etc.

### PR DESCRIPTION
**Pull request by okainov**
This is just a blind coding, no IDE around :(

Fixes #9496

### CODE REVIEW

**Comment by okainov** [comment]
Tried APK from jenkins - looks fine, working now for me

**Comment by moving-bits** [comment]
Shall we target this to `release` branch?

**Comment by okainov** [comment]
@moving-bits amm, I have no idea :) Just in case if needed, created https://github.com/cgeo/cgeo/pull/9506 for release

**Comment by Lineflyer** [comment]
@moving-bits Indeed we should use `release`. So lets close here in favor of #9506

**Pull request closed without merging**
