### PR TITLE
pass current cache coordinates to geochecker

### LINKED ISSUE #6782: Pass final coordinates to Geochecker
Some geochecker URLs allow passing of coordinates as request parameter.

For geochecker.com:
http://www.geochecker.com/index.php?code=...&lastcoords=N48+12.345+E11+12.345

Entering the coordinates with mobile devices is tedious. If a final waypoint is available we could also send these coordinates to the URL if this is supported.

### PR DESCRIPTION
**Pull request by ztNFny**
Pass the current cache coordinates to geocheckers for checkers supporting that.

## Description
Entering coordinates into the checker is quite annyoing on the small phone screen - but something done often to verify that the final coords are still correct or to get the spoiler image.
geocheck.org/geotjek.dk and geochecker.com support a url parameter to pass a coordinate to be checked.

## Related issues
fixes #6782

### CODE REVIEW

**Comment by ztNFny** [comment]
retest this please

**Comment by moving-bits** [comment]
There are some checkstyle findings, see https://ci.cgeo.org/job/cgeo%20CI%20-%20PR%20build/155/console:
```
22:48:37  [ant:checkstyle] [WARN] /home/jenkins/slave/workspace/cgeo CI - PR build/main/src/cgeo/geocaching/utils/CheckerUtils.java:19:33: Name 'CHECKERS' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]
22:48:37  [ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo CI - PR build/main/src/cgeo/geocaching/utils/CheckerUtils.java:60:27: Parameter urlPattern should be final. [FinalParameters]
22:48:37  [ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo CI - PR build/main/src/cgeo/geocaching/utils/CheckerUtils.java:64:27: Parameter urlPattern should be final. [FinalParameters]
22:48:37  [ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo CI - PR build/main/src/cgeo/geocaching/utils/CheckerUtils.java:64:46: Parameter coordinateParam should be final. [FinalParameters]
22:48:37  [ant:checkstyle] [INFO] /home/jenkins/slave/workspace/cgeo CI - PR build/main/src/cgeo/geocaching/utils/CheckerUtils.java:64:70: Parameter coordinateFormat should be final. [FinalParameters]
22:48:38  Checkstyle rule violations were found. See the report at: file:///home/jenkins/slave/workspace/cgeo%20CI%20-%20PR%20build/main/build/reports/checkstyle/checkstyle.html
22:48:38  Checkstyle files with violations: 1
22:48:38  Checkstyle violations by severity: [warning:1, info:4]
```

@bekuno 
Shouldn't those findings be listed / linked to from the build result page?

**Comment by bekuno** [comment]
Only on success:
~~~
22:51:35 [CHECKSTYLE] Skipping publisher since build result is FAILURE
~~~

**Comment by eddiemuc** [comment]
Out if interest: how do you use this function in c:geo? E.g. how as a user do I ask c:geo to open a geochecker with specific coordinates prefilled? Where do I find this in the GUI?

**Comment by ztNFny** [comment]
> how do you use this function in c:geo?

In cache overflow menu there's the "open geochecker" item (unchanged). For the 2 checkers supporting this the current coordinates will be passed.

**Comment by eddiemuc** [comment]
> > how do you use this function in c:geo?
> 
> In cache overflow menu there's the "open geochecker" item (unchanged). For the 2 checkers supporting this the current coordinates will be passed.

Thanks.
If I understand correctly this will then only work as expected for users of "corrected coordinates" (so not for me :-() because onna cache with original coordinates those would be passed. Correct?

**Comment by ztNFny** [comment]
Correct. Of course you're free to extend it to work for any waypoint.
IMHO that's not with it though, as it'd add a lot of complexity (have to extend cache with something like hasCheckerSupportingPassingOfCoordinates() + checker url, hook all the different places where coords are called) for little value (only 2 checkers are supported, most users are using corrected coords).

**Comment by eddiemuc** [comment]
I don't think it has to work for every waypoint. I propose something much simpler: in the code place where it is decided which coordinate to pass, implement following logic:
- if cache has corrected coordinate, use this one
- if cache has a final waypoint with coordinates use this one
- otherwise pass listing coordinates

According to last survey, a substantial amount of users use final waypointa to mark the spot (~30%) so I think this small extension wouls be valuable. Although you're right that the majority uses corrected coords (~60%)

**Comment by ztNFny** [comment]
> if cache has a final waypoint with coordinates use this one

How would that work when there are multiple final waypoints?

**Comment by fm-sys** [comment]
> > if cache has a final waypoint with coordinates use this one
> 
> How would that work when there are multiple final waypoints?

The algorithm will never be perfect. But it doesn't need to be perfect, as the user can always copy and paste different coords if he wants to.

So we could either:
- don't pass coordinates if there are multiple finals
- use the coords of the first final

However, I would like to avoid another selection dialog to keep the number of required clicks as low as possible...

**Comment by eddiemuc** [comment]
I agree with @fm-sys. If there are multiple final waypoints, just take the first one (with coordinates). This will solve 99%+ of all cases IMHO.

To make it very concrete, my suggestion is:
* if the `Geocache` instance in question is stored in a variable `cache`, then call `cache.getFirstMatchingWaypoint(Waypoint::isFinalWithCoords)`
* If the returned value is `null`, then there's no final waypoint with coordinates. If it is not `null`, then use the coords of this waypoint

**Comment by eddiemuc** [comment]
retest this please

**Comment by bekuno** [comment]
In the moment when I think I have a solution I don't know if this is correct. So I would not set this as final or as corrected coordinate.
Instead I would go to a manual selection. We can present a list of all defined coordinates of the cache in the form "Name (Type) - Coordinates". The user can then tap one and the checker pager should directly opened with this selected coordinate.

**Comment by ztNFny** [comment]
> if the Geocache instance in question is stored in a variable cache, then call cache.getFirstMatchingWaypoint(Waypoint::isFinalWithCoords)

implemented

**Comment by eddiemuc** [comment]
retest this please

**Comment by ztNFny** [comment]
Are only some of the build servers broken?

**Comment by Lineflyer** [comment]
> Both actually active executors have different and sporadic problems.

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
no luck with the servers 😟

**Comment by eddiemuc** [comment]
retest this please

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
are there any news on the jenkins issues?

**Comment by moving-bits** [comment]
in this case it's probably a failing test: `cgeo.geocaching.utils.CheckerUtilsTest.testGetCheckerUrl`

**Comment by ztNFny** [comment]
> in this case it's probably a failing test: `cgeo.geocaching.utils.CheckerUtilsTest.testGetCheckerUrl`

Oops, with all the build failures I didn't look at the result so close anymore, expecting it to be another generic issue.
Will adjust the test.

**Comment by eddiemuc** [comment]
> are there any news on the jenkins issues?

I had same problem with my PRs. Pushing a dummy commit (where I just changed some code comments) did the trick. For some reason this seems to trigger the CI "differently" than the "retest this please" phrase

**Comment by Lineflyer** [comment]
retest this please

**Pull request merged**
