### PR TITLE
adjust cache info hint color (rel. to #11069)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description (1)
- regarding map cache popup's and cache details' info section
- distinguish colors of name and value sections

dark mode:
image.image

light mode:
image.image

## Description (2)
- adjusts colors on waypoints page
- removes unnecessary space above waypoints on waypoints page

image

### CODE REVIEW

**Comment by fm-sys** [comment]
In light mode, the gray text color is quite hard to read. Maybe, we can do some fine tuning here?

**Comment by moving-bits** [comment]
A couple of proposals:

image.image.image
(Coming from #ffaaaaaa as color, those pics are made with 9/8/7 instead of a)

or even a bit darker:
image.image
(this one uses #ff666666 as hint color)

**Comment by fm-sys** [comment]
I like the `#ff666666` most

**Comment by moving-bits** [comment]
> I like the `#ff666666` most

Wish granted ;-)
see PR #11085

**Pull request merged**
