### PR TITLE
right-aligned expand/collapse icons in SimpleDialog and custom default list icons

### PR DESCRIPTION
**Pull request by ztNFny**
Right-align icons as per discussion in https://github.com/cgeo/cgeo/issues/15194
image

### CODE REVIEW

**Comment by ztNFny** [comment]
Use a spacer in layout instead of padding to align the icons, aslo for checkbox mode
image

**Comment by eddiemuc** [comment]
Lgtm code-wise and design-wise. Have you checked whether other places using grouped lists and other special features also still look ok? I usually double-check the following dialogs:
- function selection in variable dialog (is grouped)
- search for usages of "activate grouping" to find other examples (I believe there is one more somewhere)
- action button per item, used in filter dialog select/delete-named-filter-button
- cache selection when tapping on map and there's more than one cache under your finger
- log type selection in logging activity

**Comment by ztNFny** [comment]
> Have you checked whether other places using grouped lists and other special features also still look ok? I usually double-check the following dialogs:

all good, thanks for the pointers, especially for radiobutton i had no idea where it was used.

I just added another commit - custom icons for default lists:
image

**Comment by ztNFny** [comment]
And now can we get icons for stored filters please? 🤣

**Review by eddiemuc — APPROVED** [review]

**Comment by eddiemuc** [comment]
I added my approval, but didn't merge in case you want to do more changes to the PR

**Comment by ztNFny** [comment]
> I added my approval, but didn't merge in case you want to do more changes to the PR

it's good to go, you can merge

**Comment by eddiemuc** [comment]
> > I added my approval, but didn't merge in case you want to do more changes to the PR
> 
> it's good to go, you can merge

Ok, then thanks a lot for the great work!

**Comment by eddiemuc** [comment]
I spoke too soon. There's a small codacy issue on the PR unfortunately

**Comment by ztNFny** [comment]
done

**Comment by fm-sys** [comment]
> And now can we get icons for stored filters please? 🤣

Just add an emoji as first char of the name, using this kind of grouping since years now ;)

share_3594466075017782269_copy_372x578

**Comment by eddiemuc** [comment]
@ztNFny I am really really sorry, but it seems the branch has merge conflicts now. I hope I wasn't the one introducing them

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
And now we merge :-) Thanks again to @ztNFny

**Pull request merged**
