### PR TITLE
Remove Magic Char

### PR DESCRIPTION
**Pull request by S-Bartfast**
Just a little housekeeping

### CODE REVIEW

**Comment by kumy** [comment]
jenkins retest this please

**Comment by pstorch** [comment]
@S-Bartfast I don't want to be the one who is picky all the time, but I don't like the commit message. Can't you use the PR title `Remove Magic Char` also as the commit message? That would be great.

**Comment by S-Bartfast** [comment]
> @S-Bartfast I don't want to be the one who is picky all the time, but I don't like the commit message. Can't you use the PR title Remove Magic Char also as the commit message? That would be great.

No problem.  And no offence is taken, in fact I prefer you being picky.  It's the best way to learn ;)

**Comment by pstorch** [comment]
@S-Bartfast thanks a lot ;)

**Pull request merged**
