### PR TITLE
WIP migrate cachedetails and trackables to material tabs

### PR DESCRIPTION
**Pull request by moving-bits**
## Description

If someone wants to play with it already - here is a first shot at migrating the cache details pages to viewpager2 and material tabs. Still far from feature complete, but working in general (except a few subpages not yet activated).

### Further things on my TODO list for this
- [x] tab title should not be changed for cache details pages
- [x] cache details not loading
- [x] images view empty
- [x] trackables view missing or emtpy
- [x] loading of initial page
- [x] multiple updates to cache description (elements get added?)
- [x] pull to refresh
- [x] migrate to ViewBindings (where possible)
- [x] implement `notifyDataSetChanged`
- [x] implement `reinitializeViewPager`
- [x] remove non-Android `viewpager` dependency
- [x] remove old `AbstractViewPagerActivity` and dependent classes
- [x] start with details page instead of description page
- [x] implement hook to onPageChangeListener for calling activity
- [x] search - cache: detail page empty
- [x] search - trackable (or trackable list - detail): crash
- [x] search - cache: starts with wrong initial page (description instead of details)
- [x] cache logs page: header gets re-added on refresh (instead of replaced)
- [x] rename classes to `TabbedViewpagerActivity` / `TabbedViewPagerActivityFragment`
- [x] delete classes and layouts used for old ViewPagerActivity
- [x] fix all issues marked with "@todo mb" (when necessary), keep an eye on remaining ones if any issues occur

### CODE REVIEW

**Comment by moving-bits** [comment]
## Migration of cache details pages and trackable pages to viewpager2 and material tabs

This is closing in now on release candidate state. As this change got larger than expected, any testing would be very welcomed. Or shall we merge to a nightly for this?

Here are some screenshots and what you can expect from this PR:

### Cache detail page
image.image.image
image.image.image
(Friends' logs page left out intentionally)

### Trackable page
image.image.image

**Comment by Lineflyer** [comment]
Wow...that looks like quite some effort. Thanks @moving-bits for diving into this! :)

**Comment by moving-bits** [comment]
Of the three Codacy issues, two are about method too long / complexity too high, both already existing before this PR, and the third one is about naming a generic parameter - a rule not really useful (why should I name a generic "T" when "ViewBindingClass" gives you much more info what this parameter is about?) - so a couple of fixed old issues, but a "won't fix" for those three assumed new ones, if no one objects.

Still the PR needs to rebuild, as one unrelated test was failing.

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
