### PR TITLE
Display caches with corrected coords with enlarged "blue flag" marker

### PR DESCRIPTION
**Pull request by fm-sys**
rel. to #10924

This will look like this:

grafik

@ztNFny are you ok with this implementation?

### CODE REVIEW

**Review by ztNFny — COMMENTED** [review]
I suggest to use "else if" instead of "if" to connect the 2 cases for bottom-right, makes it easier to read the logic if each position has its own if-block.

**Comment by ztNFny** [comment]
I'm wondering whether the "has corrected" info is really important enough to be displayed in this way.

And it doesn't fit in with the existing functionality of showing big icons for found caches. For a found cache you don't care about it anymore, it's just a smiley on the map, so far so good. But is the equivalent true for a cache with corrected coords, meaning is every cache with corrected coords the same? Could be a solved mystery or a started multi or ...

I'd say this would need a new setting. The existing is "Big icons for logged caches" which doesn't accurately reflect the new behaviour, so at least it'd need to be renamed. But imho it's a completly different functionality which shouldn't be tied into the existing one.

(disclaimer: I'm not using big icons mode)

**Comment by fm-sys** [comment]
> I'm wondering whether the "has corrected" info is really important enough to be displayed in this way.

At least it was suggested in  #10924 and no one has disagreed. And it's the same as on GC.com ;-) 

> And it doesn't fit in with the existing functionality of showing big icons for found caches. For a found cache you don't care about it anymore, it's just a smiley on the map, so far so good. But is the equivalent true for a cache with corrected coords, meaning is every cache with corrected coords the same?

It's kind of a similar meaning. For found caches, you don't need to care about the cache type anymore because the cache is already found. 
For e.g. solved Mysteries or finished Multis, you don't need to care about the cache type as well, because the cache type turns into a normal Tradi as soon as it is solved.

> I'd say this would need a new setting

Those who are really using this setting where fine with connecting these two things into one and the same setting (based on the comments in  #10924). The bigSmiley thing is quite new to cgeo anyway, so it doesn't have a large user base until now. IMHO we shouldn't introduce new settings for such things until there are explicit requests which cannot be solved without a new one.

**Comment by ztNFny** [comment]
Changing the preference name/description should be included with this change though.

**Comment by fm-sys** [comment]
> Changing the preference name/description should be included with this change though.

1:0 for you. Will do so...

**Review by Lineflyer — APPROVED** [review]

**Comment by fm-sys** [comment]
I've tried my best to write a short, but meaningful and understandable explanation...

grafik

**Comment by ztNFny** [comment]
Lgtm

**Pull request merged**
