### PR TITLE
move waypoint settings to own preference group within map settings

### PR DESCRIPTION
**Pull request by moving-bits**

### CODE REVIEW

**Comment by Lineflyer** [comment]
I stumbled upon this PR, which has recently been merged to `release`.
Isn't that underlying feature (hiding different waypoint types) on `master` only? Or is this something different?

I would like to suggest again(!) to open issues before submitting PRs and use the issue to explain the desired change and only after that submit the corresponding PR (with subject "Fix #xyz). That allows a more easy tracking of whats going on.

**Comment by moving-bits** [comment]
@Lineflyer 
This is #8101 which fixes #7848 and #5118 (both are mentioned in the PR)

**Comment by Lineflyer** [comment]
#8101 is perfectly fine. But does this PR here in any way depend on that PR? That was basically my question as this PR was merged to release and #8101 to master.

**Comment by moving-bits** [comment]
> #8101 is perfectly fine. But does this PR here in any way depend on that PR? That was basically my question as this PR was merged to release and #8101 to master.

It's applicable to both master and release, as it's a follow-up to both #8101 and #8127, so rsudev suggested in https://github.com/cgeo/cgeo/pull/8133#issuecomment-589970698 to put it in release branch first.

Background: Both #8101 and #8127 introduce a new preference regarding waypoints, and together with the existing waypoint options it's clearer if grouped into it's own preference section (which I discovered during merge resolution - should have separated it then in the first place). #8101 is a new feature, therefore started on master branch, #8127 a fix for something already on release branch, therefore I targeted it to release.

**Comment by Lineflyer** [comment]
OK, thanks for clarification and sorry, I missed that discussion during my vacation.
Will smoke test a new RC then.

**Pull request merged**
