### PR TITLE
fine-tune dashboard status messages (fix #12631)

### LINKED ISSUE #12631: Automated backup check - improvements
### Describe your problem!

I just saw the automated backup check for the first time.

So I just hit the "check" button, but nothing happened. I did wait some time, pressed it again - nothing! After closing and reopening the app, it still didn't work, and I haven't found any way to get it triggered. 

### How to reproduce?

- open "view settings"
- set `automaticBackupLastCheck` to a low number but higher than 0. (e.g. 1)
- close cgeo
- notification is displayed but doesn't work

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

2022.01.29-NB-071456a

### System information

_No response_

### Additional Information

Furthermore, a visual bug: IMHO the action button should be vertically centered

Screenshot_20220129_132745_cgeo geocaching

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Fine-tuning for dashboard messages regarding backup & update reminder:
- remove action button => tapping on message activates action
- adapted messages accordingly
- fix: only one message could be shown at a time - now all (up to three) can be displayed

image

### CODE REVIEW

**Comment by Lineflyer** [comment]
What I ask myself when seeing this messages though:
How can I now decline them to get rid of them if I do not want that action to be performed.

**Comment by moving-bits** [comment]
> What I ask myself when seeing this messages though: How can I now decline them to get rid of them if I do not want that action to be performed.

With not having a dialog box any longer, you can only ignore them currently, or disable the functionality completely. But there's no way to postpone an action any more (no "later" action as we had in the dialog boxes).

If we want to have a "later" action, we could re-add a button, this time with a clock symbol or something like this.

**Comment by Lineflyer** [comment]
How about something like "Do you want ..... Tap here to dismiss or perform this action" followed by a  yes/no dialog.

At least I would like to avoid not being able to get rid of it without performing the action.

**Comment by moving-bits** [comment]
But wouldn't we have sort of a doubled dialog then? Sort of "Tap here to update" => "do you really want to update" => "yes I REALLY DO WANT TO UPDATE, I told you so" or "oops, no, I actually don't want to update"... :-)

Maybe a long-tap to dismiss temporarily?

**Comment by Lineflyer** [comment]
> Maybe a long-tap to dismiss temporarily?

Good idea. IMHO that is more wise than buttons as long as the text describes it.

**Comment by moving-bits** [comment]
Added ability to postpone dashboard actions by long-tap, extended messages accordingly:

image

**Comment by Lineflyer** [comment]
Looks not that bad. I would not put the last part in parenthesis though.

Sorry for asking rather late:
If the user accepted "auto backup". Will further auto backups just be done or will this message be recurring? 
In that case the question would be: What is automatic about that?

I would prefer it in a way like "Do you want to do enable a regular automatic backup? Tap here to accept or long tap to decline." and from then on it will be done really automatically in background.

**Comment by moving-bits** [comment]
> Looks not that bad. I would not put the last part in parenthesis though.

Ok, will adapt that.

> Sorry for asking rather late: If the user accepted "auto backup". Will further auto backups just be done or will this message be recurring? In that case the question would be: What is automatic about that?
> 
> I would prefer it in a way like "Do you want to enable a regular automatic backup? Tap here to accept or long tap to decline." and from then on it will be done really automatically in background.

We had a short discussion about that in the original issue: As we need to have exclusive access to the database, we need to inform the user anyway, and block any user actions until backup has been completed. But we did not want to force the user to be interrupted in the moment c:geo likes to perform an automatic update, so we decided to go with a message (we started with an `AlertDialog`, but switched to the current less-intrusive way later).

Switching on/off can be done in preferences, with default being "on".

**Comment by fm-sys** [comment]
Sorry, but what is the purpose of postponing the backup? (Especially as normal notifications can't be postponed either) 

I can only imagine two use cases:
- I want to do the backup not now but some minutes later
- I want to do the backup never

If I want to do it in some minutes, the postpone feature will not help me as there is no way to get the dismissed notification reappearing. Instead, I can just ignore the notification until I'm ready. 

If I want to do no automated backups at all, it will be annoying if the notification is always reappearing. 

IMHO the only thing which would make sense is to link the long click action to the "backup settings" page where the user can configure this notification.

**Comment by Lineflyer** [comment]
> IMHO the only thing which would make sense is to link the long click action to the "backup" screen in our settings where the user can configure this notification.

That would also be fine from my perspective. 
So the text would then be something like:
"This is a backup reminder. Tap here to backup your data now or long tap to configure."

**Comment by Lineflyer** [comment]
The question would then be if we still need a separate backup storage path after all.

**Comment by moving-bits** [comment]
I would leave it exactly as it is now, for several reasons:
- We were looking for a mostly-automated way to create backups, as most people seem to be unaware of this functionality, or are too lazy to use it. Putting it into the main menu did not help as much as wanted, so we want to make it more prominent. `AlterDialog` was too much for some, so we put it as a message on dashboard. Just linking from there to the regular backup mechanism is one step too much, IMHO, the action should be executed from the notification directly.
- We wanted to separate those semi-automatic backups from the regular ones, as "power users" may have created backups for specific reasons, and we don't want to overwrite those backups. And, again, asking "do you want to overwrite" might be too much for the average user in this case.
- Regarding postponing: For the "postpone by a few minutes" you simply endure the notification for that timespan. The more frequent scenario would be "I'm out on a caching tour today, so don't bother me today", IMHO - therefore a delay by a few days.
- The way it is implemented currently is very similar to the notifications for map updates and routing tile updates, so it's pretty consistent.

The only alternative I see is to enforce automatic backups, which goes into the direction of what @Lineflyer has suggested a bit further up:
- if automatic backups are enabled,
- check on c:geo start whether one is due,
- and do a full-automatic backup, if so, without any further question, blocking c:geo for that time.

This would delay the start by a few seconds in those cases, but would have minimal user-interaction impact otherwise, and would guarantee a regular backup (if not explicitly disabled by the user).

The one thing I'm unsure about this in that constellation is how big the impact will be for the user - how long will such a backup take, especially in the combination of relatively slow device and relatively large database, and would this impact be tolerable.

**Comment by fm-sys** [comment]
> Regarding postponing: For the "postpone by a few minutes" you simply endure the notification for that timespan. The more frequent scenario would be "I'm out on a caching tour today, so don't bother me today", IMHO - therefore a delay by a few days.

A backup takes only a few seconds and doesn't even require internet connection. Most probably the use case would be "not now but this evening", but then the "postpone" feature would do more harm than good.

Again: Why should it be considered bothering at all? Normal notifications (e.g. "an update is available") can't be postponed either...

**Comment by moving-bits** [comment]
> A backup takes only a few seconds and doesn't even require internet connection. 

Which leads us to a full-automatic solution then, as described above.

So if no one stops me, I will update the PR this evening, changing the auto backup behavior to:
- not display a notice on the dashboard,
- check need for auto-backup on startup, and perform it without further user interaction, if time has come
- (otherwise PR will be unchanged, e. g. configurability of auto-backup interval and dashboard notices for map/routing data update)

**Comment by Lineflyer** [comment]
Lets start with that, then test and optimize if needed.

**Comment by moving-bits** [comment]
> Lets start with that, then test and optimize if needed.

You mean "start with as it is now" or "start with full-automated" as described in my last post?

**Comment by Lineflyer** [comment]
> You mean "start with as it is now" or "start with full-automated" as described in my last post?

Start with what you proposed (full-automatic).
There might however be some cases which need consideration, as e.g. what happens if backup cannot be done for whatever reason, first start behavior, etc. 
Thats what I meant with optimize if needed.

**Comment by moving-bits** [comment]
updated PR accordingly

**Pull request merged**
