### PR TITLE
redesign of section separators

### PR DESCRIPTION
**Pull request by ztNFny**
redesign section headlines and unify their style across activities
| Screenshot_20241117_170321  | Screenshot_20241117_171824  |
|---|---|
|  Screenshot_20241117_170909 | Screenshot_20241117_171823  |
| Screenshot_20241117_172201  | Screenshot_20241117_171821  |

### CODE REVIEW

**Comment by eddiemuc** [comment]
Codacy failed on this PR. 
Also, the UX change should probably be discussed in the team before we merge it.

**Comment by bekuno** [comment]
retest this please

**Comment by murggel** [comment]
The color of the separator lines changed for dark mode and are barely visible now

**Comment by ztNFny** [comment]
> The color of the separator lines changed for dark mode and are barely visible now

you'd expect that Material Design colors are well refined ... seems that isn't the case :-(

**Pull request merged**
