### PR TITLE
related to #9142: remove dateStr as possible parameter

### PR DESCRIPTION
**Pull request by eddiemuc**
related to #9142: remove dateStr as possible parameter

@bekuno since you merged #9142 already I made an own PR for this. I hope that's ok?

### CODE REVIEW

**Comment by bekuno** [comment]
> @bekuno since you merged #9142 already I made an own PR for this. I hope that's ok?

Full ok.
It was not necessary to have both changes in one step. Therefore I merged the string change first to see the change on the CI command line.

**Comment by bekuno** [comment]
retest this please

**Comment by eddiemuc** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Pull request merged**
