### PR TITLE
fix #16086: multiple images in Personal Note not added to images tab

### LINKED ISSUE #16086: multiple images in Personal Note not added to images tab
URLs ending on an image extension (e.g. .jpg) are recognized as images and added to images tab.
However when there are multiple URLs in the note only 1 is added.

Might be related to https://github.com/cgeo/cgeo/commit/0203137ce7f6c2899e65208869bc1d2ed01a4c59 , need to check

### PR DESCRIPTION
**Pull request by ztNFny**
fixes #16086

### CODE REVIEW

**Comment by ztNFny** [comment]
Retest this please

**Comment by ztNFny** [comment]
fails unrelated

**Comment by moving-bits** [comment]
@ztNFny 
FYI: This PR has a conflict now after merging the "dynamic image size" PR...

**Comment by ztNFny** [comment]
rebased

**Pull request merged**
