### PR TITLE
fix #6826 remove superfluous waypoint note

### LINKED ISSUE #6826: User created waypoint has two editable note areas
##### Detailed steps causing the problem:
- Add a new waypoint
- There are two editable areas "Note" and "User Note"

##### Actual behavior after performing these steps:
Two areas where one is enough.

##### Expected behavior after performing these steps:
"Note" area which is usually read-only for imported waypoints is not visible because it makes no sense for user created waypoints.

##### Version of c:geo used:
2017.11.05-NB-cc9328b

##### Is the problem reproducible for you?
Yes

##### System information:
On demand.

##### Other comments and remarks:
Not sure if this was always the case.

### PR DESCRIPTION
**Pull request by pstorch**
For user defined waypoints, the note is merged with the userNote and the original note be emptied.

Empty note fields get hidden, even for server defined waypoints.

For server defined notes gets preserved. They are not editable but we stripped html. Now html can be preserved.

Html in userNotes is not supported and "<" characters escaped.

This might solve #6791 as well.

### CODE REVIEW

**Comment by Matze2** [comment]
I did a quick test. For edit it looks good.
But for a new waypoint it still shows both note fields.

**Comment by Matze2** [comment]
I've added a
`            note.setVisibility(View.GONE);
`
around line 262 in the "else"-Block to hide the note area in case of "Add Waypoint".

**Comment by Matze2** [comment]
Another one: in case of "duplicate" the note is stil HTML when concatenated.
I guess HTML.fromHTML() has to be called before entering the if-else-block but it's too late now. :)

**Comment by Matze2** [comment]
Here is my git diff. Almost untested. Just for illustration.
[diff.txt](https://github.com/cgeo/cgeo/files/1465304/diff.txt)

**Comment by pstorch** [comment]
@Matze2 thanks for testing. The handling of the HTML formatted notes gets a bit tricky now. But I wanted to preserve it as long as possible. I'll have a look.

**Comment by Matze2** [comment]
At least it does not get more complex with my changes. And it seems that now the three use cases (new, edit, duplicate) work.

**Comment by Matze2** [comment]
Tested a little bit more the PR plus my changes that fix the remaining issues with "duplicate" and "new" waypoint. Everything looks fine to me now.

**Comment by pstorch** [comment]
I'm testing your changes, too. The visibility to GONE is working.
With the HTML issue I'm not sure right now. The only problem is the `\n` concatenation is not resulting in a line break, if the note contains HTML. Everything else seams to be fine.
With your changes the EditNotesActivity crashes when I immediately clear the userNote field, save the waypoint and open it again.

**Comment by Matze2** [comment]
About the \n: yes I see that, too. But only for duplicates where HTML is preserved.

**Comment by Matze2** [comment]
It's double-stripped:
first in line 162: Html.fromHtml
second in line 173 if user note contains a "<"

So I reproduced it with the following steps:
- take a waypoint with a note
- add <12 as user note
- duplicate it
- open it (line feed is eaten between note and user note)

**Comment by Matze2** [comment]
With the crash: you're right. I screwed it up. waypoint.getNote() can be null and I now call HTML.fromHtml() unconditionally.

**Comment by pstorch** [comment]
Hmm, the fix for the `<` characters which where interpreted as invalid HTML tags cause some confusion. It causes the entire note to be recognized as HTML (because it is a `&lt;` now) and all line breaks get ignored.

I think we have to properly "clean" the notes: strip html tags while preserving the line breaks somehow. And the `TextUtils.containsHtml()` needs to be more intelligent.

**Comment by pstorch** [comment]
I've updated the PR, but the issue is not finally solved yet. That's why I added the `Do not merge` tag.
I'll continue tomorrow. @Matze2 thanks for your help.

**Comment by Matze2** [comment]
I have fix for the NullPointerException. Will share it later.

**Comment by pstorch** [comment]
@Matze2 The Nullpointer is already handled. But if you like, you can take over and continue on this.

**Comment by Matze2** [comment]
No, is ok. I was just irritated because I still saw an NPE, but with my tainted waypoint with a null note.
As this cannot happen anymore, I am fine.

For the HTML not vs. non-HTML user note, I am not sure I should start on that.
This looks weird - especially together with duplicate - and might require bigger changes as you pointed out.

I will give it a try when you have something new.

**Comment by Matze2** [comment]
Ok. A few comments before I also stop for today:
- Do we really need to check if user note is HTML? How can this happen since user note is only edited in a simple text field? And in duplicate case HTML note is already converted before it gets copied to user note...
- Is it 100% sure that waypoint.getNote() is never null? Otherwise a check might be needed. Something like that (note that I use CharSequence instead of Spanned):
```
                        CharSequence noteFromHTML;
                        if (StringUtils.isNotBlank(waypoint.getNote())) {
                            noteFromHTML = Html.fromHtml(waypoint.getNote(), new SmileyImage(activity.geocode, activity.note), new UnknownTagsHandler());
                        } else {
                            noteFromHTML = StringUtils.EMPTY;
                        }
```

**Comment by pstorch** [comment]
@Matze2 my null handling was this:
```
final Spanned noteFromHTML = Html.fromHtml(StringUtils.trimToEmpty(waypoint.getNote()), new SmileyImage(activity.geocode, activity.note), new UnknownTagsHandler());

````

The `StringUtils.trimToEmpty()` handles null and converts it to empty string. 
Or have you found another line where a null pointer could happen?

**Comment by Matze2** [comment]
You're right. Maybe it was too late yesterday. I might have build a mixture of your latest commit and code from me.
Your changes should work. Sorry about the confusion.

**Comment by pstorch** [comment]
> Sorry about the confusion.
Don't be sorry. I'm glad that someone else is looking at it, too. I regularly miss things ;)

**Comment by pstorch** [comment]
Ok, when we agree on NOT supporting HTML in the `userNote` field then it is much easier (I guess anyway no one likes to edit HTML in source code in an Android textfield).

It looks like I found a way to merge the HTML `note` with a TEXT `userNote`, incl. preservation of line breaks in the TEXT.

Please have a look.

**Comment by Lineflyer** [comment]
> Ok, when we agree on NOT supporting HTML in the userNote field then it is much easier 

My few cents:
I dont think HTML in the user note is being used quite often.
So I agree it could be interpreted as plain text anyway.

**Comment by Matze2** [comment]
Wow! You were really busy. Generally I like it when more code/complexity is removed than added. :)

About HTML in user note: I have no idea how you can use it at all. Entering HTML tags directly in the input area? Is this supported?

Anyway, I like the diff, but I cannot test anything before Friday. But then I will.

**Comment by Matze2** [comment]
I still have some old waypoints (created in previous versions) with null note.
These crash in line EditWaypointActivity:158. Do we need to care about that?

**Comment by Matze2** [comment]
I added another trimToEmpty in line 158 and now this works.
`
                        if (TextUtils.containsHtml(StringUtils.trimToEmpty(waypoint.getNote()))) {
`

**Comment by Matze2** [comment]
So, finally with the correct branch I did some testing.
- Existing waypoints with "<" in user note are now escaped and need to be fixed once.
- Existing waypoints with "<" in note got truncated but after reload everything was fine with them

Besides that I checked open, duplicate save and reopen with notes and without notes (also with <) for
- listing waypoints without note and user note
- listing waypoints with note
- own waypoints
and couldn't find any issue. 👍

**Comment by pstorch** [comment]
@Matze2 thanks again for testing.

**Comment by pstorch** [comment]
@all ready for testing in `master`?

**Pull request merged**
