### PR TITLE
updated changelog_full for release 2021.09.27

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
updated `changelog_full.md` to reflect recent changes of current release 2021.09.27

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
@mucek4 Our CI permanently fails on installing ADB bridge. Maybe it is time for a complete reboot?

**Comment by mucek4** [comment]
Restarted executor.

**Comment by bekuno** [comment]
> 
> 
> Restarted executor.

@mucek4 
Perfect, all runs are without errors now.
Please restart the other configured executors. I want to see if the java11 installation is now useable.

**Pull request merged**
