### PR TITLE
Only display the toggle switch if the device has magnetic sensor support

### PR DESCRIPTION
**Pull request by FreddieSanchez**

### CODE REVIEW

**Comment by FreddieSanchez** [comment]
This is fixing issue #6302 that I recently opened.

**Comment by rsudev** [comment]
Please test

**Comment by pstorch** [comment]
I don't have such a device either and couldn't find an emulator without magnetic compass to test it.
But from my point of view this change sounds reasonable.
We already hide the button in `onCreate()` if the device doesn't have compass capabilities but in `forceRefresh()` we set the status (which might cause the button to reappear).
So, from my point of view :+1:

**Comment by pstorch** [comment]
@FreddieSanchez please add `fix #6302` to your commit message. Then the issue will be closed automatically when the PR gets merged.

**Comment by FreddieSanchez** [comment]
That's exactly what happens.

When the device is rotated into landscape mode, the new layout is used and
the toggle button's visibility from portrait layout does not persist.

I'll update the commit message shortly. Thanks

**Comment by rsudev** [comment]
Please test this

**Comment by rsudev** [comment]
test this please

**Comment by pstorch** [comment]
@rsudev do you want to trigger a new CI build?

retest this please

**Comment by FreddieSanchez** [comment]
I tested this using the Moto G4. Displaying the compass for a cache, then rotating the device into landscape mode. Verifying the toggle button is not visible. And rotating it back to portrait mode. Again verifying the toggle button is not present. 

I also tested this using the emulator to verify the expected behavior of a device with the compass sensor.

**Comment by pstorch** [comment]
@rsudev CI doesn't show up here, but according to the CI itself the PR was tested: http://ci.cgeo.org/job/cgeo%20pull%20request/722/

I think we can merge it.

**Comment by rsudev** [comment]
Thanks for the contribution!

**Pull request merged**
