### PR TITLE
developer app id gradle script enhancements

### PR DESCRIPTION
**Pull request by fm-sys**
...just playing around what CI thinks about it...

### CODE REVIEW

**Comment by fm-sys** [comment]
retest this please

**Comment by fm-sys** [comment]
This PR includes:

- use the ".developer" app ID suffix also on CI debug builds (PR builds and watchdog tests, ...). This will allow generated PR APKs to be installed on every device without uninstalling the nightly/release APK first.
- Fix shared preferences injection (adopt it for the new debug app ID)
- Other related fixes (e.g. I had to rename the debug file provider as that identifier can only be used by one app and was already in use on our CI emulators by the old builds without the changed app ID)

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
I tried and tested it in different configuration.
So far it was fine.
Let's test in the nightlies.

**Pull request merged**
