### PR TITLE
Fix #6660

### LINKED ISSUE #6660: Coordinate calculator is illegible
On my LineageOS 14 device, using the lighttheme, the coordinate calculator is illegible. The variable names are white on a very light background.

### PR DESCRIPTION
**Pull request by S-Bartfast**
Added a switch to select appropriate font colours for the calculator in relation to the selected theme.

### CODE REVIEW

**Comment by S-Bartfast** [comment]
image

**Comment by SammysHP** [comment]
Ok to test.

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
Yeah...the CI is cooperative again.

**Pull request merged**
