### PR TITLE
unifiedmap: create unified geoitemlayer

### PR DESCRIPTION
**Pull request by eddiemuc**
unifiedmap: create unified geoitemlayer

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR contains a first version of a map-independent geoitem layer to place all sorts of items upon a map in a map-provider-agnostic way. The PR also contains map-provider-implementations for all map-libaries currently used by c:geo (mapsforge c6, vtm and google v2)

It also contains a "test layer" which draws some test items onto the map for testing purposes (e.g. if map-independent alignment and placement works). It can be activated by enabling the hidden new boolean setting `feature_unified_geoitem_layer`. The test layer is drawn around coordinate `N40 00.000 E10 00.000`

**Comment by eddiemuc** [comment]
image
image
image

**Comment by fm-sys** [comment]
Great, really nice work! 

Next step would be to not only generalize drawing but also responding to item click events. Any plans about it yet?

**Comment by eddiemuc** [comment]
> Great, really nice work!
> 
> Next step would be to not only generalize drawing but also responding to item click events. Any plans about it yet?

Yes, but today I run into a possible dead-end. I wanted to calculate myself from the geoitems whether it was clicked and when now. See screenshot (the cyan rectangles are the "click zones" calculated for the markers):
image

But look what happens if I rotate the Google Map...
image

And I can't imagine what happens when I use 3D mode :-)

**Comment by moving-bits** [comment]
Great work, thanks for putting all this effort into it! Looking forward to seeing this being used for cache & waypoint markers "in real life"...

**Pull request merged**
