### PR TITLE
Test codacy pr

### PR DESCRIPTION
**Pull request by okainov**
This is dummy PR to double-check that Codacy scans Checkstyle.  Do not merge
Expected result: fail with a lot of import order errors

### CODE REVIEW

**Comment by okainov** [comment]
Seems like Codacy is not being triggered at all which I find suspicious....

**Comment by rsudev** [comment]
Codacy has quite a delay for open source projects nowadays, so it can still get triggered. Let's see.

**Comment by rsudev** [comment]
Looks like codacy ran on the PR, but didn't comment: https://app.codacy.com/app/cgeo/cgeo/pullRequest?prid=2857132
Seemingly it failed to apply the codestyle checks for the complete codebase.

**Comment by okainov** [comment]
Can it be either a bug in Codacy or some extra configuration missing?

**Pull request closed without merging**
