### PR TITLE
ignore NonConstantResourceId lint messages

### PR DESCRIPTION
**Pull request by bekuno**
related to #9224

### CODE REVIEW

**Comment by bekuno** [comment]
now 173 lint issues
https://ci.cgeo.org/job/cgeo%20pull%20request/3872/androidLintResult/

**Comment by moving-bits** [comment]
If we disable this check, how can we track if we have migrated all occurrences (eg. by implementing #9232 and other means)?

**Comment by bekuno** [comment]
> 
> 
> If we disable this check, how can we track if we have migrated all occurrences (eg. by implementing #9232 and other means)?

We have to disable this rule then and test if no more such message occure.
I add a big text to #9232.
And we have two issues to track the progress.

**Comment by moving-bits** [comment]
Thanks for opening the extra issues.

Is there a way to disable this rule on our CI only? By this we would still get local notification (which helps during migration), without "polluting" the CI's results.

**Comment by bekuno** [comment]
Skipping the check is now only active on CI.

@Lineflyer Is this OK from your side?

**Comment by Lineflyer** [comment]
> @Lineflyer Is this OK from your side?

I do not often look at those test results (as I have no idea of the coding background). So whatever is considered as OK for the team is OK for me :)

**Comment by moving-bits** [comment]
> Skipping the check is now only active on CI.

Thanks for updating this!

GitHub signals a branch conflict - can you update and squash the PR? Thanks.

**Pull request merged**
