### PR TITLE
replace deprecations from commons.lang3

### PR DESCRIPTION
**Pull request by Bananeweizen**
Some classes from commons.lang3 are meanwhile in a separate project,
and the old classes are deprecated.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Have to re-learn proguard first, as it looks like...

**Comment by Bananeweizen** [comment]
For me, something seems completely broken in our Android Studio configuration. The import order that both checkstyle and codacy complain about is exactly the order that AS creates (I just deleted all imports to check).
Can someone verify that in his installation, maybe? And if that is actually the case for everyone and not just me, then I'm very much in favor of just disabling the "ImportOrder" check in all tools.

**Comment by rsudev** [comment]
The AS import config is definitely not aligned with the checkstyle definition...
I'll check if this can get fixed.

**Comment by rsudev** [comment]
It looks like it is possible to have a compatible configuration for the import optimization on project level, but the respective file is seemingly not under revision control.

**Comment by bekuno** [comment]
seen in an other .gitignore:
!.idea/codeStyles
Maybe this takes under revision control.

**Comment by Bananeweizen** [comment]
retest this please

**Pull request merged**
