### PR TITLE
fix update check for Voluntary/Velocity themes

### LINKED ISSUE #14111: Update check for Velocity/Voluntary theme

### PR DESCRIPTION
**Pull request by ztNFny**
closes #14111

### CODE REVIEW

**Comment by ztNFny** [comment]
retest this please

**Comment by ztNFny** [comment]
failing test is unrelated, see #14128

**Comment by ztNFny** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by ztNFny** [comment]
Retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
For whatever reason this PR always runs into the "Could not create ADB Bridge" problem on CI. But the fix is straight forward, so let's merge it anyway.

**Pull request merged**
