### PR TITLE
colored attribute icons

### LINKED ISSUE #12310: colored attribute icons
color attribute icons by group

- [ ] create SVG versions of all attribute icons
- [x] define colors (and use them in svgs)
- [x] (slightly) update some attribute icons that won't work well with coloring
- [x] decide about negative/positive icons

use black through-line for disabled red attributes

image

### LINKED ISSUE #12421: Align attribute categories with GC?
While working on #12310 I just noticed that GC also has categories for icons, altough only hidden on some help page: https://www.geocaching.com/about/icons.aspx

Maybe we should align our categories with them? But in some cases I disagree, e.g.
- Night cache -> should be equipment (our tools)
- May require swimming -> should be equipment (our tools)

 @moving-bits you implemented the current categories, any opinion?

### PR DESCRIPTION
**Pull request by ztNFny**
implements attribute icons colored by their category
fixes #12310 
fixes #12421

I also corrected some bad category assignments along the way

attribute icons are now xhdpi instead of mdpi

image
image
image

### CODE REVIEW

**Comment by ztNFny** [comment]
retest this please

**Comment by bekuno** [comment]
Retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by bekuno** [comment]
Retest this please

**Pull request merged**
