### PR TITLE
[vectorIcons] Use correct icon style in search dropdown

### LINKED ISSUE #11591: [vectorIcons] Wrong icon style in search dropdown
### Describe your problem!

all places that use icons need to build the icon from multiple layers (filter dialog, search dropdown, ...)
There'll probably some slight difference in the icon display depending on the place:
- Map = with pin
- list/search = with (circle) marker but without pin
- filter dialog = without marker (should be enough, needs to be tested)

image

### How to reproduce?

-

### Actual result after these steps?

_No response_

### Expected result after these steps?

_No response_

### Reproducible

Yes

### c:geo Version

vectorIcons build

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by fm-sys**
fix #11591

grafik

### CODE REVIEW

**Comment by ztNFny** [comment]
The text colors are broken with light theme

**Comment by fm-sys** [comment]
> The text colors are broken with light theme.

Good catch!

> In light theme the dropdown is a dark grey and text should be white but is black (for title) and dark grey (for gc code)

As we use the same layout file at many other places (~6 places if I remember correctly), I guess we should rather change the background color to stay consistent.

That's how it looks at all other places:
grafik

**Comment by ztNFny** [comment]
I don't see any reason for the dropdown being dark in light mode - it's just a list like many others, so it makes sense if it's light with dark text.

I have a minor comment regarding the layout, but will open an issue for that.

**Comment by fm-sys** [comment]
> Does this PR thanks something with respect to search suggestions.
> 
> In the past it was a nice tool to crawl the offline stored caches...that should be kept.

The searchview suggestions and how the search view behaves does not change at all compared to previous versions of cgeo. It only changes the way how the results are styled and displayed.

To be precise: 
The caches doesn't need to be fully offline to appear in the search results. But they need to be contained in the DB. (e.g.  caches of the "history" list can have this state)

**Pull request merged**
