### PR TITLE
Checklogin is added for GCVote in settings

### PR DESCRIPTION
**Pull request by madankumarbaskaran**
Have a "Check password" function for GCVote in settings #4607 ; Feature is added. Please verify and share your comments.

Thanks
Madan

### CODE REVIEW

**Comment by samueltardieu** [comment]
I'm on mobile so I'll be brief. The style should match the one existing in cgeo (position of brackets, spaces, etc.), and you may not make a network request on the UI thread (we use RxJava for that).

**Comment by Bananeweizen** [comment]
Besides the issues mentioned by @samueltardieu the change as such looks fine to me. We normally have Eclipse and IDEA settings checked into the repository (at least for Eclipse this includes formatter settings), so can you please check if those settings are available for re-formatting in your IDE?

**Comment by madankumarbaskaran** [comment]
@Bananeweizen I am using Android Studio. I changed the code formatting setting as per codestylesettings.xml. Appreciate your suggestion.

@samueltardieu Can you please mention some code using RxJava to make network request on UI?. Since GCLogin.java uses the network request for geocaching.com, I followed the same way in GCVote.java.  Thanks in advance.

**Comment by samueltardieu** [comment]
The code which checks for the GC login uses RxJava for example: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/settings/AbstractCheckCredentialsPreference.java#L76-97

**Comment by madankumarbaskaran** [comment]
@samueltardieu Just verified, GCVote login too uses RxJava. The file CheckGCVoteCredentialsPreference.java extends AbstractCheckCredentialsPreference, so checking login eventually calls RxJava. Please correct me if my understanding is wrong.

**Comment by samueltardieu** [comment]
Ok for the RxJava part then.

**Comment by kumy** [comment]
@madankumarbaskaran The coding conventions are summed up in https://github.com/cgeo/cgeo/wiki/Coding-Conventions

Your PR need to be rebased on current master.

**Comment by madankumarbaskaran** [comment]
@kumy I will make the change highlighted by you. @samueltardieu @Lineflyer I am always getting login failure for GCVote login. I mailed to Guido moderator of gcvote.com to verify my credentials. He replied with below message on 28th March.
"that's still correct. But geocaching.com changed their layout and broke GCVote for all browsers. I guess that this is the issue you are experiencing.
I hope to be able to release an update withing one or two weeks"

But even now I am facing the same failure. Please comment on this issue.

Thanks
Madan

**Comment by Lineflyer** [comment]
What Guido is refering to does not have any influence on GCVote in cgeo. 
We are communicating directly with the gcvote server.

**Comment by Lineflyer** [comment]
@kumy:
How did you try?

Using the method mentioned in #4607 gives me a positive result:
```
<votes userName='Lineflyer' currentVersion='3.3' securityState='locked' loggedIn='true'>
<errorstring></errorstring>
</votes>
```

**Comment by kumy** [comment]
@Lineflyer: what did I said??

**Comment by Lineflyer** [comment]
sorry @kumy I wanted to ask @madankumarbaskaran

**Comment by madankumarbaskaran** [comment]
@Lineflyer It is my mistake. I passed "username" instead of "userName" in gcvote.com URL. It is working fine now. Sorry for the confusion.

**Comment by Lineflyer** [comment]
@madankumarbaskaran Can you address the comments and update the PR?

**Comment by madankumarbaskaran** [comment]
@samueltardieu Please check the PR. I squashed the commits and updated the PR on 16-Apr. But I raised the PR again in wrong branch.

**Comment by samueltardieu** [comment]
@madankumarbaskaran Please rebase your PR, as you can see yourself, it cannot be merged as-is. Our time, probably as yours, is very limited, so please can you make sure that you submit a *proper* PR before asking us to review it?

**Comment by Lineflyer** [comment]
It seems #4889 is the newer PR for this (which is still with work to do).
So I close this one.

**Pull request closed without merging**
