### PR TITLE
Basic UnifiedMap VTM implementation without fragment for map

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Yet another rudimentary VTM implementation (for testing purposes only), this time without using fragments for map (has `MapView` directly included in activity's layout)

### CODE REVIEW

**Comment by ztNFny** [comment]
unable to start map with this (either from list or bottom nav):

java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.unifiedmap.UnifiedMapActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:233)
                                                                                                    	at android.os.Looper.loop(Looper.java:344)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8212)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
                                                                                                    Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                                    	at java.util.LinkedList.checkElementIndex(LinkedList.java:559)
                                                                                                    	at java.util.LinkedList.get(LinkedList.java:480)
                                                                                                    	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onCreate(UnifiedMapActivity.java:248)

**Comment by ztNFny** [comment]
did you hardcode berlin (oam).map as map file??

**Comment by moving-bits** [comment]
> did you hardcode berlin (oam).map as map file??

yes, see line 245 - sorry, should have mentioned that. I was pursuing the cross-hatches problem I had found in Berlin, Alexanderplatz, so I used that as base map for my testing.

**Comment by ztNFny** [comment]
Exactly the same result as with https://github.com/cgeo/cgeo/pull/15268

**Comment by moving-bits** [comment]
with getting positive result from #15411 so far, we can close this WIP

**Pull request closed without merging**
