### PR TITLE
Send2cgeo: force to  redownload the cache on importing via send2cgeo (fix #14110)

### LINKED ISSUE #14110: Importing via send2geo doesn't update existing
### Describe your problem!

- Update coordinates on cache 1234 on geoaching.com
- Send the cache via send2geo
- In c:geo open a list with stored caches, which inclused cache 123
- Import from send2geo
- Observe cache is imported, but details / coordinates are not updated.

### How to reproduce?

see above

### Actual result after these steps?

see above

### Expected result after these steps?

When a cache is imported via send2geo and it already exists in c:geo it should be refreshed and coordinates should be updated.

### Reproducible

Yes

### c:geo Version

2023.02.25

### System information

```text
Pixel 7 (up to date)
```

### Additional Information

According to https://github.com/cgeo/cgeo/issues/1894 this should work.

### PR DESCRIPTION
**Pull request by murggel**
## Description

forces to redownload the cache, if send2cgeo imports a cache, that is already in the database

## Related issues

fix #14110

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by murggel** [comment]
i guess, the failing tests are not related to my changes?

image

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
