### PR TITLE
add attribute overview to cache list (fix #12130)

### LINKED ISSUE #12130: add list-specific overview of attributes
### Tell us your idea!

From support:

Add an option to cache lists to show an overview of all icons associated with any of the caches in that list (each icon to be shown only once), e. g. "chirp", "UV" etc.

Use-case is to cross-check whether any special devices/tools are required to bring when doing the tour specified by that list.

### What solution would you suggest?

extend list menu "manage lists" by "show attributes", which opens a dialog window displaying the attributes being associated with any of the caches in that list (but every icon only once). "OK" closes the dialog.

### Is there an alternative?

_No response_

### Additional Information

Ticket #154783

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Adds a dialog view to display all attributes assigned to the caches in a list (icon, number of occurrences, description). 
Use menu entry "manage caches" => "Show attribute overview" to open the overview.

image

### CODE REVIEW

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by eddiemuc** [comment]
retest this please

**Comment by moving-bits** [comment]
ok, let's see if restarting the executors has helped...

retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by eddiemuc** [comment]
> ok, let's see if restarting the executors has helped...

unfortuately it doesn't seem like it helped a lot

**Comment by moving-bits** [comment]
retest this please

**Comment by eddiemuc** [comment]
retest this please

**Comment by ztNFny** [comment]
can you decrease the attribute icon size? they are huge right now, like double the cache icon size. I'd suggest to size them like cache icons / like in cache details dialog

**Comment by ztNFny** [comment]
Could we order the attribute list? Some attributes are more interesting than others, e.g. tools required, tree climbing, ... than others (e.g. water nearby)

**Comment by Lineflyer** [comment]
> Could we order the attribute list? Some attributes are more interesting than others, e.g. tools required, tree climbing, ... than others (e.g. water nearby)

That's probably totally subjective. The best we can do is alphabetic I guess?

**Comment by SammysHP** [comment]
> > Could we order the attribute list? Some attributes are more interesting than others, e.g. tools required, tree climbing, ... than others (e.g. water nearby)
> 
> That's probably totally subjective. The best we can do is alphabetic I guess?

IMHO we should use the same order as in the cache details.

**Comment by fm-sys** [comment]
> 



> > > Could we order the attribute list? Some attributes are more interesting than others, e.g. tools required, tree climbing, ... than others (e.g. water nearby)
> > 
> > 
> > That's probably totally subjective. The best we can do is alphabetic I guess?
> 
> IMHO we should use the same order as in the cache details.

Either this, or sort by the number of occurrences. (The attribute, which is most often present in the list, is shown at the top) That would IMHO make even more sense...

**Comment by ztNFny** [comment]
From original issue: "Use-case is to cross-check whether any special devices/tools are required to bring when doing the tour specified by that list."

I'd describe it as "I have prepared a list of caches that I want to visit. Before I start onto the tour I want to check what expects me - what equipment I need to bring, how long it will take. To accomplish that I need a view of the combined caches attributes where I can quickly get an overview."

Let's dive deeper into the users need:
I need to be able to QUICKLY and RELIABLY see whether certain attributes are present. If attributes are in a random (non-static) order I have to search the list which has quite a high risk that I miss one - in any case it'll be slow, if they're static you learn where to look E.g. I know that "tools required" is the 3rd in the list, so I know I only check the top of the list.
-> requirement: they must be presented in a static order. 

Suggestion for the GUI: use the same dialog we already have in filter and put counts below the attribute images.
- Advantage: Static order, same order everywhere, easy to see what is and isn't in there
- Disadvantage: "Big" UI as always all attributes are shown (but still smaller than the current list)
image

-> requirement: The attributes should be presented in some logical order.
Here it get's a little harder as "logical" certainly depends on situation and cacher, but I think we should make the UI as accessible as possible. Both the original issue and my usecase above focus on "special devices/tools are required", so those certainly are very important to the cachers. But finding them in a very long list of attributes (doesn't just apply to this feature specifically but everywhere attributes are shown) is a PITA (try it yourself, go to the attribute filter and find the "tree climbing" attribute among all those same-looking black attributes, how long does it take you?!)

Suggestion: Group related attributes
Some groups I quickly identified (non-complete):
- Tools: Tools required, climbing, boat, tree climbing, flashlight, UV
- Duration: Takes less than an hour, <1km, <10km, >10km
- Location: Lost place, Private property, Dangerous area, Stealth required
- How to get there: Parking, Public transport, Horse, Snow mobile
- Surroundings: Toilets nearby, Tourist friendly, Phone

**Comment by moving-bits** [comment]
Thanks for all your feedbacks. Currently the icons are unscaled, only those attributes occurring in any of the list's caches are listed, and the order depends on the order in which they appear first.

I will scale-down the icon a bit, trying to match the size we have on the cache details page.

As it's useful to see the attribute description I would like to stay with a list view, and show only the attributes actually assigned to any of the list's caches.

Grouping is a nice idea, just need to find groups we can agree on. Within a group I would simply sort in alphabetical order. Additional (and last) group should list all attributes not included in any of the groups before (but still only those assigned to any of the list's caches), to get a complete list (and in case some attribute we might not consider "important" actually is for the use).

**Comment by ztNFny** [comment]
I took a stab at grouping them earlier: ("oconly" is not a group, it's just attributes I didn't look at yet)

├── duration
│   ├── hike_long.svg
│   ├── hike_med.svg
│   ├── hike_short.svg
│   ├── onehour.svg
│   └── parkngrab.svg
├── location
│   ├── abandonedbuilding.svg
│   ├── available.svg
│   ├── cliff.svg
│   ├── climbing.svg
│   ├── dangerousanimals.svg
│   ├── danger.svg
│   ├── fee.svg
│   ├── frontyard.svg
│   ├── hunting.svg
│   ├── kids.svg
│   ├── mine.svg
│   ├── night.svg
│   ├── poisonoak.svg
│   ├── seasonal.svg
│   ├── stealth.svg
│   └── winter.svg
├── oconly
│   ├── ads.svg
│   ├── aircraft.svg
│   ├── all_seasons.svg
│   ├── arithmetic.svg
│   ├── ask_owner.svg
│   ├── audio_cache.svg
│   ├── blind_people.svg
│   ├── breeding.svg
│   ├── byop.svg
│   ├── cave.svg
│   ├── compass.svg
│   ├── day.svg
│   ├── easy_climbing.svg
│   ├── geohotel.svg
│   ├── handicaching.svg
│   ├── hills.svg
│   ├── historic_site.svg
│   ├── historic.svg
│   ├── inside.svg
│   ├── investigation.svg
│   ├── in_water.svg
│   ├── kids_2.svg
│   ├── letterbox.svg
│   ├── link_only.svg
│   ├── magnetic.svg
│   ├── military_area.svg
│   ├── moving_target.svg
│   ├── munzee.svg
│   ├── nature_cache.svg
│   ├── no_gps.svg
│   ├── oc_only.svg
│   ├── offset_cache.svg
│   ├── other_cache.svg
│   ├── overnight.svg
│   ├── pedestrian_only.svg
│   ├── poi.svg
│   ├── puzzle.svg
│   ├── quick_cache.svg
│   ├── railway.svg
│   ├── safari_cache.svg
│   ├── shovel.svg
│   ├── snow_proof.svg
│   ├── specific_access.svg
│   ├── specific_times.svg
│   ├── survey_marker.svg
│   ├── swamp.svg
│   ├── syringe.svg
│   ├── tide.svg
│   ├── trackables.svg
│   ├── unknown.svg
│   ├── usb_cache.svg
│   ├── video_surveil.svg
│   ├── webcam.svg
│   └── wherigo.svg
├── surroundings
│   ├── campfires.svg
│   ├── camping.svg
│   ├── cow.svg
│   ├── dogs.svg
│   ├── firstaid.svg
│   ├── food.svg
│   ├── fuel.svg
│   ├── geotour.svg
│   ├── phone.svg
│   ├── picnic.svg
│   ├── powertrail.svg
│   ├── restrooms.svg
│   ├── scenic.svg
│   ├── thorn.svg
│   ├── ticks.svg
│   ├── touristok.svg
│   ├── water.svg
│   └── wheelchair.svg
├── tools
│   ├── flashlight.svg
│   ├── nightcache.svg
│   ├── partnership.svg
│   ├── rappelling.svg
│   ├── scuba.svg
│   ├── skiis.svg
│   ├── snowshoes.svg
│   ├── s_tool.svg
│   ├── swimming.svg
│   ├── teamwork.svg
│   ├── treeclimbing.svg
│   ├── uv.svg
│   ├── wading.svg
│   └── wirelessbeacon.svg
├── transport
│   ├── bicycles.svg
│   ├── hiking.svg
│   ├── horses.svg
│   ├── jeeps.svg
│   ├── motorcycles.svg
│   ├── parking.svg
│   ├── public.svg
│   ├── quads.svg
│   ├── rv.svg
│   ├── snowmobiles.svg
│   └── stroller.svg
└── type
    ├── boat.svg
    ├── bonuscache.svg
    ├── challengecache.svg
    ├── field_puzzle.svg
    ├── hqsolutionchecker.svg
    ├── landf.svg
    └── maintenance.svg

**Comment by moving-bits** [comment]
Scaling the image and adjusting some paddings leads to this view:

image

**Comment by ztNFny** [comment]
Not sure if a list will work, the number of attributes can grow quite quickly. But maybe with collapsible groups?

**Comment by moving-bits** [comment]
Ok, here's a new approach:
- Display a list of contained attributes, sorted by categories described above in https://github.com/cgeo/cgeo/pull/12140#issuecomment-978244882
- Then display a list of description texts (same order) + the number of occurrences
- list is scrollable
- category order is: tools, type, location, duration, surroundings, transport, oconly

image

So you will get all assigned attributes at a glance, in a defined order, and grouped by category. And if you want to see the details, you can still scroll further down a bit.

**Comment by ztNFny** [comment]
Looks great!

Do you need help with the oc attributes of did you assign them already? Should we use that group sorting everywhere?

**Comment by moving-bits** [comment]
So far I've put them in a separate block only, actually simply implemented your list so far, but would be nice to assign them to one of the other categories instead.

**Comment by ztNFny** [comment]
some of the OC attributes I can't find explained on OC. E.g. Munzee (ocacode 77) or ads (ocacode 78). Where are those coming from?

**Comment by ztNFny** [comment]
sorted them as best as I could without knowing where some of those are coming from
as for the group order I'd suggest: tools, duration, location, type, surroundings, transport
[attributes.txt](https://github.com/cgeo/cgeo/files/7611665/attributes.txt)

**Comment by ztNFny** [comment]
To see how those groups play out in practice I modified the attribute image creation script a bit to assign different background colors to the groups. Not something that should end up in the app (or should it??), so I'm attaching it here
[attributesIconsColor.zip](https://github.com/cgeo/cgeo/files/7611685/attributesIconsColor.zip)

**Comment by moving-bits** [comment]
Thanks for categorizing the "oconly" attributes. I have
- implemented the new categorization
- adapted the category order according to your proposal
- and added printing out the category names in the attribute list

image

**Comment by moving-bits** [comment]
retest this please

**Comment by bekuno** [comment]
> some of the OC attributes I can't find explained on OC. E.g. Munzee (ocacode 77) or ads (ocacode 78). Where are those coming from?

They are based on the ocapi attribute-definitions.xml.
For details please read https://github.com/cgeo/cgeo/blob/master/main/project/attributes_okapi/readme.txt

For `acode="A77"` you have the block in
https://github.com/cgeo/cgeo/blob/master/main/project/attributes_okapi/attribute-definitions.xml#L3998
and you find there that is used in "OCUK".

A short overview is in the generated https://github.com/cgeo/cgeo/blob/master/main/project/attributes_okapi/attrlist.txt.
The https://github.com/cgeo/cgeo/blob/master/main/project/attributes_okapi/attrlist.txt#L80
refers to `acode="A77"`.

**Comment by moving-bits** [comment]
retest this please

**Comment by ztNFny** [comment]
> and added printing out the category names in the attribute list

Not sure whether these terms are clear enough for users, it was just intended for myself.

How about
tools: Tools required
duration: Distance / Duration
location: Cache location
surroundings: Around the cache

Do you plan to order also the attributes on cache details screen by these groups? Not necessarily grouping, but at least ordering would be nice i guess

**Comment by moving-bits** [comment]
> How about tools: Tools required duration: Distance / Duration location: Cache location surroundings: Around the cache

I can update the terms accordingly

> Do you plan to order also the attributes on cache details screen by these groups? Not necessarily grouping, but at least ordering would be nice i guess

They are already ordered to this on this overview. If requested I can order them on cache details page accordingly, and we should probably do the same in the attribute filter screen.

**Comment by ztNFny** [comment]
> If requested I can order them on cache details page accordingly, and we should probably do the same in the attribute filter screen.

For filter dialog it'd also be nice to have the groups - but then the dialog gets even longer than it already is ... But then again, a list of "many" items just can't be short.
There was a Feature request about adding a search field to that dialog that could probably be adressed by grouping instead.

**Comment by kumy** [comment]
retest this

**Pull request merged**
