### PR TITLE
Add three dot image for cache popup (Fix #7251)

### LINKED ISSUE #7251: Three dot icon replaced by new icon on cache popup
##### Detailed steps causing the problem:
- Open map
- Click on a cache on the map to open the popup

##### Actual behavior after performing these steps:
The popup "action bar" now contains a new icon instead of the three-dot icon

##### Expected behavior after performing these steps:
Actually the new icon is pretty same style as the other icons.
So instead of havin the three-dot back here, I could also imagine to keep it but then maybe make it consistent in other activities.

##### Version of c:geo used:
2019.01.23-NB

##### Is the problem reproducible for you?
Yes

##### System information:
Android 8.0

##### Other comments and remarks:
Picture from @okainov

### PR DESCRIPTION
**Pull request by bekuno**
Fix #7251
Use also xml file generated in AS

### CODE REVIEW

**Comment by bekuno** [comment]
@Lineflyer Now the fresh build apk file from jenkins was fine for me.
Can you test it?
I'm not sure why that did not work without this vector xml.

**Comment by bekuno** [comment]
Rebased, squashed and tested the debug.apk with android 7.
Now the image is ok.
@moving-bits can you test this with some other API Versions with the emulator(s)?

**Comment by moving-bits** [comment]
@bekuno will do

But how can I fetch your branch to my local repo for testing? `git checkout --track bekuno/Three_dot_icon_replaced_by_new_icon_on_cache_popup` did not work (although I had created "bekuno" as alias for remote repo https://github.com/bekuno/cgeo before).

**Comment by SammysHP** [comment]
If you've added bekuno as a remote you can

```
git fetch bekuno Three_dot_icon_replaced_by_new_icon_on_cache_popup:bekuno/Three_dot_icon_replaced_by_new_icon_on_cache_popup
git checkout bekuno/Three_dot_icon_replaced_by_new_icon_on_cache_popup
```

If you have not added the remote yet, you can also directly fetch from GitHub:

```
git fetch https://github.com/bekuno/... Three_dot_icon_replaced_by_new_icon_on_cache_popup:...
```

**Comment by moving-bits** [comment]
@SammysHP Thx for the explanation, will try when back at the dev machine

**Comment by moving-bits** [comment]
I've tested with different API versions on the same (emulated) device - looks good. See screenshots attached to #7251.

**Comment by bekuno** [comment]
Yes, we need them.
I tried all from https://developer.android.com/studio/write/vector-asset-studio .
But this works not realy good. Using the support library it shows this:
screenshot_20190227-234233
Therfore it is the mixed method:
"Android 4.4 (API level 20) and lower doesn't support vector drawables. If your minimum API level is set at one of these API levels, you have two options when using Vector Asset Studio: generate Portable Network Graphic (PNG) files (the default) or use the Support Library.
For backward-compatibility, Vector Asset Studio generates raster images of the vector drawable. The vector and raster drawables are packaged together in the APK. You can refer to vector drawables as Drawable in Java code or @drawable in XML code; when your app runs, the corresponding vector or raster image displays automatically depending on the API level."

**Comment by bekuno** [comment]
> 
> 
> The PNGs for ldpi and xxxhdpi differ significantly from the other icons. I think that's not intended.

You are right.
These were not overwritten. Fixed now.

**Comment by UniQP** [comment]
Can you squash the commits into one?

**Comment by UniQP** [comment]
Sorry, the xxxhdpi icon size is already correct.

**Comment by bekuno** [comment]
> 
> 
>     * The ldpi icon has no transparent background (in contrast to the other icons)
> 
>     * The xxxhdpi icon has the wrong size (should be 96x96)

deleted the ldpi icon.
(after consulting rsudev)

**Comment by bekuno** [comment]
Image problem solved, squashed and successfully tested on my dev device.

**Pull request merged**
