### PR TITLE
Add URL to JakeDot in contributors

### PR DESCRIPTION
**Pull request by jakedot**
See title

### CODE REVIEW

**Comment by fm-sys** [comment]
Nice URL ;)

**Comment by bekuno** [comment]
This adress is fine as IDN.

But I propose to not use it in our international project, and instead stay to only use adresses with ASCII symbols (ACE).
This would be `xn--4ca.at` here.
Or use directly the forwarded adress (*@geocaching.com) or the github address.

**Comment by jakedot** [comment]
I will change the domain to jakedot.net or if one of the team could do it for me, I'm on vacation right now.

Thanks for your consideration.

**Comment by eddiemuc** [comment]
> I will change the domain to jakedot.net or if one of the team could do it for me, I'm on vacation right now.
> 
> My plan was to redirect ã.at to my GitHub profile.
> 
> Thanks for your consideration.

Done via GitHub app on my mobile.

By mistake I directly committed to master instead of a new branch + PR Sorry for that. But I figure the change is so small that I don't need to revert?

**Pull request closed without merging**
