### PR TITLE
WIP ease offline maps onboarding

### PR DESCRIPTION
**Pull request by moving-bits**
This is a WIP for beta testing only - do not merge

- integrate locally stored OSM map file into c:geo
  - move to map dir (cancellable)
  - set as current map source
- add preference link to download v3 OSM files
- improve handling of local files (forward detected file types internally, show an info message for the rest)
- smoke tested with different file types and Android versions from 4 to 10

For details and current status see #8180.

### CODE REVIEW

**Comment by moving-bits** [comment]
(resolved merge conflicts introduced by moving the non translatable strings)

**Comment by Lineflyer** [comment]
It makes IMHO no sense to make use of V3 maps as these maps are no longer updated since a longer time on the mapsforge servers. That will in return give complaints of outdated maps. 
You probably used that version to be compatible to WhereYouGo, but IMHO it makes more sense to rather make a c:geo solution with newer maps and wait with WhereYouGo until we have support for higher versions in there.

**Comment by moving-bits** [comment]
Ok, shall I make it download a v5 map instead, then, or shall I make this dependent on the "use old Mapsforge v3" setting?

**Comment by Lineflyer** [comment]
IMHO the setting to use old mpasforge is for experienced users (and might hopefully be removed rather soon).
Therefore I suggest to go for V5 as a straight default.

**Comment by moving-bits** [comment]
Rebased to current master and changed map dir to v5 maps.

**Comment by moving-bits** [comment]
Rebased to current master

**Pull request merged**
