### PR TITLE
Estimate device orientation and transform coords when upright (fix #7152)

### LINKED ISSUE #7152: Orientation in speech/voice output if phone is upright
##### Detailed steps causing the problem:
if i hold the phone horizontally I get the correct distance and directions like "200m 4 Uhr".

##### Actual behavior after performing these steps:
If the phone is upright I get arbitrary directions.

##### Expected behavior after performing these steps:
The phone should recognize that the phone is upright and switch from y-axis to z axis as "12 Uhr"
(x-axis being left/right if you look at the screen, y-axis being up-down and z front-back)

##### Version of c:geo used:
2018.09.17

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: GT-I9505 (jfltexx, samsung)
Android version: 5.0.1
Android build: LRX22C.I9505XXUHPK2
c:geo version: 2018.09.17
Google Play services: disabled - 13.2.80 (020308-211705629)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yyyy
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (1,3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (1,2 GB free) external non-removable
Geocache data: /storage/extSdCard/Android/data/cgeo.geocaching/files/GeocacheData (6,5 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (9,8 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins: none
--- End of system information ---
```

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

### PR DESCRIPTION
**Pull request by eddiemuc**
This PR attempts to fix #7152

### CODE REVIEW

**Comment by Lineflyer** [comment]
Let me set the "DO NOT MERGE" once again as we IMHO should wait until branched for beta.

**Comment by moving-bits** [comment]
@eddiemuc 
Same here: Just remove the "Do not merge / WIP" label when this PR is ready to be merged to `master`

**Comment by eddiemuc** [comment]
@moving-bits PR is ready for merge

**Comment by moving-bits** [comment]
@eddiemuc 
Both PR are merged now. Thanks for your contributions!

**Comment by eddiemuc** [comment]
@moving-bits Thanks a lot for your great support!

**Comment by moving-bits** [comment]
> @moving-bits Thanks a lot for your great support!

You're welcome. I love the spirit of the team behind c:geo!

**Pull request merged**
