### PR TITLE
TB namespace conflict workaround for disabled GK connector (rel. to #13097)

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Workaround for TB namespace conflicts for TB starting with "GK":
Leave out GeoKrety TB connector of list of TB connectors, if GeoKrety connector is not activated. In this case no GeoKrety TB will be searched for online.
Be aware, though, that Geokrety TB already stored locally in the database will still be retrieved by the TB search.

### CODE REVIEW

**Comment by moving-bits** [comment]
GK-related tests failing, which is to be expected when GK connector is not active.

@eddiemuc 
How can I activate GK connector for tests? (Would need to be done before `TRACKABLE_CONNECTORS` static variable gets set.)
Or can I check in code whether we are running tests currently, and always include the connector in this case?

**Comment by eddiemuc** [comment]
> How can I activate GK connector for tests? (Would need to be done before `TRACKABLE_CONNECTORS` static variable gets set.)
> Or can I check in code whether we are running tests currently, and always include the connector in this case?

In such situations I usually try to abstract out an initialization routine (or a constructor) where I can parameterize initialization. In your case e.g. using a boolean parameter to decide whether to initialize GK connector or not and call this in production with the "GK-activates" flag and for tests with a fixed value.

For more concrete advise I am afraid I would have to look deeper into this.

**Comment by moving-bits** [comment]
Thanks for your reply. In this case it's a static variable `TRACKABLE_CONNECTORS` in `connector/ConnectorFactory`, so not being called explicitly... 🤔. I was hoping for some "setting test prerequisites" routine where I can activate GeoKrety connector for tests, before variable `TRACKABLE_CONNECTORS` is set.

**Comment by eddiemuc** [comment]
But there has to be some variability to this? Because iiuc then the trackable must also be activateable/deactivateable at runtime when the user activates/deactivates the GK connector? (Or does this require a restart?)

**Comment by moving-bits** [comment]
Currently it requires a restart. But I guess one could make it a non-static variable instead, and pass a parameter to initialization routine whether to force all connectors or only active ones. Performance punishment of not using a static variable shouldn't be too harsh, and this would also save users the restart on changing the GeoKrety activity status (although this is done infrequently, probably). I'll pursue this approach further, thanks for your input.

**Comment by moving-bits** [comment]
Workaround is in the nightlies for quite some time, and IMHO it's not worth the effort to refactor TB handling to detect namespace conflicts (and present selection dialogs, if so) in case GK connector is activated, so I propose to close this issue.

**Pull request merged**
