### PR TITLE
fix #12383, fix #12596: add ability to scan and copypaste calculated waypoints

### LINKED ISSUE #12383: [Calculated Waypoints] Implement Scan Function trying to find calculated waypoints in listing and auto-create Calculated Waypoints for them
c:geo should provide a scanner function in the wqypoint tab (third button "Scan for Wqypoints" under "Add Wayppoint" and "Add current location") which scans the cache listing for potential calculated waypoints and offers to create them. Quite similar to "+ Scan" function for variables, but for waypoints

### LINKED ISSUE #12596: WP Calc - Allow C&P for whole coord at once
### Tell us your idea!

Maybe its possible and I just don't know how:

In cache listings I often find things like `N 51° 15. (B) (A+B) (C-A+B) E 06° 5C. (B) (A-B) (C)` which are well prepared fomulas for the new parser but the usage flow to get them there is not always easy.

### What solution would you suggest?

I would like to have the ability to copy & paste these in one batch to the WP calculator. 

One step further:
Ideally there could be some feature comparable to the "scan listing" which finds such strings and creates calculated waypoints for it.

### Is there an alternative?

At the moment you have to either copy latitude and logitude part after another, or copy the whole string and delete the non needed part in either field (lat/lon).

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #12383, fix #12596: add ability to scan and copypaste calculated waypoints

### CODE REVIEW

**Comment by eddiemuc** [comment]
Adds following option to scan for calculated waypoints:

image

image

image

Also adds the following copy&Paste option in calculated coordinate dialog:

image

image

Wrt algorithm to extract calculated waypoints from text/listing -> see #12383

**Comment by bekuno** [comment]
I propose to rename it to "Scan for waypoints to be calculated", as in the moment of scanning they are not calculated.

**Comment by eddiemuc** [comment]
> I propose to rename it to "Scan for waypoints to be calculated", as in the moment of scanning they are not calculated.

When the waypoint is created, c:geo will try to calculate it immediately (and store the resulting coordinate as the waypointÄs coord). This will work out only if all vars in the waypoint are already defined of course.

**Comment by bekuno** [comment]
> > I propose to rename it to "Scan for waypoints to be calculated", as in the moment of scanning they are not calculated.
> 
> When the waypoint is created, c:geo will try to calculate it immediately (and store the resulting coordinate as the waypointÄs coord). This will work out only if all vars in the waypoint are already defined of course.

From user point of view to the listing the waypoint has to be calculated. It will be (maybe) calculated by c:geo after the scan.

**Comment by ztNFny** [comment]
I agree that the wording should be changed. It's not a "calculated waypoint" in the listing but a formula.
How about "Scan for formulas" or "Scan for waypoint formulas"?

**Comment by eddiemuc** [comment]
> I agree that the wording should be changed. It's not a "calculated waypoint" in the listing but a formula. How about "Scan for formulas" or "Scan for waypoint formulas"?

That would be wrong, it specifically scans for calculateable coordinates (which may or may not contain formulas), not for standalone formulas. Eg. it will find `N40 12.ABC E11 34.DEF`, but it will not find a standalone `A+B/2` (that would be found by "scan" function in variable page).

For now I changed to `Scan for waypoints to be calculated` as proposed by @bekuno. To be honest, I really don't have a strong opinion about the exact wording :-)

**Comment by ztNFny** [comment]
>  That would be wrong, it specifically scans for calculateable coordinate

That's why I suggested "Scan for WAYPOINT formulas" though?!

"to be calculated" sounds awkward to me, like trying to avoid the word "formula" no matter what. If I wouldn't know what it does I'd have a hard time figuring it out. 
Also looking at the branch name "scan formula" seems like an obvious candidate.

As for the scan function in variables page, I actually don't see any usecase for that once we have this feature. Can't think of any cache using formulas for something that's not coordinates.

**Comment by eddiemuc** [comment]
> > That would be wrong, it specifically scans for calculateable coordinate
> 
> That's why I suggested "Scan for WAYPOINT formulas" though?!

Ok, that's a fair point. How do you want to decide about this? As mentioned before, I don't really have a stroing opinion here. @bekuno would you approve (since the initial request came from you)?
 
> Also looking at the branch name "scan formula" seems like an obvious candidate.

Ah, my branch names are usually not a good indicator for these kind of things :-)

> As for the scan function in variables page, I actually don't see any usecase for that once we have this feature. Can't think of any cache using formulas for something that's not coordinates.

I had in mind things like e.g. in GC5JAQ6. Deep down in the listing you find (sorry, it's german): (peilt von hier...) `[X + Y + 7] Meter in Richtung [5*X + Y + 7] Grad`. Obviously this use case is discussable, but maybe in a separate issue?

**Comment by bekuno** [comment]
>> That's why I suggested "Scan for WAYPOINT formulas" though?!

> Ok, that's a fair point. How do you want to decide about this? As mentioned before, I don't really have a stroing opinion here. @bekuno would you approve (since the initial request came from you)?

Approved, sounds good to me and is shorter.

**Comment by eddiemuc** [comment]
> > > That's why I suggested "Scan for WAYPOINT formulas" though?!
> 
> > Ok, that's a fair point. How do you want to decide about this? As mentioned before, I don't really have a stroing opinion here. @bekuno would you approve (since the initial request came from you)?
> 
> Approved, sounds good to me and is shorter.

Ok, changed in PR

image

**Pull request merged**
