### PR TITLE
switch several calls from http to https

### PR DESCRIPTION
**Pull request by ztNFny**
as discussed in the call let's try switching all the http urls that also work with SSL to https

### CODE REVIEW

**Comment by ztNFny** [comment]
Terracaching should be fixed. I have no idea about those Twitter tests though, can't see that I touched anything remotely related to those?!

**Comment by fm-sys** [comment]
The Twitter tests are failing also on our master branch:

https://ci.cgeo.org/job/cgeo%20CI%20-%20Commit%20build/38/

**Comment by fm-sys** [comment]
Commit https://github.com/cgeo/cgeo/commit/20812da80144772a60d6b8ca89c8bcbcb7c88596 is the first one where the test got broken...

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Comment by ztNFny** [comment]
Needs to be rebased

**Comment by Lineflyer** [comment]
retest this please
Again a false positive result on CI (meaning no tests have been executed).

**Comment by Lineflyer** [comment]
retest this please

**Pull request merged**
