### PR TITLE
Fix some accessibility issues

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
On publishing a new release Play Store does some prelaunch tests. One major part (at least for us) is about accessibility issues. Sadly I found no way to export this report, so I start a PR here to fix them one-by-one. This is a first start, more to come.

### CODE REVIEW

**Comment by bekuno** [comment]
Please have a look at the CI lint results.

The https://ci.cgeo.org/job/cgeo-CI_PR-build/9085/androidLintResult/new/ shows 2 new entries.

One of them is `The resource `R.string.google_maps_style_details` appears to be unused`.
The string is in your strings.xml, but not the line in GoogleMapsThemeHelper.java, if I see it correct.
(The souece was https://github.com/cgeo/cgeo/commit/589b25c3653b7d44f52ac2496cf75dbb5f067253)

**Comment by moving-bits** [comment]
Removed the strings that are no longer in use

**Comment by bekuno** [comment]
retest this please

**Comment by ztNFny** [comment]
This PR needs to be partially reverted.
It added "android:hint" to many buttons - I guess what it wanted to do is add "android:tooltipText". "hint" is intended for text input fields as the "Hint text to display when the text is empty." On a button hint never makes any sense.

Those "hint"s are a visible element of the buttons so now most buttons look like this:
image


@moving-bits as I don't know what the Play Store Console reported could you please share why you added hint?

**Comment by ztNFny** [comment]
https://github.com/cgeo/cgeo/pull/15944 converts those hints into tooltipText - assuming that was the intended change

**Pull request merged**
