### PR TITLE
Fix bug which causes every second route segment to be lost

### LINKED ISSUE #14028: GPX Routes no longer displayed correctly.
### Describe your problem!

I use the GME extension on "Browse maps" on the website to draw a route I wish to follow.
Since the latest release the route is not shown correctly. 
In fact, as far as I can tell, only every other segment of the route is shown.

### How to reproduce?

1. Draw a route using GME on the website (Haven't tried any other source) and save GPX file
2. Open c:geo and goto map page
3. Goto "Routes/tracks"
4. use "Load track/route from GPX" to load your GPX file

### Actual result after these steps?

Route is shown disjointed, see screenshots below

### Expected result after these steps?

Full route shown

### Reproducible

Yes

### c:geo Version

2023.02.12

### System information

```text
## System information

c:geo version: 2023.02.12

Device:
-------
- Device type: M2101K6G (sweet_eea, Redmi)
- Available processors: 8
- Android version: 12
- Android build: SKQ1.210908.001 test-keys
- Screen resolution: 1080x2177px (392x791dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 23.06.16 (190400-510240997)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:229
- Set language: en_GB (system default)
- System date format: dd/MM/y
- Time zone: GMT
- Debug mode active: no
- Last backup: 20 Jan, 19:45
- Routing mode: Off
- Live map mode: false
- OSM multi-threading: true / threads: 4
- Map: Great-Britain_OAM_V5_Dec2022 (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:OpenStreetMaps/Great-Britain_OAM_V5_Dec2022.map
  - Atts: VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2022
  - Theme: ElevateTheme_V5.zip:Elevate.xml

Filters:
-------
- Hide waypoints: -
- LIVE: No Advlabs* ([No Advlabs*:inconclusive=false:advanced=true]AND(type:VIRTUAL:MULTI:CITO:USER_DEFINED:WHERIGO:EVENT:EARTH:TRADITIONAL:MYSTERY:LETTERBOX:WEBCAM;status:exclude_archived))
- OFFLINE: None ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Stored Filters (#1):
- No Advlabs: [No Advlabs:inconclusive=false:advanced=true]AND(type:VIRTUAL:MULTI:CITO:USER_DEFINED:WHERIGO:EVENT:EARTH:TRADITIONAL:MYSTERY:LETTERBOX:WEBCAM;status:exclude_archived))

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
- Geocaching.com date format: dd MMM yy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2022-10-04 09-45)
- Last successful login on geocaching.com: 2023-02-25 13-22
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions
-------
-android.permission.ACCESS_COARSE_LOCATION:: granted
-android.permission.ACCESS_FINE_LOCATION:: granted
-android.permission.READ_CONTACTS:: DENIED
-android.permission.READ_EXTERNAL_STORAGE:: DENIED

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (40.7 GB free) v3 internal isDir(11 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (40.7 GB free) v3 internal isDir(11 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (40.7 GB free) v3 external non-removable isDir(2199 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (40.7 GB free) v3 internal isDir(3 entries)
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=12, dirs:>=13, totalFileSize:>=180.3 MB, free space: 40.7 GB, files on device: 13511677)
  - OFFLINE_MAPS: /OpenStreetMaps (User-Defined)[/OpenStreetMaps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps/document/primary%3AOpenStreetMaps, Av:true, files:7, dirs:2, totalFileSize:2.7 GB, free space: 40.7 GB, files on device: 13511677)
  - OFFLINE_MAP_THEMES: /OpenStreetMaps/_themes (Default)[/OpenStreetMaps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps/document/primary%3AOpenStreetMaps%2F_themes, Av:true, files:2, dirs:0, totalFileSize:948.5 KB, free space: 40.7 GB, files on device: 13511677)
  - OFFLINE_MAP_SHADING: /OpenStreetMaps/_hgt (Default)[/OpenStreetMaps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps::/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps/document/primary%3AOpenStreetMaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 40.7 GB, files on device: 13511677)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:6, dirs:0, totalFileSize:636.2 KB, free space: 40.7 GB, files on device: 13511677)
  - GPX: /My Documents/SyncedWithGoogle/GPX (User-Defined)[/My Documents/SyncedWithGoogle/GPX[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX/document/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX, Av:true, files:24, dirs:2, totalFileSize:73.3 MB, free space: 40.7 GB, files on device: 13511677)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=10, dirs:>=6, totalFileSize:>=298.9 MB, free space: 40.7 GB, files on device: 13511677)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 40.7 GB, files on device: 13511677)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 40.7 GB, files on device: 13511677)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81.2 KB, free space: 40.7 GB, files on device: 13511677)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 40.7 GB, files on device: 13511677)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 40.7 GB, files on device: -1)
- Map render theme path: ElevateTheme_V5.zip:Elevate.xml
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #3
  - content://com.android.externalstorage.documents/tree/primary%3AMy%20Documents%2FSyncedWithGoogle%2FGPX (26 May 2021, 15:31):RW
  - content://com.android.externalstorage.documents/tree/primary%3AOpenStreetMaps (7 May 2021, 19:56):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (7 May 2021, 19:45):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v99, Size:61.2 MB) on user storage

--- End of system information ---
```

### Additional Information

This is the route loaded into c:geo

Screenshot_2023-02-25-15-42-21-295_cgeo geocaching

This is the same GPX file loaded into "AlpineQuest" App.

Screenshot_2023-02-25-15-43-08-774_psyberia alpinequest full

GPX File attached (Had to zip it up)

[GMERoute.zip](https://github.com/cgeo/cgeo/files/10831612/GMERoute.zip)

### PR DESCRIPTION
**Pull request by fm-sys**
Fix bug which causes every second route segment to be lost. (fix #14028)

@eddiemuc as you are working in this area currently, would you mind a short review?

### CODE REVIEW

**Comment by eddiemuc** [comment]
Hi @fm-sys , thanks for fixing this bug which was clearly caused by my changes (mea culpa).

The change however must be applied to `release`. I read your comment on #14028, easiest way to solve this is probably to code the change again on a new PR. Question: should I provide a PR for `release`  or will you do that?

**Comment by moving-bits** [comment]
Thank you for diving into this. We do have a ticket on support that looks to have the same cause. Only one so far, AFAICS.

**Comment by fm-sys** [comment]
@eddiemuc I can provide a new PR. However, it would be nice if someone could handle the resulting merge conflicts for me :)

**Comment by fm-sys** [comment]
Let's close in favor of #14030

**Comment by eddiemuc** [comment]
> @eddiemuc I can provide a new PR. However, it would be nice if someone could handle the resulting merge conflicts for me :)

Should not be too hard, IF git is a clever as is claims to be :-)

**Pull request closed without merging**
