### PR TITLE
fix #13938: contentstorage: correctly catch illegalargumentexception in ensureFolder

### LINKED ISSUE #13938: SecurityException in DocumentContentAccessor
### Describe your problem!

Reported for 2023.01.30-RC as well as for 2022.12.21 (not earlier)

5 events
4 users
Android 11,12,13

### How to reproduce?

Unclear

### Actual result after these steps?

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3760)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3934)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2287)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:210)
  at android.os.Looper.loop (Looper.java:299)
  at android.app.ActivityThread.main (ActivityThread.java:8261)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:556)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1045)
Caused by java.lang.IllegalArgumentException:
  at cgeo.geocaching.storage.DocumentContentAccessor.queryDir (DocumentContentAccessor.java:408)
  at cgeo.geocaching.storage.DocumentContentAccessor.findCreateSubdirectory (DocumentContentAccessor.java:361)
  at cgeo.geocaching.storage.DocumentContentAccessor.getSubdirUri (DocumentContentAccessor.java:344)
  at cgeo.geocaching.storage.DocumentContentAccessor.getFolderUri (DocumentContentAccessor.java:311)
  at cgeo.geocaching.storage.DocumentContentAccessor.ensureFolder (DocumentContentAccessor.java:252)
  at cgeo.geocaching.storage.ContentStorage.ensureFolder (ContentStorage.java:134)
  at cgeo.geocaching.storage.ContentStorage.ensureFolder (ContentStorage.java:124)
  at cgeo.geocaching.utils.BackupUtils.getNewBackupFolder (BackupUtils.java:755)
  at cgeo.geocaching.utils.BackupUtils.backupInternal (BackupUtils.java:536)
  at cgeo.geocaching.utils.BackupUtils.backup (BackupUtils.java:369)
  at cgeo.geocaching.MainActivity.onCreate (MainActivity.java:358)
  at android.app.Activity.performCreate (Activity.java:8238)
  at android.app.Activity.performCreate (Activity.java:8206)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1329)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3733)
Caused by java.lang.SecurityException:
  at android.os.Parcel.createExceptionOrNull (Parcel.java:2426)
  at android.os.Parcel.createException (Parcel.java:2410)
  at android.os.Parcel.readException (Parcel.java:2393)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:190)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:142)
  at android.content.ContentProviderProxy.query (ContentProviderNative.java:481)
  at android.content.ContentResolver.query (ContentResolver.java:1219)
  at android.content.ContentResolver.query (ContentResolver.java:1151)
  at android.content.ContentResolver.query (ContentResolver.java:1107)
  at cgeo.geocaching.storage.DocumentContentAccessor.queryDir (DocumentContentAccessor.java:395)
```

### Expected result after these steps?

Normal operation

### Reproducible

Unclear

### c:geo Version

2023.01.30-RC

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #13938: contentstorage: correctly catch illegalargumentexception in ensureFolder

### CODE REVIEW

**Comment by eddiemuc** [comment]
...and again, CI failure is unrelated

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
