### PR TITLE
Make "some seconds" more natural english

### PR DESCRIPTION
**Pull request by akkatracker**
Noticed this when out caching today - this does not come across as fluent English.

### CODE REVIEW

**Comment by samueltardieu** [comment]
ok to test

**Comment by samueltardieu** [comment]
**Note**: merging this will likely invalidate all translations. It should be merged only when there is time to update translations before a release, for example just after a release.

**Comment by rsudev** [comment]
I'd say currently is not a bad point in time to merge it on master, as a call for translations for the next feature release is still due.

**Comment by samueltardieu** [comment]
@rsudev Done.

@akkatracker Thanks for your contribution.

**Comment by akkatracker** [comment]
@samueltardieu no worries - enjoy using the app so it's the least I can do.

**Pull request merged**
