### PR TITLE
Fix #6725 Variable not shown alpabetically

### LINKED ISSUE #6725: Variable not shown alpabetically
##### Detailed steps causing the problem:
- Today I used the WP Calc to enter the formula given in GC2DMGW
- In this formula the variables are not appearing in alphabetical order
- I entered the formulas in the sequence as given in the cache description

##### Actual behavior after performing these steps:
The lower case variables are sorted in the order of appearance, which makes it more difficult to fill them with values later on.

##### Expected behavior after performing these steps:
The lower case variables should be sorted alpabetically.

##### Version of c:geo used:
2017.09.04-NB

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Screenshot:
screenshot_20170905-110909

### PR DESCRIPTION
**Pull request by S-Bartfast**
Sort the list variables before they are added to the variable grid.

### CODE REVIEW

**Comment by kumy** [comment]
Jenkins test this please

**Comment by Lineflyer** [comment]
It seems this also contains #6729

**Comment by kumy** [comment]
@Lineflyer those are the exact same commit, just merge them in the natural order, and git should be fine

**Comment by S-Bartfast** [comment]
> It seems this also contains #6729

Oh, does it.
The next one's probably going to contain 3 branches them :blush:

Man, still have much to learn when it comes to Git.

**Comment by pstorch** [comment]
@S-Bartfast when you create a new branch, make sure you checked out master first.

**Comment by S-Bartfast** [comment]
Yeah, shooda dun dat!
:blush:

**Comment by pstorch** [comment]
I think you can create new branches from master and cherry pick only the one relevant commit.

**Comment by pstorch** [comment]
Besides the two commits there are also two minor issues reported by codacy. It was disabled for a while. I re-enabled it.

**Comment by kumy** [comment]
Jenkins test this please

**Comment by pstorch** [comment]
@S-Bartfast do you need some help with your pull requests? I can try to help, if you like.

**Comment by S-Bartfast** [comment]
Sorry, I've been rather sick the last week, but am finally pulling through now.
> @S-Bartfast do you need some help with your pull requests? I can try to help, if you like.

I'm not exactly sure what the hold up is, I was expecting this to go through weeks ago.  I can only assume someone forestalled it for some reason but I'm not sure why.  Is there any reason this isn't getting accepted?

**Comment by pstorch** [comment]
@S-Bartfast sorry to hear. Hope you are well now.  Just see the comments. There are codacy issues and the PRs contain unrelated commits. If you need help to sort out the commits, I can assist.

**Comment by S-Bartfast** [comment]
> If you need help to sort out the commits, I can assist.

Yeah, I'm a but lost as to what's going on here.

So I thought I had addressed most of the Codacy issues.  In fact I had thought there were only 2 left that weren't relay worth fixing.  Have I missed some others?

**Comment by S-Bartfast** [comment]
Okay, I think I have moved everything into the "SaveButton" request.

**Pull request closed without merging**
