### PR TITLE
Fix filtering caches on live map

### LINKED ISSUE #15470: [Unified Map] "Long-Click-Filter" not applied
### Describe your problem!

Saved filters will not be applied to UM, if activated via LongClick on Filter icon.

### How to reproduce?

1. activate ``Map Sources`` => ``[X] Use Unified Map``
2. open Map
3. long click on Filter icon => ``Clear``
4. all caches will be shown (as expected)
5. long click on Filter icon => select any saved filter (which should make a difference WRT number of visible caches)

### Actual result after these steps?

No change WRT the number of caches shown, filter has not been applied.

### Expected result after these steps?

Filter should immediately be applied.

### Reproducible

Yes

### c:geo Version

2024.03.16-NB-4f30164

### System information

_No response_

### Additional Information

If afterwards you open the filter definition and just click [Ok], the filter will eventually be applied.

### PR DESCRIPTION
**Pull request by murggel**
## Description

As of my limited understanding of the filtering and loading stuff of caches - but debugging and trying:
when on `UnifiedMapActivity::reloadCachesAndWaypoints`  not only the `loadInBackgroundHandler` is initialized for `UMTT_PlainMap`
but the map data is refreshed (filter on `viewModel.caches` is applied (again(?)) via `UnifiedMapActivity::refreshMapData`) everything works fine.

## Related issues

fix #15470

## Additional context

This PR is not a fix for #15614

### CODE REVIEW

**Comment by murggel** [comment]
@eddiemuc  / @moving-bits please check if my assumption and fix is correct

**Comment by murggel** [comment]
Failing tests are not related to this change

**Comment by murggel** [comment]
If the fix is correct, the same can be applied for `UMTT_SearchResult` to fix #15557

**Comment by ztNFny** [comment]
When mapping 1 offline list this PR causes it to show caches from all offline lists - akin to enabling live mode on offline map.

**Comment by murggel** [comment]
Ok thanks, didn't try that, will check for it

**Comment by murggel** [comment]
> When mapping 1 offline list this PR causes it to show caches from all offline lists - akin to enabling live mode on offline map.

Hopefully fixed with the last commit

@ztNFny can you please yest / try again?

**Comment by ztNFny** [comment]
Looks good

**Comment by murggel** [comment]
Ready for review

**Comment by bekuno** [comment]
retest this please

**Comment by ztNFny** [comment]
@moving-bits can you please merge this?

**Comment by moving-bits** [comment]
Let's give it a try in the nightlies. Thanks @murggel for looking into this.

**Comment by MagpieFourtyTwo** [comment]
Seems to work now ...

**Pull request merged**
