### PR TITLE
DO NOT MERGE: Mapsforge 6

### PR DESCRIPTION
**Pull request by rsudev**
Finally I was able to get most of the things I deem required for a first version implemented.
This implements a new map, currently solely based on mapsforge 0.6
It also moves the target SDK to 23, as well as the AppCompat version.
Besides replicating the core features of the existing map does it better (IMO) handle situations where you switch a list to live mode (filter out found caches for the live-loaded ones while retaining those on the list) and multiple markers in the roughly the same place (popup list to select the one to open).
The new map is just a normal navigation target (and can as such also be used as default navigation). Additionally I added a setting to activate it for live- and list-maps as well.
I would like to get feedback regarding the overall architecture of the new map and suggestions on how to proceed further (add this as an experimental feature, first try to do the same for google maps v2 and unify the implementations again, ...)

### CODE REVIEW

**Comment by Lineflyer** [comment]
Thanks @rsudev !
I highly appreciate your initiative for this. This and new Google Maps are long overdue IMHO.

**Comment by rsudev** [comment]
I start another try to get some feedback on how to proceed with a move to new maps.

This PR contains three commits and I bundled them up, as the first two make no sense without the third, but are separate nevertheless.

Switch to target SDK 23:
To achieve that, I needed to extend the fallback-behaviour on the map (selfmade actionbar, etc) to all Android versions and to adapt some icon and theme references. I assume there will still be some glitches in the styles here and there, otherwise it went smoothly

Move the old mapsforge library to a new namespace:
I rebuild the mapsforge 0.3 version moving everything inside to a new namespace. According to my tests it works as before. This is required, if we want to have the new and the old map side-by-side until the new map is ready for prime-time.

Initial implementation of a new map based on mapsforge 0.6:
I mainly re-implemented the map, re-using large pieces of the current implementation, adapting it to the new map, but at the same time, I put some new concepts in place, which in turn allowed to address some issues and requested features.
As the new Api has a Layer for every marker, I designed layer-bundles, to be able to handle the different sources for the caches to display in a consistent fashion. So now it is possible, to show all caches from a list, but at the same time filter the found ones on the live layer, in case it is activated.
I also introduced an empty 'catch' layer for touch events, allowing me to collect all touched markers and show them as a selection list to the user, thus addressing the areas with many overlapping caches.
To integrate that, the new map is available as normal navigation target, but additionally you can check in the system settings whether it should also replace the live and list maps.

If the impact on the 'normal' map (regarding the old action bar) is ok, this could be merged in order to test this new feature, complete the missing bits (some map-menu-items still don't work) and try to get an implementation for gmaps v2 up and running alongside as well.

@Bananeweizen @samueltardieu @SammysHP any thoughts on this?

**Comment by samueltardieu** [comment]
When I try to use the "New map" navigation target, I get

```
01-20 01:05:14.106 E/cgeo    (17300): [main] UncaughtException
01-20 01:05:14.106 E/cgeo    (17300): java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
01-20 01:05:14.106 E/cgeo    (17300): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
01-20 01:05:14.106 E/cgeo    (17300): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
01-20 01:05:14.106 E/cgeo    (17300): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-20 01:05:14.106 E/cgeo    (17300): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
01-20 01:05:14.106 E/cgeo    (17300): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-20 01:05:14.106 E/cgeo    (17300): 	at android.os.Looper.loop(Looper.java:148)
01-20 01:05:14.106 E/cgeo    (17300): 	at android.app.ActivityThread.main(ActivityThread.java:5466)
01-20 01:05:14.106 E/cgeo    (17300): 	at java.lang.reflect.Method.invoke(Native Method)
01-20 01:05:14.106 E/cgeo    (17300): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-20 01:05:14.106 E/cgeo    (17300): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-20 01:05:14.106 E/cgeo    (17300): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
01-20 01:05:14.106 E/cgeo    (17300): 	at java.io.File.fixSlashes(File.java:183)
01-20 01:05:14.106 E/cgeo    (17300): 	at java.io.File.<init>(File.java:130)
01-20 01:05:14.106 E/cgeo    (17300): 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.getMapFile(NewMap.java:612)
01-20 01:05:14.106 E/cgeo    (17300): 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onStart(NewMap.java:445)
01-20 01:05:14.106 E/cgeo    (17300): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
01-20 01:05:14.106 E/cgeo    (17300): 	at android.app.Activity.performStart(Activity.java:6268)
01-20 01:05:14.106 E/cgeo    (17300): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
01-20 01:05:14.106 E/cgeo    (17300): 	... 9 more
```

Do I need to use an offline map, or can it be used online too?

**Comment by rsudev** [comment]
In the current implementation you must have an offline map (and configured an offline map before using it the first time).
If the new version of the library still supports online maps I have not checked yet.

**Comment by rsudev** [comment]
Closing here for the moment. Feel free to still add feedback. I'll try to prepare a version which is perhaps mergeable as experimental feature to master.

**Pull request closed without merging**
