### PR TITLE
new icon for cache download in progress

### LINKED ISSUE #13090: Create a better "sync ongoing"-marker
@ztNFny I would be glad if you could design a better "sync ongoing"-marker.

_Originally posted by @fm-sys in https://github.com/cgeo/cgeo/issues/13084_

### PR DESCRIPTION
**Pull request by ztNFny**
fixes #13090

image

### CODE REVIEW

**Comment by ztNFny** [comment]
GC3FJ5F Herminghauspark is causing the fail

**Comment by ztNFny** [comment]
@Lineflyer you modified the GC listing without modifying the data in src-android/cgeo/geocaching/test/mock/GC3FJ5F.java
Can you take care of updating that?

**Comment by Lineflyer** [comment]
@ztNFny I did try, see #13102 but thats also failing

**Comment by fm-sys** [comment]
retest this please

**Pull request merged**
