### PR TITLE
check for missing routing data for current viewport (fix #12172)

### LINKED ISSUE #12172: add BRouter Download Manager functionality
The BRouter has the function to select the routing data region based on a world map.
We have now in c:geo only an automatic download. For preparing a trip outside the home region it would be fine to have such a download manager possibility.

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
- adds a menu entry "Check for missing routing data" to the map
- if selected, c:geo checks whether routing data is available for the whole viewport currently visible, and offers to download missing files
- checking is done in background
- if you select to download missing files, this triggers our regular integrated downloader

image.image

### CODE REVIEW

**Comment by bekuno** [comment]
Retest this please

**Comment by ztNFny** [comment]
Menu item text is broken:
image

There's a crash when clicking the download menu item somewhere where no routing data is available - e.g. in the middle of the ocean. Logcat:
```
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching E/cgeo: [network--1] checking W45_N40.rd5: not available!
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching W/System.err: io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.util.ConcurrentModificationException
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching W/System.err:     at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:327)
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-12-29 19:41:28.280 29446-29472/cgeo.geocaching W/System.err: Caused by: java.util.ConcurrentModificationException
2021-12-29 19:41:28.281 29446-29472/cgeo.geocaching W/System.err:     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
2021-12-29 19:41:28.281 29446-29472/cgeo.geocaching W/System.err:     at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
2021-12-29 19:41:28.281 29446-29472/cgeo.geocaching W/System.err:     at cgeo.geocaching.maps.MapUtils.lambda$checkRoutingData$0(MapUtils.java:138)
2021-12-29 19:41:28.281 29446-29472/cgeo.geocaching W/System.err:     at cgeo.geocaching.maps.-$$Lambda$MapUtils$r3iocCbVSHaQy8Drh-TKqFldp7I.run(Unknown Source:14)
2021-12-29 19:41:28.281 29446-29472/cgeo.geocaching W/System.err:     at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:70)
2021-12-29 19:41:28.281 29446-29472/cgeo.geocaching W/System.err:     at cgeo.geocaching.utils.-$$Lambda$AndroidRxUtils$bqzWo9nlvU86BvboB-9jhDWp5vc.run(Unknown Source:4)
2021-12-29 19:41:28.281 29446-29472/cgeo.geocaching W/System.err:     at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
2021-12-29 19:41:28.281 29446-29472/cgeo.geocaching W/System.err: 	... 5 more
2021-12-29 19:41:28.281 29446-29472/cgeo.geocaching W/cgeo: [network--1] UncaughtException
    io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.util.ConcurrentModificationException
        at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:327)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
        at cgeo.geocaching.maps.MapUtils.lambda$checkRoutingData$0(MapUtils.java:138)
        at cgeo.geocaching.maps.-$$Lambda$MapUtils$r3iocCbVSHaQy8Drh-TKqFldp7I.run(Unknown Source:14)
        at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:70)
        at cgeo.geocaching.utils.-$$Lambda$AndroidRxUtils$bqzWo9nlvU86BvboB-9jhDWp5vc.run(Unknown Source:4)
```

I'd recommend placing this in the "Map view" menu, together with "<Download offline map>" instead of the "normal" menu - or in Map Quick settings, next to the Routing options.
image

**Comment by moving-bits** [comment]
> Menu item text is broken: 

arg, editor's auto expansion feature - `check_tiles_menu` has same beginning as `check_tiles_missing`

> There's a crash when clicking the download menu item somewhere where no routing data is available - e.g. in the middle of the ocean.

Good catch. Was supposed to be handled (checking requested tiles against those available on the server), but obviously there's some other obstacle hitting me here.

Will look into both.

**Comment by moving-bits** [comment]
Fixed both errors and added a warning for unsupported regions:

image

**Comment by moving-bits** [comment]
failing test is unrelated (triggered by outage of opencaching.us)

**Pull request merged**
