### PR TITLE
Use improved hints for equation content

### PR DESCRIPTION
**Pull request by Lineflyer**
showing more of the supported calculation operators

### CODE REVIEW

**Comment by S-Bartfast** [comment]
Just wondering what it is about these hints that you think is an improvement.

I mean no offence but I certainly put thought into the original hints and decided on them for a few reasons.  In what way is it that you think these are better?

In particular, I used the "a^2 + b^2" to demonstrate that 'powers' were available.  While I was concerned that the '^' character may appear foreign to some I still elected to use it as I figured that even if the meaning of the character was lost it would still look sufficiently 'maths-ie' to convey the meaning.  I did actually want to show bracket priority as well but ultimately decided against it in favour of the Pythagorean formula as it is such a famous and elegant equation 👍.  Is there any particular advantage to "(a+b)*c/d" other than it showing bracketing?
 
As for the spaces around the '+' signs, that was also intentional; partly to add visual neatness to the layout but also because the 'hint' seems to set the minimum width of the field and there is a subtle bug that seems to exhibit itself on occasion if the fields are too narrow.

**Comment by Lineflyer** [comment]
>  Is there any particular advantage to "(a+b)*c/d" other than it showing bracketing?

The main purpose was to present all available operators. But you are right I forgot `^` to make it complete (and `%` but that would be to special I think).
I came to this thought, because I showed the calculator to a friend and he failed to understand what to fill into the fields. He was not familiar with the `^` operator thus not got the hint, that he can actually insert an equation here.

> As for the spaces around the '+' signs, that was also intentional; partly to add visual neatness to the layout but also because the 'hint' seems to set the minimum width of the field and there is a subtle bug that seems to exhibit itself on occasion if the fields are too narrow.

Good to know...in this case we should not change it but maybe also could show the possible operators here.

>  in favour of the Pythagorean formula as it is such a famous and elegant equation

:) But that was exactly what confused the non-mathematical expert user, whom I showed the calculator.
And to be honest, only very few of the caches I have come across are using powers in their formulas.

**Comment by S-Bartfast** [comment]
> I came to this thought, because I showed the calculator to a friend and he failed to understand what to fill into the fields. He was not familiar with the ^ operator thus not got the hint, that he can actually insert an equation here.

That's a shame.  I was really hoping it would be more or less intuitive.  If it's not though, than sure, I'd advocate making it simpler.

I'm actually not such a fan of trying to turn the hint test into a substitute manual.  If the original was unintuitive I'd lean more toward making it less complicated and instructional rather than more.  If `"a^2 + b^2"` was confusing I'd prefer to simply reduce it to just `"a + b"` (assuming "a + b" is a long enough string to not cause problems).  If "a + b" is too short then possibly we could use something like `"2*(a+b)"` but `"(a+b)*c^d/e"` just offends my sense of aesthetic :p

As for `"(5+4-3)*2/3"`.  I mean really??  I'm not going to put my foot down about it or anything but seriously?  `"2 + 2"` is the very epitome of a simple truth ;)

You know, we're not trying to write a manual here or anything, it's just a hint to suggest what to enter :) :)

**Comment by Lineflyer** [comment]
> You know, we're not trying to write a manual here or anything, it's just a hint to suggest what to enter :) :)

Thanks, got your point. Maybe I was a little overinspirated.

So how about keeping it simple and having
`a + b` and
`2 + 2` ?

That will show that operators can be used on both, and the first one supports variables as well.

**Comment by S-Bartfast** [comment]
That looks good to me 👍 

By the way, I have created a little 'help' button (for #6664) which opens a HTML page where we can be more detailed about accepted operators and so forth.  I'm struggling to workout exactly what to say in the help page but the button itself can actually be seen in the top left corner of the screenshots I uploaded for #6687.  I'll discuss it more fully in #6664 though when I have a page worth showing.

**Comment by Lineflyer** [comment]
> That looks good to me 

OK, I will change the PR accordingly and merge it.

> By the way, I have created a little 'help' button (for #6664) which opens a HTML page where we can be more detailed about accepted operators and so forth. I'm struggling to workout exactly what to say in the help page but the button itself can actually be seen in the top left corner of the screenshots I uploaded for #6687. I'll discuss it more fully in #6664 though when I have a page worth showing.

Feel free to provide it even if not complete.
I can for sure help trying to complete it or draft some idea/structure for it.

**Comment by Lineflyer** [comment]
As squashing is not allowed from Github UI I will close this PR and do changes directly.

**Pull request closed without merging**
