### PR TITLE
Update implemented CacheAttributes according to current OC acodes

### PR DESCRIPTION
**Pull request by bekuno**
one line for every attribute

### CODE REVIEW

**Comment by bekuno** [comment]
the second commit fixes #7671

**Comment by bekuno** [comment]
@following5 @andrixnet
Please check if this is okay as it is in progress through you on the OC page.

**Comment by andrixnet** [comment]
According to https://github.com/cgeo/cgeo/tree/master/main/project/attributes readme.txt, `iconlist.txt` must be edited, graphics added and then some scripts run to make the conversions and generate contents for several files, including `CacheAttributes.java`.

I scheduled myself for next monday to start working on exactly this based on recommendations received from c:geo developer team. 
**At least concerning `CacheAttributes.java` looks like you are ahead of me :-)**  Thanks

While some details are still under some discussion, the ACODE changes are additions and some internal proper correspondancy matches.

**Comment by following5** [comment]
>Please check if this is okay as it is in progress through you on the OC page.

Support for multiple assignment is missing, as well as inc = 0 support. Multiple OC attributes can map the the same GC attribute. E.g.

* OC A39 = GC 13 / inc 1
* OC A40 = GC 13 / inc 0
* OC A73 = GC 13 / inc 0

Best practice would be that c:geo does not maintain an own OC-to-GC attribute mapping table, but uses the information provided by OKAPI. See the `gc_equivs` field returned by [services/attrs/attribute](https://opencaching.pl/okapi/services/attrs/attribute.html). Then you don't need to care about the pending changes by andrixnet; OKAPI will deal with it.

**Comment by following5** [comment]
Using the attribute mapping information provided by OKAPI will also ensure that c:geo GPX export is always compatible to OC GPX export.

**Comment by SammysHP** [comment]
While using GPX we cannot assume that the user is online.

**Comment by following5** [comment]
Best solution then would be to require the user to go online once and cache the attribute mapping table while offline.

The alternative is to duplicate the OC <-> GS attribute mapping as defined in the &lt;groundspeak> elements [here](https://github.com/andrixnet/okapi/blob/master/okapi/services/attrs/attribute-definitions.xml). This is andrixnet's current working branch, which is backward compatible to the attribute mappings that are currently online.

**Comment by bekuno** [comment]
@following5 this mapping is realized in the CacheAttributes file - changed in this PR.
The first Parameter is the groundspeak nr, the second is the OC acode.

**Comment by andrixnet** [comment]
Important note: according to https://github.com/opencaching/okapi/pull/591#discussion_r298559150 A82 as defined at this time must not exist. As such all new ACODES will descend one position. 
Will notify you as documentation is updated. (monday I presume)

**Comment by bekuno** [comment]
The PR is reduced to the core changes in the current OKAPI attributes definition.

He is rebased & squashed & ready to merge.

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by Lineflyer** [comment]
Please feel free to test thismon nightlies or provide some test case to me... I did not follow the related issues and am no expert for the attribute things.

**Comment by bekuno** [comment]
samples: 
A75 - OC6533
A74 - OR00C1

**Pull request merged**
