### PR TITLE
colorAccent at mainActivity

### LINKED ISSUE #8701: colorAccent at mainActivity
@moving-bits implemented the new colorAccent in the logo's orange tone (see #8606) 

So the blue line at the startscreen should be in orange to...

signal-2020-07-29-003927

### PR DESCRIPTION
**Pull request by fm-sys**
fix #8701

### CODE REVIEW

**Comment by fm-sys** [comment]
retest this please

**Comment by fm-sys** [comment]
retest this please

**Comment by moving-bits** [comment]
@fm-sys: If you leave out changes in changelog files, there's a higher chance that you won't get a branch conflict, as the changelog files are changed pretty frequently, leading to conflicting changes.

Therefore standard procedure is that we adapt the changelog files manually after each couple of merges.

**Comment by fm-sys** [comment]
So should I remove my entry in changelog before this gets merged or was it a hint for my next PR's?

**Comment by moving-bits** [comment]
> So should I remove my entry in changelog before this gets merged or was it a hint for my next PR's?

You can do either way: either rebase your PR to current master or remove the change in changelog file - both should resolve the branch conflicts. For upcoming PR it would be easier to not include a change to the changelog files.

**Comment by fm-sys** [comment]
branch conflicts should be solved now

**Comment by moving-bits** [comment]
@fm-sys 
I can't directly see why, but somehow your PR still has branch conflicts. Can you update your local copy to the current state of master branch and rebase your PR to it?

**Comment by fm-sys** [comment]
does it work now? otherwise I will have to create a new PR...

**Comment by moving-bits** [comment]
> does it work now? otherwise I will have to create a new PR...

Looks good so far, at least GitHub is not complaining about any branch conflicts, and Codacy is fine as well. Build for tests is in the queue currently.

**Comment by moving-bits** [comment]
Build is green, let's merge. Thanks @fm-sys for this contribution!

**Pull request merged**
