### PR TITLE
rel to #13152: add relative date filtering for hidden date

### PR DESCRIPTION
**Pull request by eddiemuc**
rel to #13152: add relative date filtering for hidden date.

### CODE REVIEW

**Comment by eddiemuc** [comment]
Failing tests in the CI seem to be unrelated. I will try again

**Comment by eddiemuc** [comment]
Retest this please

**Comment by eddiemuc** [comment]
I have no idea why the tests are failing on CI, and I can't investigate locally due to the issues described here: #13761

**Comment by ztNFny** [comment]
failing tests seem unrelated

**Pull request merged**
