### PR TITLE
fix sheetRemoveFragment crash #15247

### PR DESCRIPTION
**Pull request by ztNFny**
Check FragmentManager state before removing the Fragment AND use commitNow() to force the commit to happen instantly. With commit() it's enqueued and when it finally happens the FragmentManager might already be saved.

### CODE REVIEW

**Review by moving-bits — COMMENTED** [review]
Are multiple commits to the same `FragmentTransaction` actually ok?

[Docs](https://developer.android.com/guide/fragments/transactions) seem to state otherwise: "The final call on each `FragmentTransaction` must commit the transaction. The commit() call signals to the `FragmentManager` that all operations have been added to the transaction."

**Comment by ztNFny** [comment]
> Are multiple commits to the same `FragmentTransaction` actually ok?
> 
> [Docs](https://developer.android.com/guide/fragments/transactions) seem to state otherwise: "The final call on each `FragmentTransaction` must commit the transaction. The commit() call signals to the `FragmentManager` that all operations have been added to the transaction."

Your right, seems there's only 1 commit per transaction. The second check prevents any expectation from being raised.
But probably the key to solving the issue is commitNow() instead of commit(). And if i see it right commitNowAllowingStateLoss() would probably be the ideal solution as that one does the check internally.

**Comment by eddiemuc** [comment]
Fragment commit concept seems kind of broken when you need 4 different kinds of commit to make it work...

If I understand the solution correctly we use the commit with the "lowest implications available" (synchronous and not checking for state loss) and that makes the solution work somehow. Ok for me to go this way, but in some way our usage of fragments seems to be flawed. 

As @ztNFny mentioned already: why is the sheet-removal-method post-delayed anyway?

**Review by eddiemuc — APPROVED** [review]

**Comment by ztNFny** [comment]
> As @ztNFny mentioned already: why is the sheet-removal-method post-delayed anyway?

Without the delay pop-up is removed first, "empty" map is shown for a moment, only the CacheDetailsActivity starts.

I think the "proper" way would be merging Popup amd Details into 1 activity, but that's a big rewrite.

**Comment by moving-bits** [comment]
This fix needs to go to `release`. I'll try to retarget this PR using GitHub.

**Comment by moving-bits** [comment]
Ok, retargeting does not work - too many differences. @ztNFny: Do you want to create a new PR using `release` as base, or shall I step in?

**Comment by ztNFny** [comment]
Please do, i won't be able for a few days.

**Comment by moving-bits** [comment]
> Please do, i won't be able for a few days.

done with #15314

**Comment by moving-bits** [comment]
superseded by #15314, so let's close here

**Pull request closed without merging**
