### PR TITLE
adjust event time recognition

### PR DESCRIPTION
**Pull request by ztNFny**
adjusts the regexp to work for all languages and adds a additional try-catch to avoid issues on furture website changes

### CODE REVIEW

**Review by eddiemuc — APPROVED** [review]
lgtm

**Comment by ztNFny** [comment]
@eddiemuc could you please rebase master?

**Comment by moving-bits** [comment]
I've merged `release` to `master` now, will build a new "nightly" then

**Comment by bekuno** [comment]
Besides the mc2/mc3/mc4 tag there is also a script block with the event date time details, e.g.
~~~
<script type="text/javascript">
//<![CDATA[
var isLoggedIn = true;
var eventCacheData = {
start: new Date(2024, 10-1, 27, 16, 00)
, end: new Date(2024, 10-1, 27, 16, 30)
, title: 'Sommerabschluss'
, description: 'https://www.geocaching.com/geocache/GCAZ3HM'
, location: '52.442517, 13.29505 (http://coord.info/GCAZ3HM)'
};
~~~
In this way no DT format check is necessary.

**Comment by moving-bits** [comment]
Do we want to implement @bekuno's suggestion yet, or leave it as is for the time being?

If no one opposes I will create a new bugfix release from current state of `release` tonight.

**Pull request merged**
