### PR TITLE
Add "none"-entry to routing-profiles-selection

### PR DESCRIPTION
**Pull request by murggel**
## Description

Once you selected a profile for the user-defined profiles 1 or 2, you can't get rid of it easily (go to the settings and delete the key).

This PR adds an entry "(none)" to the profile-selection-list (like for the launch-buttons)

### CODE REVIEW

**Comment by murggel** [comment]
Retest this please

**Comment by ztNFny** [comment]
Retest this please

**Comment by moving-bits** [comment]
There's a CheckStyle error marking this build as red: wrong order for `import java.util.ArrayList;` import in `PreferenceNavigationFragment.java`

**Comment by murggel** [comment]
I will look into it

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
