### PR TITLE
fix #6805 android-gradle-3.0

### LINKED ISSUE #6805: android-gradle 3.0
The android-gradle plugin has been updated to 3.0. There are several breaking changes in the gradle build script. I'm preparing a pull request. This issue is mostly to make every developer aware that Android Studio must be updated to 3.0 also when that PR is merged. Otherwise your IDE will not work correctly.

You can already update Android Studio now, you don't need to wait until the PR is merged.

### PR DESCRIPTION
**Pull request by Bananeweizen**
This requires to use Android Studio 3.0. You may also need to
rere-authenticate emulator/device debugging settings.

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Retest this please

**Comment by kumy** [comment]
@Bananeweizen New build tools should be added to the docker image, see branch `v2` https://github.com/cgeo/cgeo-executor/blob/v2/android-packages ; and images rebuilt.

**Comment by kumy** [comment]
Retest this please (docker images updated)

**Comment by kumy** [comment]
@Bananeweizen `cgeo-basic-debug.apk` doesn't seems to be generated, any idea?

**Comment by Bananeweizen** [comment]
That file is (and was) always renamed to not include "-basic" in the name, since it is our "default" output. However, the generation of these names has changed a lot, and I have already modified all the variant and flavour handling. Since that step is not executed locally, I was not aware of that error. I will check if we can parameterize the dexCount, or I will just skip it for the time being.

**Comment by Bananeweizen** [comment]
Retest this please

**Comment by pstorch** [comment]
Just a small feedback from me. It works locally with AS 3.0 and also via command line `./gradlew testDebug`. :+1:

**Comment by Bananeweizen** [comment]
So are we ready for merging? I did not yet merge, since I was not able to really follow the last weeks and did not want to interrupt any ongoing release.

**Comment by pstorch** [comment]
> So are we ready for merging? 

Good question. 
Technically I would say yes. From the release planning point of view I'm not sure. 
There is a strong demand to only include the absolute necessary fixes in `release`. And I guess we need another release shortly after with fixes already merged to `master`. Because of that I would be cautious with bigger changes in master. At least the new logging page and gmaps v2 should wait. I don't know the impact of this gradle v3 change. Maybe it's ok.

**Comment by pstorch** [comment]
@S-Bartfast as you are the most active developer right now, I ask you: would this be ok for you in master? You need to be on gradle v3 locally (comes with Android Studio v3). If this is not the case and you would be forced to upgrade first, then we'll better wait until the next release.

**Comment by S-Bartfast** [comment]
I'm currently only running version 2.3.3 of Android Studio (in fact I didn't even realise V3 was out :blush:).
I'll be more than happy to upgrade though, in fact I think it even sounds like fun 🙂.

Download the Canary (version 3.1) now...

**Comment by pstorch** [comment]
@S-Bartfast ok, then I'll wait for your feedback, if it works for you. If successful we can merge it.

**Comment by S-Bartfast** [comment]
I've been trying to upgrade to Android Studio 3 for a few days but can't get Gradle to synchronise.

My current issue seems to be with `'apply plugin: 'com.gradle.build-scan''`.

Specifically I'm getting this error im my log:
>`Caused by: java.lang.NoClassDefFoundError: com/gradle/scan/plugin/internal/a/j/b`

Any idea that that's about?
Been trying to Google but no luck yet.

**Comment by pstorch** [comment]
Is this error only in Android Studio or also on the command line?
If only in AS, maybe you can try to build it via command line. This helped me sometimes to fix such problems: `./gradlew testDebug`

**Comment by Bananeweizen** [comment]
build-scan is basically a "built-in" plugin of gradle. Therefore that seems ver fishy. Are you surely using the gradle version that is mentioned in the checked-in gradle-wrapper.properties?

**Comment by S-Bartfast** [comment]
I believe so:

image

Under "Project Structure" my Gradle version is "4.4".
In "gradle-wrapper.properties" it says:
>`distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-4.4-20171031235950+0000-all.zip`

**Comment by S-Bartfast** [comment]
>Is this error only in Android Studio or also on the command line?

Same error on the command line:
image

**Comment by pstorch** [comment]
My gradle version is `4.2.1`.
Maybe Android Studio Canary (version 3.1) is a bit too new?

**Comment by pstorch** [comment]
@Bananeweizen there is a conflict now, because of your other commit 8f423c7282a8c54bb7ee0f63e95640f9cee8ce59

**Comment by pstorch** [comment]
Hi, I would like to see this merged. Besides the small conflict, is there anything blocking us from doing so?

**Pull request merged**
