### PR TITLE
fix event time yet again

### PR DESCRIPTION
**Pull request by ztNFny**

### CODE REVIEW

**Comment by ztNFny** [comment]
I don't have access to my IDE (and won't for a few days). Can someone please test this with the event from https://github.com/cgeo/cgeo/issues/16391 and GC website set to languages EN, ES, DE? And also an event at 00:00 with the 3 languages and one with some "normal" time?

**Review by moving-bits — CHANGES_REQUESTED** [review]
Thanks for diving into this!

I did a short test with GCB0PWB and time zone set to "UTC+00:00 Dublin, ..." as is given in the related issue:

With web page language set to English, the PR seems to work for this cache, but it breaks when language is set to Spanish or German. 00:00-13:00 is being shown as event time in those cases.

**Comment by ztNFny** [comment]
back in front of the PC - I hope I found all the potential problems now ...

**Review by moving-bits — CHANGES_REQUESTED** [review]
I've tested with three different types of events (starting at 00:00, 12:00 and 15:30) in three languages (EN, ES, DE) and different time zones - found no problems so far.

Just a small Checkstyle warning left: https://ci.cgeo.org/job/cgeo-CI_PR-build/10347/checkstyleResult/new/

**Comment by ztNFny** [comment]
> I've tested with three different types of events (starting at 00:00, 12:00 and 15:30) in three languages (EN, ES, DE) and different time zones - found no problems so far.
> 
> Just a small Checkstyle warning left: https://ci.cgeo.org/job/cgeo-CI_PR-build/10347/checkstyleResult/new/

fixed

**Pull request merged**
