### PR TITLE
WIP - resolve left-overs from combined D/T filter

### PR DESCRIPTION
**Pull request by murggel**
## Description

fix non-functional PR-review-comments for the combined D/T filter (see comment https://github.com/cgeo/cgeo/pull/11296#discussion_r676138113)

* add method to get subConfig from ExpressionConfig
* use String-constant
* use text_label-style

## Related issues

rel #11180

### CODE REVIEW

**Comment by murggel** [comment]
still in progress

**Review by eddiemuc — APPROVED** [review]
Looks good imho. You even added a unit test for expressionconfig, many thanks!

I would merge but the PR is still in Draft state. Is there a reason for that?

**Comment by murggel** [comment]
It was late yesterday and I did not know if the CI would be green,
And I thought of waiting, if I could add outcomings for #11331.
But that should probably go in a different PR.

**Comment by eddiemuc** [comment]
Imho you don't have to set a PR to draft just because you don't know the outcome of a CI build yet (I won't merge a PR with red CI outcome anyway). Usually when a PR is in Draft I conclude that the owner still wants to work on it.

**Comment by murggel** [comment]
That was my intention yesterday evening and I forgot to set it on review in time when I finished.
You were too fast for me 😉

**Pull request merged**
