### PR TITLE
fix #10730 Lint error on CI = BUILD FAILED, but at the end SUCCESS

### LINKED ISSUE #10730: Lint error on CI = BUILD FAILED, but at the end SUCCESS
## Bug description 
If a build failed, then the final state should be ERROR.
Here we have a failed build for an lint error, bur state SUCCESS.

### Steps to reproduce the problem
see https://ci.cgeo.org/job/cgeo%20pull%20request/5894/console
see https://ci.cgeo.org/job/cgeo%20pull%20request/5833/console
~~~
> Task :main:lintBasicDebug FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':main:lintBasicDebug'.
> Lint found errors in the project; aborting build.
...
BUILD FAILED in 5m 13s
....
Finished: SUCCESS
~~~

### PR DESCRIPTION
**Pull request by xmichele**
reproduce the use case to test

### CODE REVIEW

**Comment by Lineflyer** [comment]
OK to test

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
@xmichele 
Thanks for your contribution, but AFAICS the `Jenkinsfile` is currently not evaluated on our CI.
It seems to have been created for experimental tests of pipeline builds, which are not used by now.

@kumy 
AFAIR a change similar to this proposed change has been implemented on the script used on our CI for PR/commit builds already in the past weeks. Correct?

Anyway this PR brought me back onto the track of taking another round to test the pipelined builds.
@xmichele If you are interested in helping with this or you have some more info about using such `Jenkinsfile` and the workflow of pipelines feel free to take a look into #6587

**Comment by Lineflyer** [comment]
@xmichele As mentioned in above posting I am trying out to enable pipelines and make use of it.
Modifying the `gradlew` will still not be the best way though (as mentioned in a comment above).

I am still in a learning phase for those pipelines. Feel free to check it out if interested but I will close this PR for now, as we solved the problem in our manual build and I assume in pipelines we would not have this problem of wrong passed builds anyway.

**Comment by xmichele** [comment]
Ok, thanks!
Fell free to notify me about new issues or discussions about pipelines where I can help :)

**Pull request closed without merging**
