### PR TITLE
BRouter integration

### PR DESCRIPTION
**Pull request by moving-bits**
(needed to restart from scratch. Somewhere during the Codacy/CheckStyle fixes in #10156 I've broken something, which prevents integrated BRouter from routing at all)

This is a basic integrated version of BRouter:
- import the original BRouter files
- packaged them into appropriate folders / packages
- some basic (and mostly automated) reformatting - both Codacy and CheckStyle will complain a lot here
- connected c:geo and internal BRouter

It's already a working version: c:geo is now connecting to this internal BRouter variant and doing actual routing (provided that ~`*.brf`, `lookups.dat` and~ `*.rd5` files are in the places expected by this internal BRouter version).
Edit: `*.brf` and `lookups.dat` get generated automatically meanwhile, so the only files you have to add manually are the routing tile data files `*.rd5`. This will be solved as soon as the tile downloader is integrated and activated.)

P.S.: Ok, this time I started with 1703 messages from Codacy and 2421 from CheckStyle, compared to app. 19000 each last time... :-)

With further commits I'll do either optimizations (removing unused BRouter code), solving some Codacy/CheckStyle complaints or implement more of the missing things from the project's todo-list.

### CODE REVIEW

**Comment by moving-bits** [comment]
This PR is down from app. 19.000 Cadacy / CheckStyle messages each to 153 Codacy and 344 CheckStyle. For some of the open issues fixing them breaks the BRouter codec (have tried it...), other will be replaced by refactoring to SAF anyway, so we agreed upon merging this anyway, doing the last open steps for SAF migration, and continue trying to fix the remaining issues then (https://github.com/cgeo/cgeo/pull/10156#issuecomment-800845992).

Next steps after merging this PR will be #10175, #10176 and merging #10085.

**Comment by fm-sys** [comment]
Tests are failing for all other PR's coursed by the new BRouter code (see #10270 for example). I don't know if future steps need to be done to get the light back to green...

**Comment by moving-bits** [comment]
Yeah, have seen that (and merged #10270 anyway, because the only errors are coming from the BRouter integration). Don't know if we need to do immediate action (like creating some sort of "ignore" file), or if upcoming builds recognize that those are "old" messages not introduced by the new PR, and therefore not break the build because of it. Let's keep an eye on it.

**Comment by eddiemuc** [comment]
I am confused. Why was the non-compliant BRouter code merged to master in the first place? I thought we agreed to make an own feature branch instead (like we did with storage_framework) until it is master-ready

**Comment by moving-bits** [comment]
Hm, may be a misunderstanding on my side. I thought the parallel branch was due to SAF still being on `master` at that time, and with having a fresh `master` merging to `master` would be fine. Especially since testing those changes on `master` is way easier than on a separate branch (as we had experienced with the SAF branch).

**Comment by eddiemuc** [comment]
@moving-bits it is in any case not a good idea imho to merge stuff to master which breaks the build. I am trying to fix this in #10273

**Comment by fm-sys** [comment]
I think `master` branch is fine **as long as we really concentrate** on bringing BRouter into production state in a reasonable time. Otherwise it would indeed be very bad if we have not working code at `master` but no time/interest to continue development of this functionality...

**Comment by eddiemuc** [comment]
@moving-bits , @fm-sys : as I said many times, in my opinion the master branch must **always** be green with regards to CI - except in very special emergency error situations (which this is not). It must never occur that PRs from unrelated features fail due to stuff carelessly merged there. If we start once to not care about green master any more it will degrade very quickly.

Experiments and red builds can be done on feature branches, this is what they are for. If really bad code must be used in master then suppressions must be used, but the build must stay green.

As an example, in the "windschatten" of the checkstyle problems I just found that there was already a new lint error introduced. This would have failed all successing builds too.

**Comment by fm-sys** [comment]
> @moving-bits , @fm-sys : as I said many times, in my opinion the master branch must always be green with regards to CI

Totally agree. My comment above was more about if it's ok to keep the BRouter code in current state on `master` at all or if a revert is necessary. But I would guess that the work is doable until next feature release.

**Comment by moving-bits** [comment]
> I think `master` branch is fine **as long as we really concentrate** on bringing BRouter into production state in a reasonable time. 

Agreed. I've brought Codacy/CheckStyle numbers for BRouter down to the current numbers, while checking routing functionality numerous times along the way to not break the actual code by applying coding style fixes. For the remaining issues I'm sort of stuck, but for sure very willing to help with them, if someone shows me how to tackle them.

> Otherwise it would indeed be very bad if we have not working code at `master` 

Currently it should be "Not working" in terms of coding style compliance only, not in terms of "routing functionality" or "breaking some other c:geo functionality".

> but no time/interest to continue development of this functionality...

Indeed. But if so, we wouldn't have integrated BRouter code at all in the first place.

**Pull request merged**
