### PR TITLE
move to gradle 7

### PR DESCRIPTION
**Pull request by bekuno**
## Description

The update of AS to 2020.3.1 is possible without update of gradle/AGP.
This PR should merged after the core team updated AS.

With AS 2020.3.1 we can use gradle 7 and AGP 7.
Details:
- update gradle 6.8.3 to 7.2
- update AGP 4.2.1 to 7.0.3
- Follow up:
  - versions plugin needs therefore update 0.38.0 to 0.39.0
  - similar to AGP: aapt2-proto:4.2.1-7147631 to aapt2-proto:7.0.3-7396180
  - add new lint rule checkDependencies true
  - check - checkstyle relation must be ordered

Additional:
- remove lint option disable 'NonConstantResourceId', as the related PR are finished
- add proguard rules related to OkHttp (planned there for a later release)

## Related issues

prerequisite #11352
supersedes #11500
supersedes #11501

## Additional context

Also WhereYouGo works with AS 2020.3.1 with the current gradle/AGP configuration.

### CODE REVIEW

**Comment by bekuno** [comment]
The additional part "remove lint option disable 'NonConstantResourceId', as the related PR are finished" is now moved to PR #11580.

The additional part "add proguard rules related to OkHttp (planned there for a later release)" is now moved to PR #11581.

**Comment by bekuno** [comment]
Retest this please

**Comment by mucek4** [comment]
Retest this please

**Comment by mucek4** [comment]
Retest this please

**Comment by mucek4** [comment]
Retest this please

**Comment by Lineflyer** [comment]
retest this please

**Comment by mucek4** [comment]
Executor 4 is returned to old image, as it didn't work with new one. Next week I get new powerfull computer for testing, where building new images will be faster. I'll try to put some effort into it.

**Comment by Lineflyer** [comment]
retest this please

**Comment by mucek4** [comment]
retest this please

**Comment by mucek4** [comment]
retest this please

**Comment by bekuno** [comment]
looks that rebasing did not that what it should  do :-(

**Comment by Narrat** [comment]
It kinda looks like a merge instead of a rebase. Or used a wrong branch

**Comment by bekuno** [comment]
replaced by  #12307

**Pull request closed without merging**
