### PR TITLE
fix #12947: add setting to manipulate mapsforge scaling settings

### LINKED ISSUE #12947: Introduce Resize Factors for map font/lines/symbols
### Tell us your idea!

In OSM map elements, esp. text is quite hard to read (i. e. really small) on high resolution displays, esp. if you use Elevate5 as map theme.  Therefore, I have written a script which increases fonts, lines and symbols by a configurable factor, which massively increases usability.

The other day I learned two things:
1. I am not the only one with this "problem". 
2. Locus has a setting for this, in fact, to increase all map elements by a configurable factor ...

... what gave me the idea that c:geo could perhaps offer this functionality, too.  ;)

### What solution would you suggest?

From my experience, it turned out to be best to have three factors:

1. Font Size
2. Line Width
3. Symbol Size

... as in fact I like the theme best, if fonts are increased to 160, lines to 120 and symbols to 130 percent,
while my teammate prefers F140/L120/S110 and a friend of ours even wanted to have F180/L120/S130.
Although my script can create all three in one go, life would be way easier, if c:geo would support to do this itself.  ;)

### Is there an alternative?

Just write yourself a script to increase sizes ...  ;)

### Additional Information

As an example here a comparison between original (in fact close to unreadable) vs. "my" F160, L120 S130:

Current Font 160 Lines 120 Symbols 130

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #12947: add setting to manipulate mapsforge scaling settings

### CODE REVIEW

**Comment by eddiemuc** [comment]
This PR will add experimental  functionality for DEVELOPMENT and NIGHTLY only!

It will add the following setting in the map theme options dialog:

image

The setting allows to enter up to three float or percentage values separated by `:`. If given those values will be filled into the following mapsforge scaling options:
* User Scaling: a general scaling factor which up- or downscales the whole map (technically by manipulating the tile size in pixels). This will influence storke width, text sizes and symbol sizes alike
* Text Size scaling: a scaling factor for text size alone (will be applied on top of user scaling)
* Symbol size scaling: a scaling factor fort symbols aline (will be applied on top of user scaling)

For example, given a value of `100%:200%:500%`, the map will look something like this:

image

**Comment by eddiemuc** [comment]
retest this please

**Comment by eddiemuc** [comment]
PR is now ready for merge:

image

**Comment by moving-bits** [comment]
> PR is now ready for merge:

Thanks for implementing this nice feature, looks good!

Just a tiny note: Do you mean "scale symbol sizes" or "scale symbols"?

**Comment by eddiemuc** [comment]
> Just a tiny note: Do you mean "scale symbol sizes" or "scale symbols"?

Ah, I will correct this. Thanks for asking.

**Comment by eddiemuc** [comment]
Update: allow scaling settings also for default theme, make percentage values selectable only every 10%

**Pull request merged**
