### PR TITLE
Search for coordinates: Show direction and distance to target and not to current position

### PR DESCRIPTION
**Pull request by murggel**
## Description

Sorts the result of the search for target-coordinates according to the target-coordinates and not according to the current coordinates.

## Related issues

rel #15618

### CODE REVIEW

**Comment by murggel** [comment]
Feel free to discuss:
What distance-value does the user expects? The one to the searched location or to the current location?
I would prefer the distance to the target coords, because that is the interesting value for me, not the distance from my current location and it would make the sorting distance "visible".

**Comment by murggel** [comment]
I tried it with italic - but the difference is not really visible

**Comment by fm-sys** [comment]
I think the main problem is that the tiny compass is showing the direction from the current position (at least it looks like that) while the distance is based on the target coords. Maybe hiding the compass in these cases?

**Comment by murggel** [comment]
No - the compass shows also the direction from the target coords to the specific cache.

I will provide two screenshots, one with current implementation and one with the new one...

**Comment by murggel** [comment]
|current implementation|new implementation|
|---|---|
|||

**Comment by murggel** [comment]
Just found out, that mapping the list, the target coordinates are not shown as cross...
But this is a different topic...

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Comment by moving-bits** [comment]
retest this please

**Pull request merged**
