### PR TITLE
Clean up old crowdin scripts

### PR DESCRIPTION
**Pull request by Lineflyer**
Although these scripts have made good work in the past, I think we can remove them now.
In case we might need anything, they are still in the git version history.

### CODE REVIEW

**Comment by bekuno** [comment]
I would not remove the helper scripts in project/localization.
They are helpfull to check if we have unnecessary strings, e.g. deleted in the code.

**Comment by Lineflyer** [comment]
> They are helpfull to check if we have unnecessary strings, e.g. deleted in the code.

Isn't this covered in our lint checks?
It should be AFAIR and once they are deleted from the source, crowdin will remove them from all localization's.

**Comment by bekuno** [comment]
I

> Isn't this covered in our lint checks?

Will check it the next days.

**Comment by bekuno** [comment]
Compiler/AS and the basic lint check are able to find such issues.

**Pull request merged**
