### PR TITLE
Remove deprecated GoogleApiClient connection to Fused Location Provider

### PR DESCRIPTION
**Pull request by jonas-koeritz**
Simplified LocationProvider code to not rely on deprecated GoogleApiClient anymore. Deleted boilerplate code related to GoogleApiClient connection.

### CODE REVIEW

**Comment by Lineflyer** [comment]
Precondition for #10045 ?
Thanks @jonas-koeritz 
Review request to @bekuno

**Comment by moving-bits** [comment]
@bekuno
Do you have a chance to cross-check this PR wrt to dependencies etc.?

**Comment by bekuno** [comment]
> 
> 
> @bekuno
> Do you have a chance to cross-check this PR wrt to dependencies etc.?

Yes I had some time to check the code and compared with the Android documentation.
All changes are looking good.
But as the old implementation is other than the samples in the Android documentation I am not sure if there is no side effect or additional needed implementation. 

The change needs tests, which I did not have done yet.

**Comment by Lineflyer** [comment]
@samueltardieu AFAIR you authored the fused location provider. Can you take a look on this change, which seems required due to deprecation?

**Comment by samueltardieu** [comment]
I don't have the setup to test the patch, but it looks ok for me.

**Review by samueltardieu — APPROVED** [review]
Looks good to me

**Pull request merged**
