### PR TITLE
Read and write GSAK-Extension for DNF and visitedDate

### PR DESCRIPTION
**Pull request by murggel**
## Description

Support DNF in exported GPX (use existing GSAK-extension-field)
Also export visited date

## Related issues

#9908

### CODE REVIEW

**Comment by murggel** [comment]
@moving-bits where do I have to add the fix #xxx so that the issue will be closed automatically?  
Putting it in the PR-description does appearently not work.
Or does that only work for team-members, which would be fine for me...

**Comment by moving-bits** [comment]
There are two ways:
- You can put it into the commit message, e. g. append a "(fix #12345)"
- or you can use the "linked issues" menu you can see at the right, and select the issue you want to auto-close on merging

Linked messages will be closed only when merged to `master` branches, so if you prepare a PR for `release`, the linked issue will not be closed directly, but still automatically as soon as `release` is merged back to `master` (which is something mostly @Lineflyer and I are doing on a regular basis).

**Comment by fm-sys** [comment]
In the current PR description the "fix" is missing in front of the issue id. And closing words in the PR description are only working if the PR targets to master. 



>     * or you can use the "linked issues" menu you can see at the right, and select the issue you want to auto-close on merging

This is only available for team members, but putting it in the commit message does work best (also for `release`).

**Comment by murggel** [comment]
Thanks guys, will try ot the next time

**Comment by bekuno** [comment]
Additionally to the words of @fm-sys , a link in the referenced issue is then automatic created.

**Pull request merged**
