### PR TITLE
fix #14579: add difficulty terrain matrix filter

### LINKED ISSUE #14579: Filter for missing T/D in 81er Matrix
### Tell us your idea!

It would be very nice to have a filter which shows all caches which help to fill the 81er matrix one more time. 

### What solution would you suggest?

I could be a checkbox in the T/D filter, like on the Website.

### Is there an alternative?

_No response_

### Additional Information

The website have this filter too, so may that can be used?

### PR DESCRIPTION
**Pull request by eddiemuc**
fix #14579: add difficulty terrain matrix filter

image

### CODE REVIEW

**Comment by eddiemuc** [comment]
retest this please

**Comment by ztNFny** [comment]
Shouldn't this replace the existing D/T filter? I don't see a point in having 2 filter GUIs for the same criteria.

**Comment by eddiemuc** [comment]
> Shouldn't this replace the existing D/T filter? I don't see a point in having 2 filter GUIs for the same criteria.

I would definitely leave the old filter GUI for the "simple" filter view - the matrix is far too complex for common users IMHO. We could however think about removing the simple view from the "advanced" mode or present a combined view (which would then get more complex of course). Maybe something to discuss in team meeting?

**Comment by ztNFny** [comment]
Is it more complex though? From looking at the screenshot I expect selecting "T4, D*" is one click:
image
That's actually less clicks than the old sliders where you had to set both min and max.

Showing T4-T5 would be 3 clicks now, more clicks, but not "complex" imho. I feel like the matrix-view makes it easier to get a WYSIWYG feeling, making it less complex.

Let's take it for the meeting.

**Comment by eddiemuc** [comment]
There's another problem: unlike the "simple" D/T filter, the "matrix" filter is not supported by most geocaching servers for online filtering. AFAIK just gc.com supports the online search for D-t-combinations; okapi for example just allows separate (range) search for difficulty and terrain.

**Comment by eddiemuc** [comment]
Current screenshots after updates with feedback (screenshot design has now with material3 look due to parallel changes, but this is unrelated to this PR):

image

**Comment by eddiemuc** [comment]
As discussed: remove "online" gc.com option for now and shorten button text

**Pull request merged**
