### PR TITLE
format waypoint type spinner (fix #10974)

### LINKED ISSUE #10974: WP type dropdown selector looks strange
No big issue, but to me the waypoint type selector when creating/editing a waypoint looks kind of narrow.
I mean the selector where you can choose the type of waypoint, e.g. "Reference Point", "Final", "Trailhead", etc.

Maybe we could give it the same room as the textfields above and below?

Screenshot_20210620-222432_cgeo

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
- applies more room around waypoint type spinner
- apply dialog background to spinner popup to be distinguishable from background in dark mode

image.image.image

### CODE REVIEW

**Comment by fm-sys** [comment]
Shouldn't we apply the spinners `popupBackground` to all places in c:geo (e.g. list selector, text input suggestions, ...) via our theme instead?

**Comment by moving-bits** [comment]
Found a way to set the background via theme. Margins still need to be set manually, though.

**Comment by eddiemuc** [comment]
Probably an own issue, but I would like it if we had a general style for spinners across c:geo, of course a nice one done with material.io. right now we have very different spinner/spinner-like controls across whole c:geo e.g. waypoint-type-select/image-scale-select vs. Log-type-select (in offline log)

**Comment by moving-bits** [comment]
I have not found a material.io component for it, so we probably need to create our own component to achieve that.

**Pull request merged**
