### PR TITLE
Google Maps v2

### PR DESCRIPTION
**Pull request by matej116**
I am presenting you my effort to refactor long time deprecated google maps v1 (for which developers can not obtain keys) to google maps v2. It is a lot of change and not all of them are compatible with NewMap (or how do you called the new experimental implementation of Mapsforge v2 a CGeoMap), but I beleive it is really time to migrate to Google Maps V2. I know that this code is not the best one, but I now use this for couple of weeks and it is working fine (except the DistanceDrawer, which is not fully tested yet). I do not own premium account, so I did not run the tests. Could you please review it and comment it? I have a couple of next changes, which is based on this, so I need to know if it can be merged or it is not compatible with current codebase.

### CODE REVIEW

**Comment by samueltardieu** [comment]
ok to test

**Comment by samueltardieu** [comment]
I have also been working on a v2 implementation for a few days. My approach is completely different, in that:
- My v2 map does not reuse the previous "generic" maps framework (and NewMap doesn't either).
- It tries to get useful (and probably common) functionalities out in helpers so that they can be used by other maps implementation without having them commit to use a particular framework either.

The previous framework contains numerous bugs related to concurrent events and parallelism and should be either fixed or destroyed (my preferred solution).

At this stage, I've enabled the tests so that you can get feedback from the CI server if you want to go on working on your implementation and cleaning it, but I'd like to get a chance to compare them first before committing to either choice.

**Comment by matej116** [comment]
Thanks for comment, I just wanted to make the c:geo work with google maps and the only way was to implement Google Maps API v2. And i have noticed the NewMap after a few days of work. I agree that the previous framework is bad and should be destroyed, unfortunately I have built the google maps v2 on it :(.  I certainly do not want to merge it into master now, I just wanted to get some feedback since it is my first contribution to open source. Could you please compare it to your implementation, either send me a link, if you have it somewhere?

**Comment by samueltardieu** [comment]
I'll share it as soon as it is complete and polished enough for others to see.

**Comment by matej116** [comment]
I know this implementation is based on old and wrong abstraction of map, but it is at least working. Could please someone tell me, if it is going to be merged to master or at least some opinion about it? I think that implementation of Google Maps v2 is necessery to allow new developers to participate on c:geo development. What should I (or some else) do for this to be merged or at least reviewed? Or is this piece of code just useless and it will be never merged and it is better to wait for better implementation? Please let me know :)

**Comment by samueltardieu** [comment]
We like new contributions. We even have a page in our Wiki to welcome new developers: https://github.com/cgeo/cgeo/wiki/Join-the-team. However, as you can read in this page, we emphasize the fact that it is important to talk to the team before implementing a feature in case someone else is already working on it. The goal is precisely to avoid situations like that where someone from the team (or working with the team) is already working on a feature, and someone else comes with this feature implemented in a totally different way and expect it to be merged just because some time has been spent on it.

It does not mean that your contribution is not useful or not wanted: however, accepting such a large change with the risk it entails in terms of application stability, devote resources to maintain it, only to replace all the code with some new code in a few weeks is probably not the best long-term strategy.

One of our responsibility is to decrease the technical debt. Patching older code to add functionality is not always best. Sometimes, some parts need to be cleaned up even though it means more work to do. This is the case with the maps code, and the rewrite of the maps v2 I am doing intends to give the right tools for other maps implementations to use (such as the MapsForge one).

So I do not know if someone will review and try and merge your code right now. Maybe the new implementation will be unsuccessful, or will not deemed interesting enough by the rest of the team. In this case, yours will certainly be considered again!

**Comment by matej116** [comment]
I really appreciate your mesaage, I am ok with this not being merged, I just felt like It is good idea to share my effort and get some feedback. I understand and agree that if there is someone else working on same task, it is not a good idea to make this pull request and request  a merge.

I agree that this is a big diff and the risk of introducing more bugs is high. So I guess the best option now or either leave this pull request in "do not merge" state (in case it would be needed in the future, maybe) or remove it, which is probably better idea?

Can I see your effort of implementing Google maps v2? I have met some problems with the Google maps API v2 and I would like to share how I solved them (mainly the fact, that adding more markers to map is slow and has to be done in main thread) or see another solution. Maybe I could be helpful and I am just curious how others solved this :-).

And I have some other changes (mainly performance or UX things), which I think would be nice to be merged, but I promise I will look at the issues page and the wiki before creating another pull requests.

Thanks again for your patience and explanation in this discussion, I really appreciate it.

**Comment by samueltardieu** [comment]
> the best option now or either leave this pull request in "do not merge" state (in case it would be needed in the future, maybe) or remove it

You can probably leave it open in the current state right now.

> Can I see your effort of implementing Google maps v2?

As I already answered above: (quoting myself)

> I'll share it as soon as it is complete and polished enough for others to see.

**Comment by samueltardieu** [comment]
Since I obviously don't have had (and probably won't have) the time and motivation to work on the v2, I won't stand in the path of merging such an approach.

**Comment by samueltardieu** [comment]
ok to test

**Comment by Lineflyer** [comment]
retest this please

**Comment by pstorch** [comment]
I would like to continue the discussion here. I'm also "late to the party" and not able to get a Google Maps V1 API key anymore. And we have other issues with dependencies to this API upgrade. I would appreciate if we can use it.
I've tested it locally with a new personal V2 API Key and it works so far.

@matej116 are you still interested? If yes, could you rebase your changes on the current master and squash your commits into a single one? Are you aware of any things which don't work yet in comparison to the old V1 implementation? The README should also be updated with instructions for the V2 API key.

**Comment by matej116** [comment]
I am totally interested in it. I have rebased all the commits and sqaushed them. README.md also updated. I am not aware of anything which is not functional, but it is a whole year since I wrote this. Still I can remember I was triying to imlement all original functionality. If anything is not working I will be happy to help to fix it.

**Comment by pstorch** [comment]
@matej116 thanks for the update

I'm thinking about the API in the keys.xml file. I'm not sure, maybe we should have the V2 key under its own name.

@kumy is there only one keys.xml file on the CI server for all branches? If yes I think we have to have two separate keys for google maps V1 and V2. To be able to test V2 in the nightlies and still support V1 in release.

**Comment by Lineflyer** [comment]
Just a suggestion from my side:
While I am curious to test the Google Maps V2 we should merge this only after branching to `release`. Doing so we can bring out latest features (e.g. WP calc) rather soon and have more time to polish maps V2.

**Comment by kumy** [comment]
Yes, only one key.xml file for all builds types.

On October 16, 2017 8:30:54 PM GMT+02:00, Peter Storch <notifications@github.com> wrote:
>@matej116 thanks for the update
>
>I'm thinking about the API in the keys.xml file. I'm not sure, maybe we
>should have the V2 key under its own name.
>
>@kumy is there only one keys.xml file on the CI server for all
>branches? If yes I think we have to have two separate keys for google
>maps V1 and V2. To be able to test V2 in the nightlies and still
>support V1 in release.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/pull/5973#issuecomment-336985848

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pstorch** [comment]
@Lineflyer ok, let's plan the next release. There is some good stuff already waiting for release. And other big changes waiting to be tested in the nightlies.

@matej116 can you change the PR so that the V2 map uses its own key?

**Comment by Lineflyer** [comment]
@matej116 
Sorry for letting this hang on for such a long time.
In order to target new Android versions with c:geo (as we now just managed to raise our target SDK due to Google requirements) we would have to step from Google maps V1 to V2 latest.

Some members of the team seem to be interested to work on this as well. Are you still in for working on this? Would be great.

**Comment by matej116** [comment]
@Lineflyer 
I am not working on it, I am just keeping it updated in my fork by merging master branch into this. I did not have done any changes since last commit in this PR. And I do not have an android phone since then, so I am not using c:geo, either. I can try at least resolve the conflicts to make this mergable, but I am afraid I do not have enough motivation to continue work on this.

**Comment by UniQP** [comment]
@matej116 We decided to move the Google Maps V2 development to a separate branch (so we can create PRs against it). Thank you for your work.

**Pull request merged**
